import type { KnowColdCard, SourceReference } from "@/lib/types";

/**
 * Know Cold, kept deliberately short.
 *
 * Navigation is examined on what you can produce, not what you can recite, so
 * this deck is smaller than the other courses' and every card earns its place
 * by supporting a procedure. Formulas, memory aids, the four triggers for the
 * seconds bug, the tolerances — the things you need in your head while your
 * hands are busy. Nothing here is trivia.
 */

const TG = (chapter: string, eo?: string[]): SourceReference => ({
  document: "Navigation Trainee Guide",
  chapter,
  eo,
});

const C1 = "Introduction to Air Navigation";
const C2 = "Chart Projections, Plotting and Global Timekeeping";
const C3 = "CR-3 Air Navigation Computer";
const C4 = "Airspeeds";
const C5 = "Preflight Winds";
const C6 = "In Flight Winds";
const C7 = "Flight Planning and Conduct";
const APPX = "Appendix A — Tolerances";

export const KNOW_COLD: KnowColdCard[] = [
  /* ---------------- n1 ---------------- */
  {
    id: "nkc-001",
    category: "definition",
    term: "Air navigation",
    body: "Determining geographic position and maintaining the desired direction of an aircraft relative to the surface of the earth.",
    unit: "n1",
    conceptIds: ["nav-definition"],
    source: TG(C1, ["2.330"]),
  },
  {
    id: "nkc-002",
    category: "sequence",
    term: "The four components of DR",
    body: "Position, direction, time, speed. Know any three and the fourth follows.",
    formula: "\\text{Speed} \\times \\text{Time} = \\text{Distance}",
    unit: "n1",
    conceptIds: ["nav-dr-components"],
    source: TG(C1, ["2.332"]),
  },
  {
    id: "nkc-003",
    category: "sequence",
    term: "The three types of navigation",
    body: "Dead reckoning, visual, electronic. Visual and electronic are back-ups; neither relieves you of the plot.",
    unit: "n1",
    conceptIds: ["nav-types", "nav-dead-reckoning"],
    source: TG(C1, ["2.331"]),
  },
  {
    id: "nkc-004",
    category: "aircraft",
    term: "Primary DR instruments",
    body: "Compass for direction and position, clock for time, airspeed indicator for speed.",
    unit: "n1",
    conceptIds: ["nav-primary-instruments"],
    source: TG(C1, ["2.333"]),
  },
  {
    id: "nkc-005",
    category: "aircraft",
    term: "Secondary DR instruments",
    body: "Altimeter and outside air temperature. They give density, which sets true airspeed.",
    unit: "n1",
    conceptIds: ["nav-secondary-instruments"],
    source: TG(C1, ["2.333"]),
  },
  {
    id: "nkc-006",
    category: "trap",
    term: "The stand-by compass",
    body: "Fluid-damped, not gyro-stabilised. Unstable in manoeuvre, but independent of the electrical system.",
    unit: "n1",
    conceptIds: ["nav-standby-compass"],
    source: TG(C1, ["2.333"]),
  },
  {
    id: "nkc-007",
    category: "number",
    term: "Minutes in a degree",
    body: "Sixty. Not the other way round — the exam prints the inversion.",
    unit: "n1",
    conceptIds: ["nav-latitude-longitude"],
    source: TG(C1, ["2.330"]),
  },
  {
    id: "nkc-008",
    category: "trap",
    term: "Writing a position",
    body: "Latitude first, longitude in three digits: 30° 22'N, 087° 19'W.",
    unit: "n1",
    conceptIds: ["nav-latitude-longitude"],
    source: TG(C1, ["2.330"]),
  },

  /* ---------------- n2 ---------------- */
  {
    id: "nkc-009",
    category: "definition",
    term: "Great circle",
    body: "A circle whose plane passes through the earth's centre. The shortest distance between two points, so it saves time and fuel.",
    unit: "n2",
    conceptIds: ["nav-great-circle"],
    source: TG(C2, ["2.334"]),
  },
  {
    id: "nkc-010",
    category: "trap",
    term: "Which lines are great circles",
    body: "All meridians. Of the parallels, only the equator.",
    unit: "n2",
    conceptIds: ["nav-great-circle", "nav-small-circle"],
    source: TG(C2, ["2.334"]),
  },
  {
    id: "nkc-011",
    category: "sequence",
    term: "Lambert conformal characteristics",
    body: "Parallels are equally spaced concentric circles. Meridians are straight lines converging at the poles. Scale is constant. Great circles plot as straight lines.",
    unit: "n2",
    conceptIds: ["nav-lambert"],
    source: TG(C2, ["2.335"]),
  },
  {
    id: "nkc-012",
    category: "number",
    term: "Chart scales",
    body: "TPC 1:500,000, the usual chart for route and checkpoint work. ONC 1:1,000,000, for long-range planning.",
    unit: "n2",
    conceptIds: ["nav-onc-tpc"],
    source: TG(C2, ["2.335"]),
  },
  {
    id: "nkc-013",
    category: "trap",
    term: "Lambert meridians point at TRUE north",
    body: "So every line you draw on the chart is a true direction, and the cockpit is magnetic. Variation is the bridge.",
    unit: "n2",
    conceptIds: ["nav-lambert", "nav-variation-conversion"],
    source: TG(C2, ["2.335"]),
  },

  /* ---------------- n3 ---------------- */
  {
    id: "nkc-014",
    category: "definition",
    term: "Course, heading, track",
    body: "Course is the intended flight path. Heading is where the nose points. Track is the path actually flown.",
    unit: "n3",
    conceptIds: ["nav-course", "nav-heading", "nav-track"],
    source: TG(C2, ["2.336"]),
  },
  {
    id: "nkc-015",
    category: "definition",
    term: "Variation",
    body: "The angular difference between true north and magnetic north from a given position, in degrees east or west.",
    unit: "n3",
    conceptIds: ["nav-variation"],
    source: TG(C2, ["2.337"]),
  },
  {
    id: "nkc-016",
    category: "definition",
    term: "Isogonic line",
    body: "A line joining points of equal variation. Dashed blue on a TPC or ONC, with the value in degrees.",
    unit: "n3",
    conceptIds: ["nav-isogonic"],
    source: TG(C2, ["2.337"]),
  },
  {
    id: "nkc-017",
    category: "equation",
    term: "True to magnetic",
    body: "East is least, and west is best.",
    formula: "MC = TC - E \\qquad MC = TC + W",
    unit: "n3",
    conceptIds: ["nav-variation-conversion"],
    source: TG(C2, ["2.338"]),
  },
  {
    id: "nkc-018",
    category: "trap",
    term: "Plotting a radial",
    body: "A radial is magnetic and the chart is true, so the formula reverses: easterly variation is ADDED.",
    unit: "n3",
    conceptIds: ["nav-variation-conversion", "nav-tacan-fix"],
    source: TG(C2, ["2.338", "4.7"]),
  },
  {
    id: "nkc-019",
    category: "trap",
    term: "Directions run 001 to 360",
    body: "There is no 000. Due north is written 360.",
    unit: "n3",
    conceptIds: ["nav-direction"],
    source: TG(C1, ["2.336"]),
  },
  {
    id: "nkc-020",
    category: "relationship",
    term: "Crab and drift",
    body: "Equal in size, opposite in direction. Drift is what the wind did; crab is what you do about it.",
    unit: "n3",
    conceptIds: ["nav-crab-drift"],
    source: TG(C5, ["4.14"]),
  },

  /* ---------------- n4 ---------------- */
  {
    id: "nkc-021",
    category: "number",
    term: "Degrees to the hour",
    body: "The earth turns 360° in 24 hours: 15° an hour, 24 zones, each centred on a multiple of 15°.",
    unit: "n4",
    conceptIds: ["nav-time-zones"],
    source: TG(C2, ["4.1"]),
  },
  {
    id: "nkc-022",
    category: "equation",
    term: "Zulu conversions",
    body: "Keep the brackets. Subtracting a negative adds.",
    formula: "GMT = LMT - (ZD) \\qquad LMT = GMT + (ZD)",
    unit: "n4",
    conceptIds: ["nav-zulu-conversion"],
    source: TG(C2, ["4.2"]),
  },
  {
    id: "nkc-023",
    category: "sequence",
    term: "Flying a leg across zones",
    body: "Convert the departure to Zulu, add the time en route in Zulu, convert the arrival to local. Never add flight time to a local clock.",
    unit: "n4",
    conceptIds: ["nav-fly-in-zulu"],
    source: TG(C2, ["4.2"]),
  },
  {
    id: "nkc-024",
    category: "trap",
    term: "Zone descriptions are looked up",
    body: "In the IFR en route supplement, after the coordinates. Dividing longitude by 15 fails on political boundaries and daylight saving.",
    unit: "n4",
    conceptIds: ["nav-zone-description"],
    source: TG(C2, ["4.1"]),
  },

  /* ---------------- n5 ---------------- */
  {
    id: "nkc-025",
    category: "trap",
    term: "Plotter versus dividers",
    body: "The plotter measures direction. The dividers measure distance. The distance scale printed on the straightedge is not accurate.",
    unit: "n5",
    conceptIds: ["nav-plotter", "nav-dividers"],
    source: TG(C2, ["4.6"]),
  },
  {
    id: "nkc-026",
    category: "trap",
    term: "The plotter's outer scale is reversed",
    body: "The numbers increase to the LEFT. Bracket the meridian — read both sides — or be ten degrees out.",
    unit: "n5",
    conceptIds: ["nav-plotter", "nav-measuring-direction"],
    source: TG(C2, ["4.6"]),
  },
  {
    id: "nkc-027",
    category: "relationship",
    term: "Which scale to read",
    body: "Grommet on a meridian → the outer scale. Grommet on a parallel → the inner north/south scale.",
    unit: "n5",
    conceptIds: ["nav-measuring-direction", "nav-north-south-scale"],
    source: TG(C2, ["4.6"]),
  },
  {
    id: "nkc-028",
    category: "number",
    term: "One minute, one mile",
    body: "One minute of latitude is one nautical mile; one degree is 60. Measure distance up a meridian, never along a parallel.",
    unit: "n5",
    conceptIds: ["nav-measuring-distance"],
    source: TG(C2, ["4.5"]),
  },
  {
    id: "nkc-029",
    category: "sequence",
    term: "Speed marks",
    body: "A mark every minute. Every five, a longer one on the left of the meridian. Every ten, a longer one still that crosses it.",
    unit: "n5",
    conceptIds: ["nav-speed-marks"],
    source: TG(C2, ["4.3"]),
  },
  {
    id: "nkc-030",
    category: "sequence",
    term: "Measuring a course",
    body: "Estimate. Span the dividers along the line. Lay the straightedge against their points. Slide until the grommet is on a meridian. Read.",
    unit: "n5",
    conceptIds: ["nav-measuring-direction"],
    source: TG(C2, ["4.6"]),
  },
  {
    id: "nkc-031",
    category: "sequence",
    term: "Walking the dividers",
    body: "Set a fixed span — 30 NM works — step it along the line counting in multiples, then close on the remainder.",
    unit: "n5",
    conceptIds: ["nav-walking-dividers"],
    source: TG(C2, ["4.5"]),
  },
  {
    id: "nkc-032",
    category: "trap",
    term: "Head and tail of the #2 needle",
    body: "The head gives the magnetic bearing TO the station. The tail gives the radial you are on.",
    unit: "n5",
    conceptIds: ["nav-needle-head-tail"],
    source: TG(C2, ["4.7"]),
  },

  /* ---------------- n6 ---------------- */
  {
    id: "nkc-033",
    category: "number",
    term: "The three indexes",
    body: "Rate index at 60: one hour. Seconds bug at 36: 3,600 seconds. Unit index at 10: no time in the problem.",
    unit: "n6",
    conceptIds: ["nav-rate-index", "nav-high-speed-index", "nav-unit-index"],
    source: TG(C3, ["4.9", "4.10"]),
  },
  {
    id: "nkc-034",
    category: "sequence",
    term: "When to use the seconds bug",
    body: "Time of five minutes or less. Distance of five miles or less. Speed of 500 kt or more. Seconds anywhere in the estimate, question or answer.",
    unit: "n6",
    conceptIds: ["nav-high-speed-index"],
    source: TG(C3, ["4.9"]),
  },
  {
    id: "nkc-035",
    category: "number",
    term: "What a tick is worth",
    body: "10 to 15: one per tick. 15 to 30: two. 30 to 60: five.",
    unit: "n6",
    conceptIds: ["nav-tick-values"],
    source: TG(C3, ["4.8"]),
  },
  {
    id: "nkc-036",
    category: "trap",
    term: "The floating decimal",
    body: "A printed 21 may be 0.21, 2.1, 21, 210 or 2100. The wheel gives digits; the estimate gives the decimal point.",
    unit: "n6",
    conceptIds: ["nav-floating-decimal"],
    source: TG(C3, ["4.8"]),
  },
  {
    id: "nkc-037",
    category: "equation",
    term: "The rate relationship",
    body: "Speed over the rate index equals distance over time. Swap distance for pounds and it is a fuel problem.",
    formula: "\\frac{\\text{Speed}}{\\text{Rate index}} = \\frac{\\text{Distance}}{\\text{Time}}",
    unit: "n6",
    conceptIds: ["nav-ratio", "nav-fuel-consumption"],
    source: TG(C3, ["4.9", "4.10"]),
  },
  {
    id: "nkc-038",
    category: "equation",
    term: "Fuel conversion",
    body: "Off the unit index, because there is no time in the problem. There are always more pounds than gallons.",
    formula: "\\frac{\\text{Fuel weight}}{1\\text{ gal}} = \\frac{\\text{Total lb}}{\\text{Total gal}}",
    unit: "n6",
    conceptIds: ["nav-fuel-conversion", "nav-unit-index"],
    source: TG(C3, ["4.10"]),
  },
  {
    id: "nkc-039",
    category: "number",
    term: "Rule of 60",
    body: "Groundspeed ÷ 60 is nautical miles per minute. 60 → 1, 300 → 5, 600 → 10.",
    unit: "n6",
    conceptIds: ["nav-rule-of-60"],
    source: TG(C3, ["4.9"]),
  },
  {
    id: "nkc-040",
    category: "number",
    term: "Rule of 6",
    body: "A tenth of groundspeed is the distance covered in six minutes. At 300 kt, 30 NM.",
    unit: "n6",
    conceptIds: ["nav-rule-of-6"],
    source: TG(C3, ["4.9"]),
  },
  {
    id: "nkc-041",
    category: "relationship",
    term: "The hour circle",
    body: "150 on the time scale reads 2:30 beneath it. Read the time scale as seconds and the hour circle reads minutes.",
    unit: "n6",
    conceptIds: ["nav-hour-circle"],
    source: TG(C3, ["4.9"]),
  },

  /* ---------------- n7 ---------------- */
  {
    id: "nkc-042",
    category: "number",
    term: "Standard day",
    body: "29.92 inHg and +15 °C at mean sea level. Lapse rate 2 °C and 1 inHg per 1,000 ft.",
    unit: "n7",
    conceptIds: ["nav-standard-day"],
    source: TG(C4, ["2.339"]),
  },
  {
    id: "nkc-043",
    category: "sequence",
    term: "LAGS",
    body: "Altimeter setting Less than 29.92 → Add. Greater → Subtract. At 1,000 ft per inch.",
    formula: "PA = CA + (29.92 - \\text{setting}) \\times 1000",
    unit: "n7",
    conceptIds: ["nav-pressure-altitude"],
    source: TG(C4, ["2.340"]),
  },
  {
    id: "nkc-044",
    category: "definition",
    term: "The five altitudes",
    body: "Indicated, calibrated, pressure, true, absolute. Pressure altitude is the reference for TAS; true altitude is what chart terrain uses.",
    unit: "n7",
    conceptIds: ["nav-altitude-types"],
    source: TG(C4, ["2.339"]),
  },
  {
    id: "nkc-045",
    category: "sequence",
    term: "The airspeed chain",
    body: "IAS → instrument error → CAS → density → TAS → wind → GS. Only the last step involves wind.",
    unit: "n7",
    conceptIds: ["nav-ias", "nav-cas", "nav-tas", "nav-groundspeed"],
    source: TG(C4, ["2.42", "2.43", "2.45", "2.46"]),
  },
  {
    id: "nkc-046",
    category: "trap",
    term: "High to low, look out below",
    body: "Flying into falling pressure without resetting, the altimeter reads high and you are lower. Low to high, plenty of sky. 0.10 inHg is 100 feet.",
    unit: "n7",
    conceptIds: ["nav-altimeter-errors"],
    source: TG(C4, ["2.339"]),
  },
  {
    id: "nkc-047",
    category: "equation",
    term: "Mach number",
    body: "True airspeed over the local speed of sound. Read from the same CAS-over-altitude setting, with no temperature input.",
    formula: "M = \\frac{TAS}{LSOS}",
    unit: "n7",
    conceptIds: ["nav-mach"],
    source: TG(C4, ["2.341"]),
  },
  {
    id: "nkc-048",
    category: "number",
    term: "Temperature and the altimeter",
    body: "Every 11 °C off the standard lapse rate is a 4% altimeter error. Colder than standard, you are lower than indicated.",
    unit: "n7",
    conceptIds: ["nav-temperature-error"],
    source: TG(C4, ["2.339"]),
  },
  {
    id: "nkc-049",
    category: "number",
    term: "Instrument error limit",
    body: "Above 75 feet of total altimeter error, the aircraft is unsafe for IFR flight. Instrument error cannot be corrected, only noted.",
    unit: "n7",
    conceptIds: ["nav-instrument-error"],
    source: TG(C4, ["2.339"]),
  },

  /* ---------------- n8 ---------------- */
  {
    id: "nkc-050",
    category: "definition",
    term: "The three vectors",
    body: "Air: true heading and TAS. Ground: course or track, and groundspeed. Wind: direction and velocity. Air + wind = ground.",
    unit: "n8",
    conceptIds: ["nav-wind-triangle"],
    source: TG(C5, ["4.14"]),
  },
  {
    id: "nkc-051",
    category: "trap",
    term: "Wind direction is where it comes FROM",
    body: "A 045 wind originates in the north-east. Winds aloft are TRUE; tower winds are magnetic.",
    unit: "n8",
    conceptIds: ["nav-wind-reporting"],
    source: TG(C5, ["4.14"]),
  },
  {
    id: "nkc-052",
    category: "number",
    term: "The ten percent rule",
    body: "A crosswind of 10% of TAS gives about 6° of crab, at any airspeed. 5% → 3°, 15% → 9°.",
    unit: "n8",
    conceptIds: ["nav-ten-percent"],
    source: TG(C5, ["4.15"]),
  },
  {
    id: "nkc-053",
    category: "relationship",
    term: "Quartering analysis",
    body: "Left head: TH < TC, GS < TAS. Right head: TH > TC, GS < TAS. Left tail: TH < TC, GS > TAS. Right tail: TH > TC, GS > TAS.",
    unit: "n8",
    conceptIds: ["nav-quartering"],
    source: TG(C5, ["4.14"]),
  },
  {
    id: "nkc-054",
    category: "trap",
    term: "One wind scale per problem",
    body: "Large 0–80 under 60 knots, small 0–160 at 60 and above. Mixing them is wrong by a factor of two and looks fine.",
    unit: "n8",
    conceptIds: ["nav-wind-scales"],
    source: TG(C5, ["4.15"]),
  },
  {
    id: "nkc-055",
    category: "equation",
    term: "Groundspeed on the CR-3 method",
    body: "GS = TAS ± the head or tail component. The crosswind does not enter it.",
    unit: "n8",
    conceptIds: ["nav-preflight-procedure", "nav-groundspeed"],
    source: TG(C5, ["4.15"]),
  },

  /* ---------------- n9 ---------------- */
  {
    id: "nkc-056",
    category: "trap",
    term: "In flight, TRACK goes at the index",
    body: "Not the course. The ground vector's direction in flight is what actually happened.",
    unit: "n9",
    conceptIds: ["nav-inflight-procedure"],
    source: TG(C6, ["2.343"]),
  },
  {
    id: "nkc-057",
    category: "relationship",
    term: "Estimating the wind in flight",
    body: "GS above TAS is a tailwind. Drifting right means the wind is from the left. All of the big component, half of the small.",
    unit: "n9",
    conceptIds: ["nav-inflight-estimate"],
    source: TG(C6, ["2.343"]),
  },
  {
    id: "nkc-058",
    category: "sequence",
    term: "Point to point",
    body: "Plot both fixes on the grid, circle the destination, connect, rotate the line vertical with the destination above, read the course at the index. The answer is MAGNETIC.",
    unit: "n9",
    conceptIds: ["nav-point-to-point"],
    source: TG(C6, ["2.344"]),
  },
  {
    id: "nkc-059",
    category: "definition",
    term: "Why a fix is enough",
    body: "A fix gives track and groundspeed. With the heading and TAS you flew, that is two sides of the triangle — so the wind is determined.",
    unit: "n9",
    conceptIds: ["nav-inflight-theory"],
    source: TG(C6, ["2.342"]),
  },

  /* ---------------- n10 ---------------- */
  {
    id: "nkc-060",
    category: "trap",
    term: "The jet log's primary purpose",
    body: "Fuel management. Navigation data, timing and crew coordination are all real, and all wrong as answers to that question.",
    unit: "n10",
    conceptIds: ["nav-jet-log"],
    source: TG(C7, ["4.12"]),
  },
  {
    id: "nkc-061",
    category: "sequence",
    term: "The four planning steps",
    body: "Measure courses and distances. Preflight winds for headings and groundspeeds. Groundspeed for ETE. ETE and fuel flow for leg fuel.",
    unit: "n10",
    conceptIds: ["nav-planning-steps"],
    source: TG(C7, ["4.11"]),
  },
  {
    id: "nkc-062",
    category: "sequence",
    term: "The four updating steps",
    body: "Plot the fix and measure track and distance. Measure the new course to the turn point. Determine the actual winds. Apply them and update ETA and EFR.",
    unit: "n10",
    conceptIds: ["nav-flight-conduct"],
    source: TG(C7, ["4.11", "4.16", "4.17"]),
  },
  {
    id: "nkc-063",
    category: "equation",
    term: "Estimated fuel remaining",
    body: "The previous point's EFR, less this leg's fuel. An in-flight update starts from the fuel on board NOW, not the planned figure.",
    unit: "n10",
    conceptIds: ["nav-efr-update", "nav-jet-log-enroute"],
    source: TG(C7, ["4.13", "4.17"]),
  },
  {
    id: "nkc-064",
    category: "trap",
    term: "Off course, do not fly back to the line",
    body: "Compute a new course and heading direct to the turn point, and replan from there.",
    unit: "n10",
    conceptIds: ["nav-flight-conduct"],
    source: TG(C7, ["4.11"]),
  },

  /* ---------------- Tolerances ---------------- */
  {
    id: "nkc-065",
    category: "number",
    term: "Chart tolerances",
    body: "Direction ±1°. Distance ±½ NM. Pulling or plotting latitude and longitude ±1 minute.",
    unit: "n5",
    conceptIds: ["nav-measuring-direction", "nav-measuring-distance", "nav-pulling-coordinates"],
    source: TG(APPX),
  },
  {
    id: "nkc-066",
    category: "number",
    term: "CR-3 front-side tolerances",
    body: "Time, groundspeed, distance, fuel flow and fuel quantity: ±1 unit on the log scale, about ±1%. True airspeed ±2 kt. Mach ±0.01.",
    unit: "n6",
    conceptIds: ["nav-tick-values", "nav-ratio"],
    source: TG(APPX),
  },
  {
    id: "nkc-067",
    category: "number",
    term: "CR-3 wind-side tolerances",
    body: "Components ±3 kt under 70 kt of wind, ±5 above. In-flight winds ±3° and 3 kt under 70, ±5° and 5 kt above.",
    unit: "n8",
    conceptIds: ["nav-preflight-procedure", "nav-wind-scales"],
    source: TG(APPX),
  },
  {
    id: "nkc-068",
    category: "number",
    term: "Point-to-point tolerance",
    body: "±3° and ±1 NM.",
    unit: "n9",
    conceptIds: ["nav-point-to-point"],
    source: TG(APPX),
  },
  {
    id: "nkc-069",
    category: "definition",
    term: "The mission tolerance pyramid",
    body: "A jet-log EFR has no single tolerance. Every skill in the chain has its own, and they stack — which is why accuracy at each step is what keeps the final answer inside the band.",
    unit: "n10",
    conceptIds: ["nav-planning-steps", "nav-efr-update"],
    source: TG(APPX),
  },
];
