import type { KnowColdCard, SourceReference } from "@/lib/types";

const ORG = (): SourceReference => ({
  document: "Flight Rules and Regulations Trainee Guide",
  chapter: "Federal Aviation Organization",
});
const VIFR = (): SourceReference => ({
  document: "Flight Rules and Regulations Trainee Guide",
  chapter: "Visual / Instrument Flight Rules",
});
const AIR = (): SourceReference => ({
  document: "Flight Rules and Regulations Trainee Guide",
  chapter: "Airspace and General Flight Rules",
});

/**
 * Flight Rules Know Cold — the compression layer for the night before the exam.
 *
 * Regulations fail differently from physics. A student rarely misremembers the
 * concept; they misremember the number, or which of two similar rules applies.
 * So this deck leans hard on the `number` and `trap` categories, and every
 * threshold is quoted exactly as the NIFE material states it.
 */
export const KNOW_COLD: KnowColdCard[] = [
  /* ---------------- Definitions ---------------- */
  {
    id: "fkc-001",
    category: "definition",
    term: "FAR Part 91",
    body: "General operating and flight rules. The FAA part that most concerns naval aviators. Regulatory.",
    unit: "f1",
    conceptIds: ["fr-far"],
    source: ORG(),
  },
  {
    id: "fkc-002",
    category: "definition",
    term: "AIM",
    body: "Aeronautical Information Manual. FAA plain-language amplification of the regulations. NON-regulatory.",
    unit: "f1",
    conceptIds: ["fr-aim"],
    source: ORG(),
  },
  {
    id: "fkc-003",
    category: "definition",
    term: "FLIP",
    body: "Flight Information Publications. Department of Defense — en route charts, approach plates and planning guides, used by all branches.",
    unit: "f1",
    conceptIds: ["fr-flip"],
    source: ORG(),
  },
  {
    id: "fkc-004",
    category: "definition",
    term: "CNAF M-3710.7",
    body: "The NATOPS General Flight and Operating Instructions Manual. Procedures for all naval aircraft worldwide.",
    unit: "f1",
    conceptIds: ["fr-cnaf"],
    source: ORG(),
  },
  {
    id: "fkc-005",
    category: "definition",
    term: "NOTAM",
    body: "Notice to Airmen. Information on the establishment, condition or change of any aeronautical facility, service, procedure or hazard that is temporary, or not known early enough to publish another way.",
    unit: "f1",
    conceptIds: ["fr-notam"],
    source: ORG(),
  },
  {
    id: "fkc-006",
    category: "definition",
    term: "VMC and IMC",
    body: "Meteorological conditions at or better than the specified minima (VMC), or below them (IMC). Both describe the WEATHER, never the rules.",
    unit: "f5",
    conceptIds: ["fr-vmc", "fr-imc"],
    source: VIFR(),
  },
  {
    id: "fkc-007",
    category: "definition",
    term: "VFR-on-top",
    body: "An IFR clearance under which the pilot selects the altitude. VFR cruising altitudes and VFR weather minimums both still apply.",
    unit: "f5",
    conceptIds: ["fr-vfr-on-top"],
    source: VIFR(),
  },
  {
    id: "fkc-008",
    category: "definition",
    term: "Precision approach",
    body: "An approach giving both course AND glideslope guidance. The limit is a decision height. ILS and PAR.",
    unit: "f5",
    conceptIds: ["fr-approach-types"],
    source: VIFR(),
  },
  {
    id: "fkc-009",
    category: "definition",
    term: "Non-precision approach",
    body: "Course guidance only. The limit is a minimum descent altitude. VOR, TACAN, LOC, ASR, RNAV.",
    unit: "f5",
    conceptIds: ["fr-approach-types"],
    source: VIFR(),
  },
  {
    id: "fkc-010",
    category: "definition",
    term: "Aerobatic flight",
    body: "An intentional manoeuvre involving abrupt bank greater than 60°, pitch greater than ±45°, or acceleration greater than 2.0 g.",
    unit: "f6",
    conceptIds: ["fr-aerobatic-definition"],
    source: VIFR(),
  },
  {
    id: "fkc-011",
    category: "definition",
    term: "Controlled airspace",
    body: "Airspace of defined dimensions in which ATC service is provided. Classes A, B, C, D and E. Class G is uncontrolled.",
    unit: "f7",
    conceptIds: ["fr-controlled", "fr-uncontrolled"],
    source: AIR(),
  },
  {
    id: "fkc-012",
    category: "definition",
    term: "Flat hatting",
    body: "Any manoeuvre at low altitude and/or high airspeed for THRILL purposes, over land or water. Prohibited.",
    unit: "f8",
    conceptIds: ["fr-flat-hatting"],
    source: AIR(),
  },

  /* ---------------- Numbers ---------------- */
  {
    id: "fkc-020",
    category: "number",
    term: "Weather brief void time",
    body: "Brief + 3 hours, or ETD + 30 minutes — whichever is EARLIER.",
    unit: "f2",
    conceptIds: ["fr-weather-brief"],
    source: ORG(),
  },
  {
    id: "fkc-021",
    category: "number",
    term: "Crew rest and crew day",
    body: "8 hours of uninterrupted sleep in every 24-hour period. Crew day should not exceed 18 hours.",
    unit: "f3",
    conceptIds: ["fr-crew-rest"],
    source: ORG(),
  },
  {
    id: "fkc-022",
    category: "number",
    term: "Alcohol",
    body: "None within 12 hours of the mission BRIEF or flight planning — not 12 hours before takeoff.",
    unit: "f3",
    conceptIds: ["fr-alcohol"],
    source: ORG(),
  },
  {
    id: "fkc-023",
    category: "number",
    term: "Caffeine and medication",
    body: "Caffeine 450 mg per day recommended maximum, about 3–4 cups of drip coffee. BOTH prescription and over-the-counter drugs are prohibited unless approved by a flight surgeon.",
    unit: "f3",
    conceptIds: ["fr-caffeine-drugs"],
    source: ORG(),
  },
  {
    id: "fkc-025",
    category: "number",
    term: "Basic VFR minimums",
    body: "1,000 ft above, 500 ft below, 2,000 ft horizontally, 3 SM visibility.",
    unit: "f5",
    conceptIds: ["fr-basic-vfr"],
    source: VIFR(),
  },
  {
    id: "fkc-026",
    category: "number",
    term: "Filing VFR",
    body: "Destination forecast must show at least a 1,000 ft ceiling and 3 SM visibility for ETA ± 1 hour.",
    unit: "f5",
    conceptIds: ["fr-vfr-destination"],
    source: VIFR(),
  },
  {
    id: "fkc-027",
    category: "number",
    term: "Alternate weather trigger",
    body: "3,000 ft ceiling and 3 SM visibility, during ETA ± 1 hour.",
    unit: "f5",
    conceptIds: ["fr-alternate"],
    source: VIFR(),
  },
  {
    id: "fkc-028",
    category: "number",
    term: "Fuel reserve",
    body: "10% of planned fuel requirements, never less than 20 minutes.",
    unit: "f5",
    conceptIds: ["fr-vfr-fuel", "fr-ifr-fuel"],
    source: VIFR(),
  },
  {
    id: "fkc-029",
    category: "number",
    term: "Victor airways and jet routes",
    body: "Victor airways: 1,200 AGL to 18,000 MSL, 8 nm wide (4 nm each side). Jet routes: 18,000 MSL to FL450.",
    unit: "f7",
    conceptIds: ["fr-victor-airways", "fr-jet-routes"],
    source: AIR(),
  },
  {
    id: "fkc-030",
    category: "number",
    term: "Class A",
    body: "18,000 MSL to FL600. IFR only, clearance required.",
    unit: "f7",
    conceptIds: ["fr-class-a"],
    source: AIR(),
  },
  {
    id: "fkc-031",
    category: "number",
    term: "VFR minimums above 10,000 MSL",
    body: "In Class E at or above 10,000 MSL: 1,000 above, 1,000 below, 1 SM horizontally, 5 SM visibility.",
    unit: "f7",
    conceptIds: ["fr-vfr-minimums-table"],
    source: AIR(),
  },
  {
    id: "fkc-032",
    category: "number",
    term: "Position lights",
    body: "From 30 minutes before official sunset to 30 minutes after official sunrise, and whenever visibility is less than 3 SM.",
    unit: "f8",
    conceptIds: ["fr-position-lights"],
    source: AIR(),
  },
  {
    id: "fkc-033",
    category: "number",
    term: "Minimum safe altitudes",
    body: "Congested area: 1,000 ft above the highest obstacle within a 2,000 ft radius. Other than congested: 500 ft AGL.",
    unit: "f8",
    conceptIds: ["fr-altitude-congested", "fr-altitude-other"],
    source: AIR(),
  },
  {
    id: "fkc-034",
    category: "number",
    term: "CNAF altitude floors",
    body: "VFR fixed wing: 500 ft above terrain or water. IFR outside controlled airspace: 1,000 ft above the highest obstacle within 22 miles, 2,000 ft over designated mountainous terrain.",
    unit: "f8",
    conceptIds: ["fr-altitude-cnaf"],
    source: AIR(),
  },
  {
    id: "fkc-035",
    category: "number",
    term: "Airspeed limits",
    body: "250 KIAS below 10,000 MSL. 250 inside Class B. 200 beneath the Class B shelf. 200 within 4 nm of a Class C or D primary airport, surface to 2,500 AGL.",
    unit: "f8",
    conceptIds: ["fr-airspeed"],
    source: AIR(),
  },
  {
    id: "fkc-037",
    category: "number",
    term: "Avoidance distances",
    body: "Noise-sensitive areas: avoid below 3,000 ft AGL. Wildlife habitations: maintain 3,000 ft AGL. Commercial and civil aircraft: 500 ft vertically and/or 1 SM laterally.",
    unit: "f8",
    conceptIds: ["fr-noise-sensitive", "fr-wildlife", "fr-commercial-avoidance"],
    source: AIR(),
  },
  {
    id: "fkc-038",
    category: "number",
    term: "Aerobatic floor",
    body: "Not below 1,500 ft AGL and not when visibility is less than 3 SM. The Training Command minimum is 5,000 ft AGL.",
    unit: "f6",
    conceptIds: ["fr-aerobatic-rules"],
    source: VIFR(),
  },

  /* ---------------- Sequences ---------------- */
  {
    id: "fkc-050",
    category: "sequence",
    term: "Priority of regulations",
    body: "Aircraft NATOPS → CNAF M-3710.7 → FLIP → FAR Part 91. Highest to lowest.",
    unit: "f1",
    conceptIds: ["fr-priority"],
    source: ORG(),
  },
  {
    id: "fkc-051",
    category: "sequence",
    term: "Right of way, overall",
    body: "Aircraft in distress → landing aircraft, lower first → category priority → same category, the aircraft on the right.",
    unit: "f8",
    conceptIds: ["fr-row-order"],
    source: AIR(),
  },
  {
    id: "fkc-052",
    category: "sequence",
    term: "Category priority",
    body: "Balloon → glider → airship → airplane → helicopter. Least manoeuvrable has the highest priority.",
    unit: "f8",
    conceptIds: ["fr-row-category"],
    source: AIR(),
  },
  {
    id: "fkc-053",
    category: "sequence",
    term: "Preflight planning minimum",
    body: "Weather reports and forecasts → NOTAMs → fuel requirements → alternates available → anticipated traffic delays.",
    unit: "f2",
    conceptIds: ["fr-preflight"],
    source: ORG(),
  },
  {
    id: "fkc-054",
    category: "sequence",
    term: "Aircrew minimum PPE",
    body: "Protective helmet, safety or flyer boots, fire-resistant flight suit and gloves, survival knife, personal survival kit, signal device, survival radio, emergency beacon, flashlight, identification tags.",
    unit: "f3",
    conceptIds: ["fr-ppe"],
    source: ORG(),
  },

  /* ---------------- Relationships ---------------- */
  {
    id: "fkc-070",
    category: "relationship",
    term: "Runway number from heading",
    body: "Round the magnetic heading to the nearest 10 and drop the last digit. The opposite end is always 18 away.",
    unit: "f4",
    conceptIds: ["fr-runway-numbering"],
    source: VIFR(),
  },
  {
    id: "fkc-071",
    category: "relationship",
    term: "Position lights and relative position",
    body: "Red AND green = head-on, opposite direction. White only = tail on, same direction. Red only = crossing right to left. Green only = crossing left to right.",
    unit: "f8",
    conceptIds: ["fr-relative-position"],
    source: AIR(),
  },
  {
    id: "fkc-072",
    category: "relationship",
    term: "VASI",
    body: "Red over red, you're dead. Red over white, you're alright. White over white, you're too high.",
    unit: "f4",
    conceptIds: ["fr-vasi"],
    source: VIFR(),
  },
  {
    id: "fkc-073",
    category: "relationship",
    term: "Runway end lights",
    body: "Green when approaching the threshold. Red when viewed from the runway, marking the overrun. Same fixtures, opposite meanings.",
    unit: "f4",
    conceptIds: ["fr-runway-lighting"],
    source: VIFR(),
  },
  {
    id: "fkc-074",
    category: "relationship",
    term: "Semicircular rule",
    body: "Magnetic COURSE 0–179 is east and flies odd; 180–359 is west and flies even. VFR adds 500 ft; IFR does not.",
    unit: "f6",
    conceptIds: ["fr-semicircular", "fr-vfr-altitudes", "fr-ifr-altitudes"],
    source: VIFR(),
  },
  {
    id: "fkc-075",
    category: "relationship",
    term: "Class B versus Class C and D",
    body: "Class B requires an ATC clearance. Class C and D require only that two-way communication be established — the controller answering with your call sign.",
    unit: "f7",
    conceptIds: ["fr-class-b", "fr-class-c", "fr-two-way-established"],
    source: AIR(),
  },
  {
    id: "fkc-076",
    category: "relationship",
    term: "Special use airspace",
    body: "Prohibited forbids entry. Restricted requires permission from the controlling agency. Warning has the same hazards but sits over international water, where it cannot legally be restricted.",
    unit: "f7",
    conceptIds: ["fr-prohibited-area", "fr-restricted-area", "fr-warning-area"],
    source: AIR(),
  },
  {
    id: "fkc-077",
    category: "relationship",
    term: "Wind sock and tetrahedron",
    body: "The wind sock shows wind direction and approximate velocity. The tetrahedron shows the direction of landing and takeoff.",
    unit: "f4",
    conceptIds: ["fr-wind-indicators"],
    source: VIFR(),
  },

  /* ---------------- Traps ---------------- */
  {
    id: "fkc-090",
    category: "trap",
    term: "'Will' is not a requirement",
    body: "Shall is mandatory. Should is recommended. May is optional. WILL indicates futurity only, and carries no degree of requirement at all.",
    unit: "f1",
    conceptIds: ["fr-wording"],
    source: ORG(),
  },
  {
    id: "fkc-091",
    category: "trap",
    term: "The brief clock is the EARLIER of the two",
    body: "Brief + 3 hours or ETD + 30 minutes, whichever comes first. Reading it as 'whichever is later' is the classic error.",
    unit: "f2",
    conceptIds: ["fr-weather-brief"],
    source: ORG(),
  },
  {
    id: "fkc-092",
    category: "trap",
    term: "Alcohol is measured from the brief",
    body: "12 hours from the mission brief or flight planning, not from takeoff.",
    unit: "f3",
    conceptIds: ["fr-alcohol"],
    source: ORG(),
  },
  {
    id: "fkc-093",
    category: "trap",
    term: "Over-the-counter drugs are not exempt",
    body: "BOTH prescription and over-the-counter medication are prohibited without flight surgeon approval.",
    unit: "f3",
    conceptIds: ["fr-caffeine-drugs"],
    source: ORG(),
  },
  {
    id: "fkc-094",
    category: "trap",
    term: "Flashing white is not a landing clearance",
    body: "Steady green is the clearance to land. Flashing white only means return for landing.",
    unit: "f4",
    conceptIds: ["fr-aldis"],
    source: VIFR(),
  },
  {
    id: "fkc-095",
    category: "trap",
    term: "An IFR flight plan does not mean IMC",
    body: "VMC and IMC describe the weather; VFR and IFR describe the rules. An IFR flight plan flown in VMC is entirely normal.",
    unit: "f5",
    conceptIds: ["fr-vfr-ifr-terms"],
    source: VIFR(),
  },
  {
    id: "fkc-096",
    category: "trap",
    term: "No horizon means IMC",
    body: "CNAF M-3710.7 adds that IMC exists any time a visible horizon is not distinguishable — regardless of what the reported numbers say.",
    unit: "f5",
    conceptIds: ["fr-imc"],
    source: VIFR(),
  },
  {
    id: "fkc-097",
    category: "trap",
    term: "See and avoid applies under IFR too",
    body: "The regulation says 'regardless of whether an operation is conducted under IFR or VFR'. Being on a clearance does not transfer the lookout to ATC.",
    unit: "f5",
    conceptIds: ["fr-see-and-avoid"],
    source: VIFR(),
  },
  {
    id: "fkc-098",
    category: "trap",
    term: "360° counts as EAST",
    body: "360 is 0, and 0 through 179 is the east semicircle. It is also the COURSE that decides, never the heading.",
    unit: "f6",
    conceptIds: ["fr-semicircular"],
    source: VIFR(),
  },
  {
    id: "fkc-099",
    category: "trap",
    term: "The speed limit tightens UNDER Class B",
    body: "250 knots inside Class B, 200 knots beneath the shelf. Most students invert these.",
    unit: "f8",
    conceptIds: ["fr-airspeed"],
    source: AIR(),
  },
  {
    id: "fkc-100",
    category: "trap",
    term: "Head-on ignores the category list",
    body: "Approaching head-on, or nearly so, at the same altitude, EACH pilot alters course to the right — whatever the two aircraft are.",
    unit: "f8",
    conceptIds: ["fr-row-order"],
    source: AIR(),
  },
  {
    id: "fkc-101",
    category: "trap",
    term: "Careless flying is judged by the observer",
    body: "CNAF requires particular effort so that individuals do not BELIEVE they or their property are endangered. The pilot's own assessment of actual danger is not the test.",
    unit: "f8",
    conceptIds: ["fr-careless"],
    source: AIR(),
  },
  {
    id: "fkc-102",
    category: "trap",
    term: "'Standby' is not two-way communication established",
    body: "The controller must answer using your aircraft call sign. 'Remain outside the Class C airspace and standby' does not authorise entry.",
    unit: "f7",
    conceptIds: ["fr-two-way-established"],
    source: AIR(),
  },
  {
    id: "fkc-103",
    category: "trap",
    term: "A break is not aerobatic flight",
    body: "A break manoeuvre conforming to the model NATOPS flight manual is specifically excluded from the definition of aerobatic flight.",
    unit: "f6",
    conceptIds: ["fr-aerobatic-definition"],
    source: VIFR(),
  },
];
