import type { Question, SourceReference } from "@/lib/types";

const TG = (chapter: string, eo: string[]): SourceReference => ({
  document: "Aerodynamics Trainee Guide",
  chapter,
  eo,
});

const BASIC = (eo: string[]) => TG("Basic Theory", eo);
const LIFT = (eo: string[]) => TG("Lift Production and Drag", eo);

/**
 * Assessment depth, units 1–3.
 *
 * The Aerodynamics guide enumerates enabling objectives far more finely than
 * the other courses, and the original question set averaged roughly one
 * question per EO — thin enough that a student could clear a lesson without
 * the material having been tested. These questions bring every concept in
 * units 1–3 to at least two, and cover the objectives that previously had no
 * concept carrying them at all.
 */
export const DEPTH_A_QUESTIONS: Question[] = [
  /* ================= u1 · definitions and mechanics ================= */
  {
    id: "q-da-001",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-mass-volume"],
    prompt: "Mass is defined as",
    options: [
      "the force with which a body is attracted toward the earth",
      "the quantity of molecular material that comprises an object",
      "the amount of space occupied by an object",
      "mass per unit volume",
    ],
    answer: 1,
    explanation:
      "Mass is the quantity of molecular material in an object. The amount of space it occupies is volume, and the ratio of the two is density.",
    whyWrong:
      "The first option is weight — a force. The third is volume. The fourth is density.",
    knowCold: "Mass is how much material. Weight is the force on it.",
    difficulty: 1,
    officialStyle: true,
    source: BASIC(["2.3", "2.4"]),
  },
  {
    id: "q-da-002",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-mass-volume"],
    prompt:
      "Two containers hold the same mass of air. Container B has twice the volume of container A. The density of the air in B is",
    options: ["twice that of A", "the same as A", "half that of A", "one quarter that of A"],
    answer: 2,
    explanation:
      "Density is mass divided by volume. Holding mass constant and doubling the volume halves the density.",
    knowCold: "ρ = m / V.",
    difficulty: 2,
    source: BASIC(["2.3", "2.4"]),
  },
  {
    id: "q-da-003",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-force-weight"],
    prompt: "Weight is",
    options: [
      "the quantity of molecular material in a body",
      "the force with which a mass is attracted toward the centre of the earth by gravity",
      "mass divided by volume",
      "the product of mass and volume",
    ],
    answer: 1,
    explanation:
      "Weight is a force. Force is mass times acceleration, and weight is the particular case where the acceleration is gravity.",
    whyWrong:
      "The quantity of molecular material is mass, which does not change with location. Weight does.",
    knowCold: "Weight is a force: F = m × a, with a = gravity.",
    difficulty: 1,
    officialStyle: true,
    source: BASIC(["2.6", "2.7"]),
  },
  {
    id: "q-da-004",
    type: "spotTheTrap",
    unit: "u1",
    conceptIds: ["c-force-weight", "c-mass-volume"],
    prompt: '"An aircraft\'s mass and its weight are two names for the same quantity."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. Mass is the quantity of molecular material. Weight is the force gravity exerts on that mass. Move the aircraft somewhere with different gravity and the mass is unchanged while the weight is not.",
    knowCold: "Mass is material. Weight is force.",
    difficulty: 2,
    source: BASIC(["2.3", "2.6", "2.7"]),
  },
  {
    id: "q-da-005",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-scalar-vector"],
    prompt: "Which of the following is a vector quantity?",
    options: ["Speed", "Mass", "Velocity", "Volume"],
    answer: 2,
    explanation:
      "A vector carries magnitude AND direction. Velocity is speed with a direction attached; speed alone is a scalar, as are mass and volume.",
    knowCold: "Speed is scalar. Velocity is vector.",
    difficulty: 1,
    officialStyle: true,
    source: BASIC(["2.1", "2.2"]),
  },
  {
    id: "q-da-006",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-scalar-vector"],
    prompt: "Any vector can be",
    options: [
      "expressed as a single number with no direction",
      "resolved into perpendicular components",
      "added only to vectors of equal magnitude",
      "converted into a scalar by reversing it",
    ],
    answer: 1,
    explanation:
      "Resolving a vector into perpendicular components is what makes it possible to treat lift and drag, or thrust and weight, as separate problems.",
    knowCold: "Any vector breaks into perpendicular components.",
    difficulty: 2,
    source: BASIC(["2.1", "2.2"]),
  },
  {
    id: "q-da-007",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-moment"],
    prompt:
      "The same force is applied to a control surface, but the moment arm is doubled. The moment produced is",
    options: ["unchanged", "doubled", "halved", "quadrupled"],
    answer: 1,
    explanation:
      "A moment is force times the perpendicular distance from the axis of rotation, so it is linear in the arm. Doubling the arm doubles the moment.",
    knowCold: "Moment scales linearly with the arm.",
    difficulty: 2,
    source: BASIC(["2.8"]),
  },
  {
    id: "q-da-008",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-newton-laws"],
    prompt: "An aircraft in unaccelerated straight and level flight demonstrates Newton's law of",
    options: ["acceleration", "equilibrium", "interaction", "universal gravitation"],
    answer: 1,
    explanation:
      "The first law — equilibrium: a body remains at rest or in uniform motion unless acted on by an unbalanced force. In level unaccelerated flight the four forces are balanced.",
    knowCold: "Equilibrium, acceleration, interaction — first, second, third.",
    difficulty: 2,
    officialStyle: true,
    source: BASIC(["2.14", "2.17", "2.18"]),
  },
  {
    id: "q-da-009",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-newton-laws"],
    prompt:
      "A propeller pushes air aft, and the air pushes the aircraft forward. Which of Newton's laws describes this?",
    options: ["Equilibrium", "Acceleration", "Interaction", "Conservation of mass"],
    answer: 2,
    explanation:
      "The third law, interaction: for every action there is an equal and opposite reaction.",
    knowCold: "Action and reaction is the third law.",
    difficulty: 1,
    source: BASIC(["2.14", "2.17", "2.18"]),
  },
  {
    id: "q-da-010",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-static-pressure"],
    prompt: "Static pressure always acts",
    options: [
      "in the direction of flight",
      "perpendicular to a surface",
      "parallel to a surface",
      "opposite the relative wind",
    ],
    answer: 1,
    explanation:
      "Static pressure is the pressure air particles exert on adjacent bodies, and it always acts perpendicular to the surface. Ambient static pressure equals the weight of the column of air above a given area.",
    knowCold: "Static pressure acts perpendicular to the surface.",
    difficulty: 2,
    source: BASIC(["2.19"]),
  },
  {
    id: "q-da-011",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-static-pressure"],
    prompt:
      "Climbing from sea level to 3,000 ft, ambient static pressure decreases by approximately",
    options: ["0.3 in-Hg", "1.0 in-Hg", "3.0 in-Hg", "10.0 in-Hg"],
    answer: 2,
    explanation:
      "At low altitude static pressure falls roughly 1.0 in-Hg per 1,000 ft, so 3,000 ft costs about 3 in-Hg.",
    knowCold: "About 1 in-Hg per 1,000 ft down low.",
    difficulty: 2,
    source: BASIC(["2.19"]),
  },
  {
    id: "q-da-012",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-temperature-lapse"],
    prompt:
      "Sea level temperature is 15 °C. Using the average lapse rate, what is the approximate temperature at 10,000 ft?",
    options: ["−5 °C", "0 °C", "5 °C", "−15 °C"],
    answer: 0,
    explanation:
      "The average lapse rate is 2 °C per 1,000 ft. Ten thousand feet costs 20 °C, so 15 − 20 = −5 °C.",
    knowCold: "2 °C per 1,000 ft.",
    difficulty: 2,
    source: BASIC(["2.21", "2.22"]),
  },
  {
    id: "q-da-013",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-temperature-lapse"],
    prompt: "Above approximately 36,000 ft, temperature",
    options: [
      "continues to fall at 2 °C per 1,000 ft",
      "holds constant at −56.5 °C through the isothermal layer",
      "rises at 2 °C per 1,000 ft",
      "becomes unpredictable",
    ],
    answer: 1,
    explanation:
      "From about 36,000 to 66,000 ft the atmosphere is isothermal at −56.5 °C. The linear lapse rate applies only below that.",
    knowCold: "36,000–66,000 ft: −56.5 °C, constant.",
    difficulty: 2,
    source: BASIC(["2.21", "2.22"]),
  },
  {
    id: "q-da-014",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-humidity-density"],
    prompt: "As humidity increases, air density",
    options: [
      "increases, because water is added to the air",
      "decreases, because water molecules displace heavier air molecules",
      "is unchanged, because water vapour has no mass",
      "increases at low altitude and decreases at high altitude",
    ],
    answer: 1,
    explanation:
      "Water molecules displace an equal number of air molecules but have less mass, so the total mass per unit volume falls. Humid air is LESS dense.",
    whyWrong:
      "The intuition that adding water makes air heavier is the single most-reversed relationship in this unit.",
    knowCold: "Humidity up, density down.",
    difficulty: 2,
    officialStyle: true,
    source: BASIC(["2.23", "2.24"]),
  },
  {
    id: "q-da-015",
    type: "connectChain",
    unit: "u1",
    conceptIds: ["c-humidity-density"],
    prompt: "A humid day. Order what follows.",
    trigger: "Humidity increases",
    steps: ["Air density decreases", "Performance decreases", "Takeoff speed and distance increase"],
    explanation:
      "Less dense air produces less lift and less thrust at a given speed, so the aircraft needs more runway and a higher speed to fly.",
    knowCold: "Humid, hot and high all hurt the same way.",
    difficulty: 2,
    source: BASIC(["2.23", "2.24"]),
  },
  {
    id: "q-da-016",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-viscosity"],
    prompt: "As air temperature increases, the viscosity of air",
    options: ["decreases", "increases", "is unchanged", "decreases then increases"],
    answer: 1,
    explanation:
      "Air behaves opposite to liquids: heating air makes it MORE viscous. Viscosity is the air's resistance to flow and shearing, shown by its tendency to stick to a surface.",
    whyWrong:
      "Hot oil is thinner, so students expect hot air to be thinner too. For air the relationship reverses.",
    knowCold: "Hotter air is more viscous.",
    difficulty: 3,
    officialStyle: true,
    source: BASIC(["2.25", "2.26"]),
  },
  {
    id: "q-da-017",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-viscosity"],
    prompt: "Viscosity is best described as",
    options: [
      "the weight of a column of air",
      "the air's resistance to flow and shearing",
      "the average kinetic energy of air particles",
      "mass per unit volume",
    ],
    answer: 1,
    explanation:
      "It shows itself as the air's tendency to stick to a surface — which is what creates the boundary layer.",
    knowCold: "Viscosity is stickiness.",
    difficulty: 1,
    source: BASIC(["2.25", "2.26"]),
  },
  {
    id: "q-da-018",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-speed-of-sound"],
    prompt: "The local speed of sound depends on",
    options: ["pressure alone", "density alone", "temperature alone", "altitude alone"],
    answer: 2,
    explanation:
      "In air the speed of sound is a function of temperature only. It falls with altitude because temperature falls with altitude, not because altitude affects it directly.",
    whyWrong:
      "Pressure, density and altitude all correlate with the speed of sound, but temperature is the only cause.",
    knowCold: "Temperature alone.",
    difficulty: 2,
    officialStyle: true,
    source: BASIC(["2.27", "2.28"]),
  },
  {
    id: "q-da-019",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-speed-of-sound", "c-standard-atmosphere"],
    prompt: "On a standard day at sea level, the local speed of sound is",
    options: ["551.7 knots", "601.7 knots", "661.7 knots", "761.7 knots"],
    answer: 2,
    explanation:
      "661.7 knots, one of the standard atmosphere values alongside 29.92 in-Hg and 59 °F.",
    knowCold: "661.7 knots at sea level standard.",
    difficulty: 2,
    source: BASIC(["2.27", "2.29"]),
  },
  {
    id: "q-da-020",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-standard-atmosphere"],
    prompt: "Standard sea level pressure and temperature are",
    options: [
      "29.92 in-Hg and 59 °F",
      "29.92 in-Hg and 15 °F",
      "28.92 in-Hg and 59 °F",
      "30.92 in-Hg and 15 °C",
    ],
    answer: 0,
    explanation:
      "29.92 in-Hg and 59 °F, which is 15 °C. Density is 0.0024 slugs/ft³ and the speed of sound is 661.7 knots.",
    knowCold: "29.92 and 59 °F / 15 °C.",
    difficulty: 1,
    officialStyle: true,
    source: BASIC(["2.29"]),
  },
  {
    id: "q-da-021",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-gas-law"],
    prompt:
      "In the General Gas Law, with static pressure held CONSTANT, temperature and density are",
    options: ["directly related", "inversely related", "unrelated", "equal"],
    answer: 1,
    explanation:
      "P = ρRT. Holding P constant, raising T must lower ρ. That is why a hot day gives you a high density altitude.",
    whyWrong:
      "It is easy to read P = ρRT and conclude T and ρ move together. They only do so when PRESSURE is free to change.",
    knowCold: "Pressure constant: T and ρ are inverse.",
    difficulty: 3,
    officialStyle: true,
    source: BASIC(["2.30"]),
  },
  {
    id: "q-da-022",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-gas-law"],
    prompt: "With DENSITY held constant, an increase in temperature produces",
    options: [
      "a decrease in pressure",
      "an increase in pressure",
      "no change in pressure",
      "a decrease in the gas constant",
    ],
    answer: 1,
    explanation: "P = ρRT with ρ fixed means P rises directly with T.",
    knowCold: "Density constant: T up, P up.",
    difficulty: 2,
    source: BASIC(["2.30"]),
  },
  {
    id: "q-da-023",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-steady-airflow"],
    prompt:
      "Steady airflow exists when which four properties remain constant at every point over time?",
    options: [
      "Pressure, density, temperature, viscosity",
      "Pressure, density, temperature, velocity",
      "Pressure, velocity, viscosity, humidity",
      "Density, temperature, velocity, humidity",
    ],
    answer: 1,
    explanation:
      "Static pressure, density, temperature and velocity. Viscosity is not on the list.",
    whyWrong:
      "Viscosity is the plausible fifth property, which is exactly why it appears in the distractors.",
    knowCold: "Pressure, density, temperature, velocity.",
    difficulty: 3,
    officialStyle: true,
    source: BASIC(["2.32", "2.33", "2.34"]),
  },
  {
    id: "q-da-024",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-steady-airflow"],
    prompt: "A streamtube is",
    options: [
      "the path a single particle follows in steady airflow",
      "a bundle of adjacent streamlines behaving as a closed system",
      "the region of retarded flow next to a surface",
      "the wake left behind a wingtip",
    ],
    answer: 1,
    explanation:
      "A streamline is one particle's path; a streamtube is a bundle of them treated as a closed system, which is what lets continuity be applied to it.",
    knowCold: "Streamline is one path. Streamtube is a bundle.",
    difficulty: 2,
    source: BASIC(["2.32", "2.33", "2.34"]),
  },
  {
    id: "q-da-025",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-altitude-types"],
    prompt: "Height above the standard datum plane is",
    options: ["true altitude", "absolute altitude", "pressure altitude", "density altitude"],
    answer: 2,
    explanation:
      "Pressure altitude is measured from the plane where pressure is 29.92 in-Hg. True altitude is height above mean sea level; absolute altitude is height above the terrain.",
    knowCold: "Pressure altitude is measured from 29.92.",
    difficulty: 2,
    officialStyle: true,
    source: BASIC(["2.36", "2.37", "2.38"]),
  },
  {
    id: "q-da-026",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-altitude-types"],
    prompt: "An aircraft's radar altimeter reads its",
    options: ["true altitude", "absolute altitude", "pressure altitude", "indicated altitude"],
    answer: 1,
    explanation:
      "Absolute altitude is height above the terrain — AGL. True altitude is height above mean sea level.",
    knowCold: "Absolute is AGL. True is MSL.",
    difficulty: 2,
    source: BASIC(["2.36", "2.37", "2.38"]),
  },
  {
    id: "q-da-027",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-chordwise-spanwise"],
    prompt: "Chordwise airflow travels",
    options: [
      "parallel to the leading edge and produces no lift",
      "perpendicular to the leading edge and is the only flow that produces lift",
      "parallel to the leading edge and produces all the lift",
      "perpendicular to the chord line and produces drag only",
    ],
    answer: 1,
    explanation:
      "Chordwise flow crosses the wing at right angles to the leading edge and is the only component that accelerates over the wing to produce lift. Spanwise flow runs parallel to the leading edge and produces none.",
    knowCold: "Chordwise is perpendicular, and it is the one that lifts.",
    difficulty: 2,
    officialStyle: true,
    source: BASIC(["2.63", "2.64"]),
  },
  {
    id: "q-da-028",
    type: "spotTheTrap",
    unit: "u1",
    conceptIds: ["c-chordwise-spanwise"],
    prompt: '"Spanwise airflow contributes to lift production on a finite wing."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. Spanwise flow travels parallel to the leading edge along the span and produces no lift at all. It is what rolls off the tip and creates the wingtip vortex.",
    knowCold: "Spanwise flow makes vortices, not lift.",
    difficulty: 2,
    source: BASIC(["2.63", "2.64"]),
  },
  {
    id: "q-da-029",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-cg"],
    prompt: "The centre of gravity is the point",
    options: [
      "along the chord line where all changes in aerodynamic force take place",
      "where all three axes intersect and all weight is considered concentrated",
      "at 25% of the chord aft of the leading edge",
      "where lift and drag are equal",
    ],
    answer: 1,
    explanation:
      "The CG is where the three axes intersect, where weight is treated as concentrated, and about which all forces and moments are measured. It moves as fuel burns or cargo shifts.",
    whyWrong:
      "The first and third options describe the aerodynamic centre, which is where aerodynamic force acts — a different point entirely.",
    knowCold: "CG is weight. AC is aerodynamic force.",
    difficulty: 2,
    officialStyle: true,
    source: BASIC(["2.77"]),
  },
  {
    id: "q-da-030",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-cg"],
    prompt: "During flight the centre of gravity",
    options: [
      "remains fixed once the aircraft is loaded",
      "shifts as fuel burns or cargo moves",
      "always moves aft",
      "coincides with the aerodynamic centre",
    ],
    answer: 1,
    explanation:
      "Anything that changes where the weight sits moves the CG, which is why weight and balance is computed for the whole flight rather than just for takeoff.",
    knowCold: "The CG moves in flight.",
    difficulty: 1,
    source: BASIC(["2.77"]),
  },
  {
    id: "q-da-031",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-aerodynamic-center"],
    prompt: "On a subsonic airfoil the aerodynamic centre is located approximately",
    options: [
      "25% of the chord aft of the leading edge",
      "25% of the chord forward of the trailing edge",
      "50% of the chord aft of the leading edge",
      "at the leading edge",
    ],
    answer: 0,
    explanation:
      "Between 23% and 27% of the chord aft of the leading edge, at maximum airfoil thickness, and it stays essentially stationary as long as the flow stays subsonic.",
    knowCold: "About 25% aft of the LEADING edge.",
    difficulty: 2,
    officialStyle: true,
    source: BASIC(["2.78"]),
  },
  {
    id: "q-da-032",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-aerodynamic-center"],
    prompt: "The aerodynamic centre is the point around which",
    options: [
      "all weight is considered concentrated",
      "all CHANGES in aerodynamic force take place",
      "the total aerodynamic force is zero",
      "the airplane rotates in a spin",
    ],
    answer: 1,
    explanation:
      "It is where changes in aerodynamic force act — which is what makes it the useful reference point for stability.",
    knowCold: "AC: where CHANGES in aerodynamic force act.",
    difficulty: 2,
    source: BASIC(["2.78"]),
  },
  {
    id: "q-da-033",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-aircraft-airplane"],
    prompt: "Which definition matches an AIRPLANE?",
    options: [
      "Any device used or intended to be used for flight in the air",
      "A mechanically driven fixed-wing aircraft, heavier than air, supported by the dynamic reaction of the air against its wings",
      "Any heavier-than-air device supported by the buoyancy of its structure",
      "Any rotary-wing aircraft capable of powered flight",
    ],
    answer: 1,
    explanation:
      "The first option is the definition of an aircraft, which is the broader term. A balloon is an aircraft; it is not an airplane.",
    knowCold: "Mechanically driven, fixed-wing, heavier than air, dynamic reaction.",
    difficulty: 2,
    officialStyle: true,
    source: BASIC(["2.48", "2.49"]),
  },
  {
    id: "q-da-034",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-aircraft-airplane"],
    prompt: "A dirigible is supported primarily by",
    options: [
      "the dynamic reaction of the air against its surfaces",
      "the buoyancy of its structure",
      "mechanical thrust alone",
      "ground effect",
    ],
    answer: 1,
    explanation:
      "Aircraft are supported either by buoyancy — balloons and dirigibles — or by dynamic reaction, which covers airplanes, gliders and helicopters.",
    knowCold: "Buoyancy or dynamic reaction: those are the two ways.",
    difficulty: 1,
    source: BASIC(["2.48", "2.49"]),
  },
  {
    id: "q-da-035",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-airplane-components"],
    prompt: "The five components of a conventional airplane are",
    options: [
      "fuselage, wings, empennage, landing gear, engine(s)",
      "fuselage, wings, ailerons, rudder, elevators",
      "wings, empennage, flaps, landing gear, engine(s)",
      "fuselage, wings, empennage, control surfaces, avionics",
    ],
    answer: 0,
    explanation:
      "Ailerons, rudder and elevators are the three major CONTROL SURFACES, not components. They live on the wings and empennage.",
    knowCold: "Fuselage, wings, empennage, landing gear, engine.",
    difficulty: 2,
    officialStyle: true,
    source: BASIC(["2.50"]),
  },
  {
    id: "q-da-036",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-airplane-components"],
    prompt: "Which component provides the greatest stabilising influence?",
    options: ["The fuselage", "The wings", "The empennage", "The landing gear"],
    answer: 2,
    explanation:
      "The empennage — the aft fuselage, vertical stabiliser and horizontal stabiliser. The fuselage and the wings are both NEGATIVE contributors to longitudinal static stability.",
    knowCold: "The empennage stabilises. The wing and fuselage destabilise.",
    difficulty: 2,
    source: BASIC(["2.50"]),
  },
  {
    id: "q-da-037",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-fuselage-construction"],
    prompt: "The advantage of semi-monocoque fuselage construction over full monocoque is that it",
    options: [
      "is lighter",
      "may be readily repaired if damaged",
      "requires no internal bracing",
      "carries the entire stress load in the skin",
    ],
    answer: 1,
    explanation:
      "Semi-monocoque adds transverse frame members and stringers that share the stress load with the skin, so damage can be repaired. Full monocoque is lighter and stronger for its weight but almost impossible to repair.",
    whyWrong:
      "Full monocoque is the lighter of the two. Semi-monocoque trades a little of that for repairability.",
    knowCold: "Semi-monocoque: repairable. The T-6B uses it.",
    difficulty: 3,
    officialStyle: true,
    source: BASIC(["2.51"]),
  },
  {
    id: "q-da-038",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-fuselage-construction"],
    prompt: "In TRUSS fuselage construction, the stress load is carried by",
    options: ["the skin alone", "the frame", "the stringers alone", "skin and stringers equally"],
    answer: 1,
    explanation:
      "The truss — a metal or wooden frame under a light skin — supports the entire stress load. It is very strong and easily repaired, but heavy.",
    knowCold: "Truss: the frame carries it. Monocoque: the skin does.",
    difficulty: 2,
    source: BASIC(["2.51"]),
  },
  {
    id: "q-da-039",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-cantilever-wing"],
    prompt: "A full cantilever wing is one in which",
    options: [
      "all bracing is internal",
      "the wing is mounted below the fuselage",
      "external struts carry the bending loads",
      "the wing has no taper",
    ],
    answer: 0,
    explanation:
      "No external struts or wires. The T-6B's wings are full cantilever, single, low-mounted, with split flaps inboard of the ailerons.",
    knowCold: "Full cantilever means bracing is all internal.",
    difficulty: 1,
    officialStyle: true,
    source: BASIC(["2.52"]),
  },
  {
    id: "q-da-040",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-root-tip-chord"],
    prompt: "Taper ratio is defined as",
    options: [
      "root chord divided by tip chord",
      "tip chord divided by root chord",
      "wingspan divided by average chord",
      "average chord divided by wingspan",
    ],
    answer: 1,
    explanation:
      "λ = c_T / c_R. Span over average chord is aspect ratio, which is a different quantity.",
    whyWrong: "Inverting the ratio is the standard error here.",
    knowCold: "Taper ratio is tip over root.",
    difficulty: 2,
    officialStyle: true,
    source: BASIC(["2.56", "2.57"]),
  },
  {
    id: "q-da-041",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-root-tip-chord"],
    prompt: "The T-6B's wings are tapered in order to",
    options: [
      "increase wing area",
      "reduce weight, improve structural stiffness and reduce wingtip vortices",
      "increase the taper ratio above 1",
      "move the aerodynamic centre forward",
    ],
    answer: 1,
    explanation:
      "Those three benefits are what taper buys. The cost is a stronger tip-stall tendency, which the wing's twist and stall strips address.",
    knowCold: "Taper: lighter, stiffer, weaker tip vortices.",
    difficulty: 2,
    source: BASIC(["2.56", "2.57"]),
  },
  {
    id: "q-da-042",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-dihedral"],
    prompt: "Dihedral angle is the angle between",
    options: [
      "the chord line and the relative wind",
      "the spanwise inclination of the wing and the lateral axis",
      "the lateral axis and the 25% chord line",
      "the chord line and the longitudinal axis",
    ],
    answer: 1,
    explanation:
      "It is the upward slope of the wing seen from the front. A negative dihedral angle is called anhedral. The T-6B has dihedral to improve LATERAL stability.",
    whyWrong:
      "The lateral axis to the 25% chord line is SWEEP angle. Chord line to relative wind is angle of attack.",
    knowCold: "Dihedral is the upward slope, and it buys lateral stability.",
    difficulty: 2,
    officialStyle: true,
    source: BASIC(["2.70"]),
  },
  {
    id: "q-da-043",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-dihedral"],
    prompt: "A wing with a negative dihedral angle is said to have",
    options: ["sweep", "taper", "anhedral", "washout"],
    answer: 2,
    explanation: "Anhedral, sometimes called cathedral — dihedral's opposite. Dihedral buys lateral stability; anhedral gives it away deliberately, in exchange for the roll responsiveness a manoeuvrable aircraft wants.",
    knowCold: "Negative dihedral is anhedral.",
    difficulty: 1,
    source: BASIC(["2.70"]),
  },
  {
    id: "q-da-044",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-sweep-angle"],
    prompt: "Sweep angle is measured between the lateral axis and",
    options: [
      "the leading edge",
      "a line drawn 25% aft of the leading edge",
      "the trailing edge",
      "the mean camber line",
    ],
    answer: 1,
    explanation:
      "The 25% chord line. On a tapered wing that line is NOT parallel to the leading edge, so measuring along the leading edge gives the wrong answer.",
    whyWrong:
      "The leading edge is the intuitive reference and the wrong one — the guide says so explicitly.",
    knowCold: "Sweep is measured to the 25% chord line.",
    difficulty: 3,
    officialStyle: true,
    source: BASIC(["2.75"]),
  },
  {
    id: "q-da-045",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-sweep-angle"],
    prompt: "Wing sweep primarily affects",
    options: [
      "maximum lift and stall characteristics",
      "the position of the centre of gravity",
      "the fuselage stress load path",
      "propeller efficiency",
    ],
    answer: 0,
    explanation:
      "Sweep also moves the wing's aerodynamic centre aft toward the CG, which makes the airplane more longitudinally stable.",
    knowCold: "Sweep changes max lift and stall behaviour.",
    difficulty: 2,
    source: BASIC(["2.75"]),
  },

  /* ================= u2 ================= */
  {
    id: "q-da-046",
    type: "mcq",
    unit: "u2",
    conceptIds: ["c-v-aoa-inverse"],
    prompt:
      "In level flight, an aircraft slows from 200 to 150 KIAS. To maintain altitude, angle of attack must",
    options: ["decrease", "increase", "stay the same", "decrease then increase"],
    answer: 1,
    explanation:
      "Lift must continue to equal weight. Velocity is squared in the lift equation, so losing airspeed has to be paid for with a higher C_L — which means a higher AOA.",
    knowCold: "Slower needs more AOA. Faster needs less.",
    difficulty: 1,
    officialStyle: true,
    source: LIFT(["2.84"]),
  },
  {
    id: "q-da-047",
    type: "spotTheTrap",
    unit: "u2",
    conceptIds: ["c-v-aoa-inverse"],
    prompt:
      '"In level flight, velocity and angle of attack are directly related — increasing one increases the other."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. They are INVERSELY related, because lift has to stay equal to weight. Fly faster and you must lower the AOA or you will climb.",
    knowCold: "Level flight: velocity and AOA are inverse.",
    difficulty: 2,
    source: LIFT(["2.84"]),
  },

  /* ================= u3 ================= */
  {
    id: "q-da-048",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-interference-drag"],
    prompt: "Interference drag is generated by",
    options: [
      "the mixing of streamlines between components",
      "the production of lift on a finite wing",
      "air striking a flat surface perpendicular to the flow",
      "surface roughness on the skin",
    ],
    answer: 0,
    explanation:
      "Where two components meet, the whole is greater than the sum of the parts. It is roughly 5–10% of total drag, and is minimised by fairing and filleting.",
    knowCold: "Interference drag comes from the junctions.",
    difficulty: 2,
    officialStyle: true,
    source: LIFT(["2.87", "2.88"]),
  },
  {
    id: "q-da-049",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-interference-drag"],
    prompt: "Interference drag is minimised by",
    options: [
      "increasing aspect ratio",
      "fairing and filleting component junctions",
      "adding winglets",
      "flying at L/Dmax",
    ],
    answer: 1,
    explanation:
      "Fairings and fillets smooth the junction so the streamlines from the two components mix less violently. Winglets and aspect ratio address INDUCED drag, which is a different problem.",
    knowCold: "Fair and fillet the junctions.",
    difficulty: 2,
    source: LIFT(["2.87", "2.88"]),
  },
  {
    id: "q-da-050",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-infinite-wing"],
    prompt: "On an INFINITE wing, upwash and downwash",
    options: [
      "do not exist",
      "exactly balance, producing no net change in lift",
      "combine to reduce lift",
      "combine to increase lift",
    ],
    answer: 1,
    explanation:
      "Upwash raises average AOA and increases lift; downwash lowers it and decreases lift. On an infinite wing the relative wind can only flow chordwise, so the two exactly cancel. It is the finite wing, with its spanwise flow, where the balance breaks.",
    knowCold: "Infinite wing: upwash and downwash cancel.",
    difficulty: 3,
    officialStyle: true,
    source: LIFT(["2.89"]),
  },
  {
    id: "q-da-051",
    type: "spotTheTrap",
    unit: "u3",
    conceptIds: ["c-infinite-wing"],
    prompt: '"Upwash and downwash only exist when a wing is stalled."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. Upwash and downwash exist any time an airfoil is producing lift. They are a consequence of lift production, not of separation.",
    knowCold: "Lift produced means upwash and downwash present.",
    difficulty: 2,
    source: LIFT(["2.89"]),
  },
  {
    id: "q-da-052",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-induced-drag-reduction"],
    prompt: "Which of the following reduces induced drag?",
    options: [
      "Fairings and fillets",
      "Winglets, wingtip fuel tanks and missile rails",
      "Flush riveting",
      "A more streamlined fuselage",
    ],
    answer: 1,
    explanation:
      "All three impede spanwise airflow around the wingtip, which is what generates the vortex and therefore the induced drag. The other options reduce PARASITE drag.",
    whyWrong:
      "Fairings, flush rivets and streamlining are all parasite-drag measures. Induced drag is attacked at the tip.",
    knowCold: "Block the spanwise flow at the tip.",
    difficulty: 2,
    officialStyle: true,
    source: LIFT(["2.93"]),
  },
  {
    id: "q-da-053",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-induced-drag-reduction"],
    prompt: "Ground effect reduces induced drag because",
    options: [
      "the runway increases air density",
      "the surface interferes with the formation of wingtip vortices",
      "parasite drag falls near the ground",
      "the wing produces less lift near the ground",
    ],
    answer: 1,
    explanation:
      "Close to the surface the vortex cannot fully develop, so downwash and the induced drag that comes with it are reduced.",
    knowCold: "Ground effect interrupts the vortex.",
    difficulty: 2,
    source: LIFT(["2.93"]),
  },
  {
    id: "q-da-054",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-cantilever-wing"],
    prompt: "Which statement about the T-6B's wing is correct?",
    options: [
      "It is externally braced with struts, and low-mounted",
      "It is a single low-mounted full cantilever wing with split flaps inboard of the ailerons",
      "It is a full cantilever wing with slotted flaps outboard of the ailerons",
      "It is a high-mounted full cantilever wing",
    ],
    answer: 1,
    explanation:
      "Full cantilever because all bracing is internal, low-mounted, single, with split flaps integrated into the trailing edge inboard of the ailerons.",
    knowCold: "Single, low, full cantilever, split flaps inboard.",
    difficulty: 2,
    source: BASIC(["2.52"]),
  },
];
