import type { Question, SourceReference } from "@/lib/types";

const TG = (chapter: string, eo: string[]): SourceReference => ({
  document: "Aerodynamics Trainee Guide",
  chapter,
  eo,
});

const LIFT = (eo: string[]) => TG("Lift Production and Drag", eo);
const PERF = (eo: string[]) => TG("Performance and Maneuvering", eo);
const STALL = (eo: string[]) => TG("Stalls", eo);
const SPIN = (eo: string[]) => TG("Spins", eo);
const WAKE = (eo: string[]) => TG("Wake Turbulence and Wind Shear", eo);

/**
 * Assessment depth, units 4–6. Companion to depth-a.ts — see the note there.
 */
export const DEPTH_B_QUESTIONS: Question[] = [
  /* ================= u4 · performance ================= */
  {
    id: "q-db-001",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-thrust-required"],
    prompt: "Minimum thrust required occurs at",
    options: ["stall AOA", "L/Dmax AOA", "maximum velocity", "zero angle of attack"],
    answer: 1,
    explanation:
      "Thrust required is numerically the total drag curve, so its minimum is where drag is least — L/Dmax AOA.",
    knowCold: "Minimum T_R sits at L/Dmax AOA.",
    difficulty: 2,
    officialStyle: true,
    source: LIFT(["2.101", "2.109"]),
  },
  {
    id: "q-db-002",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-thrust-required"],
    prompt: "A thrust required curve is valid for",
    options: [
      "any aircraft of the same type",
      "one specific weight, altitude and configuration",
      "all altitudes at a given weight",
      "any configuration at a given altitude",
    ],
    answer: 1,
    explanation:
      "Change the weight, the altitude or the configuration and you are reading the wrong curve.",
    knowCold: "One curve, one weight, one altitude, one configuration.",
    difficulty: 2,
    source: LIFT(["2.101", "2.109"]),
  },
  {
    id: "q-db-003",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-power-available"],
    prompt: "Power available is",
    options: [
      "the power required to overcome total drag",
      "the power the engines actually produce at a given throttle, velocity and density",
      "the difference between power required and power excess",
      "always constant with velocity",
    ],
    answer: 1,
    explanation:
      "Power available is what the engine is producing. Power required is what the airframe demands. The gap between them is power excess, which is what buys climb.",
    knowCold: "P_A is what the engine gives. P_R is what the airframe needs.",
    difficulty: 2,
    source: LIFT(["2.102", "2.103"]),
  },
  {
    id: "q-db-004",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-power-available", "c-thrust-required"],
    prompt: "Power excess is used to produce",
    options: ["maximum angle of climb", "maximum rate of climb", "maximum endurance", "maximum range"],
    answer: 1,
    explanation:
      "Rate of climb comes from POWER excess; angle of climb comes from THRUST excess. Confusing the two is the classic performance error.",
    whyWrong: "Thrust excess gives you the steepest climb. Power excess gives the fastest one.",
    knowCold: "Thrust excess → angle. Power excess → rate.",
    difficulty: 3,
    officialStyle: true,
    source: LIFT(["2.102", "2.103"]),
  },
  {
    id: "q-db-005",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-weight-curve-shift"],
    prompt: "An increase in weight shifts the thrust required and power required curves",
    options: ["up and left", "up and right", "down and left", "down and right"],
    answer: 1,
    explanation:
      "More weight needs more lift, which at a constant AOA needs more velocity. Both drag and velocity rise, so the curves move up and to the right.",
    knowCold: "Weight up: curves up and right.",
    difficulty: 2,
    officialStyle: true,
    source: LIFT(["2.112"]),
  },
  {
    id: "q-db-006",
    type: "connectChain",
    unit: "u4",
    conceptIds: ["c-weight-curve-shift"],
    prompt: "The aircraft is loaded heavier. Order what follows.",
    trigger: "Weight increases",
    steps: [
      "T_R and P_R shift up and right",
      "T_A and P_A are unaffected",
      "Thrust excess and power excess both decrease",
      "Climb performance decreases",
    ],
    explanation:
      "The engine has not changed, so the available curves stay put. Only the required curves move — and the gap between them is what climbs the aircraft.",
    knowCold: "Weight moves what you NEED, not what you HAVE.",
    difficulty: 3,
    source: LIFT(["2.112"]),
  },
  {
    id: "q-db-007",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-takeoff-landing-speeds"],
    prompt: "Minimum LANDING speed is",
    options: ["1.1 Vs", "1.2 Vs", "1.3 Vs", "1.5 Vs"],
    answer: 2,
    explanation:
      "Landing is 30% above power-off stall speed. Takeoff is 20% above. The exam routinely presents them in the opposite order.",
    whyWrong: "1.2 Vs is the TAKEOFF number.",
    knowCold: "Takeoff 1.2, landing 1.3.",
    difficulty: 2,
    officialStyle: true,
    source: PERF(["2.124"]),
  },
  {
    id: "q-db-008",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-takeoff-landing-speeds"],
    prompt:
      "An aircraft's power-off stall speed is 80 KIAS. Its minimum takeoff speed is approximately",
    options: ["88 KIAS", "96 KIAS", "104 KIAS", "120 KIAS"],
    answer: 1,
    explanation: "1.2 × 80 = 96 KIAS. The landing figure would be 1.3 × 80 = 104 KIAS.",
    knowCold: "1.2 Vs for takeoff.",
    difficulty: 2,
    source: PERF(["2.124"]),
  },
  {
    id: "q-db-009",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-hydroplaning"],
    prompt: "Hydroplaning speed depends primarily on",
    options: ["aircraft weight", "tyre pressure", "runway length", "flap setting"],
    answer: 1,
    explanation:
      "It is a function of tyre pressure, not weight. A heavier aircraft simply makes a larger contact patch at the same pressure.",
    whyWrong:
      "Weight feels like it should matter, and it does not. That is exactly why it is the first distractor.",
    knowCold: "Tyre pressure sets hydroplaning speed.",
    difficulty: 3,
    officialStyle: true,
    source: PERF(["2.150", "2.151"]),
  },
  {
    id: "q-db-010",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-hydroplaning"],
    prompt: "Hydroplaning can occur with standing water more than approximately",
    options: ["0.01 in deep", "0.1 in deep", "1.0 in deep", "2.0 in deep"],
    answer: 1,
    explanation: "A tenth of an inch is enough for the tyre to start skimming.",
    knowCold: "0.1 inch of standing water.",
    difficulty: 2,
    source: PERF(["2.150", "2.151"]),
  },
  {
    id: "q-db-011",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-best-climb-profile"],
    prompt: "The recommended best climb speed for the T-6B is",
    options: ["120 KIAS", "140 KIAS", "160 KIAS", "180 KIAS"],
    answer: 1,
    explanation:
      "140 KIAS. It meets or exceeds any obstacle clearance requirement while giving a greater margin above stall than max angle of climb would.",
    knowCold: "140 KIAS.",
    difficulty: 2,
    officialStyle: true,
    source: PERF(["2.132"]),
  },
  {
    id: "q-db-012",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-best-climb-profile"],
    prompt: "Why does the T-6B fly a best climb speed rather than maximum angle of climb?",
    options: [
      "Max angle of climb is not achievable in a turboprop",
      "At max angle of climb the aircraft can be operating near stall speed",
      "Best climb speed produces a steeper climb",
      "Max angle of climb exceeds the airframe limit load",
    ],
    answer: 1,
    explanation:
      "Max angle of climb puts the aircraft close to stall, so the T-6B trades a little climb angle for a safety margin. Max angle of climb is not flown in the T-6B.",
    knowCold: "Max AOC is near stall, so the T-6B does not fly it.",
    difficulty: 3,
    source: PERF(["2.132"]),
  },
  {
    id: "q-db-013",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-fuel-flow-turboprop"],
    prompt: "For a TURBOPROP, minimum fuel flow in equilibrium flight is found on the",
    options: [
      "thrust required curve",
      "power required curve",
      "thrust available curve",
      "power available curve",
    ],
    answer: 1,
    explanation:
      "A propeller's thrust is not produced directly by the engine — the engine turns a shaft and therefore produces power. So fuel flow varies with power output, and the minimum sits on the power required curve. For a turbojet it would be the thrust required curve.",
    whyWrong:
      "The turbojet answer is the thrust required curve. Getting the engine type wrong flips the whole question.",
    knowCold: "Jet: thrust curve. Prop: power curve.",
    difficulty: 3,
    officialStyle: true,
    source: PERF(["2.135"]),
  },
  {
    id: "q-db-014",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-fuel-flow-turboprop"],
    prompt: "Maximum endurance for the T-6B is achieved at",
    options: ["6.0 units AOA", "8.8 units AOA", "12.0 units AOA", "18 units AOA"],
    answer: 1,
    explanation:
      "8.8 units. Being a turboprop, its endurance point is at a velocity below L/Dmax and an AOA above L/Dmax AOA. 18 units is stall AOA.",
    knowCold: "8.8 units for max endurance.",
    difficulty: 3,
    source: PERF(["2.135"]),
  },
  {
    id: "q-db-015",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-nwlotd"],
    prompt: "Nosewheel liftoff/touchdown speed is",
    options: [
      "the speed at which the nosewheel must be raised on every takeoff",
      "the minimum safe airspeed at which the nosewheel may leave, or must return to, the runway",
      "the maximum speed at which the nosewheel may contact the runway",
      "the stall speed in the landing configuration",
    ],
    answer: 1,
    explanation:
      "It is read from the Takeoff/Landing Crosswind chart in NATOPS and the Dash-1. Lifting the nosewheel below it may let the airplane weathercock into the wind and run off the runway.",
    knowCold: "NWLO/TD is a minimum, and it comes off the crosswind chart.",
    difficulty: 3,
    officialStyle: true,
    source: PERF(["2.147"]),
  },
  {
    id: "q-db-016",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-nwlotd"],
    prompt: "Lifting the nosewheel below NWLO/TD speed in a crosswind may cause the airplane to",
    options: [
      "stall immediately",
      "weathercock into the wind and possibly run off the runway",
      "exceed its limit load factor",
      "porpoise down the runway",
    ],
    answer: 1,
    explanation:
      "With the nosewheel off the ground and insufficient rudder authority, directional control is lost to the weathervaning tendency.",
    knowCold: "Too slow, nose up, and it weathercocks.",
    difficulty: 2,
    source: PERF(["2.147"]),
  },
  {
    id: "q-db-017",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-crosswind-technique"],
    prompt: "During a crosswind landing, the ailerons are used to",
    options: [
      "maintain directional control down the runway",
      "overcome the lateral stability trying to roll the airplane away from the sideslip relative wind",
      "increase lift on the upwind wing",
      "reduce the crosswind component",
    ],
    answer: 1,
    explanation:
      "Directional control is the rudder's job. The aileron is fighting the roll that lateral stability generates in response to the sideslip.",
    whyWrong:
      "'Ailerons for directional control' is stated as wrong in the guide, which makes it the exam's favourite distractor.",
    knowCold: "Rudder steers. Aileron fights the roll.",
    difficulty: 3,
    officialStyle: true,
    source: PERF(["2.148"]),
  },
  {
    id: "q-db-018",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-crosswind-limits"],
    prompt: "The maximum crosswind component for takeoff or landing in the T-6B is",
    options: ["10 knots", "15 knots", "25 knots", "35 knots"],
    answer: 2,
    explanation:
      "25 knots with flaps UP or TO on a dry runway. It drops to 10 knots with flaps LDG, or on a wet runway.",
    knowCold: "25 knots dry, 10 knots wet or flaps LDG.",
    difficulty: 2,
    officialStyle: true,
    source: PERF(["2.149"]),
  },
  {
    id: "q-db-019",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-crosswind-limits"],
    prompt: "For variable or gusting winds, the crosswind component is computed using",
    options: [
      "the average wind angle and average velocity",
      "the maximum wind angle and the maximum gust velocity",
      "the steady-state wind only",
      "the minimum reported velocity",
    ],
    answer: 1,
    explanation:
      "Always the worst case: maximum angle, maximum gust. The limit exists because of the ability to maintain directional control at low speeds, and the gust is what takes it away.",
    knowCold: "Max angle, max gust.",
    difficulty: 3,
    source: PERF(["2.149"]),
  },

  /* ================= u5 · limits, stalls, maneuvering ================= */
  {
    id: "q-db-020",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-turn-weight-thrust-drag"],
    prompt: "Turn rate and turn radius are",
    options: [
      "directly proportional to weight",
      "inversely proportional to weight",
      "independent of weight",
      "proportional to the square root of weight",
    ],
    answer: 2,
    explanation:
      "Any two airplanes able to fly the same velocity and angle of bank can fly formation regardless of weight. The load factor and turn performance are identical, though the heavier one is producing more lift.",
    whyWrong:
      "Weight changes almost every other performance number, which makes 'independent' feel wrong. Here it is correct.",
    knowCold: "Turn performance does not care about weight.",
    difficulty: 3,
    officialStyle: true,
    source: PERF(["2.155", "2.156", "2.157"]),
  },
  {
    id: "q-db-021",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-turn-weight-thrust-drag"],
    prompt:
      "An airplane pulling 5 G produces how much induced drag compared with level flight?",
    options: ["5 times", "10 times", "25 times", "the same"],
    answer: 2,
    explanation:
      "Induced drag is proportional to lift squared, so 5 G costs 25 times the induced drag. This is why thrust can limit turn performance before the airframe does.",
    knowCold: "Induced drag goes as G squared.",
    difficulty: 3,
    source: PERF(["2.155", "2.156", "2.157"]),
  },
  {
    id: "q-db-022",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-turn-weight-thrust-drag"],
    prompt:
      "Maximum thrust can overcome 16 times the level-flight induced drag. The airplane can sustain level flight at",
    options: ["2 G", "4 G", "8 G", "16 G"],
    answer: 1,
    explanation:
      "Induced drag scales with the square of load factor, so 16 times the drag corresponds to √16 = 4 G.",
    knowCold: "Take the square root of the drag multiple.",
    difficulty: 3,
    source: PERF(["2.155", "2.156", "2.157"]),
  },
  {
    id: "q-db-023",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-increasing-maneuverability"],
    prompt: "The two ways to increase an airplane's maneuverability are",
    options: [
      "weaker stability, or larger control surfaces",
      "stronger stability, or larger control surfaces",
      "more thrust, or less weight",
      "more sweep, or more dihedral",
    ],
    answer: 0,
    explanation:
      "Maneuverability is the ease with which the airplane leaves equilibrium, and it is the opposite of stability. Weakening stability or enlarging the control surfaces — which generate larger moments — both increase it.",
    knowCold: "Weaker stability, or bigger control surfaces.",
    difficulty: 2,
    officialStyle: true,
    source: PERF(["2.174"]),
  },
  {
    id: "q-db-024",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-increasing-maneuverability"],
    prompt: "Compared with a fighter, a transport aircraft is designed to be",
    options: [
      "more maneuverable and less stable",
      "more stable and less maneuverable",
      "equally stable and equally maneuverable",
      "less stable and less maneuverable",
    ],
    answer: 1,
    explanation:
      "Stability and maneuverability are opposites, and the mission dictates the compromise. A transport needs stability for long range and ease of landing; a fighter needs maneuverability for high performance turning.",
    knowCold: "Stability and maneuverability trade against each other.",
    difficulty: 1,
    source: PERF(["2.174"]),
  },
  {
    id: "q-db-025",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-boundary-layer"],
    prompt: "At the leading edge, the boundary layer is approximately",
    options: ["1 mm thick", "1 cm thick", "1 in thick", "1 ft thick"],
    answer: 0,
    explanation:
      "About a millimetre, thickening as it moves aft. It is the layer showing local airflow retardation due to viscosity.",
    knowCold: "1 mm at the leading edge, thickening aft.",
    difficulty: 2,
    source: STALL(["3.1"]),
  },
  {
    id: "q-db-026",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-boundary-layer"],
    prompt: "The boundary layer exists because of",
    options: ["air density", "air viscosity", "static pressure", "the adverse pressure gradient"],
    answer: 1,
    explanation:
      "Viscosity is what makes air stick to the surface and retard the local flow. The adverse pressure gradient then acts ON the boundary layer, but it is not what creates it.",
    knowCold: "Viscosity creates the boundary layer.",
    difficulty: 2,
    source: STALL(["3.1"]),
  },
  {
    id: "q-db-027",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-pressure-gradient"],
    prompt:
      "Between maximum thickness and the trailing edge, the pressure gradient is",
    options: [
      "favourable, and helps the boundary layer adhere",
      "adverse, and impedes the flow",
      "neutral",
      "favourable at low AOA and adverse at high AOA",
    ],
    answer: 1,
    explanation:
      "From the leading edge to maximum thickness, pressure falls and the gradient is favourable. Aft of maximum thickness pressure rises again, and the boundary layer has to climb that hill — the adverse gradient.",
    knowCold: "Favourable to max thickness, adverse after it.",
    difficulty: 2,
    officialStyle: true,
    source: STALL(["3.3"]),
  },
  {
    id: "q-db-028",
    type: "connectChain",
    unit: "u5",
    conceptIds: ["c-pressure-gradient"],
    prompt: "Angle of attack increases. Order what follows in the boundary layer.",
    trigger: "AOA increases",
    steps: [
      "Boundary layer kinetic energy decreases",
      "The adverse pressure gradient increases",
      "The separation point moves forward",
    ],
    explanation:
      "The boundary layer has less energy with which to climb a steeper pressure hill, so it separates earlier — and at C_Lmax AOA, separation has moved far enough forward to stall the wing.",
    knowCold: "Higher AOA: less energy, steeper hill, earlier separation.",
    difficulty: 3,
    source: STALL(["3.3"]),
  },
  {
    id: "q-db-029",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-stall-speed-altitude"],
    prompt: "As altitude increases, INDICATED stall speed",
    options: ["increases", "decreases", "does not change", "increases above 10,000 ft only"],
    answer: 2,
    explanation:
      "Indicated airspeed is computed using sea-level density ρ₀, which is a constant, so indicated stall speed does not move with altitude. TRUE stall speed does increase, because local density falls.",
    whyWrong:
      "True stall speed is the one that rises. The question turns entirely on which speed is being asked about.",
    knowCold: "Indicated stall speed is fixed. True stall speed climbs.",
    difficulty: 3,
    officialStyle: true,
    source: STALL(["3.10"]),
  },
  {
    id: "q-db-030",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-stall-speed-altitude"],
    prompt: "True stall speed increases with altitude because",
    options: [
      "the wing produces less lift at altitude",
      "local air density decreases",
      "indicated airspeed becomes unreliable",
      "C_Lmax AOA increases with altitude",
    ],
    answer: 1,
    explanation:
      "Lower density means a higher true velocity is needed to generate the same dynamic pressure and therefore the same lift. C_Lmax AOA does not change with altitude.",
    knowCold: "Thinner air, higher true speed for the same lift.",
    difficulty: 2,
    source: STALL(["3.10"]),
  },
  {
    id: "q-db-031",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-stall-recovery"],
    prompt: "The first action in a stall recovery is to",
    options: [
      "advance the PCL to full power",
      "relax back stick pressure to reduce AOA",
      "level the wings",
      "centre the ball with rudder",
    ],
    answer: 1,
    explanation:
      "RELAX, MAX, LEVEL, BALL. Reducing AOA is what actually breaks the stall — power alone will not, because the wing is stalled by angle of attack, not by lack of speed.",
    knowCold: "RELAX, MAX, LEVEL, BALL.",
    difficulty: 2,
    officialStyle: true,
    source: STALL(["3.6"]),
  },
  {
    id: "q-db-032",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-stall-recovery"],
    prompt: "A stall recovery is complete when the aircraft is",
    options: [
      "below stall AOA",
      "wings level, clean and safely climbing",
      "at full power",
      "back at its original altitude",
    ],
    answer: 1,
    explanation:
      "Breaking the stall is the first step, not the finish. Recovery is complete wings level, clean and safely climbing.",
    knowCold: "Wings level, clean, safely climbing.",
    difficulty: 2,
    source: STALL(["3.6"]),
  },
  {
    id: "q-db-033",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-stall-pattern"],
    prompt: "The most desirable stall pattern begins at the",
    options: ["wingtip", "wing root", "trailing edge", "leading edge of the tip"],
    answer: 1,
    explanation:
      "A root-first stall preserves aileron effectiveness and sends buffet over the tail as a warning. Rectangular wings do this naturally; tapered and swept wings have a strong tip-stall tendency.",
    knowCold: "Root first: keeps the ailerons and warns you.",
    difficulty: 2,
    officialStyle: true,
    source: STALL(["3.17"]),
  },
  {
    id: "q-db-034",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-stall-pattern"],
    prompt: "An ELLIPTICAL wing planform stalls",
    options: [
      "at the root first",
      "at the tip first",
      "everywhere at once, with little warning",
      "progressively from trailing edge to leading edge",
    ],
    answer: 2,
    explanation:
      "Uniform downwash across the span means uniform local AOA, so the whole wing reaches stalling AOA together — aerodynamically efficient, but it gives almost no warning.",
    knowCold: "Elliptical: all at once, no warning.",
    difficulty: 3,
    source: STALL(["3.17"]),
  },
  {
    id: "q-db-035",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-wing-tailoring"],
    prompt: "Geometric twist means",
    options: [
      "the airfoil shape changes from root to tip",
      "the angle of incidence decreases from root to tip",
      "the wing is swept aft at the tip",
      "stall strips are fitted at the root",
    ],
    answer: 1,
    explanation:
      "Lowering the tip's angle of incidence means the root reaches stalling AOA first. Changing the airfoil SHAPE so C_Lmax AOA is higher at the tip is AERODYNAMIC twist.",
    whyWrong: "The airfoil-shape answer is aerodynamic twist, not geometric.",
    knowCold: "Geometric = angle. Aerodynamic = shape.",
    difficulty: 3,
    officialStyle: true,
    source: STALL(["3.18"]),
  },
  {
    id: "q-db-036",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-wing-tailoring"],
    prompt: "Stall fences are used to",
    options: [
      "force the root to separate first",
      "redirect spanwise flow on swept wings",
      "increase C_Lmax at the root",
      "reduce parasite drag at the wing junction",
    ],
    answer: 1,
    explanation:
      "Fences interrupt spanwise flow on a swept wing, which is what drives its tip-stall tendency. Stall STRIPS are the device that forces root separation.",
    knowCold: "Fences redirect spanwise flow. Strips trip the root.",
    difficulty: 3,
    source: STALL(["3.18"]),
  },

  /* ================= u6 · departures and hazards ================= */
  {
    id: "q-db-037",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-empennage-spin"],
    prompt: "A SWEPT vertical fin degrades spin recovery because",
    options: [
      "it reduces total vertical stabiliser area",
      "airflow to the rudder is almost entirely blocked by the horizontal surfaces",
      "it moves the CG aft",
      "it increases the spin rate directly",
    ],
    answer: 1,
    explanation:
      "With the rudder blanked, it cannot generate the force needed to stop the autorotation. The T-6B tail leaves the rudder unblocked and places the horizontal stabiliser farther aft, exposing more rudder in a spin.",
    knowCold: "Swept fin blanks the rudder.",
    difficulty: 3,
    officialStyle: true,
    source: SPIN(["3.25"]),
  },
  {
    id: "q-db-038",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-empennage-spin"],
    prompt: "The T-6B's STRAKES are located in front of the horizontal stabiliser in order to",
    options: [
      "increase the spin rate",
      "increase horizontal stabiliser area, keep the nose pitched down and prevent a flat spin",
      "increase vertical stabiliser area and decrease spin rate",
      "improve rudder authority in a crosswind",
    ],
    answer: 1,
    explanation:
      "The dorsal fin is the one that increases vertical stabiliser area and decreases spin rate. The ventral fin also decreases spin rate and helps hold the nose down.",
    knowCold: "Dorsal: vertical area. Strakes: horizontal area, nose down.",
    difficulty: 3,
    source: SPIN(["3.25"]),
  },
  {
    id: "q-db-039",
    type: "spotTheTrap",
    unit: "u6",
    conceptIds: ["c-empennage-spin"],
    prompt: '"An inverted spin in the T-6B is difficult to enter and difficult to recover from."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. It is difficult to enter and very disorienting, but EASY to recover from, because the entire vertical stabiliser is completely exposed to the relative wind in the inverted position.",
    knowCold: "Inverted spin: hard to enter, easy to recover.",
    difficulty: 3,
    source: SPIN(["3.25"]),
  },
  {
    id: "q-db-040",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-slipstream-swirl"],
    prompt: "Slipstream swirl yaws the T-6B's nose",
    options: ["right, corrected with left rudder", "left, corrected with right rudder", "right, corrected with right rudder", "left, corrected with left rudder"],
    answer: 1,
    explanation:
      "The corkscrewing slipstream strikes the LEFT side of the vertical stabiliser, increasing its AOA. The horizontal lift produced pulls the tail right, which yaws the nose LEFT. Right rudder corrects it.",
    knowCold: "Nose left, right rudder.",
    difficulty: 3,
    officialStyle: true,
    source: PERF(["2.152", "2.153"]),
  },
  {
    id: "q-db-041",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-slipstream-swirl"],
    prompt: "Slipstream swirl is greatest at",
    options: [
      "high power and high airspeed",
      "high power and low airspeed",
      "low power and low airspeed",
      "low power and high airspeed",
    ],
    answer: 1,
    explanation:
      "High power makes the swirl strong; low airspeed means the corkscrew has more time to wrap around the fuselage before reaching the tail. Takeoff is the worst case.",
    knowCold: "High power, low airspeed.",
    difficulty: 2,
    source: PERF(["2.152", "2.153"]),
  },
  {
    id: "q-db-042",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-torque-gyro"],
    prompt:
      "Pitching the T-6B's nose down produces a yaw to the LEFT. This is caused by",
    options: ["torque", "slipstream swirl", "gyroscopic precession", "P-factor"],
    answer: 2,
    explanation:
      "Gyroscopic precession makes a force applied to a spinning propeller act 90° later in the direction of rotation. It strongly influences spin entry characteristics.",
    knowCold: "Precession acts 90° later in the direction of rotation.",
    difficulty: 3,
    officialStyle: true,
    source: PERF(["2.152", "2.153"]),
  },
  {
    id: "q-db-043",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-torque-gyro"],
    prompt: "In the T-6B, engine torque is primarily compensated for by",
    options: [
      "aileron trim alone",
      "rudder and the automatic Trim Aid Device",
      "differential braking",
      "the dorsal fin",
    ],
    answer: 1,
    explanation:
      "Torque is Newton's third law: the propeller turning clockwise rolls the fuselage counter-clockwise. Rudder and the TAD are the primary means of compensating.",
    knowCold: "Rudder and the TAD.",
    difficulty: 2,
    source: PERF(["2.152", "2.153"]),
  },
  {
    id: "q-db-044",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-wake-strength"],
    prompt: "The strongest wingtip vortices are generated by an aircraft that is",
    options: ["heavy, slow and clean", "heavy, fast and clean", "light, slow and dirty", "heavy, slow and dirty"],
    answer: 0,
    explanation:
      "Heavy demands more lift, slow demands a higher C_L, and clean means no flaps to move lift inboard. Lowering the flaps produces more lift at the root, shrinking the tip pressure differential and weakening the vortex.",
    knowCold: "Heavy, slow, clean.",
    difficulty: 2,
    officialStyle: true,
    source: WAKE(["2.188"]),
  },
  {
    id: "q-db-045",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-wake-strength"],
    prompt: "Vortex strength correlates directly with",
    options: ["parasite drag", "induced drag", "interference drag", "form drag"],
    answer: 1,
    explanation:
      "Both come from the same source — the spanwise flow around the tip driven by the pressure differential. Anything that weakens the vortex reduces induced drag, and vice versa.",
    knowCold: "Vortex strength tracks induced drag.",
    difficulty: 3,
    source: WAKE(["2.188"]),
  },
  {
    id: "q-db-046",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-wind-shear"],
    prompt: "Wind shear is defined as",
    options: [
      "a sustained crosswind above 25 knots",
      "a sudden change in wind direction and/or speed over a short distance",
      "the wake left by a preceding aircraft",
      "turbulence caused by terrain",
    ],
    answer: 1,
    explanation:
      "It momentarily changes indicated airspeed and AOA until the aircraft stabilises in the new air mass.",
    knowCold: "Sudden change in direction and/or speed over a short distance.",
    difficulty: 1,
    officialStyle: true,
    source: WAKE(["2.193"]),
  },
  {
    id: "q-db-047",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-wind-shear"],
    prompt: "Wind shear is most hazardous",
    options: [
      "at cruise altitude in the jet stream",
      "at low altitude and low airspeed",
      "at high altitude and high airspeed",
      "during ground taxi operations",
    ],
    answer: 1,
    explanation:
      "Takeoff and landing, where there is neither altitude nor airspeed in reserve to trade while the aircraft stabilises. Common causes include jet streams, land and sea breezes, fronts, inversions and thunderstorms.",
    knowCold: "Low and slow is where it hurts.",
    difficulty: 2,
    source: WAKE(["2.193"]),
  },
  {
    id: "q-db-048",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-crosswind-technique"],
    prompt:
      "In a crosswind, what is trying to roll the airplane away from the sideslip relative wind?",
    options: [
      "Directional stability",
      "Lateral stability",
      "Longitudinal stability",
      "Adverse yaw",
    ],
    answer: 1,
    explanation:
      "Lateral stability responds to the sideslip by rolling the airplane away from the relative wind. The aileron input in a crosswind exists to overcome that roll — not to steer.",
    knowCold: "Lateral stability causes the roll the aileron is fighting.",
    difficulty: 3,
    source: PERF(["2.148"]),
  },
];
