import type { Question, SourceReference } from "@/lib/types";

const LIFT = (eo: string[]): SourceReference => ({
  document: "Aerodynamics Trainee Guide",
  chapter: "Lift Production and Drag",
  eo,
});
const PERF = (eo: string[]): SourceReference => ({
  document: "Aerodynamics Trainee Guide",
  chapter: "Performance and Maneuvering",
  eo,
});

/** Unit 4 — Performance. Turboprop unless a question names a turbojet. */
export const U4_QUESTIONS: Question[] = [
  /* ---------------- Thrust and power ---------------- */
  {
    id: "q-u4-001",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-thrust-required", "c-ldmax"],
    prompt: "The point of minimum thrust required occurs at",
    options: ["CLmax AOA", "L/Dmax AOA", "maximum velocity", "the stall"],
    answer: 1,
    explanation:
      "Thrust required equals total drag in equilibrium flight, so its minimum is the bottom of the total drag curve — L/Dmax.",
    knowCold: "Minimum thrust required = L/Dmax = minimum total drag.",
    difficulty: 2,
    source: LIFT(["2.108", "2.109"]),
  },
  {
    id: "q-u4-002",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-power-required", "c-ldmax"],
    prompt: "On the POWER REQUIRED curve, L/Dmax is located",
    options: [
      "at the bottom of the curve",
      "to the left of the bottom of the curve",
      "to the right of the bottom of the curve",
      "at the far right of the curve",
    ],
    answer: 2,
    explanation:
      "Because P_R = T_R × V, the tangent from the origin touches the power curve to the RIGHT of its minimum. Minimum power required is to the LEFT of L/Dmax.",
    whyWrong:
      "The bottom of the TOTAL DRAG / thrust required curve is L/Dmax. The bottom of the POWER required curve is max endurance for a prop.",
    knowCold: "L/Dmax is at the bottom of T_R but to the RIGHT of the bottom of P_R.",
    difficulty: 3,
    source: LIFT(["2.107", "2.108"]),
  },
  {
    id: "q-u4-003",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-thrust-available"],
    prompt: "For a TURBOPROP, as velocity increases, thrust available",
    options: [
      "increases",
      "decreases",
      "remains approximately constant",
      "increases then decreases sharply",
    ],
    answer: 1,
    explanation:
      "The propeller can only accelerate air to a maximum velocity. As incoming air speeds up, the propeller accelerates it less, so thrust available falls. A turbojet's ram effect offsets this, keeping T_A roughly constant.",
    knowCold: "Prop: T_A falls with speed. Jet: T_A roughly flat.",
    difficulty: 3,
    source: LIFT(["2.103"]),
  },
  {
    id: "q-u4-004",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-prop-efficiency"],
    prompt: "Propeller efficiency is",
    options: [
      "SHP divided by THP",
      "THP divided by SHP",
      "always 100% under ideal conditions in practice",
      "independent of altitude",
    ],
    answer: 1,
    explanation:
      "PE = THP / SHP. It is never 100% because of reduction-gearbox friction and propeller drag, and it falls as density falls.",
    knowCold: "PE = thrust HP ÷ shaft HP. Always under 1, and worse with altitude.",
    difficulty: 2,
    source: LIFT(["2.104", "2.106"]),
  },
  {
    id: "q-u4-005",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-prop-efficiency"],
    prompt: "The T-6B's PT6A-68 engine is flat rated at sea level to",
    options: ["550 SHP", "1,100 SHP", "1,700 SHP", "2,000 SHP"],
    answer: 1,
    explanation:
      "1,100 shaft horsepower. The constant-speed propeller runs at 2,000 RPM, and shaft torque is the pilot's indication of engine power.",
    knowCold: "T-6B: 1,100 SHP, constant-speed prop at 2,000 RPM.",
    difficulty: 2,
    source: LIFT(["2.105"]),
  },

  /* ---------------- Excess thrust and power ---------------- */
  {
    id: "q-u4-006",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-excess-power"],
    prompt:
      "Maximum excess power for a propeller-driven aircraft occurs",
    options: [
      "at an airspeed below L/Dmax",
      "at L/Dmax",
      "at an airspeed above L/Dmax",
      "independent of L/Dmax",
    ],
    answer: 1,
    explanation:
      "For a turboprop, max power excess is AT L/Dmax. For a turbojet it is at a velocity greater than L/Dmax.",
    knowCold: "Prop: max P_E at L/Dmax. Jet: max P_E above L/Dmax.",
    difficulty: 3,
    officialStyle: true,
    source: LIFT(["2.111"]),
  },
  {
    id: "q-u4-007",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-excess-thrust"],
    prompt:
      "Maximum excess THRUST for a propeller-driven aircraft occurs at an airspeed",
    options: [
      "slower than L/Dmax airspeed",
      "equal to L/Dmax airspeed",
      "faster than L/Dmax airspeed",
      "at redline",
    ],
    answer: 0,
    explanation:
      "Because a prop's thrust available falls with speed, the widest gap between T_A and T_R occurs below L/Dmax. For a turbojet, max thrust excess is right at L/Dmax.",
    knowCold: "Prop: max T_E below L/Dmax. Jet: max T_E at L/Dmax.",
    difficulty: 3,
    officialStyle: true,
    source: LIFT(["2.111"]),
  },
  {
    id: "q-u4-008",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-excess-thrust", "c-excess-power"],
    prompt: "Maximum power excess always occurs at a ___ velocity and ___ AOA than maximum thrust excess.",
    options: [
      "greater, lower",
      "greater, higher",
      "lower, lower",
      "lower, higher",
    ],
    answer: 0,
    explanation:
      "Power is thrust times velocity, so the power peak is always pushed toward higher speed — and higher speed in level flight means lower AOA.",
    knowCold: "Max P_E is always faster and at lower AOA than max T_E.",
    difficulty: 3,
    source: LIFT(["2.111"]),
  },
  {
    id: "q-u4-009",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-excess-power", "c-excess-thrust"],
    prompt: "A power excess cannot exist if",
    options: [
      "the aircraft is above L/Dmax",
      "thrust excess is zero",
      "the gear is down",
      "the aircraft is at maximum gross weight",
    ],
    answer: 1,
    explanation:
      "Power is thrust multiplied by velocity. With no surplus thrust there is no surplus power at any speed.",
    knowCold: "No thrust excess → no power excess.",
    difficulty: 3,
    source: LIFT(["2.111"]),
  },

  /* ---------------- Curve shifts ---------------- */
  {
    id: "cs-u4-010",
    type: "curveShift",
    unit: "u4",
    conceptIds: ["c-weight-curve-shift"],
    diagram: { id: "thrust-curves", props: { weight: 1, altitude: 0 } },
    prompt: "The aircraft is loaded 20% heavier.",
    change: "Gross weight increases",
    curveLabel: "Thrust required curve",
    options: ["up", "right", "upRight", "downLeft"],
    answer: "upRight",
    afterProps: { weight: 1.2 },
    explanation:
      "More weight needs more lift, which at constant AOA needs more velocity. Higher velocity and more lift both raise drag, so the T_R curve moves up AND right.",
    knowCold: "Weight ↑ → T_R and P_R shift UP and RIGHT.",
    difficulty: 3,
    source: LIFT(["2.112"]),
  },
  {
    id: "cs-u4-011",
    type: "curveShift",
    unit: "u4",
    conceptIds: ["c-altitude-curve-shift"],
    diagram: { id: "thrust-curves", props: { altitude: 0, weight: 1 } },
    prompt: "The aircraft climbs to a higher altitude at the same weight.",
    change: "Altitude increases",
    curveLabel: "Thrust required curve",
    options: ["right", "up", "upRight", "down"],
    answer: "right",
    afterProps: { altitude: 15000 },
    explanation:
      "Lower density needs a higher velocity for the same lift at the same AOA — but dynamic pressure is unchanged, so drag is unchanged. The T_R curve shifts RIGHT only, not up.",
    whyWrong:
      "The POWER required curve shifts right AND up, because the same thrust is multiplied by a higher velocity. Do not confuse the two.",
    knowCold: "Altitude ↑ → T_R shifts RIGHT only. P_R shifts RIGHT and UP.",
    difficulty: 3,
    source: LIFT(["2.113"]),
  },
  {
    id: "cs-u4-012",
    type: "curveShift",
    unit: "u4",
    conceptIds: ["c-altitude-curve-shift"],
    diagram: { id: "power-curves", props: { altitude: 0, weight: 1 } },
    prompt: "The aircraft climbs to a higher altitude at the same weight.",
    change: "Altitude increases",
    curveLabel: "Power required curve",
    options: ["right", "upRight", "up", "downRight"],
    answer: "upRight",
    afterProps: { altitude: 15000 },
    explanation:
      "P_R = T_R × V. Thrust required is unchanged but occurs at a higher velocity, so the power required curve moves both right and up.",
    knowCold: "Altitude ↑ → P_R shifts RIGHT AND UP.",
    difficulty: 3,
    source: LIFT(["2.113"]),
  },
  {
    id: "cs-u4-013",
    type: "curveShift",
    unit: "u4",
    conceptIds: ["c-config-curve-shift"],
    diagram: { id: "thrust-curves", props: { gear: false } },
    prompt: "The pilot lowers the landing gear.",
    change: "Landing gear extended",
    curveLabel: "Thrust required curve",
    options: ["up", "upLeft", "right", "upRight"],
    answer: "up",
    afterProps: { gear: true },
    explanation:
      "The gear adds parasite drag but does not change the lift the wing produces, so no velocity change is required at a given AOA. The curve moves straight UP.",
    knowCold: "Gear down → T_R and P_R shift straight UP.",
    difficulty: 3,
    source: LIFT(["2.116"]),
  },
  {
    id: "cs-u4-014",
    type: "curveShift",
    unit: "u4",
    conceptIds: ["c-config-curve-shift"],
    diagram: { id: "thrust-curves", props: { flaps: false } },
    prompt: "The pilot lowers the flaps.",
    change: "Flaps extended",
    curveLabel: "Thrust required curve",
    options: ["upLeft", "up", "upRight", "downLeft"],
    answer: "upLeft",
    afterProps: { flaps: true },
    explanation:
      "Flaps increase C_L, so the same lift is available at a lower velocity — the curve moves LEFT. They also greatly increase drag — so it moves UP as well.",
    knowCold: "Flaps down → T_R and P_R shift UP and LEFT.",
    difficulty: 3,
    source: LIFT(["2.115"]),
  },
  {
    id: "q-u4-015",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-altitude-curve-shift"],
    prompt: "As altitude increases, power available",
    options: ["increases", "remains the same", "decreases", "equals thrust available"],
    answer: 2,
    explanation:
      "Maximum engine output falls with density, so both thrust available and power available decrease with altitude.",
    knowCold: "Altitude ↑ → T_A ↓ and P_A ↓.",
    difficulty: 2,
    officialStyle: true,
    source: LIFT(["2.113"]),
  },
  {
    id: "cc-u4-016",
    type: "connectChain",
    unit: "u4",
    conceptIds: ["c-config-curve-shift", "c-excess-thrust"],
    prompt: "Build the chain from gear extension to degraded climb.",
    trigger: "Landing gear is lowered",
    steps: [
      "Parasite drag increases",
      "Thrust required increases",
      "Power required increases",
      "Excess thrust and excess power decrease",
      "Climb performance decreases",
    ],
    explanation:
      "The gear does nothing to the engine, so thrust and power available are unchanged. Everything the gear does happens on the required side, and that eats the excess.",
    knowCold: "Gear down → parasite drag ↑ → T_R/P_R ↑ → excesses ↓ → climb ↓.",
    difficulty: 2,
    source: LIFT(["2.114", "2.116"]),
  },

  /* ---------------- Takeoff and landing ---------------- */
  {
    id: "q-u4-017",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-takeoff-landing-speeds"],
    prompt:
      "The minimum landing speed is ___ times the stall speed while the minimum takeoff speed is ___ times the stall speed.",
    options: ["1/3, 2/3", "1.2, 1.3", "2/3, 1/3", "1.3, 1.2"],
    answer: 3,
    explanation:
      "Landing carries the larger margin: 1.3 Vs. Takeoff is 1.2 Vs. The extra landing margin exists because of low-altitude operation at low power.",
    knowCold: "Takeoff 1.2 Vs (20%). Landing 1.3 Vs (30%).",
    difficulty: 2,
    officialStyle: true,
    source: PERF(["2.124"]),
  },
  {
    id: "q-u4-018",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-takeoff-distance"],
    prompt: "Minimum takeoff distance",
    options: [
      "decreases with a tailwind",
      "increases with a decrease in field elevation",
      "decreases with an increase in field elevation",
      "increases with a tailwind",
    ],
    answer: 3,
    explanation:
      "A tailwind raises the groundspeed needed to reach takeoff airspeed, so the roll gets longer. Lower field elevation means denser air and a SHORTER roll.",
    knowCold: "Headwind shortens the roll; tailwind lengthens it.",
    difficulty: 2,
    officialStyle: true,
    source: PERF(["2.127"]),
  },
  {
    id: "q-u4-019",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-takeoff-distance"],
    prompt:
      "Of the factors affecting takeoff and landing performance, the single largest contributor to increased distance is",
    options: ["temperature", "humidity", "weight", "field elevation"],
    answer: 2,
    explanation:
      "Weight appears squared in the distance equation. Doubling weight quadruples both takeoff and landing distance.",
    knowCold: "Weight doubles → distance ×4.",
    difficulty: 2,
    officialStyle: true,
    source: PERF(["2.127"]),
  },
  {
    id: "q-u4-020",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-4h-club"],
    prompt:
      "As density altitude increases, the INDICATED airspeed required for takeoff",
    options: [
      "increases",
      "decreases",
      "remains constant",
      "increases only above 5,000 ft DA",
    ],
    answer: 2,
    explanation:
      "Indicated takeoff airspeed uses ρ₀, a constant, so it does not change. What changes is the TRUE airspeed and therefore the groundspeed and distance.",
    knowCold: "Indicated takeoff speed is constant. TAS and distance grow with DA.",
    difficulty: 3,
    source: PERF(["2.127"]),
  },
  {
    id: "q-u4-021",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-hydroplaning"],
    prompt: "Hydroplaning speed depends primarily on",
    options: ["aircraft weight", "tyre pressure", "runway length", "flap setting"],
    answer: 1,
    explanation:
      "V_hydroplane (mph) = 9 × √(tyre pressure). Weight only changes the size of the tyre footprint, not the speed.",
    whyWrong:
      "Weight feels like it should matter, and it does not. That is exactly why it is the first distractor.",
    knowCold: "Hydroplaning: 9√(tyre pressure), independent of weight.",
    difficulty: 3,
    officialStyle: true,
    source: PERF(["2.150", "2.151"]),
  },

  /* ---------------- Climb ---------------- */
  {
    id: "q-u4-022",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-vx-vy"],
    prompt: "Vx speed should be used for",
    options: [
      "expedited climb",
      "obstacle clearance",
      "minimum rate of descent",
      "maximum endurance",
    ],
    answer: 1,
    explanation:
      "Vx is maximum ANGLE of climb — the most altitude per unit of ground distance, which is what clears an obstacle. Vy is maximum rate, used to expedite a climb.",
    knowCold: "Vx = angle = obstacle. Vy = rate = expedite.",
    difficulty: 2,
    officialStyle: true,
    source: PERF(["2.129"]),
  },
  {
    id: "q-u4-023",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-vx-vy"],
    prompt: "Gaining the most altitude in a given amount of time is",
    options: [
      "based on the amount of excess thrust available",
      "used for obstacle clearance",
      "max angle of climb",
      "max rate of climb",
    ],
    answer: 3,
    explanation:
      "Altitude per unit TIME is rate of climb — Vy — and it depends on maximum excess POWER, not excess thrust.",
    knowCold: "Angle of climb ← thrust excess. Rate of climb ← power excess.",
    difficulty: 2,
    officialStyle: true,
    source: PERF(["2.129", "2.130"]),
  },
  {
    id: "q-u4-024",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-vx-vy"],
    prompt:
      "A headwind of 30 knots on climb-out will",
    options: [
      "increase maximum angle of climb and leave rate of climb unaffected",
      "increase both angle and rate of climb",
      "decrease maximum angle of climb",
      "have no effect on either",
    ],
    answer: 0,
    explanation:
      "A headwind reduces groundspeed, so the same altitude is reached over less ground — a steeper angle. Wind does not change how fast the aircraft climbs vertically.",
    knowCold: "Headwind improves climb ANGLE only. Rate is unaffected by wind.",
    difficulty: 3,
    source: PERF(["2.131"]),
  },
  {
    id: "q-u4-025",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-ceilings"],
    prompt: "The absolute ceiling is the altitude at which",
    options: [
      "maximum rate of climb is 500 fpm",
      "maximum rate of climb is 100 fpm",
      "maximum power excess and rate of climb are zero",
      "the aircraft reaches critical Mach",
    ],
    answer: 2,
    explanation:
      "Combat 500 fpm, cruise 300 fpm, service 100 fpm, absolute zero. The T-6B's operational ceiling is 31,000 ft.",
    knowCold: "Combat 500 · Cruise 300 · Service 100 · Absolute 0 fpm.",
    difficulty: 3,
    source: PERF(["2.133", "2.134"]),
  },

  /* ---------------- Cruise ---------------- */
  {
    id: "q-u4-026",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-max-endurance"],
    prompt: "Max endurance is",
    options: [
      "achieved by flying L/Dmax AOA and velocity",
      "the maximum distance an airplane can travel for a given amount of fuel",
      "the minimum rate of descent",
      "the maximum time an airplane can remain airborne for a given amount of fuel",
    ],
    answer: 3,
    explanation:
      "Maximum endurance is a TIME measure. For a turboprop it is found at the bottom of the power required curve — not at L/Dmax.",
    whyWrong:
      "Maximum distance for a given fuel is max RANGE. Minimum rate of descent is max GLIDE endurance.",
    knowCold: "Endurance = time. Range = distance.",
    difficulty: 2,
    officialStyle: true,
    source: PERF(["2.136"]),
  },
  {
    id: "q-u4-027",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-max-range", "c-max-endurance"],
    prompt:
      "___ is located at the lowest point of the Total Drag curve whereas ___ is located at the lowest point of the Power Required curve.",
    options: [
      "max range, max endurance",
      "L/Dmax, max range",
      "CLmax, max endurance",
      "max endurance, max range",
    ],
    answer: 0,
    explanation:
      "For a turboprop, max range sits at L/Dmax — the bottom of the total drag / thrust required curve. Max endurance sits at minimum power required.",
    knowCold: "Prop: range at bottom of drag curve, endurance at bottom of power curve.",
    difficulty: 3,
    officialStyle: true,
    source: PERF(["2.137"]),
  },
  {
    id: "q-u4-028",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-max-range", "c-max-endurance"],
    prompt:
      "Transitioning from a max endurance profile to a max range profile, you must ___ your AOA and ___ your velocity.",
    options: [
      "decrease, decrease",
      "decrease, increase",
      "increase, increase",
      "increase, decrease",
    ],
    answer: 1,
    explanation:
      "Max range is FASTER than max endurance. Going faster in level flight means a lower angle of attack.",
    knowCold: "Endurance → range: AOA down, speed up.",
    difficulty: 3,
    officialStyle: true,
    source: PERF(["2.137"]),
  },
  {
    id: "q-u4-029",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-max-range"],
    prompt:
      "Which of the following is NOT true about max range AOA and velocity for a turboprop?",
    options: [
      "Flying max range produces a minimum amount of total drag",
      "Flying max range results in a lower velocity and higher AOA than max endurance",
      "Flying max range results in equal amounts of parasite drag and induced drag",
      "Flying max range occurs at the most efficient AOA",
    ],
    answer: 1,
    explanation:
      "Max range is at L/Dmax: minimum total drag, parasite equal to induced, most efficient AOA — all true. It is a HIGHER velocity and LOWER AOA than max endurance, so option B is the false statement.",
    knowCold: "Max range is faster than max endurance, not slower.",
    difficulty: 3,
    officialStyle: true,
    source: PERF(["2.137"]),
  },
  {
    id: "q-u4-030",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-max-endurance"],
    prompt:
      "To minimize fuel consumption during a flight, you would fly what performance profile?",
    options: ["glide range", "max endurance", "max range", "glide endurance"],
    answer: 1,
    explanation:
      "Max endurance is the minimum fuel flow condition — the slowest rate of fuel burn, at the bottom of the power required curve.",
    knowCold: "Minimum fuel flow = max endurance.",
    difficulty: 2,
    officialStyle: true,
    source: PERF(["2.136", "2.137"]),
  },
  {
    id: "q-u4-031",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-range-endurance-factors"],
    prompt: "An increase in altitude has what effect on max range and max endurance?",
    options: [
      "Both decrease",
      "Both increase",
      "Range increases, endurance decreases",
      "Range decreases, endurance increases",
    ],
    answer: 1,
    explanation:
      "Colder air at altitude makes the turbine more fuel efficient, so fuel flow drops even as the throttle is advanced. Both range and endurance improve.",
    knowCold: "Altitude ↑ → max range ↑ AND max endurance ↑.",
    difficulty: 3,
    source: PERF(["2.138"]),
  },
  {
    id: "q-u4-032",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-range-endurance-factors"],
    prompt: "A headwind will",
    options: [
      "decrease max range and decrease max endurance",
      "decrease max range and leave max endurance unaffected",
      "increase max range and decrease max endurance",
      "leave both unaffected",
    ],
    answer: 1,
    explanation:
      "Range is distance over the GROUND, so a headwind hurts it. Endurance is time airborne and does not care about the wind.",
    knowCold: "Wind affects range, never endurance.",
    difficulty: 2,
    source: PERF(["2.138"]),
  },
  {
    id: "q-u4-033",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-mach"],
    prompt: "Critical Mach is defined as",
    options: [
      "the ratio of true airspeed to the local speed of sound",
      "the speed at which the airplane goes supersonic",
      "the lowest Mach number that produces the first evidence of local supersonic flow",
      "the aircraft's maximum allowable Mach number",
    ],
    answer: 2,
    explanation:
      "Critical Mach is the lowest Mach number at which sonic flow first appears SOMEWHERE on the aircraft — long before the aircraft itself is supersonic.",
    whyWrong: "Option A is Mach number itself, not critical Mach.",
    knowCold: "M_CRIT = first local sonic flow. Set by design; fixed with altitude.",
    difficulty: 3,
    officialStyle: true,
    source: PERF(["2.140"]),
  },
  {
    id: "q-u4-034",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-mach"],
    prompt: "As altitude increases at constant indicated airspeed, Mach number",
    options: ["increases", "decreases", "is unchanged", "first falls then rises"],
    answer: 0,
    explanation:
      "TAS rises for the same IAS, and colder air lowers the local speed of sound. Both effects push the ratio up.",
    knowCold: "Climb at constant IAS → TAS ↑ and LSOS ↓ → Mach ↑.",
    difficulty: 3,
    source: PERF(["2.141"]),
  },

  /* ---------------- Glide ---------------- */
  {
    id: "q-u4-035",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-glide"],
    prompt: "Max glide range (flown at best glide speed) is",
    options: [
      "obtained by flying at L/Dmax airspeed",
      "decreased by a tailwind",
      "not affected by altitude",
      "flown at an airspeed less than L/Dmax airspeed",
    ],
    answer: 0,
    explanation:
      "Max glide range is the minimum angle of descent, which occurs at L/Dmax — for any aircraft regardless of engine type. The T-6B best glide is 125 KIAS, glide ratio 11:1 clean.",
    whyWrong:
      "A tailwind INCREASES glide range. Altitude increases it. Flying slower than L/Dmax gives glide ENDURANCE, not range.",
    knowCold: "Max glide range = L/Dmax, always.",
    difficulty: 2,
    officialStyle: true,
    source: PERF(["2.142", "2.143"]),
  },
  {
    id: "q-u4-036",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-glide"],
    prompt: "An increase in weight during a glide will",
    options: [
      "decrease glide range",
      "increase glide range",
      "leave glide range unchanged but increase rate of descent",
      "leave both range and rate of descent unchanged",
    ],
    answer: 2,
    explanation:
      "Holding L/Dmax AOA keeps the L/D ratio and the descent ANGLE constant, so the distance covered is the same. The heavier aircraft simply flies that same angle faster, so it descends faster and glide endurance drops.",
    knowCold: "Heavier glide: same distance, faster, shorter time aloft.",
    difficulty: 3,
    source: PERF(["2.144"]),
  },
  {
    id: "q-u4-037",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-glide"],
    prompt:
      "After an engine failure, feathering the propeller",
    options: [
      "increases drag and shortens the glide",
      "aligns the blades with the relative wind and improves glide performance",
      "has no aerodynamic effect",
      "is only useful below best glide speed",
    ],
    answer: 1,
    explanation:
      "An unfeathered prop windmills, which drastically increases drag. Feathering aligns each blade with the relative wind and stops that.",
    knowCold: "Windmilling prop = big drag. Feather it.",
    difficulty: 2,
    source: PERF(["2.144"]),
  },
  {
    id: "trap-u4-038",
    type: "spotTheTrap",
    unit: "u4",
    conceptIds: ["c-glide"],
    prompt:
      '"If you are going to land short in a glide, raising the nose above L/Dmax AOA will stretch the glide."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. Any AOA away from L/Dmax AOA reduces the L/D ratio and therefore SHORTENS the horizontal distance travelled. Stretching the glide is a classic fatal error.",
    knowCold: "You cannot stretch a glide. Any deviation from L/Dmax costs distance.",
    difficulty: 3,
    source: PERF(["2.143"]),
  },

  /* ---------------- Reverse command ---------------- */
  {
    id: "q-u4-039",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-reverse-command"],
    prompt:
      "If increasing velocity in the region of reverse command, the pilot should ___ power to balance the ___ in induced drag.",
    options: [
      "decrease, decrease",
      "decrease, increase",
      "increase, decrease",
      "increase, increase",
    ],
    answer: 0,
    explanation:
      "In reverse command, velocity and throttle are INVERSELY related. Speeding up reduces induced drag, so less power is required to hold level flight.",
    knowCold: "Reverse command: faster needs LESS power.",
    difficulty: 3,
    officialStyle: true,
    source: PERF(["2.146"]),
  },
  {
    id: "q-u4-040",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-reverse-command"],
    prompt:
      "When flying at maximum endurance airspeed in the T-6B, increasing AOA to maintain level flight will result in",
    options: [
      "higher airspeed requiring less power",
      "higher airspeed requiring more power",
      "slower airspeed requiring less power",
      "slower airspeed requiring more power",
    ],
    answer: 3,
    explanation:
      "Max endurance is the boundary. Increasing AOA from there drops you into the region of reverse command, where holding altitude at a slower speed demands MORE power.",
    knowCold: "Below max endurance: slower = more power required.",
    difficulty: 3,
    officialStyle: true,
    source: PERF(["2.145", "2.146"]),
  },
  {
    id: "gr-u4-041",
    type: "graphRead",
    unit: "u4",
    conceptIds: ["c-reverse-command", "c-max-endurance", "c-max-range"],
    prompt:
      "Tap the region of REVERSE command on the turboprop power required curve.",
    diagram: { id: "power-curves", props: { showRegions: true } },
    targets: [
      { id: "reverse", label: "Region of reverse command", x: 136, y: 118, r: 34 },
      { id: "normal", label: "Region of normal command", x: 356, y: 118, r: 34 },
      { id: "endurance", label: "Max endurance", x: 232, y: 186, r: 22 },
      { id: "range", label: "Max range", x: 300, y: 172, r: 22 },
    ],
    answer: "reverse",
    explanation:
      "Everything to the LEFT of max endurance airspeed is the region of reverse command — airspeed-unstable, and where most accidents happen.",
    knowCold: "Left of max endurance = reverse command.",
    difficulty: 3,
    source: PERF(["2.145"]),
  },
  {
    id: "cc-u4-042",
    type: "connectChain",
    unit: "u4",
    conceptIds: ["c-reverse-command"],
    prompt:
      "Build the chain that puts an inexperienced pilot 'behind the power curve'.",
    trigger: "Pilot pulls back to slow down in the region of reverse command",
    steps: [
      "Angle of attack increases",
      "Induced drag and power required increase",
      "A power deficit develops",
      "The aircraft descends",
      "Pilot pulls back further and the deficit grows",
    ],
    explanation:
      "The fix is throttle, not stick. Increasing AOA to arrest the descent only deepens the deficit until full power cannot overcome it.",
    knowCold: "Behind the power curve: add power, do not add AOA.",
    difficulty: 3,
    source: PERF(["2.146"]),
  },
  {
    id: "q-u4-043",
    type: "mcq",
    unit: "u4",
    conceptIds: ["c-reverse-command"],
    prompt: "The region of normal command is characterised by",
    options: [
      "airspeed instability",
      "airspeed stability",
      "power required decreasing with speed",
      "operation below stall speed",
    ],
    answer: 1,
    explanation:
      "Above max endurance airspeed, a gust that slows the aircraft creates a thrust excess that accelerates it back, and vice versa. The airspeed self-corrects.",
    knowCold: "Normal command = airspeed stable. Reverse command = unstable.",
    difficulty: 2,
    source: PERF(["2.145"]),
  },
];
