import type { Question, SourceReference } from "@/lib/types";

const PERF = (eo: string[]): SourceReference => ({
  document: "Aerodynamics Trainee Guide",
  chapter: "Performance and Maneuvering",
  eo,
});
const SPINS = (eo: string[]): SourceReference => ({
  document: "Aerodynamics Trainee Guide",
  chapter: "Spins",
  eo,
});
const HAZ = (eo: string[]): SourceReference => ({
  document: "Aerodynamics Trainee Guide",
  chapter: "Wake Turbulence and Wind Shear",
  eo,
});

/** Unit 6 — Departures & Hazards. */
export const U6_QUESTIONS: Question[] = [
  /* ---------------- Slips and skids ---------------- */
  {
    id: "q-u6-001",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-slip", "c-skid"],
    prompt:
      "A ___ results from ___ rudder and leads to a ___ in turn radius and a ___ in turn rate.",
    options: [
      "slip, excessive, decrease, increase",
      "skid, insufficient, increase, decrease",
      "skid, excessive, decrease, decrease",
      "slip, insufficient, increase, decrease",
    ],
    answer: 3,
    explanation:
      "A slip is insufficient rudder in the direction of turn: the nose swings outside, the radius grows and the rate falls. A skid is the mirror image — excessive rudder, nose inside, radius down, rate UP.",
    knowCold: "Slip: insufficient rudder, radius ↑, rate ↓. Skid: excessive rudder, radius ↓, rate ↑.",
    difficulty: 3,
    officialStyle: true,
    source: PERF(["2.161"]),
  },
  {
    id: "q-u6-002",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-skid"],
    prompt:
      "In a skid, the ball will be on the ___ side of the turn needle and the nose will be ___ of the turn.",
    options: [
      "same, outside",
      "opposite, outside",
      "same, inside",
      "opposite, inside",
    ],
    answer: 3,
    explanation:
      "Excessive rudder throws the nose to the inside; centrifugal force throws the ball to the outside — the opposite side from the turn needle.",
    knowCold: "Skid: ball opposite, nose inside. Slip: ball same side, nose outside.",
    difficulty: 3,
    officialStyle: true,
    source: PERF(["2.161"]),
  },
  {
    id: "q-u6-003",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-skid", "c-slip"],
    prompt: "A skidded-turn stall is dangerous because the aircraft will",
    options: [
      "roll toward wings level",
      "roll inverted",
      "pitch straight down",
      "enter ground effect prematurely",
    ],
    answer: 1,
    explanation:
      "A stall in a skid rolls the aircraft inverted — usually fatal at pattern altitude. A stall in a slip rolls toward wings level, which is the safer failure.",
    knowCold: "Skid stall → inverted. Slip stall → wings level.",
    difficulty: 3,
    source: PERF(["2.161"]),
  },
  {
    id: "q-u6-004",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-slip", "c-skid"],
    prompt: "The correct control input for an uncoordinated turn is to",
    options: [
      "apply aileron opposite the ball",
      "step on the ball",
      "reduce power",
      "centre the control stick",
    ],
    answer: 1,
    explanation:
      "Apply rudder in the direction the ball is displaced — 'step on the ball'. Coordination is a rudder problem, not an aileron one.",
    knowCold: "Step on the ball.",
    difficulty: 1,
    source: PERF(["2.161"]),
  },

  /* ---------------- Propeller effects ---------------- */
  {
    id: "q-u6-005",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-slipstream-swirl"],
    prompt:
      "The aircraft's tendency to yaw ___ is due to slipstream swirl, which requires correction via ___.",
    options: [
      "up, left rudder",
      "down, right rudder",
      "left, right rudder",
      "right, left rudder",
    ],
    answer: 2,
    explanation:
      "The corkscrewing slipstream strikes the LEFT side of the vertical stabiliser, pulling the tail right and yawing the nose LEFT. Right rudder corrects it.",
    knowCold: "Slipstream swirl → nose yaws LEFT → right rudder.",
    difficulty: 2,
    officialStyle: true,
    source: PERF(["2.152", "2.153"]),
  },
  {
    id: "q-u6-006",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-p-factor"],
    prompt: "P-factor is most notable during what regimes of flight?",
    options: [
      "at low power settings and high airspeeds",
      "at low power settings and low airspeeds",
      "at high power settings and low airspeeds",
      "at high power settings and high airspeeds",
    ],
    answer: 2,
    explanation:
      "P-factor needs two things: a high power setting and the thrust axis displaced from the relative wind. Low airspeed means high AOA, which is exactly that displacement.",
    knowCold: "P-factor: HIGH power + LOW airspeed → left yaw → right rudder.",
    difficulty: 2,
    officialStyle: true,
    source: PERF(["2.152"]),
  },
  {
    id: "q-u6-007",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-p-factor"],
    prompt:
      "At high angle of attack with the relative wind BELOW the thrust line, the blade producing more thrust is the",
    options: [
      "up-going blade on the left side",
      "down-going blade on the right side",
      "up-going blade on the right side",
      "down-going blade on the left side",
    ],
    answer: 1,
    explanation:
      "With the relative wind below the thrust line the down-going blade on the right meets the air at a larger angle, produces more thrust, and yaws the nose left.",
    knowCold: "Low speed, high AOA: down-going RIGHT blade wins → left yaw.",
    difficulty: 3,
    source: PERF(["2.152"]),
  },
  {
    id: "q-u6-008",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-torque-gyro"],
    prompt:
      "Pitching the nose of the T-6B down produces a left yaw. This is",
    options: ["torque", "P-factor", "slipstream swirl", "gyroscopic precession"],
    answer: 3,
    explanation:
      "A force applied to a spinning propeller acts 90° later in the direction of rotation. Forward force on the top of a clockwise-turning disc emerges as a left yaw.",
    knowCold: "Gyroscopic precession: the effect shows up 90° later in the rotation.",
    difficulty: 3,
    source: PERF(["2.152"]),
  },

  /* ---------------- Spins ---------------- */
  {
    id: "q-u6-009",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-spin-definition"],
    prompt: "The two conditions needed for a spin are",
    options: [
      "exceeding CLmax AOA and a pitching moment",
      "exceeding CLmax AOA and a yawing moment",
      "exceeding L/Dmax AOA and a pitching moment",
      "exceeding L/Dmax AOA and a yawing moment",
    ],
    answer: 1,
    explanation:
      "Stall plus yaw. Both are required — remove either and the aircraft cannot spin.",
    whyWrong:
      "L/Dmax AOA is nowhere near the stall. A pitching moment does not produce autorotation.",
    knowCold: "Spin = stall + yaw.",
    difficulty: 2,
    officialStyle: true,
    source: SPINS(["3.19", "3.23"]),
  },
  {
    id: "q-u6-010",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-spin-definition"],
    prompt: "Autorotation is",
    options: [
      "the rotation of the propeller after engine failure",
      "a self-propagating combination of roll and yaw caused by asymmetrically stalled wings",
      "the rotation of the aircraft about the vertical axis in a coordinated turn",
      "another name for gyroscopic precession",
    ],
    answer: 1,
    explanation:
      "A spin is an aggravated stall that results in autorotation — the asymmetry between the two stalled wings feeds the rotation.",
    knowCold: "Autorotation: asymmetric stall feeding its own roll and yaw.",
    difficulty: 2,
    source: SPINS(["3.20"]),
  },
  {
    id: "q-u6-011",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-spin-wings"],
    prompt:
      "During a spin, the ___ wing is more stalled and experiences an increase in ___.",
    options: ["upgoing, drag", "downgoing, drag", "downgoing, lift", "upgoing, lift"],
    answer: 1,
    explanation:
      "The down-going (inside) wing sees a roll relative wind from beneath, giving it a higher AOA. Higher AOA past the stall means lower C_L and MORE drag.",
    knowCold: "Down-going wing: AOA ↑, CL ↓, drag ↑ — more stalled.",
    difficulty: 3,
    officialStyle: true,
    source: SPINS(["3.21"]),
  },
  {
    id: "cc-u6-012",
    type: "connectChain",
    unit: "u6",
    conceptIds: ["c-spin-wings", "c-spin-definition"],
    prompt: "Build the chain that sustains autorotation.",
    trigger: "The aircraft stalls and yaw is introduced",
    steps: [
      "The down-going wing sees a roll relative wind from below",
      "Down-going wing AOA increases; up-going wing AOA decreases",
      "Lift differential sustains the roll",
      "Drag differential sustains the yaw",
      "Roll and yaw together sustain autorotation",
    ],
    explanation:
      "Both wings are stalled and neither loses all its lift. It is the DIFFERENCE between them that keeps the spin going.",
    knowCold: "Lift differential → roll. Drag differential → yaw. Together → spin.",
    difficulty: 3,
    source: SPINS(["3.21"]),
  },
  {
    id: "q-u6-013",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-spin-recovery"],
    prompt: "In a right spin, the greatest anti-spin force comes from",
    options: ["full right rudder", "full left rudder", "neutral rudder", "full right aileron"],
    answer: 1,
    explanation:
      "Anti-spin rudder — opposite the spin — presents the maximum rudder area to the relative wind, maximising the drag that opposes the yaw.",
    knowCold: "Rudder FULL OPPOSITE to the turn needle deflection.",
    difficulty: 2,
    officialStyle: true,
    source: SPINS(["3.27"]),
  },
  {
    id: "cc-u6-014",
    type: "connectChain",
    unit: "u6",
    conceptIds: ["c-spin-recovery"],
    prompt: "Order the T-6B spin recovery.",
    trigger: "Spin confirmed on the turn needle",
    steps: [
      "Gear, flaps and speed brake — retracted",
      "PCL — IDLE",
      "Rudder — full opposite to turn needle deflection",
      "Control stick — forward of neutral, ailerons neutral",
      "Smoothly recover to level flight after rotation stops",
    ],
    explanation:
      "Configuration clean, power off, opposite rudder to stop the yaw, forward stick to break the stall, then a controlled pull-out.",
    knowCold: "Clean · Idle · Opposite rudder · Stick forward · Recover.",
    difficulty: 2,
    source: SPINS(["3.27"]),
  },
  {
    id: "q-u6-015",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-spin-recovery"],
    prompt: "The only reliable cockpit indicator of spin DIRECTION is the",
    options: [
      "balance ball",
      "turn needle",
      "attitude gyro",
      "AOA indexer",
    ],
    answer: 1,
    explanation:
      "The trainee guide is explicit: the balance ball gives no useful indication of spin direction and should be disregarded. The attitude gyro may be tumbling.",
    knowCold: "Spin direction: TURN NEEDLE. Ignore the ball.",
    difficulty: 3,
    source: SPINS(["3.26"]),
  },
  {
    id: "q-u6-016",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-spin-recovery"],
    prompt: "Ailerons are held neutral during a T-6B spin recovery because",
    options: [
      "aileron deflection would over-stress the wing",
      "the deeply stalled wing gives them almost no useful airflow",
      "they are mechanically locked out during a spin",
      "they would increase the rate of descent",
    ],
    answer: 1,
    explanation:
      "With the wing in a deep stall there is very little useful air flowing over the ailerons, so they rarely assist recovery.",
    knowCold: "Neutral ailerons: they have nothing to work with in a deep stall.",
    difficulty: 2,
    source: SPINS(["3.27"]),
  },
  {
    id: "q-u6-017",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-spin-factors"],
    prompt: "An accelerated spin is caused by",
    options: [
      "holding the control stick full aft",
      "holding the control stick anywhere other than full aft",
      "applying pro-spin rudder",
      "extending the landing gear",
    ],
    answer: 1,
    explanation:
      "Full aft stick gives the flattest attitude and the slowest rotation — an unaccelerated spin. Any other stick position steepens the pitch and speeds the rotation up.",
    knowCold: "Full aft stick = flattest and slowest. Anything else accelerates the spin.",
    difficulty: 3,
    officialStyle: true,
    source: SPINS(["3.24"]),
  },
  {
    id: "q-u6-018",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-spin-factors"],
    prompt:
      "Compared with a lighter aircraft, a heavier aircraft will",
    options: [
      "enter a spin faster with greater oscillations and recover faster",
      "enter a spin more slowly with fewer oscillations and take longer to recover",
      "be unable to spin at all",
      "always enter a flat spin",
    ],
    answer: 1,
    explanation:
      "Wing-carried weight gives a large moment of inertia. That resists spin entry, damps the oscillations — and equally resists the recovery.",
    knowCold: "Heavy: slow in, slow out. Light: fast in, fast out.",
    difficulty: 3,
    officialStyle: true,
    source: SPINS(["3.24"]),
  },
  {
    id: "q-u6-019",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-spin-factors"],
    prompt:
      "Because of gyroscopic precession, a T-6B in a RIGHT spin will have",
    options: [
      "a flatter attitude and slower rotation",
      "a more nose-down attitude, higher rotation rate and a more oscillatory entry",
      "identical characteristics to a left spin",
      "an immediate transition to a flat spin",
    ],
    answer: 1,
    explanation:
      "Yawing right pitches the nose down through precession, which shortens the moment arm and speeds the rotation. A left spin is the flatter, slower, smoother one.",
    knowCold: "T-6B right spin: nose lower, faster, rougher. Left spin: flatter, slower.",
    difficulty: 3,
    officialStyle: true,
    source: SPINS(["3.24"]),
  },
  {
    id: "q-u6-020",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-spin-factors"],
    prompt: "A progressive spin results when the pilot",
    options: [
      "applies full opposite rudder but inadvertently maintains full aft stick",
      "maintains pro-spin rudder while moving the stick forward",
      "applies aileron in the direction of the spin",
      "retracts the flaps during recovery",
    ],
    answer: 0,
    explanation:
      "Opposite rudder with the stick still full aft causes the nose to pitch steeply down and the aircraft to SNAP into a reversed rotation. Pro-spin rudder with forward stick is the AGGRAVATED spin.",
    knowCold: "Progressive: opposite rudder + full aft stick. Aggravated: pro-spin rudder + forward stick.",
    difficulty: 3,
    officialStyle: true,
    source: SPINS(["3.28", "3.29"]),
  },
  {
    id: "q-u6-021",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-spin-factors"],
    prompt: "The T-6B is",
    options: [
      "prone to flat spins at aft CG",
      "aerodynamically incapable of entering a flat spin",
      "cleared for intentional inverted spins",
      "unable to recover from an erect spin below 5,000 ft",
    ],
    answer: 1,
    explanation:
      "Strakes ahead of the horizontal stabiliser keep the nose pitched down. The T-6B is aerodynamically incapable of a flat spin, and intentional inverted spins are prohibited.",
    knowCold: "T-6B: no flat spins possible; inverted spins prohibited.",
    difficulty: 3,
    source: SPINS(["3.22", "3.25"]),
  },

  /* ---------------- Stability ---------------- */
  {
    id: "q-u6-022",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-static-stability"],
    prompt: "Static stability is",
    options: [
      "the motion of an object over time after a disturbance",
      "the initial tendency of an object to move toward or away from equilibrium",
      "the tendency to oscillate about equilibrium",
      "the same thing as maneuverability",
    ],
    answer: 1,
    explanation:
      "Static = the INITIAL tendency. Dynamic = what happens over TIME. Static instability guarantees dynamic instability.",
    knowCold: "Static: initial tendency. Dynamic: behaviour over time.",
    difficulty: 2,
    source: PERF(["2.169", "2.170"]),
  },
  {
    id: "q-u6-023",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-stability-contributors"],
    prompt:
      "Which airframe component is the largest positive contributor to DIRECTIONAL static stability?",
    options: [
      "the horizontal stabiliser",
      "the vertical stabiliser",
      "dihedral wings",
      "the fuselage",
    ],
    answer: 1,
    explanation:
      "The vertical stabiliser is a symmetric airfoil far behind the CG. In a sideslip it generates a horizontal lift force with a long moment arm — the weathervane effect.",
    whyWrong:
      "The horizontal stabiliser is the top LONGITUDINAL contributor; dihedral is the top LATERAL contributor; the fuselage is negative for both directional and longitudinal.",
    knowCold: "Longitudinal → horizontal stab. Directional → vertical stab. Lateral → dihedral.",
    difficulty: 3,
    officialStyle: true,
    source: PERF(["2.177"]),
  },
  {
    id: "q-u6-024",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-stability-contributors"],
    prompt:
      "A component whose aerodynamic centre is BEHIND the aircraft's centre of gravity is",
    options: [
      "a negative contributor to longitudinal static stability",
      "a positive contributor to longitudinal static stability",
      "irrelevant to longitudinal stability",
      "a positive contributor to lateral stability only",
    ],
    answer: 1,
    explanation:
      "If a disturbance raises AOA, extra lift behind the CG pitches the nose back down toward the original attitude. AC ahead of the CG does the opposite.",
    knowCold: "AC behind CG = stabilising. AC ahead of CG = destabilising.",
    difficulty: 3,
    source: PERF(["2.175"]),
  },
  {
    id: "q-u6-025",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-dynamic-modes"],
    prompt: "Dutch roll results from",
    options: [
      "strong directional stability and weak lateral stability",
      "strong lateral stability and weak directional stability",
      "negative directional stability",
      "negative longitudinal stability",
    ],
    answer: 1,
    explanation:
      "Strong lateral stability keeps snapping the wings level while weak directional stability lets the nose hunt — the 'tail wagging' motion. The reverse combination gives spiral divergence.",
    knowCold: "Dutch roll: lateral strong, directional weak. Spiral divergence: the reverse.",
    difficulty: 3,
    source: PERF(["2.180", "2.181"]),
  },
  {
    id: "q-u6-026",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-dynamic-modes"],
    prompt: "Adverse yaw is caused by",
    options: [
      "increased parasite drag on the down-going wing",
      "increased induced drag on the up-going wing",
      "the rudder deflecting with the ailerons",
      "spanwise flow over the wingtip",
    ],
    answer: 1,
    explanation:
      "The up-going wing produces more lift, so it also produces more induced drag. That retards it and yaws the nose away from the direction of roll.",
    knowCold: "Adverse yaw: more lift → more induced drag → yaw away from the roll.",
    difficulty: 3,
    source: PERF(["2.183"]),
  },
  {
    id: "q-u6-027",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-static-stability"],
    prompt: "Stability and maneuverability are",
    options: [
      "the same property measured two ways",
      "opposites — a stable aircraft is harder to move out of equilibrium",
      "independent of each other",
      "both increased by moving the CG aft of the neutral point",
    ],
    answer: 1,
    explanation:
      "A designer buys maneuverability with weak stability or with larger control surfaces. The mission dictates the compromise: transports stable, fighters maneuverable.",
    knowCold: "Stability and maneuverability trade against each other.",
    difficulty: 2,
    source: PERF(["2.173", "2.174"]),
  },

  /* ---------------- Wake turbulence ---------------- */
  {
    id: "q-u6-028",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-wake-strength"],
    prompt: "Wake turbulence is weakened by",
    options: [
      "heavier, slower, and clean configured aircraft",
      "lighter, faster, dirty configured aircraft",
      "lighter, faster, clean configured aircraft",
      "heavier, slower, and dirty configured aircraft",
    ],
    answer: 1,
    explanation:
      "Greatest vortex strength is HEAVY, SLOW and CLEAN. The weakest case is the exact opposite: light, fast and dirty.",
    knowCold: "Strongest wake: heavy, slow, clean. Weakest: light, fast, dirty.",
    difficulty: 2,
    officialStyle: true,
    source: HAZ(["2.188"]),
  },
  {
    id: "q-u6-029",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-wake-turbulence"],
    prompt: "Wake turbulence is generated",
    options: [
      "only by heavy aircraft",
      "only by helicopters at hover",
      "only when an aircraft's flaps are extended",
      "by any aircraft whenever it is producing lift",
    ],
    answer: 3,
    explanation:
      "Vortices are a by-product of lift. Every aircraft producing lift makes a vortex hazard, from rotation until the nosewheel touches down.",
    knowCold: "Lift is being produced → a wake exists.",
    difficulty: 1,
    officialStyle: true,
    source: HAZ(["2.187"]),
  },
  {
    id: "q-u6-030",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-wake-turbulence"],
    prompt: "The key hazards created by wake turbulence are",
    options: [
      "low visibility and reduced engine performance",
      "slower climb rates and adverse yaw",
      "induced roll and the induced flow field",
      "longer takeoff distances and induced pitch changes",
    ],
    answer: 2,
    explanation:
      "Induced roll can exceed the roll authority of the encountering aircraft. The induced flow field between the vortices produces downwash up to 1,500 fpm.",
    knowCold: "Wake hazards: induced roll + induced flow field.",
    difficulty: 2,
    officialStyle: true,
    source: HAZ(["2.189"]),
  },
  {
    id: "q-u6-031",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-wake-behavior"],
    prompt: "Wingtip vortices sink at approximately ___ and level off about ___ below the flight path.",
    options: [
      "100–200 fpm, 300 ft",
      "400–500 fpm, 900 ft",
      "900–1,000 fpm, 400 ft",
      "1,500 fpm, 2,500 ft",
    ],
    answer: 1,
    explanation:
      "400 to 500 feet per minute, levelling off about 900 ft below. Once they touch the ground they move laterally outward at about 5 knots.",
    knowCold: "Vortices: sink 400–500 fpm, level off 900 ft below, drift 5 kt on the ground.",
    difficulty: 3,
    source: HAZ(["2.187"]),
  },
  {
    id: "q-u6-032",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-wake-avoidance"],
    prompt:
      "How should a pilot take off after a larger airplane recently took off on the same runway?",
    options: [
      "taxi back to the line and cancel the flight",
      "take off after the airplane's point of liftoff",
      "take off prior to the airplane's point of liftoff",
      "take off prior to the airplane's point of roll",
    ],
    answer: 2,
    explanation:
      "No vortices exist before the departing aircraft's nosewheel leaves the runway, so rotating before that point — and climbing above its flight path — keeps you clear.",
    knowCold: "Rotate BEFORE their liftoff point, and stay above their flight path.",
    difficulty: 2,
    officialStyle: true,
    source: HAZ(["2.191"]),
  },
  {
    id: "q-u6-033",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-wake-avoidance"],
    prompt:
      "T-6B minimum spacing behind a heavy aircraft is ___ minutes for takeoff and ___ minutes for landing.",
    options: ["2, 2", "2, 3", "3, 2", "3, 3"],
    answer: 1,
    explanation:
      "Two minutes for takeoff, three for landing. A heavy is over 255,000 lb; the same takeoff spacing is recommended behind a large aircraft (41,000–255,000 lb).",
    knowCold: "Takeoff 2 minutes. Landing 3 minutes.",
    difficulty: 3,
    source: HAZ(["2.190"]),
  },
  {
    id: "q-u6-034",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-wake-avoidance"],
    prompt:
      "When landing behind a larger airplane that has just LANDED, you should touch down",
    options: [
      "before its nosewheel touchdown point",
      "beyond its nosewheel touchdown point",
      "at exactly its touchdown point",
      "on the parallel runway",
    ],
    answer: 1,
    explanation:
      "The hazard ceases once the preceding aircraft's nosewheel is on the runway, so landing beyond that point keeps you out of the wake. Stay at or above its final approach path on the way in.",
    knowCold: "Land BEYOND their touchdown point. Rotate BEFORE their rotation point.",
    difficulty: 3,
    source: HAZ(["2.192"]),
  },
  {
    id: "q-u6-035",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-wake-behavior"],
    prompt:
      "A 4–6 knot crosswind on landing is particularly hazardous because it",
    options: [
      "doubles the strength of both vortices",
      "holds the upwind vortex stationary over the touchdown zone",
      "causes both vortices to leave the runway immediately",
      "prevents the vortices from sinking",
    ],
    answer: 1,
    explanation:
      "Ground vortices move outward at about 5 knots, so a 4–6 knot crosswind cancels the upwind vortex's drift and parks it in the touchdown zone — while pushing the downwind one toward a parallel runway.",
    knowCold: "4–6 kt crosswind parks the upwind vortex on the runway.",
    difficulty: 3,
    source: HAZ(["2.187"]),
  },
  {
    id: "q-u6-036",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-wake-turbulence"],
    prompt:
      "The most significant factor affecting your ability to counteract wake-induced roll is",
    options: [
      "engine thrust available",
      "relative wingspan between the two aircraft",
      "the encountering aircraft's weight",
      "the vertical separation only",
    ],
    answer: 1,
    explanation:
      "If your wingspan and ailerons extend beyond the vortex's rotational flow, counter-control usually works. Short-span aircraft cannot reach outside the vortex and lose the fight.",
    knowCold: "Relative wingspan decides whether you can out-roll a vortex.",
    difficulty: 3,
    source: HAZ(["2.189"]),
  },

  /* ---------------- Wind shear ---------------- */
  {
    id: "q-u6-037",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-wind-shear"],
    prompt: "Wind shear is",
    options: [
      "a sustained crosswind above 15 knots",
      "a sudden change in wind direction and/or speed over a short distance",
      "the turbulence behind a heavy aircraft",
      "the downwash between two wingtip vortices",
    ],
    answer: 1,
    explanation:
      "Wind shear boundaries can be vertical or horizontal. It is most often caused by jet streams, land/sea breezes, fronts, inversions and thunderstorms.",
    knowCold: "Wind shear: sudden change in wind speed and/or direction over a short distance.",
    difficulty: 1,
    source: HAZ(["2.193"]),
  },
  {
    id: "q-u6-038",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-wind-shear-performance"],
    prompt:
      "How will a wind shear that decreases your headwind component by 20 knots affect your aircraft?",
    options: [
      "Indicated airspeed will decrease 20 knots, thereby decreasing lift",
      "Indicated airspeed will increase 20 knots, thereby increasing lift",
      "Indicated airspeed will decrease 20 knots, thereby increasing lift",
      "There would be no appreciable effect",
    ],
    answer: 0,
    explanation:
      "IAS is a direct readout of dynamic pressure. Losing 20 knots of headwind loses 20 knots of dynamic pressure and therefore lift — a decreasing performance shear.",
    knowCold: "Lose headwind → lose IAS → lose lift.",
    difficulty: 2,
    officialStyle: true,
    source: HAZ(["2.196"]),
  },
  {
    id: "q-u6-039",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-wind-shear-performance"],
    prompt:
      "On approach you pass through a shear that changes the wind from a 10 knot tailwind to a 10 knot headwind. How will this shear affect your aircraft?",
    options: [
      "IAS increases by 10 knots, lift decreases, aircraft descends below glidepath",
      "IAS increases by 20 knots, lift decreases, aircraft descends below glidepath",
      "IAS increases by 20 knots, lift increases, aircraft climbs above glidepath",
      "IAS decreases by 10 knots, lift decreases, aircraft climbs above glidepath",
    ],
    answer: 2,
    explanation:
      "The total swing is 20 knots, not 10. That is an increasing performance shear: more IAS, more lift, ballooning above glidepath.",
    knowCold: "Tailwind to headwind: add both numbers. Increasing performance shear.",
    difficulty: 3,
    officialStyle: true,
    source: HAZ(["2.196"]),
  },
  {
    id: "q-u6-040",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-wind-shear-performance"],
    prompt: "An aircraft flown into a microburst will initially encounter",
    options: [
      "a strong headwind",
      "a strong tailwind",
      "a pure downdraft with no horizontal component",
      "no change until the core is reached",
    ],
    answer: 0,
    explanation:
      "The initial encounter is an INCREASING performance shear — a headwind that makes the aircraft balloon. The pilot's instinct is nose-down, which is exactly wrong when the strong decreasing shear follows moments later.",
    knowCold: "Microburst: performance increase FIRST, then the killing decrease.",
    difficulty: 3,
    officialStyle: true,
    source: HAZ(["2.196", "2.197"]),
  },
  {
    id: "q-u6-041",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-wind-shear-procedures"],
    prompt:
      "An aircraft reported wind shear on final with a 10 knot loss of airspeed. How should you adjust your approach?",
    options: [
      "Subtract 10 knots from your approach speed",
      'Set flaps to "Takeoff" and maintain your normal approach speed',
      "Delay landing for 2 minutes",
      'Set flaps to "Takeoff" and add 10 knots to your approach speed',
    ],
    answer: 3,
    explanation:
      "Takeoff flaps mean less drag and quicker acceleration; the extra 10 knots restores the margin the shear will take away. Expect to land long.",
    knowCold: "Shear on final: flaps TAKEOFF, +10 knots, expect to land long.",
    difficulty: 3,
    officialStyle: true,
    source: HAZ(["2.197"]),
  },
  {
    id: "cc-u6-042",
    type: "connectChain",
    unit: "u6",
    conceptIds: ["c-wind-shear-performance"],
    prompt:
      "Build the chain for a DECREASING performance wind shear on final approach.",
    trigger: "Headwind component suddenly drops",
    steps: [
      "Indicated airspeed decreases",
      "Dynamic pressure and lift decrease",
      "The aircraft pitches down and sinks below glidepath",
      "Pilot adds power and raises the nose to recover",
    ],
    explanation:
      "At very low altitude there may be neither the time nor the power to arrest the sink — which is why this is the most hazardous shear a pilot can meet.",
    knowCold: "Decreasing shear: IAS ↓ → lift ↓ → below glidepath. Power, now.",
    difficulty: 3,
    source: HAZ(["2.195", "2.196"]),
  },
  {
    id: "q-u6-043",
    type: "mcq",
    unit: "u6",
    conceptIds: ["c-wind-shear-procedures"],
    prompt: "The best technique for dealing with wind shear is to",
    options: [
      "add power and fly through it",
      "avoid it — delay, divert or go around",
      "reduce flaps to zero",
      "increase the rate of descent to get below it quickly",
    ],
    answer: 1,
    explanation:
      "If moderate to strong shear is expected, delay the takeoff or landing. Any time shear is actually experienced, consider going around.",
    knowCold: "Wind shear: avoid first, fly through only if you must.",
    difficulty: 1,
    source: HAZ(["2.198"]),
  },
];
