import type { Question, SourceReference } from "@/lib/types";

/**
 * The recognition half of the question bank.
 *
 * Navigation is mostly application, but the exam still opens with forty items
 * of vocabulary, definitions and directional logic — and those are exactly the
 * ones a student loses by being almost right. Every question here is either
 * transcribed from an official sheet or written against a specific trap the
 * source calls out.
 *
 * Questions marked `officialStyle` come from Assignment Sheets 6-1-3, 6-2-3
 * and 6-7-3, the Navigation Practice Exam printed in the trainee guide, or the
 * NETSAFA Navigation final examination booklet.
 */

const TG = (chapter: string, eo: string[]): SourceReference => ({
  document: "Navigation Trainee Guide",
  chapter,
  eo,
});

const EXAM = (eo: string[]): SourceReference => ({
  document: "Navigation Final Examination",
  chapter: "NETSAFA Navigation, Test Booklet No. 4",
  eo,
});

const C1 = "Introduction to Air Navigation";
const C2 = "Chart Projections, Plotting and Global Timekeeping";
const C3 = "CR-3 Air Navigation Computer";
const C4 = "Airspeeds";
const C5 = "Preflight Winds";
const C6 = "In Flight Winds";
const C7 = "Flight Planning and Conduct";

export const CONCEPT_QUESTIONS: Question[] = [
  /* ================= n1 ================= */
  {
    id: "nq-c-001",
    type: "mcq",
    unit: "n1",
    conceptIds: ["nav-types", "nav-dead-reckoning"],
    prompt: "Which of the following is NOT a basic type of air navigation?",
    options: ["Dead reckoning", "Autopilot", "Visual", "Electronic"],
    answer: 1,
    explanation:
      "The three types are dead reckoning, visual and electronic. An autopilot flies a heading; it does not work out where you are.",
    knowCold: "Three types: dead reckoning, visual, electronic.",
    difficulty: 1,
    officialStyle: true,
    source: TG(C1, ["2.331"]),
  },
  {
    id: "nq-c-002",
    type: "mcq",
    unit: "n1",
    conceptIds: ["nav-visual", "nav-types"],
    prompt: "Which navigation method relies on adequate visibility?",
    options: ["Dead reckoning", "Visual", "Electronic", "Radar"],
    answer: 1,
    explanation:
      "Visual navigation requires direct sight of the surface, so it fails in cloud or at night. That limitation is why it is a back-up to DR rather than a substitute.",
    difficulty: 1,
    officialStyle: true,
    source: TG(C1, ["2.331"]),
  },
  {
    id: "nq-c-003",
    type: "mcq",
    unit: "n1",
    conceptIds: ["nav-dr-components"],
    prompt: "The four components of dead reckoning navigation are position, direction, time and ___.",
    options: ["altitude", "temperature", "chart work", "speed"],
    answer: 3,
    explanation:
      "Position, direction, time and speed. Altitude and temperature matter, but only because they change speed — they are not components in their own right.",
    knowCold: "Position, direction, time, speed. Know three, find the fourth.",
    difficulty: 1,
    officialStyle: true,
    source: TG(C1, ["2.332"]),
  },
  {
    id: "nq-c-004",
    type: "connectChain",
    unit: "n1",
    conceptIds: ["nav-dead-reckoning", "nav-dr-components"],
    prompt: "Put the dead-reckoning cycle in order.",
    trigger: "A known starting position",
    steps: [
      "Apply a direction",
      "Apply a speed over a time",
      "Arrive at a computed position",
      "Fix it visually or electronically and start again",
    ],
    explanation:
      "Dead reckoning is a chain from a known position, not a one-off calculation. Each fix becomes the next starting point, which is why the guide calls navigation both the history and the prediction of the flight path.",
    difficulty: 2,
    source: TG(C1, ["2.332"]),
  },
  {
    id: "nq-c-005",
    type: "mcq",
    unit: "n1",
    conceptIds: ["nav-primary-instruments", "nav-bdhi"],
    prompt:
      "The three instruments essential for dead reckoning navigation are the compass, the clock, and the ___.",
    options: ["sextant", "temperature gauge", "altimeter", "airspeed indicator"],
    answer: 3,
    explanation:
      "One instrument per measurable component: compass for direction, clock for time, airspeed indicator for speed.",
    whyWrong:
      "The altimeter and the temperature gauge are the two SECONDARY instruments — they feed density, which affects true airspeed.",
    knowCold: "Primary: compass, clock, airspeed. Secondary: altimeter, OAT.",
    difficulty: 1,
    officialStyle: true,
    source: TG(C1, ["2.333"]),
  },
  {
    id: "nq-c-006",
    type: "mcq",
    unit: "n1",
    conceptIds: ["nav-secondary-instruments"],
    prompt: "The secondary instruments used in DR navigation are the",
    options: [
      "OAT and airspeed indicator",
      "compass and airspeed indicator",
      "altimeter and OAT",
      "OAT and compass",
    ],
    answer: 2,
    explanation:
      "Altimeter and outside air temperature. Between them they give the air density that turns calibrated airspeed into true airspeed.",
    difficulty: 1,
    officialStyle: true,
    source: TG(C1, ["2.333"]),
  },
  {
    id: "nq-c-007",
    type: "mcq",
    unit: "n1",
    conceptIds: ["nav-bdhi", "nav-standby-compass"],
    prompt: "The aircrew's primary instrument for determining direction is the",
    options: ["wet compass", "#2 needle", "gyro indicator", "remote gyro vertical compass card"],
    answer: 3,
    explanation:
      "The remote gyro vertical compass card — the BDHI or EHSI. The stand-by compass is the back-up.",
    difficulty: 1,
    officialStyle: true,
    source: TG(C1, ["2.333"]),
  },
  {
    id: "nq-c-008",
    type: "spotTheTrap",
    unit: "n1",
    conceptIds: ["nav-standby-compass"],
    prompt: '"The stand-by compass is stabilised by gyroscopes to damp needle movement."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. It is filled with fluid — hence 'wet compass'. Its virtue is that it needs no gyros and no electrical power, which is exactly why it is the back-up.",
    knowCold: "Wet compass: fluid-damped, unstable manoeuvring, independent of electrics.",
    difficulty: 2,
    officialStyle: true,
    source: TG(C1, ["2.333"]),
  },
  {
    id: "nq-c-009",
    type: "spotTheTrap",
    unit: "n1",
    conceptIds: ["nav-latitude-longitude"],
    prompt: '"Latitude is divided into minutes. Each minute has 60 degrees."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False, and backwards. Each DEGREE has 60 minutes. The exam prints this inversion because it is easy to skim past.",
    difficulty: 1,
    officialStyle: true,
    source: TG(C1, ["2.330"]),
  },
  {
    id: "nq-c-010",
    type: "mcq",
    unit: "n1",
    conceptIds: ["nav-latitude-longitude"],
    prompt: "Latitude is measured along ___ and longitude is measured along ___.",
    options: [
      "a parallel, a meridian",
      "a meridian, a parallel",
      "a line of latitude, a line of longitude",
      "None of the above",
    ],
    answer: 1,
    explanation:
      "You count latitude up a meridian and longitude along a parallel. The line you count along is at right angles to the thing you are measuring — which is also why distance is only ever measured up a meridian.",
    knowCold: "Latitude up a meridian. Longitude along a parallel.",
    difficulty: 2,
    officialStyle: true,
    source: TG(C1, ["2.330"]),
  },
  {
    id: "nq-c-011",
    type: "mcq",
    unit: "n1",
    conceptIds: ["nav-latitude-longitude", "nav-elapsed-time"],
    prompt: "Which of these is written correctly for a position and a time en route?",
    options: [
      "087° 19'W, 30° 22'N and an ETE of 1400",
      "30° 22'N, 087° 19'W and an ETE of 2+30",
      "30° 22'N, 87° 19'W and an ETE of 0230",
      "N 30.22, W 87.19 and an ETE of 2.30",
    ],
    answer: 1,
    explanation:
      "Latitude first, longitude in three digits, and elapsed time written with a plus sign to keep it distinct from a time of day.",
    difficulty: 2,
    source: TG(C1, ["2.330"]),
  },
  {
    id: "nq-c-012",
    type: "mcq",
    unit: "n1",
    conceptIds: ["nav-electronic", "nav-tacan-station"],
    prompt: "A TACAN gives the aircrew position by providing",
    options: [
      "latitude and longitude directly",
      "distance in nautical miles and magnetic bearing from the station",
      "true course and groundspeed",
      "a continuously updated dead-reckoning plot",
    ],
    answer: 1,
    explanation:
      "Distance and magnetic bearing. Because the station's position is known, that relationship fixes you over the earth.",
    difficulty: 1,
    source: TG(C1, ["2.331"]),
  },
  {
    id: "nq-c-013",
    type: "mcq",
    unit: "n1",
    conceptIds: ["nav-electronic"],
    prompt: "Which of the following is NOT a basic method of air navigation?",
    options: ["Electronic", "Inertial", "Dead reckoning", "Visual"],
    answer: 1,
    explanation:
      "Inertial navigation is a category of electronic navigation — a self-contained, very fast DR computer — not a fourth method alongside it.",
    difficulty: 2,
    officialStyle: true,
    source: EXAM(["2.331"]),
  },
  {
    id: "nq-c-014",
    type: "mcq",
    unit: "n1",
    conceptIds: ["nav-definition", "nav-dead-reckoning"],
    prompt: "Air navigation is best defined as",
    options: [
      "flying a published route between two airfields",
      "determining geographic position and maintaining the desired direction relative to the earth's surface",
      "using electronic aids to remain within controlled airspace",
      "the calculation of fuel required for a mission",
    ],
    answer: 1,
    explanation:
      "Position and direction relative to the surface. Everything else in the course — the wheel, the chart, the log — exists to serve those two.",
    difficulty: 1,
    source: TG(C1, ["2.330"]),
  },
  {
    id: "nq-c-015",
    type: "mcq",
    unit: "n1",
    conceptIds: ["nav-visual", "nav-dead-reckoning"],
    prompt: "Why is visual navigation described as not being a stand-alone form of navigation?",
    options: [
      "It cannot be used above 10,000 feet",
      "Without a DR plot the aviator is likely to misidentify ground references and become lost",
      "It requires a second crew member",
      "Charts do not show enough ground detail",
    ],
    answer: 1,
    explanation:
      "The guide is blunt about it: without DR you do not know which river you are looking at. Ground references confirm a position you already expect; they do not supply one.",
    knowCold: "Visual and electronic support DR. Neither replaces the plot.",
    difficulty: 2,
    source: TG(C1, ["2.331"]),
  },

  /* ================= n2 ================= */
  {
    id: "nq-c-016",
    type: "mcq",
    unit: "n2",
    conceptIds: ["nav-great-circle"],
    prompt: "The shortest distance between any two points on the earth's surface is a",
    options: ["route over the north pole", "concentric circle", "constant heading", "great circle route"],
    answer: 3,
    explanation:
      "A great circle — the arc of a circle whose plane passes through the centre of the earth.",
    difficulty: 1,
    officialStyle: true,
    source: TG(C2, ["2.334"]),
  },
  {
    id: "nq-c-017",
    type: "mcq",
    unit: "n2",
    conceptIds: ["nav-great-circle"],
    prompt: "A great circle route is desirable because",
    options: ["it is the shortest distance", "it saves time", "it saves fuel", "all of the above"],
    answer: 3,
    explanation:
      "Shortest distance, and therefore less time and less fuel. The three are the same fact stated three ways.",
    difficulty: 1,
    officialStyle: true,
    source: TG(C2, ["2.334"]),
  },
  {
    id: "nq-c-018",
    type: "mcq",
    unit: "n2",
    conceptIds: ["nav-great-circle", "nav-small-circle"],
    prompt:
      "On a Lambert conformal chart, every ___ is a great circle, but only one ___, the ___, is a great circle.",
    options: [
      "meridian, parallel, equator",
      "parallel, meridian, prime meridian",
      "curved line, parallel, equator",
      "straight line, meridian, international date line",
    ],
    answer: 0,
    explanation:
      "Every meridian bisects the earth, so all of them are great circles. Of the parallels, only the equator passes through the centre.",
    knowCold: "All meridians are great circles. Of the parallels, only the equator.",
    difficulty: 2,
    officialStyle: true,
    source: TG(C2, ["2.334"]),
  },
  {
    id: "nq-c-019",
    type: "mcq",
    unit: "n2",
    conceptIds: ["nav-lambert"],
    prompt:
      "On a Lambert conformal chart, parallels appear as ___ lines, and meridians appear as ___ lines.",
    options: ["straight, curved", "curved, straight", "straight, straight", "curved, curved"],
    answer: 1,
    explanation:
      "Parallels are equally spaced concentric circles, so they curve. Meridians are straight lines converging on the poles. Most people guess the reverse.",
    difficulty: 2,
    officialStyle: true,
    source: TG(C2, ["2.335"]),
  },
  {
    id: "nq-c-020",
    type: "spotTheTrap",
    unit: "n2",
    conceptIds: ["nav-lambert", "nav-onc-tpc"],
    prompt:
      '"The meridians of the ONC and TPC are oriented to the magnetic north pole, so course lines plotted on them are magnetic courses."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. Lambert meridians point at TRUE north, so a line drawn on the chart is a true course. That single fact is why variation exists as a step in every plotting problem.",
    knowCold: "Chart lines are true. Cockpit headings are magnetic. Variation is the bridge.",
    difficulty: 2,
    officialStyle: true,
    source: TG(C2, ["2.335"]),
  },
  {
    id: "nq-c-021",
    type: "mcq",
    unit: "n2",
    conceptIds: ["nav-onc-tpc"],
    prompt: "What is the scale of the Tactical Pilotage Chart?",
    options: ["1:50,000", "1:100,000", "1:1,000,000", "1:500,000"],
    answer: 3,
    explanation:
      "The TPC is 1:500,000 and shows more ground detail; the ONC is 1:1,000,000 and is for long-range planning.",
    knowCold: "TPC 1:500,000 · ONC 1:1,000,000.",
    difficulty: 1,
    officialStyle: true,
    source: EXAM(["2.335"]),
  },
  {
    id: "nq-c-022",
    type: "mcq",
    unit: "n2",
    conceptIds: ["nav-lambert", "nav-mercator"],
    prompt: "Which of these is NOT true of a Lambert conformal chart?",
    options: [
      "Distortion is held to a minimum",
      "Scale is basically constant",
      "Great circles are curved lines",
      "Meridians converge toward the true poles",
    ],
    answer: 2,
    explanation:
      "On a Lambert, great circles plot as straight lines — which is precisely what makes it useful. Curved great circles are the Mercator's problem.",
    difficulty: 2,
    officialStyle: true,
    source: EXAM(["2.335"]),
  },
  {
    id: "nq-c-023",
    type: "mcq",
    unit: "n2",
    conceptIds: ["nav-undevelopable", "nav-lambert"],
    prompt: "Why is a cone used to develop a Lambert projection?",
    options: [
      "Because a cone can be flattened without stretching or tearing",
      "Because a cone touches the earth at the poles",
      "Because a cone gives the largest possible chart",
      "Because a cone removes all distortion",
    ],
    answer: 0,
    explanation:
      "A sphere is undevelopable; a cone is not. Laying the graticule onto a developable surface is the only way to get it onto flat paper at all, and some distortion always survives.",
    difficulty: 2,
    source: TG(C2, ["2.335"]),
  },
  {
    id: "nq-c-024",
    type: "mcq",
    unit: "n2",
    conceptIds: ["nav-mercator", "nav-lambert"],
    prompt: "Why is the Mercator used less often for air navigation?",
    options: [
      "It cannot show polar regions",
      "Its distance scale varies and great circles plot as curves",
      "It has no meridians",
      "It is only published at 1:50,000",
    ],
    answer: 1,
    explanation:
      "A variable distance scale and curved great circles make measuring awkward, which is exactly the pair of things a navigator needs to be easy.",
    difficulty: 2,
    source: TG(C2, ["2.335"]),
  },

  /* ================= n3 ================= */
  {
    id: "nq-c-025",
    type: "mcq",
    unit: "n3",
    conceptIds: ["nav-track", "nav-course", "nav-heading"],
    prompt: "The actual path an aircraft travels between two points is known as its",
    options: ["course", "track", "drift", "heading"],
    answer: 1,
    explanation: "Track is what happened. Course is what you intended. Heading is where the nose was pointing.",
    knowCold: "Course intended · heading pointed · track achieved.",
    difficulty: 1,
    officialStyle: true,
    source: TG(C2, ["2.336"]),
  },
  {
    id: "nq-c-026",
    type: "mcq",
    unit: "n3",
    conceptIds: ["nav-course", "nav-heading"],
    prompt: "A true course is always",
    options: [
      "the actual path the aircraft has flown over the ground",
      "the same as the aircraft's true heading",
      "the intended flight path of the aircraft",
      "measured relative to the nose of the aircraft",
    ],
    answer: 2,
    explanation:
      "The intended path. It only equals heading when there is no crosswind, and it only equals track when the wind did what the forecaster said.",
    difficulty: 1,
    officialStyle: true,
    source: TG(C2, ["2.336"]),
  },
  {
    id: "nq-c-027",
    type: "mcq",
    unit: "n3",
    conceptIds: ["nav-isogonic", "nav-variation"],
    prompt: "Isogonic lines connect points of equal",
    options: ["elevation", "deviation", "variation", "pressure"],
    answer: 2,
    explanation:
      "Equal variation. On a TPC they are dashed blue lines with the value printed in degrees.",
    difficulty: 1,
    officialStyle: true,
    source: TG(C2, ["2.337"]),
  },
  {
    id: "nq-c-028",
    type: "mcq",
    unit: "n3",
    conceptIds: ["nav-variation", "nav-true-vs-magnetic-north"],
    prompt:
      "The angular difference from true north to magnetic north from any given position is called",
    options: ["deviation", "isolation", "magnetic variation", "strangulation"],
    answer: 2,
    explanation:
      "Variation, expressed in degrees east or west depending on which side of true north the magnetic pole lies from where you are.",
    difficulty: 1,
    officialStyle: true,
    source: TG(C2, ["2.337"]),
  },
  {
    id: "nq-c-029",
    type: "numeric",
    unit: "n3",
    conceptIds: ["nav-variation-conversion"],
    skillIds: ["sk-variation"],
    prompt:
      "You measure a true course of 045° near Pensacola, where the variation is 2° East. What is the magnetic course?",
    given: [
      { label: "True course", value: "045°" },
      { label: "Variation", value: "2° East" },
    ],
    fields: [{ key: "mc", label: "Magnetic course", unit: "deg", answer: 43, tolerance: "direction", wraps: true }],
    worked: [
      { action: "East is least: easterly variation comes off a true course.", detail: "MC = TC − East." },
      { action: "045 − 2.", result: "043°" },
    ],
    explanation: "East is least: 045 − 2 = 043° magnetic. Westerly variation would have been added instead.",
    knowCold: "East is least, west is best — going from true to magnetic.",
    difficulty: 1,
    officialStyle: true,
    source: TG(C2, ["2.338"]),
  },
  {
    id: "nq-c-030",
    type: "numeric",
    unit: "n3",
    conceptIds: ["nav-variation-conversion", "nav-tacan-fix"],
    skillIds: ["sk-variation"],
    prompt:
      "You are on the 135° radial of a station where the variation is 7° East, and you want to plot that radial on the chart. What TRUE radial do you draw?",
    given: [
      { label: "Magnetic radial", value: "135°" },
      { label: "Variation at the station", value: "7° East" },
    ],
    fields: [{ key: "tr", label: "True radial", unit: "deg", answer: 142, tolerance: "direction", wraps: true }],
    estimate: {
      prompt: "Going from magnetic to true with easterly variation, does the number get bigger or smaller?",
      options: ["Bigger", "Smaller", "Unchanged"],
      answer: 0,
      why: "The usual rule subtracts easterly variation going true → magnetic. This is the reverse trip, so the formula reverses with it and the 7° is added.",
    },
    allowedTools: ["chart", "reference"],
    worked: [
      {
        action: "Notice the direction of travel: the radial is magnetic and the chart is true.",
        detail: "That is the opposite of the usual conversion, so the formula flips.",
      },
      { action: "135 + 7.", result: "142° true" },
      { action: "Plot 142° out from the station and mark the DME along it.", tool: "chart" },
    ],
    explanation:
      "Radials are magnetic; the chart is true. Going magnetic → true, easterly variation is ADDED: 135 + 7 = 142°. This reversal is the single most common error in TACAN position fixing.",
    knowCold: "Plotting a radial: magnetic → true, so east ADDS.",
    difficulty: 3,
    officialStyle: true,
    source: TG(C2, ["2.338", "4.7"]),
  },
  {
    id: "nq-c-031",
    type: "mcq",
    unit: "n3",
    conceptIds: ["nav-direction"],
    prompt: "Direction in air navigation is stated",
    options: [
      "from 000° to 359°",
      "from 001° to 360°",
      "in decimal degrees to one place",
      "in mils",
    ],
    answer: 1,
    explanation:
      "Whole numbers from 001° to a maximum of 360°. There is no 000 — due north is 360.",
    difficulty: 2,
    source: TG(C2, ["2.336"]),
  },
  {
    id: "nq-c-032",
    type: "mcq",
    unit: "n3",
    conceptIds: ["nav-true-vs-magnetic-north", "nav-variation"],
    prompt: "Where is the magnetic north pole currently located?",
    options: [
      "At the geographic north pole",
      "Near Hudson Bay in northern Canada",
      "In northern Siberia",
      "It moves too fast to be located",
    ],
    answer: 1,
    explanation:
      "Near Hudson Bay — far enough from true north that the angle between them, the variation, is worth a step in every plotting problem.",
    difficulty: 1,
    source: TG(C2, ["2.337"]),
  },
  {
    id: "nq-c-033",
    type: "mcq",
    unit: "n3",
    conceptIds: ["nav-crab-drift", "nav-heading", "nav-track"],
    prompt:
      "Which of the following is the difference between true heading and track, measured either left or right of true heading?",
    options: ["true course", "crab angle", "drift angle", "variation"],
    answer: 2,
    explanation:
      "Drift angle. Crab angle is the same size, measured the other way — the correction you apply rather than the error you suffer.",
    difficulty: 2,
    officialStyle: true,
    source: EXAM(["2.336"]),
  },

  /* ================= n4 ================= */
  {
    id: "nq-c-034",
    type: "mcq",
    unit: "n4",
    conceptIds: ["nav-time-zones"],
    prompt: "How many degrees of longitude wide is one time zone, and why?",
    options: [
      "10°, because the earth turns 36° an hour",
      "15°, because the earth turns 360° in 24 hours",
      "24°, one for each hour",
      "30°, because there are twelve zones",
    ],
    answer: 1,
    explanation: "360 divided by 24 is 15° an hour, which gives 24 zones each centred on a multiple of 15°.",
    knowCold: "15° of longitude to the hour.",
    difficulty: 1,
    source: TG(C2, ["4.1"]),
  },
  {
    id: "nq-c-035",
    type: "mcq",
    unit: "n4",
    conceptIds: ["nav-zone-description"],
    prompt: "Why can a zone description not be reliably found by dividing local longitude by 15?",
    options: [
      "Because longitude is measured in minutes",
      "Because zone boundaries follow geographic and political lines, and daylight saving moves them",
      "Because the earth's rotation is not constant",
      "Because the prime meridian is not at 0°",
    ],
    answer: 1,
    explanation:
      "Cities are not split between zones, some countries use one zone across three, and daylight saving shifts the value. Look it up in the en route supplement.",
    difficulty: 2,
    source: TG(C2, ["4.1"]),
  },
  {
    id: "nq-c-036",
    type: "mcq",
    unit: "n4",
    conceptIds: ["nav-gmt"],
    prompt: "Why is Greenwich mean time used as the standard for aviation?",
    options: [
      "Because most flights depart from Europe",
      "Because it is the same all over the world at any given instant",
      "Because it never changes for daylight saving",
      "Because it is halfway between the extremes of local time",
    ],
    answer: 1,
    explanation:
      "One clock everywhere. Weather briefs and flight plans are filed in Zulu precisely so that nobody has to reason about zones mid-flight.",
    difficulty: 1,
    source: TG(C2, ["4.1"]),
  },
  {
    id: "nq-c-037",
    type: "numeric",
    unit: "n4",
    conceptIds: ["nav-fly-in-zulu", "nav-zulu-conversion"],
    skillIds: ["sk-zulu-leg"],
    prompt:
      "You depart NAS Whidbey Island (ZD −8) at 1100 local with a flight time of 4+00 to NAS Pensacola (ZD −6). What is your local time of arrival?",
    given: [
      { label: "Departure", value: "1100 local, ZD −8" },
      { label: "Flight time", value: "4+00" },
      { label: "Destination", value: "ZD −6" },
    ],
    fields: [{ key: "eta", label: "Local time of arrival", unit: "clock", answer: 17 * 60, tolerance: "exact" }],
    estimate: {
      prompt: "You are flying east across two time zones. Will the local arrival time be more or less than 1500?",
      options: ["More than 1500", "Less than 1500", "Exactly 1500"],
      answer: 0,
      why: "Four hours of flying takes you to 1500 in the departure zone, but you have crossed into a zone two hours ahead, so the local clock has gained.",
    },
    allowedTools: ["timezone", "scratch"],
    worked: [
      { action: "Convert the take-off to Zulu: GMT = LMT − (ZD).", detail: "1100 − (−8) = 1900Z.", result: "1900Z" },
      { action: "Fly in Zulu: add the four hours there.", result: "2300Z" },
      { action: "Convert the landing to local: LMT = GMT + (ZD).", detail: "2300 + (−6).", result: "1700 local" },
    ],
    explanation:
      "Convert out, add the time en route in Zulu, convert back: 1900Z off, 2300Z down, 1700 local. Never add flight time to a local clock across zones.",
    knowCold: "Convert out, fly in Zulu, convert back.",
    difficulty: 2,
    officialStyle: true,
    source: TG(C2, ["4.2"]),
  },
  {
    id: "nq-c-038",
    type: "numeric",
    unit: "n4",
    conceptIds: ["nav-fly-in-zulu", "nav-zulu-conversion"],
    skillIds: ["sk-zulu-leg"],
    prompt:
      "A P-8 departs San Francisco (ZD −8) at 1300 local on 2 January. Sixteen hours later it arrives in Tokyo (ZD +9). What is the local time of arrival?",
    given: [
      { label: "Departure", value: "1300 local, ZD −8" },
      { label: "Flight time", value: "16+00" },
      { label: "Destination", value: "ZD +9" },
    ],
    fields: [{ key: "eta", label: "Local time of arrival", unit: "clock", answer: 22 * 60, tolerance: "exact" }],
    allowedTools: ["timezone", "scratch"],
    worked: [
      { action: "Take-off in Zulu: 1300 − (−8).", result: "2100Z on 2 January" },
      { action: "Add sixteen hours.", detail: "2100 + 16 rolls past midnight.", result: "1300Z on 3 January" },
      { action: "Convert to Tokyo local: 1300 + (+9).", result: "2200 local on 3 January" },
    ],
    explanation:
      "2100Z off, 1300Z the next day, 2200 local in Tokyo. The date rolls in Zulu, which is exactly why the middle step is done there.",
    difficulty: 3,
    officialStyle: true,
    source: TG(C2, ["4.2"]),
  },
  {
    id: "nq-c-039",
    type: "spotTheTrap",
    unit: "n4",
    conceptIds: ["nav-zulu-conversion"],
    prompt: '"A zone description of −6 means Greenwich mean time is six hours BEHIND local time."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. GMT = LMT − (ZD), and subtracting a negative adds: local 0700 is 1300Z. Zulu is six hours AHEAD.",
    knowCold: "Subtracting a negative adds. −6 means Zulu is six hours later.",
    difficulty: 2,
    source: TG(C2, ["4.2"]),
  },

  /* ================= n5 ================= */
  {
    id: "nq-c-040",
    type: "mcq",
    unit: "n5",
    conceptIds: ["nav-plotter", "nav-dividers"],
    prompt: "Why should the distance scales printed on the plotter's straightedge not be used?",
    options: [
      "They are only marked in statute miles",
      "They are not accurate — the dividers measure distance",
      "They only work on the ONC",
      "They are on the wrong side of the plotter",
    ],
    answer: 1,
    explanation:
      "The guide says so outright. Distance comes from the dividers, carried to a meridian and counted.",
    knowCold: "Plotter for direction. Dividers for distance.",
    difficulty: 2,
    source: TG(C2, ["4.6"]),
  },
  {
    id: "nq-c-041",
    type: "mcq",
    unit: "n5",
    conceptIds: ["nav-measuring-distance"],
    prompt: "In measuring distance on a Lambert conformal chart, the length is transferred to",
    options: ["any parallel", "the statute mile conversion scale", "any meridian", "the nautical mile conversion scale"],
    answer: 2,
    explanation:
      "Any meridian. One minute of arc along a great circle is one nautical mile, and all meridians are great circles.",
    knowCold: "Measure distance up a meridian. Never along a parallel.",
    difficulty: 2,
    officialStyle: true,
    source: EXAM(["4.5"]),
  },
  {
    id: "nq-c-042",
    type: "mcq",
    unit: "n5",
    conceptIds: ["nav-measuring-distance"],
    prompt: "Five nautical miles is equivalent to",
    options: [
      "5 minutes of latitude measured along a parallel",
      "5 minutes of latitude measured along a meridian",
      "5 minutes of longitude measured along a meridian",
      "5 degrees of latitude measured along a meridian",
    ],
    answer: 1,
    explanation:
      "Minutes of LATITUDE, counted up a MERIDIAN. The degrees marked on the longitude lines are degrees of latitude — that is what you are counting.",
    difficulty: 3,
    officialStyle: true,
    source: EXAM(["4.5"]),
  },
  {
    id: "nq-c-043",
    type: "mcq",
    unit: "n5",
    conceptIds: ["nav-measuring-direction", "nav-north-south-scale"],
    prompt:
      "You are measuring a course that runs almost due north. No meridian will come under the grommet. What do you do?",
    options: [
      "Use the distance scale on the straightedge instead",
      "Put a parallel under the grommet and read the inner north/south scale",
      "Measure the reciprocal and add 180",
      "Move to a different chart",
    ],
    answer: 1,
    explanation:
      "The inner north/south scale exists for exactly this. Grommet on a meridian reads the outer scale; grommet on a parallel reads the inner one.",
    knowCold: "Meridian → outer scale. Parallel → inner north/south scale.",
    difficulty: 2,
    source: TG(C2, ["4.6"]),
  },
  {
    id: "nq-c-044",
    type: "mcq",
    unit: "n5",
    conceptIds: ["nav-measuring-direction"],
    prompt: "Why does the guide insist you estimate the direction before reading the plotter?",
    options: [
      "To speed up the measurement",
      "Because the scale offers two answers and only the estimate can choose between them",
      "Because the plotter has no numbers below 180",
      "To decide which chart to use",
    ],
    answer: 1,
    explanation:
      "Every meridian crosses both scales, so there are always two candidate readings 180° apart. Without an estimate, half your courses come out as reciprocals.",
    knowCold: "Estimate first, or you will read the reciprocal.",
    difficulty: 2,
    source: TG(C2, ["4.6"]),
  },
  {
    id: "nq-c-045",
    type: "mcq",
    unit: "n5",
    conceptIds: ["nav-measuring-direction"],
    prompt: "What is 'bracketing' the meridian, and what does it prevent?",
    options: [
      "Drawing two course lines — it prevents a plotting slip",
      "Reading the scale numbers to both left and right of the meridian — it prevents a ten-degree error",
      "Measuring the leg twice — it prevents a distance error",
      "Using two meridians at once — it prevents convergence error",
    ],
    answer: 1,
    explanation:
      "Reading the numbers on both sides tells you which way the scale is counting, and the scale counts up to the LEFT. Skip it and you can be ten degrees out with a perfectly plausible answer.",
    difficulty: 3,
    source: TG(C2, ["4.6"]),
  },
  {
    id: "nq-c-046",
    type: "mcq",
    unit: "n5",
    conceptIds: ["nav-speed-marks", "nav-pulling-coordinates"],
    prompt: "On a meridian, which mark extends on both sides of the line?",
    options: ["Every minute", "Every five minutes", "Every ten minutes", "Every whole degree only"],
    answer: 2,
    explanation:
      "The ten-minute mark crosses the meridian; the five-minute mark is longer than a minute mark but stays on the left. That is how you count sixty miles without counting sixty ticks.",
    knowCold: "Ten-minute marks cross the line. Five-minute marks sit left of it.",
    difficulty: 2,
    source: TG(C2, ["4.3"]),
  },
  {
    id: "nq-c-047",
    type: "connectChain",
    unit: "n5",
    conceptIds: ["nav-pulling-coordinates", "nav-plotter"],
    prompt: "Order the steps for pulling a latitude off the chart.",
    trigger: "Find the point on the chart",
    steps: [
      "Align the grommet and the 90° mark along a meridian",
      "Slide the plotter down until the straightedge touches the point",
      "Mark where the straightedge crosses the meridian",
      "Count up from the nearest whole degree using the speed marks",
    ],
    explanation:
      "Align, slide, mark, count. Longitude is the same four steps rotated ninety degrees, against a parallel instead of a meridian.",
    difficulty: 2,
    source: TG(C2, ["4.3"]),
  },
  {
    id: "nq-c-048",
    type: "connectChain",
    unit: "n5",
    conceptIds: ["nav-measuring-direction", "nav-dividers"],
    prompt: "Order the steps for measuring the direction of a course line.",
    trigger: "Estimate the general direction of travel",
    steps: [
      "Span the dividers along the course line",
      "Lay the plotter's straightedge against the divider points",
      "Slide the plotter until the grommet sits on a meridian",
      "Read the outer scale, choosing the value nearest the estimate",
    ],
    explanation:
      "The dividers hold the line's direction while the plotter travels to a convenient meridian. The estimate at the start is what makes the final choice unambiguous.",
    difficulty: 3,
    source: TG(C2, ["4.6"]),
  },
  {
    id: "nq-c-049",
    type: "mcq",
    unit: "n5",
    conceptIds: ["nav-walking-dividers"],
    prompt: "A leg is longer than the dividers will span. What does the guide tell you to do?",
    options: [
      "Estimate it from the chart border",
      "Set the dividers to a fixed distance such as 30 NM and walk them along the line, counting",
      "Measure it in two halves and hope they meet",
      "Use the plotter's distance scale for the long part",
    ],
    answer: 1,
    explanation:
      "Set a fixed span, step it along counting in multiples, then close the dividers on the remainder and add it.",
    knowCold: "Walk the dividers in 30-mile steps, then close on the remainder.",
    difficulty: 2,
    source: TG(C2, ["4.5"]),
  },
  {
    id: "nq-c-050",
    type: "mcq",
    unit: "n5",
    conceptIds: ["nav-tacan-fix", "nav-variation-conversion"],
    prompt:
      "To plot a position on a Lambert conformal chart from a TACAN radial and DME, what must be applied?",
    options: ["magnetic variation", "instrument error", "deviation", "instrument variation"],
    answer: 0,
    explanation:
      "The radial is magnetic and the chart is true, so variation converts one to the other before anything is drawn.",
    difficulty: 1,
    officialStyle: true,
    source: TG(C7, ["4.7"]),
  },
  {
    id: "nq-c-051",
    type: "mcq",
    unit: "n5",
    conceptIds: ["nav-needle-head-tail"],
    prompt: "The tail of the #2 needle on a BDHI displays the magnetic",
    options: ["heading to a VOR", "bearing to a TACAN", "heading to a TACAN", "radial of a TACAN"],
    answer: 3,
    explanation:
      "Tail gives the radial you are on; head gives the bearing to the station. They are reciprocals, and problems that hand you one are testing whether you noticed which.",
    knowCold: "Head = bearing TO. Tail = the radial you are on.",
    difficulty: 2,
    officialStyle: true,
    source: TG(C2, ["4.7"]),
  },
  {
    id: "nq-c-052",
    type: "spotTheTrap",
    unit: "n5",
    conceptIds: ["nav-tacan-fix"],
    prompt: '"DME reads ground range, so it can be plotted straight onto the chart."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "Strictly false — DME is slant range, the straight-line distance including your altitude. For this course the guide says to treat it as ground range, but the distinction is real and it is worth knowing which simplification you are making.",
    difficulty: 3,
    source: TG(C2, ["4.7"]),
  },
  {
    id: "nq-c-053",
    type: "mcq",
    unit: "n5",
    conceptIds: ["nav-plotting-coordinates", "nav-plotting-direction"],
    prompt: "When plotting a set of coordinates, where does the point end up?",
    options: [
      "At the grommet",
      "Where the latitude line and the longitude line intersect",
      "At the end of the straightedge",
      "At the nearest speed mark",
    ],
    answer: 1,
    explanation:
      "Draw the latitude line, rotate ninety degrees, draw the longitude line, and the crossing is the position.",
    difficulty: 1,
    source: TG(C2, ["4.4"]),
  },

  /* ================= n6 ================= */
  {
    id: "nq-c-054",
    type: "mcq",
    unit: "n6",
    conceptIds: ["nav-cr3"],
    prompt: "What two advantages does the guide give for the CR-3 over an electronic calculator?",
    options: [
      "Speed and accuracy",
      "Reliability and cost",
      "Size and weight",
      "It shows the working",
    ],
    answer: 1,
    explanation:
      "Reliability and cost. A disc of plastic has no battery to go flat at altitude and nothing to fail.",
    difficulty: 1,
    source: TG(C3, ["4.8"]),
  },
  {
    id: "nq-c-055",
    type: "mcq",
    unit: "n6",
    conceptIds: ["nav-cr3-wheels", "nav-ratio"],
    prompt: "When a ratio is set up on the CR-3, which values go on the outer wheel?",
    options: [
      "The larger of the two values",
      "The numerators",
      "The denominators",
      "Whichever is known",
    ],
    answer: 1,
    explanation:
      "Numerators outside, denominators inside — set it up exactly as you would write the fraction on paper. Units must also match across each row.",
    knowCold: "Numerator outer, denominator inner.",
    difficulty: 2,
    source: TG(C3, ["4.9"]),
  },
  {
    id: "nq-c-056",
    type: "mcq",
    unit: "n6",
    conceptIds: ["nav-floating-decimal"],
    prompt: "On the CR-3 the number 21 could represent 0.21, 2.1, 21, 210 or 2100. What resolves the ambiguity?",
    options: [
      "The cursor hairline",
      "The estimate you made before reading the wheel",
      "The rate index",
      "The hour circle",
    ],
    answer: 1,
    explanation:
      "Nothing on the instrument knows where the decimal goes. That is the estimate's job, which is why the guide puts it at step one of every procedure.",
    knowCold: "The wheel gives digits. Your estimate gives the decimal point.",
    difficulty: 2,
    source: TG(C3, ["4.8", "4.9"]),
  },
  {
    id: "nq-c-057",
    type: "mcq",
    unit: "n6",
    conceptIds: ["nav-tick-values"],
    prompt: "Between 15 and 30 on the CR-3 scale there are four tick marks between whole numbers. Each is worth",
    options: ["one", "two", "five", "ten"],
    answer: 1,
    explanation:
      "Four ticks make five divisions, so each is worth two. From 10 to 15 there are nine ticks and each is worth one; from 30 to 60 there is one tick worth five.",
    knowCold: "10–15 → 1 · 15–30 → 2 · 30–60 → 5.",
    difficulty: 3,
    source: TG(C3, ["4.8"]),
  },
  {
    id: "nq-c-058",
    type: "mcq",
    unit: "n6",
    conceptIds: ["nav-rate-index"],
    prompt: "The rate index is found where 60 would be on the inner wheel. What value does it represent?",
    options: ["1", "6", "60 minutes", "3,600"],
    answer: 2,
    explanation:
      "Sixty MINUTES, which is one hour. The guide is emphatic that it is 0.6, 6.0 or 60 — never 1 — because reading it as one is a factor-of-sixty error.",
    difficulty: 2,
    source: TG(C3, ["4.9"]),
  },
  {
    id: "nq-c-059",
    type: "mcq",
    unit: "n6",
    conceptIds: ["nav-high-speed-index"],
    prompt: "Why is the high-speed index at 36 rather than at 60?",
    options: [
      "Because 36 is a third of the scale",
      "Because there are 3,600 seconds in an hour",
      "Because 36 knots is the minimum useful speed",
      "It is an arbitrary manufacturing mark",
    ],
    answer: 1,
    explanation:
      "3,600 seconds make an hour, so with the floating decimal that mark is at 36. It converts the hour into seconds instead of minutes.",
    knowCold: "SEC bug at 36: 3,600 seconds to the hour.",
    difficulty: 2,
    source: TG(C3, ["4.9"]),
  },
  {
    id: "nq-c-060",
    type: "mcq",
    unit: "n6",
    conceptIds: ["nav-high-speed-index"],
    prompt: "Which of these does NOT call for the high-speed index?",
    options: [
      "A time of about three minutes",
      "A distance of 4 NM",
      "A groundspeed of 650 kt",
      "A fuel flow of 3,600 pph",
    ],
    answer: 3,
    explanation:
      "The four triggers on the reference card are time under five minutes, distance under five miles, speed of 500 kt or more, and seconds appearing anywhere in the problem. A fuel flow that happens to read 3,600 is a coincidence, not a trigger.",
    difficulty: 3,
    source: TG(C3, ["4.9"]),
  },
  {
    id: "nq-c-061",
    type: "mcq",
    unit: "n6",
    conceptIds: ["nav-unit-index", "nav-fuel-conversion"],
    prompt: "Why is the unit index, not the rate index, used for a gallons-to-pounds conversion?",
    options: [
      "Because gallons are smaller than pounds",
      "Because there is no time in the problem",
      "Because fuel weight is always under ten",
      "Because the outer wheel changes meaning",
    ],
    answer: 1,
    explanation:
      "The rate index exists to represent an hour. A conversion is a plain ratio with no time in it, so the mark at 10 is the right one.",
    knowCold: "No time in the problem → unit index.",
    difficulty: 2,
    source: TG(C3, ["4.10"]),
  },
  {
    id: "nq-c-062",
    type: "mcq",
    unit: "n6",
    conceptIds: ["nav-hour-circle"],
    prompt: "The time scale is being read as SECONDS. What does the hour circle beneath it now read?",
    options: ["Hours", "Minutes", "Still seconds", "Nothing useful"],
    answer: 1,
    explanation:
      "Seconds relate to minutes exactly as minutes relate to hours, so the same scale serves both. 150 on the time scale reads 2:30 either way — two and a half hours, or two and a half minutes.",
    difficulty: 3,
    source: TG(C3, ["4.9"]),
  },
  {
    id: "nq-c-063",
    type: "mcq",
    unit: "n6",
    conceptIds: ["nav-rule-of-60", "nav-rule-of-6"],
    prompt: "At 420 kt groundspeed, roughly how far do you go in one minute, and in six?",
    options: ["4 NM and 24 NM", "7 NM and 42 NM", "42 NM and 7 NM", "6 NM and 36 NM"],
    answer: 1,
    explanation:
      "Rule of 60: 420 ÷ 60 = 7 NM a minute. Rule of 6: a tenth of groundspeed, 42 NM, in six minutes. The two rules are the same statement at different resolutions.",
    knowCold: "GS ÷ 60 per minute. GS ÷ 10 per six minutes.",
    difficulty: 2,
    source: TG(C3, ["4.9"]),
  },
  {
    id: "nq-c-064",
    type: "mcq",
    unit: "n6",
    conceptIds: ["nav-cursor"],
    prompt: "What is the primary function of the cursor hairline on the calculation side?",
    options: [
      "Reading the answer",
      "Inputting temperature for a true airspeed solution",
      "Locking the wheel in place",
      "Marking the rate index",
    ],
    answer: 1,
    explanation:
      "Temperature input for TAS is its main job; helping interpolate between printed marks is the secondary one.",
    difficulty: 2,
    source: TG(C3, ["4.8"]),
  },
  {
    id: "nq-c-065",
    type: "spotTheTrap",
    unit: "n6",
    conceptIds: ["nav-cr3"],
    prompt: '"A ballpoint pen is fine on the wind side of the CR-3 as long as you wipe it off."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. Soft pencil or felt tip only. The care instructions also warn against leaving it in direct sunlight, which warps the plastic and puts the scales out.",
    difficulty: 1,
    source: TG(C3, ["4.8"]),
  },

  /* ================= n7 ================= */
  {
    id: "nq-c-066",
    type: "mcq",
    unit: "n7",
    conceptIds: ["nav-standard-day"],
    prompt: "A standard day is defined as",
    options: [
      "29.92 inHg and +15 °C at mean sea level",
      "30.00 inHg and +20 °C at field elevation",
      "29.92 inHg and 0 °C at mean sea level",
      "The average of the last thirty days",
    ],
    answer: 0,
    explanation:
      "29.92 and +15 °C at sea level, with a lapse rate of 2 °C and 1 inHg per thousand feet. On a standard day calibrated and true altitude are the same.",
    knowCold: "29.92 and +15 °C. Then 2 °C and 1 inHg per 1,000 ft.",
    difficulty: 1,
    source: TG(C4, ["2.339"]),
  },
  {
    id: "nq-c-067",
    type: "mcq",
    unit: "n7",
    conceptIds: ["nav-altitude-types"],
    prompt: "Which statement defines TRUE altitude?",
    options: [
      "Altitude assigned to a given barometric pressure",
      "Actual height above the earth's surface",
      "Altitude indicated on the altimeter",
      "Actual height above mean sea level",
    ],
    answer: 3,
    explanation:
      "Height above mean sea level — which matters because terrain elevation on the chart is labelled in feet MSL. Height above the surface is ABSOLUTE altitude.",
    knowCold: "True = above sea level. Absolute = above the ground.",
    difficulty: 2,
    officialStyle: true,
    source: EXAM(["2.339"]),
  },
  {
    id: "nq-c-068",
    type: "mcq",
    unit: "n7",
    conceptIds: ["nav-altitude-types", "nav-pressure-altitude"],
    prompt: "The standard datum plane is the pressure level at",
    options: ["ground level", "29.92 inches Hg", "the aircraft's altitude", "mean sea level"],
    answer: 1,
    explanation:
      "29.92 inHg. Pressure altitude is measured from it, and pressure altitude is what a true airspeed solution needs.",
    difficulty: 2,
    officialStyle: true,
    source: EXAM(["2.340"]),
  },
  {
    id: "nq-c-069",
    type: "mcq",
    unit: "n7",
    conceptIds: ["nav-pressure-altitude"],
    prompt: "The altimeter setting is 30.42\". Going from calibrated altitude to pressure altitude, you",
    options: [
      "add 500 feet",
      "subtract 500 feet",
      "add 5,000 feet",
      "make no correction",
    ],
    answer: 1,
    explanation:
      "LAGS: the setting is Greater than 29.92, so Subtract. The difference is 0.50\", worth 500 feet at 1,000 feet to the inch.",
    knowCold: "LAGS — Less, Add. Greater, Subtract.",
    difficulty: 2,
    source: TG(C4, ["2.340"]),
  },
  {
    id: "nq-c-070",
    type: "mcq",
    unit: "n7",
    conceptIds: ["nav-cas", "nav-ias"],
    prompt: "Calibrated airspeed is indicated airspeed corrected for",
    options: [
      "air density",
      "instrument and installation error",
      "wind",
      "compressibility only",
    ],
    answer: 1,
    explanation:
      "Instrument and installation error, taken from the airspeed calibration card in the cockpit. Correcting for density is the next step, and it gives TRUE airspeed.",
    difficulty: 2,
    source: TG(C4, ["2.42", "2.43"]),
  },
  {
    id: "nq-c-071",
    type: "mcq",
    unit: "n7",
    conceptIds: ["nav-tas", "nav-cas", "nav-density-effect"],
    prompt: "Indicated airspeed corrected for mechanical error AND density is",
    options: ["calibrated airspeed", "ground speed", "true airspeed", "found on the calibration card"],
    answer: 2,
    explanation:
      "True airspeed — the speed through the air mass. Correcting further for wind would give ground speed.",
    knowCold: "IAS → instrument error → CAS → density → TAS → wind → GS.",
    difficulty: 2,
    officialStyle: true,
    source: EXAM(["2.45", "2.47"]),
  },
  {
    id: "nq-c-072",
    type: "mcq",
    unit: "n7",
    conceptIds: ["nav-groundspeed", "nav-tas"],
    prompt: "Ground speed is true airspeed corrected for",
    options: ["temperature", "the head or tail component of the wind", "pressure altitude", "instrument error"],
    answer: 1,
    explanation:
      "Only the along-course component of the wind changes ground speed. The crosswind component changes heading instead.",
    difficulty: 1,
    source: TG(C4, ["2.46"]),
  },
  {
    id: "nq-c-073",
    type: "mcq",
    unit: "n7",
    conceptIds: ["nav-tas-procedure", "nav-mach"],
    prompt: "Which variables must you know to solve for TAS on the CR-3?",
    options: ["IAS, OAT, PA", "IAS, OAT, CAS", "CAS, OAT, PA", "CAS, OAT, true altitude"],
    answer: 2,
    explanation:
      "Calibrated airspeed, outside air temperature and PRESSURE altitude. True altitude is not the reference; pressure altitude is.",
    knowCold: "TAS needs CAS, OAT and pressure altitude.",
    difficulty: 2,
    officialStyle: true,
    source: EXAM(["2.340"]),
  },
  {
    id: "nq-c-074",
    type: "mcq",
    unit: "n7",
    conceptIds: ["nav-mach", "nav-shock-wave"],
    prompt: "Mach number is",
    options: [
      "true airspeed divided by the local speed of sound",
      "calibrated airspeed divided by 661 knots",
      "the speed at which a shock wave forms",
      "ground speed divided by the local speed of sound",
    ],
    answer: 0,
    explanation:
      "TAS over the local speed of sound. Comparing the two matters because pressure waves travel at the speed of sound, and once the aircraft catches them they pile into a shock wave.",
    difficulty: 2,
    source: TG(C4, ["2.341"]),
  },
  {
    id: "nq-c-075",
    type: "mcq",
    unit: "n7",
    conceptIds: ["nav-density-effect", "nav-tas"],
    prompt: "When you climb at a constant indicated airspeed, what happens to true airspeed?",
    options: ["It decreases", "It stays the same", "It increases", "It depends on the wind"],
    answer: 2,
    explanation:
      "Thinner air gives the same pitot pressure at a higher real speed, so TAS rises with altitude at a fixed IAS.",
    difficulty: 2,
    source: TG(C4, ["2.339", "2.47"]),
  },
  {
    id: "nq-c-076",
    type: "mcq",
    unit: "n7",
    conceptIds: ["nav-altimeter-errors"],
    prompt:
      "You fly from an area of high pressure to an area of low pressure without resetting the altimeter. What happens?",
    options: [
      "The altimeter reads low and the aircraft is higher than indicated",
      "The altimeter reads high and the aircraft is lower than indicated",
      "The altimeter is unaffected",
      "The altimeter reads high and the aircraft is higher than indicated",
    ],
    answer: 1,
    explanation: "High to low, look out below. The altimeter over-reads and you are lower than it says.",
    knowCold: "High to low, look out below. Low to high, plenty of sky.",
    difficulty: 2,
    source: TG(C4, ["2.339"]),
  },
  {
    id: "nq-c-077",
    type: "mcq",
    unit: "n7",
    conceptIds: ["nav-instrument-error", "nav-altitude-types"],
    prompt:
      "An altimeter reads 80 feet at NAS Pensacola, where the field elevation is 30 feet MSL and the current setting is dialled in. What is the instrument error, and what does it mean?",
    options: [
      "−50 feet, and it can be corrected in flight",
      "+50 feet, and it cannot be corrected for",
      "50 feet, which makes the aircraft unsafe for IFR",
      "There is no error; the altimeter reads MSL",
    ],
    answer: 1,
    explanation:
      "The altimeter over-reads by 50 feet. Instrument error cannot be corrected; it is only noted. Above 75 feet total the aircraft is unsafe for IFR.",
    difficulty: 3,
    source: TG(C4, ["2.339"]),
  },
  {
    id: "nq-c-078",
    type: "mcq",
    unit: "n7",
    conceptIds: ["nav-temperature-error"],
    prompt: "For every 11 °C the temperature varies from the standard lapse rate, the altimeter is in error by",
    options: ["1%", "4%", "10%", "11%"],
    answer: 1,
    explanation:
      "4%. Colder than standard and the aircraft is lower than indicated; warmer and it is higher.",
    difficulty: 3,
    source: TG(C4, ["2.339"]),
  },
  {
    id: "nq-c-079",
    type: "mcq",
    unit: "n7",
    conceptIds: ["nav-mach"],
    prompt: "You descend at a constant indicated airspeed. Your Mach number",
    options: ["increases", "decreases", "varies inversely with TAS", "remains constant"],
    answer: 1,
    explanation:
      "Lower down the air is warmer, so the local speed of sound is higher, and TAS is lower too. Mach falls on both counts.",
    difficulty: 3,
    officialStyle: true,
    source: EXAM(["2.341"]),
  },

  /* ================= n8 ================= */
  {
    id: "nq-c-080",
    type: "mcq",
    unit: "n8",
    conceptIds: ["nav-wind-triangle"],
    prompt: "The air vector consists of",
    options: [
      "true course and true airspeed",
      "true heading and ground speed",
      "wind direction and velocity",
      "true heading and true airspeed",
    ],
    answer: 3,
    explanation:
      "True heading and true airspeed. Course and ground speed are the ground vector; direction and velocity are the wind vector.",
    knowCold: "Air = TH/TAS · Ground = TC or TK/GS · Wind = direction/velocity.",
    difficulty: 2,
    officialStyle: true,
    source: TG(C5, ["4.14"]),
  },
  {
    id: "nq-c-081",
    type: "mcq",
    unit: "n8",
    conceptIds: ["nav-wind-reporting"],
    prompt: "Wind direction and velocity at altitude are stated as",
    options: [
      "a magnetic direction and speed in knots",
      "a magnetic direction and speed in miles per hour",
      "a true direction and speed in miles per hour",
      "a true direction and speed in knots",
    ],
    answer: 3,
    explanation:
      "En route winds from the forecaster are TRUE and in knots. Surface winds from the tower are magnetic, so they match the runway numbers.",
    knowCold: "Winds aloft: true. Tower winds: magnetic.",
    difficulty: 2,
    officialStyle: true,
    source: TG(C5, ["4.14"]),
  },
  {
    id: "nq-c-082",
    type: "spotTheTrap",
    unit: "n8",
    conceptIds: ["nav-wind-reporting"],
    prompt: '"A wind reported as 045 is blowing toward the north-east."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. Wind direction is where it comes FROM, so 045 originates in the north-east and blows toward the south-west.",
    difficulty: 1,
    source: TG(C5, ["4.14"]),
  },
  {
    id: "nq-c-083",
    type: "mcq",
    unit: "n8",
    conceptIds: ["nav-quartering", "nav-crab-drift"],
    prompt:
      "You are planning a true course of 285 and the preflight winds are 107 at 40. How do the predicted heading and ground speed compare with the course and true airspeed?",
    options: [
      "TH increases and GS increases",
      "TH decreases and GS increases",
      "TH increases and GS decreases",
      "TH decreases and GS decreases",
    ],
    answer: 1,
    explanation:
      "The wind is almost directly behind and slightly from the left, so it is a left tailwind: heading comes down from the course and ground speed beats true airspeed.",
    knowCold: "Left tail → TH < TC, GS > TAS.",
    difficulty: 3,
    officialStyle: true,
    source: TG(C7, ["4.14"]),
  },
  {
    id: "nq-c-084",
    type: "mcq",
    unit: "n8",
    conceptIds: ["nav-ten-percent"],
    prompt: "With a TAS of 150 kt and 30 kt of crosswind, roughly what crab angle should you expect?",
    options: ["3°", "6°", "12°", "20°"],
    answer: 2,
    explanation:
      "Ten percent of 150 is 15 kt, which gives 6°. Thirty knots is twice that, so about 12°.",
    knowCold: "Crosswind = 10% of TAS → 6° of crab.",
    difficulty: 2,
    source: TG(C5, ["4.15"]),
  },
  {
    id: "nq-c-085",
    type: "mcq",
    unit: "n8",
    conceptIds: ["nav-wind-scales"],
    prompt: "The wind is forecast at 75 kt. Which grid scale do you use, and what is the rule?",
    options: [
      "The large 0–80 scale, because 75 fits on it",
      "The small 0–160 scale, because the wind is 60 kt or more — and the same scale is used throughout the problem",
      "Either, as long as you convert at the end",
      "Whichever gives a rounder number",
    ],
    answer: 1,
    explanation:
      "Sixty knots is the changeover. Once you pick a scale you stay on it: mixing the two inside one problem produces a wrong answer that looks entirely reasonable.",
    difficulty: 2,
    source: TG(C5, ["4.15"]),
  },
  {
    id: "nq-c-086",
    type: "mcq",
    unit: "n8",
    conceptIds: ["nav-balloon", "nav-wind-triangle"],
    prompt:
      "An aircraft flies east at 50 kt inside an air mass that is moving west at 50 kt. After one hour, what has happened?",
    options: [
      "It has travelled 100 NM east over the ground",
      "It has not moved over the ground at all, but has crossed the air mass",
      "It has travelled 50 NM west",
      "It has stalled",
    ],
    answer: 1,
    explanation:
      "Zero ground speed, but it has still flown from one side of the balloon to the other. Motion through the air and motion over the ground are two separate things — which is the whole reason the wind triangle exists.",
    difficulty: 2,
    source: TG(C5, ["4.14"]),
  },
  {
    id: "nq-c-087",
    type: "connectChain",
    unit: "n8",
    conceptIds: ["nav-preflight-procedure"],
    prompt: "Order the preflight wind procedure.",
    trigger: "Estimate — sketch the wind against the course",
    steps: [
      "Plot the wind on the grid",
      "Set the TAS over the TAS index",
      "Set the true course at the course index",
      "Read the crosswind and head/tail components",
      "Apply the component to TAS for ground speed",
      "Read the crab angle and apply it for heading",
    ],
    explanation:
      "Estimate, plot, set, set, read, apply, apply — and then check the answer against the estimate you started with.",
    difficulty: 3,
    source: TG(C5, ["4.15"]),
  },

  /* ================= n9 ================= */
  {
    id: "nq-c-088",
    type: "mcq",
    unit: "n9",
    conceptIds: ["nav-inflight-theory", "nav-inflight-procedure"],
    prompt: "In an in-flight wind solution, what goes over the course index?",
    options: ["The true course", "The track", "The true heading", "The wind direction"],
    answer: 1,
    explanation:
      "Track. In flight the ground vector is what actually happened, and its direction is track — not the course you meant to fly.",
    knowCold: "Preflight: course at the index. In flight: TRACK at the index.",
    difficulty: 3,
    source: TG(C6, ["2.343"]),
  },
  {
    id: "nq-c-089",
    type: "mcq",
    unit: "n9",
    conceptIds: ["nav-inflight-estimate"],
    prompt:
      "Your ground speed is greater than your TAS and you have drifted left. What kind of wind are you in?",
    options: ["Left headwind", "Right headwind", "Left tailwind", "Right tailwind"],
    answer: 3,
    explanation:
      "Ground speed above TAS means a tailwind. Drifting left means the wind is pushing from the right. Right tailwind.",
    knowCold: "Drift tells you the side. GS versus TAS tells you head or tail.",
    difficulty: 2,
    officialStyle: true,
    source: TG(C7, ["2.343"]),
  },
  {
    id: "nq-c-090",
    type: "mcq",
    unit: "n9",
    conceptIds: ["nav-inflight-estimate"],
    prompt:
      "Your ground speed is less than your TAS and you have drifted left. What kind of wind are you in?",
    options: ["Left headwind", "Right headwind", "Right tailwind", "Left tailwind"],
    answer: 1,
    explanation:
      "Slower than TAS is a headwind; drifting left means it comes from the right. Right headwind.",
    difficulty: 2,
    officialStyle: true,
    source: TG(C7, ["2.343"]),
  },
  {
    id: "nq-c-091",
    type: "mcq",
    unit: "n9",
    conceptIds: ["nav-crab-drift", "nav-track", "nav-heading"],
    prompt:
      "An aircraft is on a true heading of 200° at 175 kt TAS and 14° of left drift is observed. What is its track?",
    options: ["186°", "200°", "214°", "More information is required"],
    answer: 0,
    explanation:
      "Drift is measured from heading, so 14° left of 200 is 186. Airspeed is a distractor — track does not need it.",
    difficulty: 2,
    officialStyle: true,
    source: TG(C7, ["2.336", "2.342"]),
  },
  {
    id: "nq-c-092",
    type: "mcq",
    unit: "n9",
    conceptIds: ["nav-point-to-point"],
    prompt: "What is the advantage of TACAN point-to-point navigation?",
    options: [
      "It works without a TACAN receiver",
      "It lets you fly direct from one radial and DME fix to another without overflying the station",
      "It converts magnetic courses to true automatically",
      "It removes the need for a wind solution",
    ],
    answer: 1,
    explanation:
      "Direct between two fixes defined against the same station. On the CR-3 the wind grid becomes a map with the station at the centre.",
    difficulty: 2,
    source: TG(C6, ["2.344"]),
  },
  {
    id: "nq-c-093",
    type: "mcq",
    unit: "n9",
    conceptIds: ["nav-point-to-point"],
    prompt:
      "When solving a point-to-point on the CR-3, why does the guide tell you to circle the destination dot?",
    options: [
      "To keep the pencil mark from smudging",
      "So you rotate the line with the destination above the present position, and do not read the reciprocal",
      "To mark which scale you used",
      "Because the destination is always plotted first",
    ],
    answer: 1,
    explanation:
      "The line has two ends and the scale will happily give you either. Circling the destination fixes which way is 'up' when you rotate it vertical.",
    knowCold: "Circle the destination. Arrow points up.",
    difficulty: 3,
    source: TG(C6, ["2.344"]),
  },
  {
    id: "nq-c-094",
    type: "mcq",
    unit: "n9",
    conceptIds: ["nav-point-to-point", "nav-variation-conversion"],
    prompt: "A course read off a CR-3 point-to-point solution is",
    options: ["true", "magnetic", "relative", "grid"],
    answer: 1,
    explanation:
      "Magnetic, because TACAN radials are magnetic and the grid is being used as a map of them. No variation is applied.",
    difficulty: 2,
    source: TG(C6, ["2.344"]),
  },

  /* ================= n10 ================= */
  {
    id: "nq-c-095",
    type: "mcq",
    unit: "n10",
    conceptIds: ["nav-jet-log"],
    prompt: "The jet log's PRIMARY purpose is",
    options: [
      "to provide route navigation data",
      "for route timing",
      "for aircrew coordination",
      "for fuel management",
    ],
    answer: 3,
    explanation:
      "Fuel management. It does the other three as well, but the guide names fuel as the reason it exists.",
    knowCold: "Jet log: fuel management first.",
    difficulty: 2,
    officialStyle: true,
    source: TG(C7, ["4.12"]),
  },
  {
    id: "nq-c-096",
    type: "mcq",
    unit: "n10",
    conceptIds: ["nav-planning-steps"],
    prompt: "All of the following are basic flight planning steps EXCEPT",
    options: [
      "plot new course and distance using a TACAN fix",
      "find heading and ground speed using preflight winds",
      "compute leg fuel using ETE and fuel flow",
      "compute en route time using ground speed",
    ],
    answer: 0,
    explanation:
      "Plotting a new course from a fix is a flight CONDUCT step — it happens once you are airborne and off the plan. Planning is: measure, wind, time, fuel.",
    knowCold: "Plan: measure, wind, time, fuel. Conduct: fix, re-measure, new winds, update.",
    difficulty: 3,
    officialStyle: true,
    source: TG(C7, ["4.11"]),
  },
  {
    id: "nq-c-097",
    type: "mcq",
    unit: "n10",
    conceptIds: ["nav-planning-steps"],
    prompt: "All of the following are basic air navigation flight planning steps EXCEPT",
    options: [
      "determine headings and ground speeds using preflight winds",
      "compute an ETE for each leg using ground speed",
      "use track to determine updated winds",
      "plot courses and measure distances",
    ],
    answer: 2,
    explanation:
      "Track only exists once you have flown somewhere, so using it to update the winds belongs to flight conduct rather than planning.",
    difficulty: 3,
    officialStyle: true,
    source: TG(C7, ["4.11"]),
  },
  {
    id: "nq-c-098",
    type: "connectChain",
    unit: "n10",
    conceptIds: ["nav-planning-steps", "nav-jet-log-enroute"],
    prompt: "Order the four flight planning steps.",
    trigger: "You have a route and a chart",
    steps: [
      "Measure true courses and distances",
      "Use preflight winds for headings and ground speeds",
      "Compute an ETE for each leg from ground speed",
      "Compute leg fuel from the ETE and the fuel flow",
    ],
    explanation:
      "Each step feeds the next: you cannot get an ETE without a ground speed, and you cannot get a ground speed without a course.",
    difficulty: 2,
    source: TG(C7, ["4.11", "4.13"]),
  },
  {
    id: "nq-c-099",
    type: "connectChain",
    unit: "n10",
    conceptIds: ["nav-flight-conduct", "nav-eta-update", "nav-efr-update"],
    prompt: "Order the four updating steps once you are airborne and off the plan.",
    trigger: "A fix says you are not where the plan expected",
    steps: [
      "Plot the fix and measure track and distance flown",
      "Measure the updated course and distance to the next turn point",
      "Determine the actual in-flight winds",
      "Apply the new winds to the remaining legs and update ETA and EFR",
    ],
    explanation:
      "Note what this course does NOT do: it does not turn back to the original line. It computes a new course direct to the turn point and replans from there.",
    difficulty: 3,
    source: TG(C7, ["4.11", "4.16", "4.17"]),
  },
  {
    id: "nq-c-100",
    type: "mcq",
    unit: "n10",
    conceptIds: ["nav-jet-log-enroute", "nav-efr-update"],
    prompt: "How is estimated fuel remaining over a turn point computed?",
    options: [
      "Total fuel on board minus the total trip fuel",
      "The previous point's EFR minus this leg's fuel",
      "Fuel flow multiplied by the ETE",
      "Fuel on board divided by the number of legs",
    ],
    answer: 1,
    explanation:
      "EFR carries down the log: each line starts from the line above it and subtracts the leg. That running total is what makes the log a fuel-management document.",
    difficulty: 2,
    source: TG(C7, ["4.13", "4.17"]),
  },
  {
    id: "nq-c-101",
    type: "mcq",
    unit: "n10",
    conceptIds: ["nav-plan-is-an-estimate", "nav-flight-conduct"],
    prompt: "What does the guide say the jet log actually contains when you strap in?",
    options: [
      "The route as cleared by ATC",
      "The crew's best estimate of what will happen",
      "A legally binding fuel plan",
      "The winds as they will be",
    ],
    answer: 1,
    explanation:
      "A best estimate, no more. Aviation is dynamic; the log is written in pencil for a reason.",
    difficulty: 1,
    source: TG(C7, ["4.11"]),
  },
  {
    id: "nq-c-102",
    type: "mcq",
    unit: "n10",
    conceptIds: ["nav-jet-log-enroute", "nav-jet-log"],
    prompt: "Which section of the jet log does this course use?",
    options: ["The departure section", "The clearance section", "The en route section", "The fuel plan on the back"],
    answer: 2,
    explanation:
      "Only the en route section: navaid, course, distance, ETE, ETA, leg fuel and EFR. The rest of the card exists but is out of scope here.",
    difficulty: 1,
    source: TG(C7, ["4.12"]),
  },
];
