import type { Question, SourceReference } from "@/lib/types";

const TG = (chapter: string, eo: string[]): SourceReference => ({
  document: "Aerodynamics Trainee Guide",
  chapter,
  eo,
});

const BASIC = (eo: string[]) => TG("Basic Theory", eo);

/**
 * Unit 1 — Learn the Language.
 *
 * Distractors are drawn from the real confusions the official review questions
 * and the practice test exploit: moment vs work, density vs mass, TAS vs IAS,
 * pitch attitude vs AOA, chord line vs mean camber line.
 */
export const U1_QUESTIONS: Question[] = [
  /* ---------------- Definitions & mechanics ---------------- */
  {
    id: "q-u1-001",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-moment"],
    prompt: "A moment is",
    options: [
      "force times the distance of displacement",
      "work done per unit of time",
      "force times the perpendicular distance from a fulcrum",
      "mass times acceleration",
    ],
    answer: 2,
    explanation:
      "A moment is a rotational force: force multiplied by the perpendicular distance from the axis of rotation. That distance is the moment arm.",
    whyWrong:
      "Force × displacement is work. Work per unit time is power. Mass × acceleration is force.",
    knowCold: "Moment = force × perpendicular distance from the fulcrum.",
    difficulty: 1,
    officialStyle: true,
    source: BASIC(["2.8"]),
  },
  {
    id: "q-u1-002",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-density"],
    prompt: "Air density is defined by",
    options: [
      "the volume of space occupied by an object",
      "mass of air per unit volume",
      "the quantity of molecular material that comprises an object",
      "volume of air per unit mass",
    ],
    answer: 1,
    explanation:
      "Density is mass per unit volume, ρ = m / V. Air density is the total mass of air particles per unit of volume.",
    whyWrong:
      "Volume occupied is volume. Quantity of molecular material is mass. Volume per unit mass is the reciprocal.",
    knowCold: "ρ = mass ÷ volume.",
    difficulty: 1,
    officialStyle: true,
    source: BASIC(["2.5", "2.20"]),
  },
  {
    id: "q-u1-003",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-work-power-energy"],
    prompt: "Potential energy is",
    options: [
      "the ability of a body to do work due to its motion",
      "dependent on mass and velocity",
      "a scalar measure of a body's capacity to do work",
      "the ability of a body to do work due to its position or state of being",
    ],
    answer: 3,
    explanation:
      "Potential energy is the capacity to do work because of position or state of being — a function of mass, gravity and height.",
    whyWrong:
      "Motion and mass-plus-velocity describe kinetic energy. 'A scalar measure of capacity to do work' is the definition of energy generally, not of potential energy.",
    knowCold: "PE = position. KE = motion.",
    difficulty: 1,
    officialStyle: true,
    source: BASIC(["2.12", "2.13"]),
  },
  {
    id: "q-u1-004",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-newton-laws"],
    prompt: "The Law of Interaction states",
    options: [
      '"For every action there is an equal and opposite reaction."',
      '"A body at rest tends to stay at rest."',
      '"Two opposite forces cannot interact."',
      '"An unbalanced force acting upon a body produces an acceleration in the direction of the force."',
    ],
    answer: 0,
    explanation:
      "Newton's third law — the Law of Interaction — states that the forces two bodies exert on each other are equal in magnitude and opposite in direction.",
    whyWrong:
      "Option B is the Law of Equilibrium (first law). Option D is the Law of Acceleration (second law).",
    knowCold: "Equilibrium → 1st. Acceleration → 2nd. Interaction → 3rd.",
    difficulty: 1,
    officialStyle: true,
    source: BASIC(["2.18"]),
  },
  {
    id: "q-u1-005",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-equilibrium", "c-trimmed"],
    prompt:
      "If the sum of all forces and moments around the ___ are equal to zero, the plane is in ___ flight.",
    options: [
      "center of gravity, equilibrium",
      "aerodynamic center, equilibrium",
      "center of gravity, trimmed",
      "aerodynamic center, trimmed",
    ],
    answer: 0,
    explanation:
      "Equilibrium flight requires the sum of all forces AND all moments around the centre of gravity to be zero. Trimmed flight requires only the moments to be zero.",
    whyWrong:
      "Moments are measured about the CG, not the aerodynamic centre. Trimmed flight is the moments-only condition.",
    knowCold: "Forces + moments = equilibrium. Moments only = trimmed.",
    difficulty: 2,
    officialStyle: true,
    source: BASIC(["2.15", "2.16"]),
  },
  {
    id: "trap-u1-006",
    type: "spotTheTrap",
    unit: "u1",
    conceptIds: ["c-equilibrium"],
    prompt:
      "\"An airplane must be in straight and level flight to be in equilibrium.\"",
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. Equilibrium only requires no acceleration. A steady climb at constant airspeed, and even a constant-airspeed vertical climb, are equilibrium flight.",
    knowCold: "Equilibrium = no acceleration, not necessarily level.",
    difficulty: 2,
    source: BASIC(["2.15"]),
  },
  {
    id: "trap-u1-007",
    type: "spotTheTrap",
    unit: "u1",
    conceptIds: ["c-trimmed", "c-equilibrium"],
    prompt:
      "\"An airplane in a constant-rate, constant-angle-of-bank turn is in trimmed flight but not equilibrium flight.\"",
    options: ["True", "False"],
    answer: 0,
    explanation:
      "True. The moments around the CG sum to zero, so it is trimmed. But the turn is an acceleration, so the forces do not sum to zero and it is not equilibrium.",
    knowCold: "Equilibrium ⇒ trimmed. Trimmed ⇏ equilibrium.",
    difficulty: 3,
    source: BASIC(["2.16"]),
  },

  /* ---------------- Atmosphere ---------------- */
  {
    id: "q-u1-008",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-humidity-density", "c-4h-club"],
    prompt:
      "As humidity ___, density will ___ and minimum takeoff speed will ___.",
    options: [
      "increases, increase, increase",
      "decreases, decrease, increase",
      "increases, decrease, increase",
      "decreases, increase, decrease",
    ],
    answer: 2,
    explanation:
      "Water molecules displace air molecules and weigh less, so more humidity means less dense air. Less dense air requires a higher true airspeed to produce takeoff lift.",
    knowCold: "Humidity ↑ → density ↓ → true takeoff speed ↑.",
    difficulty: 2,
    officialStyle: true,
    source: BASIC(["2.23", "2.24"]),
  },
  {
    id: "q-u1-009",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-viscosity"],
    prompt: "As the temperature of air increases, its viscosity",
    options: [
      "increases",
      "decreases",
      "remains constant",
      "varies with pressure only",
    ],
    answer: 0,
    explanation:
      "Air is the opposite of a liquid: as temperature increases, air viscosity increases. Car oil gets thinner when hot; air does not.",
    knowCold: "Hot air = MORE viscous. Hot oil = less viscous.",
    difficulty: 2,
    source: BASIC(["2.25", "2.26"]),
  },
  {
    id: "q-u1-010",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-speed-of-sound"],
    prompt: "The local speed of sound in air depends only on",
    options: ["static pressure", "air density", "temperature", "humidity"],
    answer: 2,
    explanation:
      "The speed of sound in air is a function of temperature alone. Warmer air means more excited molecules, which propagate the wave faster.",
    knowCold: "Speed of sound: temperature only.",
    difficulty: 2,
    source: BASIC(["2.27", "2.28"]),
  },
  {
    id: "q-u1-011",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-temperature-lapse"],
    prompt:
      "The average lapse rate is a temperature decrease of ___ per 1,000 ft, holding until approximately ___.",
    options: [
      "2 °C, 36,000 ft",
      "3.57 °C, 18,000 ft",
      "2 °F, 36,000 ft",
      "1 °C, 66,000 ft",
    ],
    answer: 0,
    explanation:
      "Air temperature decreases linearly at 2 °C (3.57 °F) per 1,000 ft up to about 36,000 ft, above which the isothermal layer holds −56.5 °C.",
    knowCold: "Lapse rate: 2 °C / 3.57 °F per 1,000 ft to 36,000 ft.",
    difficulty: 2,
    source: BASIC(["2.22", "2.29"]),
  },
  {
    id: "q-u1-012",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-standard-atmosphere"],
    prompt:
      "The altimeter setting for a standard day, where pressure altitude equals true altitude, is",
    options: ["29.92 in-Hg", "92.29 in-Hg", "92.92 in-Hg", "1013.2 in-Hg"],
    answer: 0,
    explanation:
      "Standard sea-level pressure is 29.92 in-Hg (1013.25 mbar). The standard datum plane is where the barometric pressure is 29.92 in-Hg.",
    knowCold: "Standard day: 29.92 in-Hg, 59 °F / 15 °C.",
    difficulty: 1,
    officialStyle: true,
    source: BASIC(["2.29", "2.39"]),
  },
  {
    id: "q-u1-013",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-gas-law"],
    prompt: "If pressure remains constant in the General Gas Law:",
    options: [
      "The Universal Gas Constant and temperature have an inverse relationship",
      "The Universal Gas Constant and density are no longer in a relationship",
      "Temperature and density have a direct relationship",
      "Temperature and density have an inverse relationship",
    ],
    answer: 3,
    explanation:
      "P = ρRT. With P and R fixed, an increase in temperature must be matched by a decrease in density, and vice versa.",
    knowCold: "P constant → T and ρ are inverse.",
    difficulty: 2,
    officialStyle: true,
    source: BASIC(["2.30"]),
  },
  {
    id: "cc-u1-014",
    type: "connectChain",
    unit: "u1",
    conceptIds: ["c-density-altitude", "c-4h-club"],
    prompt: "Build the chain from a hot day to a long takeoff roll.",
    trigger: "Outside air temperature increases",
    steps: [
      "Air density decreases",
      "Density altitude increases",
      "True airspeed required for takeoff increases",
      "Takeoff distance increases",
    ],
    explanation:
      "Higher temperature reduces density, which raises density altitude. Lower density needs a higher true airspeed to make the same lift, and the engine makes less thrust — so the roll gets longer.",
    knowCold: "High DA means LOW air density and degraded performance.",
    difficulty: 2,
    source: BASIC(["2.40", "2.127"]),
  },
  {
    id: "q-u1-015",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-density-altitude"],
    prompt: "A high density altitude indicates",
    options: [
      "high air density and improved performance",
      "low air density and degraded performance",
      "an aircraft operating above 10,000 ft MSL",
      "a pressure altitude below the standard datum plane",
    ],
    answer: 1,
    explanation:
      "Density altitude is the standard-atmosphere altitude at which density matches the local density. A high value means the air is thin, so power, thrust and acceleration all suffer.",
    knowCold: "High DA = thin air = worse performance.",
    difficulty: 2,
    source: BASIC(["2.40"]),
  },

  /* ---------------- Airflow, continuity, Bernoulli ---------------- */
  {
    id: "q-u1-016",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-steady-airflow"],
    prompt:
      "What variables remain constant over time for air particles in steady airflow?",
    options: [
      "Temperature, pressure, direction, viscosity",
      "Temperature, direction, speed, velocity",
      "Temperature, density, velocity, pressure",
      "Temperature, density, velocity, viscosity",
    ],
    answer: 2,
    explanation:
      "Steady airflow exists if at every point static pressure, density, temperature and velocity remain constant over time.",
    whyWrong: "Viscosity is not one of the four defining constants.",
    knowCold: "Steady airflow: pressure, density, temperature, velocity.",
    difficulty: 2,
    officialStyle: true,
    source: BASIC(["2.32"]),
  },
  {
    id: "q-u1-017",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-continuity"],
    prompt: "Which statement is true about a streamtube?",
    options: [
      "Potential and kinetic energy are equal",
      "Static and dynamic pressure are equal",
      "As the cross-sectional area of one end decreases, velocity increases",
      "As the cross-sectional area of one end decreases, velocity is unaffected",
    ],
    answer: 2,
    explanation:
      "The continuity equation A₁V₁ = A₂V₂ means area and velocity are inversely related within a streamtube.",
    knowCold: "A₁V₁ = A₂V₂. Squeeze the tube, speed the flow.",
    difficulty: 2,
    officialStyle: true,
    source: BASIC(["2.35"]),
  },
  {
    id: "sp-u1-018",
    type: "sliderPredict",
    unit: "u1",
    conceptIds: ["c-continuity", "c-bernoulli"],
    widget: "StreamtubeSlider",
    prompt:
      "Narrow the streamtube and watch the readouts. What happens to STATIC pressure at the narrow point?",
    options: ["It increases", "It decreases", "It is unchanged"],
    answer: 1,
    explanation:
      "Narrowing the tube raises velocity (continuity), which raises dynamic pressure. Since total pressure is constant in a closed system, static pressure must fall.",
    knowCold: "Faster flow = lower static pressure.",
    difficulty: 2,
    source: BASIC(["2.31", "2.35"]),
  },
  {
    id: "q-u1-019",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-bernoulli", "c-dynamic-pressure"],
    prompt:
      "In a closed system, an increase in static pressure results in a ___ in dynamic pressure because ___.",
    options: [
      "decrease, total pressure is constant",
      "increase, total pressure is constant",
      "decrease, density is constant",
      "increase, velocity is constant",
    ],
    answer: 0,
    explanation:
      "H = Pₛ + q. With total pressure H fixed, the two components trade off against each other.",
    knowCold: "H = Pₛ + ½ρV². Total is constant; the parts trade.",
    difficulty: 2,
    source: BASIC(["2.31"]),
  },
  {
    id: "q-u1-020",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-dynamic-pressure"],
    prompt: "If true airspeed doubles at constant density, dynamic pressure",
    options: [
      "doubles",
      "quadruples",
      "increases by half",
      "is unchanged",
    ],
    answer: 1,
    explanation:
      "q = ½ρV². Velocity appears squared, so doubling V multiplies q by four.",
    knowCold: "q ∝ V². Double the speed, four times the q.",
    difficulty: 2,
    source: BASIC(["2.31"]),
  },

  /* ---------------- Pitot-static & airspeeds ---------------- */
  {
    id: "q-u1-021",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-pitot-static"],
    prompt:
      "___ airspeed is displayed in the cockpit by calculating ___ from Bernoulli's equation using pitot-static system measurements.",
    options: [
      "Calibrated, static pressure",
      "Equivalent, static pressure",
      "Indicated, dynamic pressure",
      "True, dynamic pressure",
    ],
    answer: 2,
    explanation:
      "The differential pressure gauge subtracts static pressure from total pressure to give dynamic pressure, which the airspeed indicator displays as indicated airspeed.",
    knowCold: "The ASI shows INDICATED airspeed, computed from DYNAMIC pressure.",
    difficulty: 2,
    officialStyle: true,
    source: BASIC(["2.41", "2.42"]),
  },
  {
    id: "tap-u1-022",
    type: "tapDiagram",
    unit: "u1",
    conceptIds: ["c-pitot-static"],
    prompt: "Tap the component that senses TOTAL pressure.",
    diagram: { id: "pitot-static" },
    targets: [
      { id: "pitot", label: "Pitot tube", x: 108, y: 96, r: 34 },
      { id: "static", label: "Static port", x: 268, y: 138, r: 30 },
      { id: "gauge", label: "Differential gauge", x: 400, y: 106, r: 34 },
    ],
    answer: "pitot",
    explanation:
      "The pitot tube is open to the airflow and closed at the back. Air fills it, motion stops, and by Bernoulli that stagnation pressure equals total pressure.",
    knowCold: "Pitot = total. Static port = static. Gauge = the difference (q).",
    difficulty: 1,
    source: BASIC(["2.41"]),
  },
  {
    id: "q-u1-023",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-icetg"],
    prompt: "TAS is",
    options: [
      "indicated airspeed corrected for instrument error",
      "equivalent airspeed corrected for compressibility",
      "calibrated airspeed corrected for density",
      "equivalent airspeed corrected for density",
    ],
    answer: 3,
    explanation:
      "The ladder is ICE-TG: IAS → CAS (instrument/position error) → EAS (compressibility) → TAS (density) → GS (wind).",
    whyWrong:
      "IAS corrected for instrument error is CAS. CAS corrected for compressibility is EAS.",
    knowCold: "ICE-TG: Indicated, Calibrated, Equivalent, True, Ground.",
    difficulty: 2,
    officialStyle: true,
    source: BASIC(["2.44", "2.45"]),
  },
  {
    id: "cc-u1-024",
    type: "connectChain",
    unit: "u1",
    conceptIds: ["c-icetg"],
    prompt: "Put the airspeed ladder in order, starting from the instrument.",
    trigger: "Indicated airspeed (IAS)",
    steps: [
      "Calibrated airspeed — corrected for instrument error",
      "Equivalent airspeed — corrected for compressibility",
      "True airspeed — corrected for density",
      "Groundspeed — corrected for wind",
    ],
    explanation:
      "ICE-TG. Each rung corrects for exactly one error, in this order.",
    knowCold: "IAS → CAS → EAS → TAS → GS.",
    difficulty: 1,
    source: BASIC(["2.42", "2.43", "2.44", "2.45", "2.46"]),
  },
  {
    id: "q-u1-025",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-tas-altitude"],
    prompt: "At 5,000 ft MSL, IAS is ___ TAS and ___ as TAS ___.",
    options: [
      "less than, increases, decreases",
      "greater than, decreases, increases",
      "less than, decreases, decreases",
      "greater than, remains constant, decreases",
    ],
    answer: 0,
    explanation:
      "Above sea level the local density is lower than ρ₀, so TAS exceeds IAS. As TAS increases at that altitude, the gap widens further — so IAS increasingly falls behind.",
    knowCold: "Above sea level, IAS < TAS, and the gap grows with speed and altitude.",
    difficulty: 3,
    officialStyle: true,
    source: BASIC(["2.45", "2.47"]),
  },
  {
    id: "q-u1-026",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-tas-altitude"],
    prompt:
      "True airspeed will be ___ indicated airspeed at 10,000 feet MSL.",
    options: ["less than", "equal to", "greater than", "unrelated to"],
    answer: 2,
    explanation:
      "TAS = IAS × √(ρ₀/ρ). Since ρ is less than ρ₀ at altitude, the radical exceeds 1 and TAS exceeds IAS.",
    knowCold: "Rule of thumb: TAS gains ~3 knots per 1,000 ft at constant IAS.",
    difficulty: 2,
    officialStyle: true,
    source: BASIC(["2.45"]),
  },
  {
    id: "cs-u1-027",
    type: "curveShift",
    unit: "u1",
    conceptIds: ["c-tas-altitude"],
    diagram: { id: "ias-tas-ladder", props: { altitude: 0 } },
    prompt:
      "You climb from sea level to 15,000 ft holding a constant indicated airspeed.",
    change: "Altitude increases at constant IAS",
    curveLabel: "True airspeed",
    options: ["up", "down", "none"],
    answer: "up",
    afterProps: { altitude: 15000 },
    explanation:
      "Density falls with altitude, so producing the same dynamic pressure — the same IAS — requires a higher true velocity through the air mass.",
    knowCold: "Constant IAS + climb = rising TAS.",
    difficulty: 2,
    source: BASIC(["2.45", "2.47"]),
  },

  /* ---------------- Airfoil & wing geometry ---------------- */
  {
    id: "q-u1-028",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-mean-camber-line"],
    prompt:
      "The line connecting all points halfway between the ___ and ___ of the airfoil is the ___.",
    options: [
      "upper surface, lower surface, mean camber line",
      "leading edge, trailing edge, mean camber line",
      "leading edge, trailing edge, chord line",
      "upper surface, lower surface, average chord",
    ],
    answer: 0,
    explanation:
      "The mean camber line runs halfway between the upper and lower SURFACES. The line drawn through the leading and trailing EDGES is the chord line.",
    knowCold: "MCL: halfway between surfaces. Chord line: through the edges.",
    difficulty: 2,
    officialStyle: true,
    source: BASIC(["2.59"]),
  },
  {
    id: "q-u1-029",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-chordline-chord"],
    prompt: "The chord of an airfoil is defined as",
    options: [
      "the angle between the longitudinal axis and the horizon",
      "the measurement along the chord line from leading edge to trailing edge",
      "an infinitely long line drawn through the leading and trailing edges",
      "the length of a wing",
    ],
    answer: 1,
    explanation:
      "Chord is the measurement; the chord LINE is the infinitely long straight line through both edges.",
    knowCold: "Chord = a length. Chord line = a line.",
    difficulty: 1,
    officialStyle: true,
    source: BASIC(["2.54", "2.55"]),
  },
  {
    id: "dl-u1-030",
    type: "dragLabel",
    unit: "u1",
    conceptIds: ["c-chordline-chord", "c-mean-camber-line", "c-camber-types"],
    prompt: "Label the airfoil geometry.",
    diagram: { id: "airfoil-geometry", props: { camber: 0.06, labels: false } },
    labels: ["Chord line", "Mean camber line", "Leading edge", "Trailing edge", "Camber"],
    slots: [
      { id: "s-chord", label: "", x: 240, y: 132 },
      { id: "s-mcl", label: "", x: 240, y: 96 },
      { id: "s-le", label: "", x: 62, y: 118 },
      { id: "s-te", label: "", x: 424, y: 130 },
      { id: "s-camber", label: "", x: 168, y: 78 },
    ],
    answer: {
      "s-chord": "Chord line",
      "s-mcl": "Mean camber line",
      "s-le": "Leading edge",
      "s-te": "Trailing edge",
      "s-camber": "Camber",
    },
    explanation:
      "Camber is the maximum distance between the mean camber line and the chord line, measured perpendicular to the chord line.",
    knowCold: "Camber = max gap between MCL and chord line.",
    difficulty: 2,
    source: BASIC(["2.54", "2.59", "2.61"]),
  },
  {
    id: "q-u1-031",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-camber-types"],
    prompt: "A ___ airfoil produces ___ lift at zero degrees AOA.",
    options: [
      "negatively cambered, zero",
      "positively cambered, zero",
      "symmetrically cambered, zero",
      "symmetrically cambered, positive",
    ],
    answer: 2,
    explanation:
      "A symmetric airfoil has identical velocity and pressure changes on both surfaces at 0° AOA, so there is no pressure differential and no net lift.",
    whyWrong:
      "A positively cambered airfoil makes positive lift at 0° AOA; a negatively cambered one makes negative lift.",
    knowCold: "Symmetric → zero lift at zero AOA. Cambered → not zero.",
    difficulty: 2,
    officialStyle: true,
    source: BASIC(["2.60", "2.61", "2.62"]),
  },
  {
    id: "q-u1-032",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-chordwise-spanwise"],
    prompt:
      "Spanwise flow travels ___ to the leading edge and chordwise flow travels ___ to the leading edge.",
    options: [
      "at right angles, parallel",
      "parallel, parallel",
      "parallel, perpendicular",
      "perpendicular, parallel",
    ],
    answer: 2,
    explanation:
      "Spanwise flow runs along the span, parallel to the leading edge, and makes no lift. Chordwise flow crosses the leading edge at right angles, accelerates over the wing, and is the only flow that produces lift.",
    knowCold: "Chordwise ⟂ LE and makes lift. Spanwise ∥ LE and does not.",
    difficulty: 2,
    officialStyle: true,
    source: BASIC(["2.63", "2.64"]),
  },
  {
    id: "q-u1-033",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-wing-planform"],
    prompt: "Aspect ratio is the ratio of",
    options: [
      "wingspan to average chord",
      "tip chord to root chord",
      "weight to wing area",
      "wing area to wingspan",
    ],
    answer: 0,
    explanation:
      "AR = b / c. Tip chord over root chord is taper ratio; weight over wing area is wing loading.",
    knowCold: "AR = span ÷ average chord. Gliders high, fighters low.",
    difficulty: 2,
    source: BASIC(["2.73", "2.74", "2.76"]),
  },

  /* ---------------- Axes, CG, AC ---------------- */
  {
    id: "q-u1-034",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-axes"],
    prompt: "A pitching moment around the ___ axis is controlled by the ___.",
    options: [
      "lateral, rudder",
      "lateral, elevator",
      "longitudinal, elevator",
      "longitudinal, aileron",
    ],
    answer: 1,
    explanation:
      "The lateral axis runs wingtip to wingtip; rotation about it is pitch, commanded by the elevator.",
    whyWrong:
      "The longitudinal axis is the roll axis, controlled by ailerons. The rudder controls yaw about the vertical axis.",
    knowCold: "Lateral → pitch → elevator. Longitudinal → roll → aileron. Vertical → yaw → rudder.",
    difficulty: 2,
    officialStyle: true,
    source: BASIC(["2.53", "2.79"]),
  },
  {
    id: "tap-u1-035",
    type: "tapDiagram",
    unit: "u1",
    conceptIds: ["c-axes"],
    prompt: "Tap the LONGITUDINAL axis.",
    diagram: { id: "axes-3d" },
    targets: [
      { id: "longitudinal", label: "Longitudinal (roll)", x: 250, y: 150, r: 40 },
      { id: "lateral", label: "Lateral (pitch)", x: 250, y: 74, r: 34 },
      { id: "vertical", label: "Vertical (yaw)", x: 336, y: 196, r: 34 },
    ],
    answer: "longitudinal",
    explanation:
      "The longitudinal axis runs from nose to tail. The aircraft ROLLS about it, using ailerons.",
    knowCold: "Nose to tail = longitudinal = roll.",
    difficulty: 1,
    source: BASIC(["2.53"]),
  },
  {
    id: "q-u1-036",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-axes"],
    prompt:
      "The ___ axis is the one about which the aircraft nose moves left or right around the center of gravity.",
    options: ["center", "yaw (vertical)", "pitch (lateral)", "roll (longitudinal)"],
    answer: 1,
    explanation:
      "Yaw is movement of the longitudinal axis around the vertical axis, controlled by the rudder.",
    knowCold: "Nose left/right = yaw = vertical axis = rudder.",
    difficulty: 1,
    officialStyle: true,
    source: BASIC(["2.53"]),
  },
  {
    id: "q-u1-037",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-cg"],
    prompt: "The center of gravity is",
    options: [
      "the point that describes an aircraft's flight path as it moves through an air mass",
      "the point along the chord line around which all changes in aerodynamic force take place",
      "the point at which all weight is considered to be concentrated",
      "the point at which control surfaces are considered to be balanced",
    ],
    answer: 2,
    explanation:
      "The CG is where all weight is considered concentrated and where the three axes intersect. It is the reference for all forces and moments.",
    whyWrong:
      "Option B defines the aerodynamic centre. Option D describes the hinge line.",
    knowCold: "CG = weight. AC = aerodynamic force.",
    difficulty: 2,
    officialStyle: true,
    source: BASIC(["2.77"]),
  },
  {
    id: "q-u1-038",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-aerodynamic-center"],
    prompt: "The aerodynamic center is located approximately",
    options: [
      "at the leading edge",
      "25% of the chord aft of the leading edge",
      "50% of the chord aft of the leading edge",
      "at the trailing edge stagnation point",
    ],
    answer: 1,
    explanation:
      "On a subsonic airfoil the aerodynamic centre sits between 23% and 27% of the chord aft of the leading edge — at maximum airfoil thickness — and stays there.",
    knowCold: "AC ≈ 25% chord aft of the LE.",
    difficulty: 2,
    source: BASIC(["2.78"]),
  },

  /* ---------------- AOA vs pitch attitude ---------------- */
  {
    id: "q-u1-039",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-pitch-vs-aoa"],
    prompt: "Angle of incidence is defined by the difference between",
    options: [
      "the chord line of an airfoil and the relative wind",
      "the chord line of an airfoil and the longitudinal axis",
      "the chord line of an airfoil and the horizon",
      "the chord line of an airfoil and the lateral axis",
    ],
    answer: 1,
    explanation:
      "Angle of incidence is a fixed, built-in angle between the wing chord line and the aircraft's longitudinal axis. Chord line against relative wind is angle of attack.",
    knowCold: "Incidence: chord line vs longitudinal axis. AOA: chord line vs relative wind.",
    difficulty: 2,
    officialStyle: true,
    source: BASIC(["2.68", "2.69"]),
  },
  {
    id: "trap-u1-040",
    type: "spotTheTrap",
    unit: "u1",
    conceptIds: ["c-pitch-vs-aoa"],
    prompt: '"Pitch attitude determines angle of attack."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. Pitch attitude is measured against the horizon; AOA is measured against the relative wind. The same nose attitude can give a high AOA in a descent and a low AOA in a climb.",
    whyWrong:
      "The trainee guide is explicit: flight path, relative wind and angle of attack should never be inferred from pitch attitude.",
    knowCold: "Pitch attitude vs horizon. AOA vs relative wind. Never infer one from the other.",
    difficulty: 3,
    source: BASIC(["2.65", "2.68"]),
  },
  {
    id: "sp-u1-041",
    type: "sliderPredict",
    unit: "u1",
    conceptIds: ["c-pitch-vs-aoa"],
    widget: "AoaVsPitchSlider",
    prompt:
      "Hold the nose at +5° pitch and steepen the descent. What happens to angle of attack?",
    options: [
      "It stays at 5° because pitch is unchanged",
      "It increases as the flight path drops below the nose",
      "It decreases as the flight path drops below the nose",
    ],
    answer: 1,
    explanation:
      "AOA is the angle between the chord line and the relative wind. Pushing the flight path down while holding the nose up opens that angle, so AOA increases.",
    knowCold: "AOA = pitch attitude − flight path angle (in the vertical plane).",
    difficulty: 3,
    source: BASIC(["2.65", "2.66", "2.67", "2.68"]),
  },
  {
    id: "tap-u1-042",
    type: "tapDiagram",
    unit: "u1",
    conceptIds: ["c-pitch-vs-aoa"],
    prompt: "Tap the RELATIVE WIND vector.",
    diagram: { id: "aoa-vs-pitch", props: { pitch: 8, flightPath: -4 } },
    targets: [
      { id: "relwind", label: "Relative wind", x: 118, y: 178, r: 32 },
      { id: "flightpath", label: "Flight path", x: 376, y: 196, r: 32 },
      { id: "chord", label: "Chord line", x: 330, y: 128, r: 28 },
      { id: "horizon", label: "Horizon", x: 420, y: 150, r: 26 },
    ],
    answer: "relwind",
    explanation:
      "Relative wind is equal in magnitude and OPPOSITE in direction to the flight path — it comes toward the aircraft from ahead of the flight path.",
    knowCold: "Relative wind is exactly opposite the flight path.",
    difficulty: 2,
    source: BASIC(["2.66", "2.67"]),
  },
  {
    id: "q-u1-043",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-pitch-vs-aoa"],
    prompt: "Relative wind is",
    options: [
      "equal and opposite in direction to the flight path",
      "always parallel to the horizon",
      "always aligned with the longitudinal axis",
      "the wind reported by the tower",
    ],
    answer: 0,
    explanation:
      "Relative wind is the airflow the aircraft experiences as it moves, equal in magnitude and opposite in direction to the flight path of the CG.",
    knowCold: "Flight path forward → relative wind backward, same line.",
    difficulty: 1,
    source: BASIC(["2.67"]),
  },
  {
    id: "q-u1-044",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-pitch-vs-aoa"],
    prompt: "Pitch attitude is the angle between",
    options: [
      "the chord line and the relative wind",
      "the longitudinal axis and the horizon",
      "the longitudinal axis and the chord line",
      "the flight path and the horizon",
    ],
    answer: 1,
    explanation:
      "Pitch attitude (θ) is measured between the aircraft's longitudinal axis and the horizon — it is what the attitude indicator shows.",
    knowCold: "Pitch attitude: longitudinal axis vs horizon.",
    difficulty: 2,
    source: BASIC(["2.65"]),
  },
  {
    id: "q-u1-045",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-altitude-types"],
    prompt: "Pressure altitude is",
    options: [
      "the actual height above mean sea level",
      "the height above the standard datum plane",
      "the height above the terrain directly beneath the aircraft",
      "pressure altitude corrected for temperature and humidity",
    ],
    answer: 1,
    explanation:
      "The standard datum plane is the elevation at which barometric pressure is 29.92 in-Hg. Option A is true altitude, C is absolute altitude, D is density altitude.",
    knowCold: "Pressure altitude: height above the 29.92 datum plane.",
    difficulty: 2,
    source: BASIC(["2.38", "2.39", "2.40"]),
  },
  {
    id: "q-u1-046",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-density", "c-static-pressure"],
    prompt: "Air density is ___ at 10,000 feet compared to ___ feet.",
    options: [
      "lower / 5,000",
      "equal / 5,000",
      "equal / 20,000",
      "lower / 20,000",
    ],
    answer: 0,
    explanation:
      "Density decreases with altitude because the air particles spread further apart. 10,000 ft is thinner than 5,000 ft and denser than 20,000 ft.",
    knowCold: "Altitude ↑ → pressure, temperature and density all ↓.",
    difficulty: 1,
    officialStyle: true,
    source: BASIC(["2.19", "2.20"]),
  },
  {
    id: "q-u1-047",
    type: "mcq",
    unit: "u1",
    conceptIds: ["c-scalar-vector"],
    prompt: "Which of the following is a vector quantity?",
    options: ["Temperature", "Volume", "Velocity", "Time"],
    answer: 2,
    explanation:
      "A vector carries magnitude and direction. Velocity is speed plus direction; speed alone is a scalar.",
    knowCold: "Speed = scalar. Velocity = vector.",
    difficulty: 1,
    source: BASIC(["2.1", "2.2"]),
  },
];
