import type { Question, SourceReference } from "@/lib/types";

const DRAG = (eo: string[]): SourceReference => ({
  document: "Aerodynamics Trainee Guide",
  chapter: "Lift Production and Drag",
  eo,
});

/** Unit 3 — Master Drag. */
export const U3_QUESTIONS: Question[] = [
  /* ---------------- Parasite drag ---------------- */
  {
    id: "q-u3-001",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-parasite-drag"],
    prompt: "Parasite drag is",
    options: [
      "the component of drag associated with the production of lift",
      "minimized by installing winglets, wingtip fuel tanks or missile rails",
      "greatest at low airspeeds",
      "made up of form, friction and interference drag",
    ],
    answer: 3,
    explanation:
      "Parasite drag is drag NOT associated with lift production, and it is composed of form, friction and interference drag.",
    whyWrong:
      "Options A, B and C all describe induced drag — the lift-associated drag, reduced by wingtip devices, dominant at low speed.",
    knowCold: "Parasite = form + friction + interference. Not lift-related.",
    difficulty: 2,
    officialStyle: true,
    source: DRAG(["2.87"]),
  },
  {
    id: "q-u3-002",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-form-drag"],
    prompt: "Form drag results from",
    options: [
      "the interaction between airflow and the aircraft surface",
      "airflow separation and the low pressure wake it creates",
      "the mixing of streamlines between components",
      "the production of lift on a finite wing",
    ],
    answer: 1,
    explanation:
      "Form (pressure or profile) drag comes from separation and the low-pressure wake behind it. It depends primarily on shape and is reduced by streamlining.",
    whyWrong:
      "Surface interaction is friction drag; streamline mixing is interference drag; lift production is induced drag.",
    knowCold: "Form drag = separation + low-pressure wake. Fix: streamline it.",
    difficulty: 2,
    source: DRAG(["2.87", "2.88"]),
  },
  {
    id: "q-u3-003",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-friction-drag"],
    prompt: "Friction drag is reduced by",
    options: [
      "painting, cleaning, waxing and flush rivets",
      "fairing and filleting component junctions",
      "installing winglets",
      "increasing wingspan",
    ],
    answer: 0,
    explanation:
      "Friction drag is the viscous retarding force over the whole wetted surface. Smoothing the surface reduces it.",
    whyWrong:
      "Fairing and filleting reduce interference drag. Winglets and greater span reduce induced drag.",
    knowCold: "Smooth the skin → less friction drag.",
    difficulty: 2,
    source: DRAG(["2.88"]),
  },
  {
    id: "q-u3-004",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-friction-drag", "c-form-drag"],
    prompt:
      "The dimples on a golf ball reduce total parasite drag because",
    options: [
      "they reduce friction drag more than they increase form drag",
      "they increase friction drag but reduce form drag by more",
      "they eliminate the boundary layer entirely",
      "they smooth the airflow into fully laminar flow",
    ],
    answer: 1,
    explanation:
      "The dimples trip the boundary layer turbulent. That costs friction drag but the turbulent layer sticks longer, shrinking the separated wake — and the form-drag saving is larger.",
    knowCold: "Turbulent boundary layer: more friction, later separation, less total drag.",
    difficulty: 3,
    source: DRAG(["2.88"]),
  },
  {
    id: "q-u3-005",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-interference-drag"],
    prompt: "Interference drag accounts for roughly what share of total drag?",
    options: ["1–2 percent", "5–10 percent", "25–30 percent", "50 percent"],
    answer: 1,
    explanation:
      "Roughly 5 to 10 percent of an airplane's total drag is attributed to interference drag from streamlines mixing between components.",
    knowCold: "Interference drag ≈ 5–10% of total drag. Fix: fairings and fillets.",
    difficulty: 2,
    source: DRAG(["2.87"]),
  },
  {
    id: "q-u3-006",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-parasite-drag"],
    prompt:
      "Equivalent parasite area (f) is",
    options: [
      "the cross-sectional area of the airplane",
      "the wetted surface area of the airplane",
      "the area of a flat plate perpendicular to the relative wind producing the same parasite drag",
      "the wing area minus the fuselage area",
    ],
    answer: 2,
    explanation:
      "f is a bookkeeping area: the flat plate that would generate the same combined form, friction and interference drag. It is explicitly NOT the aircraft's cross-section.",
    knowCold: "f = the equivalent flat plate, not the cross-section.",
    difficulty: 3,
    source: DRAG(["2.87"]),
  },
  {
    id: "q-u3-007",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-parasite-drag"],
    prompt: "If airspeed doubles, parasite drag",
    options: ["doubles", "quadruples", "halves", "is unchanged"],
    answer: 1,
    explanation:
      "D_P = ½ρV²f. Velocity is squared, so doubling speed gives four times the parasite drag.",
    knowCold: "Parasite drag ∝ V².",
    difficulty: 2,
    source: DRAG(["2.87"]),
  },

  /* ---------------- Induced drag ---------------- */
  {
    id: "q-u3-008",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-infinite-wing"],
    prompt: "On an INFINITE wing, upwash and downwash",
    options: [
      "do not exist",
      "exactly balance, producing no net change in lift",
      "produce a net increase in lift",
      "produce wingtip vortices",
    ],
    answer: 1,
    explanation:
      "Upwash raises average AOA and increases lift; downwash lowers it and decreases lift. On an infinite wing there are no tips, so the two exactly cancel.",
    knowCold: "Infinite wing: upwash = downwash, no induced drag.",
    difficulty: 2,
    source: DRAG(["2.89"]),
  },
  {
    id: "q-u3-009",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-finite-wing-vortices"],
    prompt: "On a FINITE wing, downwash is approximately",
    options: [
      "equal to upwash",
      "half of upwash",
      "doubled compared with an infinite wing",
      "eliminated by the wingtip",
    ],
    answer: 2,
    explanation:
      "Spanwise flow rounds the wingtip and adds to the downwash already produced by chordwise flow, roughly doubling it — which is what creates induced drag and the tip vortex.",
    knowCold: "Finite wing: downwash roughly doubles. Twice as much down as up.",
    difficulty: 3,
    source: DRAG(["2.90", "2.92"]),
  },
  {
    id: "q-u3-010",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-induced-drag"],
    prompt: "Induced drag is a result of an increase in ___ and increases as AOA ___.",
    options: [
      "downwash, decreases",
      "upwash, decreases",
      "downwash, increases",
      "upwash, increases",
    ],
    answer: 2,
    explanation:
      "Increased downwash inclines the average relative wind downward, rotating the total lift vector aft. The rearward component is induced drag, and it grows with AOA.",
    knowCold: "Downwash ↑ → lift vector rotates aft → induced drag ↑.",
    difficulty: 2,
    officialStyle: true,
    source: DRAG(["2.91", "2.92"]),
  },
  {
    id: "cc-u3-011",
    type: "connectChain",
    unit: "u3",
    conceptIds: ["c-finite-wing-vortices", "c-induced-drag"],
    prompt: "Build the chain that creates induced drag on a finite wing.",
    trigger: "High pressure below the wing seeks the low pressure above",
    steps: [
      "Air flows spanwise around the wingtip",
      "Wingtip vortices form and downwash roughly doubles",
      "Average relative wind is inclined downward",
      "Total lift vector rotates aft",
      "The rearward component of lift is induced drag",
    ],
    explanation:
      "Because total lift must stay perpendicular to the AVERAGE relative wind, tilting that wind tilts the lift vector — and the aft-pointing part of it is drag.",
    knowCold: "Tip flow → vortex → downwash → lift tilts aft → induced drag.",
    difficulty: 3,
    source: DRAG(["2.90", "2.91", "2.92"]),
  },
  {
    id: "q-u3-012",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-induced-drag"],
    prompt: "Effective lift is",
    options: [
      "greater than total lift",
      "equal to total lift",
      "the component of total lift perpendicular to the free-airstream relative wind, and less than total lift",
      "another name for induced drag",
    ],
    answer: 2,
    explanation:
      "Because total lift is inclined aft on a finite wing, its perpendicular component — effective lift — is always smaller than total lift. The parallel component is induced drag.",
    knowCold: "Total lift tilts aft: perpendicular part = effective lift, parallel part = induced drag.",
    difficulty: 3,
    source: DRAG(["2.91"]),
  },
  {
    id: "q-u3-013",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-induced-drag-factors"],
    prompt: "Induced drag is directly proportional to",
    options: [
      "velocity squared",
      "lift (or weight) squared",
      "density",
      "wingspan squared",
    ],
    answer: 1,
    explanation:
      "D_I = kL²/(ρV²b²). Lift/weight is on top and squared; density, velocity squared and wingspan squared are all on the bottom.",
    knowCold: "D_I = kW² / (ρV²b²).",
    difficulty: 2,
    source: DRAG(["2.93"]),
  },
  {
    id: "q-u3-014",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-induced-drag-factors"],
    prompt: "Increasing wingspan at constant weight and speed",
    options: [
      "increases induced drag",
      "decreases induced drag",
      "has no effect on induced drag",
      "increases induced drag only in ground effect",
    ],
    answer: 1,
    explanation:
      "Wingspan appears squared in the denominator of the induced drag equation, so a longer span reduces induced drag. That is why gliders have very high aspect ratios.",
    knowCold: "Longer span = less induced drag.",
    difficulty: 2,
    source: DRAG(["2.93"]),
  },
  {
    id: "q-u3-015",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-induced-drag-reduction"],
    prompt: "Which of these reduces induced drag?",
    options: [
      "Flush-mounted rivets",
      "Wingtip fuel tanks and winglets",
      "Fairing and filleting the wing root",
      "Streamlining the fuselage",
    ],
    answer: 1,
    explanation:
      "Devices that impede spanwise airflow around the tip — winglets, wingtip tanks, missile rails — reduce induced drag. The other three all target parasite drag.",
    knowCold: "Block the spanwise flow at the tip → less induced drag.",
    difficulty: 2,
    source: DRAG(["2.93"]),
  },

  /* ---------------- Ground effect ---------------- */
  {
    id: "q-u3-016",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-ground-effect"],
    prompt: "Ground effect occurs within",
    options: [
      "one-quarter wingspan of the ground",
      "one wingspan of the ground",
      "two wingspans of the ground",
      "100 feet of the ground",
    ],
    answer: 1,
    explanation:
      "Ground effect begins within one wingspan of the ground — about 33 ft for the T-6B — although at exactly one wingspan the induced drag reduction is only 1.4%.",
    knowCold: "Ground effect: within ONE wingspan.",
    difficulty: 2,
    source: DRAG(["2.94"]),
  },
  {
    id: "q-u3-017",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-ground-effect"],
    prompt: "Entering ground effect ___ effective lift and ___ induced drag.",
    options: [
      "increases, increases",
      "increases, decreases",
      "decreases, increases",
      "decreases, decreases",
    ],
    answer: 1,
    explanation:
      "The ground prevents full downwash, so the total lift vector rotates forward: more effective lift, less induced drag.",
    knowCold: "Ground effect: effective lift ↑, induced drag ↓.",
    difficulty: 2,
    officialStyle: true,
    source: DRAG(["2.95"]),
  },
  {
    id: "ba-u3-018",
    type: "beforeAfter",
    unit: "u3",
    conceptIds: ["c-ground-effect"],
    prompt:
      "The aircraft lifts off and climbs OUT of ground effect. What happens?",
    diagram: { id: "ground-effect", props: { heightFraction: 0.15 } },
    states: ["In ground effect", "Out of ground effect"],
    beforeProps: { heightFraction: 0.15 },
    afterProps: { heightFraction: 1.4 },
    rows: [
      { label: "Downwash", options: ["Increases", "Decreases", "Unchanged"], answer: 0 },
      { label: "Effective lift", options: ["Increases", "Decreases", "Unchanged"], answer: 1 },
      { label: "Induced drag", options: ["Increases", "Decreases", "Unchanged"], answer: 0 },
    ],
    explanation:
      "Leaving ground effect restores full downwash, so effective lift falls and induced drag climbs. If the pilot does not account for it, the aircraft can settle back onto the runway — a real gear-up landing risk.",
    knowCold: "Leaving ground effect: lift ↓, induced drag ↑. Do not rotate early and coast.",
    difficulty: 3,
    source: DRAG(["2.95"]),
  },
  {
    id: "q-u3-019",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-ground-effect"],
    prompt:
      "Maximum induced drag reduction from ground effect is approximately",
    options: ["1.4%", "23.5%", "60%", "90%"],
    answer: 2,
    explanation:
      "1.4% at one wingspan, 23.5% at one-quarter wingspan, and a maximum of about 60% just before touchdown or just after liftoff.",
    knowCold: "Ground effect: 1.4% @ 1 span · 23.5% @ ¼ span · 60% max.",
    difficulty: 3,
    source: DRAG(["2.95"]),
  },

  /* ---------------- Total drag & L/Dmax ---------------- */
  {
    id: "q-u3-020",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-total-drag"],
    prompt: "Total drag is composed of",
    options: [
      "parasite and induced drag",
      "form and interference drag",
      "thrust and lift",
      "upwash and downwash",
    ],
    answer: 0,
    explanation: "D_T = D_P + D_I. Form and interference are subsets of parasite drag.",
    knowCold: "Total drag = parasite + induced.",
    difficulty: 1,
    officialStyle: true,
    source: DRAG(["2.99"]),
  },
  {
    id: "q-u3-021",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-total-drag"],
    prompt: "As airspeed decreases, total drag is primarily composed of",
    options: ["Parasite drag", "Form drag", "Interference drag", "Induced drag"],
    answer: 3,
    explanation:
      "Below L/Dmax velocity the aircraft is dominated by induced drag, which rises as speed falls. Above L/Dmax, parasite drag dominates.",
    knowCold: "Slow = induced drag. Fast = parasite drag.",
    difficulty: 2,
    officialStyle: true,
    source: DRAG(["2.100"]),
  },
  {
    id: "gr-u3-022",
    type: "graphRead",
    unit: "u3",
    conceptIds: ["c-ldmax", "c-total-drag"],
    prompt: "Tap L/Dmax on the total drag curve.",
    diagram: { id: "drag-curves", props: { marker: null } },
    targets: [
      { id: "ldmax", label: "L/Dmax", x: 250, y: 172, r: 26 },
      { id: "lowspeed", label: "Induced-dominated region", x: 132, y: 92, r: 26 },
      { id: "highspeed", label: "Parasite-dominated region", x: 386, y: 92, r: 26 },
      { id: "parasitecurve", label: "Parasite drag curve", x: 344, y: 168, r: 22 },
    ],
    answer: "ldmax",
    explanation:
      "L/Dmax sits at the BOTTOM of the total drag curve — minimum total drag — and it is exactly where the parasite and induced curves cross.",
    knowCold: "L/Dmax = bottom of total drag = where parasite equals induced.",
    difficulty: 2,
    source: DRAG(["2.98"]),
  },
  {
    id: "q-u3-023",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-ldmax"],
    prompt: "L/Dmax yields",
    options: [
      "greatest amount of lift produced",
      "minimum total drag",
      "the lowest ratio of lift to drag",
      "the AOA and velocity associated with max endurance",
    ],
    answer: 1,
    explanation:
      "L/Dmax is the greatest ratio of lift to drag, which occurs at minimum total drag — the bottom of the total drag curve.",
    whyWrong:
      "Maximum lift is CLmax. For a turboprop, max endurance is at the bottom of the POWER required curve, not at L/Dmax.",
    knowCold: "L/Dmax = minimum total drag ≠ maximum lift.",
    difficulty: 2,
    officialStyle: true,
    source: DRAG(["2.98"]),
  },
  {
    id: "q-u3-024",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-ldmax"],
    prompt: "At L/Dmax AOA,",
    options: [
      "induced drag is zero",
      "parasite drag is zero",
      "parasite drag and induced drag are equal",
      "parasite drag is twice induced drag",
    ],
    answer: 2,
    explanation:
      "The total drag curve bottoms out exactly where the falling induced drag curve crosses the rising parasite drag curve.",
    knowCold: "At L/Dmax: D_P = D_I.",
    difficulty: 2,
    source: DRAG(["2.98"]),
  },
  {
    id: "q-u3-025",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-ldmax"],
    prompt: "The most efficient AOA is known as",
    options: [
      "CLmax AOA",
      "L/Dmax AOA",
      "the point of maximum lift",
      "the peak of the total drag curve",
    ],
    answer: 1,
    explanation:
      "L/Dmax AOA gives the greatest ratio of lift to drag, so it is the most efficient angle of attack. CLmax AOA is the most EFFECTIVE.",
    whyWrong:
      "The total drag curve has a minimum, not a meaningful peak, at L/Dmax.",
    knowCold: "Efficient = L/Dmax AOA. Effective = CLmax AOA.",
    difficulty: 2,
    officialStyle: true,
    source: DRAG(["2.98"]),
  },
  {
    id: "q-u3-026",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-ldmax"],
    prompt: "An increase in weight or altitude will",
    options: [
      "increase L/Dmax airspeed but not affect L/Dmax or L/Dmax AOA",
      "increase L/Dmax and L/Dmax AOA",
      "decrease L/Dmax airspeed",
      "have no effect on any L/Dmax parameter",
    ],
    answer: 0,
    explanation:
      "Weight and altitude move the SPEED at which L/Dmax occurs, but the ratio itself and the angle of attack that produces it are set by the wing.",
    knowCold: "Weight or altitude change L/Dmax AIRSPEED only. AOA and ratio hold.",
    difficulty: 3,
    source: DRAG(["2.98"]),
  },
  {
    id: "trap-u3-027",
    type: "spotTheTrap",
    unit: "u3",
    conceptIds: ["c-ldmax"],
    prompt: '"L/D measures the efficiency of the engine."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. L/D is the efficiency of the WING. The trainee guide is explicit about this distinction.",
    knowCold: "L/D = wing efficiency, not engine efficiency.",
    difficulty: 2,
    source: DRAG(["2.98"]),
  },
  {
    id: "cs-u3-028",
    type: "curveShift",
    unit: "u3",
    conceptIds: ["c-total-drag", "c-induced-drag-factors"],
    diagram: { id: "drag-curves", props: { weight: 1 } },
    prompt: "The aircraft takes off heavier than usual.",
    change: "Gross weight increases",
    curveLabel: "Total drag curve",
    options: ["upRight", "upLeft", "downRight", "down"],
    answer: "upRight",
    afterProps: { weight: 1.35 },
    explanation:
      "More weight needs more lift, which at a given AOA needs more velocity. Higher speed and more lift raise both drag types, so the curve moves up and right — and L/Dmax airspeed increases.",
    knowCold: "Weight ↑ → total drag curve UP and RIGHT.",
    difficulty: 3,
    source: DRAG(["2.93", "2.100"]),
  },
  {
    id: "sp-u3-029",
    type: "sliderPredict",
    unit: "u3",
    conceptIds: ["c-total-drag", "c-parasite-drag", "c-induced-drag-factors"],
    widget: "DragLabMini",
    prompt:
      "Starting well below L/Dmax, slide airspeed upward. What happens to TOTAL drag at first?",
    options: [
      "It rises immediately",
      "It falls until L/Dmax, then rises",
      "It falls continuously",
      "It stays flat",
    ],
    answer: 1,
    explanation:
      "Below L/Dmax the collapsing induced drag outweighs the growing parasite drag, so total drag falls. Past L/Dmax the V² parasite term takes over and total drag climbs.",
    knowCold: "Total drag is U-shaped, with its minimum at L/Dmax.",
    difficulty: 2,
    source: DRAG(["2.100"]),
  },
  {
    id: "q-u3-030",
    type: "mcq",
    unit: "u3",
    conceptIds: ["c-induced-drag-factors"],
    prompt:
      "Why does induced drag decrease as airspeed increases in level flight?",
    options: [
      "Because parasite drag takes over and cancels it",
      "Because lift is no longer produced at high speed",
      "Because the required AOA falls, weakening the vortices and downwash",
      "Because density increases with airspeed",
    ],
    answer: 2,
    explanation:
      "Level flight needs constant lift. Going faster means a lower AOA and a lower C_L, which weakens the tip vortices and the downwash they create.",
    knowCold: "Faster → lower AOA → weaker vortices → less induced drag.",
    difficulty: 2,
    officialStyle: true,
    source: DRAG(["2.93"]),
  },
];
