import type { Question, SourceReference } from "@/lib/types";

const STALLS = (eo: string[]): SourceReference => ({
  document: "Aerodynamics Trainee Guide",
  chapter: "Stalls",
  eo,
});
const PERF = (eo: string[]): SourceReference => ({
  document: "Aerodynamics Trainee Guide",
  chapter: "Performance and Maneuvering",
  eo,
});

/** Unit 5 — Limits & Maneuvering. */
export const U5_QUESTIONS: Question[] = [
  /* ---------------- Boundary layer ---------------- */
  {
    id: "q-u5-001",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-laminar-turbulent"],
    prompt: "___ are the two types of flow that exist within the boundary layer.",
    options: [
      "Chordwise and spanwise",
      "Laminar and turbulent",
      "Friction and form",
      "Induced and parasite",
    ],
    answer: 1,
    explanation:
      "The boundary layer is laminar near the leading edge and becomes turbulent as it flows aft.",
    knowCold: "Boundary layer: laminar first, then turbulent.",
    difficulty: 1,
    officialStyle: true,
    source: STALLS(["3.2"]),
  },
  {
    id: "q-u5-002",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-laminar-turbulent"],
    prompt: "Compared with laminar flow, turbulent boundary-layer flow",
    options: [
      "produces less friction drag and separates more easily",
      "produces more friction drag but adheres better, delaying separation",
      "produces less friction drag and adheres better",
      "produces more friction drag and separates more easily",
    ],
    answer: 1,
    explanation:
      "That trade — more friction for later separation — is exactly why vortex generators and golf-ball dimples exist.",
    knowCold: "Turbulent: more friction, better adhesion, later separation.",
    difficulty: 2,
    source: STALLS(["3.2"]),
  },
  {
    id: "q-u5-003",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-boundary-layer"],
    prompt: "The boundary layer is",
    options: [
      "the layer of airflow that shows local retardation due to viscosity",
      "the layer of air displaced by the wingtip vortex",
      "the region of separated flow behind the wing",
      "the volume of air within one wingspan of the aircraft",
    ],
    answer: 0,
    explanation:
      "It is about 1 mm thick at the leading edge — the thickness of a playing card — and grows as it moves aft.",
    knowCold: "Boundary layer: viscous retardation next to the surface.",
    difficulty: 1,
    source: STALLS(["3.1"]),
  },
  {
    id: "q-u5-004",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-pressure-gradient", "c-bl-separation"],
    prompt:
      "The adverse pressure gradient exists between",
    options: [
      "the leading edge and the point of maximum thickness",
      "the point of maximum thickness and the trailing edge",
      "the upper and lower surfaces",
      "the wing root and the wingtip",
    ],
    answer: 1,
    explanation:
      "From maximum thickness (low static pressure) aft to the trailing edge (high static pressure) the flow is pushing uphill against pressure — the adverse gradient. Forward of maximum thickness the gradient is favourable.",
    knowCold: "LE → max thickness = favourable. Max thickness → TE = adverse.",
    difficulty: 3,
    source: STALLS(["3.3"]),
  },
  {
    id: "sp-u5-005",
    type: "sliderPredict",
    unit: "u5",
    conceptIds: ["c-bl-separation"],
    widget: "BoundaryLayerSlider",
    prompt:
      "Raise angle of attack and watch the separation point. Which way does it move?",
    options: [
      "Aft, toward the trailing edge",
      "Forward, toward the leading edge",
      "It does not move until the stall",
    ],
    answer: 1,
    explanation:
      "Higher AOA drains the boundary layer's kinetic energy and strengthens the adverse gradient, so the flow gives up earlier — the separation point marches FORWARD.",
    knowCold: "AOA ↑ → separation point moves FORWARD.",
    difficulty: 2,
    source: STALLS(["3.3"]),
  },
  {
    id: "trap-u5-006",
    type: "spotTheTrap",
    unit: "u5",
    conceptIds: ["c-bl-separation", "c-stall"],
    prompt:
      '"A stall occurs when the boundary layer separation point moves aft toward the trailing edge."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False, and this exact distractor appears on the practice test. The separation point moves FORWARD toward the leading edge as AOA increases; when it gets far enough forward, C_L drops and the wing stalls.",
    knowCold: "Separation moves FORWARD into a stall, never aft.",
    difficulty: 2,
    source: STALLS(["3.3"]),
  },

  /* ---------------- Stalls ---------------- */
  {
    id: "q-u5-007",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-stall"],
    prompt: "A stall occurs when",
    options: [
      "the boundary layer separation point moves aft towards the trailing edge",
      "an increase in AOA results in a decrease in CL",
      "the wing no longer produces lift",
      "the boundary layer begins to adhere to the wing",
    ],
    answer: 1,
    explanation:
      "That IS the definition of a stall. A stalled wing still produces lift — just less than it did, and less than is needed.",
    whyWrong:
      "'The wing no longer produces lift' is the most common wrong answer. Separation moves forward, not aft.",
    knowCold: "Stall = AOA ↑ produces CL ↓.",
    difficulty: 2,
    officialStyle: true,
    source: STALLS(["3.5"]),
  },
  {
    id: "q-u5-008",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-stall", "c-clmax-aoa"],
    prompt: "The only cause of a stall is",
    options: [
      "low airspeed",
      "excessive angle of attack",
      "high gross weight",
      "insufficient power",
    ],
    answer: 1,
    explanation:
      "The trainee guide states it flatly: the only cause of a stall is excessive AOA. Regardless of flight conditions or airspeed, the wing always stalls at CLmax AOA.",
    knowCold: "Only cause of a stall: exceeding CLmax AOA.",
    difficulty: 2,
    source: STALLS(["3.6", "3.7"]),
  },
  {
    id: "q-u5-009",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-clmax-aoa"],
    prompt: "The T-6B stalls at approximately",
    options: ["8.8 units AOA", "15.5 units AOA", "18 units AOA", "22 units AOA"],
    answer: 2,
    explanation:
      "18 units, regardless of airspeed, nose attitude, weight or altitude. Stick shakers activate at 15.5 units; 8.8 units is max endurance AOA.",
    knowCold: "T-6B: stall 18 units, shaker 15.5 units.",
    difficulty: 2,
    source: STALLS(["3.16"]),
  },
  {
    id: "q-u5-010",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-clmax-aoa"],
    prompt:
      "Approaching a stall in the T-6B, control effectiveness is lost in what order?",
    options: [
      "rudder, elevator, ailerons",
      "elevator, ailerons, rudder",
      "ailerons, elevator, rudder",
      "ailerons, rudder, elevator",
    ],
    answer: 2,
    explanation:
      "Ailerons go first, then elevator, then rudder. The rudder stays effective longest — which is why it is the principal spin-recovery control.",
    knowCold: "T-6B loses ailerons → elevator → rudder.",
    difficulty: 3,
    source: STALLS(["3.9"]),
  },
  {
    id: "q-u5-011",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-stall-recovery"],
    prompt: "The only action necessary for stall recovery is to",
    options: [
      "add full power",
      "level the wings",
      "decrease angle of attack below CLmax AOA",
      "lower the flaps",
    ],
    answer: 2,
    explanation:
      "Reducing AOA is the only aerodynamic requirement. RELAX, MAX, LEVEL, BALL adds power, wings level and coordination to make the recovery safe and efficient.",
    knowCold: "Break the stall with AOA. Everything else is housekeeping.",
    difficulty: 2,
    source: STALLS(["3.6"]),
  },
  {
    id: "q-u5-012",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-stall-speed"],
    prompt:
      "The minimum true airspeed required to maintain level flight at CLmax AOA is also known as",
    options: [
      "L/Dmax airspeed",
      "stall speed",
      "CLmax airspeed",
      "minimum takeoff speed",
    ],
    answer: 1,
    explanation:
      "That is the definition of stall speed. It varies with weight, altitude, power and load factor, but the stalling AOA behind it does not.",
    knowCold: "Vs = minimum TRUE airspeed for level flight at CLmax AOA.",
    difficulty: 2,
    officialStyle: true,
    source: STALLS(["3.10"]),
  },
  {
    id: "q-u5-013",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-stall-speed"],
    prompt: "As weight ___, stall speed ___.",
    options: [
      "increases, decreases",
      "decreases, increases",
      "increases, remains constant",
      "decreases, decreases",
    ],
    answer: 3,
    explanation:
      "Vs = √(2W / ρSC_Lmax). Less weight requires less lift, so the wing can reach the same lift at a lower speed. Carrier pilots dump fuel before landing for exactly this reason.",
    knowCold: "Lighter aircraft, lower stall speed.",
    difficulty: 2,
    officialStyle: true,
    source: STALLS(["3.11"]),
  },
  {
    id: "q-u5-014",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-stall-speed-altitude"],
    prompt: "As altitude increases,",
    options: [
      "both true and indicated stall speed increase",
      "true stall speed increases and indicated stall speed is unchanged",
      "true stall speed is unchanged and indicated stall speed increases",
      "both decrease",
    ],
    answer: 1,
    explanation:
      "Local density falls, so a higher TRUE airspeed is needed for the same dynamic pressure. Indicated stall speed uses ρ₀, a constant, so it does not move.",
    knowCold: "Altitude ↑: true stall speed ↑, indicated stall speed unchanged.",
    difficulty: 3,
    source: STALLS(["3.10"]),
  },
  {
    id: "q-u5-015",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-power-on-off-stall"],
    prompt: "Stall speed increases in",
    options: [
      "flaps extended flight",
      "descending flight",
      "power-on flight",
      "power-off flight",
    ],
    answer: 3,
    explanation:
      "Power-off removes the vertical component of thrust and the propeller's acceleration of air over the wing root, so more of the weight must be carried by the wing alone.",
    whyWrong: "Flaps extended LOWERS stall speed. Power-on LOWERS stall speed.",
    knowCold: "Power OFF = higher stall speed. Power ON = lower.",
    difficulty: 2,
    officialStyle: true,
    source: STALLS(["3.8"]),
  },
  {
    id: "q-u5-016",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-power-on-off-stall"],
    prompt:
      "The factors associated with increased thrust that lower power-on stall speed are",
    options: [
      "reduced weight and increased wing area",
      "the vertical component of thrust and propeller acceleration over the wing",
      "increased camber and increased CLmax AOA",
      "ground effect and reduced downwash",
    ],
    answer: 1,
    explanation:
      "At high pitch attitudes part of the weight is carried by the vertical component of the thrust vector, and the propeller accelerates air over the wing behind it.",
    knowCold: "Power-on: thrust vertical component + prop wash over the wing.",
    difficulty: 3,
    source: STALLS(["3.8"]),
  },
  {
    id: "cc-u5-017",
    type: "connectChain",
    unit: "u5",
    conceptIds: ["c-bl-separation", "c-stall"],
    prompt: "Build the chain from too much AOA to a stall.",
    trigger: "Angle of attack increases past the normal range",
    steps: [
      "Boundary layer kinetic energy decreases",
      "The adverse pressure gradient strengthens",
      "The separation point moves forward toward the leading edge",
      "Coefficient of lift decreases",
      "The wing stalls",
    ],
    explanation:
      "This is the whole mechanism of a stall — and it is why airspeed does not appear anywhere in it.",
    knowCold: "AOA ↑ → BL energy ↓ → separation forward → CL ↓ → stall.",
    difficulty: 3,
    source: STALLS(["3.3", "3.6"]),
  },

  /* ---------------- High lift devices ---------------- */
  {
    id: "q-u5-018",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-high-lift-purpose"],
    prompt: "The primary purpose of high lift devices is to",
    options: [
      "increase cruise speed",
      "reduce takeoff and landing speeds",
      "increase CLmax AOA",
      "reduce parasite drag",
    ],
    answer: 1,
    explanation:
      "High lift devices raise C_L at high AOA, which reduces both indicated and true stall speeds — and therefore takeoff and landing speeds.",
    knowCold: "High lift devices exist to lower takeoff and landing speeds.",
    difficulty: 2,
    source: STALLS(["3.12"]),
  },
  {
    id: "q-u5-019",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-blc-devices", "c-camber-devices"],
    prompt:
      "Boundary layer control devices such as slots and slats affect the CL curve by",
    options: [
      "increasing CLmax and increasing CLmax AOA",
      "increasing CLmax and decreasing CLmax AOA",
      "decreasing CLmax and increasing CLmax AOA",
      "increasing CL at low AOA only",
    ],
    answer: 0,
    explanation:
      "Slots and slats re-energise the boundary layer so separation is delayed to a HIGHER angle of attack. Because they do not change camber, they do not change C_L at low AOA.",
    whyWrong:
      "Option B describes flaps — camber devices raise CLmax but LOWER CLmax AOA.",
    knowCold: "BLC: CLmax ↑ AND CLmax AOA ↑. Flaps: CLmax ↑ but CLmax AOA ↓.",
    difficulty: 3,
    source: STALLS(["3.13", "3.14"]),
  },
  {
    id: "ba-u5-020",
    type: "beforeAfter",
    unit: "u5",
    conceptIds: ["c-blc-devices", "c-camber-devices"],
    prompt: "Compare a leading-edge SLAT against a trailing-edge FLAP.",
    diagram: { id: "high-lift-comparison", props: { device: "slat" } },
    states: ["Slat (BLC)", "Flap (camber)"],
    beforeProps: { device: "slat" },
    afterProps: { device: "flap" },
    rows: [
      {
        label: "Effect on CLmax",
        options: ["Both increase it", "Only the slat increases it", "Only the flap increases it"],
        answer: 0,
      },
      {
        label: "Effect on CLmax AOA",
        options: [
          "Slat raises it, flap lowers it",
          "Both raise it",
          "Slat lowers it, flap raises it",
        ],
        answer: 0,
      },
      {
        label: "Effect on CL at low AOA",
        options: [
          "Slat: no change · Flap: increases it",
          "Both increase it",
          "Slat: increases it · Flap: no change",
        ],
        answer: 0,
      },
    ],
    explanation:
      "Slats and slots buy you a higher stalling angle. Flaps buy you more lift at every angle but bring the stall on sooner. Many designs use both to keep approach attitudes flat.",
    knowCold: "Slats delay the stall to higher AOA. Flaps bring it on at lower AOA.",
    difficulty: 3,
    source: STALLS(["3.13", "3.14", "3.15"]),
  },
  {
    id: "q-u5-021",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-camber-devices"],
    prompt: "The flap type that also significantly increases wing AREA is the",
    options: ["plain flap", "split flap", "slotted flap", "Fowler flap"],
    answer: 3,
    explanation:
      "The Fowler flap moves down AND aft, adding camber, area and one or more slots for boundary layer control. That extra area creates a large twisting moment, so it needs a stronger wing.",
    knowCold: "Fowler = camber + area + slot. T-6B uses split flaps.",
    difficulty: 2,
    source: STALLS(["3.15"]),
  },
  {
    id: "q-u5-022",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-stall-pattern"],
    prompt: "The most desirable stall pattern begins at the",
    options: [
      "wingtip, to preserve elevator authority",
      "wing root, to preserve aileron effectiveness and provide buffet warning",
      "trailing edge, to delay separation",
      "leading edge, to give the earliest possible warning",
    ],
    answer: 1,
    explanation:
      "A root-first stall keeps the ailerons in clean air until the wing is fully stalled, and the turbulent root wake buffets the empennage as an aerodynamic warning.",
    knowCold: "Root stall first: keeps roll control, gives buffet warning.",
    difficulty: 2,
    source: STALLS(["3.17"]),
  },
  {
    id: "q-u5-023",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-wing-tailoring"],
    prompt: "Geometric twist means",
    options: [
      "a gradual change in airfoil shape from root to tip",
      "a decrease in angle of incidence from wing root to wingtip",
      "a sharp metal strip on the leading edge of the root",
      "a chordwise fence on a swept wing",
    ],
    answer: 1,
    explanation:
      "Geometric twist lowers the tip's angle of incidence so the tip flies at a lower AOA and the root reaches stalling AOA first. Aerodynamic twist is the shape-change version; stall strips and fences are separate devices.",
    knowCold: "Geometric twist = incidence change. Aerodynamic twist = shape change.",
    difficulty: 3,
    source: STALLS(["3.18"]),
  },

  /* ---------------- Turns and load factor ---------------- */
  {
    id: "q-u5-024",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-turn-lift"],
    prompt: "During a coordinated level turn, ___ must increase to maintain level flight.",
    options: [
      "horizontal lift component",
      "total lift",
      "power",
      "both total lift and power",
    ],
    answer: 3,
    explanation:
      "Banking tilts the lift vector, so total lift must rise for the vertical component to still equal weight. The extra lift raises induced drag, so power must rise too.",
    knowCold: "Bank → more total lift AND more power.",
    difficulty: 2,
    officialStyle: true,
    source: PERF(["2.154", "2.162"]),
  },
  {
    id: "q-u5-025",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-load-factor"],
    prompt: "The load factor equation is",
    options: ["L / W", "L × D", "L / D", "L × W"],
    answer: 0,
    explanation:
      "Load factor n is total lift divided by weight — the Gs the aircraft feels. L/D is the efficiency ratio, an entirely different quantity.",
    knowCold: "n = L / W.",
    difficulty: 1,
    officialStyle: true,
    source: PERF(["2.164"]),
  },
  {
    id: "q-u5-026",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-load-factor"],
    prompt: "A level, constant-airspeed turn at 60° angle of bank produces",
    options: ["1.4 G", "2 G", "2.5 G", "3 G"],
    answer: 1,
    explanation:
      "n = 1 / cos 60° = 2. The aircraft must produce twice its weight in lift, so 2 Gs of back stick are required.",
    knowCold: "60° bank = 2 G. Above 45° the numbers climb fast.",
    difficulty: 2,
    source: PERF(["2.162", "2.163"]),
  },
  {
    id: "cc-u5-027",
    type: "connectChain",
    unit: "u5",
    conceptIds: ["c-turn-lift", "c-load-factor", "c-accelerated-stall"],
    prompt: "Put these in the correct order.",
    trigger: "Bank angle increases",
    steps: [
      "Load factor increases",
      "Lift required increases",
      "Angle of attack demand increases",
      "Stall speed increases",
    ],
    explanation:
      "This is the signature maneuvering chain, and it is why a steep approach turn at low airspeed kills people.",
    knowCold: "Bank ↑ → n ↑ → lift required ↑ → stall speed ↑.",
    difficulty: 2,
    source: PERF(["2.163"]),
  },
  {
    id: "q-u5-028",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-accelerated-stall"],
    prompt:
      "An aircraft with a wings-level stall speed of 100 knots performs a 2 G maneuver. Its accelerated stall speed is approximately",
    options: ["100 knots", "120 knots", "140 knots", "200 knots"],
    answer: 2,
    explanation:
      "Accelerated stall speed = Vs × √n = 100 × √2 ≈ 140 knots. A 60° bank raises stall speed by about 40%.",
    knowCold: "Accelerated stall speed = Vs × √n.",
    difficulty: 3,
    source: PERF(["2.163"]),
  },
  {
    id: "sp-u5-029",
    type: "sliderPredict",
    unit: "u5",
    conceptIds: ["c-turn-rate-radius"],
    widget: "TurnLabMini",
    prompt:
      "Hold bank angle fixed and increase airspeed. What happens to turn RADIUS?",
    options: ["It decreases", "It increases", "It is unchanged"],
    answer: 1,
    explanation:
      "r = V² / (g tan φ). Velocity is squared on top, so going faster at the same bank sweeps a much wider circle — and the turn rate falls.",
    knowCold: "Faster at fixed bank: bigger radius, slower rate.",
    difficulty: 2,
    source: PERF(["2.160"]),
  },
  {
    id: "q-u5-030",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-turn-rate-radius"],
    prompt: "Turn radius is",
    options: [
      "a factor of velocity and bank angle",
      "a factor of weight, airspeed and temperature",
      "a factor of velocity, wingspan and bank angle",
      "measured in degrees per second",
    ],
    answer: 0,
    explanation:
      "In a level coordinated turn, both turn rate and turn radius depend only on airspeed and angle of bank — never on weight. Degrees per second is turn RATE.",
    knowCold: "Turn performance: airspeed and bank only. Weight is irrelevant.",
    difficulty: 2,
    officialStyle: true,
    source: PERF(["2.158", "2.159", "2.160"]),
  },
  {
    id: "trap-u5-031",
    type: "spotTheTrap",
    unit: "u5",
    conceptIds: ["c-turn-rate-radius"],
    prompt:
      '"A heavier aircraft cannot turn as tightly as a lighter one at the same airspeed and bank angle."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. Turn rate and radius are independent of weight. Two aircraft at the same speed and bank fly identical circles — the heavier one just produces more lift to do it.",
    knowCold: "Same speed + same bank = same turn, whatever the weight.",
    difficulty: 3,
    source: PERF(["2.158"]),
  },

  /* ---------------- Structural limits & V-n ---------------- */
  {
    id: "q-u5-032",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-load-definitions"],
    prompt: "The limit load is ___ the ultimate load.",
    options: ["1.5 times", "1/3 of", "2.5 times", "2/3 of"],
    answer: 3,
    explanation:
      "Ultimate load is 150% of limit load, so limit load is two-thirds of ultimate. Watch which direction the question asks.",
    knowCold: "Ultimate = 1.5 × limit. Limit = 2/3 of ultimate.",
    difficulty: 3,
    officialStyle: true,
    source: PERF(["2.164"]),
  },
  {
    id: "q-u5-033",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-load-definitions"],
    prompt: "Ultimate load factor is defined as",
    options: [
      "the least load factor an airplane can sustain without any risk of permanent deformation",
      "+6.0 Gs",
      "−1.0 G",
      "the maximum load factor the airplane can withstand without structural failure",
    ],
    answer: 3,
    explanation:
      "There will be permanent deformation at the ultimate load factor, but no failure of the major load-carrying components. Beyond it, structural failure is imminent.",
    knowCold: "Limit = no deformation. Ultimate = no failure (but deformation likely).",
    difficulty: 2,
    officialStyle: true,
    source: PERF(["2.164"]),
  },
  {
    id: "q-u5-034",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-load-definitions"],
    prompt: "The elastic limit is",
    options: [
      "the maximum load factor anticipated in normal operation",
      "the maximum load that can be applied and still allow return to the original shape",
      "150% of the limit load",
      "the load at which the wing separates",
    ],
    answer: 1,
    explanation:
      "Limit load factor is deliberately designed BELOW the elastic limit of individual components, which is what guarantees the aircraft reaches its expected service life.",
    knowCold: "Elastic limit: the last load you can undo.",
    difficulty: 3,
    source: PERF(["2.165"]),
  },
  {
    id: "q-u5-035",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-maneuver-speed"],
    prompt:
      "What is the point called between the accelerated stall line and the positive limit load?",
    options: ["cornering viscosity", "Vne", "limit load", "maneuver speed"],
    answer: 3,
    explanation:
      "The maneuver point is where those two boundaries meet. The indicated airspeed there is maneuver speed (Va) or cornering velocity — the lowest speed at which limit load can be reached, and the point of best turn performance.",
    knowCold: "Maneuver point = accelerated stall line ∩ limit load line.",
    difficulty: 3,
    officialStyle: true,
    source: PERF(["2.166", "2.167"]),
  },
  {
    id: "q-u5-036",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-maneuver-speed"],
    prompt:
      "Why is it impossible to exceed the aircraft load limit at airspeeds below cornering velocity?",
    options: [
      "The engine cannot produce enough thrust",
      "The aircraft will stall before the limit load factor is reached",
      "The control surfaces lose authority",
      "Dynamic pressure is too low to bend the wing",
    ],
    answer: 1,
    explanation:
      "Below Va the accelerated stall line lies beneath the limit load line, so the wing runs out of C_L before it runs out of structure.",
    knowCold: "Below Va: you stall before you over-G.",
    difficulty: 3,
    officialStyle: true,
    source: PERF(["2.167"]),
  },
  {
    id: "gr-u5-037",
    type: "graphRead",
    unit: "u5",
    conceptIds: ["c-vn-diagram", "c-maneuver-speed"],
    prompt: "Tap the MANEUVER POINT on the V-n diagram.",
    diagram: { id: "vn-diagram", props: {} },
    targets: [
      { id: "maneuver", label: "Maneuver point", x: 196, y: 74, r: 24 },
      { id: "limit", label: "Positive limit load", x: 320, y: 74, r: 24 },
      { id: "stallline", label: "Accelerated stall line", x: 138, y: 118, r: 24 },
      { id: "vne", label: "Redline (Vne)", x: 418, y: 148, r: 24 },
    ],
    answer: "maneuver",
    explanation:
      "The maneuver point is the corner where the curving accelerated stall line meets the flat positive limit load line.",
    knowCold: "The corner of the envelope is the maneuver point.",
    difficulty: 3,
    source: PERF(["2.167"]),
  },
  {
    id: "q-u5-038",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-vn-diagram"],
    prompt: "The horizontal axis of the V-n diagram is",
    options: [
      "true airspeed",
      "indicated airspeed",
      "Mach number",
      "groundspeed",
    ],
    answer: 1,
    explanation:
      "Indicated airspeed, because that is what the pilot sees in the cockpit. The vertical axis is load factor.",
    knowCold: "V-n: indicated airspeed vs load factor.",
    difficulty: 2,
    source: PERF(["2.166"]),
  },
  {
    id: "cs-u5-039",
    type: "curveShift",
    unit: "u5",
    conceptIds: ["c-envelope-factors"],
    diagram: { id: "vn-diagram", props: { weight: 1 } },
    prompt: "The aircraft is loaded to a higher gross weight.",
    change: "Gross weight increases",
    curveLabel: "Accelerated stall lines",
    options: ["right", "left", "up", "down"],
    answer: "right",
    afterProps: { weight: 1.3 },
    explanation:
      "More weight raises stall speed, so the accelerated stall lines sweep RIGHT and maneuver speed increases. The limit load factor decreases because the same structural load is now a smaller multiple of a bigger weight.",
    knowCold: "Weight ↑ → stall lines sweep right, Va ↑, limit load factor ↓.",
    difficulty: 3,
    source: PERF(["2.167"]),
  },
  {
    id: "q-u5-040",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-envelope-factors"],
    prompt: "As altitude increases, the indicated redline airspeed must",
    options: [
      "increase",
      "decrease, to keep the aircraft below critical Mach",
      "remain constant",
      "be replaced by the limit load factor",
    ],
    answer: 1,
    explanation:
      "TAS rises for a given IAS and the speed of sound falls, so a fixed IAS eventually reaches critical Mach. The indicated redline must come down with altitude. Load limits and accelerated stall lines do not change.",
    knowCold: "Altitude ↑ → indicated redline ↓. Load limits unchanged.",
    difficulty: 3,
    source: PERF(["2.167"]),
  },
  {
    id: "q-u5-041",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-envelope-factors"],
    prompt:
      "With asymmetric loading or in turbulence, pilot-induced limit load should be reduced to approximately",
    options: [
      "one-half of the normal limit load",
      "two-thirds of the normal limit load",
      "the ultimate load factor",
      "1.5 times the normal limit load",
    ],
    answer: 1,
    explanation:
      "Asymmetric and gust loading are CUMULATIVE with pilot-induced loading, so the pilot's own share must be cut to about two-thirds to keep one wing from being overstressed.",
    knowCold: "Asymmetric or gust load → limit yourself to 2/3 of limit load.",
    difficulty: 3,
    source: PERF(["2.167", "2.168"]),
  },
  {
    id: "q-u5-042",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-load-definitions"],
    prompt:
      "The T-6B's limit load factor is",
    options: ["+4.7 / −1.0 G", "+7.0 / −3.5 G", "+6.0 / −3.0 G", "+3.5 / −7.0 G"],
    answer: 1,
    explanation:
      "+7.0 and −3.5 G are the normal limit loads. +4.7 / −1.0 G is the maximum during asymmetric loading.",
    knowCold: "T-6B: +7.0 / −3.5 G normal; +4.7 / −1.0 G asymmetric.",
    difficulty: 3,
    source: PERF(["2.164", "2.168"]),
  },
  {
    id: "q-u5-043",
    type: "mcq",
    unit: "u5",
    conceptIds: ["c-turn-rate-radius", "c-maneuver-speed"],
    prompt:
      "Maximum turn performance (fastest rate, tightest radius) is achieved",
    options: [
      "at maximum airspeed and maximum bank",
      "at the maneuver point on the V-n diagram",
      "at L/Dmax airspeed",
      "at maximum endurance airspeed",
    ],
    answer: 1,
    explanation:
      "The maneuver point is where CLmax AOA and the limit load factor meet — the slowest speed at which you can pull the maximum allowable G. Any deviation makes the turn worse or stalls the aircraft.",
    knowCold: "Best turn = maneuver point (assuming you are not thrust limited).",
    difficulty: 3,
    source: PERF(["2.167"]),
  },
];
