import type { Explainer, SourceReference } from "@/lib/types";

const L201: SourceReference = {
  document: "Principles of Gas Turbine/Reciprocating Operation",
  chapter: "Principles of Gas Turbine/Reciprocating Operation",
};
const L202: SourceReference = {
  document: "Gas Turbine/Reciprocating Engines",
  chapter: "Gas Turbine/Reciprocating Engines",
};
const L203: SourceReference = {
  document: "Compressor Stalls",
  chapter: "Compressor Stalls",
};
const NOTES: SourceReference = {
  document: "Engines Condensed Notes",
  chapter: "Engine Types",
};

/**
 * Engines visual explainers.
 *
 * Each is one diagram driven through a short sequence of prop changes, so the
 * student watches a single picture evolve rather than reading paragraphs. Every
 * caption is under about fourteen words by design.
 */
export const EXPLAINERS: Explainer[] = [
  {
    id: "ex-air-through-engine",
    title: "Air Through the Engine",
    promise: "Follow one parcel of air from inlet to exhaust and watch what happens to it.",
    unit: "e1",
    conceptIds: ["e-gas-generator", "e-station-changes"],
    lessonId: "el04-gas-generator-and-cycles",
    diagram: { id: "eng-cutaway" },
    frames: [
      { caption: "Air arrives cool, slow and at ambient pressure.", hold: 2600, props: { highlight: "inlet" } },
      { caption: "The inlet acts as a diffuser: pressure up, velocity down.", hold: 3000, props: { highlight: "inlet" } },
      { caption: "The compressor raises pressure, temperature and velocity together.", hold: 3200, props: { highlight: "compressor" } },
      { caption: "Fuel burns. Temperature and velocity climb; pressure dips slightly.", hold: 3200, props: { highlight: "burner" } },
      { caption: "The turbine takes 75% of the energy back to drive the compressor.", hold: 3200, props: { highlight: "turbine" } },
      { caption: "What is left accelerates out the exhaust as thrust.", hold: 3000, props: { highlight: "exhaust" } },
      { caption: "Five stations, one continuous flow. That is the whole engine.", hold: 2800, props: { highlight: "all" } },
    ],
    knowCold: "Inlet → compressor → combustion → turbine → exhaust.",
    source: L201,
  },
  {
    id: "ex-pressure-budget",
    title: "The Pressure Budget",
    promise: "Why static and dynamic pressure always trade against each other.",
    unit: "e1",
    conceptIds: ["e-static-pressure", "e-dynamic-pressure", "e-total-pressure"],
    lessonId: "el01-pressure-and-velocity",
    diagram: { id: "eng-pressure-split" },
    frames: [
      { caption: "Total pressure is a fixed budget with two line items.", hold: 2600, props: { dynamic: 0.35 } },
      { caption: "Static pressure: the energy of molecules at rest.", hold: 2600, props: { dynamic: 0.2 } },
      { caption: "Speed the air up and dynamic pressure grows.", hold: 2800, props: { dynamic: 0.55 } },
      { caption: "Static pressure must fall to pay for it.", hold: 2800, props: { dynamic: 0.72 } },
      { caption: "Inside the engine we just call them pressure and velocity.", hold: 3000, props: { dynamic: 0.35 } },
    ],
    knowCold: "Total = static + dynamic. One rises, the other falls.",
    source: L201,
  },
  {
    id: "ex-supersonic-flip",
    title: "Why Supersonic Flips the Rules",
    promise: "The same duct doing the opposite thing either side of Mach 1.",
    unit: "e1",
    conceptIds: ["e-supersonic-ducts", "e-compressibility"],
    lessonId: "el03-supersonic-reversal",
    diagram: { id: "eng-duct" },
    frames: [
      { caption: "Subsonic flow, convergent duct: velocity up, pressure down.", hold: 3000, props: { shape: "convergent", regime: "subsonic" } },
      { caption: "Now send supersonic flow through the identical duct.", hold: 2600, props: { shape: "convergent", regime: "supersonic" } },
      { caption: "It slows down and gains pressure — the exact opposite.", hold: 3200, props: { shape: "convergent", regime: "supersonic" } },
      { caption: "Divergent, subsonic: slows down. A classic diffuser.", hold: 2800, props: { shape: "divergent", regime: "subsonic" } },
      { caption: "Divergent, supersonic: speeds up. Now it is a nozzle.", hold: 3000, props: { shape: "divergent", regime: "supersonic" } },
      { caption: "Shape does not decide the outcome. Speed regime does.", hold: 3000, props: { shape: "divergent", regime: "supersonic" } },
    ],
    knowCold: "Above Mach 1, every duct does the opposite.",
    source: L201,
  },
  {
    id: "ex-density-thrust",
    title: "Everything Works Through Density",
    promise: "One mechanism connects temperature, pressure and altitude to thrust.",
    unit: "e2",
    conceptIds: ["e-density-thrust", "e-altitude-thrust", "e-temperature-thrust"],
    lessonId: "el06-density-and-thrust",
    diagram: { id: "eng-thrust-factor" },
    frames: [
      { caption: "Thrust is mass times acceleration. Density feeds the mass.", hold: 2800, props: { factor: "temperature" } },
      { caption: "Colder air is denser, so thrust rises as temperature falls.", hold: 3200, props: { factor: "temperature", marker: -20 } },
      { caption: "Climb, and pressure falls — density with it.", hold: 2800, props: { factor: "altitude", marker: 10 } },
      { caption: "Colder air up there helps, but pressure loss wins.", hold: 3000, props: { factor: "altitude", marker: 25 } },
      { caption: "Above 36,000 ft temperature stops helping entirely.", hold: 3200, props: { factor: "altitude", marker: 42 } },
      { caption: "So thrust falls away faster above that altitude.", hold: 2800, props: { factor: "altitude", marker: 48 } },
    ],
    knowCold: "Altitude ↑ → thrust ↓. Faster above 36,000 ft.",
    source: L201,
  },
  {
    id: "ex-compressor-does",
    title: "What the Compressor Actually Does",
    promise: "Rotor and stator, and why one stage is both.",
    unit: "e3",
    conceptIds: ["e-axial-compressor", "e-compressor-purpose"],
    lessonId: "el12-axial-compressor",
    diagram: { id: "eng-axial" },
    frames: [
      { caption: "Air enters straight and leaves straight. That is axial flow.", hold: 2600, props: { stages: 2 } },
      { caption: "The rotor spins, adding velocity and pressure.", hold: 2800, props: { stages: 2 } },
      { caption: "The stator slows it, converting speed into pressure.", hold: 3000, props: { stages: 3 } },
      { caption: "One rotor plus one stator is a single stage.", hold: 3000, props: { stages: 4 } },
      { caption: "Stack the stages and pressure multiplies each time.", hold: 3000, props: { stages: 6 } },
      { caption: "Fifteen to thirty to one, overall. Then the diffuser finishes it.", hold: 3200, props: { stages: 8 } },
    ],
    knowCold: "One rotor + one stator = one stage.",
    source: L202,
  },
  {
    id: "ex-why-not-forward",
    title: "Why Combustion Doesn't Blow Forward",
    promise: "What keeps a continuous fire pointing the right way.",
    unit: "e4",
    conceptIds: ["e-primary-secondary-air", "e-burner-purpose"],
    lessonId: "el14-burner-section",
    diagram: { id: "eng-burner-split" },
    frames: [
      { caption: "The diffuser has just made this the highest pressure in the engine.", hold: 3000 },
      { caption: "Only 25% of that air enters the liner to burn.", hold: 2800 },
      { caption: "The other 75% flows around the outside.", hold: 2800 },
      { caption: "That secondary air cools the walls and shapes the flame.", hold: 3000 },
      { caption: "High pressure upstream and expansion aft keep the gas moving rearward.", hold: 3200 },
      { caption: "Burning must finish before the gas reaches the turbine.", hold: 3000 },
    ],
    knowCold: "25% primary burns, 75% secondary cools and controls.",
    source: L202,
  },
  {
    id: "ex-turbine-vs-compressor",
    title: "Turbine versus Compressor",
    promise: "Two bladed sections doing opposite jobs on the same shaft.",
    unit: "e4",
    conceptIds: ["e-turbine-purpose", "e-compressor-purpose"],
    lessonId: "el16-turbine-section",
    diagram: { id: "eng-turbine-energy" },
    frames: [
      { caption: "The compressor spends energy to raise pressure.", hold: 2800 },
      { caption: "The turbine harvests energy from the expanding gas.", hold: 2800 },
      { caption: "75% of that harvest goes straight back to the compressor.", hold: 3200 },
      { caption: "Plus the accessory gear box, which runs the pumps.", hold: 2800 },
      { caption: "Only the remaining 25% is left to be thrust.", hold: 3000 },
      { caption: "Most of the fire simply keeps the engine turning.", hold: 3000 },
    ],
    knowCold: "Turbine: 75% back to the compressor, 25% to thrust.",
    source: L202,
  },
  {
    id: "ex-why-stalls-happen",
    title: "Why Compressor Stalls Happen",
    promise: "Watch blade angle of attack climb until the airflow breaks away.",
    unit: "e5",
    conceptIds: ["e-compressor-aoa", "e-compressor-relative-wind"],
    lessonId: "el18-blade-aoa",
    diagram: { id: "eng-blade-aoa" },
    frames: [
      { caption: "Inlet airflow comes down the axis. Blade speed comes from RPM.", hold: 3000, props: { inletFlow: 1, rpm: 1 } },
      { caption: "Together they make the relative wind the blade feels.", hold: 2800, props: { inletFlow: 1, rpm: 1 } },
      { caption: "Spin the compressor faster and the relative wind swings up.", hold: 3000, props: { inletFlow: 1, rpm: 1.3 } },
      { caption: "Angle of attack rises with it.", hold: 2600, props: { inletFlow: 1, rpm: 1.45 } },
      { caption: "Or starve the inlet airflow — same result.", hold: 3000, props: { inletFlow: 0.5, rpm: 1 } },
      { caption: "Past the limit, flow breaks away. The blade has stalled.", hold: 3200, props: { inletFlow: 0.35, rpm: 1.2 } },
    ],
    knowCold: "Less inlet airflow or more RPM raises blade AOA.",
    source: L203,
  },
  {
    id: "ex-indications-90s",
    title: "Engine Indications in 90 Seconds",
    promise: "The gauge pattern that says compressor stall.",
    unit: "e5",
    conceptIds: ["e-stall-indications"],
    lessonId: "el19-stall-indications",
    diagram: { id: "eng-stall-indications" },
    frames: [
      { caption: "Normal cruise: everything steady where you set it.", hold: 2800, props: { stalled: false } },
      { caption: "You have not touched the power control lever.", hold: 2400, props: { stalled: false } },
      { caption: "RPM begins to decay.", hold: 2600, props: { stalled: true } },
      { caption: "ITT climbs at the same time.", hold: 2800, props: { stalled: true } },
      { caption: "Torque and fuel flow fluctuate. Possibly loud bangs.", hold: 3000, props: { stalled: true } },
      { caption: "Two needles moving opposite ways: RPM down, ITT up.", hold: 3200, props: { stalled: true } },
    ],
    knowCold: "Stall: RPM down, ITT up.",
    source: L203,
  },
  {
    id: "ex-turbine-to-prop",
    title: "From Turbine to Propeller",
    promise: "How shaft power becomes 90% of a turboprop's thrust.",
    unit: "e6",
    conceptIds: ["e-turboprop", "e-rgb"],
    lessonId: "el23-turboprop-turboshaft",
    diagram: { id: "eng-turboprop-flow" },
    frames: [
      { caption: "Combustion releases heat energy into the gas stream.", hold: 2600, props: { highlight: "combustion" } },
      { caption: "The turbine converts it to shaft rotation.", hold: 2800, props: { highlight: "turbine" } },
      { caption: "That shaft spins fast, with relatively little torque.", hold: 2800, props: { highlight: "shaft" } },
      { caption: "The reduction gear box trades RPM for torque.", hold: 3000, props: { highlight: "rgb" } },
      { caption: "Without it, propeller tips would go supersonic and lose efficiency.", hold: 3200, props: { highlight: "rgb" } },
      { caption: "The propeller produces 90% of the thrust. Exhaust gives 10%.", hold: 3200, props: { highlight: "prop" } },
    ],
    knowCold: "Turbine → shaft → RGB → prop. 90% of thrust.",
    source: NOTES,
  },
  {
    id: "ex-engine-types",
    title: "Four Engines, Four Missions",
    promise: "Where each engine type's thrust comes from, side by side.",
    unit: "e6",
    conceptIds: ["e-turbojet", "e-turbofan", "e-turboprop", "e-turboshaft"],
    lessonId: "el22-turbojet-turbofan",
    diagram: { id: "eng-type-split" },
    frames: [
      { caption: "Turbojet: all thrust from accelerating air out the back.", hold: 3000, props: { type: "turbojet" } },
      { caption: "Fastest and lightest, but thirsty and slow off the runway.", hold: 3000, props: { type: "turbojet" } },
      { caption: "Turbofan: a fan adds 30–60% of the thrust.", hold: 3000, props: { type: "turbofan" } },
      { caption: "Turboprop: the propeller does 90% of the work.", hold: 3000, props: { type: "turboprop" } },
      { caption: "Lowest fuel consumption of any gas turbine, but capped near 400–450 knots.", hold: 3200, props: { type: "turboprop" } },
      { caption: "Turboshaft: everything through the rotor, nothing from exhaust.", hold: 3200, props: { type: "turboshaft" } },
    ],
    knowCold: "Turbojet 100 exhaust · Turboprop 90/10 · Turboshaft 100 rotor.",
    source: NOTES,
  },
  {
    id: "ex-start-sequence",
    title: "A Normal Start, Step by Step",
    promise: "Why fuel waits for 30% RPM.",
    unit: "e7",
    conceptIds: ["e-start-sequence", "e-abnormal-starts"],
    lessonId: "el28-starting-ignition",
    diagram: { id: "eng-start-sequence" },
    frames: [
      { caption: "The starter engages and begins turning the compressor.", hold: 2800, props: { stage: "starter" } },
      { caption: "Airflow builds as RPM rises.", hold: 2400, props: { stage: "starter" } },
      { caption: "At 30% RPM, fuel begins to flow.", hold: 3000, props: { stage: "fuel" } },
      { caption: "Ignition follows once airflow can support combustion.", hold: 3000, props: { stage: "ignition" } },
      { caption: "The engine reaches self-accelerating speed and the starter drops out.", hold: 3000, props: { stage: "idle" } },
      { caption: "Break that order and you get a hot, hung, false or wet start.", hold: 3200, props: { stage: "none" } },
    ],
    knowCold: "Starter → 30% RPM → fuel → ignition.",
    source: { document: "Engines Condensed Notes", chapter: "Starting and Ignition" },
  },
];

export const EXPLAINER_BY_ID: Record<string, Explainer> = Object.fromEntries(
  EXPLAINERS.map((e) => [e.id, e]),
);
