import type { Explainer, SourceReference } from "@/lib/types";

const L201: SourceReference = {
  document: "Principles of Gas Turbine/Reciprocating Operation",
  chapter: "Principles of Gas Turbine/Reciprocating Operation",
};
const L202: SourceReference = {
  document: "Gas Turbine/Reciprocating Engines",
  chapter: "Gas Turbine/Reciprocating Engines",
};
const NOTES = (chapter: string): SourceReference => ({
  document: "Engines Condensed Notes",
  chapter,
});

/**
 * Second explainer set. Eighteen Engines lessons had no walkthrough; these
 * cover the thirteen whose diagram can carry a frame sequence.
 */
export const EXPLAINERS_B: Explainer[] = [
  {
    id: "ex-duct-inversion",
    title: "The Same Duct, Twice",
    promise: "One shape, two speed regimes, opposite answers.",
    unit: "e1",
    conceptIds: ["e-subsonic-convergent", "e-subsonic-divergent", "e-nozzle", "e-diffuser"],
    lessonId: "el02-nozzles-and-diffusers",
    diagram: { id: "eng-duct" },
    frames: [
      { caption: "Subsonic, convergent: velocity up, pressure down. A nozzle.", hold: 3200, props: { shape: "convergent", regime: "subsonic" } },
      { caption: "Subsonic, divergent: velocity down, pressure up. A diffuser.", hold: 3200, props: { shape: "divergent", regime: "subsonic" } },
      { caption: "Now go supersonic. The same convergent duct…", hold: 2800, props: { shape: "convergent", regime: "supersonic" } },
      { caption: "…now slows the flow. It has become a diffuser.", hold: 3200, props: { shape: "convergent", regime: "supersonic" } },
      { caption: "And the divergent duct accelerates it. Shape alone tells you nothing.", hold: 3400, props: { shape: "divergent", regime: "supersonic" } },
    ],
    knowCold: "Shape plus regime. Neither one decides alone.",
    source: L201,
  },
  {
    id: "ex-thrust-factors",
    title: "Four Levers on Thrust",
    promise: "Temperature, altitude, RPM and airspeed — and which one has a break point.",
    unit: "e2",
    conceptIds: ["e-rpm-thrust", "e-airspeed-thrust", "e-ram-effect"],
    lessonId: "el07-rpm-airspeed-ram",
    diagram: { id: "eng-thrust-factor" },
    frames: [
      { caption: "Temperature up, density down, thrust down.", hold: 3000, props: { factor: "temperature" } },
      { caption: "Altitude costs pressure faster than the cold gains it back.", hold: 3200, props: { factor: "altitude" } },
      { caption: "Above 36,000 ft temperature stops falling — thrust drops away.", hold: 3400, props: { factor: "altitude" } },
      { caption: "RPM is strongly non-linear: the last few percent give the most.", hold: 3200, props: { factor: "rpm" } },
      { caption: "Airspeed loses thrust to acceleration, then ram effect wins it back.", hold: 3400, props: { factor: "airspeed" } },
    ],
    knowCold: "36,000 ft is the altitude break point. RPM is non-linear.",
    source: L201,
  },
  {
    id: "ex-stall-indications",
    title: "What a Stall Looks Like",
    promise: "The gauges during a compressor stall, and what each one is telling you.",
    unit: "e2",
    conceptIds: ["e-epr", "e-torquemeter", "e-tachometer"],
    lessonId: "el08-thrust-instruments",
    diagram: { id: "eng-stall-indications" },
    frames: [
      { caption: "Normal operation: everything sits where you set it.", hold: 2800, props: { stalled: false } },
      { caption: "A stall breaks the airflow over the compressor blades.", hold: 3000, props: { stalled: true } },
      { caption: "RPM falls off as the compressor stops doing work.", hold: 3000, props: { stalled: true } },
      { caption: "Exhaust gas temperature rises — the burn has nowhere to go.", hold: 3200, props: { stalled: true } },
      { caption: "The tachometer monitors. It never measured thrust in the first place.", hold: 3200, props: { stalled: false } },
    ],
    knowCold: "RPM down, EGT up.",
    source: L201,
  },
  {
    id: "ex-inlet-job",
    title: "The Inlet's One Job",
    promise: "Before anything else happens, the air has to be slowed down.",
    unit: "e3",
    conceptIds: ["e-inlet-purpose", "e-single-entrance", "e-divided-entrance"],
    lessonId: "el09-inlet-ducts",
    diagram: { id: "eng-cutaway" },
    frames: [
      { caption: "Air arrives fast. The compressor cannot use it that way.", hold: 3000, props: { highlight: "inlet" } },
      { caption: "The inlet acts as a diffuser: velocity down, pressure up.", hold: 3200, props: { highlight: "inlet" } },
      { caption: "Single entrance: maximum ram, minimum turbulence, but long ducting.", hold: 3200, props: { highlight: "inlet" } },
      { caption: "Divided entrance: shorter, less friction — but more turbulence.", hold: 3200, props: { highlight: "inlet" } },
      { caption: "Only then does the compressor get to work.", hold: 2800, props: { highlight: "compressor" } },
    ],
    knowCold: "The inlet is always a diffuser.",
    source: L202,
  },
  {
    id: "ex-supersonic-inlet",
    title: "Slowing Supersonic Air",
    promise: "Why a supersonic inlet needs two sections to do one job.",
    unit: "e3",
    conceptIds: ["e-inlet-geometry", "e-variable-geometry-inlet"],
    lessonId: "el10-inlet-geometry",
    diagram: { id: "eng-duct" },
    frames: [
      { caption: "Subsonic, the inlet is simply divergent.", hold: 3000, props: { shape: "divergent", regime: "subsonic" } },
      { caption: "Supersonic, a divergent duct would speed the air UP.", hold: 3200, props: { shape: "divergent", regime: "supersonic" } },
      { caption: "So the convergent section goes first, to slow it below sonic.", hold: 3400, props: { shape: "convergent", regime: "supersonic" } },
      { caption: "Then a divergent section finishes the job, subsonically.", hold: 3200, props: { shape: "divergent", regime: "subsonic" } },
      { caption: "A variable geometry inlet reshapes itself to stay a diffuser throughout.", hold: 3400, props: { shape: "divergent", regime: "subsonic" } },
    ],
    knowCold: "Supersonic inlet: convergent then divergent.",
    source: L202,
  },
  {
    id: "ex-centrifugal-path",
    title: "Around, Not Through",
    promise: "Follow air through an impeller, a diffuser and a manifold.",
    unit: "e3",
    conceptIds: ["e-centrifugal-compressor", "e-centrifugal-tradeoffs"],
    lessonId: "el11-centrifugal-compressor",
    diagram: { id: "eng-centrifugal" },
    frames: [
      { caption: "The impeller throws air outward, raising velocity.", hold: 3000, props: { labels: true } },
      { caption: "Its divergent blade shape raises pressure at the same time.", hold: 3200, props: { labels: true } },
      { caption: "The diffuser then converts that velocity into more pressure.", hold: 3200, props: { labels: true } },
      { caption: "The manifold routes it to the combustion chambers.", hold: 3000, props: { labels: true } },
      { caption: "High rise per stage — but the frontal area is the price.", hold: 3200, props: { labels: true } },
    ],
    knowCold: "Impeller, diffuser, manifold.",
    source: L202,
  },
  {
    id: "ex-station-by-station",
    title: "Station by Station",
    promise: "Pressure, temperature and velocity, one section at a time.",
    unit: "e3",
    conceptIds: ["e-guide-vanes", "e-compressor-diffuser", "e-station-changes"],
    lessonId: "el13-guide-vanes-diffuser",
    diagram: { id: "eng-station-changes" },
    frames: [
      { caption: "Inlet: pressure up, velocity down.", hold: 2800, props: { highlight: "inlet" } },
      { caption: "Compressor: pressure, temperature and velocity all up.", hold: 3000, props: { highlight: "compressor" } },
      { caption: "The diffuser is the point of HIGHEST pressure in the engine.", hold: 3400, props: { highlight: "compressor" } },
      { caption: "Burner: temperature and velocity up, pressure slightly down.", hold: 3200, props: { highlight: "burner" } },
      { caption: "Turbine and exhaust: velocity up, pressure down.", hold: 3000, props: { highlight: "turbine" } },
    ],
    knowCold: "Highest pressure is the diffuser, not the last compressor stage.",
    source: L202,
  },
  {
    id: "ex-three-chambers",
    title: "Three Ways to Burn",
    promise: "Can, annular and can-annular, and what each trades away.",
    unit: "e4",
    conceptIds: ["e-can-chamber", "e-annular-chamber", "e-can-annular-chamber"],
    lessonId: "el15-combustion-chambers",
    diagram: { id: "eng-cutaway" },
    frames: [
      { caption: "The burner has to mix, cool and add energy all at once.", hold: 3000, props: { highlight: "burner" } },
      { caption: "Can: strong, durable, easy to maintain — used with centrifugal engines.", hold: 3200, props: { highlight: "burner" } },
      { caption: "But a clogged can leaves a COLD SPOT on the turbine.", hold: 3200, props: { highlight: "turbine" } },
      { caption: "Can-annular burns in cans, mixes in an annulus — no cold spots.", hold: 3400, props: { highlight: "burner" } },
      { caption: "It is better in almost every way. Cost is what it trades.", hold: 3000, props: { highlight: "burner" } },
    ],
    knowCold: "Cans risk cold spots. Can-annular solves them, expensively.",
    source: L202,
  },
  {
    id: "ex-out-the-back",
    title: "Out the Back",
    promise: "What is left after the turbine, and what an afterburner does with it.",
    unit: "e4",
    conceptIds: ["e-exhaust-section", "e-exhaust-nozzles", "e-afterburner"],
    lessonId: "el17-exhaust-and-afterburner",
    diagram: { id: "eng-cutaway" },
    frames: [
      { caption: "The turbine has already taken 75% of the energy back.", hold: 3000, props: { highlight: "turbine" } },
      { caption: "What remains reaches the exhaust section.", hold: 2800, props: { highlight: "exhaust" } },
      { caption: "A convergent nozzle accelerates it toward the speed of sound.", hold: 3200, props: { highlight: "exhaust" } },
      { caption: "Supersonic aircraft add a divergent section to go beyond it.", hold: 3200, props: { highlight: "exhaust" } },
      { caption: "The afterburner relights secondary air: 50% more thrust, briefly.", hold: 3400, props: { highlight: "exhaust" } },
    ],
    knowCold: "Convergent reaches sonic. Divergent goes beyond.",
    source: L202,
  },
  {
    id: "ex-otto-versus-brayton",
    title: "Sequential or Continuous",
    promise: "The same four events, arranged two completely different ways.",
    unit: "e6",
    conceptIds: ["e-otto", "e-recip-propulsion"],
    lessonId: "el24-reciprocating",
    diagram: { id: "eng-cycles" },
    frames: [
      { caption: "Intake, compression, combustion, exhaust. Both cycles, same four.", hold: 3000, props: { cycle: "both" } },
      { caption: "Otto runs them SEQUENTIALLY, in one cylinder.", hold: 3200, props: { cycle: "otto" } },
      { caption: "Suck, squeeze, bang, blow — one at a time.", hold: 3000, props: { cycle: "otto" } },
      { caption: "Brayton runs all four SIMULTANEOUSLY, in separate sections.", hold: 3400, props: { cycle: "brayton" } },
      { caption: "That is why a gas turbine produces continuous thrust.", hold: 3000, props: { cycle: "both" } },
    ],
    knowCold: "Otto: sequential. Brayton: simultaneous and continuous.",
    source: L201,
  },
  {
    id: "ex-fuel-path",
    title: "Tank to Nozzle",
    promise: "Eight stops between the fuel tank and the flame.",
    unit: "e7",
    conceptIds: ["e-fuel-path", "e-boost-pump", "e-fcu", "e-fuel-manifolds"],
    lessonId: "el25-fuel-system",
    diagram: { id: "eng-fuel-system" },
    frames: [
      { caption: "The boost pump's critical job is preventing AERATION.", hold: 3200, props: { highlight: "boost" } },
      { caption: "Through the low pressure filter to the engine-driven pump.", hold: 3000, props: { highlight: "pump" } },
      { caption: "The Fuel Control Unit meters what the engine actually gets.", hold: 3200, props: { highlight: "fcu" } },
      { caption: "The P&D valve splits flow between two manifolds.", hold: 3000, props: { highlight: "pd" } },
      { caption: "Primary is small, so fuel atomizes well when flow is low.", hold: 3400, props: { highlight: "manifold" } },
    ],
    knowCold: "Tank, boost, filter, pump, FCU, P&D, manifolds, nozzles.",
    source: NOTES("Fuel System"),
  },
  {
    id: "ex-oil-three-ways",
    title: "Three Oil Subsystems",
    promise: "Supply, return and the one that uses bleed air.",
    unit: "e7",
    conceptIds: ["e-oil-subsystems", "e-oil-pump", "e-chip-detector"],
    lessonId: "el27-lubrication",
    diagram: { id: "eng-oil-system" },
    frames: [
      { caption: "Pressure supplies oil to the engine and accessory gear box.", hold: 3000, props: { subsystem: "pressure" } },
      { caption: "Scavenge removes it from bearings and drives, via the coolers.", hold: 3200, props: { subsystem: "scavenge" } },
      { caption: "Scavenge capacity is deliberately GREATER than pressure.", hold: 3400, props: { subsystem: "scavenge" } },
      { caption: "Otherwise oil pools in the sumps and backs up into the bearings.", hold: 3200, props: { subsystem: "scavenge" } },
      { caption: "Breather uses bleed air to pressurize the tank and engine.", hold: 3200, props: { subsystem: "breather" } },
    ],
    knowCold: "Pressure, scavenge, breather. Scavenge is the bigger one.",
    source: NOTES("Oil System"),
  },
  {
    id: "ex-pascal-tradeoff",
    title: "Force for Distance",
    promise: "Hydraulics multiply force, and charge you in travel.",
    unit: "e7",
    conceptIds: ["e-pascal", "e-hydraulic-pumps", "e-accumulator"],
    lessonId: "el29-hydraulics",
    diagram: { id: "eng-hydraulic" },
    frames: [
      { caption: "Pressure applied to a confined liquid is constant throughout.", hold: 3000, props: { ratio: 1 } },
      { caption: "A larger output piston sees the same pressure over more area.", hold: 3200, props: { ratio: 2 } },
      { caption: "So the output force is multiplied.", hold: 2800, props: { ratio: 3 } },
      { caption: "But displacement is divided by exactly the same factor.", hold: 3400, props: { ratio: 4 } },
      { caption: "Six times the force, one sixth the travel. Nothing is free.", hold: 3200, props: { ratio: 6 } },
    ],
    knowCold: "Force × n means displacement ÷ n.",
    source: NOTES("Hydraulics"),
  },
  {
    id: "ex-four-buses",
    title: "Four Buses",
    promise: "What gets power first when there is not enough to go around.",
    unit: "e7",
    conceptIds: ["e-buses", "e-power-sources", "e-ac-dc"],
    lessonId: "el30-electrical",
    diagram: { id: "eng-electrical" },
    frames: [
      { caption: "The essential bus supplies what flight safety requires.", hold: 3000, props: { highlight: "essential" } },
      { caption: "The primary bus supplies the equipment the mission needs.", hold: 3000, props: { highlight: "primary" } },
      { caption: "The monitor bus supplies convenience circuits — cabin lighting.", hold: 3200, props: { highlight: "monitor" } },
      { caption: "The starter bus supplies the starter circuit.", hold: 2800, props: { highlight: "starter" } },
      { caption: "Inverter goes DC to AC. Transformer rectifier goes AC to DC.", hold: 3400, props: { highlight: "none" } },
    ],
    knowCold: "Essential = safety, primary = mission, monitor = convenience.",
    source: NOTES("Electrical"),
  },
];
