import type { KnowColdCard, SourceReference } from "@/lib/types";

const L201 = (): SourceReference => ({
  document: "Principles of Gas Turbine/Reciprocating Operation",
  chapter: "Principles of Gas Turbine/Reciprocating Operation",
});
const L202 = (): SourceReference => ({
  document: "Gas Turbine/Reciprocating Engines",
  chapter: "Gas Turbine/Reciprocating Engines",
});
const L203 = (): SourceReference => ({
  document: "Compressor Stalls",
  chapter: "Compressor Stalls",
});
const NOTES = (chapter: string): SourceReference => ({
  document: "Engines Condensed Notes",
  chapter,
});

/**
 * Engines Know Cold — the compression layer for the night before the exam.
 *
 * Same discipline as the Aerodynamics deck: definitions exact, numbers exact,
 * sequences ordered, relationships directional, and the traps stated as traps.
 */
export const KNOW_COLD: KnowColdCard[] = [
  /* ---------------- Definitions ---------------- */
  {
    id: "ekc-001",
    category: "definition",
    term: "Static pressure",
    body: "The potential of fluid molecules at rest. Inside a gas generator it is simply called pressure.",
    unit: "e1",
    conceptIds: ["e-static-pressure"],
    source: L201(),
  },
  {
    id: "ekc-002",
    category: "definition",
    term: "Dynamic pressure",
    body: "The kinetic energy of fluid molecules in motion. Inside a gas generator it is simply called velocity.",
    unit: "e1",
    conceptIds: ["e-dynamic-pressure"],
    source: L201(),
  },
  {
    id: "ekc-003",
    category: "equation",
    term: "Total pressure",
    body: "The sum of static and dynamic pressure. As one falls the other rises.",
    formula: "P_{total} = P_{static} + P_{dynamic}",
    unit: "e1",
    conceptIds: ["e-total-pressure"],
    source: L201(),
  },
  {
    id: "ekc-004",
    category: "definition",
    term: "Nozzle",
    body: "Always increases velocity and decreases pressure. Convergent if subsonic, divergent if supersonic.",
    unit: "e1",
    conceptIds: ["e-nozzle"],
    source: L201(),
  },
  {
    id: "ekc-005",
    category: "definition",
    term: "Diffuser",
    body: "Always decreases velocity and increases pressure. Divergent if subsonic, convergent if supersonic.",
    unit: "e1",
    conceptIds: ["e-diffuser"],
    source: L201(),
  },
  {
    id: "ekc-006",
    category: "definition",
    term: "Gas generator",
    body: "Compressor, combustion chamber and turbine. The inlet and exhaust attach to it but are not part of it.",
    unit: "e1",
    conceptIds: ["e-gas-generator"],
    source: L201(),
  },
  {
    id: "ekc-007",
    category: "definition",
    term: "Gross thrust",
    body: "Measured on stationary engines or ground run-ups at standard day conditions. Ignores inlet velocity.",
    unit: "e2",
    conceptIds: ["e-gross-thrust"],
    source: L201(),
  },
  {
    id: "ekc-008",
    category: "definition",
    term: "Net thrust",
    body: "Corrects for inlet airflow velocity. The realistic measurement, and what 'thrust' usually means.",
    formula: "T_{net} = m \\times \\frac{V_{final} - V_{initial}}{t}",
    unit: "e2",
    conceptIds: ["e-net-thrust"],
    source: L201(),
  },
  {
    id: "ekc-009",
    category: "definition",
    term: "Creep",
    body: "Abnormal elongation of turbine blades due to overheating, which can permanently deform them.",
    unit: "e4",
    conceptIds: ["e-creep"],
    source: L202(),
  },
  {
    id: "ekc-010",
    category: "definition",
    term: "TSFC",
    body: "Thrust Specific Fuel Consumption: the fuel required to produce one pound of thrust.",
    unit: "e6",
    conceptIds: ["e-tsfc"],
    source: NOTES("Engine Types"),
  },
  {
    id: "ekc-011",
    category: "definition",
    term: "Bypass ratio",
    body: "The ratio of bypassed air to air passing through the gas generator in a turbofan.",
    unit: "e6",
    conceptIds: ["e-turbofan"],
    source: NOTES("Engine Types"),
  },
  {
    id: "ekc-012",
    category: "definition",
    term: "Viscosity",
    body: "The property of a fluid that resists force tending to make it flow. Inversely related to temperature.",
    unit: "e7",
    conceptIds: ["e-viscosity"],
    source: NOTES("Lubrication"),
  },
  {
    id: "ekc-013",
    category: "definition",
    term: "Squeeze film",
    body: "A thin lubricant film preventing metal-to-metal contact and dissipating heat. Needs proper viscosity to form.",
    unit: "e7",
    conceptIds: ["e-viscosity"],
    source: NOTES("Lubrication"),
  },
  {
    id: "ekc-014",
    category: "definition",
    term: "Flash point",
    body: "The lowest temperature at which a liquid gives off enough vapour to form an ignitable mixture.",
    unit: "e7",
    conceptIds: ["e-fuel-types"],
    source: NOTES("Fuel Systems"),
  },
  {
    id: "ekc-015",
    category: "equation",
    term: "Thrust",
    body: "Thrust is mass times acceleration. Every factor changes one or the other.",
    formula: "T = m \\times a",
    unit: "e2",
    conceptIds: ["e-thrust-equation"],
    source: L201(),
  },
  {
    id: "ekc-016",
    category: "equation",
    term: "Pascal's law",
    body: "Pressure applied to a liquid in a confined system is constant. Force multiplied means displacement divided.",
    formula: "P = \\frac{F}{A}",
    unit: "e7",
    conceptIds: ["e-pascal"],
    source: NOTES("Hydraulic Systems"),
  },

  /* ---------------- Sequences ---------------- */
  {
    id: "ekc-020",
    category: "sequence",
    term: "Gas path",
    body: "Inlet → Compressor → Combustion → Turbine → Exhaust.",
    unit: "e1",
    conceptIds: ["e-gas-generator", "e-station-changes"],
    source: L201(),
  },
  {
    id: "ekc-021",
    category: "sequence",
    term: "Brayton cycle",
    body: "Intake, compression, combustion, exhaust — all four SIMULTANEOUSLY. Gas turbine.",
    unit: "e1",
    conceptIds: ["e-brayton"],
    source: L201(),
  },
  {
    id: "ekc-022",
    category: "sequence",
    term: "Otto cycle",
    body: "Intake, compression, combustion, exhaust — SEQUENTIALLY. Suck, squeeze, bang, blow. Reciprocating.",
    unit: "e1",
    conceptIds: ["e-otto"],
    source: L201(),
  },
  {
    id: "ekc-023",
    category: "sequence",
    term: "Dual spool, forward to aft",
    body: "LPC → HPC → HPT → LPT. LP turbine drives LP compressor; HP turbine drives HP compressor.",
    unit: "e3",
    conceptIds: ["e-spools"],
    source: L202(),
  },
  {
    id: "ekc-024",
    category: "sequence",
    term: "Centrifugal compressor",
    body: "Impeller → diffuser → manifold.",
    unit: "e3",
    conceptIds: ["e-centrifugal-compressor"],
    source: L202(),
  },
  {
    id: "ekc-025",
    category: "sequence",
    term: "Compressor stall recovery",
    body: "Lower the nose to reduce inlet AOA → slowly retard the PCL → bleed valves increase airflow → slowly advance the PCL.",
    unit: "e5",
    conceptIds: ["e-stall-recovery"],
    source: L203(),
  },
  {
    id: "ekc-026",
    category: "sequence",
    term: "Fuel path",
    body: "Tank → boost pump → LP filter → engine-driven pump → FCU → P&D valve → manifolds → nozzles.",
    unit: "e7",
    conceptIds: ["e-fuel-path"],
    source: NOTES("Fuel Systems"),
  },
  {
    id: "ekc-027",
    category: "sequence",
    term: "Normal start",
    body: "Starter engages → fuel flows after 30% RPM → ignition when airflow supports combustion → self-accelerating speed.",
    unit: "e7",
    conceptIds: ["e-start-sequence"],
    source: NOTES("Starting and Ignition"),
  },
  {
    id: "ekc-028",
    category: "sequence",
    term: "Turboprop power path",
    body: "Combustion → turbine → shaft → reduction gear box → propeller.",
    unit: "e6",
    conceptIds: ["e-turboprop", "e-rgb"],
    source: NOTES("Engine Types"),
  },
  {
    id: "ekc-029",
    category: "sequence",
    term: "Oil subsystems",
    body: "Pressure supplies the engine and AGB · Scavenge returns and cools · Breather pressurizes with bleed air.",
    unit: "e7",
    conceptIds: ["e-oil-subsystems"],
    source: NOTES("Lubrication"),
  },

  /* ---------------- Numbers ---------------- */
  {
    id: "ekc-040",
    category: "number",
    term: "Burner air split",
    body: "25% primary air burns. 75% secondary air cools the walls and turbine, controls the flame, feeds the afterburner.",
    unit: "e4",
    conceptIds: ["e-primary-secondary-air"],
    source: L202(),
  },
  {
    id: "ekc-041",
    category: "number",
    term: "Turbine energy split",
    body: "75% of heat energy drives the compressor and accessory gear box. 25% is left for thrust.",
    unit: "e4",
    conceptIds: ["e-turbine-purpose"],
    source: L202(),
  },
  {
    id: "ekc-042",
    category: "number",
    term: "36,000 feet",
    body: "Above it temperature stabilises and stops offsetting pressure, so thrust falls off more rapidly in a climb.",
    unit: "e2",
    conceptIds: ["e-altitude-thrust"],
    source: L201(),
  },
  {
    id: "ekc-043",
    category: "number",
    term: "Standard day",
    body: "29.92 inHg and 15 °C. The basis for gross thrust.",
    unit: "e2",
    conceptIds: ["e-gross-thrust"],
    source: L201(),
  },
  {
    id: "ekc-044",
    category: "number",
    term: "Axial compression ratio",
    body: "15:1 to 30:1 overall, achieved by stacking stages.",
    unit: "e3",
    conceptIds: ["e-axial-compressor"],
    source: L202(),
  },
  {
    id: "ekc-045",
    category: "number",
    term: "Afterburner gain",
    body: "Increases maximum thrust available by 50% or more, for short periods.",
    unit: "e4",
    conceptIds: ["e-afterburner"],
    source: L202(),
  },
  {
    id: "ekc-046",
    category: "number",
    term: "Turbofan thrust split",
    body: "40–70% from the gas generator, 30–60% from the ducted fan.",
    unit: "e6",
    conceptIds: ["e-turbofan"],
    source: NOTES("Engine Types"),
  },
  {
    id: "ekc-047",
    category: "number",
    term: "Turboprop thrust split",
    body: "90% from the propeller, 10% from exhaust gases.",
    unit: "e6",
    conceptIds: ["e-turboprop"],
    source: NOTES("Engine Types"),
  },
  {
    id: "ekc-048",
    category: "number",
    term: "Turboprop speed limit",
    body: "Approximately 400–450 knots.",
    unit: "e6",
    conceptIds: ["e-turboprop"],
    source: NOTES("Engine Types"),
  },
  {
    id: "ekc-049",
    category: "number",
    term: "Fuel flow begins",
    body: "After engine RPM reaches 30% during a normal start.",
    unit: "e7",
    conceptIds: ["e-start-sequence"],
    source: NOTES("Starting and Ignition"),
  },
  {
    id: "ekc-050",
    category: "number",
    term: "Fuel flash points",
    body: "JP-4: −35 °F · JP-5: 140 °F · JP-8: 100 °F · Avgas: −45 °F.",
    unit: "e7",
    conceptIds: ["e-fuel-types"],
    source: NOTES("Fuel Systems"),
  },
  {
    id: "ekc-051",
    category: "number",
    term: "Military thrust duration",
    body: "Maximum turbine temperature for a limited time, roughly 30 minutes.",
    unit: "e7",
    conceptIds: ["e-thrust-ratings"],
    source: NOTES("Fuel Systems"),
  },
  {
    id: "ekc-052",
    category: "aircraft",
    term: "T-6 compressor",
    body: "Four-stage axial compressor plus one centrifugal impeller — an axial-centrifugal arrangement.",
    unit: "e3",
    conceptIds: ["e-axial-centrifugal"],
    source: L202(),
  },

  /* ---------------- Relationships ---------------- */
  {
    id: "ekc-060",
    category: "relationship",
    term: "Density and thrust",
    body: "Density ↑ → mass ↑ → thrust ↑. Every atmospheric factor works through density.",
    unit: "e2",
    conceptIds: ["e-density-thrust"],
    source: L201(),
  },
  {
    id: "ekc-061",
    category: "relationship",
    term: "Temperature and thrust",
    body: "Temperature ↓ → density ↑ → thrust ↑.",
    unit: "e2",
    conceptIds: ["e-temperature-thrust"],
    source: L201(),
  },
  {
    id: "ekc-062",
    category: "relationship",
    term: "Altitude and thrust",
    body: "Altitude ↑ → thrust ↓, because the pressure drop outweighs the temperature drop.",
    unit: "e2",
    conceptIds: ["e-altitude-thrust"],
    source: L201(),
  },
  {
    id: "ekc-063",
    category: "relationship",
    term: "RPM and thrust",
    body: "RPM ↑ → thrust ↑, non-linearly. Little effect low down, large effect near maximum.",
    unit: "e2",
    conceptIds: ["e-rpm-thrust"],
    source: L201(),
  },
  {
    id: "ekc-064",
    category: "relationship",
    term: "Airspeed and ram effect",
    body: "Airspeed ↑ → thrust ↓ on its own. Ram effect adds mass, holding thrust steady subsonic and raising it supersonic.",
    unit: "e2",
    conceptIds: ["e-airspeed-thrust", "e-ram-effect"],
    source: L201(),
  },
  {
    id: "ekc-065",
    category: "relationship",
    term: "Blade AOA",
    body: "Inlet airflow ↓ OR compressor RPM ↑ → relative wind swings → blade AOA ↑ → stall risk ↑.",
    unit: "e5",
    conceptIds: ["e-compressor-aoa"],
    source: L203(),
  },
  {
    id: "ekc-066",
    category: "relationship",
    term: "Bypass ratio and TSFC",
    body: "Bypass ratio ↑ → TSFC ↓ → more fuel efficient.",
    unit: "e6",
    conceptIds: ["e-turbofan", "e-tsfc"],
    source: NOTES("Engine Types"),
  },
  {
    id: "ekc-067",
    category: "relationship",
    term: "Volatility and flash point",
    body: "Volatility ↑ → flash point ↓. They are inversely related.",
    unit: "e7",
    conceptIds: ["e-fuel-types"],
    source: NOTES("Fuel Systems"),
  },
  {
    id: "ekc-068",
    category: "relationship",
    term: "Station changes",
    body: "Inlet P↑ V↓ · Compressor P↑ T↑ V↑ · Combustion T↑ V↑ P slightly↓ · Turbine V↑ P↓ · Exhaust V↑ P↓.",
    unit: "e1",
    conceptIds: ["e-station-changes"],
    source: L201(),
  },

  /* ---------------- Traps ---------------- */
  {
    id: "ekc-080",
    category: "trap",
    term: "Supersonic reverses",
    body: "Shape does not decide the outcome — the speed regime does. Supersonic convergent SLOWS the flow.",
    unit: "e1",
    conceptIds: ["e-supersonic-ducts"],
    source: L201(),
  },
  {
    id: "ekc-081",
    category: "trap",
    term: "Combustion pressure",
    body: "Pressure DROPS slightly across the burner. The heat goes into temperature and velocity, not pressure.",
    unit: "e1",
    conceptIds: ["e-station-changes"],
    source: L201(),
  },
  {
    id: "ekc-082",
    category: "trap",
    term: "Two 25/75 splits",
    body: "The burner splits AIRFLOW (25% primary). The turbine splits ENERGY (75% to the compressor). Different quantities.",
    unit: "e4",
    conceptIds: ["e-primary-secondary-air", "e-turbine-purpose"],
    source: L202(),
  },
  {
    id: "ekc-083",
    category: "trap",
    term: "Highest pressure point",
    body: "The DIFFUSER, not the last compressor stage and definitely not the combustion chamber.",
    unit: "e3",
    conceptIds: ["e-compressor-diffuser"],
    source: L202(),
  },
  {
    id: "ekc-084",
    category: "trap",
    term: "Avoidance versus prevention",
    body: "Avoidance is what the PILOT does. Prevention is the four ENGINE DESIGN features. The exam mixes the lists.",
    unit: "e5",
    conceptIds: ["e-stall-avoidance", "e-stall-prevention"],
    source: L203(),
  },
  {
    id: "ekc-085",
    category: "trap",
    term: "Hung versus false start",
    body: "Both stabilise RPM below normal. Hung has temperature RISING; false has temperature WITHIN limits.",
    unit: "e7",
    conceptIds: ["e-abnormal-starts"],
    source: NOTES("Starting and Ignition"),
  },
  {
    id: "ekc-086",
    category: "trap",
    term: "Inverter versus transformer rectifier",
    body: "Inverter: DC → AC. Transformer rectifier: AC → DC. Direct opposites, routinely swapped.",
    unit: "e7",
    conceptIds: ["e-power-sources"],
    source: NOTES("Electrical Systems"),
  },
  {
    id: "ekc-087",
    category: "trap",
    term: "Compressor raises both",
    body: "Pressure AND velocity increase across the compressor. It is not a closed system — the turbine feeds energy in.",
    unit: "e3",
    conceptIds: ["e-compressor-purpose"],
    source: L202(),
  },
  {
    id: "ekc-088",
    category: "trap",
    term: "Tachometer measures nothing",
    body: "It monitors percent RPM. It does not measure thrust. EPR and the torquemeter do that.",
    unit: "e2",
    conceptIds: ["e-tachometer"],
    source: L201(),
  },
  {
    id: "ekc-089",
    category: "trap",
    term: "Turboshaft exhaust",
    body: "A turboshaft gets NO propulsion from exhaust. A turboprop still gets 10%.",
    unit: "e6",
    conceptIds: ["e-turboshaft"],
    source: NOTES("Engine Types"),
  },
  {
    id: "ekc-090",
    category: "trap",
    term: "Recovery order",
    body: "Lower the nose FIRST. Only then touch the PCL, and move it slowly.",
    unit: "e5",
    conceptIds: ["e-stall-recovery"],
    source: L203(),
  },
  {
    id: "ekc-091",
    category: "trap",
    term: "Most common stall cause",
    body: "Airflow distortion, not mechanical malfunction.",
    unit: "e5",
    conceptIds: ["e-airflow-distortion"],
    source: L203(),
  },
  {
    id: "ekc-092",
    category: "trap",
    term: "Scavenge is bigger",
    body: "The scavenge pump has GREATER capacity than the pressure pump, to prevent oil pooling in sump cavities.",
    unit: "e7",
    conceptIds: ["e-oil-pump"],
    source: NOTES("Lubrication"),
  },
];

export const KNOW_COLD_BY_ID: Record<string, KnowColdCard> = Object.fromEntries(
  KNOW_COLD.map((c) => [c.id, c]),
);
