import type { Lesson, SourceReference } from "@/lib/types";

const NOTES = (chapter: string): SourceReference => ({
  document: "Weather Condensed Notes",
  chapter,
});

const MECH = NOTES("WX 2: Mechanics");
const HAZ = NOTES("WX 3: Hazards");
const PLAN = NOTES("WX 4: Planning and Resources");

/** Weather lessons, units w6–w10: fronts, hazards and products. */
export const LESSONS_B: Lesson[] = [
  /* ================= w6 · fronts ================= */
  {
    id: "wl13-cold-and-warm-fronts",
    unit: "w6",
    index: 13,
    title: "Cold and Warm Fronts",
    subtitle: "The slope decides everything",
    estimatedMinutes: 7,
    mapIcon: "wx-front",
    enablingObjectives: [],
    conceptIds: ["wx-cold-front", "wx-warm-front"],
    masteryThreshold: 0.85,
    screens: [
      {
        kind: "hook",
        headline: "Two air masses, and the only real question is which one is moving",
        line: "Everything else — the cloud, the rain, the ride — follows from how steeply the warm air gets lifted.",
      },
      {
        kind: "model",
        headline: "A cold front, in cross-section",
        diagram: { id: "wx-front", props: { kind: "cold" } },
        bullets: [
          "Cooler, denser air undercuts the warm air and forces it up",
          "Steep lifting → unstable conditions",
          "Cumuliform cloud, showery precipitation",
        ],
      },
      {
        kind: "model",
        headline: "A warm front, in cross-section",
        diagram: { id: "wx-front", props: { kind: "warm" } },
        bullets: [
          "Warmer air overtakes cooler air, usually more slowly, and rides up over it",
          "Shallow lifting → stable conditions prior to passage",
          "Stratiform cloud, continuous precipitation, little to no turbulence",
        ],
      },
      {
        kind: "compare",
        headline: "Side by side",
        line: "Read this table as one causal chain running left to right.",
        columns: ["Cold front", "Warm front"],
        rows: [
          { label: "Which air advances", a: "The cold air", b: "The warm air" },
          { label: "Speed", a: "Faster", b: "Usually slower" },
          { label: "Slope of lifting", a: "Steep", b: "Shallow" },
          { label: "Stability", a: "Unstable", b: "Stable prior to passage" },
          { label: "Cloud", a: "Cumuliform", b: "Stratiform" },
          { label: "Precipitation", a: "Showery", b: "Continuous" },
          { label: "Turbulence", a: "Frontal turbulence", b: "Little to none" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Cold front: unstable, cumuliform, showery",
          "Warm front: stable, stratiform, continuous, smooth",
          "Warm fronts are the SLOW ones",
        ],
      },
      { kind: "question", questionId: "wq-w6-001" },
      { kind: "question", questionId: "wq-w6-002" },
      { kind: "question", questionId: "wq-w6-003" },
      { kind: "question", questionId: "wbf-w6-011" },
    ],
    questionIds: ["wq-w6-001", "wq-w6-002", "wq-w6-003", "wbf-w6-011"],
    memorize: [
      "Cold: unstable, cumuliform, showery",
      "Warm: stable, stratiform, continuous",
    ],
    sourceReferences: [MECH],
    explainerIds: ["wx-x-cold-front", "wx-x-warm-front"],
    labIds: ["wxlab-front"],
  },
  {
    id: "wl14-stationary-and-occluded",
    unit: "w6",
    index: 14,
    title: "Stationary and Occluded Fronts",
    subtitle: "Stalemate, and the one that lifts the warm air clear",
    estimatedMinutes: 6,
    mapIcon: "wx-occluded",
    enablingObjectives: [],
    conceptIds: ["wx-stationary-front", "wx-occluded-front", "wx-frontal-discontinuities"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "What happens when neither air mass wins — and when one wins completely",
        line: "A stationary front is a stalemate. An occlusion is a cold front catching a warm one and lifting it off the ground entirely.",
      },
      {
        kind: "model",
        headline: "Stationary",
        diagram: { id: "wx-front", props: { kind: "stationary" } },
        line: "Neither is powerful enough to move the other. Weather resembles a warm front, but often less intense.",
      },
      {
        kind: "model",
        headline: "Occluded",
        diagram: { id: "wx-front", props: { kind: "occluded" } },
        bullets: [
          "A cold front overtakes a warm front",
          "The wind shifts 180°, from SE to NW",
          "Weather from BOTH fronts, potentially over a very widespread area",
          "Named cold or warm occlusion by which front touches the ground",
        ],
      },
      {
        kind: "model",
        headline: "And on the chart",
        diagram: { id: "wx-front-symbols", props: { kind: "none" } },
        bullets: [
          "Stationary alternates the symbols in OPPOSITE directions",
          "Occluded puts them on the SAME side, in purple",
        ],
      },
      {
        kind: "rule",
        headline: "What makes something a front at all",
        rule:
          "A front is a discontinuity between contrasting air masses. The four frontal discontinuities are Temperature, Dew point, Wind and Pressure.",
        appliesWhen: ["Any front, of any of the four types"],
        watchFor: "Dew point, not humidity, and pressure — not precipitation.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Stationary: neither wins, symbols oppose, warm-front-like weather",
          "Occluded: cold overtakes warm, purple, 180° wind shift SE to NW",
          "Discontinuities: Temperature, Dew point, Wind, Pressure",
        ],
      },
      { kind: "question", questionId: "wq-w6-004" },
      { kind: "question", questionId: "wq-w6-006" },
      { kind: "question", questionId: "wq-w6-008" },
      { kind: "question", questionId: "wtap-w6-010" },
    ],
    questionIds: [
      "wq-w6-004", "wq-w6-005", "wq-w6-006", "wq-w6-007", "wq-w6-008",
      "wq-w6-009", "wtap-w6-010",
    ],
    memorize: ["Occluded: purple, 180° SE to NW", "TDWP"],
    sourceReferences: [MECH],
    explainerIds: ["wx-x-occlusion"],
  },

  /* ================= w7 · turbulence and wind shear ================= */
  {
    id: "wl15-turbulence-classification",
    unit: "w7",
    index: 15,
    title: "Classifying Turbulence",
    subtitle: "How bad, and how often",
    estimatedMinutes: 5,
    mapIcon: "wx-turbulence",
    enablingObjectives: [],
    conceptIds: [
      "wx-turbulence",
      "wx-turbulence-intensity",
      "wx-turbulence-duration",
      "wx-clear-air-turbulence",
    ],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Intensity and duration are two different scales",
        line: "Continuous light turbulence is an ordinary report. Occasional extreme is an emergency.",
      },
      {
        kind: "compare",
        headline: "The two scales",
        line: "A PIREP carries one from each column.",
        columns: ["Intensity", "Duration"],
        rows: [
          { label: "First", a: "Light", b: "Occasional — less than ⅓ of the time" },
          { label: "Second", a: "Moderate", b: "Intermittent — ⅓ to ⅔" },
          { label: "Third", a: "Severe", b: "Continuous — more than ⅔" },
          { label: "Fourth", a: "Extreme — declare an emergency, exit ASAP", b: "" },
        ],
      },
      {
        kind: "chain",
        headline: "Where it hurts",
        nodes: [
          { label: "Irregular or disturbed flow", trend: "none" },
          { label: "Gusts and eddies", trend: "up" },
          { label: "Most hazardous at LOW altitude", trend: "down", emphasis: true },
        ],
        footnote: "Low means no height and no airspeed in reserve to absorb an upset.",
      },
      {
        kind: "rule",
        headline: "Clear air turbulence",
        rule:
          "Turbulence occurring in the absence of, or outside of, clouds is referred to as clear-air turbulence. Any of the four causative types may occur without the visual warning associated with clouds.",
        appliesWhen: ["Anywhere the cause is present but the cloud is not"],
        watchFor:
          "CAT is not a fifth cause. It describes where the turbulence happens, not what produced it — and it is why forecasts and PIREPs matter more than looking out of the window.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Light, moderate, severe, extreme",
          "CAT is turbulence with no cloud to warn you",
          "Extreme → declare an emergency and exit ASAP",
          "Occasional < ⅓ · Intermittent ⅓–⅔ · Continuous > ⅔",
          "Most hazardous at low altitude",
        ],
      },
      { kind: "question", questionId: "wq-w7-001" },
      { kind: "question", questionId: "wq-w7-004" },
      { kind: "question", questionId: "wq-w7-005" },
      { kind: "question", questionId: "wq-wg-023" },
    ],
    questionIds: [
      "wq-w7-001", "wq-w7-002", "wq-w7-003", "wq-w7-004", "wq-w7-005", "wq-wg-023",
    ],
    memorize: ["Occasional ⅓, intermittent ⅔, continuous beyond"],
    sourceReferences: [HAZ],
  },
  {
    id: "wl16-four-causes",
    unit: "w7",
    index: 16,
    title: "The Four Causes",
    subtitle: "Wind shear, thermal, frontal, mechanical",
    estimatedMinutes: 7,
    mapIcon: "wx-causes",
    enablingObjectives: [],
    conceptIds: [
      "wx-turbulence-causes",
      "wx-wind-shear",
      "wx-shear-sources",
      "wx-thermal-turbulence",
      "wx-frontal-turbulence",
      "wx-mechanical-turbulence",
    ],
    masteryThreshold: 0.85,
    screens: [
      {
        kind: "hook",
        headline: "Four causes, and one of them does not exist where you would expect",
        line: "There is no such thing as warm frontal turbulence. The notes say so outright.",
      },
      {
        kind: "model",
        headline: "All four",
        diagram: { id: "wx-turbulence-causes", props: { cause: "none" } },
        bullets: [
          "WIND SHEAR: a sudden, drastic change in wind speed and/or direction — anywhere",
          "THERMAL: heating from below; the drier the surface, the stronger",
          "FRONTAL: cold front lifting only, and worse in a fast cold front",
          "MECHANICAL: obstructions and terrain, usually below 1,000 ft AGL",
        ],
      },
      {
        kind: "compare",
        headline: "High shear versus low shear",
        line: "Same phenomenon, very different risk.",
        columns: ["High level", "Low level (LLWS)"],
        rows: [
          { label: "Associated with", a: "Clear air turbulence, the jet stream", b: "Local phenomena such as a temperature inversion" },
          { label: "When", a: "Any time", b: "Near the surface on cool, clear nights" },
          { label: "Why it matters", a: "Uncomfortable, hard to forecast", b: "MOST DANGEROUS — risk of stall at low altitude" },
        ],
      },
      {
        kind: "rule",
        headline: "No warm frontal turbulence",
        rule:
          "Frontal turbulence is the result of frontal lifting associated with the passage of a COLD front. There is little or no lifting with warm fronts, so there is no warm frontal turbulence.",
        appliesWhen: ["Cold fronts, and more prominently in fast ones"],
        watchFor:
          "Not 'less turbulence at a warm front' — none. Warm fronts are the smooth ones for exactly this reason.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Wind shear · Thermal · Frontal · Mechanical",
          "LLWS is the most dangerous — stall risk at low altitude",
          "Drier surface → stronger thermal turbulence",
          "Mechanical: usually below 1,000 ft AGL",
          "No warm frontal turbulence",
        ],
      },
      { kind: "question", questionId: "wq-w7-006" },
      { kind: "question", questionId: "wq-w7-007" },
      { kind: "question", questionId: "wq-w7-010" },
      { kind: "question", questionId: "wq-w7-011" },
      { kind: "question", questionId: "wq-w7-013" },
    ],
    questionIds: [
      "wq-w7-006", "wq-w7-007", "wq-w7-008", "wq-w7-009", "wq-w7-010",
      "wq-w7-011", "wq-w7-012", "wq-w7-013", "wq-w7-014",
    ],
    memorize: ["Wind shear, thermal, frontal, mechanical", "No warm frontal turbulence"],
    sourceReferences: [HAZ],
    explainerIds: ["wx-x-turbulence"],
    labIds: ["wxlab-turbulence"],
  },
  {
    id: "wl17-flying-turbulence",
    unit: "w7",
    index: 17,
    title: "Flying Through It",
    subtitle: "Fly attitude, not needles",
    estimatedMinutes: 4,
    mapIcon: "wx-technique",
    enablingObjectives: [],
    conceptIds: ["wx-turbulence-technique"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "The technique is mostly a list of things not to chase",
        line: "Airspeed will wander. Altitude will wander. Both are fine. Attitude is what you hold.",
      },
      {
        kind: "rule",
        headline: "Turbulence penetration",
        rule:
          "Maintain the power setting consistent with the aircraft's recommended turbulence penetration airspeed, trim for level flight, do not chase airspeed deviations with power corrections, allow altitude to vary and do not chase the altimeter, and maintain pitch and bank by reference to the attitude indicator with a VFR scan when conditions permit.",
        appliesWhen: ["Any turbulence penetration"],
        watchFor:
          "Chasing the needles is what turns turbulence into an upset. Keep a level attitude and let the rest move.",
      },
      {
        kind: "chain",
        headline: "In order",
        nodes: [
          { label: "Set turbulence penetration power", trend: "none" },
          { label: "Trim for level flight", trend: "none" },
          { label: "Stop chasing airspeed and altitude", trend: "none" },
          { label: "Fly the attitude indicator", trend: "up", emphasis: true },
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Do not chase airspeed with power",
          "Do not chase the altimeter",
          "Pitch and bank on the attitude indicator",
          "Keep a level attitude",
        ],
      },
      { kind: "question", questionId: "wq-w7-015" },
      { kind: "question", questionId: "wq-w7-016" },
      { kind: "question", questionId: "wq-w7-017" },
    ],
    questionIds: ["wq-w7-015", "wq-w7-016", "wq-w7-017"],
    memorize: ["Fly attitude. Let airspeed and altitude wander."],
    sourceReferences: [HAZ],
  },

  /* ================= w8 · icing ================= */
  {
    id: "wl18-what-icing-needs",
    unit: "w8",
    index: 18,
    title: "What Icing Needs",
    subtitle: "Three conditions, all required",
    estimatedMinutes: 5,
    mapIcon: "wx-icing",
    enablingObjectives: [],
    conceptIds: ["wx-icing-requirements", "wx-structural-icing"],
    masteryThreshold: 0.85,
    screens: [
      {
        kind: "hook",
        headline: "Three conditions. Remove any one and ice cannot form.",
        line: "Which is also the whole logic behind every escape option later in this unit.",
      },
      {
        kind: "model",
        headline: "The intersection",
        diagram: { id: "wx-icing-requirements", props: { missing: "none" } },
        bullets: [
          "Visible moisture",
          "Free air temperature below freezing",
          "Aircraft surface temperature below freezing",
        ],
      },
      {
        kind: "model",
        headline: "Take one away",
        diagram: { id: "wx-icing-requirements", props: { missing: "moisture" } },
        line: "Clear air at −15 °C is cold enough, but there is nothing to freeze. No visible moisture, no structural ice.",
      },
      {
        kind: "rule",
        headline: "The real hazard",
        rule:
          "The most hazardous aspect of structural icing is the aerodynamic effect on the airfoil.",
        appliesWhen: ["Any accumulation on a lifting surface"],
        watchFor:
          "Not the weight. Structural concerns — flight controls, vibration, pitot blockage, panels freezing over — are real, but secondary to what the ice does to the shape of the wing.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Visible moisture + FAT below freezing + surface below freezing",
          "All three, together",
          "Most hazardous aspect: the AERODYNAMIC effect on the airfoil",
        ],
      },
      { kind: "question", questionId: "wq-w8-001" },
      { kind: "question", questionId: "wq-w8-002" },
      { kind: "question", questionId: "wq-w8-003" },
    ],
    questionIds: ["wq-w8-001", "wq-w8-002", "wq-w8-003"],
    memorize: ["Moisture, cold air, cold surface. All three."],
    sourceReferences: [HAZ],
    explainerIds: ["wx-x-icing"],
    labIds: ["wxlab-icing"],
  },
  {
    id: "wl19-ice-types",
    unit: "w8",
    index: 19,
    title: "Four Types of Ice",
    subtitle: "Read the temperature, name the ice",
    estimatedMinutes: 7,
    mapIcon: "wx-icetype",
    enablingObjectives: [],
    conceptIds: [
      "wx-clear-ice",
      "wx-rime-ice",
      "wx-mixed-ice",
      "wx-frost",
      "wx-engine-icing",
      "wx-frontal-icing",
      "wx-pirep-icing",
    ],
    masteryThreshold: 0.85,
    screens: [
      {
        kind: "hook",
        headline: "The temperature tells you which ice you are about to get",
        line: "And the type tells you how bad it will be and how hard it will be to shed.",
      },
      {
        kind: "model",
        headline: "The bands",
        diagram: { id: "wx-icing-ladder", props: { temp: -5 } },
        bullets: [
          "CLEAR: 0 to −10 °C, unstable, cumulus, large droplets — most severe",
          "RIME: −10 to −20 °C, stable, stratus, tiny droplets that freeze instantly",
          "MIXED: −8 to −15 °C, and it OVERLAPS both",
        ],
      },
      {
        kind: "manipulate",
        headline: "Move the temperature",
        widget: "IcingWidget",
        line: "Watch the mixed band straddle the boundary between clear and rime. It is not a gap between them.",
      },
      {
        kind: "compare",
        headline: "Why clear is the dangerous one",
        line: "The difference is what the droplet does after it hits.",
        columns: ["Clear", "Rime"],
        rows: [
          { label: "Droplet size", a: "Large", b: "Tiny" },
          { label: "On contact", a: "Spreads out, THEN freezes slowly", b: "Freezes instantly" },
          { label: "Result", a: "Alters the shape of the wing", b: "Rough accretion in place" },
          { label: "Severity", a: "Most severe, difficult to remove", b: "Less severe" },
          { label: "Conditions", a: "Unstable, cumulus, freezing rain", b: "Stable, stratus" },
        ],
      },
      {
        kind: "compare",
        headline: "The two that are not in-flight structural ice",
        line: "Both still matter.",
        columns: ["Frost", "Engine icing"],
        rows: [
          { label: "Where", a: "Ground icing", b: "Compressor inlet, or the intake and carburettor" },
          { label: "Rule", a: "SHALL be removed prior to flight", b: "Induction icing possible up to +10 °C" },
          { label: "Watch out", a: "Do NOT scrape it off, especially the windshield", b: "Ice ingestion is FOD" },
        ],
      },
      {
        kind: "compare",
        headline: "The front tells you which ice to expect",
        line: "Because the front decides the cloud, and the cloud decides the ice.",
        columns: ["Front", "Icing signature"],
        rows: [
          { label: "Warm", a: "Stratiform cloud", b: "Rime · low rate · widespread" },
          { label: "Cold", a: "Cumuliform cloud", b: "Clear · high rate · limited area" },
          { label: "Occluded", a: "Stratus AND cumulus", b: "Rime, clear and mixed · rapid and heavy · very widespread" },
        ],
      },
      {
        kind: "compare",
        headline: "Reporting it",
        line: "A PIREP carries the type and the intensity together.",
        columns: ["Intensity", "What it means"],
        rows: [
          { label: "Trace", a: "Ice becomes perceptible", b: "Accumulating slightly faster than it sublimates" },
          { label: "Light", a: "A problem over an extended time, over an hour", b: "Occasional equipment use prevents it" },
          { label: "Moderate", a: "Potentially hazardous even in short encounters", b: "Equipment or diversion necessary" },
          { label: "Severe", a: "Equipment FAILS to reduce or control it", b: "Immediate diversion necessary" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Clear 0 to −10 · Rime −10 to −20 · Mixed −8 to −15",
          "Warm front rime · cold front clear · occluded the worst of both",
          "Severe icing means the equipment has lost",
          "Clear is the most severe and hardest to remove",
          "Frost is ground icing — remove it, never scrape it",
          "Induction icing up to +10 °C",
        ],
      },
      { kind: "question", questionId: "wq-w8-004" },
      { kind: "question", questionId: "wq-w8-008" },
      { kind: "question", questionId: "wsl-w8-009" },
      { kind: "question", questionId: "wq-wg-031" },
      { kind: "question", questionId: "wq-wg-033" },
    ],
    questionIds: [
      "wq-w8-004", "wq-w8-005", "wq-w8-006", "wq-w8-007", "wq-w8-008",
      "wsl-w8-009", "wq-w8-010", "wq-w8-011", "wq-w8-012",
      "wq-wg-031", "wq-wg-032", "wq-wg-033", "wq-wg-034", "wq-wg-035",
    ],
    memorize: ["0/−10 clear, −10/−20 rime, −8/−15 mixed"],
    sourceReferences: [HAZ],
    explainerIds: ["wx-x-ice-types"],
  },
  {
    id: "wl20-icing-consequences",
    unit: "w8",
    index: 20,
    title: "Living With Ice",
    subtitle: "What it costs, and how to get out",
    estimatedMinutes: 5,
    mapIcon: "wx-deice",
    enablingObjectives: [],
    conceptIds: ["wx-icing-effects", "wx-icing-response"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Every performance number moves the wrong way",
        line: "There is no compensating benefit anywhere on the list.",
      },
      {
        kind: "compare",
        headline: "What ice does to the aircraft",
        columns: ["Increases", "Decreases"],
        rows: [
          { label: "", a: "Drag", b: "Thrust" },
          { label: " ", a: "Weight", b: "Range" },
          { label: "  ", a: "Stall speed", b: "Lift" },
          { label: "   ", a: "Fuel consumption", b: "" },
        ],
      },
      {
        kind: "compare",
        headline: "Two kinds of equipment",
        columns: ["De-icing", "Anti-icing"],
        rows: [
          { label: "Does what", a: "Eliminates or removes ice that is PRESENT", b: "PREVENTS accumulation" },
        ],
      },
      {
        kind: "chain",
        headline: "After encountering icing",
        nodes: [
          { label: "Use anti-ice and/or de-ice equipment", trend: "none" },
          { label: "Climb to colder than −20 °C, or descend to warmer air", trend: "none" },
          { label: "Get out of visible moisture", trend: "none" },
          { label: "Land, in an emergency", trend: "none" },
          { label: "Minimise manoeuvring throughout", trend: "down", emphasis: true },
        ],
        footnote: "Manoeuvring costs performance you no longer have.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "↑ drag, weight, stall speed, fuel · ↓ thrust, range, lift",
          "De-ice REMOVES · Anti-ice PREVENTS",
          "Climb past −20 °C or descend to warmer air",
          "Minimise manoeuvring",
        ],
      },
      { kind: "question", questionId: "wq-w8-013" },
      { kind: "question", questionId: "wq-w8-014" },
      { kind: "question", questionId: "wq-w8-015" },
    ],
    questionIds: ["wq-w8-013", "wq-w8-014", "wq-w8-015"],
    memorize: ["De-ice removes, anti-ice prevents", "Colder than −20 °C"],
    sourceReferences: [HAZ],
  },

  /* ================= w9 · storms and low visibility ================= */
  {
    id: "wl21-thunderstorms",
    unit: "w9",
    index: 21,
    title: "Thunderstorms",
    subtitle: "Six hazards, four options",
    estimatedMinutes: 6,
    mapIcon: "wx-thunderstorm",
    enablingObjectives: [],
    conceptIds: ["wx-thunderstorm-hazards", "wx-thunderstorm-avoidance", "wx-thunderstorm-radar"],
    masteryThreshold: 0.85,
    screens: [
      {
        kind: "hook",
        headline: "A cumulonimbus contains every hazard in this course at once",
        line: "Hail, icing, microbursts, extreme turbulence, lightning and tornados. Which is why the first option is always to go around it.",
      },
      {
        kind: "chain",
        headline: "The six hazards",
        nodes: [
          { label: "Hail", trend: "none" },
          { label: "Icing", trend: "none" },
          { label: "Microbursts", trend: "none" },
          { label: "Extreme turbulence", trend: "none" },
          { label: "Lightning", trend: "none" },
          { label: "Tornados", trend: "none" },
        ],
      },
      {
        kind: "model",
        headline: "Four options, in priority order",
        diagram: { id: "wx-storm-avoidance", props: { option: "none" } },
        bullets: [
          "CIRCUMNAVIGATE — fly around it. Always the first choice.",
          "OVER — 1,000 ft above the top per 10 kt of wind at the top",
          "UNDER — the lower third of the distance from cloud base to ground",
          "THROUGH — penetrate the lower third, with no angle",
        ],
      },
      {
        kind: "rule",
        headline: "The order is the priority",
        rule:
          "Circumnavigate, Over, Under, Through — in that order of priority.",
        appliesWhen: ["Any thunderstorm on the route"],
        watchFor:
          "Going over costs 1,000 ft for every 10 kt of wind at the top, which over a tall storm in a strong wind puts it out of reach quickly.",
      },
      {
        kind: "rule",
        headline: "What radar can and cannot do",
        rule:
          "A direct relationship exists between the strength of the radar echoes, the presence of aircraft icing and the intensity of turbulence. Radar echo tops above 35,000 ft often mean extreme turbulence and hail. Radar merely helps to LOCATE the most severe conditions — it does not eliminate the hazard.",
        appliesWhen: [
          "Scattered echoes can usually be circumnavigated",
          "Broken or solid lines of moderate to strong intensity need a radar-equipped aircraft to avoid",
        ],
        watchFor:
          "Severe clear air turbulence and hail may be experienced BETWEEN thunderstorms when the echoes are less than 30 miles apart. The gap is not automatically safe.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Hail, Icing, Microbursts, Extreme turbulence, Lightning, Tornados",
          "Echo tops above 35,000 ft: extreme turbulence and hail",
          "Circumnavigate, Over, Under, Through — in priority order",
          "Over: 1,000 ft per 10 kt at the top",
          "Through: lower third, no angle",
        ],
      },
      { kind: "question", questionId: "wq-w9-001" },
      { kind: "question", questionId: "wq-w9-004" },
      { kind: "question", questionId: "wcc-w9-006" },
      { kind: "question", questionId: "wq-wg-045" },
      { kind: "question", questionId: "wq-wg-047" },
    ],
    questionIds: [
      "wq-w9-001", "wq-w9-002", "wq-w9-003", "wq-w9-004", "wq-w9-005", "wcc-w9-006",
      "wq-wg-045", "wq-wg-046", "wq-wg-047",
    ],
    memorize: ["HI MELT", "COUT, and the order is the priority"],
    sourceReferences: [HAZ],
    explainerIds: ["wx-x-thunderstorm"],
    labIds: ["wxlab-storm"],
  },
  {
    id: "wl22-microbursts",
    unit: "w9",
    index: 22,
    title: "Microbursts",
    subtitle: "It feels good on the way in",
    estimatedMinutes: 5,
    mapIcon: "wx-microburst",
    enablingObjectives: [],
    conceptIds: ["wx-microburst"],
    masteryThreshold: 0.85,
    screens: [
      {
        kind: "hook",
        headline: "The first thing a microburst does is improve your performance",
        line: "That is the trap. The airspeed increase on the way in is borrowed, and the far side takes it back all at once.",
      },
      {
        kind: "model",
        headline: "Entering",
        diagram: { id: "wx-microburst", props: { stage: "headwind" } },
        line: "The outflow arrives as a headwind. Airspeed rises and the aircraft climbs.",
      },
      {
        kind: "model",
        headline: "The core",
        diagram: { id: "wx-microburst", props: { stage: "downdraft" } },
        line: "2,000 to 6,000 feet per minute straight down, inside a vortex ring of 20 to 200 kt.",
      },
      {
        kind: "model",
        headline: "Exiting",
        diagram: { id: "wx-microburst", props: { stage: "tailwind" } },
        line: "The headwind becomes a tailwind. Sudden loss of airspeed, on takeoff or landing, with no height to trade.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "2,000–6,000 fpm downdraft · 20–200 kt vortex ring",
          "Usually lasts only 5–10 minutes, very localised",
          "Visual cues: virga, localised blowing dust, rain shafts, roll clouds",
          "The hazard is the SUDDEN AIRSPEED LOSS on the far side",
        ],
      },
      { kind: "question", questionId: "wq-w9-007" },
      { kind: "question", questionId: "wq-w9-008" },
      { kind: "question", questionId: "wq-w9-009" },
      { kind: "question", questionId: "wq-w9-010" },
    ],
    questionIds: ["wq-w9-007", "wq-w9-008", "wq-w9-009", "wq-w9-010"],
    memorize: ["2,000–6,000 fpm, 20–200 kt, 5–10 minutes"],
    sourceReferences: [HAZ],
    explainerIds: ["wx-x-microburst"],
  },
  {
    id: "wl23-fog-and-visibility",
    unit: "w9",
    index: 23,
    title: "Fog and Obscuration",
    subtitle: "Three conditions and three numbers",
    estimatedMinutes: 5,
    mapIcon: "wx-fog",
    enablingObjectives: [],
    conceptIds: ["wx-fog", "wx-obscuring-phenomenon", "wx-fog-types", "wx-fog-winds"],
    masteryThreshold: 0.85,
    screens: [
      {
        kind: "hook",
        headline: "Fog is a cloud that formed at the wrong altitude",
        line: "Which is why it needs the same ingredients as any cloud, plus one condition all of its own.",
      },
      {
        kind: "model",
        headline: "What it takes, and what defines it",
        diagram: { id: "wx-fog", props: { highlight: "none" } },
        bullets: [
          "Requires condensation nuclei, a low temperature/dew point spread, and LIGHT surface winds",
          "Base within 50 ft of the ground",
          "More than 20 ft thick",
          "Visibility less than ⅝ SM",
        ],
      },
      {
        kind: "rule",
        headline: "Light winds, not calm",
        rule: "Fog requires light surface winds.",
        appliesWhen: ["Formation of any fog"],
        watchFor:
          "Calm air will not mix the moisture through the layer, and strong wind disperses it. Light is the narrow band in between.",
      },
      {
        kind: "compare",
        headline: "Two ways to get there",
        line: "Both cool the air to its dew point. They do it from opposite directions — and they respond to wind in opposite directions too.",
        columns: ["Radiation fog", "Advection fog"],
        rows: [
          { label: "Mechanism", a: "Nocturnal cooling on clear nights", b: "Warm moist air moving over a cold surface" },
          { label: "Timing", a: "Cooling starts 1530–1600 local, runs to just after sunrise", b: "Any time · can persist for weeks over water" },
          { label: "Under 5 kt", a: "Shallow fog", b: "—" },
          { label: "5 to 10 kt", a: "DENSE fog", b: "Thickening" },
          { label: "Over 10 kt", a: "Disperses into low stratus", b: "Still thickening, to about 15 kt" },
          { label: "Also called", a: "—", b: "Sea fog" },
        ],
      },
      {
        kind: "compare",
        headline: "Obscuration is a wider category",
        columns: ["Obscuring phenomenon", "Fog"],
        rows: [
          { label: "Threshold", a: "Reduces horizontal visibility below 7 SM", b: "Visibility below ⅝ SM" },
          { label: "Scope", a: "Anything that does that", b: "A specific cloud-on-the-deck condition" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Nuclei + small spread + LIGHT surface winds",
          "Base within 50 ft, more than 20 ft thick, below ⅝ SM",
          "Obscuring phenomenon: below 7 SM",
        ],
      },
      { kind: "question", questionId: "wq-w9-012" },
      { kind: "question", questionId: "wq-w9-013" },
      { kind: "question", questionId: "wq-wg-036" },
      { kind: "question", questionId: "wq-wg-038" },
      { kind: "question", questionId: "wq-wg-040" },
    ],
    questionIds: [
      "wq-w9-011", "wq-w9-012", "wq-w9-013", "wq-w9-014",
      "wq-wg-036", "wq-wg-037", "wq-wg-038", "wq-wg-039", "wq-wg-040",
    ],
    memorize: ["50 ft base, 20 ft thick, ⅝ SM", "Light winds, not calm"],
    sourceReferences: [HAZ],
    explainerIds: ["wx-x-fog"],
  },

  /* ================= w10 · weather products ================= */
  {
    id: "wl24-reading-the-sky",
    unit: "w10",
    index: 24,
    title: "Ceiling and Visibility",
    subtitle: "Four visibilities, one ceiling",
    estimatedMinutes: 6,
    mapIcon: "wx-ceiling",
    enablingObjectives: [],
    conceptIds: ["wx-ceiling", "wx-visibility-types"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Four different visibilities, and only one of them is in feet",
        line: "They are not interchangeable, and the exam asks you to tell them apart.",
      },
      {
        kind: "rule",
        headline: "Ceiling",
        rule:
          "The ceiling is the lowest BROKEN, OVERCAST or VERTICAL VISIBILITY layer, reported in AGL. Vertical visibility is the distance seen upward from the ground into a total obscuration.",
        appliesWhen: ["Reading any METAR or TAF"],
        watchFor: "Scattered is never a ceiling, however low it is.",
      },
      {
        kind: "compare",
        headline: "The four visibilities",
        line: "Watch the units in the right-hand column.",
        columns: ["What it measures", "Units"],
        rows: [
          { label: "Flight", a: "Unlighted objects by day, lighted by night, from the cockpit", b: "SM" },
          { label: "Prevailing", a: "Max horizontal through at least HALF the horizon circle", b: "SM · on METARs and TAFs" },
          { label: "Slant range", a: "Distance on final when the runway comes in sight", b: "SM" },
          { label: "RVR", a: "Horizontal distance looking DOWN the runway", b: "FEET or METRES" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Ceiling: lowest broken, overcast or vertical visibility, in AGL",
          "Scattered is not a ceiling",
          "Prevailing: at least half the horizon circle",
          "RVR is the only one in feet or metres",
        ],
      },
      { kind: "question", questionId: "wq-w10-001" },
      { kind: "question", questionId: "wq-w10-002" },
      { kind: "question", questionId: "wq-w10-020" },
      { kind: "question", questionId: "wq-w10-021" },
    ],
    questionIds: [
      "wq-w10-001", "wq-w10-002", "wq-w10-020", "wq-w10-021", "wq-w10-022",
    ],
    memorize: ["Broken, overcast or VV — never scattered", "RVR is in feet"],
    sourceReferences: [PLAN],
  },
  {
    id: "wl25-metar-taf-pirep",
    unit: "w10",
    index: 25,
    title: "METAR, TAF and PIREP",
    subtitle: "Now, later, and what you owe the next aircraft",
    estimatedMinutes: 7,
    mapIcon: "wx-metar",
    enablingObjectives: [],
    conceptIds: ["wx-metar", "wx-taf", "wx-pirep", "wx-station-model"],
    masteryThreshold: 0.85,
    screens: [
      {
        kind: "hook",
        headline: "One of these decides whether you go. The other one plans the flight.",
        line: "Swapping them is the most common mistake in this unit.",
      },
      {
        kind: "compare",
        headline: "METAR versus TAF",
        columns: ["METAR", "TAF"],
        rows: [
          { label: "Full name", a: "Meteorological Aerodrome Report", b: "Terminal Aerodrome Forecast" },
          { label: "Reports", a: "CURRENT conditions", b: "FORECAST conditions" },
          { label: "Schedule", a: "Hourly, xx:55–xx:59", b: "Every 6 hours" },
          { label: "Covers", a: "Right now", b: "At least 24 hours from issue" },
          { label: "Used for", a: "Takeoff and landing criteria", b: "Planning" },
        ],
      },
      {
        kind: "model",
        headline: "Reading a wind barb",
        diagram: { id: "wx-station-model", props: { knots: 25 } },
        bullets: [
          "Half line = 5 kt · full line = 10 kt · triangular flag = 50 kt",
          "Cig is the cloud ceiling in hundreds of feet",
        ],
      },
      {
        kind: "manipulate",
        headline: "Build a barb",
        widget: "StationModelWidget",
        line: "Work down from 50s, then 10s, then a single 5. 65 kt is one flag, one full line and one half line.",
      },
      {
        kind: "rule",
        headline: "When a PIREP is required",
        rule:
          "A PIREP is a voice report to ATC while airborne, to warn other aviators. It is required when conditions differ from the last observation on an IFR approach, on wind shear during departure or arrival, when requested in-flight by ATC, for unusual or unforeseen weather conditions, and after a missed approach.",
        appliesWhen: ["Any of those five situations"],
        watchFor: "IWRUM. It is not optional in those cases.",
        authority: "IWRUM",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "METAR: hourly, current, decides takeoff and landing",
          "TAF: every 6 hours, covers 24+, used for planning",
          "TAF elements persist until a later line changes them",
          "Half 5, full 10, flag 50",
          "PIREP required: IWRUM",
        ],
      },
      { kind: "question", questionId: "wq-w10-006" },
      { kind: "question", questionId: "wq-w10-007" },
      { kind: "question", questionId: "wq-w10-008" },
      { kind: "question", questionId: "wsl-w10-004" },
      { kind: "question", questionId: "wq-w10-010" },
    ],
    questionIds: [
      "wq-w10-003", "wsl-w10-004", "wq-w10-005", "wq-w10-006",
      "wq-w10-007", "wq-w10-008", "wq-w10-009", "wq-w10-010", "wq-w10-011",
    ],
    memorize: ["METAR decides, TAF plans", "IWRUM"],
    sourceReferences: [PLAN],
    explainerIds: ["wx-x-metar-taf"],
    labIds: ["wxlab-products"],
  },
  {
    id: "wl26-charts-and-imagery",
    unit: "w10",
    index: 26,
    title: "Charts and Imagery",
    subtitle: "The big picture, and how it is made",
    estimatedMinutes: 5,
    mapIcon: "wx-chart",
    enablingObjectives: [],
    conceptIds: ["wx-surface-analysis", "wx-prognostic-chart", "wx-radar-satellite", "wx-winds-aloft"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "One chart shows what is. The other shows what will be — and it is the one with the rain on it.",
        line: "That single difference is the question the exam asks.",
      },
      {
        kind: "compare",
        headline: "Two charts",
        columns: ["Surface analysis", "Prognostic"],
        rows: [
          { label: "Shows", a: "Troughs, fronts, pressure systems, isobars", b: "Forecast future conditions" },
          { label: "Isobar spacing", a: "4 mb", b: "" },
          { label: "Precipitation", a: "NONE", b: "YES" },
          { label: "Used for", a: "Current synoptic picture", b: "Big picture planning" },
        ],
      },
      {
        kind: "compare",
        headline: "Radar and satellite",
        columns: ["Radar", "Satellite"],
        rows: [
          { label: "Based", a: "Ground based", b: "NOT ground based" },
          { label: "Limitation", a: "Restricted to line of sight", b: "—" },
          { label: "Shows", a: "Returns from precipitation", b: "Reflectivity of clouds — whiter is thicker" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Surface analysis: isobars at 4 mb, and NO precipitation",
          "Prognostic: the future, with precipitation",
          "Radar is ground based and line of sight",
          "Satellite: whiter means thicker cloud",
          "Winds aloft: pick a flight level, aid navigation planning",
        ],
      },
      { kind: "question", questionId: "wq-w10-012" },
      { kind: "question", questionId: "wq-w10-014" },
      { kind: "question", questionId: "wq-w10-015" },
      { kind: "question", questionId: "wq-w10-017" },
    ],
    questionIds: [
      "wq-w10-012", "wq-w10-013", "wq-w10-014", "wq-w10-015", "wq-w10-016", "wq-w10-017",
    ],
    memorize: ["No precipitation on a surface analysis", "Whiter is thicker"],
    sourceReferences: [PLAN],
  },
  {
    id: "wl27-advisories-and-briefings",
    unit: "w10",
    index: 27,
    title: "Advisories and Briefings",
    subtitle: "SIGMET, AIRMET, and the form you sign for",
    estimatedMinutes: 7,
    mapIcon: "wx-advisory",
    enablingObjectives: [],
    conceptIds: [
      "wx-convective-sigmet",
      "wx-nonconvective-sigmet",
      "wx-airmet",
      "wx-weather-briefing",
      "wx-advisory-identifiers",
    ],
    masteryThreshold: 0.85,
    screens: [
      {
        kind: "hook",
        headline: "AIRMET is the moderate one. SIGMET is the severe one.",
        line: "Get that the wrong way round and every number that follows is wrong too.",
      },
      {
        kind: "model",
        headline: "How far forward each reaches",
        diagram: { id: "wx-product-timeline", props: { product: "none" } },
        bullets: [
          "Convective SIGMET: issued xx:55, valid 2 hours",
          "Non-convective SIGMET: 4 hours, or 6 for hurricanes",
          "AIRMET: routinely every 6 hours",
        ],
      },
      {
        kind: "compare",
        headline: "What triggers each",
        columns: ["Product", "Criteria"],
        rows: [
          {
            label: "Convective SIGMET",
            a: "60 mile line with storms over 40% of it · 40% area coverage of high reflectivity · severe or embedded storms > 30 min · tornado · hail > ¾ in · gusts ≥ 50 kt",
            b: "Thunderstorm related",
          },
          {
            label: "Non-convective SIGMET",
            a: "Severe icing · severe or extreme turbulence · dust or sand below 3 SM · volcanic ash",
            b: "Not thunderstorm related",
          },
          {
            label: "AIRMET",
            a: "Moderate turbulence · LLWS below 2,000 AGL with a shift > 20 kt · surface winds > 30 kt · icing and moderate structural icing · freezing level · IFR below 1,000 AGL and/or 3 SM · mountain obscuration",
            b: "At least 3,000 sq mi",
          },
        ],
      },
      {
        kind: "compare",
        headline: "The letter identifiers",
        line: "Three products, and three AIRMET types inside the last one.",
        columns: ["Identifier", "What it is"],
        rows: [
          { label: "WS", a: "SIGMET", b: "Severe, non-convective" },
          { label: "WST", a: "Convective SIGMET", b: "Thunderstorm-related" },
          { label: "WA", a: "AIRMET", b: "Moderate" },
          { label: "Sierra", a: "AIRMET for widespread IFR", b: "Ceiling below 1,000 ft and/or visibility below 3 miles over 50% of the area, or extensive mountain obscuration" },
          { label: "Tango", a: "AIRMET for turbulence", b: "Moderate turbulence, or sustained surface winds of 30 kt or more" },
          { label: "Zulu", a: "AIRMET for icing", b: "Moderate icing, or freezing level data" },
        ],
      },
      {
        kind: "rule",
        headline: "The weather brief",
        rule:
          "A DD Form 175-1 is prepared by weather offices to brief the pilot on local, en route and destination conditions. A FLIMSY number is required. The FAR requires knowledge of VFR minimums and says you SHOULD receive a brief; M-3710.7 says you SHALL receive one, and an en route brief for IFR.",
        appliesWhen: ["Every naval flight"],
        watchFor:
          "Two publications, two different words. FAR says should; CNAF says shall. That difference is the question.",
        authority: "CNAF M-3710.7",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Convective SIGMET: 2 hours · Non-convective: 4, or 6 for hurricanes",
          "AIRMET: 3,000 sq mi, every 6 hours, MODERATE",
          "SIGMET is severe. AIRMET is moderate.",
          "DD Form 175-1 · FAR should, CNAF shall",
        ],
      },
      { kind: "question", questionId: "wq-w10-023" },
      { kind: "question", questionId: "wq-w10-029" },
      { kind: "question", questionId: "wq-w10-019" },
      { kind: "question", questionId: "wq-wg-048" },
      { kind: "question", questionId: "wq-wg-049" },
    ],
    questionIds: [
      "wq-w10-018", "wq-w10-019", "wq-w10-023", "wq-w10-024", "wq-w10-025",
      "wq-w10-026", "wq-w10-027", "wq-w10-028", "wq-w10-029", "wq-w10-030",
      "wq-wg-048", "wq-wg-049", "wq-wg-050", "wq-wg-051",
    ],
    memorize: [
      "AIRMET moderate, SIGMET severe",
      "2 / 4 / 6 hours · DD-175-1",
    ],
    sourceReferences: [PLAN],
    explainerIds: ["wx-x-advisories"],
  },
];
