import type { Lesson, SourceReference } from "@/lib/types";

const NOTES = (chapter: string): SourceReference => ({
  document: "Weather Condensed Notes",
  chapter,
});

const THEORY = NOTES("WX 1: Theory");
const MECH = NOTES("WX 2: Mechanics");

/**
 * Weather lessons, units w1–w5.
 *
 * Each lesson follows the same arc the brief asks for: see the system, change
 * one variable, watch the result, connect the chain, then retrieve. Weather is
 * the course where the picture does most of the teaching, so almost every
 * lesson opens on a diagram rather than on a definition.
 */
export const LESSONS_A: Lesson[] = [
  /* ================= w1 · the atmosphere ================= */
  {
    id: "wl01-the-troposphere",
    unit: "w1",
    index: 1,
    title: "The Troposphere",
    subtitle: "The layer weather lives in",
    estimatedMinutes: 5,
    mapIcon: "wx-atmosphere",
    enablingObjectives: [],
    conceptIds: [
      "wx-troposphere",
      "wx-tropopause",
      "wx-stratosphere",
      "wx-layer-flight-conditions",
      "wx-heat-exchange",
    ],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "Everything in this course happens in one thin layer",
        line: "The troposphere holds almost all the water and almost all the weather. Above it, the air stops cooling and the weather stops happening.",
      },
      {
        kind: "model",
        headline: "Looking at it side on",
        diagram: { id: "wx-atmosphere", props: { highlight: "troposphere" } },
        bullets: [
          "0–5% water vapour by volume — the moisture is all down here",
          "Top runs 28,000–55,000 ft MSL, about 36,000 ft over the US",
          "Climbing through it: temperature falls, wind strengthens",
        ],
      },
      {
        kind: "model",
        headline: "Where it stops",
        diagram: { id: "wx-atmosphere", props: { highlight: "tropopause" } },
        line: "The tropopause is isothermal — the temperature holds constant through it. That is the transition to the stratosphere.",
      },
      {
        kind: "compare",
        headline: "Three layers, three rides",
        line: "Flight conditions follow the weather, and the weather is all in one place.",
        columns: ["Layer", "What it is like to fly in"],
        rows: [
          { label: "Troposphere", a: "Nearly all weather", b: "Turbulence, icing, restricted visibility" },
          { label: "Tropopause", a: "Isothermal transition", b: "The jet stream and its shear" },
          { label: "Stratosphere", a: "Constant temperature to ~66,000 ft, then rising", b: "Smooth, excellent visibility — few aircraft get there" },
        ],
      },
      {
        kind: "chain",
        headline: "Why any of it moves",
        nodes: [
          { label: "The earth heats unevenly", trend: "none" },
          { label: "Air circulation and pressure differentials", trend: "none" },
          { label: "All weather", trend: "up", emphasis: true },
        ],
        footnote: "All weather is the result of heat exchange. Every chain in this course starts there.",
      },
      {
        kind: "manipulate",
        headline: "Three layers, three different rides",
        widget: "AtmosphereLayerPicker",
        line: "Pick a layer and see what flying in it actually involves.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Nearly all weather occurs in the troposphere",
          "Top 28k–55k MSL, about 36k over the US",
          "The tropopause is ISOTHERMAL — constant temperature",
          "All weather is heat exchange",
        ],
      },
      { kind: "question", questionId: "wq-w1-001" },
      { kind: "question", questionId: "wq-w1-005" },
      { kind: "question", questionId: "wq-wg-001" },
      { kind: "question", questionId: "wq-wg-003" },
    ],
    questionIds: [
      "wq-w1-001", "wq-w1-002", "wq-w1-003", "wq-w1-004", "wq-w1-005", "wq-w1-006",
      "wq-wg-001", "wq-wg-002", "wq-wg-003", "wq-wg-004",
    ],
    memorize: [
      "Troposphere: 0–5% water vapour, nearly all weather",
      "Tropopause is isothermal",
      "All weather is heat exchange",
    ],
    sourceReferences: [THEORY],
    explainerIds: ["wx-x-atmosphere"],
  },
  {
    id: "wl02-pressure-and-lapse-rates",
    unit: "w1",
    index: 2,
    title: "Pressure and Lapse Rates",
    subtitle: "Two variables, two rates",
    estimatedMinutes: 6,
    mapIcon: "wx-pressure",
    enablingObjectives: [],
    conceptIds: ["wx-atmospheric-pressure", "wx-standard-atmosphere", "wx-lapse-rate", "wx-slp-sp"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Pressure is just the weight of the air above you",
        line: "Climb, and there is less of it. That single idea sets both the pressure lapse rate and the altimeter.",
      },
      {
        kind: "model",
        headline: "Both rates on one chart",
        diagram: { id: "wx-lapse-rates", props: { altitude: 0, show: "both" } },
        bullets: [
          "Temperature: 2 °C per 1,000 ft",
          "Pressure: 1 inHg per 1,000 ft",
          "Standard sea level: 29.92 inHg and 15 °C (59 °F)",
        ],
      },
      {
        kind: "manipulate",
        headline: "Climb and read both off",
        widget: "LapseRateWidget",
        line: "At 10,000 ft the standard day is −5 °C and 19.92 inHg. Both numbers move together, at different rates in different units.",
      },
      {
        kind: "compare",
        headline: "Sea level pressure versus station pressure",
        line: "The difference matters the moment your airfield is not at sea level.",
        columns: ["What it is", "How it compares"],
        rows: [
          { label: "SLP", a: "Pressure at sea level, or calculated from a station", b: "This is the altimeter setting" },
          { label: "SP", a: "Pressure directly at the airfield", b: "ALWAYS less than SLP if the station is above sea level" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Standard sea level: 29.92 inHg, 15 °C, 59 °F",
          "Temperature 2 °C / 1,000 ft · Pressure 1 inHg / 1,000 ft",
          "Station above sea level → SP is less than SLP",
          "The altimeter setting is SLP",
        ],
      },
      { kind: "question", questionId: "wq-w1-011" },
      { kind: "question", questionId: "wq-w1-013" },
      { kind: "question", questionId: "wsl-w1-014" },
      { kind: "question", questionId: "wq-w1-016" },
    ],
    questionIds: [
      "wq-w1-010", "wq-w1-011", "wq-w1-012", "wq-w1-013", "wsl-w1-014",
      "wq-w1-015", "wq-w1-016", "wq-w1-017",
    ],
    memorize: ["29.92 and 15 °C", "2 °C and 1 inHg, both per 1,000 ft"],
    sourceReferences: [THEORY],
    explainerIds: ["wx-x-lapse-rates"],
    labIds: ["wxlab-atmosphere"],
  },
  {
    id: "wl03-pressure-gradient-force",
    unit: "w1",
    index: 3,
    title: "Pressure Gradient Force",
    subtitle: "What starts every wind",
    estimatedMinutes: 4,
    mapIcon: "wx-gradient",
    enablingObjectives: [],
    conceptIds: ["wx-pgf", "wx-heat-exchange"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Nothing moves until there is a pressure difference",
        line: "PGF is the initiating force for all winds. Everything else — friction, terrain, the jet stream — only modifies what PGF began.",
      },
      {
        kind: "model",
        headline: "Reading a gradient",
        diagram: { id: "wx-pressure-field", props: { level: "gradient" } },
        bullets: [
          "Isobars join points of equal pressure",
          "The gradient is measured PERPENDICULAR to them",
          "Closely spaced isobars mean a steep gradient and strong wind",
        ],
      },
      {
        kind: "chain",
        headline: "From sunlight to wind",
        nodes: [
          { label: "Uneven heating of the earth", trend: "none" },
          { label: "Pressure differentials", trend: "up" },
          { label: "Pressure gradient", trend: "up" },
          { label: "Wind", trend: "up", emphasis: true },
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "PGF is the initiating force for ALL winds",
          "The gradient is a rate of change PERPENDICULAR to the isobars",
        ],
      },
      { kind: "question", questionId: "wq-w1-009" },
      { kind: "question", questionId: "wq-w1-008" },
      { kind: "question", questionId: "wcc-w1-007" },
    ],
    questionIds: ["wq-w1-008", "wq-w1-009", "wcc-w1-007"],
    memorize: ["PGF starts every wind", "Gradient is measured across the isobars"],
    sourceReferences: [THEORY],
  },

  /* ================= w2 · altitude and the altimeter ================= */
  {
    id: "wl04-five-altitudes",
    unit: "w2",
    index: 4,
    title: "Five Altitudes",
    subtitle: "Same aircraft, five different numbers",
    estimatedMinutes: 6,
    mapIcon: "wx-altitude",
    enablingObjectives: [],
    conceptIds: [
      "wx-indicated-altitude",
      "wx-true-altitude",
      "wx-absolute-altitude",
      "wx-pressure-altitude",
      "wx-density-altitude",
    ],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "One aircraft, five altitudes, all of them correct",
        line: "They differ because each is measured from a different reference — and one of them is not a height at all.",
      },
      {
        kind: "model",
        headline: "Four references on one picture",
        diagram: { id: "wx-altitude-types", props: { highlight: "none" } },
        bullets: [
          "TRUE: above mean sea level — the standard altitude",
          "ABSOLUTE: above the terrain below you",
          "PRESSURE: above the standard datum plane, with 29.92 set",
          "INDICATED: what the altimeter reads, trying to be true",
        ],
      },
      {
        kind: "compare",
        headline: "The odd one out",
        line: "Density altitude is not a position. It is a performance figure wearing the units of a height.",
        columns: ["Measures", "Used for"],
        rows: [
          { label: "True", a: "Height above MSL", b: "Terrain and obstacle clearance" },
          { label: "Absolute", a: "Height above the terrain", b: "How far you are off the ground right now" },
          { label: "Pressure", a: "Height above the 29.92 datum", b: "Standard in Class A" },
          { label: "Density", a: "Nothing physical", b: "Gauging aircraft performance" },
        ],
      },
      {
        kind: "manipulate",
        headline: "Same aeroplane, three different numbers",
        widget: "AltitudeTypePicker",
        line: "Pick a reference and see what it is measured from, and what it is for.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "True = MSL · Absolute = AGL",
          "Pressure altitude: set 29.92, and it is standard in Class A",
          "Density altitude is about performance, not position",
        ],
      },
      { kind: "question", questionId: "wq-w2-001" },
      { kind: "question", questionId: "wq-w2-002" },
      { kind: "question", questionId: "wq-w2-003" },
      { kind: "question", questionId: "wq-w2-005" },
      { kind: "question", questionId: "wtap-w2-011" },
    ],
    questionIds: [
      "wq-w2-001", "wq-w2-002", "wq-w2-003", "wq-w2-004", "wq-w2-005",
      "wq-w2-006", "wtap-w2-011",
    ],
    memorize: ["True MSL, Absolute AGL", "Pressure altitude runs on 29.92"],
    sourceReferences: [THEORY],
    explainerIds: ["wx-x-altitudes"],
  },
  {
    id: "wl05-altimeter-errors",
    unit: "w2",
    index: 5,
    title: "When the Altimeter Lies",
    subtitle: "Cold, high, and lower than you think",
    estimatedMinutes: 5,
    mapIcon: "wx-altimeter",
    enablingObjectives: [],
    conceptIds: ["wx-altimeter", "wx-temp-altimeter-error"],
    masteryThreshold: 0.85,
    screens: [
      {
        kind: "hook",
        headline: "On a cold day the altimeter reads high",
        line: "Which means the aircraft is LOWER than the number in front of you. That is the direction that hurts.",
      },
      {
        kind: "model",
        headline: "Standard day, no error",
        diagram: { id: "wx-altimeter-error", props: { condition: "standard" } },
        line: "The altimeter measures the difference between static pressure and the sea level pressure set in the Kollsman window, at 1,000 ft per inch of mercury.",
      },
      {
        kind: "model",
        headline: "Colder than standard",
        diagram: { id: "wx-altimeter-error", props: { condition: "cold" } },
        line: "The indication stays put while the true height falls away beneath it. You are lower than it says.",
      },
      {
        kind: "model",
        headline: "Hotter than standard",
        diagram: { id: "wx-altimeter-error", props: { condition: "hot" } },
        line: "The error reverses: it indicates lower than true, so you are higher than it says. Less dangerous, same mechanism.",
      },
      {
        kind: "manipulate",
        headline: "Fly into colder air and watch the error appear",
        widget: "AltimeterConditionPicker",
        line: "One of these two directions puts you lower than the needle claims.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "1 inHg of difference = 1,000 ft of indication",
          "COLDER than standard → indicates HIGHER than true → you are lower",
          "HOTTER than standard → indicates LOWER than true",
          "Temperature effects are less noticeable than pressure changes",
        ],
      },
      { kind: "question", questionId: "wq-w2-007" },
      { kind: "question", questionId: "wq-w2-009" },
      { kind: "question", questionId: "wq-w2-010" },
    ],
    questionIds: ["wq-w2-007", "wq-w2-008", "wq-w2-009", "wq-w2-010"],
    memorize: ["Cold: indicates high, you are LOW", "1 inHg = 1,000 ft"],
    sourceReferences: [THEORY],
    explainerIds: ["wx-x-altimeter"],
    labIds: ["wxlab-altimeter"],
  },

  /* ================= w3 · moisture and stability ================= */
  {
    id: "wl06-moisture",
    unit: "w3",
    index: 6,
    title: "Moisture",
    subtitle: "Dew point, spread and saturation",
    estimatedMinutes: 6,
    mapIcon: "wx-moisture",
    enablingObjectives: [],
    conceptIds: ["wx-dew-point", "wx-dew-point-spread", "wx-relative-humidity", "wx-saturation"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Two numbers on a METAR tell you whether you will get cloud",
        line: "Temperature and dew point. What matters is not either one — it is the gap between them.",
      },
      {
        kind: "model",
        headline: "The spread",
        diagram: { id: "wx-dewpoint-spread", props: { spread: 12 } },
        bullets: [
          "Dew point: the temperature the parcel must be cooled to, at CONSTANT PRESSURE, to condense",
          "Dew point depression is the difference between the two",
          "Relative humidity is the same idea as a percentage — percent saturation",
        ],
      },
      {
        kind: "manipulate",
        headline: "Close the gap",
        widget: "DewPointWidget",
        line: "Bring the dew point up toward the temperature and watch condensation appear. At zero spread the air is saturated.",
      },
      {
        kind: "rule",
        headline: "Saturation",
        rule:
          "Saturation is the state in which the air is holding the maximum water vapour possible for its temperature and pressure — relative humidity 100%, dew point spread zero.",
        appliesWhen: [
          "COOLING the air, which brings the temperature down to the dew point",
          "EVAPORATION, which adds moisture and brings the dew point up to the temperature",
        ],
        watchFor:
          "Two roads, not one. And by the time the spread is 4 °F the relative humidity is already 90%, with vapour condensing into fog or cloud.",
      },
      {
        kind: "chain",
        headline: "What a shrinking spread means",
        nodes: [
          { label: "Spread decreases", trend: "down" },
          { label: "Relative humidity rises toward 100%", trend: "up" },
          { label: "More moisture condenses", trend: "up", emphasis: true },
          { label: "Cloud, fog or precipitation more likely", trend: "up" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Dew point: cooled at CONSTANT PRESSURE to condense",
          "Smaller depression → more moisture condenses",
          "Relative humidity = percent saturation",
        ],
      },
      { kind: "question", questionId: "wq-w3-001" },
      { kind: "question", questionId: "wsl-w3-003" },
      { kind: "question", questionId: "wq-wg-053" },
      { kind: "question", questionId: "wq-wg-054" },
    ],
    questionIds: [
      "wq-w3-001", "wq-w3-002", "wsl-w3-003", "wq-w3-004", "wq-wg-053", "wq-wg-054",
    ],
    memorize: ["Smaller spread, more condensation", "RH is percent saturation"],
    sourceReferences: [THEORY],
    explainerIds: ["wx-x-dewpoint"],
    labIds: ["wxlab-cloud"],
  },
  {
    id: "wl07-stability",
    unit: "w3",
    index: 7,
    title: "Stability",
    subtitle: "Whether the air wants to rise",
    estimatedMinutes: 6,
    mapIcon: "wx-stability",
    enablingObjectives: [],
    conceptIds: ["wx-air-stability", "wx-air-mass", "wx-inversion", "wx-stability-clues"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Stability is never about an absolute temperature",
        line: "It is about the parcel compared with what surrounds it. Get that straight and half the course follows.",
      },
      {
        kind: "model",
        headline: "Three cases",
        diagram: { id: "wx-stability", props: { state: "unstable" } },
        bullets: [
          "Parcel COLDER than the surroundings → stable, it sinks back",
          "Parcel HOTTER → unstable, it keeps rising",
          "Parcel the SAME → neutral, it stays put",
        ],
      },
      {
        kind: "manipulate",
        headline: "Change the parcel",
        widget: "StabilityWidget",
        line: "Same picture, three answers, depending only on how the parcel compares with its surroundings.",
      },
      {
        kind: "compare",
        headline: "Air masses carry their stability with them",
        line: "This is the line that drives cloud type, precipitation and turbulence later in the course.",
        columns: ["Air mass", "Stability"],
        rows: [
          { label: "Warm air mass", a: "STABLE", b: "Stratiform cloud, continuous precipitation, smooth" },
          { label: "Cold air mass", a: "UNSTABLE", b: "Cumuliform cloud, showery precipitation, turbulent" },
        ],
      },
      {
        kind: "compare",
        headline: "Reading it from the cockpit",
        line: "You will not have a thermometer trace. You will have these.",
        columns: ["Stable", "Unstable"],
        rows: [
          { label: "Temperature while climbing", a: "Rising, or falling only slightly", b: "Falling rapidly" },
          { label: "Cloud", a: "Widespread fog or low cloud", b: "Towering cumulus" },
          { label: "Precipitation", a: "Steady if any", b: "Heavy showers" },
          { label: "Other signs", a: "Temperature inversions", b: "Thunderstorms, dust devils" },
        ],
      },
      {
        kind: "rule",
        headline: "Temperature inversion",
        rule: "A temperature inversion exists when temperature INCREASES as altitude increases.",
        appliesWhen: [
          "Typically near the surface on cool, clear nights",
          "Wherever a fast warm airflow overruns colder air",
        ],
        watchFor:
          "An inversion is a very stable layer — and the wind that creates it generates large wind shear at the inversion boundary.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Cold → stable · Hot → unstable · Same → neutral",
          "Warm air masses are stable, cold air masses are unstable",
          "Inversion: temperature INCREASES with altitude",
        ],
      },
      { kind: "question", questionId: "wq-w3-006" },
      { kind: "question", questionId: "wbf-w3-008" },
      { kind: "question", questionId: "wq-wg-008" },
      { kind: "question", questionId: "wq-wg-009" },
    ],
    questionIds: [
      "wq-w3-005", "wq-w3-006", "wq-w3-007", "wbf-w3-008", "wq-w3-009", "wq-w3-010",
      "wq-wg-008", "wq-wg-009", "wq-wg-010",
    ],
    memorize: [
      "Warm mass stable, cold mass unstable",
      "Inversion: warmer as you climb",
    ],
    sourceReferences: [THEORY, MECH],
    explainerIds: ["wx-x-stability"],
  },

  /* ================= w4 · wind ================= */
  {
    id: "wl08-gradient-and-surface-wind",
    unit: "w4",
    index: 8,
    title: "Gradient and Surface Wind",
    subtitle: "The same wind, 2,000 feet apart",
    estimatedMinutes: 6,
    mapIcon: "wx-wind",
    enablingObjectives: [],
    conceptIds: ["wx-gradient-wind", "wx-surface-wind"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Wind does not blow straight from high to low",
        line: "PGF would send it that way. What you actually get is wind running parallel to the isobars — until friction gets hold of it.",
      },
      {
        kind: "model",
        headline: "Above the friction layer",
        diagram: { id: "wx-pressure-field", props: { level: "gradient" } },
        bullets: [
          "Above 2,000 ft AGL",
          "Parallel to the isobars",
          "Counter-clockwise around lows, clockwise around highs",
        ],
      },
      {
        kind: "manipulate",
        headline: "Drop below 2,000 feet",
        widget: "PressureFieldWidget",
        line: "Surface wind keeps the same sense of rotation, but friction adds directional variation and pulls it across the isobars.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "2,000 ft AGL divides surface wind from gradient wind",
          "Gradient wind runs PARALLEL to the isobars",
          "Counter-clockwise around a low, clockwise around a high",
          "Friction is what makes the surface wind different",
        ],
      },
      { kind: "question", questionId: "wq-w4-001" },
      { kind: "question", questionId: "wq-w4-002" },
      { kind: "question", questionId: "wq-w4-003" },
      { kind: "question", questionId: "wq-w4-004" },
    ],
    questionIds: ["wq-w4-001", "wq-w4-002", "wq-w4-003", "wq-w4-004"],
    memorize: ["2,000 ft AGL is the line", "Low counter-clockwise, high clockwise"],
    sourceReferences: [MECH],
    explainerIds: ["wx-x-wind"],
    labIds: ["wxlab-wind"],
  },
  {
    id: "wl09-buys-ballot-and-breezes",
    unit: "w4",
    index: 9,
    title: "Buys Ballot and Local Winds",
    subtitle: "Finding the low, and the daily cycle at the coast",
    estimatedMinutes: 5,
    mapIcon: "wx-breeze",
    enablingObjectives: [],
    conceptIds: ["wx-buys-ballot", "wx-sea-land-breeze", "wx-mountain-valley-wind"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "You can locate a pressure system by standing still",
        line: "Put the wind at your back. The low is on your left.",
      },
      {
        kind: "model",
        headline: "Buys Ballot's Law",
        diagram: { id: "wx-buys-ballot" },
        line: "Wind at your back: low to the left, high to the right. One glance at a windsock places the systems around you.",
      },
      {
        kind: "model",
        headline: "The coast, by day",
        diagram: { id: "wx-sea-land-breeze", props: { phase: "day" } },
        line: "Warm land air rises and moves out to sea; cool dense sea air moves in beneath it. About 15–20 kt around the shore.",
      },
      {
        kind: "model",
        headline: "And by night",
        diagram: { id: "wx-sea-land-breeze", props: { phase: "night" } },
        line: "Land cools faster than sea, so the contrast inverts and the whole cycle flips.",
      },
      {
        kind: "compare",
        headline: "The same cycle, on a mountain",
        line: "Named the same way as the sea breeze — for where the air comes FROM.",
        columns: ["Valley wind", "Mountain wind"],
        rows: [
          { label: "When", a: "Day", b: "Night" },
          { label: "Cause", a: "Sun heats the slope, which heats the air by conduction", b: "Outgoing terrestrial radiation cools the slope air" },
          { label: "That air becomes", a: "Warmer and less dense — it rises", b: "Denser than its surroundings — it sinks" },
          { label: "Flow", a: "Up the slope, out of the valley", b: "Downhill from the peak" },
        ],
      },
      {
        kind: "manipulate",
        headline: "Flip day to night and the breeze reverses",
        widget: "SeaLandBreezePhase",
        line: "Find the warmer surface, put the rising air over it, and read off the direction.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Wind at your back: LOW LEFT, HIGH RIGHT",
          "Sea breeze by day, land breeze by night",
          "Valley wind by day, mountain wind by night",
          "Named for where the surface air comes FROM",
          "Land cools faster than sea — that is the whole mechanism",
        ],
      },
      { kind: "question", questionId: "wq-w4-005" },
      { kind: "question", questionId: "wq-w4-007" },
      { kind: "question", questionId: "wbf-w4-009" },
      { kind: "question", questionId: "wq-wg-005" },
      { kind: "question", questionId: "wq-wg-006" },
    ],
    questionIds: [
      "wq-w4-005", "wq-w4-006", "wq-w4-007", "wq-w4-008", "wbf-w4-009",
      "wq-wg-005", "wq-wg-006", "wq-wg-007",
    ],
    memorize: ["Wind at your back: L left, H right", "Day sea, night land"],
    sourceReferences: [MECH],
    explainerIds: ["wx-x-breeze"],
  },
  {
    id: "wl10-jet-stream",
    unit: "w4",
    index: 10,
    title: "The Jet Stream",
    subtitle: "A river of wind at the top of the troposphere",
    estimatedMinutes: 4,
    mapIcon: "wx-jetstream",
    enablingObjectives: [],
    conceptIds: ["wx-jet-stream"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "A hundred knots is the AVERAGE",
        line: "It can exceed 250. And it sits exactly where a lot of aircraft want to cruise.",
      },
      {
        kind: "model",
        headline: "Where it lives",
        diagram: { id: "wx-atmosphere", props: { highlight: "troposphere" } },
        bullets: [
          "At the top of the troposphere, averaging FL300 over the US",
          "Generally west to east, and it can change hourly",
          "100–400 miles wide, 1,000–3,000 miles long, 3,000–7,000 ft thick",
        ],
      },
      {
        kind: "chain",
        headline: "Why it matters beyond the tailwind",
        nodes: [
          { label: "Large fluctuations in wind intensity through the jet", trend: "none" },
          { label: "A high degree of wind shear", trend: "up" },
          { label: "Clear air turbulence", trend: "up", emphasis: true },
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "FL300 average over the US",
          "100–150 kt average, can exceed 250 kt",
          "West to east, changes hourly",
          "It is a high level wind shear source — clear air turbulence",
        ],
      },
      { kind: "question", questionId: "wq-w4-010" },
      { kind: "question", questionId: "wq-w4-011" },
      { kind: "question", questionId: "wq-w4-012" },
    ],
    questionIds: ["wq-w4-010", "wq-w4-011", "wq-w4-012"],
    memorize: ["FL300, 100–150 kt, west to east"],
    sourceReferences: [MECH],
  },

  /* ================= w5 · clouds and lifting ================= */
  {
    id: "wl11-lifting-methods",
    unit: "w5",
    index: 11,
    title: "Four Ways to Lift Air",
    subtitle: "Nothing builds until something lifts",
    estimatedMinutes: 5,
    mapIcon: "wx-lifting",
    enablingObjectives: [],
    conceptIds: ["wx-lifting-methods"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Moisture alone builds nothing",
        line: "Air has to be lifted before it can cool to its dew point. There are exactly four ways that happens.",
      },
      {
        kind: "model",
        headline: "The four mechanisms",
        diagram: { id: "wx-lifting", props: { method: "none" } },
        bullets: [
          "FRONTAL: one air mass forces another up",
          "OROGRAPHIC: terrain does the work",
          "CONVERGENCE: air flows together and has nowhere to go but up",
          "THERMAL: heating from below",
        ],
      },
      {
        kind: "chain",
        headline: "The chain every one of them feeds",
        nodes: [
          { label: "A lifting mechanism acts", trend: "up" },
          { label: "The parcel rises and cools", trend: "up" },
          { label: "Temperature reaches the dew point", trend: "down" },
          { label: "Cloud forms", trend: "up", emphasis: true },
        ],
        footnote: "Only the first step differs between the four. Everything after it is identical.",
      },
      {
        kind: "manipulate",
        headline: "Four ways to make air rise",
        widget: "LiftingMethodPicker",
        line: "Pick a mechanism and see where the cloud forms, and where the turbulence goes.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Frontal · Orographic · Convergence · Thermal",
          "Lift → cool → saturate → cloud",
        ],
      },
      { kind: "question", questionId: "wq-w5-006" },
      { kind: "question", questionId: "wq-w5-007" },
      { kind: "question", questionId: "wcc-w5-010" },
    ],
    questionIds: ["wq-w5-006", "wq-w5-007", "wcc-w5-010"],
    memorize: ["Frontal, Orographic, Convergence, Thermal"],
    sourceReferences: [NOTES("WX 2: Mechanics")],
    explainerIds: ["wx-x-clouds"],
  },
  {
    id: "wl12-cloud-types",
    unit: "w5",
    index: 12,
    title: "Cloud Types",
    subtitle: "Four groups, and the two that matter most",
    estimatedMinutes: 6,
    mapIcon: "wx-cloud",
    enablingObjectives: [],
    conceptIds: [
      "wx-cloud-groups",
      "wx-special-clouds",
      "wx-precipitation-types",
      "wx-precipitation-forms",
    ],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "A cloud's name tells you what the air inside it is doing",
        line: "Group is altitude. Shape is stability. And nimbus means it is about to be unpleasant.",
      },
      {
        kind: "model",
        headline: "The four groups",
        diagram: { id: "wx-cloud-groups", props: { group: "none" } },
        bullets: [
          "Low, Middle, High and Special",
          "A cloud is defined by the altitude group it sits in",
          "Nimbo- or -nimbus means violent or heavy",
        ],
      },
      {
        kind: "compare",
        headline: "The two special clouds",
        line: "Both are heavy. Only one of them has thunder.",
        columns: ["Cumulonimbus", "Nimbostratus"],
        rows: [
          { label: "Shape", a: "Base low, tops high", b: "Thick, uniform, widespread" },
          { label: "Builds", a: "Upward", b: "DOWNWARD" },
          { label: "Turbulence", a: "Severe to extreme", b: "Moderate" },
          { label: "Also brings", a: "Hail, icing, lightning", b: "Heavy continuous rain — no thunder" },
        ],
      },
      {
        kind: "compare",
        headline: "Precipitation names the cloud",
        line: "Two of these identify the cloud type for you. One does not.",
        columns: ["Character", "From"],
        rows: [
          { label: "Shower", a: "Sudden start and stop, abrupt intensity changes", b: "Cumuliform" },
          { label: "Continuous", a: "Steady, gradual changes", b: "Stratiform" },
          { label: "Intermittent", a: "Starts and stops at least once an hour", b: "EITHER type" },
        ],
      },
      {
        kind: "compare",
        headline: "Which forms actually ice the aircraft",
        line: "Three of these are routinely got wrong.",
        columns: ["Form", "Structural icing?"],
        rows: [
          { label: "Freezing rain and freezing drizzle", a: "Freeze on impact with objects", b: "YES" },
          { label: "Hail or graupel", a: "Irregular lumps of ice from severe storms", b: "NO — but structural DAMAGE" },
          { label: "Ice pellets or sleet", a: "Rain that froze falling through cold air", b: "Only if mixed with super-cooled water" },
          { label: "Snow", a: "Ice crystals", b: "Wet snow YES · dry snow no" },
        ],
      },
      {
        kind: "manipulate",
        headline: "The group is set by altitude",
        widget: "CloudGroupPicker",
        line: "Pick a group and read off its prefix and what it is made of.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Low, Middle, High, Special",
          "Nimbus = violent or heavy",
          "Hail damages but does not ice · wet snow ices",
          "Nimbostratus: heavy, continuous, NO thunder",
          "Cumuliform → showers · Stratiform → continuous · Intermittent → either",
        ],
      },
      { kind: "question", questionId: "wq-w5-004" },
      { kind: "question", questionId: "wq-w5-008" },
      { kind: "question", questionId: "wq-w5-009" },
      { kind: "question", questionId: "wq-wg-011" },
      { kind: "question", questionId: "wq-wg-013" },
    ],
    questionIds: [
      "wq-w5-001", "wq-w5-002", "wq-w5-003", "wq-w5-004", "wq-w5-005",
      "wq-w5-008", "wq-w5-009",
      "wq-wg-011", "wq-wg-012", "wq-wg-013", "wq-wg-014",
    ],
    memorize: [
      "Nimbostratus has no thunder",
      "Cumuliform showers, stratiform continuous",
    ],
    sourceReferences: [MECH],
    labIds: ["wxlab-clouds"],
  },
];
