import type { Question, SourceReference } from "@/lib/types";

const L201 = (eo: string[]): SourceReference => ({
  document: "Principles of Gas Turbine/Reciprocating Operation",
  chapter: "Principles of Gas Turbine/Reciprocating Operation",
  eo,
});
const L202 = (eo: string[]): SourceReference => ({
  document: "Gas Turbine/Reciprocating Engines",
  chapter: "Gas Turbine/Reciprocating Engines",
  eo,
});
const L203 = (eo: string[]): SourceReference => ({
  document: "Compressor Stalls",
  chapter: "Compressor Stalls",
  eo,
});
const NOTES = (chapter: string): SourceReference => ({
  document: "Engines Condensed Notes",
  chapter,
});

/**
 * Assessment depth.
 *
 * Most Engines concepts carried a single question, which is enough to look
 * covered and not enough to be. Units e6–e7 were worst affected because they
 * come from the condensed notes and carry no enabling objectives, so nothing
 * in the EO matrix flagged them. These bring every concept to at least two.
 */
export const DEPTH_QUESTIONS: Question[] = [
  /* ================= e1 ================= */
  {
    id: "q-ed-001",
    type: "mcq",
    unit: "e1",
    conceptIds: ["e-static-pressure"],
    prompt: "Inside a gas generator, the word 'pressure' used on its own refers to",
    options: ["total pressure", "static pressure", "dynamic pressure", "ram pressure"],
    answer: 1,
    explanation:
      "Inside the engine, static pressure is simply called pressure and dynamic pressure is simply called velocity. Keeping that convention straight is what makes the station-by-station changes readable.",
    knowCold: "In the engine: pressure = static, velocity = dynamic.",
    difficulty: 2,
    source: L201(["1.1"]),
  },
  {
    id: "q-ed-002",
    type: "mcq",
    unit: "e1",
    conceptIds: ["e-dynamic-pressure"],
    prompt: "Dynamic pressure is the",
    options: [
      "potential of fluid molecules at rest",
      "kinetic energy of fluid molecules in motion",
      "sum of static and total pressure",
      "pressure measured perpendicular to the flow",
    ],
    answer: 1,
    explanation:
      "Molecules in motion carry kinetic energy, and that is dynamic pressure. Molecules at rest carry potential, and that is static pressure.",
    knowCold: "Dynamic = motion = kinetic energy.",
    difficulty: 1,
    source: L201(["1.1"]),
  },
  {
    id: "q-ed-003",
    type: "spotTheTrap",
    unit: "e1",
    conceptIds: ["e-compressibility"],
    prompt: '"Air is an incompressible fluid."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. Air IS compressible. What is true is that subsonic AIRFLOW is treated as relatively incompressible, and that flow becomes more compressible as it approaches supersonic speed.",
    knowCold: "Air is compressible; subsonic flow is treated as if it were not.",
    difficulty: 3,
    source: L201(["1.2", "1.3"]),
  },
  {
    id: "q-ed-004",
    type: "mcq",
    unit: "e1",
    conceptIds: ["e-subsonic-divergent"],
    prompt: "Subsonic air passing through a DIVERGENT duct experiences",
    options: [
      "velocity increase and pressure decrease",
      "velocity decrease and pressure increase",
      "velocity increase and pressure increase",
      "no change in either",
    ],
    answer: 1,
    explanation:
      "Divergent and subsonic means the duct is acting as a diffuser. That is why a subsonic inlet is divergent.",
    knowCold: "Subsonic + divergent = diffuser.",
    difficulty: 2,
    source: L201(["1.2"]),
  },
  {
    id: "q-ed-005",
    type: "mcq",
    unit: "e1",
    conceptIds: ["e-otto"],
    prompt: "The four events of the Otto cycle occur",
    options: [
      "simultaneously and continuously",
      "sequentially, one after another",
      "two at a time",
      "continuously in separate sections",
    ],
    answer: 1,
    explanation:
      "Intake, compression, combustion, exhaust — suck, squeeze, bang, blow — happen one after another in the same cylinder. In the Brayton cycle the same four events happen simultaneously and continuously in separate engine sections.",
    whyWrong:
      "Simultaneous and continuous in separate sections is the BRAYTON cycle, which is the whole distinction the exam is testing.",
    knowCold: "Otto is sequential. Brayton is simultaneous.",
    difficulty: 2,
    officialStyle: true,
    source: L201(["1.6"]),
  },
  {
    id: "q-ed-006",
    type: "connectChain",
    unit: "e1",
    conceptIds: ["e-otto"],
    prompt: "Order the four events of the Otto cycle.",
    trigger: "The piston begins its cycle",
    steps: ["Intake", "Compression", "Combustion", "Exhaust"],
    explanation: "Suck, squeeze, bang, blow.",
    knowCold: "Suck, squeeze, bang, blow.",
    difficulty: 1,
    source: L201(["1.6"]),
  },

  /* ================= e2 ================= */
  {
    id: "q-ed-007",
    type: "mcq",
    unit: "e2",
    conceptIds: ["e-thrust-equation"],
    prompt: "Thrust is fundamentally",
    options: [
      "mass times acceleration",
      "pressure times area",
      "velocity times density",
      "work divided by time",
    ],
    answer: 0,
    explanation:
      "Thrust results from the pressure, temperature and velocity changes as airflow passes through the engine, and it reduces to mass times acceleration. Raising either term raises thrust.",
    knowCold: "T = m × a.",
    difficulty: 1,
    source: L201(["1.8"]),
  },
  {
    id: "q-ed-008",
    type: "mcq",
    unit: "e2",
    conceptIds: ["e-torquemeter"],
    prompt: "Which gauge indicates power available on a propeller-driven aircraft?",
    options: ["EPR", "Torquemeter", "Tachometer", "TIT"],
    answer: 1,
    explanation:
      "The torquemeter indicates shaft horsepower available to drive the propeller or rotor. EPR is the turbojet and turbofan equivalent.",
    whyWrong: "EPR is for turbojet and turbofan. The tachometer monitors RPM, not power.",
    knowCold: "Torquemeter for props. EPR for jets.",
    difficulty: 2,
    officialStyle: true,
    source: L201(["1.15"]),
  },
  {
    id: "q-ed-009",
    type: "mcq",
    unit: "e2",
    conceptIds: ["e-tachometer"],
    prompt: "The tachometer",
    options: [
      "measures thrust directly",
      "indicates engine rotation speed in percent RPM and monitors only",
      "indicates shaft horsepower available",
      "measures turbine inlet temperature",
    ],
    answer: 1,
    explanation:
      "It is the most commonly used cockpit gauge and gives a quick assessment of the energy the engine is producing — but it is a monitoring instrument, not a thrust measurement.",
    knowCold: "The tachometer monitors. It does not measure thrust.",
    difficulty: 2,
    source: L201(["1.15"]),
  },

  /* ================= e3 ================= */
  {
    id: "q-ed-010",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-divided-entrance"],
    prompt: "The main disadvantage of a divided entrance inlet duct is",
    options: [
      "greater friction loss",
      "more inlet air turbulence",
      "the pilot must sit higher",
      "longer ducting",
    ],
    answer: 1,
    explanation:
      "Divided entrance ducts are shorter, let pilots sit lower and produce less friction loss. What they cost is turbulence.",
    whyWrong:
      "Friction loss and duct length are advantages of the divided entrance, not disadvantages.",
    knowCold: "Divided entrance: less friction, more turbulence.",
    difficulty: 3,
    source: L202(["2.1"]),
  },
  {
    id: "q-ed-011",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-inlet-geometry"],
    prompt: "A SUPERSONIC inlet duct is",
    options: ["divergent", "convergent", "convergent/divergent", "of constant area"],
    answer: 2,
    explanation:
      "It must first slow the flow below supersonic in the convergent section, then behave like a subsonic inlet — further reducing velocity and raising pressure — in the divergent section. A subsonic inlet is simply divergent.",
    knowCold: "Subsonic inlet: divergent. Supersonic inlet: C/D.",
    difficulty: 3,
    officialStyle: true,
    source: L202(["2.1"]),
  },
  {
    id: "q-ed-012",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-variable-geometry-inlet"],
    prompt: "A variable geometry inlet changes shape with speed in order to",
    options: [
      "act as a nozzle at supersonic speeds",
      "keep acting as a diffuser throughout the speed range",
      "reduce the engine's frontal area",
      "eliminate the need for a compressor",
    ],
    answer: 1,
    explanation:
      "Mechanical ramps, cones or wedges make it divergent at subsonic speeds and convergent/divergent at supersonic speeds, so it always delivers slow high-pressure air to the compressor.",
    knowCold: "The inlet is always a diffuser. The shape changes to keep it one.",
    difficulty: 3,
    source: L202(["2.1"]),
  },
  {
    id: "q-ed-013",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-centrifugal-compressor"],
    prompt: "The three main components of a centrifugal flow compressor are",
    options: [
      "rotor, stator, manifold",
      "impeller, diffuser, manifold",
      "impeller, rotor, diffuser",
      "inlet guide vanes, impeller, stator",
    ],
    answer: 1,
    explanation:
      "The impeller accelerates air outward, the diffuser converts that velocity to pressure, and the manifold routes air to the combustion chambers.",
    knowCold: "Impeller, diffuser, manifold.",
    difficulty: 2,
    officialStyle: true,
    source: L202(["2.2"]),
  },
  {
    id: "q-ed-014",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-centrifugal-tradeoffs"],
    prompt: "A disadvantage of the centrifugal flow compressor is",
    options: [
      "poor power output across the RPM range",
      "large frontal area, and impracticality for multiple stages",
      "low pressure increase per stage",
      "high cost and fragility",
    ],
    answer: 1,
    explanation:
      "It is rugged, cheap, gives good power output over a large RPM range and a high pressure increase per stage. The costs are drag from the frontal area and the fact that stages cannot practically be stacked.",
    knowCold: "Centrifugal: great per stage, bad at stacking.",
    difficulty: 3,
    source: L202(["2.2"]),
  },
  {
    id: "q-ed-015",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-axial-tradeoffs"],
    prompt: "Which is a disadvantage of the AXIAL flow compressor?",
    options: [
      "Large frontal area",
      "Low peak efficiency",
      "Compressor stalls are more likely at low airspeeds",
      "Low pressure rise across the whole compressor",
    ],
    answer: 2,
    explanation:
      "Axial gives high peak efficiencies, low drag from a small frontal area and straight-through airflow. It is stall-prone at low airspeed, costly to manufacture, and efficient only over a narrow RPM range.",
    whyWrong: "Large frontal area is the CENTRIFUGAL disadvantage.",
    knowCold: "Axial stalls; centrifugal is rugged.",
    difficulty: 3,
    officialStyle: true,
    source: L202(["2.2"]),
  },
  {
    id: "q-ed-016",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-axial-centrifugal"],
    prompt: "The T-6 compressor consists of",
    options: [
      "a single centrifugal impeller only",
      "four axial stages and one centrifugal impeller",
      "eight axial stages",
      "two centrifugal impellers in series",
    ],
    answer: 1,
    explanation:
      "An axial-centrifugal arrangement: straight-through airflow from the axial stages plus a large pressure increase through the impeller. Well suited to smaller mission aircraft, but not to supersonic airflow.",
    knowCold: "T-6: four axial stages plus one impeller.",
    difficulty: 2,
    source: L202(["2.2"]),
  },
  {
    id: "q-ed-017",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-guide-vanes"],
    prompt: "Inlet guide vanes",
    options: [
      "remove swirl before the first stage rotor",
      "impart swirl in the direction of compressor rotation, reducing drag on the first stage rotor",
      "convert velocity to pressure ahead of the burner",
      "straighten airflow before the diffuser",
    ],
    answer: 1,
    explanation:
      "Inlet guide vanes add swirl going in. Exit or straightening vanes are the last stator set, removing rotational turbulence to prepare airflow for the diffuser.",
    whyWrong: "Straightening the flow before the diffuser is the EXIT vanes' job.",
    knowCold: "Inlet vanes add swirl. Exit vanes remove it.",
    difficulty: 3,
    source: L202(["2.2"]),
  },
  {
    id: "q-ed-018",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-compressor-diffuser"],
    prompt: "The point of highest pressure in the engine is at the",
    options: [
      "last compressor stage",
      "diffuser",
      "burner",
      "first turbine stage",
    ],
    answer: 1,
    explanation:
      "The diffuser is divergent, decreasing velocity and giving a final pressure increase before the burner. It is the point of highest compression in the engine.",
    whyWrong:
      "The last compressor stage is the intuitive answer, and it is one station too early.",
    knowCold: "Highest pressure is at the diffuser.",
    difficulty: 3,
    officialStyle: true,
    source: L202(["2.2"]),
  },

  /* ================= e4 ================= */
  {
    id: "q-ed-019",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-burner-purpose"],
    prompt: "One purpose of the burner section is to deliver gases to the turbine at a temperature that",
    options: [
      "is as high as the fuel will allow",
      "will not exceed turbine blade limits",
      "equals compressor discharge temperature",
      "prevents any thermal expansion of the blades",
    ],
    answer: 1,
    explanation:
      "It must also mix fuel and air properly to ensure combustion, and add enough heat energy to accelerate the gases and produce the desired thrust.",
    knowCold: "Mix, stay under blade limits, add enough energy.",
    difficulty: 2,
    source: L202(["2.3"]),
  },
  {
    id: "q-ed-020",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-burner-criteria"],
    prompt: "Which is a combustion chamber design criterion?",
    options: [
      "Maximise the pressure decrease across the burner",
      "Complete burning before gases enter the turbine section",
      "Allow the flame to blow out at high altitude",
      "Maximise chamber volume regardless of pressure loss",
    ],
    answer: 1,
    explanation:
      "The four criteria are: minimise pressure decrease, achieve combustion efficiency, prevent flame blowout, and complete burning before the turbine.",
    knowCold: "Finish burning before the turbine.",
    difficulty: 2,
    source: L202(["2.4"]),
  },
  {
    id: "q-ed-021",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-can-chamber"],
    prompt: "A malfunction in a CAN combustion chamber can cause",
    options: [
      "cold spots on the turbine",
      "an immediate compressor stall",
      "loss of all bleed air",
      "afterburner ignition",
    ],
    answer: 0,
    explanation:
      "Cans are used with older centrifugal compressor engines. Their advantages are strength, durability and ease of maintenance; the disadvantages are poor use of chamber space, greater pressure loss, and cold spots on the turbine when one malfunctions.",
    knowCold: "Can chambers risk cold spots.",
    difficulty: 3,
    source: L202(["2.4"]),
  },
  {
    id: "q-ed-022",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-can-annular-chamber"],
    prompt: "The primary disadvantage of the can-annular combustion chamber is",
    options: [
      "poor thermodynamics",
      "high cost of procurement and replacement",
      "cold spots from clogged nozzles",
      "low structural stability",
    ],
    answer: 1,
    explanation:
      "Can-annular ELIMINATES the cold spot problem and offers ease of maintenance with good thermodynamics, greater structural stability and lower pressure loss. Cost is what it trades away.",
    whyWrong: "Cold spots are the CAN chamber's problem, which can-annular was designed to solve.",
    knowCold: "Can-annular: better in every way except cost.",
    difficulty: 3,
    source: L202(["2.4"]),
  },
  {
    id: "q-ed-023",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-turbine-construction"],
    prompt: "In the turbine section, the order of components is",
    options: [
      "rotor then stator",
      "stationary stator then rotor",
      "two rotors then a stator",
      "diffuser then rotor",
    ],
    answer: 1,
    explanation:
      "A stationary stator followed by a rotor — the reverse of the compressor's rotor-then-stator arrangement. Turbine rotors connect to the compressor by a drive shaft.",
    whyWrong:
      "The compressor is rotor-then-stator. The turbine reverses it, and that reversal is the question.",
    knowCold: "Compressor: rotor then stator. Turbine: stator then rotor.",
    difficulty: 3,
    officialStyle: true,
    source: L202(["2.5"]),
  },
  {
    id: "q-ed-024",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-creep"],
    prompt: "Creep is",
    options: [
      "the gradual loss of compressor efficiency over time",
      "abnormal elongation of turbine blades due to overheating",
      "slow leakage of oil past a seal",
      "the drift of engine RPM at a fixed throttle",
    ],
    answer: 1,
    explanation:
      "Excessive temperature and speed at the most stressed part of the engine elongate the blades, and the deformation can be permanent.",
    knowCold: "Creep: blades stretch from heat, permanently.",
    difficulty: 2,
    officialStyle: true,
    source: L202(["2.6"]),
  },
  {
    id: "q-ed-025",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-fir-tree"],
    prompt: "The fir tree method of attaching turbine blades provides for",
    options: [
      "easier blade replacement in the field",
      "normal expansion of the blades due to heating",
      "a reduction in blade weight",
      "electrical grounding of the blade",
    ],
    answer: 1,
    explanation:
      "The blades run extremely hot and must be allowed to expand. The fir tree root gives them room to do so without loosening.",
    knowCold: "Fir tree allows thermal expansion.",
    difficulty: 2,
    source: L202(["2.6"]),
  },
  {
    id: "q-ed-026",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-exhaust-nozzles"],
    prompt: "A convergent/divergent exhaust nozzle is used on supersonic aircraft because",
    options: [
      "the convergent section alone cannot accelerate the gases",
      "the divergent section allows further acceleration beyond the speed of sound",
      "it reduces exhaust temperature",
      "it eliminates the need for an afterburner",
    ],
    answer: 1,
    explanation:
      "The convergent section accelerates gases toward the speed of sound; the divergent section then takes them supersonic — the same inversion that governs supersonic inlets, running the other way.",
    knowCold: "C/D nozzle: convergent to sonic, divergent beyond.",
    difficulty: 3,
    source: L202(["2.7"]),
  },
  {
    id: "q-ed-027",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-afterburner"],
    prompt: "Using the afterburner can increase thrust by",
    options: ["about 10%", "about 25%", "50% or more", "about 200%"],
    answer: 2,
    explanation:
      "It ignites secondary and bypass air to increase maximum thrust available for short periods, such as takeoff.",
    knowCold: "Afterburner: 50% or more, briefly.",
    difficulty: 2,
    source: L202(["2.8"]),
  },
  {
    id: "q-ed-028",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-afterburner-ignition"],
    prompt: "Hot streak ignition lights the afterburner by",
    options: [
      "using a spark igniter in the afterburner duct",
      "maintaining a continuous pilot light",
      "sending additional ignited fuel from the combustion chamber streaking through the turbine",
      "raising turbine inlet temperature until autoignition occurs",
    ],
    answer: 2,
    explanation:
      "Spark ignition is the most common method; torch ignition uses a pilot light. Hot streak is the one that sends flame through the turbine.",
    knowCold: "Spark, torch, hot streak.",
    difficulty: 3,
    source: L202(["2.8"]),
  },
  {
    id: "q-ed-029",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-afterburner-components"],
    prompt: "Screech liners in an afterburner",
    options: [
      "introduce fuel to the exhaust section",
      "mix fuel and air and stabilise the flame",
      "reduce pressure fluctuations and vibration, acting like a shock absorber",
      "vary the nozzle area",
    ],
    answer: 2,
    explanation:
      "Spray bars introduce the fuel, flame holders stabilise the flame, and the variable exhaust nozzle opens and closes with a leaf or iris arrangement.",
    knowCold: "Spray bars, flame holders, screech liners, variable nozzle.",
    difficulty: 3,
    source: L202(["2.8"]),
  },
  {
    id: "q-ed-030",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-recip-components"],
    prompt: "Which of the following is a basic component of a reciprocating engine?",
    options: ["Impeller", "Crankshaft", "Stator", "Diffuser"],
    answer: 1,
    explanation:
      "The basic components are the crankcase, cylinders, pistons, connecting rods, valves, valve-operating mechanism and crankshaft. Impellers, stators and diffusers belong to gas turbines.",
    knowCold: "Crankcase, cylinders, pistons, rods, valves, valve gear, crankshaft.",
    difficulty: 2,
    officialStyle: true,
    source: L202(["2.9"]),
  },
  {
    id: "q-ed-031",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-recip-components"],
    prompt: "In a reciprocating engine, the component that converts the pistons' linear motion into rotation is the",
    options: ["camshaft", "connecting rod", "crankshaft", "crankcase"],
    answer: 2,
    explanation:
      "The connecting rods link pistons to the crankshaft, and the crankshaft is what turns that reciprocating motion into the rotation that drives the propeller.",
    knowCold: "The crankshaft converts linear to rotary.",
    difficulty: 2,
    source: L202(["2.9"]),
  },

  /* ================= e5 ================= */
  {
    id: "q-ed-032",
    type: "mcq",
    unit: "e5",
    conceptIds: ["e-compressor-relative-wind"],
    prompt: "Relative wind inside the compressor is formed by combining",
    options: [
      "inlet airflow and ambient temperature",
      "inlet airflow and compressor RPM",
      "compressor RPM and exhaust velocity",
      "aircraft airspeed and altitude",
    ],
    answer: 1,
    explanation:
      "Which is why any change to EITHER — a disturbed inlet or a change in RPM — changes the blade's angle of attack and can stall it.",
    knowCold: "Inlet airflow + RPM = compressor relative wind.",
    difficulty: 2,
    officialStyle: true,
    source: L203(["3.1"]),
  },
  {
    id: "q-ed-033",
    type: "mcq",
    unit: "e5",
    conceptIds: ["e-stall-definition"],
    prompt: "A compressor stall occurs because",
    options: [
      "the engine runs out of fuel",
      "airflow over a rotor or stator airfoil breaks away due to excessive angle of attack",
      "turbine inlet temperature exceeds limits",
      "the compressor exceeds its maximum RPM",
    ],
    answer: 1,
    explanation:
      "Rotors and stators are airfoils and stall for exactly the same reason a wing does. A compressor stall could lead to engine flameout.",
    knowCold: "Compressor blades are airfoils, and they stall on AOA.",
    difficulty: 2,
    source: L203(["3.2"]),
  },

  /* ================= e6 · engine types ================= */
  {
    id: "q-ed-034",
    type: "mcq",
    unit: "e6",
    conceptIds: ["e-turbojet"],
    prompt: "A disadvantage of the turbojet is",
    options: [
      "heaviest specific weight",
      "low propulsive efficiency at low airspeeds and high TSFC",
      "inability to fly at high altitude",
      "poor high-end performance",
    ],
    answer: 1,
    explanation:
      "The turbojet flies higher and faster than the other types, has the best high-end performance and the lightest specific weight. What it costs is low-speed efficiency, fuel consumption and takeoff distance.",
    knowCold: "Turbojet: best up high and fast, worst down low.",
    difficulty: 3,
    source: NOTES("Engine Types"),
  },
  {
    id: "q-ed-035",
    type: "mcq",
    unit: "e6",
    conceptIds: ["e-turboprop-torquemeter"],
    prompt: "The turboprop torquemeter's REFERENCE shaft",
    options: [
      "carries the load from engine to propeller",
      "provides a stationary reference against which twist is measured",
      "drives the reduction gear box",
      "rotates opposite the inner shaft",
    ],
    answer: 1,
    explanation:
      "The inner torque shaft carries the load from engine to propeller; the outer reference shaft stays stationary so the twist between them can be measured as power output.",
    knowCold: "Inner shaft carries load, outer shaft is the reference.",
    difficulty: 3,
    source: NOTES("Engine Types"),
  },
  {
    id: "q-ed-036",
    type: "mcq",
    unit: "e6",
    conceptIds: ["e-propeller-ranges"],
    prompt: "In the BETA range, the power control lever is",
    options: [
      "controlling the fuel control unit only, with the governor setting blade angle",
      "mechanically connected to the FCU and the pitch change assembly",
      "inoperative",
      "limited to flight idle and above",
    ],
    answer: 1,
    explanation:
      "Beta is the ground-only range, from idle to max reverse, with a direct mechanical link. Alpha is the flight range, where the PCL drives the FCU and the propeller governor sets blade angle.",
    whyWrong: "The first option describes ALPHA, the flight range.",
    knowCold: "Alpha flies. Beta is ground only, and it is mechanical.",
    difficulty: 3,
    officialStyle: true,
    source: NOTES("Engine Types"),
  },
  {
    id: "q-ed-037",
    type: "mcq",
    unit: "e6",
    conceptIds: ["e-turboshaft"],
    prompt: "How much propulsive thrust does a turboshaft derive from its exhaust gases?",
    options: ["None", "About 10%", "About 25%", "About 50%"],
    answer: 0,
    explanation:
      "All propulsive energy comes from rotor rotation. A turboprop, by contrast, still gets about 10% of its thrust from the exhaust.",
    whyWrong: "10% is the TURBOPROP figure.",
    knowCold: "Turboshaft: zero from exhaust. Turboprop: 10%.",
    difficulty: 3,
    source: NOTES("Engine Types"),
  },
  {
    id: "q-ed-038",
    type: "mcq",
    unit: "e6",
    conceptIds: ["e-recip-propulsion"],
    prompt: "In a reciprocating engine installation, blade angle and propeller speed are controlled by",
    options: ["the throttle directly", "a governor", "the reduction gear box", "the crankshaft"],
    answer: 1,
    explanation:
      "All thrust comes from a propeller driven by crankshaft rotation, either directly or through a reduction gear box, and a governor controls blade angle and propeller speed.",
    knowCold: "A governor sets blade angle and speed.",
    difficulty: 2,
    source: NOTES("Engine Types"),
  },

  /* ================= e7 · systems ================= */
  {
    id: "q-ed-039",
    type: "connectChain",
    unit: "e7",
    conceptIds: ["e-fuel-path"],
    prompt: "Trace fuel from the tank to the nozzles.",
    trigger: "Fuel leaves the tank",
    steps: [
      "Boost pump",
      "Low pressure filter",
      "Engine-driven fuel pump",
      "Fuel control unit",
      "Pressurizing and dump valve",
      "Primary and secondary manifolds",
    ],
    explanation: "From the manifolds it reaches the fuel nozzles and the burner.",
    knowCold: "Tank, boost, filter, pump, FCU, P&D valve, manifolds, nozzles.",
    difficulty: 3,
    source: NOTES("Fuel System"),
  },
  {
    id: "q-ed-040",
    type: "mcq",
    unit: "e7",
    conceptIds: ["e-boost-pump"],
    prompt: "A critical function of the boost pump is",
    options: [
      "raising fuel to burner pressure",
      "preventing aeration of the fuel",
      "metering fuel to the nozzles",
      "filtering contaminants",
    ],
    answer: 1,
    explanation:
      "Aeration can result from the rapid pressure change during a climb. The boost pump is submerged in the tank and ensures adequate supply to the engine-driven pump.",
    whyWrong: "Metering is the FCU's job, and filtering is the low pressure filter's.",
    knowCold: "The boost pump prevents aeration.",
    difficulty: 3,
    source: NOTES("Fuel System"),
  },
  {
    id: "q-ed-041",
    type: "mcq",
    unit: "e7",
    conceptIds: ["e-fuel-manifolds"],
    prompt: "The PRIMARY fuel manifold is smaller in order to",
    options: [
      "reduce weight",
      "let fuel reach high pressure for good atomization during starting and altitude idling",
      "limit total fuel flow at high power",
      "keep the secondary manifold cool",
    ],
    answer: 1,
    explanation:
      "The secondary manifold comes in once engine RPM raises fuel pressure to a predetermined level.",
    knowCold: "Primary is small so it atomizes well when flow is low.",
    difficulty: 3,
    source: NOTES("Fuel System"),
  },
  {
    id: "q-ed-042",
    type: "mcq",
    unit: "e7",
    conceptIds: ["e-thrust-ratings"],
    prompt: "Which thrust rating is NOT based on turbine temperature limitations?",
    options: ["Normal", "Military", "Combat", "All are"],
    answer: 2,
    explanation:
      "Combat thrust uses the afterburner, which adds heat downstream of the turbine. Normal is the maximum continuous turbine temperature with no time limit; military is maximum turbine temperature for roughly 30 minutes.",
    knowCold: "Normal unlimited, military ~30 min, combat is afterburner.",
    difficulty: 3,
    source: NOTES("Fuel System"),
  },
  {
    id: "q-ed-043",
    type: "mcq",
    unit: "e7",
    conceptIds: ["e-oil-sumps"],
    prompt: "An advantage of a DRY sump over a wet sump is",
    options: [
      "simpler plumbing",
      "better cooling, a more streamlined engine and larger oil quantities",
      "oil is stored inside the engine where it stays warm",
      "it needs no scavenge system",
    ],
    answer: 1,
    explanation:
      "A wet sump stores oil internally, which makes cooling difficult and cannot adapt to unusual flight attitudes.",
    knowCold: "Dry sump: external tank, better cooling, more oil.",
    difficulty: 2,
    source: NOTES("Oil System"),
  },
  {
    id: "q-ed-044",
    type: "mcq",
    unit: "e7",
    conceptIds: ["e-oil-subsystems"],
    prompt: "Which oil subsystem uses compressor bleed air?",
    options: ["Pressure", "Scavenge", "Breather", "All three"],
    answer: 2,
    explanation:
      "The breather subsystem pressurizes the tank and engine to minimise leakage and ensure proper spray patterns. Pressure supplies oil; scavenge returns it via the coolers.",
    knowCold: "Pressure, scavenge, breather — the breather uses bleed air.",
    difficulty: 3,
    source: NOTES("Oil System"),
  },
  {
    id: "q-ed-045",
    type: "mcq",
    unit: "e7",
    conceptIds: ["e-oil-pump"],
    prompt: "The scavenge side of the oil pump has GREATER capacity than the pressure side in order to",
    options: [
      "increase oil pressure at high RPM",
      "prevent back pressure and accumulation of oil in the bearing sump cavities",
      "compensate for oil lost to combustion",
      "allow a smaller oil tank",
    ],
    answer: 1,
    explanation:
      "If scavenge could not out-pace supply, oil would pool in the sumps and back up into the bearings.",
    knowCold: "Scavenge capacity exceeds pressure capacity, deliberately.",
    difficulty: 3,
    source: NOTES("Oil System"),
  },
  {
    id: "q-ed-046",
    type: "mcq",
    unit: "e7",
    conceptIds: ["e-oil-contamination"],
    prompt: "The most common cause of oil contamination is",
    options: [
      "coking",
      "metal particles from metal-to-metal contact",
      "foreign objects such as sand and dirt",
      "storing synthetic oil too long",
    ],
    answer: 1,
    explanation:
      "All four are listed causes. Metal particles are the most common, which is why the magnetic chip detector exists.",
    knowCold: "Metal particles first, then coking, foreign objects, old oil.",
    difficulty: 2,
    officialStyle: true,
    source: NOTES("Oil System"),
  },
  {
    id: "q-ed-047",
    type: "mcq",
    unit: "e7",
    conceptIds: ["e-chip-detector"],
    prompt: "A magnetic chip detector is located in the",
    options: [
      "pressure oil path before the bearings",
      "scavenge oil path",
      "breather line",
      "fuel return line",
    ],
    answer: 1,
    explanation:
      "It sits where oil is coming BACK from the bearings, so it can collect the metal particles those bearings are shedding, and illuminates a cockpit warning light once enough accumulate.",
    knowCold: "Chip detector sits in the scavenge path.",
    difficulty: 3,
    source: NOTES("Oil System"),
  },
  {
    id: "q-ed-048",
    type: "mcq",
    unit: "e7",
    conceptIds: ["e-viscosity"],
    prompt: "Squeeze film is",
    options: [
      "the oil layer scraped from the cylinder wall",
      "a thin film of lubricant preventing metal-to-metal contact and dissipating heat",
      "the foam produced by aerated oil",
      "carbon deposited by oil evaporation",
    ],
    answer: 1,
    explanation:
      "Proper viscosity is required to form it, and viscosity is inversely related to temperature — hotter oil is thinner.",
    knowCold: "Squeeze film keeps metal off metal. Viscosity forms it.",
    difficulty: 2,
    source: NOTES("Oil System"),
  },
  {
    id: "q-ed-049",
    type: "mcq",
    unit: "e7",
    conceptIds: ["e-start-sequence"],
    prompt: "During a normal start, fuel flows after engine RPM reaches approximately",
    options: ["10%", "20%", "30%", "50%"],
    answer: 2,
    explanation:
      "The starter engages until the engine attains self-accelerating speed, fuel flows at about 30% RPM, and ignition occurs once airflow is sufficient to support combustion.",
    knowCold: "Starter, 30% RPM, fuel, ignition.",
    difficulty: 2,
    officialStyle: true,
    source: NOTES("Starting"),
  },
  {
    id: "q-ed-050",
    type: "mcq",
    unit: "e7",
    conceptIds: ["e-starters"],
    prompt: "Larger gas turbine engines typically use",
    options: [
      "a DC electric motor starter",
      "an air turbine starter",
      "a hand crank",
      "hot streak ignition",
    ],
    answer: 1,
    explanation:
      "A small geared air turbine accelerates the compressor. DC electric motor starters, drawing on the battery, are used on smaller engines.",
    knowCold: "Small engines: DC motor. Large engines: air turbine.",
    difficulty: 2,
    source: NOTES("Starting"),
  },
  {
    id: "q-ed-051",
    type: "mcq",
    unit: "e7",
    conceptIds: ["e-igniters"],
    prompt: "The CONSTRAINED-gap igniter differs from the annular-gap igniter in that it",
    options: [
      "protrudes further into the chamber",
      "extends the spark beyond the face of the chamber liner and runs cooler",
      "requires no electrical power",
      "is used only for afterburner ignition",
    ],
    answer: 1,
    explanation:
      "The annular-gap igniter is the most common and protrudes into the chamber to provide an effective spark.",
    knowCold: "Annular protrudes. Constrained stays flush and runs cooler.",
    difficulty: 3,
    source: NOTES("Starting"),
  },
  {
    id: "q-ed-052",
    type: "mcq",
    unit: "e7",
    conceptIds: ["e-bleed-air"],
    prompt: "Which of the following is powered by compressor BLEED AIR?",
    options: [
      "The tachometer",
      "The hydraulic pumps",
      "Engine anti-icing",
      "The alternator",
    ],
    answer: 2,
    explanation:
      "Bleed air powers environmental systems, cabin pressurization and engine anti-icing. The tachometer, hydraulic pumps and alternator are mechanically driven accessories off the accessory gear box.",
    knowCold: "Bleed air: environmental, pressurization, anti-ice.",
    difficulty: 3,
    source: NOTES("Systems"),
  },
  {
    id: "q-ed-053",
    type: "mcq",
    unit: "e7",
    conceptIds: ["e-pascal"],
    prompt:
      "A hydraulic system multiplies the input force by two. The output displacement is",
    options: [
      "twice the input",
      "half the input",
      "the same as the input",
      "four times the input",
    ],
    answer: 1,
    explanation:
      "Linear displacement is inversely proportional to the multiplied force. Force is bought with distance; the energy does not come free.",
    knowCold: "Double the force, halve the travel.",
    difficulty: 3,
    officialStyle: true,
    source: NOTES("Hydraulics"),
  },
  {
    id: "q-ed-054",
    type: "mcq",
    unit: "e7",
    conceptIds: ["e-hydraulic-pumps"],
    prompt: "Which hydraulic pump must incorporate a pressure regulator or unloader valve?",
    options: [
      "The hand pump",
      "The variable displacement power pump",
      "The constant displacement power pump",
      "None of them",
    ],
    answer: 2,
    explanation:
      "It delivers steady flow regardless of system pressure, so something has to relieve that flow when the system does not need it. The variable displacement pump regulates volume to demand and needs no such valve.",
    knowCold: "Constant displacement needs the unloader valve.",
    difficulty: 3,
    source: NOTES("Hydraulics"),
  },
  {
    id: "q-ed-055",
    type: "mcq",
    unit: "e7",
    conceptIds: ["e-accumulator"],
    prompt: "In a hydraulic accumulator, the compressed air or nitrogen is separated from the fluid by",
    options: ["a check valve", "a diaphragm", "a pressure relief valve", "an actuator"],
    answer: 1,
    explanation:
      "It acts as a shock absorber, provides pressure for one-time emergency use, supports pressure during peak operation, and with the check valve maintains system pressure during shutdown.",
    knowCold: "A diaphragm separates gas from fluid.",
    difficulty: 2,
    source: NOTES("Hydraulics"),
  },
  {
    id: "q-ed-056",
    type: "mcq",
    unit: "e7",
    conceptIds: ["e-hydraulic-components"],
    prompt: "The component that ensures a leak does not deplete the whole hydraulic system is the",
    options: ["check valve", "pressure relief valve", "hydraulic fuse", "selector control valve"],
    answer: 2,
    explanation:
      "The check valve prevents backflow, the relief valve stops pressure bursting seals, the selector valve directs flow, and the actuator converts fluid power into motion.",
    knowCold: "The fuse contains a leak.",
    difficulty: 3,
    source: NOTES("Hydraulics"),
  },
  {
    id: "q-ed-057",
    type: "mcq",
    unit: "e7",
    conceptIds: ["e-ac-dc"],
    prompt: "Alternating current is preferred in aircraft primarily because it",
    options: [
      "is simpler to generate",
      "requires lower current loads, permitting lighter wiring and saving weight",
      "needs no conversion for any load",
      "cannot be interrupted by a bus failure",
    ],
    answer: 1,
    explanation:
      "Direct current uses straight line voltage with heavier components and increased maintenance. AC alternates equally either side of base voltage.",
    knowCold: "AC saves weight through lighter wiring.",
    difficulty: 2,
    source: NOTES("Electrical"),
  },
  {
    id: "q-ed-058",
    type: "mcq",
    unit: "e7",
    conceptIds: ["e-power-sources"],
    prompt: "A transformer rectifier converts",
    options: ["DC to AC", "AC to DC", "AC to a higher AC voltage", "DC to a higher DC voltage"],
    answer: 1,
    explanation:
      "The INVERTER is the one that goes DC to AC. The exam routinely swaps them.",
    whyWrong: "DC to AC is the inverter.",
    knowCold: "Rectifier: AC → DC. Inverter: DC → AC.",
    difficulty: 3,
    officialStyle: true,
    source: NOTES("Electrical"),
  },
  {
    id: "q-ed-059",
    type: "mcq",
    unit: "e7",
    conceptIds: ["e-csd"],
    prompt: "A Constant Speed Drive exists because",
    options: [
      "the generator needs a constant speed input while engine RPM varies",
      "the engine needs a constant load",
      "the battery must be charged at a fixed rate",
      "the accessory gear box cannot handle variable torque",
    ],
    answer: 0,
    explanation:
      "It is a hydro-mechanical linkage between engine and generator that converts the engine's variable RPM into the constant speed output the generator requires.",
    knowCold: "CSD: variable engine RPM in, constant generator speed out.",
    difficulty: 2,
    source: NOTES("Electrical"),
  },
  {
    id: "q-ed-060",
    type: "mcq",
    unit: "e7",
    conceptIds: ["e-buses"],
    prompt: "Cabin lighting would be supplied by which bus?",
    options: ["Essential", "Primary", "Monitor or secondary", "Starter"],
    answer: 2,
    explanation:
      "Essential supplies equipment required for flight safety, primary supplies mission equipment, monitor or secondary supplies convenience circuits, and the starter bus supplies the starter circuit.",
    knowCold: "Essential = safety, primary = mission, monitor = convenience.",
    difficulty: 2,
    officialStyle: true,
    source: NOTES("Electrical"),
  },
];
