import type { Question, SourceReference } from "@/lib/types";

const L201 = (eo: string[]): SourceReference => ({
  document: "Principles of Gas Turbine/Reciprocating Operation",
  chapter: "Principles of Gas Turbine/Reciprocating Operation",
  eo,
});

/**
 * Unit e1 — Principles of Operation.
 *
 * The distractors are built from the confusions the block actually creates:
 * pressure/velocity naming inside the engine, nozzle and diffuser defined by
 * shape rather than by effect, and above all the subsonic/supersonic reversal.
 */
export const E1_QUESTIONS: Question[] = [
  {
    id: "eq-e1-001",
    type: "mcq",
    unit: "e1",
    conceptIds: ["e-static-pressure", "e-dynamic-pressure"],
    prompt: "Within a gas generator, the terms 'pressure' and 'velocity' refer respectively to",
    options: [
      "total pressure and static pressure",
      "static pressure and dynamic pressure",
      "dynamic pressure and static pressure",
      "ram pressure and total pressure",
    ],
    answer: 1,
    explanation:
      "Static pressure — the potential of molecules at rest — is simply called pressure inside the engine. Dynamic pressure, the kinetic energy of molecules in motion, is simply called velocity.",
    whyWrong:
      "Reversing them is the common slip: velocity is the energy of MOTION, so it is the dynamic term.",
    knowCold: "In the engine: pressure = static, velocity = dynamic.",
    difficulty: 1,
    officialStyle: true,
    source: L201(["1.1"]),
  },
  {
    id: "eq-e1-002",
    type: "mcq",
    unit: "e1",
    conceptIds: ["e-total-pressure"],
    prompt: "Total pressure is",
    options: [
      "static pressure minus dynamic pressure",
      "the sum of static pressure and dynamic pressure",
      "always equal to static pressure",
      "the pressure measured at the exhaust nozzle",
    ],
    answer: 1,
    explanation:
      "Total pressure is the sum of static and dynamic pressure. As static pressure decreases, dynamic pressure increases, keeping total pressure the same.",
    knowCold: "Total = static + dynamic.",
    difficulty: 1,
    officialStyle: true,
    source: L201(["1.1"]),
  },
  {
    id: "esl-e1-003",
    type: "sliderPredict",
    unit: "e1",
    conceptIds: ["e-total-pressure"],
    prompt: "Squeeze the static side down. What happens to the dynamic side?",
    widget: "EnginePressureSplit",
    options: ["Dynamic pressure increases", "Dynamic pressure decreases", "Nothing changes"],
    answer: 0,
    explanation:
      "Total pressure is fixed, so the two components trade against each other. Losing static pressure means gaining velocity.",
    knowCold: "Static ↓ → dynamic ↑, total unchanged.",
    difficulty: 2,
    source: L201(["1.1"]),
  },
  {
    id: "eq-e1-004",
    type: "mcq",
    unit: "e1",
    conceptIds: ["e-compressibility"],
    prompt: "At subsonic speeds, airflow is treated as",
    options: [
      "compressible, because air is a compressible fluid",
      "relatively incompressible",
      "incompressible only above 36,000 feet",
      "compressible only in the compressor section",
    ],
    answer: 1,
    explanation:
      "Air is a compressible fluid, but airflow at subsonic speeds is considered relatively incompressible. Compressibility becomes significant as flow approaches supersonic speed.",
    whyWrong:
      "The trap is conflating the FLUID (compressible) with the FLOW at subsonic speed (treated as incompressible).",
    knowCold: "Air is compressible; subsonic airflow is treated as incompressible.",
    difficulty: 2,
    officialStyle: true,
    source: L201(["1.2", "1.3"]),
  },
  {
    id: "eq-e1-005",
    type: "mcq",
    unit: "e1",
    conceptIds: ["e-subsonic-convergent"],
    prompt: "Subsonic airflow passing through a convergent opening will",
    options: [
      "increase in velocity and decrease in pressure",
      "decrease in velocity and increase in pressure",
      "increase in both velocity and pressure",
      "remain unchanged",
    ],
    answer: 0,
    explanation:
      "Bernoulli: an incompressible fluid through a convergent opening speeds up and its pressure drops.",
    knowCold: "Subsonic + convergent → velocity ↑, pressure ↓.",
    difficulty: 1,
    officialStyle: true,
    source: L201(["1.2"]),
  },
  {
    id: "eq-e1-006",
    type: "mcq",
    unit: "e1",
    conceptIds: ["e-subsonic-divergent"],
    prompt: "Subsonic airflow passing through a divergent opening will",
    options: [
      "increase in velocity and decrease in pressure",
      "decrease in velocity and increase in pressure",
      "decrease in both velocity and pressure",
      "increase in velocity with no pressure change",
    ],
    answer: 1,
    explanation:
      "A divergent opening slows subsonic flow and raises its pressure — which is why inlet ducts are divergent.",
    knowCold: "Subsonic + divergent → velocity ↓, pressure ↑.",
    difficulty: 1,
    officialStyle: true,
    source: L201(["1.2"]),
  },
  {
    id: "eq-e1-007",
    type: "mcq",
    unit: "e1",
    conceptIds: ["e-supersonic-ducts"],
    prompt: "A convergent opening will cause SUPERSONIC airflow to",
    options: [
      "increase in velocity and decrease in pressure",
      "decrease in velocity and increase in pressure",
      "behave exactly as subsonic flow does",
      "become incompressible",
    ],
    answer: 1,
    explanation:
      "Supersonic flow does the opposite of subsonic. A convergent opening decreases supersonic velocity and increases pressure.",
    whyWrong:
      "Option A is the SUBSONIC answer. The shape does not decide the outcome — the speed regime does.",
    knowCold: "Supersonic + convergent → velocity ↓, pressure ↑.",
    difficulty: 2,
    officialStyle: true,
    source: L201(["1.3"]),
  },
  {
    id: "eq-e1-008",
    type: "mcq",
    unit: "e1",
    conceptIds: ["e-supersonic-ducts"],
    prompt: "A divergent opening causes supersonic airflow velocity to ___ and pressure to ___.",
    options: [
      "decrease, increase",
      "increase, decrease",
      "increase, increase",
      "decrease, decrease",
    ],
    answer: 1,
    explanation:
      "Divergent plus supersonic accelerates the flow and drops its pressure — the principle behind the divergent section of a convergent/divergent exhaust nozzle.",
    knowCold: "Supersonic + divergent → velocity ↑, pressure ↓.",
    difficulty: 2,
    officialStyle: true,
    source: L201(["1.3"]),
  },
  {
    id: "ebf-e1-009",
    type: "beforeAfter",
    unit: "e1",
    conceptIds: ["e-supersonic-ducts", "e-subsonic-convergent"],
    prompt:
      "The same convergent duct, first with subsonic flow and then with supersonic flow.",
    diagram: { id: "eng-duct", props: { shape: "convergent", labels: false } },
    states: ["Subsonic", "Supersonic"],
    beforeProps: { regime: "subsonic" },
    afterProps: { regime: "supersonic" },
    rows: [
      {
        label: "Velocity",
        options: ["Increases then decreases", "Decreases then increases", "Increases both times"],
        answer: 0,
      },
      {
        label: "Pressure",
        options: ["Decreases then increases", "Increases then decreases", "Decreases both times"],
        answer: 0,
      },
    ],
    explanation:
      "Identical geometry, opposite result. Subsonic flow speeds up and loses pressure through a convergent duct; supersonic flow slows down and gains pressure.",
    knowCold: "Same shape, opposite effect either side of Mach 1.",
    difficulty: 3,
    source: L201(["1.2", "1.3"]),
  },
  {
    id: "eq-e1-010",
    type: "mcq",
    unit: "e1",
    conceptIds: ["e-nozzle"],
    prompt: "A nozzle always",
    options: [
      "is convergent in shape",
      "increases velocity and decreases pressure",
      "decreases velocity and increases pressure",
      "is used only in supersonic aircraft",
    ],
    answer: 1,
    explanation:
      "Nozzles always increase velocity and decrease pressure. Whether that requires a convergent or divergent shape depends on whether the flow is subsonic or supersonic.",
    whyWrong:
      "A nozzle is defined by what it DOES, not by its shape — a supersonic nozzle is divergent.",
    knowCold: "Nozzle = velocity ↑, pressure ↓, always.",
    difficulty: 2,
    officialStyle: true,
    source: L201(["1.2", "1.3"]),
  },
  {
    id: "eq-e1-011",
    type: "mcq",
    unit: "e1",
    conceptIds: ["e-diffuser"],
    prompt: "A diffuser always",
    options: [
      "decreases velocity and increases pressure",
      "increases velocity and decreases pressure",
      "is divergent in shape regardless of airflow speed",
      "is found only in the exhaust section",
    ],
    answer: 0,
    explanation:
      "Diffusers always decrease velocity and increase pressure. A subsonic diffuser is divergent; a supersonic diffuser is convergent.",
    knowCold: "Diffuser = velocity ↓, pressure ↑, always.",
    difficulty: 2,
    officialStyle: true,
    source: L201(["1.2", "1.3"]),
  },
  {
    id: "etrap-e1-012",
    type: "spotTheTrap",
    unit: "e1",
    conceptIds: ["e-diffuser", "e-nozzle"],
    prompt: '"A diffuser is always divergent in shape."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. A diffuser is defined by its effect — velocity down, pressure up. A SUBSONIC diffuser is divergent, but a SUPERSONIC diffuser is convergent.",
    knowCold: "Shape follows the speed regime; the job stays the same.",
    difficulty: 3,
    source: L201(["1.2", "1.3"]),
  },
  {
    id: "eq-e1-013",
    type: "mcq",
    unit: "e1",
    conceptIds: ["e-gas-generator"],
    prompt: "The three main sections of a gas generator are the",
    options: [
      "inlet, compressor, and exhaust",
      "compressor, combustion chamber, and turbine",
      "inlet, combustion chamber, and exhaust",
      "compressor, turbine, and afterburner",
    ],
    answer: 1,
    explanation:
      "Every gas generator minimally includes a compressor, a combustion chamber and a turbine. The inlet and exhaust are not part of the gas generator itself.",
    whyWrong:
      "The inlet and exhaust sections attach to the gas generator but are not among its three main sections.",
    knowCold: "Gas generator = compressor + combustion chamber + turbine.",
    difficulty: 1,
    officialStyle: true,
    source: L201(["1.4"]),
  },
  {
    id: "etap-e1-014",
    type: "tapDiagram",
    unit: "e1",
    conceptIds: ["e-gas-generator"],
    prompt: "Tap the COMBUSTION section of the engine.",
    diagram: { id: "eng-cutaway", props: { labels: false, flow: false } },
    targets: [
      { id: "inlet", label: "Inlet", x: 85, y: 150, r: 32 },
      { id: "compressor", label: "Compressor", x: 183, y: 150, r: 40 },
      { id: "burner", label: "Combustion", x: 274, y: 150, r: 32 },
      { id: "turbine", label: "Turbine", x: 348, y: 150, r: 30 },
      { id: "exhaust", label: "Exhaust", x: 428, y: 150, r: 34 },
    ],
    answer: "burner",
    explanation:
      "Combustion sits between the compressor and the turbine — fuel is added to compressed air here, and the turbine downstream harvests the energy.",
    knowCold: "Inlet → compressor → combustion → turbine → exhaust.",
    difficulty: 1,
    source: L201(["1.4", "1.7"]),
  },
  {
    id: "eq-e1-015",
    type: "mcq",
    unit: "e1",
    conceptIds: ["e-brayton", "e-otto"],
    prompt:
      "The four events of the Brayton cycle occur ___, while the four events of the Otto cycle occur ___.",
    options: [
      "sequentially, simultaneously",
      "simultaneously, sequentially",
      "simultaneously, simultaneously",
      "sequentially, sequentially",
    ],
    answer: 1,
    explanation:
      "Both cycles have the same four events — intake, compression, combustion, exhaust. In a gas turbine (Brayton) they happen simultaneously and continuously; in a reciprocating engine (Otto) they happen one after another.",
    whyWrong:
      "Because the event NAMES are identical, the exam tests only the timing. Turbine = simultaneous.",
    knowCold: "Brayton = simultaneous. Otto = sequential (suck, squeeze, bang, blow).",
    difficulty: 2,
    officialStyle: true,
    source: L201(["1.5", "1.6"]),
  },
  {
    id: "eq-e1-016",
    type: "mcq",
    unit: "e1",
    conceptIds: ["e-brayton"],
    prompt: "The four events of the Brayton cycle are",
    options: [
      "intake, compression, combustion, exhaust",
      "intake, ignition, expansion, exhaust",
      "compression, ignition, power, exhaust",
      "suck, squeeze, bang, blow",
    ],
    answer: 0,
    explanation:
      "Intake, compression, combustion, exhaust — occurring simultaneously in a gas turbine engine.",
    knowCold: "Intake → compression → combustion → exhaust.",
    difficulty: 1,
    officialStyle: true,
    source: L201(["1.5"]),
  },
  {
    id: "ecc-e1-017",
    type: "connectChain",
    unit: "e1",
    conceptIds: ["e-station-changes", "e-gas-generator"],
    prompt: "Put the engine sections in the order air passes through them.",
    trigger: "Air enters the engine",
    steps: ["Inlet", "Compressor", "Combustion chamber", "Turbine", "Exhaust"],
    explanation:
      "The gas path never changes: air is slowed and pressurised at the inlet, compressed, burned, expanded through the turbine, then accelerated out the exhaust.",
    knowCold: "Inlet → compressor → combustion → turbine → exhaust.",
    difficulty: 1,
    source: L201(["1.7"]),
  },
  {
    id: "eq-e1-018",
    type: "mcq",
    unit: "e1",
    conceptIds: ["e-station-changes"],
    prompt: "As airflow passes through the COMBUSTION section, pressure",
    options: [
      "increases significantly",
      "decreases slightly",
      "remains exactly constant",
      "decreases to atmospheric",
    ],
    answer: 1,
    explanation:
      "Combustion adds heat, raising temperature and velocity, but there is a slight DECREASE in pressure across the burner.",
    whyWrong:
      "Intuition says burning fuel raises pressure. It does not — the energy goes into temperature and velocity.",
    knowCold: "Combustion: temperature ↑, velocity ↑, pressure slightly ↓.",
    difficulty: 3,
    officialStyle: true,
    source: L201(["1.7"]),
  },
  {
    id: "eq-e1-019",
    type: "mcq",
    unit: "e1",
    conceptIds: ["e-station-changes"],
    prompt: "Through the INLET duct, pressure ___ and velocity ___.",
    options: ["increases, decreases", "decreases, increases", "increases, increases", "decreases, decreases"],
    answer: 0,
    explanation:
      "The inlet acts as a diffuser: it raises pressure and lowers velocity before the air reaches the first compressor stage.",
    knowCold: "Inlet = diffuser: pressure ↑, velocity ↓.",
    difficulty: 2,
    officialStyle: true,
    source: L201(["1.7"]),
  },
  {
    id: "eq-e1-020",
    type: "mcq",
    unit: "e1",
    conceptIds: ["e-station-changes"],
    prompt: "Across the TURBINE section, velocity ___ and pressure ___.",
    options: ["decreases, increases", "increases, decreases", "increases, increases", "decreases, decreases"],
    answer: 1,
    explanation:
      "The turbine increases airflow velocity while pressure drops, using most of the kinetic energy to turn the compressor.",
    knowCold: "Turbine: velocity ↑, pressure ↓.",
    difficulty: 2,
    source: L201(["1.7"]),
  },
];
