import type { Question, SourceReference } from "@/lib/types";

const L201 = (eo: string[]): SourceReference => ({
  document: "Principles of Gas Turbine/Reciprocating Operation",
  chapter: "Principles of Gas Turbine/Reciprocating Operation",
  eo,
});

/**
 * Unit e2 — Making Thrust.
 *
 * Every atmospheric factor works through density, so the questions keep
 * forcing the student back through that chain rather than letting them
 * memorise six unrelated arrows.
 */
export const E2_QUESTIONS: Question[] = [
  {
    id: "eq-e2-001",
    type: "mcq",
    unit: "e2",
    conceptIds: ["e-thrust-equation"],
    prompt: "The thrust equation is",
    options: [
      "thrust = mass × velocity",
      "thrust = mass × acceleration",
      "thrust = pressure × area",
      "thrust = force ÷ area",
    ],
    answer: 1,
    explanation:
      "Thrust equals mass times acceleration. Every factor that changes thrust does so by changing either the mass of air or its acceleration.",
    knowCold: "T = m × a.",
    difficulty: 1,
    officialStyle: true,
    source: L201(["1.8"]),
  },
  {
    id: "eq-e2-002",
    type: "mcq",
    unit: "e2",
    conceptIds: ["e-gross-thrust"],
    prompt: "Gross thrust is measured",
    options: [
      "in flight at cruise airspeed",
      "on stationary engines or aircraft ground run-ups, ignoring inlet velocity",
      "by correcting for the velocity of air at the inlet",
      "only with the afterburner engaged",
    ],
    answer: 1,
    explanation:
      "Gross thrust is measured on stationary engines or ground run-ups at standard day conditions. It ignores inlet air velocity and measures exhaust gas velocity only.",
    whyWrong: "Correcting for inlet velocity is what makes thrust NET, not gross.",
    knowCold: "Gross ignores inlet velocity. Net corrects for it.",
    difficulty: 2,
    officialStyle: true,
    source: L201(["1.8"]),
  },
  {
    id: "eq-e2-003",
    type: "mcq",
    unit: "e2",
    conceptIds: ["e-net-thrust", "e-gross-thrust"],
    prompt: "Net thrust and gross thrust are equal when",
    options: [
      "the engine is at maximum RPM",
      "inlet velocity is zero at standard day conditions",
      "the aircraft is supersonic",
      "the afterburner is operating",
    ],
    answer: 1,
    explanation:
      "Net thrust corrects for inlet airflow velocity. With no inlet velocity there is nothing to correct, so the two are the same.",
    knowCold: "Zero inlet velocity → net = gross.",
    difficulty: 2,
    officialStyle: true,
    source: L201(["1.8"]),
  },
  {
    id: "eq-e2-004",
    type: "mcq",
    unit: "e2",
    conceptIds: ["e-density-thrust"],
    prompt: "An increase in air density will cause thrust to",
    options: [
      "decrease, because denser air resists acceleration",
      "increase, because mass increases",
      "remain the same",
      "decrease only above 36,000 feet",
    ],
    answer: 1,
    explanation:
      "Density is mass per unit volume and feeds the mass term directly. Denser air means more mass through the engine, so more thrust.",
    knowCold: "Density ↑ → mass ↑ → thrust ↑.",
    difficulty: 1,
    officialStyle: true,
    source: L201(["1.9"]),
  },
  {
    id: "eq-e2-005",
    type: "mcq",
    unit: "e2",
    conceptIds: ["e-temperature-thrust"],
    prompt: "As outside air temperature decreases, thrust",
    options: ["decreases", "increases", "remains constant", "increases only below 36,000 feet"],
    answer: 1,
    explanation:
      "Colder air packs molecules closer together, raising density, which raises mass and therefore thrust.",
    knowCold: "Temperature ↓ → density ↑ → thrust ↑.",
    difficulty: 1,
    officialStyle: true,
    source: L201(["1.9"]),
  },
  {
    id: "eq-e2-006",
    type: "mcq",
    unit: "e2",
    conceptIds: ["e-pressure-thrust"],
    prompt: "As atmospheric pressure decreases, thrust",
    options: ["increases", "decreases", "remains constant", "increases then decreases"],
    answer: 1,
    explanation:
      "Lower pressure lets air molecules move farther apart, making the air less dense, which reduces mass and thrust.",
    knowCold: "Pressure ↓ → density ↓ → thrust ↓.",
    difficulty: 1,
    officialStyle: true,
    source: L201(["1.11"]),
  },
  {
    id: "eq-e2-007",
    type: "mcq",
    unit: "e2",
    conceptIds: ["e-altitude-thrust"],
    prompt:
      "Thrust decreases as altitude increases because",
    options: [
      "temperature drops faster than pressure",
      "the drop in pressure has a greater impact than the drop in temperature",
      "engine RPM is limited at altitude",
      "ram effect stops working above 10,000 feet",
    ],
    answer: 1,
    explanation:
      "Climbing brings colder air (which would help thrust) and lower pressure (which hurts it). Pressure wins, so net thrust falls.",
    whyWrong:
      "Both temperature and pressure drop with altitude — the question is which effect dominates. Pressure does.",
    knowCold: "Altitude ↑ → thrust ↓, because pressure beats temperature.",
    difficulty: 2,
    officialStyle: true,
    source: L201(["1.10"]),
  },
  {
    id: "eq-e2-008",
    type: "mcq",
    unit: "e2",
    conceptIds: ["e-altitude-thrust"],
    prompt: "Above 36,000 feet, thrust decreases more rapidly during a climb because",
    options: [
      "the engine reaches its RPM limit",
      "temperature stabilises and no longer offsets pressure changes",
      "the air becomes compressible",
      "ram effect reverses",
    ],
    answer: 1,
    explanation:
      "Below 36,000 ft the falling temperature partly offsets falling pressure. Above it temperature stabilises, so only the pressure loss remains and thrust falls off faster.",
    knowCold: "36,000 ft: temperature stops helping, thrust drops faster.",
    difficulty: 3,
    officialStyle: true,
    source: L201(["1.10"]),
  },
  {
    id: "ecs-e2-009",
    type: "curveShift",
    unit: "e2",
    conceptIds: ["e-altitude-thrust"],
    prompt: "The aircraft climbs from sea level to high altitude.",
    diagram: { id: "eng-thrust-factor", props: { factor: "altitude" } },
    change: "Altitude increases",
    curveLabel: "Available thrust",
    options: ["up", "down", "left", "right"],
    answer: "down",
    afterProps: { factor: "altitude", marker: 40 },
    explanation:
      "Less dense air at altitude means less mass through the engine, so available thrust falls — and falls faster once past 36,000 ft.",
    knowCold: "Climb → thrust curve moves down.",
    difficulty: 2,
    source: L201(["1.10"]),
  },
  {
    id: "eq-e2-010",
    type: "mcq",
    unit: "e2",
    conceptIds: ["e-rpm-thrust"],
    prompt: "Regarding engine RPM and thrust,",
    options: [
      "thrust increases linearly with RPM throughout the range",
      "at low RPM a throttle increase produces little thrust; at high RPM a small increase produces a large thrust increase",
      "thrust is independent of RPM",
      "thrust decreases at high RPM due to compressor stall",
    ],
    answer: 1,
    explanation:
      "Any RPM increase increases thrust, but not linearly. Most of the available thrust lives at the top of the RPM range.",
    whyWrong:
      "The relationship is decidedly non-linear, which is why small throttle changes matter so much near max power.",
    knowCold: "RPM ↑ → thrust ↑, and the effect grows with RPM.",
    difficulty: 2,
    officialStyle: true,
    source: L201(["1.12"]),
  },
  {
    id: "eq-e2-011",
    type: "mcq",
    unit: "e2",
    conceptIds: ["e-airspeed-thrust"],
    prompt: "Considering airspeed alone, as airspeed increases thrust",
    options: [
      "increases, because more air enters the inlet",
      "decreases, as inlet velocity approaches exhaust velocity",
      "remains constant at all speeds",
      "increases only at supersonic speeds",
    ],
    answer: 1,
    explanation:
      "Airspeed acts on the acceleration term. As inlet velocity approaches exhaust velocity, the difference shrinks and thrust falls.",
    whyWrong:
      "More air entering the inlet is the RAM EFFECT, a separate factor that offsets this loss.",
    knowCold: "Airspeed ↑ → thrust ↓ (before ram effect).",
    difficulty: 2,
    officialStyle: true,
    source: L201(["1.13"]),
  },
  {
    id: "eq-e2-012",
    type: "mcq",
    unit: "e2",
    conceptIds: ["e-ram-effect"],
    prompt: "Ram effect keeps thrust fairly constant at ___ speeds and greatly increases thrust at ___ speeds.",
    options: ["supersonic, subsonic", "subsonic, supersonic", "subsonic, subsonic", "supersonic, supersonic"],
    answer: 1,
    explanation:
      "At higher speeds more air molecules are rammed into the inlet, increasing mass. That keeps thrust roughly constant subsonically, and at supersonic speeds thrust greatly increases.",
    knowCold: "Ram: subsonic → thrust steady · supersonic → thrust way up.",
    difficulty: 2,
    officialStyle: true,
    source: L201(["1.14"]),
  },
  {
    id: "ecc-e2-013",
    type: "connectChain",
    unit: "e2",
    conceptIds: ["e-temperature-thrust", "e-density-thrust"],
    prompt: "Build the chain from colder air to more thrust.",
    trigger: "Outside air temperature decreases",
    steps: [
      "Air molecules move closer together",
      "Air density increases",
      "Mass of air through the engine increases",
      "Thrust increases",
    ],
    explanation:
      "Every atmospheric factor reaches thrust the same way — through density, into the mass term of T = m × a.",
    knowCold: "Everything atmospheric works through density.",
    difficulty: 2,
    source: L201(["1.9"]),
  },
  {
    id: "eq-e2-014",
    type: "mcq",
    unit: "e2",
    conceptIds: ["e-epr"],
    prompt: "Engine Pressure Ratio (EPR) indicates",
    options: [
      "the ratio between inlet and exhaust airflow pressure",
      "engine rotation speed in percent RPM",
      "shaft horsepower available to the propeller",
      "the ratio of fuel flow to airflow",
    ],
    answer: 0,
    explanation:
      "EPR gauges indicate the pressure ratio between inlet and exhaust airflow, and are used in most turbojet and turbofan aircraft.",
    knowCold: "EPR = inlet-to-exhaust pressure ratio. Turbojet and turbofan.",
    difficulty: 2,
    officialStyle: true,
    source: L201(["1.15"]),
  },
  {
    id: "eq-e2-015",
    type: "mcq",
    unit: "e2",
    conceptIds: ["e-torquemeter", "e-epr"],
    prompt: "A turboprop aircraft determines power available using the",
    options: ["EPR gauge", "torquemeter", "tachometer", "fuel flow gauge"],
    answer: 1,
    explanation:
      "Propeller or rotor driven aircraft use the torquemeter, which indicates shaft horsepower available to drive the propeller or rotor.",
    whyWrong: "EPR belongs to turbojets and turbofans, where thrust comes from the exhaust.",
    knowCold: "Torquemeter → prop/rotor. EPR → jet/fan.",
    difficulty: 2,
    officialStyle: true,
    source: L201(["1.15"]),
  },
  {
    id: "eq-e2-016",
    type: "mcq",
    unit: "e2",
    conceptIds: ["e-tachometer"],
    prompt: "The tachometer",
    options: [
      "directly measures thrust output",
      "indicates engine rotation speed, calibrated in percent RPM",
      "measures turbine inlet temperature",
      "indicates the pressure ratio across the engine",
    ],
    answer: 1,
    explanation:
      "The tachometer is the most commonly used cockpit gauge and shows engine rotation speed in percent RPM. It does not measure thrust — it monitors.",
    whyWrong:
      "The tachometer gives a quick sense of energy being produced, but it is a monitoring instrument, not a thrust measurement.",
    knowCold: "Tachometer = percent RPM, monitor only.",
    difficulty: 2,
    officialStyle: true,
    source: L201(["1.15"]),
  },
  {
    id: "etrap-e2-017",
    type: "spotTheTrap",
    unit: "e2",
    conceptIds: ["e-airspeed-thrust", "e-ram-effect"],
    prompt: '"Increasing airspeed always reduces thrust."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. Airspeed alone reduces thrust as inlet velocity approaches exhaust velocity, but ram effect adds mass and offsets it — keeping thrust roughly constant subsonically and increasing it supersonically.",
    knowCold: "Airspeed hurts thrust; ram effect pays it back.",
    difficulty: 3,
    source: L201(["1.13", "1.14"]),
  },
  {
    id: "eq-e2-018",
    type: "mcq",
    unit: "e2",
    conceptIds: ["e-net-thrust"],
    prompt: "Net thrust is considered a more realistic measurement than gross thrust because it",
    options: [
      "includes afterburner augmentation",
      "corrects for the effects of inlet airflow velocity",
      "is measured at maximum continuous RPM",
      "accounts for fuel consumption",
    ],
    answer: 1,
    explanation:
      "Net thrust corrects for inlet airflow velocity, which is why it reflects what the engine actually delivers in flight.",
    knowCold: "Net thrust accounts for the air already moving into the inlet.",
    difficulty: 2,
    source: L201(["1.8"]),
  },
  {
    id: "eq-e2-019",
    type: "mcq",
    unit: "e2",
    conceptIds: ["e-altitude-thrust", "e-temperature-thrust", "e-pressure-thrust"],
    prompt:
      "An aircraft takes off on a hot, high-altitude day. Compared with a cold day at sea level, available thrust is",
    options: [
      "greater, because hot air expands through the engine",
      "less, because both high temperature and low pressure reduce density",
      "the same, because the engine self-compensates",
      "less, but only if the afterburner is unavailable",
    ],
    answer: 1,
    explanation:
      "Hot air is less dense and high altitude means lower pressure. Both reduce density, so mass through the engine falls and thrust with it.",
    knowCold: "Hot and high = thin air = less thrust.",
    difficulty: 2,
    officialStyle: true,
    source: L201(["1.9", "1.10", "1.11"]),
  },
  {
    id: "eq-e2-020",
    type: "mcq",
    unit: "e2",
    conceptIds: ["e-rpm-thrust"],
    prompt: "Which cockpit gauge is used in most turbojet and turbofan aircraft to monitor thrust?",
    options: ["Torquemeter", "Engine Pressure Ratio", "Tachometer", "Interstage Turbine Temperature"],
    answer: 1,
    explanation:
      "EPR is used in most turbojet and turbofan aircraft and is more widely used than the turbine discharge pressure indicator.",
    knowCold: "Turbojet/turbofan → EPR.",
    difficulty: 1,
    source: L201(["1.15"]),
  },
];
