import type { Question, SourceReference } from "@/lib/types";

const L202 = (eo: string[]): SourceReference => ({
  document: "Gas Turbine/Reciprocating Engines",
  chapter: "Gas Turbine/Reciprocating Engines",
  eo,
});

/** Unit e3 — Inlet and Compressor. */
export const E3_QUESTIONS: Question[] = [
  {
    id: "eq-e3-001",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-inlet-purpose"],
    prompt: "The purpose of the inlet duct is to provide",
    options: [
      "high velocity, low pressure air to the compressor",
      "the proper amount of high pressure, turbulent-free, steady and uniform air to the first stage of the compressor",
      "cooling air for the combustion chamber liners",
      "bleed air for the environmental system",
    ],
    answer: 1,
    explanation:
      "The inlet duct delivers steady, uniform, turbulence-free high pressure air to the first compressor stage. Uniform airflow is what avoids compressor stalls.",
    knowCold: "Inlet: high pressure, turbulence-free, steady, uniform.",
    difficulty: 1,
    officialStyle: true,
    source: L202(["2.1"]),
  },
  {
    id: "eq-e3-002",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-inlet-purpose"],
    prompt: "Inlet ducts are designed to act as",
    options: ["nozzles", "diffusers", "manifolds", "venturis"],
    answer: 1,
    explanation:
      "Inlet ducts act as diffusers — they decrease velocity and increase pressure before the compressor.",
    knowCold: "Inlet = diffuser.",
    difficulty: 1,
    officialStyle: true,
    source: L202(["2.1"]),
  },
  {
    id: "eq-e3-003",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-single-entrance", "e-divided-entrance"],
    prompt: "Compared with a single entrance duct, a divided entrance duct",
    options: [
      "is simpler and more efficient",
      "has shorter ducts and less friction loss, but creates more inlet air turbulence",
      "eliminates the possibility of compressor stall",
      "is used only on single-engine aircraft",
    ],
    answer: 1,
    explanation:
      "Divided entrance ducts are shorter with less friction loss and let pilots sit lower, but they create more inlet air turbulence.",
    whyWrong: "The single entrance duct is the simple, efficient one.",
    knowCold: "Divided: shorter, less friction, MORE turbulence.",
    difficulty: 2,
    officialStyle: true,
    source: L202(["2.1"]),
  },
  {
    id: "eq-e3-004",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-single-entrance"],
    prompt: "A disadvantage of short single entrance inlet ducts is that they",
    options: [
      "cause excessive friction loss",
      "can cause stall at slow airspeed or high AOA",
      "require variable geometry at all speeds",
      "cannot be used with axial compressors",
    ],
    answer: 1,
    explanation:
      "Short single ducts can cause stall at slow airspeed or high angle of attack.",
    knowCold: "Short single duct → stall risk at low speed / high AOA.",
    difficulty: 2,
    source: L202(["2.1"]),
  },
  {
    id: "eq-e3-005",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-inlet-geometry"],
    prompt: "A supersonic inlet duct is ___ in design.",
    options: ["divergent", "convergent", "convergent/divergent", "constant area"],
    answer: 2,
    explanation:
      "A supersonic inlet is convergent/divergent: it must first slow the flow below supersonic, then further reduce velocity and increase pressure like a subsonic inlet.",
    whyWrong: "Divergent alone is the SUBSONIC inlet.",
    knowCold: "Subsonic inlet = divergent. Supersonic inlet = convergent/divergent.",
    difficulty: 2,
    officialStyle: true,
    source: L202(["2.1"]),
  },
  {
    id: "eq-e3-006",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-variable-geometry-inlet"],
    prompt: "A variable geometry inlet duct uses ramps, cones or wedges in order to",
    options: [
      "increase the frontal area for more mass flow",
      "keep acting as a diffuser as the aircraft changes speed regime",
      "convert the inlet into a nozzle at high speed",
      "reduce foreign object damage",
    ],
    answer: 1,
    explanation:
      "Mechanical devices change the duct shape — divergent at subsonic speeds, convergent/divergent at supersonic speeds — so it continues to act as a diffuser throughout.",
    knowCold: "Variable geometry keeps the inlet a diffuser at any speed.",
    difficulty: 2,
    source: L202(["2.1"]),
  },
  {
    id: "eq-e3-007",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-compressor-purpose"],
    prompt: "Across the compressor section, airflow",
    options: [
      "increases in pressure but decreases in velocity",
      "increases in both pressure and velocity",
      "decreases in both pressure and velocity",
      "increases in velocity but decreases in pressure",
    ],
    answer: 1,
    explanation:
      "Because the compressor is driven by energy from the turbine, both pressure AND velocity increase across it. It is not a closed system.",
    whyWrong:
      "Option A describes a diffuser. The compressor adds energy, so it can raise both.",
    knowCold: "Compressor: pressure ↑ AND velocity ↑.",
    difficulty: 3,
    officialStyle: true,
    source: L202(["2.2"]),
  },
  {
    id: "eq-e3-008",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-centrifugal-compressor"],
    prompt: "The three main components of a centrifugal flow compressor are the",
    options: [
      "rotor, stator, and manifold",
      "impeller, diffuser, and manifold",
      "impeller, rotor, and stator",
      "inlet guide vanes, impeller, and turbine",
    ],
    answer: 1,
    explanation:
      "Impeller, diffuser and manifold. The impeller accelerates the air outward, the diffuser converts velocity to pressure, and the manifold routes air to the combustion chambers.",
    whyWrong: "Rotor and stator are the AXIAL compressor's elements.",
    knowCold: "Centrifugal: impeller → diffuser → manifold.",
    difficulty: 2,
    officialStyle: true,
    source: L202(["2.2"]),
  },
  {
    id: "eq-e3-009",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-centrifugal-tradeoffs"],
    prompt: "Which is a DISADVANTAGE of the centrifugal flow compressor?",
    options: [
      "Poor power output across the RPM range",
      "Large frontal area increases drag, and it is impractical for multiple stages",
      "Low pressure increase per stage",
      "Compressor stalls are likely at low airspeed",
    ],
    answer: 1,
    explanation:
      "Centrifugal compressors are rugged, low cost and give a high pressure increase per stage, but their large frontal area adds drag and they cannot practically be stacked into many stages.",
    whyWrong:
      "Low-airspeed stall proneness and narrow efficient RPM range are AXIAL disadvantages.",
    knowCold: "Centrifugal: rugged and wide-RPM, but draggy and single-stage.",
    difficulty: 2,
    officialStyle: true,
    source: L202(["2.2"]),
  },
  {
    id: "eq-e3-010",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-axial-compressor"],
    prompt: "In an axial flow compressor, a single stage consists of",
    options: [
      "one rotor and one stator",
      "two rotors",
      "one impeller and one diffuser",
      "one rotor, one stator, and one set of guide vanes",
    ],
    answer: 0,
    explanation:
      "One rotor blade row plus one stator forms a single stage. Stacking stages gives the greatest overall compression ratios, between 15:1 and 30:1.",
    knowCold: "One rotor + one stator = one stage.",
    difficulty: 2,
    officialStyle: true,
    source: L202(["2.2"]),
  },
  {
    id: "eq-e3-011",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-axial-compressor"],
    prompt: "In an axial flow compressor, the stator",
    options: [
      "increases velocity and decreases pressure",
      "decreases velocity, increases pressure, and straightens the airflow",
      "drives the rotor via the main shaft",
      "meters fuel into the burner",
    ],
    answer: 1,
    explanation:
      "The stationary stator reduces airflow velocity, producing a proportional increase in pressure, while also straightening flow for the next stage.",
    knowCold: "Rotor accelerates; stator diffuses and straightens.",
    difficulty: 2,
    officialStyle: true,
    source: L202(["2.2"]),
  },
  {
    id: "eq-e3-012",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-axial-tradeoffs"],
    prompt: "Which is a disadvantage of the axial flow compressor?",
    options: [
      "Large frontal area",
      "Low pressure ratios",
      "Compressor stalls are more likely at low airspeeds",
      "Poor combustion efficiency",
    ],
    answer: 2,
    explanation:
      "Axial compressors stall more readily at low airspeeds, are difficult and costly to manufacture, and are efficient only across a narrow RPM range.",
    whyWrong: "Large frontal area is the CENTRIFUGAL penalty.",
    knowCold: "Axial: efficient and slim, but stall-prone and RPM-fussy.",
    difficulty: 2,
    officialStyle: true,
    source: L202(["2.2"]),
  },
  {
    id: "eq-e3-013",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-spools"],
    prompt: "In a dual spool compressor, the correct order from forward to aft is",
    options: [
      "HPC → LPC → LPT → HPT",
      "LPC → HPC → HPT → LPT",
      "LPC → HPC → LPT → HPT",
      "HPC → LPC → HPT → LPT",
    ],
    answer: 1,
    explanation:
      "Low pressure compressor, high pressure compressor, high pressure turbine, low pressure turbine. The high pressure pair sits in the middle, closest to the burner.",
    whyWrong:
      "The turbines mirror the compressors: the HP turbine is first out of the burner because it drives the HP compressor.",
    knowCold: "LPC → HPC → HPT → LPT.",
    difficulty: 3,
    officialStyle: true,
    source: L202(["2.2"]),
  },
  {
    id: "eq-e3-014",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-spools"],
    prompt: "In a dual spool arrangement, the low pressure turbine drives the",
    options: [
      "high pressure compressor",
      "low pressure compressor",
      "accessory gear box only",
      "propeller through a reduction gear box",
    ],
    answer: 1,
    explanation:
      "Each spool is independent: the LP turbine drives the LP compressor and the HP turbine drives the HP compressor, on separate shafts.",
    knowCold: "LP drives LP, HP drives HP.",
    difficulty: 2,
    source: L202(["2.2"]),
  },
  {
    id: "eq-e3-015",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-axial-centrifugal"],
    prompt: "The axial-centrifugal compressor is",
    options: [
      "well suited to supersonic airflow",
      "used to combine straight-through airflow with a large pressure increase through the impeller",
      "only found on large airliners",
      "a compressor with no stator vanes",
    ],
    answer: 1,
    explanation:
      "It combines the advantages of both: straight-through airflow plus a large pressure rise through the impeller. It is not suited to supersonic airflow. The T-6 uses a four-stage axial compressor and one centrifugal impeller.",
    knowCold: "Axial-centrifugal: best of both, but not for supersonic.",
    difficulty: 2,
    source: L202(["2.2"]),
  },
  {
    id: "eq-e3-016",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-guide-vanes"],
    prompt: "Inlet guide vanes",
    options: [
      "straighten the airflow leaving the compressor",
      "impart a swirling motion in the direction of compressor rotation and reduce drag on the first stage rotor",
      "meter fuel into the primary manifold",
      "prevent foreign object damage",
    ],
    answer: 1,
    explanation:
      "Inlet guide vanes swirl the incoming air in the direction of rotation, directing it onto the first stage rotor and reducing aerodynamic drag on those blades.",
    whyWrong: "Straightening flow at the discharge end is the EXIT guide vanes' job.",
    knowCold: "Inlet guide vanes swirl in; exit guide vanes straighten out.",
    difficulty: 2,
    source: L202(["2.2"]),
  },
  {
    id: "eq-e3-017",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-compressor-diffuser"],
    prompt: "The point of highest compression in a gas turbine engine is the",
    options: ["first compressor stage", "diffuser", "combustion chamber", "turbine inlet"],
    answer: 1,
    explanation:
      "The diffuser prepares air for the burner by decreasing velocity and giving a final pressure increase. It is the point of highest compression and is divergent in design.",
    whyWrong:
      "Pressure actually falls slightly across the combustion chamber, so it cannot be the peak.",
    knowCold: "Highest pressure in the engine = the diffuser.",
    difficulty: 3,
    officialStyle: true,
    source: L202(["2.2"]),
  },
  {
    id: "etap-e3-018",
    type: "tapDiagram",
    unit: "e3",
    conceptIds: ["e-compressor-purpose"],
    prompt: "Tap the COMPRESSOR section.",
    diagram: { id: "eng-cutaway", props: { labels: false, flow: false } },
    targets: [
      { id: "inlet", label: "Inlet", x: 85, y: 150, r: 32 },
      { id: "compressor", label: "Compressor", x: 183, y: 150, r: 40 },
      { id: "burner", label: "Combustion", x: 274, y: 150, r: 32 },
      { id: "turbine", label: "Turbine", x: 348, y: 150, r: 30 },
      { id: "exhaust", label: "Exhaust", x: 428, y: 150, r: 34 },
    ],
    answer: "compressor",
    explanation:
      "The compressor is the long bladed section between the inlet and the burner, where pressure and velocity both climb.",
    knowCold: "Compressor sits between inlet and combustion.",
    difficulty: 1,
    source: L202(["2.2"]),
  },
  {
    id: "eq-e3-019",
    type: "mcq",
    unit: "e3",
    conceptIds: ["e-axial-compressor"],
    prompt: "Axial flow compressors achieve overall compression ratios of approximately",
    options: ["2:1 to 4:1", "5:1 to 10:1", "15:1 to 30:1", "50:1 to 80:1"],
    answer: 2,
    explanation:
      "Because multiple stages can be stacked, axial compressors reach the greatest overall compression ratios, between 15:1 and 30:1.",
    knowCold: "Axial compression ratio: 15:1 to 30:1.",
    difficulty: 2,
    source: L202(["2.2"]),
  },
  {
    id: "etrap-e3-020",
    type: "spotTheTrap",
    unit: "e3",
    conceptIds: ["e-compressor-purpose", "e-total-pressure"],
    prompt: '"Total pressure remains constant across the compressor."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. The compressor is driven by the turbine, so energy is added — it is not a closed system, and total pressure rises. Total pressure IS conserved across the centrifugal compressor's stationary diffuser.",
    knowCold: "Energy added → total pressure rises. Only passive ducts conserve it.",
    difficulty: 3,
    source: L202(["2.2"]),
  },
];
