import type { Question, SourceReference } from "@/lib/types";

const L202 = (eo: string[]): SourceReference => ({
  document: "Gas Turbine/Reciprocating Engines",
  chapter: "Gas Turbine/Reciprocating Engines",
  eo,
});

/**
 * Unit e4 — Burn, Turbine, Exhaust.
 *
 * Two different 25/75 splits live one section apart — air in the burner and
 * energy at the turbine — so several questions deliberately put them near each
 * other to force the distinction.
 */
export const E4_QUESTIONS: Question[] = [
  {
    id: "eq-e4-001",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-primary-secondary-air"],
    prompt: "Primary air, used for combustion, makes up approximately ___ of the airflow from the diffuser.",
    options: ["10%", "25%", "50%", "75%"],
    answer: 1,
    explanation:
      "25% of the airflow is primary air, mixed with fuel for ignition. The other 75% is secondary air.",
    knowCold: "25% primary burns · 75% secondary cools.",
    difficulty: 1,
    officialStyle: true,
    source: L202(["2.3"]),
  },
  {
    id: "eq-e4-002",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-primary-secondary-air"],
    prompt: "Secondary air in the combustion chamber is used for all of the following EXCEPT",
    options: [
      "cooling the thin walls of the combustion chamber",
      "cooling the turbine",
      "mixing with fuel for initial ignition",
      "controlling the flame",
    ],
    answer: 2,
    explanation:
      "Secondary air (75%) flows around the chamber to cool the walls and turbine, control the flame, and feed afterburner operation. Mixing with fuel for ignition is the job of PRIMARY air.",
    knowCold: "Secondary cools and controls; primary burns.",
    difficulty: 2,
    officialStyle: true,
    source: L202(["2.3"]),
  },
  {
    id: "eq-e4-003",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-burner-purpose"],
    prompt: "The burner section delivers gases to the turbine at a temperature that",
    options: [
      "is as high as the fuel can produce",
      "will not exceed the limits of the turbine blades",
      "equals compressor inlet temperature",
      "is below the flash point of the fuel",
    ],
    answer: 1,
    explanation:
      "The burner must mix fuel and air properly, deliver gases below the turbine blade temperature limit, and add enough heat energy to accelerate the gases for the desired thrust.",
    knowCold: "Hot enough for thrust, cool enough for the turbine blades.",
    difficulty: 2,
    source: L202(["2.3"]),
  },
  {
    id: "eq-e4-004",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-burner-criteria"],
    prompt: "Combustion chamber design criteria include all of the following EXCEPT",
    options: [
      "minimise pressure decrease",
      "burning must be complete prior to gases entering the turbine section",
      "the flame must not blow out",
      "maximise the pressure rise across the chamber",
    ],
    answer: 3,
    explanation:
      "The chamber aims to MINIMISE pressure loss — there is no pressure rise to maximise. Pressure decreases slightly across the burner.",
    knowCold: "Burner minimises pressure loss; it never raises pressure.",
    difficulty: 3,
    officialStyle: true,
    source: L202(["2.4"]),
  },
  {
    id: "eq-e4-005",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-can-chamber"],
    prompt: "A disadvantage of the can combustion chamber is that",
    options: [
      "maintenance requires a major engine overhaul",
      "malfunctions can lead to cold spots on the turbine",
      "it has the largest engine diameter of the three types",
      "it cannot be used with centrifugal compressors",
    ],
    answer: 1,
    explanation:
      "Can chambers make poor use of chamber space, have greater pressure loss, and a malfunction can leave cold spots on the turbine. They are strong, durable and easy to maintain.",
    whyWrong: "Requiring a major overhaul to maintain is the ANNULAR disadvantage.",
    knowCold: "Can: easy to maintain, but cold spots and pressure loss.",
    difficulty: 2,
    officialStyle: true,
    source: L202(["2.4"]),
  },
  {
    id: "eq-e4-006",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-annular-chamber"],
    prompt: "The annular combustion chamber's principal advantages are",
    options: [
      "strength, durability and ease of maintenance",
      "uniform heat distribution across the turbine face and a smaller engine diameter",
      "lowest procurement cost and easiest replacement",
      "elimination of secondary airflow requirements",
    ],
    answer: 1,
    explanation:
      "The continuous liner gives uniform heat distribution across the turbine face, and its much smaller circumference reduces overall engine diameter.",
    whyWrong: "Strength, durability and easy maintenance describe the CAN chamber.",
    knowCold: "Annular: uniform heat, smallest diameter.",
    difficulty: 2,
    officialStyle: true,
    source: L202(["2.4"]),
  },
  {
    id: "eq-e4-007",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-annular-chamber"],
    prompt: "The liner of an annular combustion chamber is referred to as the",
    options: ["burner basket", "screech liner", "flame holder", "manifold"],
    answer: 0,
    explanation:
      "The continuous circular inner liner and outer shroud surrounding the compressor drive shaft is called the burner basket, with fuel introduced through a series of nozzles.",
    knowCold: "Annular liner = burner basket.",
    difficulty: 2,
    source: L202(["2.4"]),
  },
  {
    id: "eq-e4-008",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-can-annular-chamber"],
    prompt: "Can-annular combustion chambers are used primarily on",
    options: [
      "older centrifugal compressor engines",
      "larger high performance aircraft",
      "reciprocating engines",
      "helicopters only",
    ],
    answer: 1,
    explanation:
      "Combustion occurs in cans with hot gases mixing in the annular portion. Used on larger high performance aircraft, it eliminates cold spots caused by clogged nozzles.",
    knowCold: "Can-annular: big high-performance aircraft, no cold spots.",
    difficulty: 2,
    source: L202(["2.4"]),
  },
  {
    id: "eq-e4-009",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-turbine-purpose"],
    prompt:
      "The turbine transforms approximately ___ of the heat energy of the expanding gases into mechanical energy.",
    options: ["25%", "50%", "75%", "90%"],
    answer: 2,
    explanation:
      "75% of the heat energy drives the compressor and accessory gear box. The remaining 25% is used for thrust.",
    whyWrong:
      "25% is the share left for THRUST, and separately the share of AIR that is primary in the burner. Three different quantities, easy to swap.",
    knowCold: "Turbine: 75% to the compressor, 25% to thrust.",
    difficulty: 2,
    officialStyle: true,
    source: L202(["2.5"]),
  },
  {
    id: "eq-e4-010",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-turbine-purpose", "e-primary-secondary-air"],
    prompt:
      "In the burner, 25% of the ___ is primary. At the turbine, 25% of the ___ is left for thrust.",
    options: [
      "energy, airflow",
      "airflow, energy",
      "fuel, airflow",
      "airflow, fuel",
    ],
    answer: 1,
    explanation:
      "The burner splits AIRFLOW 25/75 (primary/secondary). The turbine splits ENERGY 75/25 (compressor/thrust). Same numbers, different quantities, one section apart.",
    knowCold: "Burner splits air. Turbine splits energy.",
    difficulty: 3,
    source: L202(["2.3", "2.5"]),
  },
  {
    id: "eq-e4-011",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-creep"],
    prompt: "Creep is",
    options: [
      "the gradual loss of compressor efficiency over time",
      "abnormal elongation of turbine blades due to overheating",
      "slow leakage of oil past the bearing seals",
      "progressive advance of the throttle during cruise",
    ],
    answer: 1,
    explanation:
      "Creep is the abnormal elongation of turbine blades due to overheating, which can result in permanent blade deformation. The turbine is the most stressed part of the engine.",
    knowCold: "Creep = turbine blades stretch from heat.",
    difficulty: 1,
    officialStyle: true,
    source: L202(["2.6"]),
  },
  {
    id: "eq-e4-012",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-fir-tree"],
    prompt: "Turbine blades are attached to the wheel by a 'fir tree' attachment in order to",
    options: [
      "increase the blade surface area",
      "provide for normal expansion of the blades due to heating",
      "allow blades to be changed without removing the engine",
      "reduce the weight of the turbine wheel",
    ],
    answer: 1,
    explanation:
      "The fir tree attachment provides for normal expansion of the blades as they heat, which is what keeps normal thermal growth from becoming damage.",
    knowCold: "Fir tree = room for the blades to grow when hot.",
    difficulty: 2,
    officialStyle: true,
    source: L202(["2.6"]),
  },
  {
    id: "eq-e4-013",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-exhaust-section"],
    prompt: "The parts of the exhaust section are the",
    options: [
      "outer duct, inner cone, and radial struts",
      "spray bars, flame holders, and screech liner",
      "impeller, diffuser, and manifold",
      "rotor, stator, and shroud",
    ],
    answer: 0,
    explanation:
      "The exhaust section comprises the exhaust outer duct, the exhaust inner cone and radial struts, and directs hot gases rearward at high velocity while preventing turbulence.",
    whyWrong: "Spray bars, flame holders and screech liners are AFTERBURNER components.",
    knowCold: "Exhaust: outer duct, inner cone, radial struts.",
    difficulty: 2,
    officialStyle: true,
    source: L202(["2.7"]),
  },
  {
    id: "eq-e4-014",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-exhaust-nozzles"],
    prompt: "A convergent/divergent exhaust nozzle is used in supersonic aircraft because",
    options: [
      "the convergent section accelerates gases toward the speed of sound and the divergent section allows further acceleration to supersonic speeds",
      "it reduces exhaust noise at high altitude",
      "the divergent section slows the gases to prevent turbine damage",
      "it eliminates the need for an afterburner",
    ],
    answer: 0,
    explanation:
      "Convergent accelerates subsonic gas toward Mach 1; once supersonic, divergent continues the acceleration — exactly the reversal from unit e1.",
    knowCold: "Con-di: convergent to Mach 1, divergent beyond it.",
    difficulty: 2,
    officialStyle: true,
    source: L202(["2.7"]),
  },
  {
    id: "eq-e4-015",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-afterburner"],
    prompt: "Afterburner operation can increase the maximum thrust available by",
    options: ["about 10%", "about 25%", "50% or more", "exactly 100%"],
    answer: 2,
    explanation:
      "Igniting secondary and bypass air increases maximum thrust available by 50% or more, for short periods such as takeoff.",
    knowCold: "Afterburner: +50% or more, briefly.",
    difficulty: 1,
    officialStyle: true,
    source: L202(["2.8"]),
  },
  {
    id: "eq-e4-016",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-afterburner-ignition"],
    prompt:
      "Which afterburner ignition method sends additional ignited fuel from the combustion chamber streaking through the turbine?",
    options: ["Spark ignition", "Torch ignition", "Hot streak ignition", "Capacitor discharge"],
    answer: 2,
    explanation:
      "Hot streak ignition streaks additional ignited fuel from the combustion chamber through the turbine to light the afterburner. Spark ignition is most common; torch ignition uses a pilot light.",
    knowCold: "Hot streak literally streaks fire through the turbine.",
    difficulty: 2,
    source: L202(["2.8"]),
  },
  {
    id: "eq-e4-017",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-afterburner-components"],
    prompt: "Screech liners are installed in the afterburner duct to",
    options: [
      "introduce fuel to the exhaust section",
      "reduce pressure fluctuations and vibrations, acting as a shock absorber",
      "stabilise the flame in the duct",
      "vary the nozzle area during afterburner operation",
    ],
    answer: 1,
    explanation:
      "Screech liners are perforated sleeves that reduce pressure fluctuations and vibration. Spray bars introduce fuel; flame holders stabilise the flame.",
    knowCold: "Screech liner = shock absorber for pressure pulses.",
    difficulty: 2,
    officialStyle: true,
    source: L202(["2.8"]),
  },
  {
    id: "eq-e4-018",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-variable-exhaust-nozzle"],
    prompt:
      "The variable exhaust nozzle opens during afterburner operation to prevent",
    options: [
      "flame blowout in the combustion chamber",
      "gases backing up and causing back pressure, which can stall the compressor",
      "overheating of the turbine blades",
      "loss of nozzle focal point",
    ],
    answer: 1,
    explanation:
      "Opening the nozzle lets the gases expand. If they back up, the resulting back pressure travels forward and can stall the compressor — which is why a nozzle failure appears again in the compressor stall block.",
    knowCold: "Nozzle stuck shut in afterburner → back pressure → compressor stall.",
    difficulty: 3,
    officialStyle: true,
    source: L202(["2.8"]),
  },
  {
    id: "eq-e4-019",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-variable-exhaust-nozzle"],
    prompt: "When the afterburner is NOT in operation, the variable exhaust nozzle is",
    options: ["fully open", "convergent", "divergent", "closed completely"],
    answer: 1,
    explanation:
      "With the afterburner off the nozzle is convergent, which accelerates the subsonic gases.",
    knowCold: "Afterburner off → nozzle convergent.",
    difficulty: 2,
    source: L202(["2.8"]),
  },
  {
    id: "eq-e4-020",
    type: "mcq",
    unit: "e4",
    conceptIds: ["e-recip-components"],
    prompt: "Which is NOT a basic component of a reciprocating engine?",
    options: ["Crankshaft", "Connecting rods", "Stator vanes", "Valve-operating mechanism"],
    answer: 2,
    explanation:
      "The basic components are the crankcase, cylinders, pistons, connecting rods, valves, valve-operating mechanism and crankshaft. Stator vanes belong to an axial compressor.",
    knowCold: "Recip: crankcase, cylinders, pistons, rods, valves, valve gear, crankshaft.",
    difficulty: 2,
    officialStyle: true,
    source: L202(["2.9"]),
  },
  {
    id: "ecc-e4-021",
    type: "connectChain",
    unit: "e4",
    conceptIds: ["e-turbine-purpose", "e-exhaust-section"],
    prompt: "Trace the energy from combustion to thrust.",
    trigger: "Fuel burns in the combustion chamber",
    steps: [
      "Expanding gases carry heat energy to the turbine",
      "Turbine extracts 75% to drive the compressor and accessory gear box",
      "Remaining 25% passes to the exhaust section",
      "Exhaust nozzle accelerates the gases rearward as thrust",
    ],
    explanation:
      "Most of the fire goes into keeping the engine turning. Only the last quarter leaves as thrust.",
    knowCold: "75% keeps the engine running, 25% pushes the aircraft.",
    difficulty: 2,
    source: L202(["2.5", "2.7"]),
  },
];
