import type { Question, SourceReference } from "@/lib/types";

const NOTES = (chapter: string): SourceReference => ({
  document: "Engines Condensed Notes",
  chapter,
});

/**
 * Unit e6 — Engine Types.
 *
 * No official lecture covers this block, so every fact here traces to the
 * condensed notes and no enabling objective is claimed.
 */
export const E6_QUESTIONS: Question[] = [
  {
    id: "eq-e6-001",
    type: "mcq",
    unit: "e6",
    conceptIds: ["e-turbojet"],
    prompt: "An advantage of the turbojet is",
    options: [
      "lowest TSFC of any gas turbine engine",
      "the lightest specific weight and best high-end performance",
      "highest thrust at low airspeed",
      "shortest takeoff distance",
    ],
    answer: 1,
    explanation:
      "Turbojets fly higher and faster than other types, have the best high-end performance and the lightest specific weight. Their weaknesses are low propulsive efficiency at low airspeed, high TSFC and longer takeoff requirements.",
    whyWrong: "Lowest TSFC belongs to the turboprop; high low-speed thrust to the turboprop and turbofan.",
    knowCold: "Turbojet: fast and light, thirsty and slow off the runway.",
    difficulty: 2,
    source: NOTES("Engine Types"),
  },
  {
    id: "eq-e6-002",
    type: "mcq",
    unit: "e6",
    conceptIds: ["e-turbofan"],
    prompt: "In a turbofan, thrust from the ducted fan accounts for approximately",
    options: ["10%", "30–60%", "75%", "90%"],
    answer: 1,
    explanation:
      "40–70% of thrust comes from the gas generator and 30–60% from the ducted fan.",
    knowCold: "Turbofan: 40–70% core, 30–60% fan.",
    difficulty: 2,
    source: NOTES("Engine Types"),
  },
  {
    id: "eq-e6-003",
    type: "mcq",
    unit: "e6",
    conceptIds: ["e-turbofan", "e-tsfc"],
    prompt: "Engines with higher bypass ratios have",
    options: [
      "higher TSFC and are less fuel efficient",
      "lower TSFC and are more fuel efficient",
      "unchanged TSFC but more thrust",
      "lower thrust at all airspeeds",
    ],
    answer: 1,
    explanation:
      "More fuel efficient engines have higher bypass ratios, yielding lower TSFC. Airliners and cargo aircraft run high bypass ratios; fighters run low bypass to resemble turbojet performance.",
    knowCold: "Bypass ratio ↑ → TSFC ↓ → more efficient.",
    difficulty: 2,
    source: NOTES("Engine Types"),
  },
  {
    id: "eq-e6-004",
    type: "mcq",
    unit: "e6",
    conceptIds: ["e-turboprop"],
    prompt: "In a turboprop, approximately ___ of the thrust comes from the propeller.",
    options: ["50%", "75%", "90%", "100%"],
    answer: 2,
    explanation:
      "90% of thrust comes from the propeller and 10% from the exhaust gases of the gas turbine engine.",
    whyWrong: "100% from the rotor with nothing from exhaust describes the TURBOSHAFT.",
    knowCold: "Turboprop: 90% prop, 10% exhaust.",
    difficulty: 1,
    source: NOTES("Engine Types"),
  },
  {
    id: "eq-e6-005",
    type: "mcq",
    unit: "e6",
    conceptIds: ["e-rgb"],
    prompt: "The reduction gear box converts",
    options: [
      "low RPM, high torque turbine rotation to high RPM, low torque for the propeller",
      "high RPM, low torque turbine rotation to low RPM, high torque for the propeller",
      "mechanical energy to electrical energy",
      "AC voltage to DC voltage",
    ],
    answer: 1,
    explanation:
      "The RGB trades RPM for torque, and in doing so prevents the propeller reaching supersonic tip speeds, which would lower efficiency.",
    knowCold: "RGB: high RPM/low torque → low RPM/high torque.",
    difficulty: 2,
    source: NOTES("Engine Types"),
  },
  {
    id: "eq-e6-006",
    type: "mcq",
    unit: "e6",
    conceptIds: ["e-propeller-ranges"],
    prompt: "The beta range of turboprop propeller operation is",
    options: [
      "the flight range, from idle to full power",
      "the ground-only range, from idle to max reverse",
      "used only during engine start",
      "the range in which the governor controls blade angle",
    ],
    answer: 1,
    explanation:
      "Beta is ground-only, PCL from idle to max reverse, with the PCL mechanically connected to the FCU and the pitch change assembly. Alpha is the flight range.",
    whyWrong:
      "In ALPHA range the propeller governor controls blade angle; in beta the linkage is mechanical.",
    knowCold: "Alpha = flight. Beta = ground.",
    difficulty: 2,
    source: NOTES("Engine Types"),
  },
  {
    id: "eq-e6-007",
    type: "mcq",
    unit: "e6",
    conceptIds: ["e-turboshaft", "e-turboprop"],
    prompt: "The key difference between a turboshaft and a turboprop is that a turboshaft",
    options: [
      "produces no propulsive energy from exhaust gases",
      "has no reduction gear box",
      "cannot use a free turbine",
      "derives 10% of its thrust from exhaust",
    ],
    answer: 0,
    explanation:
      "A turboshaft always uses a free or power turbine separate from the gas generator, and all propulsive energy comes from rotor rotation — none from the exhaust gases. A turboprop still gets 10% from exhaust.",
    knowCold: "Turboshaft: 100% rotor, 0% exhaust.",
    difficulty: 2,
    source: NOTES("Engine Types"),
  },
  {
    id: "eq-e6-008",
    type: "mcq",
    unit: "e6",
    conceptIds: ["e-tsfc"],
    prompt: "Thrust Specific Fuel Consumption (TSFC) is",
    options: [
      "the total fuel burned per flight hour",
      "the amount of fuel required to produce one pound of thrust",
      "the ratio of bypassed air to core air",
      "the efficiency of converting kinetic energy to propulsive force",
    ],
    answer: 1,
    explanation:
      "TSFC is fuel required per pound of thrust. Bypass ratio and propulsive efficiency are separate definitions.",
    knowCold: "TSFC = fuel per pound of thrust.",
    difficulty: 1,
    source: NOTES("Engine Types"),
  },
  {
    id: "eq-e6-009",
    type: "mcq",
    unit: "e6",
    conceptIds: ["e-turboprop"],
    prompt: "Which engine type has the LOWEST TSFC?",
    options: ["Turbojet", "Turbofan", "Turboprop", "All are equal"],
    answer: 2,
    explanation:
      "The turboprop has the lowest TSFC of any gas turbine engine, along with excellent takeoff, slow speed and low altitude performance. Its penalty is a speed limit of roughly 400–450 knots.",
    knowCold: "Turboprop: lowest TSFC, ~400–450 kt ceiling on speed.",
    difficulty: 2,
    source: NOTES("Engine Types"),
  },
  {
    id: "eq-e6-010",
    type: "mcq",
    unit: "e6",
    conceptIds: ["e-turboprop"],
    prompt: "A disadvantage of the turboprop is",
    options: [
      "high TSFC",
      "poor performance off short runways",
      "limited speed of approximately 400–450 knots",
      "inability to lift heavy loads",
    ],
    answer: 2,
    explanation:
      "Turboprops are heavier and more complicated and limited to roughly 400–450 knots. Everything else in the list is a turboprop strength.",
    knowCold: "Turboprop tops out near 400–450 knots.",
    difficulty: 2,
    source: NOTES("Engine Types"),
  },
  {
    id: "eq-e6-011",
    type: "mcq",
    unit: "e6",
    conceptIds: ["e-turboprop-torquemeter"],
    prompt: "The turboprop torquemeter's inner (torque) shaft",
    options: [
      "provides a stationary reference",
      "carries the load from the gas turbine engine to the propeller",
      "drives the accessory gear box",
      "meters fuel to the primary manifold",
    ],
    answer: 1,
    explanation:
      "The inner torque shaft carries the load from the engine to the propeller; the reference outer shaft provides a stationary reference against which twist is measured.",
    knowCold: "Inner shaft carries load, outer shaft is the reference.",
    difficulty: 3,
    source: NOTES("Engine Types"),
  },
  {
    id: "eq-e6-012",
    type: "mcq",
    unit: "e6",
    conceptIds: ["e-turbofan"],
    prompt: "A disadvantage of the turbofan compared with the turbojet is",
    options: [
      "higher TSFC",
      "larger frontal area for drag and less efficiency at higher altitudes",
      "louder operation",
      "longer takeoff distance",
    ],
    answer: 1,
    explanation:
      "Turbofans have higher specific weight, a larger frontal area for drag, and are less efficient at higher altitudes. They are quieter, more efficient and take off shorter than turbojets.",
    knowCold: "Turbofan: quieter and thriftier, but fatter and worse up high.",
    difficulty: 2,
    source: NOTES("Engine Types"),
  },
  {
    id: "eq-e6-013",
    type: "mcq",
    unit: "e6",
    conceptIds: ["e-recip-propulsion"],
    prompt: "In a reciprocating engine, propeller blade angle and speed are controlled by the",
    options: ["fuel control unit", "governor", "reduction gear box", "torquemeter"],
    answer: 1,
    explanation:
      "All thrust comes from a propeller driven by crankshaft rotation, and a governor controls blade angle and propeller speed.",
    knowCold: "Recip prop: governor controls blade angle and speed.",
    difficulty: 2,
    source: NOTES("Engine Types"),
  },
  {
    id: "ecc-e6-014",
    type: "connectChain",
    unit: "e6",
    conceptIds: ["e-turboprop", "e-rgb"],
    prompt: "Trace turboprop power from the fire to the air.",
    trigger: "Fuel burns in the combustion chamber",
    steps: [
      "Turbine extracts energy from the expanding gases",
      "Shaft turns at high RPM with low torque",
      "Reduction gear box trades RPM for torque",
      "Propeller produces 90% of the thrust",
    ],
    explanation:
      "The gear box is the pivot of the whole arrangement: without it the propeller tips would go supersonic and efficiency would collapse.",
    knowCold: "Turbine → shaft → RGB → prop.",
    difficulty: 2,
    source: NOTES("Engine Types"),
  },
  {
    id: "eq-e6-015",
    type: "mcq",
    unit: "e6",
    conceptIds: ["e-turbofan"],
    prompt: "Fighter aircraft typically use ___ bypass ratio turbofans because",
    options: [
      "high, to maximise fuel efficiency",
      "low, to resemble turbojet performance while keeping turbofan efficiency",
      "high, to reduce noise near carriers",
      "low, to reduce engine weight only",
    ],
    answer: 1,
    explanation:
      "Fighters use low bypass ratios to resemble turbojet performance but with turbofan efficiency. Airliners and cargo aircraft use high bypass ratios.",
    knowCold: "Fighters low bypass, airliners high bypass.",
    difficulty: 2,
    source: NOTES("Engine Types"),
  },
];
