import type { Question, SourceReference } from "@/lib/types";

const ORG = (eo: string[]): SourceReference => ({
  document: "Flight Rules and Regulations Trainee Guide",
  chapter: "Federal Aviation Organization",
  eo,
});
const VIFR = (eo: string[]): SourceReference => ({
  document: "Flight Rules and Regulations Trainee Guide",
  chapter: "Visual / Instrument Flight Rules",
  eo,
});
const AIR = (eo: string[]): SourceReference => ({
  document: "Flight Rules and Regulations Trainee Guide",
  chapter: "Airspace and General Flight Rules",
  eo,
});

/**
 * Assessment depth.
 *
 * The first pass gave most concepts one question, which is enough for the
 * concept to look covered and not enough for the review queue to have anything
 * to resurface. These bring every Flight Rules concept to at least two.
 */
export const DEPTH_QUESTIONS: Question[] = [
  /* ================= f1 ================= */
  {
    id: "q-fd-001",
    type: "mcq",
    unit: "f1",
    conceptIds: ["fr-far"],
    prompt: "FAR Part 91 covers",
    options: [
      "certification of airmen",
      "general operating and flight rules",
      "air carrier operations",
      "aircraft airworthiness standards",
    ],
    answer: 1,
    explanation: "It is the FAA part that most concerns naval aviators, and it is regulatory.",
    knowCold: "Part 91: general operating and flight rules.",
    difficulty: 1,
    source: ORG(["2.345"]),
  },
  {
    id: "q-fd-002",
    type: "spotTheTrap",
    unit: "f1",
    conceptIds: ["fr-aim"],
    prompt: '"The Aeronautical Information Manual is a regulatory document."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. The AIM is FAA-published plain-language amplification of the regulations, and it is explicitly NON-regulatory. FAR Part 91 is the regulation.",
    knowCold: "The AIM explains. The FAR regulates.",
    difficulty: 2,
    source: ORG(["2.345"]),
  },
  {
    id: "q-fd-003",
    type: "mcq",
    unit: "f1",
    conceptIds: ["fr-flip"],
    prompt: "FLIP is published by",
    options: ["the FAA", "the Department of Defense", "the Navy alone", "ICAO"],
    answer: 1,
    explanation: "The DOD, for all branches, covering both IFR and VFR.",
    knowCold: "FLIP is DOD, all branches.",
    difficulty: 1,
    source: ORG(["2.346"]),
  },
  {
    id: "q-fd-004",
    type: "mcq",
    unit: "f1",
    conceptIds: ["fr-cnaf"],
    prompt: "CNAF M-3710.7 applies to",
    options: [
      "one aircraft model",
      "all naval aircraft worldwide",
      "all Department of Defense aircraft",
      "all civil and military aircraft in US airspace",
    ],
    answer: 1,
    explanation:
      "It is the NATOPS General Flight and Operating Instructions Manual. The aircraft-specific document is the model NATOPS; the all-services document is FLIP.",
    knowCold: "CNAF: every naval aircraft, everywhere.",
    difficulty: 2,
    source: ORG(["2.346"]),
  },
  {
    id: "q-fd-005",
    type: "mcq",
    unit: "f1",
    conceptIds: ["fr-natops"],
    prompt: "Which publication has the HIGHEST priority?",
    options: ["FAR Part 91", "FLIP", "CNAF M-3710.7", "The aircraft NATOPS manual"],
    answer: 3,
    explanation:
      "NATOPS → CNAF M-3710.7 → FLIP → FAR Part 91. The more specific the document, the higher it ranks.",
    knowCold: "NATOPS wins.",
    difficulty: 2,
    source: ORG(["2.347"]),
  },
  {
    id: "q-fd-006",
    type: "mcq",
    unit: "f1",
    conceptIds: ["fr-atc"],
    prompt: "Air Traffic Control is responsible for",
    options: [
      "publishing the FAR",
      "enforcing the FAR, approving flight plans and granting all clearances",
      "issuing NOTAMs only",
      "certifying aircrew",
    ],
    answer: 1,
    explanation:
      "Four subordinate agencies do the work: FSS, control tower, approach control and ARTCC.",
    knowCold: "ATC enforces, approves and clears.",
    difficulty: 2,
    source: ORG(["2.349"]),
  },
  {
    id: "q-fd-007",
    type: "mcq",
    unit: "f1",
    conceptIds: ["fr-fss"],
    prompt: "Search and rescue coordination is a function of",
    options: ["the control tower", "approach control", "the Flight Service Station", "ARTCC"],
    answer: 2,
    explanation:
      "The FSS, also called base ops, handles briefings, flight plan filing, NOTAMs, SAR and flight following.",
    knowCold: "FSS: brief, file, NOTAM, SAR, following.",
    difficulty: 2,
    source: ORG(["2.349"]),
  },
  {
    id: "q-fd-008",
    type: "mcq",
    unit: "f1",
    conceptIds: ["fr-tower"],
    prompt: "The control tower is responsible for",
    options: [
      "air traffic only, at and around the airport",
      "both air AND ground traffic at and around the airport",
      "all instrument traffic in the terminal area",
      "positive control of IFR aircraft en route",
    ],
    answer: 1,
    explanation:
      "Its job is the safe, orderly and expeditious flow of traffic at and around the airport — which includes aircraft on the ground.",
    knowCold: "Tower owns the field, air and ground.",
    difficulty: 2,
    source: ORG(["2.349"]),
  },
  {
    id: "q-fd-009",
    type: "mcq",
    unit: "f1",
    conceptIds: ["fr-approach"],
    prompt: "Approach control is responsible for",
    options: [
      "all instrument flight in the terminal area",
      "en route IFR traffic",
      "traffic on the airport surface",
      "weather briefings",
    ],
    answer: 0,
    explanation:
      "Also called TRACON, it may serve one or more airfields. Center handles en route.",
    knowCold: "Approach = terminal IFR.",
    difficulty: 2,
    source: ORG(["2.349"]),
  },
  {
    id: "q-fd-010",
    type: "mcq",
    unit: "f1",
    conceptIds: ["fr-artcc"],
    prompt: "ARTCC provides VFR aircraft with",
    options: [
      "positive control at all times",
      "advisories when workload permits",
      "no service whatsoever",
      "mandatory separation from all traffic",
    ],
    answer: 1,
    explanation:
      "Center exercises positive control of IFR aircraft en route, and offers advisories to VFR aircraft as workload allows.",
    knowCold: "Center: positive control IFR, advisories VFR.",
    difficulty: 3,
    source: ORG(["2.349"]),
  },
  {
    id: "q-fd-011",
    type: "mcq",
    unit: "f1",
    conceptIds: ["fr-notam"],
    prompt: "Information is published as a NOTAM when it is",
    options: [
      "permanent and of general interest",
      "temporary, or not known early enough to publicise by other means",
      "classified",
      "applicable only to military aircraft",
    ],
    answer: 1,
    explanation:
      "It covers the establishment, condition or change of any aeronautical facility, service, procedure or hazard meeting that description.",
    knowCold: "NOTAM: temporary, or too late to publish otherwise.",
    difficulty: 2,
    source: ORG(["2.349"]),
  },

  /* ================= f2 ================= */
  {
    id: "q-fd-012",
    type: "mcq",
    unit: "f2",
    conceptIds: ["fr-pic"],
    prompt: "Under CNAF M-3710.7, the pilot in command is responsible for",
    options: [
      "the aircraft only",
      "the safe, orderly flight of the aircraft and the well-being of the crew",
      "compliance with ATC instructions in all circumstances",
      "the flight plan only",
    ],
    answer: 1,
    explanation:
      "The FAR states it differently — directly responsible for, and final authority as to, the operation of that aircraft. Together they cover the aircraft, the flight and the people in it.",
    knowCold: "Aircraft, flight, crew.",
    difficulty: 2,
    source: ORG(["2.350"]),
  },
  {
    id: "q-fd-013",
    type: "mcq",
    unit: "f2",
    conceptIds: ["fr-pic"],
    prompt: "Under the FAR, the pilot in command is",
    options: [
      "subordinate to ATC in all cases",
      "directly responsible for, and the final authority as to, the operation of that aircraft",
      "responsible only for crew safety",
      "responsible only once airborne",
    ],
    answer: 1,
    explanation:
      "'Final authority' is the operative phrase, and it is what makes emergency deviation possible.",
    knowCold: "Final authority as to the operation of that aircraft.",
    difficulty: 2,
    source: ORG(["2.350"]),
  },
  {
    id: "q-fd-014",
    type: "mcq",
    unit: "f2",
    conceptIds: ["fr-flight-plan"],
    prompt: "A flight plan may be filed",
    options: [
      "only at base operations",
      "at base operations or a Flight Service Station",
      "only with the control tower",
      "only with ARTCC",
    ],
    answer: 1,
    explanation:
      "Its primary purpose is to give departure, destination and intermediate agencies the baseline for finding you if communications or the aircraft are lost.",
    knowCold: "Base ops or an FSS.",
    difficulty: 1,
    source: ORG(["2.352"]),
  },
  {
    id: "q-fd-015",
    type: "mcq",
    unit: "f2",
    conceptIds: ["fr-flight-plan"],
    prompt: "The primary purpose of a flight plan is to",
    options: [
      "obtain an IFR clearance",
      "provide the baseline for locating an aircraft whose communications or position are lost",
      "reserve airspace along the route",
      "satisfy the destination airfield's arrival requirements",
    ],
    answer: 1,
    explanation:
      "A flight plan is not a clearance. Its job becomes obvious only when something goes wrong.",
    knowCold: "The flight plan exists so someone can find you.",
    difficulty: 2,
    source: ORG(["2.352"]),
  },
  {
    id: "q-fd-016",
    type: "mcq",
    unit: "f2",
    conceptIds: ["fr-icing-thunderstorms"],
    prompt: "Flights shall be planned to circumvent forecast areas of",
    options: [
      "turbulence and low ceilings",
      "atmospheric icing and thunderstorm conditions",
      "crosswinds and precipitation",
      "any cloud whatsoever",
    ],
    answer: 1,
    explanation:
      "Icing and thunderstorms specifically, qualified by 'whenever practicable'.",
    knowCold: "Circumvent icing and thunderstorms when practicable.",
    difficulty: 2,
    source: ORG(["2.353"]),
  },
  {
    id: "q-fd-017",
    type: "mcq",
    unit: "f2",
    conceptIds: ["fr-authorized-airfields"],
    prompt: "Landing at a civil airfield requires",
    options: [
      "no coordination if fuel is available",
      "prior permission",
      "only a filed flight plan",
      "approval from ARTCC",
    ],
    answer: 1,
    explanation:
      "Prior permission is required, and the pilot must know local procedures, runway length and load bearing capacity, DoD contract services and security arrangements.",
    knowCold: "Authorized airfields: prior permission required.",
    difficulty: 2,
    source: ORG(["2.355"]),
  },
  {
    id: "q-fd-018",
    type: "mcq",
    unit: "f2",
    conceptIds: ["fr-fuel-purchase"],
    prompt: "Fuel shall be purchased from military or government contract sources EXCEPT for",
    options: [
      "any flight over 500 nm",
      "mission requirements, emergency landings and alternate landings",
      "training flights",
      "flights outside the continental United States",
    ],
    answer: 1,
    explanation: "Those three exceptions are the stated list.",
    knowCold: "Mission, emergency, alternate.",
    difficulty: 2,
    source: ORG(["2.355"]),
  },
  {
    id: "q-fd-019",
    type: "mcq",
    unit: "f2",
    conceptIds: ["fr-closing-plans"],
    prompt: "A flight plan may be closed",
    options: [
      "only in writing at base operations",
      "verbally with the tower or base ops, or with an FSS by any means available",
      "only with the destination control tower",
      "automatically on landing",
    ],
    answer: 1,
    explanation:
      "Both the pilot in command AND the formation leader are responsible for closing out flight plans.",
    knowCold: "Verbally with tower or base ops, or any means with an FSS.",
    difficulty: 2,
    source: ORG(["2.355"]),
  },

  /* ================= f3 ================= */
  {
    id: "q-fd-020",
    type: "mcq",
    unit: "f3",
    conceptIds: ["fr-harness"],
    prompt: "Inertial reels, when provided, shall be manually locked",
    options: [
      "for the entire flight",
      "for takeoffs, landings and when high G forces are anticipated",
      "only during aerobatics",
      "only when the autopilot is engaged",
    ],
    answer: 1,
    explanation:
      "Except where locking the reel would itself be detrimental to safety. Belts and harnesses are worn and tightened before takeoff and until the flight is complete.",
    knowCold: "Reels locked: takeoff, landing, high G.",
    difficulty: 2,
    source: ORG(["2.356"]),
  },
  {
    id: "q-fd-021",
    type: "mcq",
    unit: "f3",
    conceptIds: ["fr-ppe"],
    prompt: "Which of the following is part of the minimum aircrew personal protective equipment?",
    options: ["A parachute", "A survival knife", "A portable oxygen bottle", "A life raft"],
    answer: 1,
    explanation:
      "The list is protective helmet, safety or flyer boots, fire-resistant suit and gloves, survival knife, personal survival kit, signal device, survival radio, emergency beacon, flashlight and identification tags.",
    knowCold: "Helmet, boots, suit, gloves, knife, kit, signal, radio, beacon, light, tags.",
    difficulty: 2,
    source: ORG(["2.356"]),
  },
  {
    id: "q-fd-022",
    type: "mcq",
    unit: "f3",
    conceptIds: ["fr-life-rafts"],
    prompt: "Life rafts must have sufficient capacity for",
    options: [
      "the crew only",
      "all passengers and crew",
      "half the persons aboard",
      "the pilot in command only",
    ],
    answer: 1,
    explanation:
      "Carried whenever there is significant risk of water entry during a mishap.",
    knowCold: "Everyone aboard.",
    difficulty: 1,
    source: ORG(["2.356"]),
  },
  {
    id: "q-fd-023",
    type: "mcq",
    unit: "f3",
    conceptIds: ["fr-oxygen"],
    prompt: "Supplemental oxygen is required when",
    options: [
      "aircraft altitude exceeds 10,000 ft",
      "CABIN altitude exceeds 10,000 ft",
      "aircraft altitude exceeds 12,000 ft",
      "cabin altitude exceeds 13,000 ft",
    ],
    answer: 1,
    explanation:
      "It is the cabin altitude that matters, not the aircraft's. A pressurized aircraft at 30,000 ft may have a cabin altitude well below the trigger.",
    whyWrong: "Aircraft altitude is the trap. The rule is written in cabin altitude.",
    knowCold: "Cabin altitude above 10,000 ft.",
    difficulty: 3,
    source: ORG(["2.357"]),
  },
  {
    id: "q-fd-024",
    type: "mcq",
    unit: "f3",
    conceptIds: ["fr-oxygen-tacjet"],
    prompt: "In tactical jet and tactical jet training aircraft, oxygen is used",
    options: [
      "above 10,000 ft only",
      "from takeoff to landing",
      "only when the cabin is depressurized",
      "at the pilot's discretion",
    ],
    answer: 1,
    explanation: "The whole flight, regardless of altitude.",
    knowCold: "Tac jets: takeoff to landing.",
    difficulty: 2,
    source: ORG(["2.357"]),
  },
  {
    id: "q-fd-025",
    type: "mcq",
    unit: "f3",
    conceptIds: ["fr-performance-factors"],
    prompt: "Human performance in the cockpit is degraded by",
    options: [
      "fatigue alone",
      "a range of factors including fatigue, alcohol, medication and recent immunization",
      "altitude alone",
      "workload alone",
    ],
    answer: 1,
    explanation:
      "Which is why CNAF sets explicit limits on each: 8 hours sleep in 24, an 18-hour crew day, 12 hours from alcohol, 450 mg of caffeine, and grounding periods after immunization and blood donation.",
    knowCold: "Rest, alcohol, drugs, caffeine, immunization, blood.",
    difficulty: 1,
    source: ORG(["2.358"]),
  },
  {
    id: "q-fd-026",
    type: "mcq",
    unit: "f3",
    conceptIds: ["fr-crew-rest"],
    prompt: "Crew rest requires how much uninterrupted sleep in each 24-hour period?",
    options: ["6 hours", "8 hours", "10 hours", "12 hours"],
    answer: 1,
    explanation: "8 hours of uninterrupted sleep, and the crew day should not exceed 18 hours.",
    knowCold: "8 hours sleep, 18-hour crew day.",
    difficulty: 1,
    source: ORG(["2.358"]),
  },
  {
    id: "q-fd-027",
    type: "spotTheTrap",
    unit: "f3",
    conceptIds: ["fr-alcohol"],
    prompt: '"The alcohol restriction is measured from 12 hours before takeoff."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. It is 12 hours from the mission BRIEF or flight planning, which comes earlier than takeoff.",
    knowCold: "12 hours from the brief, not the takeoff.",
    difficulty: 3,
    source: ORG(["2.359"]),
  },
  {
    id: "q-fd-028",
    type: "mcq",
    unit: "f3",
    conceptIds: ["fr-immunization-blood"],
    prompt: "Following an immunization, aircrew are grounded for",
    options: ["4 hours", "12 hours", "24 hours", "4 days"],
    answer: 1,
    explanation: "12 hours after immunization; 4 days after donating a pint of blood.",
    whyWrong: "4 days is the blood donation figure.",
    knowCold: "Immunization 12 hours, blood 4 days.",
    difficulty: 2,
    source: ORG(["2.359"]),
  },

  /* ================= f4 ================= */
  {
    id: "q-fd-029",
    type: "mcq",
    unit: "f4",
    conceptIds: ["fr-airport-signs"],
    prompt: "White letters on a red background indicate",
    options: [
      "a location sign",
      "a mandatory instruction sign",
      "a direction sign",
      "a destination sign",
    ],
    answer: 1,
    explanation:
      "Mandatory instruction signs mark entrances to runways and critical areas.",
    knowCold: "Red with white letters: mandatory.",
    difficulty: 2,
    source: VIFR(["2.361"]),
  },
  {
    id: "q-fd-030",
    type: "mcq",
    unit: "f4",
    conceptIds: ["fr-displaced-threshold"],
    prompt: "Pavement before a displaced threshold may be used for",
    options: [
      "landing only",
      "takeoff and rollout, but not landing",
      "all operations",
      "no operations at all",
    ],
    answer: 1,
    explanation:
      "It is available for takeoff and for landing rollout, but you may not touch down on it.",
    knowCold: "Displaced threshold: takeoff and rollout, never landing.",
    difficulty: 2,
    source: VIFR(["2.361"]),
  },
  {
    id: "q-fd-031",
    type: "mcq",
    unit: "f4",
    conceptIds: ["fr-waveoff"],
    prompt: "Compliance with a waveoff is",
    options: [
      "advisory",
      "mandatory, except in an emergency",
      "mandatory in all circumstances without exception",
      "required only from the LSO",
    ],
    answer: 1,
    explanation:
      "A waveoff means DO NOT LAND. Any high intensity red lights at the approach end should be treated as a waveoff signal.",
    knowCold: "Waveoff is mandatory. The only exception is your own emergency.",
    difficulty: 2,
    source: VIFR(["2.361"]),
  },
  {
    id: "q-fd-032",
    type: "mcq",
    unit: "f4",
    conceptIds: ["fr-beacon"],
    prompt: "A MILITARY airport rotating beacon shows",
    options: [
      "alternating white and green",
      "dual-peaked white flashes alternating with a green flash",
      "alternating white and red",
      "a steady green light",
    ],
    answer: 1,
    explanation:
      "Two quick white flashes is what marks the field as military. A civilian beacon alternates solid white with solid green.",
    knowCold: "Two quick whites = military field.",
    difficulty: 2,
    source: VIFR(["2.361"]),
  },
  {
    id: "q-fd-033",
    type: "mcq",
    unit: "f4",
    conceptIds: ["fr-iflols"],
    prompt: "On IFLOLS, being ON glideslope is indicated by",
    options: [
      "the amber ball below the green datum bar",
      "the amber ball aligned with the green datum bar",
      "a red ball above the datum",
      "all lights extinguished",
    ],
    answer: 1,
    explanation:
      "Below the datum the ball drops and turns red; above it, the ball rises.",
    knowCold: "Ball on the datum.",
    difficulty: 2,
    source: VIFR(["2.361"]),
  },
  {
    id: "q-fd-034",
    type: "mcq",
    unit: "f4",
    conceptIds: ["fr-sgsi"],
    prompt: "SGSI is used for",
    options: [
      "shipboard helicopter operations",
      "carrier fixed-wing recovery",
      "instrument approaches ashore",
      "night formation flying",
    ],
    answer: 0,
    explanation:
      "Red is low, the amber-red interface is on glideslope, amber slightly above and green well above.",
    knowCold: "SGSI: shipboard helos.",
    difficulty: 2,
    source: VIFR(["2.361"]),
  },
  {
    id: "q-fd-035",
    type: "mcq",
    unit: "f4",
    conceptIds: ["fr-als"],
    prompt: "Approach light systems begin at the",
    options: [
      "runway midpoint",
      "landing threshold, extending into the approach area",
      "far end of the runway",
      "outer marker",
    ],
    answer: 1,
    explanation:
      "They provide the transition from instrument flight to visual flight for landing.",
    knowCold: "ALS starts at the threshold and reaches outward.",
    difficulty: 2,
    source: VIFR(["2.361"]),
  },

  /* ================= f5 ================= */
  {
    id: "q-fd-036",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-vmc"],
    prompt: "VMC describes",
    options: ["a set of rules", "the weather", "a type of flight plan", "an airspace class"],
    answer: 1,
    explanation:
      "VMC and IMC describe the weather. VFR and IFR describe the rules. Keeping the pairs apart is the whole point of this lesson.",
    knowCold: "VMC and IMC are weather.",
    difficulty: 1,
    source: VIFR(["2.362"]),
  },
  {
    id: "q-fd-037",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-imc"],
    prompt:
      "CNAF M-3710.7 adds a condition under which IMC exists regardless of the reported numbers:",
    options: [
      "any time the aircraft is above 10,000 ft",
      "any time a visible horizon is not distinguishable",
      "any time the flight is at night",
      "any time an IFR flight plan is filed",
    ],
    answer: 1,
    explanation:
      "No distinguishable horizon means IMC even if visibility and ceiling look adequate.",
    knowCold: "No horizon means IMC.",
    difficulty: 3,
    source: VIFR(["2.362"]),
  },
  {
    id: "q-fd-038",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-vfr-ifr-terms"],
    prompt: "Besides naming a set of rules, 'VFR' is also used to describe",
    options: [
      "weather, the rules an airport is operating under, and a type of flight plan",
      "airspace classes only",
      "aircraft equipment fits",
      "pilot qualification levels",
    ],
    answer: 0,
    explanation:
      "Four distinct uses of one term. Weather relative to 1,000/3, the airport's operating state, the flight plan type, and the rules themselves.",
    knowCold: "One word, four jobs.",
    difficulty: 3,
    source: VIFR(["2.362"]),
  },
  {
    id: "q-fd-039",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-forecast"],
    prompt: "A weather forecast is valid for",
    options: [
      "an unlimited area and time",
      "a specific area for a specific time period",
      "the departure field only",
      "24 hours from issue, anywhere",
    ],
    answer: 1,
    explanation:
      "Which is why the VFR filing and alternate rules are both written as windows: ETA plus or minus one hour.",
    knowCold: "Specific area, specific period.",
    difficulty: 1,
    source: VIFR(["2.362"]),
  },
  {
    id: "q-fd-040",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-see-and-avoid"],
    prompt: "The requirement to see and avoid other aircraft applies",
    options: [
      "only under VFR",
      "only under IFR",
      "regardless of whether the operation is IFR or VFR, when weather permits",
      "only in Class G airspace",
    ],
    answer: 2,
    explanation:
      "Being on an IFR clearance does not transfer the lookout to ATC.",
    knowCold: "See and avoid applies to everyone the weather allows.",
    difficulty: 2,
    source: VIFR(["2.362"]),
  },
  {
    id: "q-fd-041",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-basic-vfr"],
    prompt: "Basic VFR cloud clearance BELOW a cloud is",
    options: ["500 ft", "1,000 ft", "2,000 ft", "clear of clouds"],
    answer: 0,
    explanation: "1,000 ft above, 500 ft below, 2,000 ft horizontally, 3 SM visibility.",
    whyWrong: "1,000 ft is the ABOVE figure; 2,000 ft is horizontal.",
    knowCold: "1,000 above, 500 below, 2,000 horizontal, 3 SM.",
    difficulty: 2,
    source: VIFR(["2.363"]),
  },
  {
    id: "q-fd-042",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-vfr-destination"],
    prompt: "The destination forecast window for filing VFR is",
    options: [
      "ETA to ETA plus 2 hours",
      "one hour before through one hour after ETA",
      "the whole day of the flight",
      "ETD to ETA",
    ],
    answer: 1,
    explanation: "It must indicate at least a 1,000 ft ceiling and 3 SM visibility throughout.",
    knowCold: "ETA ± 1 hour.",
    difficulty: 2,
    source: VIFR(["2.363"]),
  },
  {
    id: "q-fd-043",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-vfr-enroute"],
    prompt: "En route under VFR, you must maintain",
    options: [
      "1,000 ft and 3 SM everywhere",
      "VMC according to the criteria for the class of airspace you are in",
      "clear of clouds at all times",
      "the destination's minimums",
    ],
    answer: 1,
    explanation:
      "The numbers change with the airspace — Class B is clear of clouds, Class E above 10,000 MSL is 1,000/1,000/1 and 5 SM.",
    knowCold: "The airspace you are in sets the numbers.",
    difficulty: 2,
    source: VIFR(["2.364"]),
  },
  {
    id: "q-fd-044",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-vfr-fuel"],
    prompt: "VFR fuel requirements are enough to reach the first point of intended landing plus",
    options: [
      "10% of planned fuel, never less than 20 minutes",
      "20% of planned fuel, never less than 10 minutes",
      "30 minutes fixed",
      "45 minutes fixed",
    ],
    answer: 0,
    explanation: "The 20 minutes is a floor under the 10%, not an alternative to it.",
    knowCold: "10%, minimum 20 minutes.",
    difficulty: 2,
    source: VIFR(["2.364"]),
  },
  {
    id: "q-fd-045",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-ifr-general"],
    prompt: "To operate IFR in controlled airspace you must have",
    options: [
      "a filed IFR flight plan only",
      "an ATC clearance only",
      "both a filed IFR flight plan and an appropriate ATC clearance",
      "neither, provided you remain in VMC",
    ],
    answer: 2,
    explanation:
      "Both. CNAF adds that naval aircraft shall be flown IFR whenever conditions preclude VFR flight.",
    knowCold: "Plan AND clearance.",
    difficulty: 2,
    source: VIFR(["2.365"]),
  },
  {
    id: "q-fd-046",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-vfr-on-top"],
    prompt: "An aircraft cleared VFR-on-top must comply with",
    options: [
      "IFR cruising altitudes",
      "VFR cruising altitudes",
      "any altitude the pilot selects",
      "the altitude last assigned by ATC",
    ],
    answer: 1,
    explanation:
      "The pilot picks the altitude, but it must be an appropriate VFR cruising altitude — and VFR visibility and cloud clearance criteria still apply.",
    knowCold: "IFR clearance, VFR altitudes.",
    difficulty: 3,
    source: VIFR(["2.366"]),
  },
  {
    id: "q-fd-047",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-missed-approach"],
    prompt: "A missed approach directed by a controller is",
    options: [
      "advisory",
      "mandatory",
      "mandatory only below decision height",
      "at the pilot's discretion",
    ],
    answer: 1,
    explanation:
      "Execution is mandatory when directed. Separately, pilots may execute a missed approach at their own discretion at any time.",
    knowCold: "Directed missed approach: mandatory. Pilot's own: any time.",
    difficulty: 2,
    source: VIFR(["2.367"]),
  },
  {
    id: "q-fd-048",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-ifr-fuel"],
    prompt: "With an alternate required, IFR fuel must cover takeoff to the approach fix serving the destination, then to the alternate, plus",
    options: [
      "20% of planned fuel, minimum 30 minutes",
      "10% of planned fuel, never less than 20 minutes",
      "a fixed 45 minutes",
      "no additional reserve",
    ],
    answer: 1,
    explanation: "With no alternate required, the fuel requirement is the same as VFR.",
    knowCold: "Same reserve either way: 10%, minimum 20 minutes.",
    difficulty: 3,
    source: VIFR(["2.367"]),
  },

  /* ================= f6 ================= */
  {
    id: "q-fd-049",
    type: "mcq",
    unit: "f6",
    conceptIds: ["fr-aerobatic-definition"],
    prompt: "Which acceleration threshold defines aerobatic flight?",
    options: ["1.5 g", "2.0 g", "3.0 g", "4.0 g"],
    answer: 1,
    explanation:
      "Greater than 2.0 g, or bank greater than 60°, or pitch greater than ±45°, intentionally.",
    knowCold: "60, 45, 2.0.",
    difficulty: 2,
    source: VIFR(["2.369"]),
  },
  {
    id: "q-fd-050",
    type: "mcq",
    unit: "f6",
    conceptIds: ["fr-unusual-maneuvers"],
    prompt: "Individual commands may set aerobatic minimums that are",
    options: [
      "less restrictive than the FAR",
      "more restrictive than the FAR",
      "identical to the FAR in all cases",
      "advisory only",
    ],
    answer: 1,
    explanation:
      "The FAR floor is 1,500 ft AGL; the Training Command minimum is 5,000 ft AGL. CNAF adds that aerobatics shall not be performed if the aircraft's NATOPS prohibits them.",
    knowCold: "Commands may be stricter, never looser.",
    difficulty: 2,
    source: VIFR(["2.371"]),
  },

  /* ================= f7 ================= */
  {
    id: "q-fd-051",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-controlled"],
    prompt: "In controlled airspace, ATC service is provided to",
    options: [
      "IFR flights only",
      "IFR flights and to VFR flights in accordance with the airspace classification",
      "VFR flights only",
      "no one — the term refers to airspace dimensions",
    ],
    answer: 1,
    explanation:
      "'Controlled' means service is provided there. What you actually receive depends on the class and on how you are flying.",
    knowCold: "Controlled means service is available, not that you are watched.",
    difficulty: 2,
    source: AIR(["2.372"]),
  },
  {
    id: "q-fd-052",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-uncontrolled"],
    prompt: "In uncontrolled airspace, ATC has",
    options: [
      "full authority but no responsibility",
      "neither the authority nor the responsibility to control traffic",
      "responsibility but no authority",
      "the same authority as in Class E",
    ],
    answer: 1,
    explanation: "Class G is the only uncontrolled class.",
    knowCold: "Class G: no authority, no responsibility.",
    difficulty: 2,
    source: AIR(["2.372"]),
  },
  {
    id: "q-fd-053",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-class-g"],
    prompt: "Class G airspace generally extends up to",
    options: ["700 ft AGL", "1,200 ft AGL", "2,500 ft AGL", "10,000 ft MSL"],
    answer: 1,
    explanation:
      "Usually below 1,200 ft AGL, where radar coverage is incomplete or air traffic is minimal.",
    knowCold: "Class G: usually below 1,200 AGL.",
    difficulty: 2,
    source: AIR(["2.374"]),
  },
  {
    id: "q-fd-054",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-jet-routes"],
    prompt: "Jet routes extend from",
    options: [
      "1,200 ft AGL to 18,000 ft MSL",
      "18,000 ft MSL to FL450",
      "FL180 to FL600",
      "the surface to FL450",
    ],
    answer: 1,
    explanation: "Victor airways run from 1,200 AGL to 18,000 MSL and are 8 nm wide.",
    knowCold: "Victor below 18,000, jet routes above, to FL450.",
    difficulty: 2,
    source: AIR(["2.375"]),
  },
  {
    id: "q-fd-055",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-prohibited-area"],
    prompt: "Flight within a prohibited area is",
    options: [
      "permitted with prior approval from the controlling agency",
      "prohibited",
      "permitted when the area is inactive",
      "permitted under IFR only",
    ],
    answer: 1,
    explanation:
      "Restricted areas are the ones you may enter with permission. Prohibited means prohibited.",
    knowCold: "Prohibited forbids. Restricted permits.",
    difficulty: 2,
    source: AIR(["2.377"]),
  },
  {
    id: "q-fd-056",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-controlled-firing"],
    prompt: "In a controlled firing area, activities are",
    options: [
      "conducted regardless of aircraft in the vicinity",
      "suspended when an aircraft approaches",
      "restricted to night hours",
      "coordinated by ARTCC in real time with each pilot",
    ],
    answer: 1,
    explanation:
      "It is the one special use airspace that stops for you, which is why it imposes no restriction on the pilot.",
    knowCold: "Controlled firing stops for you.",
    difficulty: 3,
    source: AIR(["2.377"]),
  },

  /* ================= f8 ================= */
  {
    id: "q-fd-057",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-relative-position"],
    prompt: "At night you see only a GREEN light on another aircraft. It is",
    options: [
      "head-on, opposite direction",
      "crossing left to right",
      "crossing right to left",
      "tail on, same direction",
    ],
    answer: 1,
    explanation:
      "Green is on the right wing, so seeing green alone means you are looking at its right side as it crosses from your left to your right.",
    knowCold: "Green only: left to right.",
    difficulty: 3,
    source: AIR(["2.379"]),
  },
  {
    id: "q-fd-058",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-anticollision"],
    prompt: "CNAF permits anti-collision lights to be turned off",
    options: [
      "at any time at the pilot's discretion",
      "in cloud, to prevent distracting the pilot, and where they adversely affect ground operations",
      "only on the ground",
      "never",
    ],
    answer: 1,
    explanation:
      "They are otherwise used from before engine start until engine shutdown.",
    knowCold: "Off in cloud, when distracting, or when they hurt ground ops.",
    difficulty: 3,
    source: AIR(["2.378"]),
  },
  {
    id: "q-fd-059",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-altitude-congested"],
    prompt: "Over a congested area the minimum altitude is 1,000 ft above the highest obstacle within",
    options: ["500 ft", "1,000 ft", "2,000 ft", "1 nautical mile"],
    answer: 2,
    explanation:
      "A 2,000 ft horizontal radius of the aircraft, and 1,000 ft above whatever the tallest thing inside that radius is.",
    knowCold: "1,000 up, 2,000 out.",
    difficulty: 2,
    source: AIR(["2.381"]),
  },
  {
    id: "q-fd-060",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-altitude-other"],
    prompt: "Over other than congested areas the FAR minimum altitude is",
    options: ["300 ft AGL", "500 ft AGL", "1,000 ft AGL", "2,000 ft AGL"],
    answer: 1,
    explanation:
      "Over open water or sparsely populated areas the 500 ft becomes a distance from any person, vessel, vehicle or structure rather than a height.",
    knowCold: "500 ft AGL, or 500 ft from things over water.",
    difficulty: 2,
    source: AIR(["2.381"]),
  },
  {
    id: "q-fd-061",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-holding-speed"],
    prompt: "Maximum holding airspeed for a turbojet at or below 14,000 ft MSL is",
    options: ["175 KIAS", "200 KIAS", "230 KIAS", "265 KIAS"],
    answer: 2,
    explanation:
      "230 KIAS below 14,000 MSL and 265 KIAS above. Props hold at 175 KIAS and helicopters at 80 KIAS.",
    knowCold: "Props 175, jets 230/265, helos 80.",
    difficulty: 3,
    source: AIR(["2.382"]),
  },
  {
    id: "q-fd-062",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-cnaf-speed-exemption"],
    prompt: "The FAA airspeed exemption for naval aircraft exists to accommodate",
    options: [
      "fuel economy",
      "high-performance aircraft and military missions",
      "formation flight only",
      "training flights only",
    ],
    answer: 1,
    explanation:
      "Examples include climbs and descents from traffic patterns, designated training areas, authorised low-level routes, restricted areas and MOAs, and cases where crew or aircraft safety requires it.",
    knowCold: "The exemption is about performance and mission.",
    difficulty: 2,
    source: AIR(["2.382"]),
  },
  {
    id: "q-fd-063",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-careless"],
    prompt: "Under CNAF, naval aircraft shall be flown in a manner that is safe and non-threatening to",
    options: [
      "other aircraft only",
      "both people and property on the ground",
      "military personnel only",
      "civil aircraft only",
    ],
    answer: 1,
    explanation:
      "And particular effort shall be taken so that individuals do not BELIEVE they or their property are endangered — the test is the observer's perception.",
    knowCold: "People and property, and what they believe.",
    difficulty: 2,
    source: AIR(["2.383", "2.384"]),
  },
  {
    id: "q-fd-064",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-wildlife"],
    prompt: "The 3,000 ft AGL altitude over known wildlife habitations exists to",
    options: [
      "improve engine-out glide range",
      "prevent frightening wild fowl or driving them from feeding grounds",
      "reduce bird strike risk to the aircraft",
      "comply with noise abatement procedures",
    ],
    answer: 1,
    explanation:
      "It is written for the birds' benefit, not the aircraft's, and applies conditions permitting.",
    knowCold: "3,000 AGL, for the wildlife's sake.",
    difficulty: 2,
    source: AIR(["2.385"]),
  },
  {
    id: "q-fd-065",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-commercial-avoidance"],
    prompt:
      "Naval aircraft must avoid commercial carriers and civil aircraft because those aircraft are",
    options: [
      "operating under different regulations",
      "comparatively difficult to manoeuvre and relatively blind",
      "always at a higher altitude",
      "not equipped with transponders",
    ],
    answer: 1,
    explanation:
      "Hence 500 ft vertically and/or 1 SM laterally, and no erratic or aerobatic flight in their vicinity.",
    knowCold: "They cannot manoeuvre and cannot see you.",
    difficulty: 3,
    source: AIR(["2.385"]),
  },
  {
    id: "q-fd-066",
    type: "spotTheTrap",
    unit: "f8",
    conceptIds: ["fr-flat-hatting"],
    prompt:
      '"Any low-altitude, high-speed manoeuvre is flat hatting, regardless of the reason it is flown."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. The definition turns on 'for thrill purposes'. The same profile flown for a mission — an authorised low-level route, for instance — is not flat hatting.",
    knowCold: "It is flat hatting when it is for thrills.",
    difficulty: 3,
    source: AIR(["2.386"]),
  },
];
