import type { Question, SourceReference } from "@/lib/types";

const ORG = (eo: string[]): SourceReference => ({
  document: "Flight Rules and Regulations Trainee Guide",
  chapter: "Federal Aviation Organization",
  eo,
});
const VIFR = (eo: string[]): SourceReference => ({
  document: "Flight Rules and Regulations Trainee Guide",
  chapter: "Visual / Instrument Flight Rules",
  eo,
});

/** Units f3 (safety and the human) and f4 (the airport). */
export const F3_QUESTIONS: Question[] = [
  {
    id: "fq-f3-005",
    type: "mcq",
    unit: "f3",
    conceptIds: ["fr-crew-rest"],
    prompt:
      "Crew rest must include an opportunity for ___ of uninterrupted sleep, and crew day should not exceed ___.",
    options: ["6 hours, 12 hours", "8 hours, 18 hours", "8 hours, 24 hours", "10 hours, 16 hours"],
    answer: 1,
    explanation:
      "Eight hours of uninterrupted sleep in every 24-hour period, and a crew day that should not exceed 18 hours.",
    knowCold: "8 hours sleep, 18 hour crew day.",
    difficulty: 2,
    officialStyle: true,
    source: ORG(["2.359"]),
  },
  {
    id: "fq-f3-006",
    type: "mcq",
    unit: "f3",
    conceptIds: ["fr-alcohol"],
    prompt:
      "Consumption of alcohol is prohibited within how many hours of any mission brief or flight planning?",
    options: ["6", "12", "18", "24"],
    answer: 1,
    explanation:
      "Twelve hours — and note the clock runs from the BRIEF or flight planning, not from takeoff. Crews must also be free of the effects of alcohol prior to flight.",
    knowCold: "12 hours from the brief, not from takeoff.",
    difficulty: 2,
    officialStyle: true,
    source: ORG(["2.359"]),
  },
  {
    id: "fq-f3-007",
    type: "mcq",
    unit: "f3",
    conceptIds: ["fr-caffeine-drugs"],
    prompt: "What is the recommended maximum daily intake of caffeine?",
    options: ["150 mg", "450 mg, roughly three to four cups of coffee", "1,000 mg", "There is no recommendation"],
    answer: 1,
    explanation: "450 mg per day is the recommended maximum, about three to four cups of coffee.",
    knowCold: "450 mg of caffeine a day.",
    difficulty: 1,
    officialStyle: true,
    source: ORG(["2.359"]),
  },
  {
    id: "fq-f3-008",
    type: "mcq",
    unit: "f3",
    conceptIds: ["fr-caffeine-drugs"],
    prompt: "Use of over-the-counter medication by flight personnel is",
    options: [
      "permitted, since it does not require a prescription",
      "prohibited unless specifically approved by a flight surgeon",
      "permitted up to 12 hours before flight",
      "governed only by the aircraft NATOPS",
    ],
    answer: 1,
    explanation:
      "BOTH prescription and over-the-counter drugs are prohibited unless specifically approved by a flight surgeon.",
    whyWrong:
      "The trap is assuming over-the-counter is exempt because it needs no prescription. It is not.",
    knowCold: "Prescription AND over-the-counter: flight surgeon approval only.",
    difficulty: 2,
    source: ORG(["2.359"]),
  },
  {
    id: "fq-f3-010",
    type: "mcq",
    unit: "f3",
    conceptIds: ["fr-harness"],
    prompt: "Inertial reels, where provided, shall be manually locked",
    options: [
      "for the entire flight",
      "for takeoffs and landings, and when high G forces are anticipated",
      "only during aerobatic flight",
      "only when directed by the PIC",
    ],
    answer: 1,
    explanation:
      "Locked for takeoff and landing and for high G, except where doing so would be detrimental to safety. Belts and harnesses are worn and tightened before takeoff until completion of flight.",
    knowCold: "Reels locked for takeoff, landing and high G.",
    difficulty: 2,
    source: ORG(["2.356"]),
  },
  {
    id: "fq-f3-011",
    type: "mcq",
    unit: "f3",
    conceptIds: ["fr-ppe"],
    prompt: "Which of the following is NOT among the minimum aircrew PPE items?",
    options: [
      "Protective helmet",
      "Fire-resistant flight suit and gloves",
      "Portable oxygen concentrator",
      "Survival knife and personal survival kit",
    ],
    answer: 2,
    explanation:
      "The minimum list is helmet, safety or flyer boots, fire-resistant flight suit and gloves, survival knife, personal survival kit, signal device, survival radio, emergency beacon, flashlight and identification tags.",
    knowCold: "Helmet, boots, suit, gloves, knife, kit, signal, radio, beacon, light, tags.",
    difficulty: 2,
    source: ORG(["2.356"]),
  },
  {
    id: "fq-f3-012",
    type: "mcq",
    unit: "f3",
    conceptIds: ["fr-performance-factors"],
    prompt: "Which is a recognised factor affecting aircrew human performance?",
    options: [
      "Quality and duration of sleep",
      "The circadian clock",
      "Dehydration",
      "All of the above",
    ],
    answer: 3,
    explanation:
      "The list also includes weather, temperature extremes, nighttime operations, vision imaging systems, mission delays, personal equipment and duration of the duty period.",
    knowCold: "Sleep, circadian rhythm and dehydration are all named factors.",
    difficulty: 1,
    source: ORG(["2.358"]),
  },

  /* ================= f4 · The Airport ================= */
  {
    id: "fq-f4-001",
    type: "mcq",
    unit: "f4",
    conceptIds: ["fr-runway-numbering"],
    prompt:
      "You are landing on a magnetic heading of 093°. What runway are you landing on?",
    options: ["Runway 9", "Runway 27", "Runway 93", "Runway 10"],
    answer: 0,
    explanation:
      "Runway numbering is the magnetic heading rounded to the nearest 10 degrees with the last digit dropped: 093 rounds to 090, giving runway 09.",
    whyWrong: "Runway 27 is the reciprocal end of the same strip.",
    knowCold: "Round the heading to the nearest 10, drop the last digit.",
    difficulty: 1,
    officialStyle: true,
    source: VIFR(["2.360"]),
  },
  {
    id: "fq-f4-002",
    type: "mcq",
    unit: "f4",
    conceptIds: ["fr-wind-indicators"],
    prompt:
      "While flying at night you approach an airport on a heading of 180°. The tetrahedron's spar is pointed 90° left of the aircraft's heading. On what runway are you expected to land?",
    options: ["09", "18", "27", "36"],
    answer: 0,
    explanation:
      "The tetrahedron indicates the direction of landing. Ninety degrees left of a 180° heading is 090°, so the expected landing runway is 09.",
    knowCold: "The tetrahedron's spar points the way you land.",
    difficulty: 3,
    officialStyle: true,
    source: VIFR(["2.361"]),
  },
  {
    id: "fq-f4-003",
    type: "mcq",
    unit: "f4",
    conceptIds: ["fr-wind-indicators"],
    prompt: "A wind sock indicates",
    options: [
      "the direction of landing and takeoff",
      "wind direction and approximate velocity",
      "the active runway number",
      "the position of the control tower",
    ],
    answer: 1,
    explanation:
      "The wind sock is a free-swinging indicator giving wind direction and approximate velocity. The tetrahedron is what indicates landing direction.",
    knowCold: "Sock = wind. Tetrahedron = landing direction.",
    difficulty: 1,
    officialStyle: true,
    source: VIFR(["2.361"]),
  },
  {
    id: "fq-f4-004",
    type: "mcq",
    unit: "f4",
    conceptIds: ["fr-airport-signs"],
    prompt: "What airport signs have white letters on a red background?",
    options: ["Location signs", "Direction signs", "Information signs", "Mandatory instruction signs"],
    answer: 3,
    explanation: "White on red marks a MANDATORY instruction — the boundary of somewhere you may not go without a clearance, typically a runway holding position. Red on an airfield always means stop and check.",
    knowCold: "White on red = mandatory instruction.",
    difficulty: 1,
    officialStyle: true,
    source: VIFR(["2.361"]),
  },
  {
    id: "fq-f4-005",
    type: "mcq",
    unit: "f4",
    conceptIds: ["fr-aldis"],
    prompt: "From the tower, a FLASHING WHITE light gun signal means",
    options: ["Cleared to land", "Return for landing", "Give way and continue circling", "Airport unsafe, do not land"],
    answer: 1,
    explanation:
      "Flashing white means return for landing. Steady green is cleared to land; steady red means give way and continue circling.",
    whyWrong:
      "Flashing white is easy to read as a clearance. It is not — steady green is the clearance.",
    knowCold: "Steady green = cleared to land. Flashing white = return for landing.",
    difficulty: 2,
    officialStyle: true,
    source: VIFR(["2.361"]),
  },
  {
    id: "ftap-f4-006",
    type: "tapDiagram",
    unit: "f4",
    conceptIds: ["fr-aldis"],
    prompt: "Tap the signal that means CLEARED TO LAND.",
    diagram: { id: "frr-light-gun", props: { highlight: "none", labels: false } },
    targets: [
      { id: "green", label: "Steady green", x: 90, y: 95, r: 30 },
      { id: "red", label: "Steady red", x: 90, y: 157, r: 30 },
      { id: "white", label: "Flashing white", x: 90, y: 219, r: 30 },
    ],
    answer: "green",
    explanation:
      "Steady green clears you to land. Of the other two on the gun, steady red means give way and keep circling, and flashing white means return for landing — an instruction to come back, not a clearance to put the wheels down.",
    knowCold: "Steady green = cleared to land.",
    difficulty: 1,
    source: VIFR(["2.361"]),
  },
  {
    id: "fq-f4-007",
    type: "mcq",
    unit: "f4",
    conceptIds: ["fr-displaced-threshold"],
    prompt: "A displaced threshold marks pavement that is available for",
    options: [
      "landing only",
      "takeoff or rollout, but not landing",
      "all operations",
      "no operations at all",
    ],
    answer: 1,
    explanation:
      "A displaced threshold is located at a point other than the runway end. The pavement before it may be used for takeoff or rollout but not for landing.",
    knowCold: "Displaced threshold: take off from it, roll out over it, never land on it.",
    difficulty: 2,
    source: VIFR(["2.361"]),
  },
  {
    id: "fq-f4-008",
    type: "mcq",
    unit: "f4",
    conceptIds: ["fr-vasi"],
    prompt:
      "For a VASI glideslope indicator, two red lights over two white lights indicates",
    options: ["Below glideslope", "On glideslope", "Above glideslope", "Waveoff"],
    answer: 1,
    explanation: "Red over white is on glideslope. Red over red is below; white over white is above.",
    knowCold: "Red over white, you're alright.",
    difficulty: 1,
    officialStyle: true,
    source: VIFR(["2.361"]),
  },
  {
    id: "fbf-f4-009",
    type: "beforeAfter",
    unit: "f4",
    conceptIds: ["fr-vasi"],
    prompt: "The VASI changes from red-over-white to red-over-red.",
    diagram: { id: "frr-vasi", props: {} },
    states: ["Red over white", "Red over red"],
    beforeProps: { state: "on" },
    afterProps: { state: "low" },
    rows: [
      {
        label: "Your position",
        options: ["On glideslope, then below it", "Below, then on it", "Above, then on it"],
        answer: 0,
      },
      {
        label: "Required action",
        options: ["Correct upward", "Correct downward", "No correction"],
        answer: 0,
      },
    ],
    explanation:
      "All red means you have descended below the glideslope and need to correct upward.",
    knowCold: "Red over red, you're dead.",
    difficulty: 2,
    source: VIFR(["2.361"]),
  },
  {
    id: "fq-f4-019",
    type: "spotTheTrap",
    unit: "f4",
    conceptIds: ["fr-vasi"],
    prompt:
      '"All white on the VASI means the aircraft is safely established on the glideslope."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. White over white is ABOVE the glideslope. Only red over white is on slope. All white looks reassuring, which is exactly why it is worth knowing — it means you are high and will land long.",
    knowCold: "White over white, you're high as a kite.",
    difficulty: 2,
    officialStyle: true,
    source: VIFR(["2.361"]),
  },
  {
    id: "fq-f4-010",
    type: "mcq",
    unit: "f4",
    conceptIds: ["fr-runway-lighting"],
    prompt:
      "Viewed from an approaching aircraft, the lights marking the end of a runway are green. Viewed from the runway they are red. These are respectively called",
    options: [
      "overrun lights and threshold lights",
      "threshold lights and overrun lights",
      "centerline lights and edge lights",
      "touchdown zone lights and taxiway lights",
    ],
    answer: 1,
    explanation:
      "Green on approach are threshold lights, marking the landing threshold. Red viewed from the runway are overrun lights, marking the end of useable runway.",
    knowCold: "Green approaching = threshold. Red from the runway = overrun.",
    difficulty: 3,
    source: VIFR(["2.361"]),
  },
  {
    id: "fq-f4-011",
    type: "mcq",
    unit: "f4",
    conceptIds: ["fr-runway-lighting"],
    prompt: "Taxiways are outlined with ___ lights and have ___ centerline lights.",
    options: ["green, blue", "blue, green", "white, red", "blue, white"],
    answer: 1,
    explanation:
      "Taxiway edges are blue and taxiway centerlines are green. Taxiway turnoff lights are also green.",
    knowCold: "Taxiway: blue edges, green centerline.",
    difficulty: 2,
    source: VIFR(["2.361"]),
  },
  {
    id: "fq-f4-012",
    type: "mcq",
    unit: "f4",
    conceptIds: ["fr-runway-lighting"],
    prompt:
      "Viewed from the landing threshold, runway centerline lights are white until the last ___ of the runway, then alternate white and red, and are red for the final ___.",
    options: [
      "3,000 feet, 1,000 feet",
      "2,000 feet, 1,000 feet",
      "1,000 feet, 500 feet",
      "5,000 feet, 2,000 feet",
    ],
    answer: 0,
    explanation:
      "White until the last 3,000 feet, alternating white and red for the next 2,000 feet, then red for the final 1,000 feet.",
    knowCold: "White, then white/red for 2,000, then red for the last 1,000.",
    difficulty: 3,
    source: VIFR(["2.361"]),
  },
  {
    id: "fq-f4-013",
    type: "mcq",
    unit: "f4",
    conceptIds: ["fr-beacon"],
    prompt: "A military airport rotating beacon is distinguished from a civilian one by",
    options: [
      "a solid white light alternating with solid green",
      "dual-peaked white flashes alternating with a green flash",
      "a red flashing light",
      "operating only during daylight",
    ],
    answer: 1,
    explanation:
      "The military beacon shows two quick white flashes alternating with a solid green flash. The civilian beacon alternates solid white with solid green.",
    knowCold: "Two quick whites = military.",
    difficulty: 2,
    source: VIFR(["2.361"]),
  },
  {
    id: "fq-f4-014",
    type: "mcq",
    unit: "f4",
    conceptIds: ["fr-waveoff"],
    prompt: "A waveoff signal means",
    options: [
      "reduce speed and continue the approach",
      "DO NOT LAND, and compliance is mandatory except in an emergency",
      "land at the pilot's discretion",
      "contact the tower on the alternate frequency",
    ],
    answer: 1,
    explanation:
      "A waveoff means do not land and compliance is mandatory except for emergencies. Any high intensity red lights at the approach end should be treated as a waveoff.",
    knowCold: "Waveoff = do not land, mandatory.",
    difficulty: 1,
    source: VIFR(["2.361"]),
  },
  {
    id: "fq-f3-013",
    type: "mcq",
    unit: "f3",
    conceptIds: ["fr-life-rafts"],
    prompt: "Life rafts shall be carried with sufficient capacity for all passengers and crew when",
    options: [
      "any part of the route crosses water",
      "there is significant risk of water entry during a mishap",
      "the flight will exceed one hour",
      "operating above 10,000 feet",
    ],
    answer: 1,
    explanation:
      "The trigger is the risk of water entry in a mishap, not merely being over water at some point.",
    knowCold: "Rafts when a mishap could put you in the water.",
    difficulty: 2,
    source: ORG(["2.356"]),
  },
  {
    id: "fq-f3-014",
    type: "mcq",
    unit: "f4",
    conceptIds: ["fr-als"],
    prompt: "Approach light systems exist to",
    options: [
      "mark the runway edges at night",
      "provide the transition from instrument flight to visual flight for landing",
      "indicate the direction of landing and takeoff",
      "identify the airport as military",
    ],
    answer: 1,
    explanation:
      "They begin at the landing threshold and extend outward into the approach area, bridging the moment the pilot comes off instruments.",
    knowCold: "ALS bridges instruments to visual.",
    difficulty: 2,
    source: VIFR(["2.361"]),
  },
  {
    id: "fq-f4-017",
    type: "mcq",
    unit: "f4",
    conceptIds: ["fr-runway-numbering"],
    prompt: "You are on final with a magnetic heading of 355°. Which runway are you landing on?",
    options: ["Runway 35", "Runway 36", "Runway 01", "Runway 18"],
    answer: 1,
    explanation:
      "355 rounds to 360, and 360 divided by 10 is 36. A runway is never numbered 00.",
    whyWrong:
      "Truncating instead of rounding gives 35. The rule is to round to the nearest ten first.",
    knowCold: "Round first, then drop the digit.",
    difficulty: 2,
    source: VIFR(["2.360"]),
  },
  {
    id: "fq-f4-018",
    type: "mcq",
    unit: "f4",
    conceptIds: ["fr-runway-numbering"],
    prompt:
      "The wind shifts and the tower switches you to the opposite end of runway 04. What is the new runway number?",
    options: ["Runway 40", "Runway 14", "Runway 22", "Runway 26"],
    answer: 2,
    explanation:
      "The two ends of one strip are reciprocals, so they always differ by 18. 04 plus 18 is 22.",
    knowCold: "Same strip, 18 apart.",
    difficulty: 2,
    source: VIFR(["2.360"]),
  },
];
