import type { Question, SourceReference } from "@/lib/types";

const VIFR = (eo: string[]): SourceReference => ({
  document: "Flight Rules and Regulations Trainee Guide",
  chapter: "Visual / Instrument Flight Rules",
  eo,
});

/** Units f5 (VFR and IFR) and f6 (altitudes and aerobatics). */
export const F5_QUESTIONS: Question[] = [
  {
    id: "fq-f5-001",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-basic-vfr"],
    prompt: "What are the basic VFR minimums?",
    options: ["300'/1 SM", "1,000'/1 SM", "1,000'/3 SM", "3,000'/3 SM"],
    answer: 2,
    explanation:
      "Basic VFR is a 1,000 foot ceiling and 3 statute miles visibility, written 1000/3.",
    knowCold: "Basic VFR = 1000/3.",
    difficulty: 1,
    officialStyle: true,
    source: VIFR(["2.364"]),
  },
  {
    id: "fq-f5-002",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-vmc", "fr-imc"],
    prompt: "Per CNAF M-3710.7, IMC also exists any time",
    options: [
      "the ceiling is below 1,000 feet",
      "a visible horizon is not distinguishable",
      "the aircraft is above 18,000 feet MSL",
      "an IFR flight plan has been filed",
    ],
    answer: 1,
    explanation:
      "CNAF adds this clause to the FAR definition. No distinguishable horizon means IMC even where the reported numbers would allow VMC.",
    whyWrong:
      "Filing IFR does not create IMC — the flight plan and the weather are independent.",
    knowCold: "No visible horizon = IMC, per CNAF.",
    difficulty: 3,
    source: VIFR(["2.362"]),
  },
  {
    id: "ftrap-f5-003",
    type: "spotTheTrap",
    unit: "f5",
    conceptIds: ["fr-vfr-ifr-terms"],
    prompt: '"An IFR flight plan can only be flown in IMC."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. IFR flight plans can be conducted in either VMC or IMC. VMC and IMC describe the weather; VFR and IFR describe the rules being flown under.",
    knowCold: "Weather is VMC/IMC. Rules are VFR/IFR. They are independent.",
    difficulty: 2,
    source: VIFR(["2.362"]),
  },
  {
    id: "fq-f5-004",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-forecast"],
    prompt: "A forecast gives the",
    options: [
      "average conditions expected during the flight",
      "worst conditions expected from one hour before to one hour after the ETA",
      "conditions at the moment of the brief",
      "best conditions expected on arrival",
    ],
    answer: 1,
    explanation:
      "A forecast is the WORST conditions expected during ETA ± 1 hour, stated as ceiling then visibility.",
    knowCold: "Forecast = worst conditions, ETA ± 1 hour.",
    difficulty: 2,
    source: VIFR(["2.362", "2.364"]),
  },
  {
    id: "fq-f5-005",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-see-and-avoid"],
    prompt: "The principle of see and avoid applies",
    options: [
      "only to aircraft on a VFR flight plan",
      "only in Class G airspace",
      "regardless of flight plan type, when weather conditions permit",
      "only when ATC is not providing radar service",
    ],
    answer: 2,
    explanation:
      "When weather permits, and regardless of flight plan type, pilots are required to observe the presence of and manoeuvre to avoid other aircraft. CNAF adds that all aircraft shall request radar advisory service when available.",
    whyWrong: "Being on an IFR flight plan does not excuse the responsibility.",
    knowCold: "See and avoid: regardless of flight plan type.",
    difficulty: 2,
    source: VIFR(["2.363"]),
  },
  {
    id: "fcc-f5-006",
    type: "connectChain",
    unit: "f5",
    conceptIds: ["fr-precluding-vfr"],
    prompt:
      "You are VFR and encounter weather en route that precludes VFR minimums. Build the set of alternatives available to you.",
    trigger: "En route weather falls below VFR minimums",
    steps: [
      "Alter the route of flight to continue in VMC",
      "Remain in VMC until a flight plan change is filed and an IFR clearance obtained",
      "Remain in VMC and land at a suitable alternate",
    ],
    explanation:
      "All three keep you in VMC. Continuing into IMC in controlled airspace without a clearance is not among them.",
    knowCold: "Alter route · get a clearance · land at an alternate.",
    difficulty: 2,
    source: VIFR(["2.365"]),
  },
  {
    id: "fq-f5-007",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-precluding-vfr"],
    prompt:
      "Which is NOT an alternative available to a VFR pilot encountering weather below VFR minimums en route?",
    options: [
      "Alter the route of flight to continue in VMC",
      "Continue into IMC in controlled airspace and request a clearance once inside",
      "Remain in VMC until an IFR clearance is obtained",
      "Remain in VMC and land at a suitable alternate",
    ],
    answer: 1,
    explanation:
      "Flights shall not be made in IFR conditions within controlled airspace until an ATC clearance has been obtained. Every legitimate option keeps the aircraft in VMC.",
    knowCold: "Never enter IMC in controlled airspace without a clearance first.",
    difficulty: 3,
    source: VIFR(["2.365", "2.366"]),
  },
  {
    id: "fq-f5-008",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-vfr-fuel"],
    prompt:
      "VFR fuel planning requires enough fuel to reach the destination plus a reserve of",
    options: [
      "10% of planned fuel requirements, never less than 20 minutes of flight time",
      "10% of planned fuel requirements, never less than 45 minutes of flight time",
      "20% of planned fuel requirements",
      "30 minutes of flight time",
    ],
    answer: 0,
    explanation:
      "Ten percent of planned fuel requirements, and in no case less than that needed for 20 minutes of flight. For turbine-powered fixed-wing aircraft the reserve is computed at maximum endurance at 10,000 feet MSL.",
    knowCold: "10% reserve, floor of 20 minutes.",
    difficulty: 2,
    source: VIFR(["2.364"]),
  },
  {
    id: "fq-f5-009",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-ifr-general"],
    prompt: "Regarding IFR filing, CNAF M-3710.7 requires that",
    options: [
      "naval flights be conducted IFR to the maximum extent practicable",
      "IFR be filed only when the weather is below VFR minimums",
      "IFR be filed only for flights above 18,000 feet",
      "the choice is entirely at the PIC's discretion",
    ],
    answer: 0,
    explanation:
      "All flights in naval aircraft shall be conducted under IFR to the maximum extent practicable, to decrease the probability of midair collision.",
    knowCold: "File IFR wherever practicable.",
    difficulty: 2,
    source: VIFR(["2.366"]),
  },
  {
    id: "fq-f5-010",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-approach-types"],
    prompt: "An instrument approach that provides an electronic glideslope is a",
    options: ["non-precision approach", "precision approach", "circling approach", "visual approach"],
    answer: 1,
    explanation:
      "A precision approach provides an electronic glideslope — ILS or PAR. Non-precision approaches such as VOR, TACAN, LOC, NDB and ASR do not.",
    knowCold: "Electronic glideslope = precision.",
    difficulty: 1,
    officialStyle: true,
    source: VIFR(["2.367"]),
  },
  {
    id: "fq-f5-011",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-approach-types", "fr-landing-minimums"],
    prompt: "Precision approaches usually have the lowest landing minimums because",
    options: [
      "they are flown at slower speeds",
      "the more accurate the course and glideslope information, the lower the minimums",
      "they are only flown by multi-piloted aircraft",
      "they require less visibility by regulation",
    ],
    answer: 1,
    explanation:
      "Landing minimums depend on the approach flown and the aircraft's approach speed, and better course and glideslope information permits lower minimums.",
    knowCold: "Better guidance buys lower minimums.",
    difficulty: 2,
    source: VIFR(["2.367"]),
  },
  {
    id: "fq-f5-012",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-landing-minimums"],
    prompt:
      "Absolute minimums for a single-piloted aircraft executing a precision approach are",
    options: [
      "100 ft HAT and ¼ SM",
      "200 ft HAT and ½ SM / 2,400 ft RVR, or the published minimums, whichever is higher",
      "200 ft HAT and ½ SM, or the published minimums, whichever is lower",
      "300 ft HAT and 1 SM",
    ],
    answer: 1,
    explanation:
      "200 foot ceiling (height above touchdown) and ½ SM visibility or 2,400 feet RVR — or the published minimums, whichever is HIGHER.",
    whyWrong:
      "'Whichever is lower' is the trap. The more restrictive figure always governs.",
    knowCold: "200 and a half, or published — whichever is higher.",
    difficulty: 3,
    source: VIFR(["2.367"]),
  },
  {
    id: "fq-f5-013",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-alternate"],
    prompt:
      "What table from CNAF M-3710.7 is used to determine if an alternate airport is required for a flight plan?",
    options: [
      "IFR filing criteria",
      "IFR alternate criteria",
      "DoD en route flight planning",
      "Weather for naval aviators",
    ],
    answer: 0,
    explanation:
      "The IFR Filing Criteria table, applied to the destination forecast for ETA ± 1 hour.",
    knowCold: "IFR Filing Criteria decides whether you need an alternate.",
    difficulty: 2,
    officialStyle: true,
    source: VIFR(["2.367"]),
  },
  {
    id: "fq-f5-014",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-alternate"],
    prompt:
      "An alternate must have a published approach flyable without two-way radio when the forecast weather at that alternate is below",
    options: [
      "1,000 foot ceiling and 3 SM",
      "3,000 foot ceiling and 3 SM during ETA ± 1 hour",
      "200 foot ceiling and ½ SM",
      "5,000 foot ceiling and 5 SM",
    ],
    answer: 1,
    explanation:
      "That requirement applies when the destination lacks such an approach, or when the alternate's forecast is below 3,000 feet and 3 SM during ETA ± 1 hour. It guarantees a flyable approach after a radio failure.",
    knowCold: "Alternate below 3,000/3 → it needs a no-radio published approach.",
    difficulty: 3,
    source: VIFR(["2.367"]),
  },
  {
    id: "fq-f5-015",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-ifr-fuel"],
    prompt: "When an alternate IS required, IFR fuel must cover",
    options: [
      "takeoff to destination plus 10%",
      "takeoff to the approach fix serving the destination, then to the alternate, plus a 10% reserve",
      "takeoff to the alternate only",
      "takeoff to destination plus 45 minutes",
    ],
    answer: 1,
    explanation:
      "With no alternate required the requirement matches VFR. With one required, add the leg from the destination approach fix to the alternate, then the 10% reserve — never less than 20 minutes.",
    knowCold: "Destination fix → alternate → 10%, floor 20 minutes.",
    difficulty: 3,
    source: VIFR(["2.367"]),
  },
  {
    id: "fq-f5-016",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-missed-approach"],
    prompt: "When a controller directs a missed approach, execution is",
    options: [
      "at the pilot's discretion",
      "mandatory",
      "required only in IMC",
      "advisory only",
    ],
    answer: 1,
    explanation:
      "When so directed, execution of the missed approach is mandatory. Separately, pilots may execute a missed approach at their own discretion at any time.",
    knowCold: "Directed missed approach: mandatory. Pilot-initiated: any time.",
    difficulty: 2,
    source: VIFR(["2.367"]),
  },
  {
    id: "fq-f5-017",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-vfr-destination"],
    prompt:
      "VFR destination weather must be at least 1,000/3 and forecast to remain so",
    options: [
      "for one hour after the ETA",
      "from one hour before to one hour after the ETA",
      "for the duration of the flight",
      "until the flight plan is closed",
    ],
    answer: 1,
    explanation: "ETA ± 1 hour, or above any more stringent established minimums.",
    knowCold: "Destination 1000/3, ETA ± 1 hour.",
    difficulty: 2,
    source: VIFR(["2.364"]),
  },

  /* ================= f6 · Altitudes and Aerobatics ================= */
  {
    id: "fq-f6-001",
    type: "mcq",
    unit: "f6",
    conceptIds: ["fr-semicircular"],
    prompt:
      "Per the semicircular rules, a magnetic course of 360° is considered ___ and 180° is considered ___.",
    options: ["west, east", "east, west", "east, east", "west, west"],
    answer: 1,
    explanation:
      "Courses of 0° through 179° count as east, and 360° is 0°. Courses of 180° through 359° count as west.",
    whyWrong:
      "360 looks like the top of the west range, but it wraps to 0 and counts as east.",
    knowCold: "0–179 east · 180–359 west · 360 is 0, so east.",
    difficulty: 3,
    officialStyle: true,
    source: VIFR(["2.368"]),
  },
  {
    id: "fq-f6-002",
    type: "mcq",
    unit: "f6",
    conceptIds: ["fr-vfr-altitudes"],
    prompt: "VFR semicircular cruising altitudes start at what altitude?",
    options: ["1,000' AGL", "3,000' AGL", "3,000' MSL", "18,000' MSL"],
    answer: 1,
    explanation:
      "They apply above 3,000 feet AGL. At or below 3,000 AGL any altitude may be used regardless of direction of flight.",
    knowCold: "VFR semicircular rules begin above 3,000 ft AGL.",
    difficulty: 2,
    officialStyle: true,
    source: VIFR(["2.368"]),
  },
  {
    id: "fq-f6-003",
    type: "mcq",
    unit: "f6",
    conceptIds: ["fr-vfr-altitudes"],
    prompt:
      "You are on an easterly course on a VFR flight plan below 18,000 MSL. Which altitude is correct?",
    options: ["13,500' MSL", "14,500' MSL", "15,000' MSL", "16,000' MSL"],
    answer: 0,
    explanation:
      "East on VFR means odd thousands plus 500. 13,500 fits; 14,500 is even plus 500 (west), and 15,000 and 16,000 are IFR-style altitudes.",
    knowCold: "VFR east: odd thousands plus 500.",
    difficulty: 2,
    officialStyle: true,
    source: VIFR(["2.368"]),
  },
  {
    id: "fq-f6-004",
    type: "mcq",
    unit: "f6",
    conceptIds: ["fr-ifr-altitudes"],
    prompt:
      "An aircraft flying IFR eastbound in Class A airspace would fly at which altitude?",
    options: ["FL 230", "FL 245", "FL 260", "The assigned altitude"],
    answer: 3,
    explanation:
      "In controlled airspace ATC assigns the cruising altitude. The semicircular rules are used primarily for preflight planning and in uncontrolled airspace.",
    whyWrong:
      "FL230 is the right shape for IFR east, but Class A is controlled — the assignment governs.",
    knowCold: "Controlled airspace: fly what ATC assigns.",
    difficulty: 3,
    officialStyle: true,
    source: VIFR(["2.368"]),
  },
  {
    id: "fq-f6-005",
    type: "mcq",
    unit: "f6",
    conceptIds: ["fr-semicircular", "fr-ifr-altitudes"],
    prompt:
      "While planning an IFR flight you compute a magnetic heading of 358° to maintain a magnetic course of 004°. What altitude would you request?",
    options: ["5,000' MSL", "10,500' MSL", "11,500' MSL", "16,000' MSL"],
    answer: 0,
    explanation:
      "The COURSE decides, not the heading. A course of 004° is east, and IFR east below 18,000 is odd thousands — 5,000 MSL. The 358° heading is there to tempt you west.",
    whyWrong:
      "16,000 would be IFR west. The +500 options are VFR altitudes.",
    knowCold: "Course, not heading. IFR east = odd thousands.",
    difficulty: 3,
    officialStyle: true,
    source: VIFR(["2.368"]),
  },
  {
    id: "fsl-f6-006",
    type: "sliderPredict",
    unit: "f6",
    conceptIds: ["fr-semicircular", "fr-vfr-altitudes"],
    prompt: "Swing the course through 180° and watch the required altitudes change.",
    widget: "SemicircularWidget",
    options: [
      "Crossing 180° switches from odd to even thousands",
      "Nothing changes — direction does not matter",
      "Crossing 090° switches from odd to even thousands",
    ],
    answer: 0,
    explanation:
      "The boundary sits at 180°. Courses of 0–179 are east and fly odd; 180–359 are west and fly even.",
    knowCold: "The split is at 180°.",
    difficulty: 2,
    source: VIFR(["2.368"]),
  },
  {
    id: "fq-f6-007",
    type: "mcq",
    unit: "f6",
    conceptIds: ["fr-aerobatic-definition"],
    prompt:
      "Aerobatic flight is defined as an intentional maneuver involving abrupt bank angles greater than ___, pitch angles greater than ___, or accelerations greater than ___.",
    options: [
      "45°, ±30°, 1.5 g",
      "60°, ±45°, 2.0 g",
      "90°, ±60°, 3.0 g",
      "30°, ±20°, 2.5 g",
    ],
    answer: 1,
    explanation:
      "Bank greater than 60°, pitch greater than ±45°, or acceleration greater than 2.0 g. A break manoeuvre conforming to the model NATOPS flight manual is not aerobatic flight.",
    knowCold: "60° bank, ±45° pitch, 2.0 g.",
    difficulty: 2,
    officialStyle: true,
    source: VIFR(["2.369"]),
  },
  {
    id: "fq-f6-008",
    type: "mcq",
    unit: "f6",
    conceptIds: ["fr-aerobatic-rules"],
    prompt: "Where can naval aviators execute aerobatic maneuvers?",
    options: [
      "Over congested areas",
      "If they remain at least 1,500' above the surface and have at least 3 statute miles visibility",
      "Within a federal airway",
      "Within Class A airspace in IMC",
    ],
    answer: 1,
    explanation:
      "Aerobatics are prohibited over congested areas, over open air assemblies, within Class B, C, D or E airspace designated for an airport or within federal airways, below 1,500 feet AGL, and when visibility is less than 3 SM.",
    knowCold: "Above 1,500 AGL and at least 3 SM, clear of the prohibited places.",
    difficulty: 2,
    officialStyle: true,
    source: VIFR(["2.370"]),
  },
  {
    id: "fq-f6-009",
    type: "mcq",
    unit: "f6",
    conceptIds: ["fr-aerobatic-rules"],
    prompt: "What does CNAF M-3710.7 add to the FAR aerobatic restrictions?",
    options: [
      "A 5,000 foot AGL minimum for all naval aircraft",
      "That aerobatics shall not be performed if prohibited by the aircraft's NATOPS manual",
      "That aerobatics require ATC clearance",
      "Nothing — it simply repeats them",
    ],
    answer: 1,
    explanation:
      "CNAF restates all the FAR restrictions so they apply to naval aircraft worldwide, and adds the NATOPS prohibition. Individual commands may be more restrictive — 5,000 feet AGL is the Training Command minimum, but that is a command rule, not CNAF.",
    knowCold: "CNAF adds: not if NATOPS prohibits it.",
    difficulty: 3,
    source: VIFR(["2.370"]),
  },
  {
    id: "fq-f6-010",
    type: "mcq",
    unit: "f6",
    conceptIds: ["fr-unusual-maneuvers"],
    prompt:
      "Regarding unusual maneuvers within Class B, C or D airspace, CNAF M-3710.7 states that",
    options: [
      "pilots may perform them with ATC approval",
      "pilots shall not perform or request clearance to perform them if not essential to the flight, and ATC may not approve or request them",
      "they are permitted above 1,500 feet AGL",
      "only formation flights are restricted",
    ],
    answer: 1,
    explanation:
      "Both sides are bound: the pilot may not perform or even request them, and ATC personnel are not permitted to approve a request or ask a pilot to perform them.",
    knowCold: "Neither the pilot nor ATC may initiate them.",
    difficulty: 3,
    source: VIFR(["2.371"]),
  },
  {
    id: "ftrap-f6-011",
    type: "spotTheTrap",
    unit: "f6",
    conceptIds: ["fr-vfr-altitudes"],
    prompt:
      '"A VFR aircraft cruising at 2,500 feet AGL on a westerly course must fly an even thousand plus 500."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. The VFR semicircular rules apply above 3,000 feet AGL. At or below that, any altitude may be used regardless of direction.",
    knowCold: "Below 3,000 AGL the rule does not apply.",
    difficulty: 3,
    source: VIFR(["2.368"]),
  },
  {
    id: "fq-f5-018",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-vfr-enroute"],
    prompt: "While en route VFR, the weather criteria you must satisfy are those for",
    options: [
      "the departure airfield",
      "the class of airspace you are flying in",
      "the destination airfield",
      "3 SM and clear of clouds, everywhere",
    ],
    answer: 1,
    explanation:
      "You must maintain VMC throughout, and VMC is defined by the class of airspace you happen to be in. The minimums are not one fixed set for the whole flight.",
    knowCold: "En route VFR: the airspace you are in sets the numbers.",
    difficulty: 2,
    source: VIFR(["2.364"]),
  },
  {
    id: "fq-f5-019",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-vfr-on-top"],
    prompt:
      "You are cleared VFR-on-top on an easterly course at 9,500 feet. Approaching a cloud deck, you find you cannot maintain VFR cloud clearance. What must you do?",
    options: [
      "Nothing — VFR-on-top exempts you from cloud clearance",
      "Advise ATC and obtain an altitude or clearance that lets you comply",
      "Descend below the deck at your own discretion and continue",
      "Cancel your IFR flight plan",
    ],
    answer: 1,
    explanation:
      "VFR-on-top is an IFR clearance under which the pilot must still comply with VFR visibility and distance-from-cloud criteria. You remain an IFR aircraft, so the fix goes through ATC.",
    whyWrong:
      "Cancelling the flight plan is exactly backwards — you are on an IFR clearance precisely so the system keeps track of you.",
    knowCold: "On top you still owe VFR cloud clearance, and you are still IFR.",
    difficulty: 3,
    source: VIFR(["2.366"]),
  },
  {
    id: "fq-f5-020",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-approach-criteria"],
    prompt:
      "A single-piloted aircraft arrives to find reported weather below published minimums. The pilot",
    options: [
      "may commence the approach and continue to published minimums",
      "shall not commence the approach",
      "may commence the approach with ATC concurrence",
      "shall commence the approach and go missed at the DH",
    ],
    answer: 1,
    explanation:
      "A single-piloted aircraft shall not commence an approach if reported weather is below published minimums. Once an approach has been commenced, the pilot may continue to those minimums.",
    whyWrong:
      "The 'may continue' clause only protects an approach already begun. It does not authorise starting one.",
    knowCold: "Single pilot: do not START below minimums.",
    difficulty: 3,
    source: VIFR(["2.367"]),
  },
  {
    id: "fq-f5-021",
    type: "mcq",
    unit: "f5",
    conceptIds: ["fr-approach-criteria"],
    prompt:
      "A multi-piloted aircraft shall not commence an approach at or below published minimums unless",
    options: [
      "the destination has a precision approach",
      "it can proceed to a suitable alternate after a missed approach",
      "the pilot in command declares an emergency",
      "two-way communication has been established",
    ],
    answer: 1,
    explanation:
      "The extra crew buys latitude, but only if there is somewhere to go when the approach does not work out.",
    knowCold: "Multi-piloted: only if an alternate is reachable afterwards.",
    difficulty: 3,
    source: VIFR(["2.367"]),
  },
];
