import type { Question, SourceReference } from "@/lib/types";

const AIR = (eo: string[]): SourceReference => ({
  document: "Flight Rules and Regulations Trainee Guide",
  chapter: "Airspace and General Flight Rules",
  eo,
});

/** Unit f7 — airspace classes, airways, Mode C, VFR minimums, special use. */
export const F7_QUESTIONS: Question[] = [
  {
    id: "fq-f7-001",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-controlled", "fr-uncontrolled"],
    prompt: "Airspace is divided into two types. They are",
    options: [
      "domestic and international",
      "controlled and uncontrolled",
      "terminal and en route",
      "civil and military",
    ],
    answer: 1,
    explanation:
      "Controlled airspace covers Classes A, B, C, D and E, where ATC service is provided. Uncontrolled airspace is Class G, where it is not.",
    knowCold: "Controlled (A–E) and uncontrolled (G).",
    difficulty: 1,
    officialStyle: true,
    source: AIR(["2.372"]),
  },
  {
    id: "fq-f7-002",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-class-a"],
    prompt: "Class A airspace extends from",
    options: [
      "the surface to 10,000' MSL",
      "14,500' MSL to 18,000' MSL",
      "18,000' MSL up to and including FL600",
      "18,000' MSL to FL450",
    ],
    answer: 2,
    explanation:
      "Class A runs from 18,000 feet MSL up to and including FL600, including airspace within 12 nautical miles of the coast.",
    whyWrong: "18,000 to FL450 is the vertical extent of jet routes, not Class A.",
    knowCold: "Class A: 18,000 MSL to FL600.",
    difficulty: 2,
    source: AIR(["2.373"]),
  },
  {
    id: "fq-f7-003",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-class-a"],
    prompt: "Which is NOT a requirement for flight within Class A airspace?",
    options: [
      "Instrument rated pilot and aircraft",
      "Transponder with Mode C",
      "IFR clearance prior to entry",
      "At least a private pilot certificate",
    ],
    answer: 3,
    explanation:
      "Class A requires an instrument certified pilot and aircraft, Mode C, an IFR clearance, and two-way radio communication. The private pilot certificate requirement belongs to Class B.",
    knowCold: "Class B is the class that demands a certification level.",
    difficulty: 3,
    officialStyle: true,
    source: AIR(["2.373"]),
  },
  {
    id: "ftrap-f7-004",
    type: "spotTheTrap",
    unit: "f7",
    conceptIds: ["fr-class-a"],
    prompt: '"ATC may authorise VFR-on-top within Class A airspace."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. All aircraft in Class A must operate under IFR. ATC will not authorise VFR or VFR-on-top in Class A.",
    knowCold: "No VFR of any kind in Class A.",
    difficulty: 2,
    source: AIR(["2.373"]),
  },
  {
    id: "fq-f7-005",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-class-b"],
    prompt:
      "To operate a fixed wing aircraft VFR within Class B airspace, a pilot must hold at least a",
    options: [
      "student pilot certificate",
      "private pilot certificate, or be a designated aviator in a military aircraft",
      "commercial pilot certificate",
      "instrument rating",
    ],
    answer: 1,
    explanation:
      "Class B requires at least a private pilot certificate, or designated aviator status when flying a military aircraft, plus Mode C, an ATC clearance and two-way radio communication.",
    knowCold: "Class B: private pilot or designated aviator.",
    difficulty: 2,
    officialStyle: true,
    source: AIR(["2.373"]),
  },
  {
    id: "fq-f7-006",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-class-c"],
    prompt: "The typical Class C configuration is",
    options: [
      "a 4 nm radius from surface to 2,500' AGL",
      "a 5 nm core from the surface to 4,000' AGL, and a 10 nm shelf from 1,200' to 4,000' AGL",
      "a 10 nm core from the surface to 10,000' MSL",
      "an upside-down wedding cake to 10,000' MSL",
    ],
    answer: 1,
    explanation:
      "Class C surrounds airports with an operational tower and radar approach control: a 5 nm core surface to 4,000 AGL, with a 10 nm shelf from 1,200 to 4,000 AGL.",
    whyWrong: "The 4 nm radius to 2,500 AGL is Class D; the wedding cake is Class B.",
    knowCold: "Class C: 5 nm core, 10 nm shelf, 4,000 AGL.",
    difficulty: 3,
    source: AIR(["2.373"]),
  },
  {
    id: "fq-f7-007",
    type: "spotTheTrap",
    unit: "f7",
    conceptIds: ["fr-class-c", "fr-two-way-established"],
    prompt:
      '"A pilot may fly VFR within Class C airspace without first establishing two-way radio communications with ATC."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. Two-way radio communication must be established before entry and maintained inside, along with an operable Mode C transponder.",
    knowCold: "Class C: establish two-way comms before you enter.",
    difficulty: 1,
    officialStyle: true,
    source: AIR(["2.373"]),
  },
  {
    id: "fq-f7-008",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-two-way-established"],
    prompt:
      "You call Pensacola Approach. They reply, 'Aircraft calling Pensacola Approach, stand by.' You",
    options: [
      "have established two-way communications and may enter",
      "have not established two-way communications and may not enter",
      "may enter provided you have Mode C",
      "should squawk 1200 and enter",
    ],
    answer: 1,
    explanation:
      "Communication is established only when ATC responds with your specific call sign. A generic acknowledgement does not count, and you may not legally enter.",
    whyWrong:
      "A reply is not the test — YOUR CALL SIGN in the reply is the test.",
    knowCold: "They must say your call sign.",
    difficulty: 3,
    source: AIR(["2.373"]),
  },
  {
    id: "fq-f7-009",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-class-d"],
    prompt:
      "Class D airspace exists only when a ___ is in operation, and extends from the surface up to but not including ___ AGL.",
    options: [
      "radar approach control, 4,000 feet",
      "control tower, 2,500 feet",
      "control tower, 4,000 feet",
      "flight service station, 2,500 feet",
    ],
    answer: 1,
    explanation:
      "Class D exists around airports with an operational control tower, surface to 2,500 feet AGL, generally a 4 nm core radius.",
    knowCold: "Class D: tower in operation, 2,500 AGL, 4 nm.",
    difficulty: 2,
    officialStyle: true,
    source: AIR(["2.373"]),
  },
  {
    id: "fq-f7-010",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-class-e"],
    prompt: "Unless designated at a lower altitude, Class E airspace begins at",
    options: ["700' AGL", "1,200' AGL", "14,500' MSL", "18,000' MSL"],
    answer: 2,
    explanation:
      "Class E begins at 14,500 feet MSL unless designated lower, excluding airspace less than 1,500 feet AGL. Lower floors are the surface, 700 AGL, or 1,200 AGL depending on the purpose.",
    knowCold: "Class E default floor: 14,500 MSL.",
    difficulty: 3,
    source: AIR(["2.373"]),
  },
  {
    id: "fq-f7-011",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-class-e"],
    prompt: "The entry requirements for Class E airspace are",
    options: [
      "two-way radio communication and Mode C",
      "an ATC clearance",
      "none — there are no certification, equipment or entry requirements",
      "an instrument rating",
    ],
    answer: 2,
    explanation:
      "Class E is controlled airspace, but there are no specific pilot certification, equipment, arrival or through-flight entry requirements. You must volunteer for control.",
    whyWrong:
      "Controlled does not mean restricted. Class E is the class you may simply fly into.",
    knowCold: "Class E is controlled, but you volunteer for the control.",
    difficulty: 3,
    source: AIR(["2.373"]),
  },
  {
    id: "ftap-f7-012",
    type: "tapDiagram",
    unit: "f7",
    conceptIds: ["fr-class-b", "fr-class-c", "fr-class-d"],
    prompt: "Tap the airspace that resembles an upside-down wedding cake.",
    diagram: { id: "frr-airspace-profile", props: { labels: false } },
    targets: [
      { id: "a", label: "Class A", x: 250, y: 60, r: 26 },
      { id: "b", label: "Class B", x: 86, y: 190, r: 34 },
      { id: "c", label: "Class C", x: 233, y: 212, r: 30 },
      { id: "d", label: "Class D", x: 383, y: 226, r: 26 },
    ],
    answer: "b",
    explanation:
      "Class B is individually tailored into layers that resemble an upside-down wedding cake, from the surface to 10,000 feet MSL.",
    knowCold: "Wedding cake = Class B.",
    difficulty: 2,
    source: AIR(["2.373"]),
  },
  {
    id: "fq-f7-013",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-victor-airways"],
    prompt:
      "The vertical dimensions of a Victor airway are 1,200' AGL up to, but NOT including",
    options: ["10,000' MSL", "14,500' MSL", "18,000' MSL", "FL600"],
    answer: 2,
    explanation:
      "Victor airways are Class E, extending from 1,200 feet AGL up to but not including 18,000 feet MSL, and are 4 nm either side of centerline.",
    knowCold: "Victor airways: 1,200 AGL to just below 18,000 MSL.",
    difficulty: 2,
    officialStyle: true,
    source: AIR(["2.374"]),
  },
  {
    id: "fq-f7-014",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-victor-airways", "fr-jet-routes"],
    prompt: "Which statement about jet routes is correct?",
    options: [
      "They are airways 8 nm wide",
      "They extend from 18,000' MSL to FL450 and have no defined width",
      "They are Class E airspace",
      "They extend from 1,200' AGL to FL600",
    ],
    answer: 1,
    explanation:
      "Jet routes are not airways. They standardise routing in Class A, run from 18,000 MSL to FL450, and have no defined width.",
    whyWrong: "The 8 nm total width belongs to Victor airways.",
    knowCold: "Victor has width; jet routes do not.",
    difficulty: 3,
    source: AIR(["2.374"]),
  },
  {
    id: "fq-f7-015",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-mode-c"],
    prompt: "An operable Mode C transponder is required in all airspace",
    options: [
      "at and above 10,000' MSL",
      "at and above 14,500' MSL",
      "at and above 18,000' MSL",
      "below 1,200' AGL",
    ],
    answer: 0,
    explanation:
      "Mode C is required at and above 10,000 feet MSL, within 30 nm of a Class B airport from the surface to 10,000 MSL, and above the ceilings and lateral boundaries of Class B and C up to 10,000 MSL.",
    knowCold: "Mode C at and above 10,000 MSL.",
    difficulty: 2,
    source: AIR(["2.375"]),
  },
  {
    id: "fq-f7-016",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-mode-c"],
    prompt: "Mode C is required within how many nautical miles of a Class B airport?",
    options: ["10 nm", "20 nm", "30 nm", "50 nm"],
    answer: 2,
    explanation:
      "Within 30 nm of a Class B airport from the surface to 10,000 feet MSL, and in extensions beyond 30 nm above the Class B ceiling up to 10,000 MSL.",
    knowCold: "30 nm of a Class B airport, surface to 10,000 MSL.",
    difficulty: 2,
    source: AIR(["2.375"]),
  },
  {
    id: "fq-f7-017",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-vfr-minimums-table"],
    prompt:
      "A cloud clearance of 1,000' above, 500' below, 2,000' horizontally, and 3 SM visibility is required for VFR flight in what class of airspace?",
    options: ["Class A", "Class C", "Class D", "Both Class C and Class D"],
    answer: 3,
    explanation:
      "Classes C and D share those minimums, as does Class E below 10,000 MSL.",
    knowCold: "500 below, 1,000 above, 2,000 horizontal, 3 SM — C, D and E below 10,000.",
    difficulty: 2,
    officialStyle: true,
    source: AIR(["2.376"]),
  },
  {
    id: "fq-f7-018",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-vfr-minimums-table"],
    prompt:
      "When flying VFR in Class E airspace above 10,000' MSL, you must adhere to which weather minimums?",
    options: [
      "1,000' above, 500' below, 2,000' horizontally, 3 SM",
      "1,000' above, 1,000' below, 1 SM horizontally, 5 SM",
      "Clear of clouds, 1 SM visibility",
      "500' above, 1,000' below, 2,000' horizontally, 3 SM",
    ],
    answer: 1,
    explanation:
      "Above 10,000 MSL the requirement rises to 5 SM visibility with 1,000 feet above, 1,000 feet below and 1 statute mile horizontal.",
    whyWrong:
      "The horizontal clearance becomes 1 SM, not 2,000 feet — that is the detail being tested.",
    knowCold: "Above 10,000 MSL: 5 SM and 1,000/1,000/1 SM.",
    difficulty: 3,
    officialStyle: true,
    source: AIR(["2.376"]),
  },
  {
    id: "fq-f7-019",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-vfr-minimums-table"],
    prompt: "VFR weather minimums in Class B airspace are",
    options: [
      "3 SM and clear of clouds",
      "3 SM with 500 below, 1,000 above, 2,000 horizontal",
      "5 SM with 1,000/1,000/1 SM",
      "1 SM and clear of clouds",
    ],
    answer: 0,
    explanation:
      "Class B is the odd one out: 3 statute miles visibility and merely clear of clouds, because ATC is separating everyone inside it.",
    knowCold: "Class B: 3 SM, clear of clouds.",
    difficulty: 2,
    source: AIR(["2.376"]),
  },
  {
    id: "fq-f7-020",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-vfr-minimums-table"],
    prompt:
      "Flying VFR by DAY in Class G airspace below 1,200' AGL, the requirement is",
    options: [
      "1 SM and clear of clouds",
      "3 SM and clear of clouds",
      "3 SM with 500/1,000/2,000",
      "5 SM with 1,000/1,000/1 SM",
    ],
    answer: 0,
    explanation:
      "By day below 1,200 AGL in Class G it is 1 statute mile and clear of clouds. By night the same airspace requires 3 SM with 500 below, 1,000 above and 2,000 horizontal.",
    knowCold: "Class G day, low: 1 SM clear of clouds. Night: 3 SM and the standard clearances.",
    difficulty: 3,
    source: AIR(["2.376"]),
  },
  {
    id: "fbf-f7-021",
    type: "beforeAfter",
    unit: "f7",
    conceptIds: ["fr-vfr-minimums-table"],
    prompt: "You climb from Class E below 10,000 MSL to Class E above 10,000 MSL.",
    diagram: { id: "frr-cloud-clearance", props: {} },
    states: ["Below 10,000 MSL", "Above 10,000 MSL"],
    beforeProps: { preset: "standard" },
    afterProps: { preset: "high" },
    rows: [
      {
        label: "Visibility",
        options: ["3 SM then 5 SM", "5 SM then 3 SM", "3 SM both"],
        answer: 0,
      },
      {
        label: "Horizontal clearance",
        options: ["2,000 ft then 1 SM", "1 SM then 2,000 ft", "2,000 ft both"],
        answer: 0,
      },
      {
        label: "Below clearance",
        options: ["500 ft then 1,000 ft", "1,000 ft then 500 ft", "500 ft both"],
        answer: 0,
      },
    ],
    explanation:
      "Crossing 10,000 MSL raises visibility from 3 to 5 SM, deepens the below-clearance from 500 to 1,000 feet, and stretches the horizontal clearance from 2,000 feet to a full statute mile.",
    knowCold: "Above 10,000 MSL everything gets bigger.",
    difficulty: 3,
    source: AIR(["2.376"]),
  },
  {
    id: "fq-f7-022",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-restricted-area"],
    prompt: "Restricted areas are so designated because",
    options: [
      "the area is restricted in the interest of national security",
      "no navigational aids are available in these areas",
      "they denote the existence of unusual, often invisible, hazards to aircraft",
      "excessive turbulence is always prevalent in that area",
    ],
    answer: 2,
    explanation:
      "Restricted Areas denote unusual, often invisible hazards such as artillery firing, aerial gunnery or guided missiles. National security is the basis for a PROHIBITED area.",
    knowCold: "Restricted = hazards. Prohibited = security.",
    difficulty: 2,
    officialStyle: true,
    source: AIR(["2.377"]),
  },
  {
    id: "fq-f7-023",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-restricted-area"],
    prompt: "Prior to flight through a restricted area, you must obtain permission from the",
    options: ["nearest FSS", "controlling authority", "ARTCC", "airport manager"],
    answer: 1,
    explanation:
      "Prior approval must be granted by the controlling authority. Penetration without authorisation may be extremely hazardous.",
    knowCold: "Restricted areas need the controlling authority's approval.",
    difficulty: 1,
    officialStyle: true,
    source: AIR(["2.377"]),
  },
  {
    id: "fq-f7-024",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-warning-area"],
    prompt: "Warning areas are established",
    options: [
      "over congested cities",
      "generally over international waters, beyond the three-mile limit",
      "only within Class A airspace",
      "wherever a MOA is inactive",
    ],
    answer: 1,
    explanation:
      "Warning areas may contain hazards to nonparticipating aircraft, generally in international airspace beyond the three-mile limit. No permission is required, but you enter at your own risk.",
    knowCold: "Warning areas: international waters, enter at your own risk.",
    difficulty: 2,
    officialStyle: true,
    source: AIR(["2.377"]),
  },
  {
    id: "fq-f7-025",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-moa"],
    prompt: "A Military Operations Area is established to",
    options: [
      "prohibit all civilian flight",
      "separate certain military training activities from IFR traffic",
      "protect the President",
      "mark an area of intense radio interference",
    ],
    answer: 1,
    explanation:
      "MOAs separate military training from IFR traffic. VFR pilots need no permission to fly through one, but should exercise extreme caution and contact the controlling agency for advisories.",
    knowCold: "MOA separates military training from IFR traffic.",
    difficulty: 2,
    source: AIR(["2.377"]),
  },
  {
    id: "fq-f7-026",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-moa", "fr-alert-area", "fr-warning-area", "fr-restricted-area"],
    prompt:
      "Entry into which special use airspace requires prior approval from the controlling authority?",
    options: ["Warning Area", "Military Operations Area", "Alert Area", "Restricted Area"],
    answer: 3,
    explanation:
      "Only the Restricted Area requires prior approval. Warning Areas, MOAs and Alert Areas may all be entered without permission, though with caution.",
    knowCold: "Of the four, only Restricted needs permission.",
    difficulty: 3,
    source: AIR(["2.377"]),
  },
  {
    id: "fq-f7-027",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-controlled-firing"],
    prompt: "Which special use airspace is NOT depicted on aeronautical charts?",
    options: ["Prohibited Area", "Alert Area", "Controlled Firing Area", "Warning Area"],
    answer: 2,
    explanation:
      "Controlled Firing Areas are not charted, because activity is suspended immediately when a spotter, radar or ground lookout detects an approaching aircraft — so they never require a nonparticipating aircraft to change course.",
    knowCold: "Controlled Firing Area: uncharted, because it stops for you.",
    difficulty: 3,
    source: AIR(["2.377"]),
  },
  {
    id: "fq-f7-028",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-alert-area"],
    prompt: "Alert Areas are charted to inform pilots of",
    options: [
      "areas where flight is prohibited",
      "a high volume of pilot training or unusual aerial activity",
      "temporary flight restrictions",
      "areas of known icing",
    ],
    answer: 1,
    explanation:
      "Alert Areas may contain a high volume of pilot training or unusual activity such as ballooning, parachuting or glider operations. Participating and transiting pilots are equally responsible for collision avoidance.",
    knowCold: "Alert Area: heavy training or unusual activity, everyone shares avoidance.",
    difficulty: 2,
    source: AIR(["2.377"]),
  },
  {
    id: "fq-f7-029",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-class-g"],
    prompt: "Class G airspace generally exists where",
    options: [
      "an operating control tower is present",
      "radar coverage is incomplete or air traffic is minimal",
      "IFR traffic is densest",
      "military operations are conducted",
    ],
    answer: 1,
    explanation:
      "Class G is uncontrolled. The FAA provides minimal guidance to pilots operating in it, and ATC has neither the authority nor the responsibility to control traffic there.",
    knowCold: "Class G: no radar, little traffic, no control.",
    difficulty: 2,
    source: AIR(["2.374"]),
  },
  {
    id: "fq-f7-030",
    type: "mcq",
    unit: "f7",
    conceptIds: ["fr-prohibited-area"],
    prompt: "A prohibited area is established for",
    options: [
      "artillery, gunnery and guided missile firing",
      "security or other reasons associated with the national welfare",
      "high volumes of pilot training",
      "military activity separated from IFR traffic",
    ],
    answer: 1,
    explanation:
      "Flight within a prohibited area is exactly that — prohibited. Artillery and gunnery describe a restricted area, which you may enter with permission from the controlling agency.",
    whyWrong:
      "The gunnery answer is the definition of a RESTRICTED area. The two are routinely swapped on exams.",
    knowCold: "Prohibited = national security. Restricted = live fire.",
    difficulty: 2,
    source: AIR(["2.377"]),
  },
];
