import type { Question, SourceReference } from "@/lib/types";

const AIR = (eo: string[]): SourceReference => ({
  document: "Flight Rules and Regulations Trainee Guide",
  chapter: "Airspace and General Flight Rules",
  eo,
});

/** Unit f8 — lighting, right of way, altitude, airspeed, disturbances. */
export const F8_QUESTIONS: Question[] = [
  {
    id: "fq-f8-001",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-position-lights"],
    prompt: "The position light on the left wing is what colour?",
    options: ["Green", "Red", "White", "Amber"],
    answer: 1,
    explanation: "Red on the left wing, green on the right wing, white facing aft.",
    knowCold: "Red left, green right, white aft.",
    difficulty: 1,
    officialStyle: true,
    source: AIR(["2.378"]),
  },
  {
    id: "fq-f8-002",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-position-lights"],
    prompt:
      "A C-130 departs at 1830 and lands at 0600. Sunset is 1930 and sunrise 0500. Position lights are required from ___ to ___.",
    options: ["1830, 0430", "1830, 0600", "1900, 0630", "1900, 0530"],
    answer: 3,
    explanation:
      "Position lights are required from 30 minutes before official sunset until 30 minutes after official sunrise: 1930 minus 30 is 1900, and 0500 plus 30 is 0530.",
    whyWrong:
      "The window is not the flight time and not the hours of darkness — it is sunset minus 30 to sunrise plus 30.",
    knowCold: "Sunset − 30 to sunrise + 30.",
    difficulty: 3,
    officialStyle: true,
    source: AIR(["2.378"]),
  },
  {
    id: "fq-f8-003",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-position-lights"],
    prompt:
      "Pilots should turn on their position lights during the day when visibility is less than",
    options: ["1 SM", "3 SM", "5 SM", "10 SM"],
    answer: 1,
    explanation:
      "Whenever flight visibility as seen from the cockpit is less than 3 statute miles, in addition to the sunset-to-sunrise window.",
    knowCold: "Less than 3 SM: lights on.",
    difficulty: 2,
    officialStyle: true,
    source: AIR(["2.378"]),
  },
  {
    id: "fq-f8-004",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-anticollision"],
    prompt: "Anti-collision lights are required to be on from",
    options: [
      "sunset to sunrise",
      "engine start to engine shutdown",
      "takeoff to landing",
      "taxi to touchdown",
    ],
    answer: 1,
    explanation:
      "They are used from before engine start until engine shutdown. CNAF permits them off in cloud, to prevent distracting the pilot, and where they adversely affect ground operations.",
    knowCold: "Anti-collision: engine start to engine shutdown.",
    difficulty: 2,
    officialStyle: true,
    source: AIR(["2.378"]),
  },
  {
    id: "fq-f8-005",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-relative-position"],
    prompt:
      "Flying at night, you look directly ahead and see a red AND a green position light of another aircraft at the same altitude. What is its orientation and direction?",
    options: [
      "Tail on, same direction",
      "Head on, opposite direction",
      "Left side closest, 90° to the right",
      "Head on, same direction",
    ],
    answer: 1,
    explanation:
      "Seeing both wingtip lights means you are looking at the front of the aircraft — it is head-on and travelling the opposite way. Seeing only white means you are behind it, travelling the same way.",
    knowCold: "Red and green together = head-on.",
    difficulty: 3,
    officialStyle: true,
    source: AIR(["2.379"]),
  },
  {
    id: "ftap-f8-006",
    type: "tapDiagram",
    unit: "f8",
    conceptIds: ["fr-position-lights"],
    prompt: "Tap the wingtip that carries the RED position light.",
    diagram: { id: "frr-position-lights", props: { view: "headon", labels: false } },
    targets: [
      { id: "left", label: "Left wing — red", x: 154, y: 130, r: 32 },
      { id: "right", label: "Right wing — green", x: 346, y: 130, r: 32 },
      { id: "aft", label: "Aft — white", x: 250, y: 170, r: 26 },
    ],
    answer: "left",
    explanation: "Red is on the left wing, green on the right, white facing aft.",
    knowCold: "Red left.",
    difficulty: 1,
    source: AIR(["2.378"]),
  },
  {
    id: "fq-f8-007",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-row-order"],
    prompt: "An aircraft in ___ has the right of way over all other air traffic.",
    options: ["a formation", "distress", "a landing pattern", "a MOA"],
    answer: 1,
    explanation:
      "An aircraft in distress has right of way over all other air traffic. Landing aircraft come next.",
    knowCold: "Distress outranks everything.",
    difficulty: 1,
    officialStyle: true,
    source: AIR(["2.380"]),
  },
  {
    id: "fq-f8-008",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-row-order"],
    prompt:
      "When two or more aircraft are approaching an airport to land, the right of way belongs to",
    options: [
      "the faster aircraft",
      "the aircraft at the lower altitude",
      "the aircraft that called first",
      "the larger aircraft",
    ],
    answer: 1,
    explanation:
      "The aircraft at the lower altitude has the right of way — though it may not use that to cut in front of another on final.",
    knowCold: "Lower aircraft has it.",
    difficulty: 2,
    officialStyle: true,
    source: AIR(["2.380"]),
  },
  {
    id: "fq-f8-009",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-row-order"],
    prompt:
      "An aircraft being overtaken has the right of way. The overtaking aircraft must alter course to the",
    options: ["left", "right", "left or right, at the pilot's discretion", "left, then climb"],
    answer: 1,
    explanation: "The overtaking aircraft alters course to the right to pass well clear.",
    knowCold: "Overtake to the right.",
    difficulty: 1,
    officialStyle: true,
    source: AIR(["2.380"]),
  },
  {
    id: "fq-f8-010",
    type: "spotTheTrap",
    unit: "f8",
    conceptIds: ["fr-row-order"],
    prompt:
      '"Aircraft in a head-on situation, regardless of category, are required to alter heading to the right."',
    options: ["True", "False"],
    answer: 0,
    explanation:
      "True. Approaching head-on or nearly so at the same altitude, EACH pilot alters course to the right — the category hierarchy does not override it.",
    knowCold: "Head-on: both turn right, whatever they are.",
    difficulty: 2,
    officialStyle: true,
    source: AIR(["2.380"]),
  },
  {
    id: "fq-f8-011",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-row-order"],
    prompt:
      "Two airplanes of the same category are converging at about the same altitude. Which has the right of way?",
    options: [
      "The aircraft to the other's right",
      "The aircraft to the other's left",
      "The faster aircraft",
      "The aircraft at the lower altitude",
    ],
    answer: 0,
    explanation:
      "When aircraft of the same category converge at approximately the same altitude, other than head-on, the aircraft to the other's RIGHT has the right of way.",
    knowCold: "Converging: the one on your right has it.",
    difficulty: 2,
    source: AIR(["2.380"]),
  },
  {
    id: "fq-f8-012",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-row-category"],
    prompt: "In the right-of-way category hierarchy, which has the HIGHEST priority?",
    options: ["Helicopter", "Airplane", "Glider", "Hot air balloon"],
    answer: 3,
    explanation:
      "Priority follows manoeuvrability, least manoeuvrable first: balloon, glider, airship, airplane, helicopter. The balloon can do least about a conflict, so it has priority.",
    whyWrong:
      "The instinct is that the more capable aircraft wins. It is the reverse.",
    knowCold: "Balloon > glider > airship > airplane > helicopter.",
    difficulty: 3,
    source: AIR(["2.380"]),
  },
  {
    id: "fcc-f8-013",
    type: "connectChain",
    unit: "f8",
    conceptIds: ["fr-row-category"],
    prompt: "Order the categories from highest right-of-way priority to lowest.",
    trigger: "Two different categories conflict",
    steps: ["Hot air balloon", "Glider", "Airship", "Airplane", "Helicopter"],
    explanation:
      "Least manoeuvrable first. The helicopter, which can most easily change what it is doing, yields to everyone.",
    knowCold: "Least manoeuvrable has the highest priority.",
    difficulty: 2,
    source: AIR(["2.380"]),
  },
  {
    id: "fq-f8-014",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-altitude-congested"],
    prompt:
      "Over a congested area, a pilot shall maintain an altitude of 1,000 feet above the highest obstacle within a horizontal radius of",
    options: ["500 feet", "1,000 feet", "2,000 feet", "1 statute mile"],
    answer: 2,
    explanation:
      "1,000 feet above the highest obstacle within a 2,000 foot horizontal radius of the aircraft.",
    knowCold: "1,000 up, 2,000 out.",
    difficulty: 2,
    source: AIR(["2.381"]),
  },
  {
    id: "fq-f8-015",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-altitude-other"],
    prompt:
      "Over other than congested areas, the FAR minimum altitude is 500 feet AGL, except over open water or sparsely populated areas, where an aircraft",
    options: [
      "has no minimum altitude",
      "may not be operated closer than 500 feet to any person, vessel, vehicle or structure",
      "must maintain 1,000 feet AGL",
      "must remain above 2,000 feet AGL",
    ],
    answer: 1,
    explanation:
      "The 500 feet becomes a distance from things rather than a height above the ground.",
    knowCold: "Open water: 500 feet from any person, vessel, vehicle or structure.",
    difficulty: 3,
    source: AIR(["2.381"]),
  },
  {
    id: "fq-f8-016",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-altitude-cnaf"],
    prompt:
      "During IFR operations outside controlled airspace, CNAF requires an aircraft be flown no less than ___ above the highest terrain, water or obstacle within ___ of the intended line of flight.",
    options: [
      "500 feet, 10 miles",
      "1,000 feet, 22 miles",
      "2,000 feet, 22 miles",
      "1,000 feet, 5 miles",
    ],
    answer: 1,
    explanation:
      "1,000 feet within 22 miles, rising to 2,000 feet over designated mountainous terrain.",
    knowCold: "1,000 ft within 22 miles · 2,000 ft over mountains.",
    difficulty: 3,
    source: AIR(["2.381"]),
  },
  {
    id: "fq-f8-017",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-altitude-cnaf"],
    prompt:
      "During VFR operations, CNAF states that fixed-wing flights shall not be conducted below",
    options: ["300 feet AGL", "500 feet above the terrain or surface of the water", "1,000 feet AGL", "1,500 feet AGL"],
    answer: 1,
    explanation:
      "Except when necessary for takeoff and landing, or when the mission requires otherwise.",
    knowCold: "CNAF VFR floor: 500 feet.",
    difficulty: 2,
    source: AIR(["2.381"]),
  },
  {
    id: "fq-f8-018",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-airspeed"],
    prompt: "What is the airspeed limit beneath the lateral limits of Class B airspace?",
    options: ["150 KIAS", "200 KIAS", "250 KIAS", "There is no limit"],
    answer: 1,
    explanation:
      "200 knots beneath the shelf. Inside Class B itself the limit is 250 knots.",
    whyWrong:
      "This is the classic inversion: the tighter limit applies UNDERNEATH, not inside.",
    knowCold: "Under the shelf: 200. Inside B: 250.",
    difficulty: 3,
    officialStyle: true,
    source: AIR(["2.382"]),
  },
  {
    id: "fq-f8-019",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-airspeed"],
    prompt: "Below 10,000 feet MSL the FAR airspeed limit is",
    options: ["200 KIAS", "250 KIAS", "280 KIAS", "Mach 0.8"],
    answer: 1,
    explanation:
      "250 KIAS below 10,000 MSL. If the minimum safe airspeed for an operation is higher than the limit, the aircraft may be flown at that minimum speed.",
    knowCold: "250 below 10,000.",
    difficulty: 1,
    source: AIR(["2.382"]),
  },
  {
    id: "fq-f8-020",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-airspeed"],
    prompt:
      "Within 4 nm of the primary airport of Class C or D airspace, from the surface to 2,500' AGL, the limit is",
    options: ["150 knots", "200 knots", "250 knots", "no limit applies"],
    answer: 1,
    explanation: "200 knots within 4 nm of the primary Class C or D airport, surface to 2,500 ft AGL. The limit exists because that cylinder is where arriving and departing traffic concentrates and closing speeds matter most.",
    knowCold: "C and D primary airport: 200 knots within 4 nm, up to 2,500 AGL.",
    difficulty: 2,
    source: AIR(["2.382"]),
  },
  {
    id: "fq-f8-022",
    type: "spotTheTrap",
    unit: "f8",
    conceptIds: ["fr-careless"],
    prompt:
      '"In reference to careless and reckless flying, CNAF M-3710.7 states that the only requirement is that the pilot must fly in a safe and non-threatening manner to both people and property on the ground."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. CNAF goes further: it is not enough that no one is actually endangered. Particular effort shall be taken so that individuals do not BELIEVE they or their property are endangered. The test is the perception of the person on the ground.",
    knowCold: "What matters is what the person on the ground thinks, not what the pilot judges.",
    difficulty: 3,
    officialStyle: true,
    source: AIR(["2.383", "2.384"]),
  },
  {
    id: "fq-f8-023",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-noise-sensitive"],
    prompt: "You must avoid noise-sensitive areas when",
    options: [
      "below 1,000' AGL within 3 nm",
      "below 2,000' AGL within 5 nm",
      "below 3,000' AGL",
      "at any altitude",
    ],
    answer: 2,
    explanation:
      "Below 3,000 feet AGL, except when complying with an approved traffic or approach pattern, VFR and IFR training routes, or special use airspace.",
    knowCold: "Noise-sensitive: avoid below 3,000 AGL.",
    difficulty: 2,
    officialStyle: true,
    source: AIR(["2.385"]),
  },
  {
    id: "fq-f8-024",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-noise-sensitive"],
    prompt: "Which of the following have been designated noise-sensitive areas?",
    options: ["Resorts", "Beaches", "Breeding farms", "All of the above"],
    answer: 3,
    explanation:
      "Along with National Parks, National Monuments and National Recreational Areas designated by the Department of the Interior.",
    knowCold: "Resorts, beaches, breeding farms and the national parks.",
    difficulty: 1,
    officialStyle: true,
    source: AIR(["2.385"]),
  },
  {
    id: "fq-f8-025",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-wildlife"],
    prompt:
      "When it is necessary to fly over known wildlife habitations, what altitude shall be maintained, conditions permitting?",
    options: ["500 feet AGL", "1,000 feet AGL", "2,000 feet AGL", "3,000 feet AGL"],
    answer: 3,
    explanation:
      "At least 3,000 feet AGL, to prevent frightening wild fowl or driving them from feeding grounds.",
    knowCold: "Wildlife habitations: 3,000 AGL.",
    difficulty: 2,
    source: AIR(["2.385"]),
  },
  {
    id: "fq-f8-026",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-flat-hatting"],
    prompt:
      "Any maneuver conducted at low altitude and/or high airspeed for thrill purposes over land or water is considered",
    options: ["zooming", "disturbance to wildlife", "flat hatting", "autorotation"],
    answer: 2,
    explanation:
      "Flat hatting, which CNAF M-3710.7 prohibits outright. The defining phrase is 'for thrill purposes' — the same profile flown for a mission is not flat hatting.",
    knowCold: "Flat hatting = low and/or fast, for thrills. Prohibited.",
    difficulty: 1,
    officialStyle: true,
    source: AIR(["2.386"]),
  },
  {
    id: "fq-f8-027",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-commercial-avoidance"],
    prompt:
      "CNAF M-3710.7 requires naval aircraft to avoid commercial carriers and civil aircraft by at least",
    options: [
      "200 feet vertically and/or ½ SM laterally",
      "500 feet vertically and/or 1 SM laterally",
      "1,000 feet vertically and/or 2 SM laterally",
      "there is no specified distance",
    ],
    answer: 1,
    explanation:
      "At least 500 feet vertically and/or 1 SM laterally unless directed otherwise by competent ATC, with no erratic or aerobatic flight in their vicinity. They are comparatively difficult to manoeuvre and relatively blind.",
    knowCold: "500 feet vertical, 1 SM lateral.",
    difficulty: 3,
    source: AIR(["2.385"]),
  },
  {
    id: "fq-f8-028",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-tfr"],
    prompt: "The exact dimensions of a temporary flight restriction are published in",
    options: ["the AIM", "a NOTAM", "FLIP en route charts", "the sectional chart"],
    answer: 1,
    explanation:
      "CNAF states aircraft shall not be operated within an area designated by NOTAM within which temporary flight restrictions apply, and the exact dimensions are in that NOTAM.",
    knowCold: "TFR dimensions live in the NOTAM.",
    difficulty: 2,
    source: AIR(["2.385"]),
  },
  {
    id: "fq-f8-029",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-tfr"],
    prompt: "Temporary flight restrictions are typically imposed around",
    options: [
      "military training routes",
      "natural disasters, major sporting events, parades and forest fires",
      "any airport without a control tower",
      "areas of forecast icing",
    ],
    answer: 1,
    explanation:
      "Incidents or events generating a high degree of public interest that could create hazardous air traffic congestion.",
    knowCold: "TFRs follow public interest and hazard.",
    difficulty: 1,
    source: AIR(["2.385"]),
  },
  {
    id: "fq-f8-030",
    type: "mcq",
    unit: "f8",
    conceptIds: ["fr-cnaf-speed-exemption"],
    prompt:
      "The FAA has exempted naval aircraft from the airspeed limitations. Which of the following is an example of that exemption?",
    options: [
      "Any flight conducted at night",
      "Flight within restricted areas and Military Operations Areas",
      "Any flight above 10,000 feet MSL",
      "Any flight on an IFR clearance",
    ],
    answer: 1,
    explanation:
      "The exemption accommodates high-performance aircraft and military missions. Examples include climbs and descents from traffic patterns, designated training areas and authorised low-level routes, flight within restricted areas and MOAs, and cases where crew or aircraft safety requires it.",
    knowCold: "The exemption is mission-shaped, not altitude-shaped.",
    difficulty: 3,
    source: AIR(["2.382"]),
  },
];
