import type { KnowColdCard, SourceReference } from "@/lib/types";

const TG = (chapter: string, eo: string[]): SourceReference => ({
  document: "Aerodynamics Trainee Guide",
  chapter,
  eo,
});

/**
 * KNOW COLD — the pre-exam compression layer.
 *
 * Gouge Compressor logic applied: every card answers a likely exam question.
 * No anecdotes, no background, no unsupported numbers.
 */
export const KNOW_COLD: KnowColdCard[] = [
  /* ---------------- Definitions ---------------- */
  {
    id: "kc-aoa",
    category: "definition",
    term: "Angle of attack",
    body: "Angle between the CHORD LINE and the RELATIVE WIND.",
    unit: "u1",
    conceptIds: ["c-pitch-vs-aoa"],
    source: TG("Basic Theory", ["2.68"]),
  },
  {
    id: "kc-pitch-attitude",
    category: "definition",
    term: "Pitch attitude",
    body: "Angle between the LONGITUDINAL AXIS and the HORIZON. Never infer AOA from it.",
    unit: "u1",
    conceptIds: ["c-pitch-vs-aoa"],
    source: TG("Basic Theory", ["2.65"]),
  },
  {
    id: "kc-incidence",
    category: "definition",
    term: "Angle of incidence",
    body: "Fixed angle between the LONGITUDINAL AXIS and the CHORD LINE.",
    unit: "u1",
    conceptIds: ["c-pitch-vs-aoa"],
    source: TG("Basic Theory", ["2.69"]),
  },
  {
    id: "kc-relative-wind",
    category: "definition",
    term: "Relative wind",
    body: "Equal in magnitude and OPPOSITE in direction to the flight path.",
    unit: "u1",
    conceptIds: ["c-pitch-vs-aoa"],
    source: TG("Basic Theory", ["2.67"]),
  },
  {
    id: "kc-mcl",
    category: "definition",
    term: "Mean camber line",
    body: "Line halfway between the UPPER and LOWER SURFACES. The chord line runs through the EDGES.",
    unit: "u1",
    conceptIds: ["c-mean-camber-line"],
    source: TG("Basic Theory", ["2.59"]),
  },
  {
    id: "kc-cg",
    category: "definition",
    term: "Centre of gravity",
    body: "Point where all three axes intersect and all WEIGHT is considered concentrated.",
    unit: "u1",
    conceptIds: ["c-cg"],
    source: TG("Basic Theory", ["2.77"]),
  },
  {
    id: "kc-ac",
    category: "definition",
    term: "Aerodynamic centre",
    body: "Point along the chord line where all CHANGES in aerodynamic force occur. ≈25% chord aft of the leading edge.",
    unit: "u1",
    conceptIds: ["c-aerodynamic-center"],
    source: TG("Basic Theory", ["2.78"]),
  },
  {
    id: "kc-equilibrium",
    category: "definition",
    term: "Equilibrium flight",
    body: "Sum of all FORCES and all MOMENTS about the CG equals zero.",
    unit: "u1",
    conceptIds: ["c-equilibrium"],
    source: TG("Basic Theory", ["2.15"]),
  },
  {
    id: "kc-trimmed",
    category: "definition",
    term: "Trimmed flight",
    body: "Sum of all MOMENTS about the CG equals zero. Forces need not.",
    unit: "u1",
    conceptIds: ["c-trimmed"],
    source: TG("Basic Theory", ["2.16"]),
  },
  {
    id: "kc-lift",
    category: "definition",
    term: "Lift",
    body: "Component of aerodynamic force PERPENDICULAR to the relative wind.",
    unit: "u2",
    conceptIds: ["c-lift-def"],
    source: TG("Lift Production and Drag", ["2.83"]),
  },
  {
    id: "kc-drag",
    category: "definition",
    term: "Drag",
    body: "Component of aerodynamic force PARALLEL to and in the SAME DIRECTION as the relative wind.",
    unit: "u2",
    conceptIds: ["c-drag-def"],
    source: TG("Lift Production and Drag", ["2.86"]),
  },
  {
    id: "kc-stall",
    category: "definition",
    term: "Stall",
    body: "An INCREASE in AOA results in a DECREASE in C_L. The only cause is excessive AOA.",
    unit: "u5",
    conceptIds: ["c-stall"],
    source: TG("Stalls", ["3.5"]),
  },
  {
    id: "kc-stall-speed",
    category: "definition",
    term: "Stall speed",
    body: "Minimum TRUE airspeed required to maintain LEVEL flight at C_Lmax AOA.",
    unit: "u5",
    conceptIds: ["c-stall-speed"],
    source: TG("Stalls", ["3.10"]),
  },
  {
    id: "kc-spin",
    category: "definition",
    term: "Spin",
    body: "An aggravated stall resulting in autorotation. Requires STALL and YAW.",
    unit: "u6",
    conceptIds: ["c-spin-definition"],
    source: TG("Spins", ["3.19"]),
  },
  {
    id: "kc-boundary-layer",
    category: "definition",
    term: "Boundary layer",
    body: "Layer of airflow showing local retardation due to VISCOSITY. ~1 mm at the leading edge.",
    unit: "u5",
    conceptIds: ["c-boundary-layer"],
    source: TG("Stalls", ["3.1"]),
  },
  {
    id: "kc-wind-shear",
    category: "definition",
    term: "Wind shear",
    body: "A sudden change in wind DIRECTION and/or SPEED over a short distance.",
    unit: "u6",
    conceptIds: ["c-wind-shear"],
    source: TG("Wake Turbulence and Wind Shear", ["2.193"]),
  },
  {
    id: "kc-load-factor",
    category: "definition",
    term: "Load factor",
    body: "Ratio of total LIFT to WEIGHT. n = L/W = 1/cos φ.",
    formula: "n = \\frac{L}{W} = \\frac{1}{\\cos\\phi}",
    unit: "u5",
    conceptIds: ["c-load-factor"],
    source: TG("Performance and Maneuvering", ["2.164"]),
  },
  {
    id: "kc-maneuver-speed",
    category: "definition",
    term: "Maneuver speed (Va)",
    body: "Lowest airspeed at which the LIMIT LOAD FACTOR can be reached. Below it you stall before you over-G.",
    unit: "u5",
    conceptIds: ["c-maneuver-speed"],
    source: TG("Performance and Maneuvering", ["2.166"]),
  },

  /* ---------------- Equations ---------------- */
  {
    id: "kc-eq-lift",
    category: "equation",
    term: "Lift",
    body: "Density, velocity squared, wing area, coefficient of lift.",
    formula: "L = \\tfrac{1}{2}\\rho V^2 S C_L",
    unit: "u2",
    conceptIds: ["c-lift-equation"],
    source: TG("Lift Production and Drag", ["2.84"]),
  },
  {
    id: "kc-eq-bernoulli",
    category: "equation",
    term: "Bernoulli",
    body: "Total pressure is constant; static and dynamic trade against each other.",
    formula: "H = P_S + \\tfrac{1}{2}\\rho V^2",
    unit: "u1",
    conceptIds: ["c-bernoulli"],
    source: TG("Basic Theory", ["2.31"]),
  },
  {
    id: "kc-eq-continuity",
    category: "equation",
    term: "Continuity",
    body: "Area and velocity are inversely related in a streamtube.",
    formula: "A_1V_1 = A_2V_2",
    unit: "u1",
    conceptIds: ["c-continuity"],
    source: TG("Basic Theory", ["2.35"]),
  },
  {
    id: "kc-eq-gas-law",
    category: "equation",
    term: "General Gas Law",
    body: "With pressure constant, temperature and density are INVERSE.",
    formula: "P = \\rho R T",
    unit: "u1",
    conceptIds: ["c-gas-law"],
    source: TG("Basic Theory", ["2.30"]),
  },
  {
    id: "kc-eq-tas",
    category: "equation",
    term: "True airspeed",
    body: "EAS corrected for density. Above sea level ρ < ρ₀, so TAS > IAS.",
    formula: "TAS = EAS\\sqrt{\\frac{\\rho_0}{\\rho}}",
    unit: "u1",
    conceptIds: ["c-icetg", "c-tas-altitude"],
    source: TG("Basic Theory", ["2.45"]),
  },
  {
    id: "kc-eq-parasite",
    category: "equation",
    term: "Parasite drag",
    body: "f is equivalent parasite area — a flat plate, not the cross-section.",
    formula: "D_P = \\tfrac{1}{2}\\rho V^2 f",
    unit: "u3",
    conceptIds: ["c-parasite-drag"],
    source: TG("Lift Production and Drag", ["2.87"]),
  },
  {
    id: "kc-eq-induced",
    category: "equation",
    term: "Induced drag",
    body: "Weight squared on top; density, velocity squared and wingspan squared underneath.",
    formula: "D_I = \\frac{kW^2}{\\rho V^2 b^2}",
    unit: "u3",
    conceptIds: ["c-induced-drag-factors"],
    source: TG("Lift Production and Drag", ["2.93"]),
  },
  {
    id: "kc-eq-stall-speed",
    category: "equation",
    term: "Stall speed (with load factor)",
    body: "Swap ρ for ρ₀ to get INDICATED stall speed, which does not change with altitude.",
    formula: "V_S = \\sqrt{\\frac{2Wn}{\\rho S C_{L\\,max}}}",
    unit: "u5",
    conceptIds: ["c-stall-speed", "c-accelerated-stall"],
    source: TG("Stalls", ["3.11"]),
  },
  {
    id: "kc-eq-turn",
    category: "equation",
    term: "Turn rate and radius",
    body: "Airspeed and bank angle only. Weight appears nowhere.",
    formula: "\\omega = \\frac{g\\tan\\phi}{V} \\quad\\quad r = \\frac{V^2}{g\\tan\\phi}",
    unit: "u5",
    conceptIds: ["c-turn-rate-radius"],
    source: TG("Performance and Maneuvering", ["2.158"]),
  },
  {
    id: "kc-eq-power-required",
    category: "equation",
    term: "Power required",
    body: "Thrust required times velocity, divided by 325 for horsepower.",
    formula: "P_R = \\frac{T_R \\times V}{325}",
    unit: "u4",
    conceptIds: ["c-power-required"],
    source: TG("Lift Production and Drag", ["2.107"]),
  },
  {
    id: "kc-eq-takeoff-distance",
    category: "equation",
    term: "Takeoff distance",
    body: "Weight is SQUARED. Doubling it quadruples the distance.",
    formula: "S_{TO} = \\frac{W^2}{g\\rho S C_{L\\,max}(T - D - F_R)}",
    unit: "u4",
    conceptIds: ["c-takeoff-distance"],
    source: TG("Performance and Maneuvering", ["2.127"]),
  },
  {
    id: "kc-eq-hydroplane",
    category: "equation",
    term: "Hydroplaning speed",
    body: "In mph. Divide by 1.15 for knots. Independent of weight.",
    formula: "V_{hydroplane} = 9\\sqrt{\\text{tyre pressure}}",
    unit: "u4",
    conceptIds: ["c-hydroplaning"],
    source: TG("Performance and Maneuvering", ["2.150"]),
  },
  {
    id: "kc-eq-mach",
    category: "equation",
    term: "Mach number",
    body: "TAS over local speed of sound, which depends only on temperature.",
    formula: "M = \\frac{TAS}{LSOS}",
    unit: "u4",
    conceptIds: ["c-mach"],
    source: TG("Performance and Maneuvering", ["2.139"]),
  },

  /* ---------------- Sequences ---------------- */
  {
    id: "kc-seq-icetg",
    category: "sequence",
    term: "ICE-TG",
    body: "Indicated → Calibrated (instrument) → Equivalent (compressibility) → True (density) → Ground (wind).",
    unit: "u1",
    conceptIds: ["c-icetg"],
    source: TG("Basic Theory", ["2.42", "2.46"]),
  },
  {
    id: "kc-seq-carvac",
    category: "sequence",
    term: "C.AR.V.A.C",
    body: "Coefficient of lift = Compressibility, Aspect Ratio, Viscosity, AOA, Camber. Pilot controls AOA and camber.",
    unit: "u2",
    conceptIds: ["c-coefficient-of-lift"],
    source: TG("Lift Production and Drag", ["2.85"]),
  },
  {
    id: "kc-seq-stall-recovery",
    category: "sequence",
    term: "Stall recovery",
    body: "RELAX back pressure · MAX power · LEVEL the wings · BALL centred with rudder.",
    unit: "u5",
    conceptIds: ["c-stall-recovery"],
    source: TG("Stalls", ["3.6"]),
  },
  {
    id: "kc-seq-spin-recovery",
    category: "sequence",
    term: "T-6B spin recovery",
    body: "1. Gear, flaps, speed brake retracted · 2. PCL IDLE · 3. Rudder FULL OPPOSITE to turn needle · 4. Stick forward of neutral, ailerons neutral · 5. Recover to level flight.",
    unit: "u6",
    conceptIds: ["c-spin-recovery"],
    source: TG("Spins", ["3.27"]),
  },
  {
    id: "kc-seq-4h",
    category: "sequence",
    term: "The 4-H Club",
    body: "High, Hot, Humid, Heavy. All increase required speed and required distance.",
    unit: "u4",
    conceptIds: ["c-4h-club"],
    source: TG("Performance and Maneuvering", ["2.127"]),
  },
  {
    id: "kc-seq-bank-chain",
    category: "sequence",
    term: "Bank chain",
    body: "Bank ↑ → load factor ↑ → lift required ↑ → AOA demand ↑ → stall speed ↑.",
    unit: "u5",
    conceptIds: ["c-load-factor", "c-accelerated-stall"],
    source: TG("Performance and Maneuvering", ["2.163"]),
  },
  {
    id: "kc-seq-stall-chain",
    category: "sequence",
    term: "Stall chain",
    body: "AOA ↑ → boundary layer energy ↓ → adverse gradient ↑ → separation moves FORWARD → C_L ↓ → stall.",
    unit: "u5",
    conceptIds: ["c-bl-separation", "c-stall"],
    source: TG("Stalls", ["3.3"]),
  },

  /* ---------------- Numbers ---------------- */
  {
    id: "kc-num-standard-atmosphere",
    category: "number",
    term: "Standard atmosphere (sea level)",
    body: "29.92 in-Hg · 59 °F / 15 °C · ρ₀ 0.0024 slugs/ft³ · LSOS 661.7 kt.",
    unit: "u1",
    conceptIds: ["c-standard-atmosphere"],
    source: TG("Basic Theory", ["2.29"]),
  },
  {
    id: "kc-num-lapse-rate",
    category: "number",
    term: "Average lapse rate",
    body: "2 °C (3.57 °F) per 1,000 ft to ~36,000 ft. Isothermal at −56.5 °C from 36,000 to ~66,000 ft.",
    unit: "u1",
    conceptIds: ["c-temperature-lapse"],
    source: TG("Basic Theory", ["2.22"]),
  },
  {
    id: "kc-num-takeoff-landing",
    category: "number",
    term: "Takeoff and landing margins",
    body: "Takeoff 1.2 Vs (20%). Landing 1.3 Vs (30%).",
    unit: "u4",
    conceptIds: ["c-takeoff-landing-speeds"],
    source: TG("Performance and Maneuvering", ["2.124"]),
  },
  {
    id: "kc-num-ground-effect",
    category: "number",
    term: "Ground effect",
    body: "Within one wingspan. 1 span: −1.4% induced drag · ¼ span: −23.5% · max ≈ −60%.",
    unit: "u3",
    conceptIds: ["c-ground-effect"],
    source: TG("Lift Production and Drag", ["2.94", "2.95"]),
  },
  {
    id: "kc-num-ultimate-load",
    category: "number",
    term: "Ultimate load",
    body: "Ultimate = 1.5 × limit. Limit = 2/3 of ultimate.",
    unit: "u5",
    conceptIds: ["c-load-definitions"],
    source: TG("Performance and Maneuvering", ["2.164"]),
  },
  {
    id: "kc-num-load-factor-bank",
    category: "number",
    term: "Bank and load factor",
    body: "60° bank = 2 G = stall speed 40% higher. Above 45° the numbers climb fast.",
    unit: "u5",
    conceptIds: ["c-load-factor", "c-accelerated-stall"],
    source: TG("Performance and Maneuvering", ["2.163"]),
  },
  {
    id: "kc-num-wake",
    category: "number",
    term: "Wake vortex behaviour",
    body: "Sink 400–500 fpm · level off ~900 ft below · drift outward ~5 kt on the ground · core ≈ ¼ wingspan.",
    unit: "u6",
    conceptIds: ["c-wake-behavior"],
    source: TG("Wake Turbulence and Wind Shear", ["2.187"]),
  },
  {
    id: "kc-num-wake-spacing",
    category: "number",
    term: "T-6B wake spacing",
    body: "2 minutes behind a heavy for TAKEOFF. 3 minutes for LANDING. Heavy = over 255,000 lb.",
    unit: "u6",
    conceptIds: ["c-wake-avoidance"],
    source: TG("Wake Turbulence and Wind Shear", ["2.190"]),
  },
  {
    id: "kc-num-ceilings",
    category: "number",
    term: "Ceilings",
    body: "Combat 500 fpm · Cruise 300 fpm · Service 100 fpm · Absolute 0 fpm.",
    unit: "u4",
    conceptIds: ["c-ceilings"],
    source: TG("Performance and Maneuvering", ["2.133"]),
  },
  {
    id: "kc-num-interference",
    category: "number",
    term: "Interference drag share",
    body: "Roughly 5–10% of an aircraft's total drag.",
    unit: "u3",
    conceptIds: ["c-interference-drag"],
    source: TG("Lift Production and Drag", ["2.87"]),
  },

  /* ---------------- Aircraft-specific (T-6B) ---------------- */
  {
    id: "kc-t6b-stall",
    category: "aircraft",
    term: "T-6B stall AOA",
    body: "18 units, regardless of airspeed, attitude, weight or altitude. Stick shaker at 15.5 units.",
    unit: "u5",
    conceptIds: ["c-clmax-aoa"],
    source: TG("Stalls", ["3.16"]),
  },
  {
    id: "kc-t6b-controls",
    category: "aircraft",
    term: "T-6B control loss order",
    body: "Approaching a stall: ailerons → elevator → rudder.",
    unit: "u5",
    conceptIds: ["c-clmax-aoa"],
    source: TG("Stalls", ["3.9"]),
  },
  {
    id: "kc-t6b-limits",
    category: "aircraft",
    term: "T-6B load limits",
    body: "+7.0 / −3.5 G normal. +4.7 / −1.0 G with asymmetric loading. Maneuver speed 227 KIAS at max gross.",
    unit: "u5",
    conceptIds: ["c-load-definitions", "c-maneuver-speed", "c-envelope-factors"],
    source: TG("Performance and Maneuvering", ["2.164", "2.167", "2.168"]),
  },
  {
    id: "kc-t6b-speeds",
    category: "aircraft",
    term: "T-6B speeds",
    body: "Best glide 125 KIAS (11:1 clean) · best climb 140 KIAS · max operating 316 KIAS or .67 Mach · turbulence max 207 KIAS, recommended 180 KIAS.",
    unit: "u4",
    conceptIds: ["c-glide", "c-vx-vy", "c-envelope-factors"],
    source: TG("Performance and Maneuvering", ["2.132", "2.143", "2.167"]),
  },
  {
    id: "kc-t6b-aoa-profiles",
    category: "aircraft",
    term: "T-6B cruise AOA",
    body: "Max endurance 8.8 units. Max range (no wind) 4.4 units.",
    unit: "u4",
    conceptIds: ["c-max-range", "c-max-endurance"],
    source: TG("Performance and Maneuvering", ["2.137"]),
  },
  {
    id: "kc-t6b-engine",
    category: "aircraft",
    term: "T-6B engine",
    body: "PT6A-68 turboprop, flat rated 1,100 SHP at sea level. Variable-pitch constant-speed prop at 2,000 RPM. Ceiling 31,000 ft.",
    unit: "u4",
    conceptIds: ["c-prop-efficiency", "c-ceilings"],
    source: TG("Lift Production and Drag", ["2.105", "2.134"]),
  },
  {
    id: "kc-t6b-airframe",
    category: "aircraft",
    term: "T-6B airframe",
    body: "Semi-monocoque fuselage, full cantilever low wing, swept and tapered with dihedral, geometric and aerodynamic twist, stall strips. Wingspan 33'5\". Crosswind limit 25 kt.",
    unit: "u1",
    conceptIds: ["c-wing-planform", "c-wing-tailoring"],
    source: TG("Basic Theory", ["2.51", "2.52", "2.71"]),
  },
  {
    id: "kc-t6b-spin-empennage",
    category: "aircraft",
    term: "T-6B spin design features",
    body: "Dorsal fin, ventral fin and strakes reduce spin severity. Aerodynamically incapable of a flat spin. Intentional inverted spins prohibited.",
    unit: "u6",
    conceptIds: ["c-spin-factors"],
    source: TG("Spins", ["3.22", "3.25"]),
  },

  /* ---------------- Increase / decrease relationships ---------------- */
  {
    id: "kc-rel-altitude",
    category: "relationship",
    term: "Altitude increases",
    body: "Pressure ↓ · Temperature ↓ · Density ↓ · TAS ↑ for constant IAS · true stall speed ↑ (indicated unchanged) · max range and endurance ↑ · thrust and power available ↓.",
    unit: "u1",
    conceptIds: ["c-density", "c-tas-altitude", "c-stall-speed-altitude", "c-range-endurance-factors"],
    source: TG("Basic Theory", ["2.19", "2.45"]),
  },
  {
    id: "kc-rel-weight",
    category: "relationship",
    term: "Weight increases",
    body: "Stall speed ↑ · induced drag ↑ · T_R and P_R up and right · excesses ↓ · climb ↓ · takeoff/landing distance ↑ as W² · glide RANGE unchanged · turn performance unchanged · limit load factor ↓.",
    unit: "u4",
    conceptIds: ["c-weight-curve-shift", "c-stall-speed", "c-glide", "c-turn-rate-radius"],
    source: TG("Lift Production and Drag", ["2.112"]),
  },
  {
    id: "kc-rel-velocity",
    category: "relationship",
    term: "Velocity increases (level flight)",
    body: "AOA ↓ · parasite drag ↑ as V² · induced drag ↓ · turn radius ↑ · turn rate ↓ at fixed bank.",
    unit: "u3",
    conceptIds: ["c-parasite-drag", "c-induced-drag-factors", "c-v-aoa-inverse"],
    source: TG("Lift Production and Drag", ["2.100"]),
  },
  {
    id: "kc-rel-flaps-down",
    category: "relationship",
    term: "Flaps DOWN",
    body: "C_L ↑ · C_Lmax ↑ · C_Lmax AOA ↓ · stall speed ↓ · drag ↑ · T_R and P_R up and LEFT · takeoff/landing distance ↓ · wake vortex WEAKER.",
    unit: "u2",
    conceptIds: ["c-flaps-cl", "c-config-curve-shift", "c-wake-strength"],
    source: TG("Lift Production and Drag", ["2.115"]),
  },
  {
    id: "kc-rel-gear-down",
    category: "relationship",
    term: "Gear DOWN",
    body: "Parasite drag ↑ · lift unchanged · T_R and P_R shift straight UP · excesses ↓ · climb, range, endurance and glide all ↓.",
    unit: "u4",
    conceptIds: ["c-config-curve-shift"],
    source: TG("Lift Production and Drag", ["2.116"]),
  },
  {
    id: "kc-rel-aoa-up",
    category: "relationship",
    term: "AOA increases",
    body: "C_L ↑ to C_Lmax then ↓ · C_D ↑ · induced drag ↑ · separation point moves FORWARD · past C_Lmax AOA: stall.",
    unit: "u2",
    conceptIds: ["c-cl-vs-aoa", "c-induced-drag", "c-bl-separation"],
    source: TG("Lift Production and Drag", ["2.96"]),
  },

  /* ---------------- Curve shifts ---------------- */
  {
    id: "kc-shift-summary",
    category: "curveShift",
    term: "Curve shift table",
    body: "Weight ↑ → T_R and P_R UP + RIGHT. Altitude ↑ → T_R RIGHT only, P_R RIGHT + UP. Gear down → both UP. Flaps down → both UP + LEFT.",
    unit: "u4",
    conceptIds: ["c-weight-curve-shift", "c-altitude-curve-shift", "c-config-curve-shift"],
    source: TG("Lift Production and Drag", ["2.112", "2.113", "2.114"]),
  },
  {
    id: "kc-shift-vn",
    category: "curveShift",
    term: "V-n envelope shifts",
    body: "Weight ↑ → stall lines sweep RIGHT, Va ↑, limit load factor ↓. Altitude ↑ → indicated redline ↓; stall lines and load limits unchanged. Gear/flaps → envelope much smaller.",
    unit: "u5",
    conceptIds: ["c-envelope-factors"],
    source: TG("Performance and Maneuvering", ["2.167"]),
  },
  {
    id: "kc-shift-cl",
    category: "curveShift",
    term: "CL curve shifts",
    body: "Flaps (camber) → UP and LEFT. Slats/slots (BLC) → peak UP and RIGHT, no change at low AOA. Positive camber → whole curve LEFT.",
    unit: "u2",
    conceptIds: ["c-flaps-cl", "c-blc-devices"],
    source: TG("Stalls", ["3.13", "3.14"]),
  },

  /* ---------------- Traps ---------------- */
  {
    id: "kc-trap-effective-efficient",
    category: "trap",
    term: "Effective vs efficient AOA",
    body: "Most EFFECTIVE = C_Lmax AOA (greatest C_L). Most EFFICIENT = L/Dmax AOA (greatest L/D, minimum total drag).",
    unit: "u3",
    conceptIds: ["c-clmax", "c-ldmax"],
    source: TG("Lift Production and Drag", ["2.96", "2.98"]),
  },
  {
    id: "kc-trap-drag-power-curves",
    category: "trap",
    term: "Bottom of which curve?",
    body: "Bottom of TOTAL DRAG / thrust required = L/Dmax = prop max range. Bottom of POWER REQUIRED = prop max endurance. L/Dmax sits RIGHT of the power curve's bottom.",
    unit: "u4",
    conceptIds: ["c-power-required", "c-max-range", "c-max-endurance"],
    source: TG("Performance and Maneuvering", ["2.137"]),
  },
  {
    id: "kc-trap-range-endurance",
    category: "trap",
    term: "Range vs endurance speed",
    body: "Max RANGE is FASTER and at LOWER AOA than max endurance. Endurance → range: decrease AOA, increase velocity.",
    unit: "u4",
    conceptIds: ["c-max-range", "c-max-endurance"],
    source: TG("Performance and Maneuvering", ["2.137"]),
  },
  {
    id: "kc-trap-separation-direction",
    category: "trap",
    term: "Which way does separation move?",
    body: "FORWARD, toward the leading edge, as AOA increases. 'Aft toward the trailing edge' is the planted wrong answer.",
    unit: "u5",
    conceptIds: ["c-bl-separation"],
    source: TG("Stalls", ["3.3"]),
  },
  {
    id: "kc-trap-stall-lift",
    category: "trap",
    term: "Does a stalled wing make lift?",
    body: "Yes — just less than before, and less than needed. 'The wing no longer produces lift' is wrong.",
    unit: "u5",
    conceptIds: ["c-stall"],
    source: TG("Stalls", ["3.5"]),
  },
  {
    id: "kc-trap-slip-skid",
    category: "trap",
    term: "Slip vs skid",
    body: "SLIP: insufficient rudder, nose OUTSIDE, radius ↑, rate ↓, ball SAME side. SKID: excessive rudder, nose INSIDE, radius ↓, rate ↑, ball OPPOSITE side. Skid stall rolls INVERTED.",
    unit: "u6",
    conceptIds: ["c-slip", "c-skid"],
    source: TG("Performance and Maneuvering", ["2.161"]),
  },
  {
    id: "kc-trap-limit-ultimate",
    category: "trap",
    term: "Limit vs ultimate load",
    body: "Read the direction carefully. Ultimate = 1.5 × limit. Limit = 2/3 of ultimate.",
    unit: "u5",
    conceptIds: ["c-load-definitions"],
    source: TG("Performance and Maneuvering", ["2.164"]),
  },
  {
    id: "kc-trap-power-stall",
    category: "trap",
    term: "Which stall speed is higher?",
    body: "POWER-OFF is higher. Power-on stall speed is lower because thrust's vertical component and prop wash help.",
    unit: "u5",
    conceptIds: ["c-power-on-off-stall"],
    source: TG("Stalls", ["3.8"]),
  },
  {
    id: "kc-trap-tas-ias",
    category: "trap",
    term: "TAS vs IAS",
    body: "TAS is EAS corrected for DENSITY. Above sea level IAS is LESS than TAS, and the gap widens with speed and altitude.",
    unit: "u1",
    conceptIds: ["c-icetg", "c-tas-altitude"],
    source: TG("Basic Theory", ["2.44", "2.45"]),
  },
  {
    id: "kc-trap-spin-conditions",
    category: "trap",
    term: "Spin conditions",
    body: "Exceeding C_Lmax AOA and a YAWING moment. Not a pitching moment. Not L/Dmax AOA.",
    unit: "u6",
    conceptIds: ["c-spin-definition"],
    source: TG("Spins", ["3.19"]),
  },
  {
    id: "kc-trap-wake-strength",
    category: "trap",
    term: "Strongest wake",
    body: "HEAVY, SLOW, CLEAN. The question is often asked as 'weakened by', where the answer is light, fast, dirty.",
    unit: "u6",
    conceptIds: ["c-wake-strength"],
    source: TG("Wake Turbulence and Wind Shear", ["2.188"]),
  },
  {
    id: "kc-trap-humid",
    category: "trap",
    term: "Humidity and density",
    body: "Humid air is LESS dense. Water molecules weigh less than the air molecules they displace.",
    unit: "u1",
    conceptIds: ["c-humidity-density"],
    source: TG("Basic Theory", ["2.24"]),
  },
  {
    id: "kc-trap-aero-force",
    category: "trap",
    term: "Aerodynamic force vs lift",
    body: "Aerodynamic force is the RESULT of pressure and friction distribution. Lift is only its perpendicular component.",
    unit: "u2",
    conceptIds: ["c-aero-force", "c-lift-def"],
    source: TG("Lift Production and Drag", ["2.80"]),
  },
];

export const KNOW_COLD_BY_ID: Record<string, KnowColdCard> = Object.fromEntries(
  KNOW_COLD.map((k) => [k.id, k]),
);

export const KNOW_COLD_CATEGORIES: {
  key: KnowColdCard["category"];
  label: string;
  blurb: string;
}[] = [
  { key: "definition", label: "Definitions", blurb: "Exact wording the exam expects." },
  { key: "equation", label: "Equations", blurb: "Every formula in the course." },
  { key: "sequence", label: "Sequences", blurb: "Ordered lists and mnemonics." },
  { key: "number", label: "Numbers", blurb: "Values worth memorising." },
  { key: "relationship", label: "Relationships", blurb: "Increase / decrease chains." },
  { key: "curveShift", label: "Curve shifts", blurb: "Which way each curve moves." },
  { key: "aircraft", label: "T-6B facts", blurb: "Aircraft-specific values." },
  { key: "trap", label: "Common traps", blurb: "Where the wording bites." },
];
