import type { Lesson, SourceReference } from "@/lib/types";

const TG = (chapter: string, eo: string[]): SourceReference => ({
  document: "Aerodynamics Trainee Guide",
  chapter,
  eo,
});

/** Lessons 14–30: Units 4, 5 and 6. */
export const LESSONS_B: Lesson[] = [
  /* ================================================================ */
  /* UNIT 4 — PERFORMANCE                                              */
  /* ================================================================ */
  {
    id: "l14-thrust-and-power",
    unit: "u4",
    index: 16,
    title: "Thrust & Power Curves",
    subtitle: "Required vs available, and where L/Dmax sits",
    estimatedMinutes: 8,
    mapIcon: "thrustcurve",
    enablingObjectives: [
      "2.101", "2.102", "2.103", "2.104", "2.105", "2.106", "2.107", "2.108", "2.109",
    ],
    conceptIds: [
      "c-thrust-required",
      "c-thrust-available",
      "c-power-required",
      "c-power-available",
      "c-prop-efficiency",
    ],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Four curves run the rest of this unit",
        line: "Thrust required, thrust available, power required, power available. Every performance question is read off them.",
      },
      {
        kind: "model",
        headline: "Thrust required IS the drag curve",
        diagram: { id: "thrust-curves", props: { engine: "turboprop" } },
        bullets: [
          "In equilibrium, thrust must equal drag — so T_R is the total drag curve in pounds",
          "Minimum thrust required is at L/Dmax",
          "Turboprop T_A FALLS with velocity; turbojet T_A stays roughly flat (ram effect)",
        ],
      },
      {
        kind: "model",
        headline: "Power required is thrust × velocity",
        diagram: { id: "power-curves", props: { engine: "turboprop" } },
        bullets: [
          "P_R = T_R × V ÷ 325 (horsepower, V in knots)",
          "Multiplying by V pushes the curve's shape rightward and upward",
          "L/Dmax is NOT at the bottom of P_R — it is to the RIGHT of the bottom",
        ],
      },
      {
        kind: "manipulate",
        headline: "Compare the two curves side by side",
        widget: "ThrustPowerMini",
        line: "Same aircraft, same conditions. Watch where L/Dmax lands on each.",
      },
      {
        kind: "compare",
        headline: "The location trap",
        columns: ["Thrust required curve", "Power required curve"],
        rows: [
          { label: "Bottom of the curve is", a: "L/Dmax — minimum total drag", b: "Minimum power required" },
          { label: "L/Dmax is located", a: "At the bottom", b: "To the RIGHT of the bottom" },
          { label: "For a turboprop that bottom is", a: "Max range", b: "Max endurance" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Minimum thrust required = L/Dmax.",
          "Minimum power required is to the LEFT of L/Dmax.",
          "Velocity and AOA for L/Dmax are the same on both curves.",
          "T-6B: PT6A-68, flat rated 1,100 SHP, constant-speed prop at 2,000 RPM.",
        ],
        formula: "P_R = \\frac{T_R \\times V}{325} \\quad\\quad PE = \\frac{THP}{SHP}",
      },
      { kind: "question", questionId: "q-u4-002" },
      { kind: "question", questionId: "q-u4-001" },
      { kind: "question", questionId: "q-u4-003" },
      { kind: "question", questionId: "q-u4-004" },
      { kind: "question", questionId: "q-u4-005" },
    ],
    questionIds: [
      "q-u4-001", "q-u4-002", "q-u4-003", "q-u4-004", "q-u4-005", "q-cov-004",
    ],
    memorize: [
      "T_R is the drag curve; its bottom is L/Dmax",
      "P_R = T_R × V / 325",
      "L/Dmax is right of the bottom of the power curve",
    ],
    sourceReferences: [TG("Lift Production and Drag", ["2.101", "2.107", "2.108"])],
    labIds: ["lab-performance"],
  },

  {
    id: "l15-excess-and-shifts",
    unit: "u4",
    index: 17,
    title: "Excess Thrust, Excess Power & Curve Shifts",
    subtitle: "Weight, altitude and configuration",
    estimatedMinutes: 9,
    mapIcon: "shift",
    enablingObjectives: [
      "2.110", "2.111", "2.112", "2.113", "2.114", "2.115", "2.116",
    ],
    conceptIds: [
      "c-excess-thrust",
      "c-excess-power",
      "c-weight-curve-shift",
      "c-altitude-curve-shift",
      "c-config-curve-shift",
    ],
    masteryThreshold: 0.85,
    screens: [
      {
        kind: "hook",
        headline: "Excess is the gap between the curves",
        line: "Thrust excess buys you climb ANGLE. Power excess buys you climb RATE. Everything that shrinks the gap shrinks both.",
      },
      {
        kind: "model",
        headline: "Where the excesses peak",
        diagram: { id: "excess-curves", props: { engine: "turboprop" } },
        bullets: [
          "Turboprop: max THRUST excess BELOW L/Dmax · max POWER excess AT L/Dmax",
          "Turbojet: max THRUST excess AT L/Dmax · max POWER excess ABOVE L/Dmax",
          "Max power excess is always faster and lower-AOA than max thrust excess",
          "No thrust excess means no power excess",
        ],
      },
      {
        kind: "manipulate",
        headline: "Shift the curves yourself",
        widget: "CurveShiftLab",
        line: "Toggle weight, altitude, gear and flaps. Note that only ONE of them moves the T_R curve up without moving it sideways.",
      },
      {
        kind: "compare",
        headline: "The three shifts, memorised as directions",
        columns: ["Thrust required", "Power required"],
        rows: [
          { label: "Weight ↑", a: "UP and RIGHT", b: "UP and RIGHT" },
          { label: "Altitude ↑", a: "RIGHT only", b: "RIGHT and UP" },
          { label: "Gear down", a: "UP", b: "UP" },
          { label: "Flaps down", a: "UP and LEFT", b: "UP and LEFT" },
        ],
      },
      {
        kind: "chain",
        headline: "Why altitude does not raise T_R",
        nodes: [
          { label: "Altitude", trend: "up", emphasis: true },
          { label: "Density", trend: "down" },
          { label: "Velocity needed for the same lift", trend: "up" },
          { label: "Dynamic pressure at that AOA", trend: "same" },
          { label: "Drag and thrust required", trend: "same", emphasis: true },
        ],
        footnote:
          "The density loss is exactly offset by the velocity gain. Power required DOES rise, because the same thrust is multiplied by a higher velocity.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Weight and configuration change T_R/P_R only. Altitude also lowers T_A and P_A.",
          "Every one of the four changes REDUCES both excesses.",
          "Angle of climb ← thrust excess. Rate of climb ← power excess.",
        ],
        formula: "T_E = T_A - T_R \\quad\\quad P_E = P_A - P_R",
      },
      { kind: "question", questionId: "cs-u4-011" },
      { kind: "question", questionId: "cs-u4-012" },
      { kind: "question", questionId: "cs-u4-013" },
      { kind: "question", questionId: "cs-u4-014" },
      { kind: "question", questionId: "q-u4-006" },
      { kind: "question", questionId: "cc-u4-016" },
    ],
    questionIds: [
      "cs-u4-010", "cs-u4-011", "cs-u4-012", "cs-u4-013", "cs-u4-014",
      "q-u4-006", "q-u4-007", "q-u4-008", "q-u4-009", "q-u4-015", "cc-u4-016",
    ],
    memorize: [
      "Weight ↑ → T_R and P_R up AND right",
      "Altitude ↑ → T_R right only; P_R right AND up",
      "Gear down → straight up. Flaps down → up and left.",
    ],
    sourceReferences: [TG("Lift Production and Drag", ["2.111", "2.112", "2.113", "2.115", "2.116"])],
    explainerIds: ["x-altitude-curve-shifts", "x-weight-changes-everything"],
    labIds: ["lab-performance"],
  },

  {
    id: "l16-takeoff-landing",
    unit: "u4",
    index: 18,
    title: "Takeoff & Landing Performance",
    subtitle: "1.2, 1.3 and the 4-H Club",
    estimatedMinutes: 7,
    mapIcon: "runway",
    enablingObjectives: [
      "2.124", "2.125", "2.126", "2.127", "2.128", "2.147", "2.148",
      "2.149", "2.150", "2.151",
    ],
    conceptIds: [
      "c-takeoff-landing-speeds",
      "c-takeoff-distance",
      "c-4h-club",
      "c-hydroplaning",
      "c-nwlotd",
      "c-crosswind-technique",
      "c-crosswind-limits",
    ],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Weight is squared. Everything else is a footnote.",
        line: "Doubling gross weight QUADRUPLES both takeoff and landing distance.",
      },
      {
        kind: "model",
        headline: "The net accelerating force",
        diagram: { id: "takeoff-forces" },
        bullets: [
          "T − D − F_R is what accelerates you to takeoff speed",
          "Rolling friction F_R = μ(W − L), so it shrinks as lift builds",
          "μ depends on runway surface, condition, tyre type and braking",
        ],
      },
      {
        kind: "manipulate",
        headline: "Load the aircraft and change the day",
        widget: "TakeoffLab",
        line: "Weight, elevation, temperature, humidity, wind and flaps. Watch speed and distance move independently.",
      },
      {
        kind: "compare",
        headline: "The two safety margins",
        columns: ["Takeoff", "Landing"],
        rows: [
          { label: "Speed", a: "1.2 × Vs (20% margin)", b: "1.3 × Vs (30% margin)" },
          {
            label: "Why that margin",
            a: "Minimises reverse-command time, allows shallow turns",
            b: "Low altitude AND low power setting",
          },
          { label: "Net force", a: "T − D − F_R accelerates", b: "D + F_R − T decelerates" },
        ],
      },
      {
        kind: "chain",
        headline: "The 4-H Club",
        nodes: [
          { label: "High · Hot · Humid", trend: "up", emphasis: true },
          { label: "Air density", trend: "down" },
          { label: "TRUE takeoff speed required", trend: "up" },
          { label: "Engine thrust available", trend: "down" },
          { label: "Takeoff distance", trend: "up", emphasis: true },
        ],
        footnote:
          "Heavy is the fourth H and hits the distance equation squared. Note that INDICATED takeoff speed never changes.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Takeoff 1.2 Vs. Landing 1.3 Vs.",
          "Doubling weight quadruples takeoff and landing distance.",
          "Indicated takeoff airspeed is constant regardless of density.",
          "Headwind shortens the roll; tailwind lengthens it; flaps shorten it.",
          "Hydroplaning speed (mph) = 9√(tyre pressure) — independent of weight.",
        ],
        formula: "S_{TO} = \\frac{W^2}{g\\rho S C_{L\\,max}(T - D - F_R)}",
        mnemonic: "High · Hot · Humid · Heavy",
      },
      { kind: "question", questionId: "q-u4-017" },
      { kind: "question", questionId: "q-u4-019" },
      { kind: "question", questionId: "q-u4-018" },
      { kind: "question", questionId: "q-u4-020" },
      { kind: "question", questionId: "q-u4-021" },
    ],
    questionIds: [
      "q-u4-017", "q-u4-018", "q-u4-019", "q-u4-020", "q-u4-021", "q-u1-008",
      "q-cov-007",
      "q-db-015", "q-db-016", "q-db-017", "q-db-018", "q-db-019", "q-db-048",
    ],
    memorize: [
      "Takeoff 1.2 Vs · Landing 1.3 Vs",
      "Weight doubles → distance ×4",
      "4-H Club: High, Hot, Humid, Heavy",
    ],
    sourceReferences: [TG("Performance and Maneuvering", ["2.124", "2.127", "2.150"])],
  },

  {
    id: "l17-climb",
    unit: "u4",
    index: 19,
    title: "Climb Performance",
    subtitle: "Vx, Vy and ceilings",
    estimatedMinutes: 6,
    mapIcon: "climb",
    enablingObjectives: ["2.129", "2.130", "2.131", "2.132", "2.133", "2.134"],
    conceptIds: ["c-vx-vy", "c-ceilings", "c-excess-thrust", "c-excess-power",
      "c-best-climb-profile",
    ],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Angle or rate — pick the one the obstacle needs",
        line: "Both climbs are flown at maximum power. The only difference is AOA and airspeed.",
      },
      {
        kind: "model",
        headline: "Two different geometries",
        diagram: { id: "climb-vectors" },
        bullets: [
          "Angle of climb: altitude gained per unit of GROUND DISTANCE — obstacle clearance",
          "Rate of climb: altitude gained per unit of TIME — expedited climb",
          "sin γ = T_E / W · ROC = P_E / W",
        ],
      },
      {
        kind: "chain",
        headline: "Which excess drives which",
        nodes: [
          { label: "Thrust excess", emphasis: true },
          { label: "→ Angle of climb (Vx)" },
          { label: "Power excess", emphasis: true },
          { label: "→ Rate of climb (Vy)" },
        ],
        footnote:
          "Turboprop: Vx is BELOW L/Dmax airspeed; Vy is AT L/Dmax. Turbojet: Vx AT L/Dmax; Vy above it.",
      },
      {
        kind: "manipulate",
        headline: "Fly both profiles",
        widget: "ClimbLab",
        line: "Same 30 seconds of climb. Compare altitude gained and ground covered.",
      },
      {
        kind: "compare",
        headline: "What changes each profile",
        columns: ["Max angle of climb", "Max rate of climb"],
        rows: [
          { label: "Weight ↑ / altitude ↑ / gear / flaps", a: "Decreases", b: "Decreases" },
          { label: "Headwind", a: "INCREASES the angle", b: "No effect" },
          { label: "Tailwind", a: "Decreases the angle", b: "No effect" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Vx = angle = obstacle clearance = thrust excess.",
          "Vy = rate = expedited climb = power excess.",
          "Ceilings: combat 500 · cruise 300 · service 100 · absolute 0 fpm.",
          "T-6B recommended best climb 140 KIAS; operational ceiling 31,000 ft.",
        ],
        formula: "\\sin\\gamma = \\frac{T_E}{W} \\quad\\quad ROC = \\frac{P_E}{W}",
      },
      { kind: "question", questionId: "q-u4-022" },
      { kind: "question", questionId: "q-u4-023" },
      { kind: "question", questionId: "q-u4-024" },
      { kind: "question", questionId: "q-u4-025" },
    ],
    questionIds: [
      "q-u4-022", "q-u4-023", "q-u4-024", "q-u4-025", "q-u4-007", "q-cov-005",
      "q-db-011", "q-db-012",
    ],
    memorize: [
      "Vx = angle = obstacle = thrust excess",
      "Vy = rate = expedite = power excess",
      "Headwind helps angle, not rate",
    ],
    sourceReferences: [TG("Performance and Maneuvering", ["2.129", "2.131", "2.133"])],
  },

  {
    id: "l18-range-endurance",
    unit: "u4",
    index: 20,
    title: "Max Range & Max Endurance",
    subtitle: "Distance vs time, on the right curve",
    estimatedMinutes: 8,
    mapIcon: "cruise",
    enablingObjectives: [
      "2.135", "2.136", "2.137", "2.138", "2.139", "2.140", "2.141",
    ],
    conceptIds: [
      "c-max-range",
      "c-max-endurance",
      "c-range-endurance-factors",
      "c-mach",
      "c-fuel-flow-turboprop",
    ],
    masteryThreshold: 0.85,
    screens: [
      {
        kind: "hook",
        headline: "Range is distance. Endurance is time. They are different speeds.",
        line: "And which curve you read them off depends on whether you have a propeller.",
      },
      {
        kind: "model",
        headline: "Turboprop: fuel flow follows POWER",
        diagram: { id: "power-curves", props: { showRangeEndurance: true } },
        bullets: [
          "Minimum fuel flow = minimum power required = bottom of the P_R curve = MAX ENDURANCE",
          "Best fuel-per-mile = tangent from the origin = L/Dmax = MAX RANGE",
          "T-6B: max endurance 8.8 units AOA · max range 4.4 units AOA",
        ],
      },
      {
        kind: "compare",
        headline: "Prop vs jet — the reversal",
        columns: ["Turboprop", "Turbojet"],
        rows: [
          { label: "Fuel flow follows", a: "Power available", b: "Thrust available" },
          { label: "Max endurance", a: "Below L/Dmax, AOA above L/Dmax AOA", b: "AT L/Dmax" },
          { label: "Max range", a: "AT L/Dmax", b: "Above L/Dmax, AOA below L/Dmax AOA" },
        ],
      },
      {
        kind: "chain",
        headline: "Endurance → range",
        nodes: [
          { label: "Currently at max endurance", emphasis: true },
          { label: "Angle of attack", trend: "down" },
          { label: "Velocity", trend: "up" },
          { label: "Now at max range", emphasis: true },
        ],
        footnote: "Max range is always the FASTER of the two. If you answered 'slower', re-read this.",
      },
      {
        kind: "manipulate",
        headline: "Move the tangent line",
        widget: "RangeEnduranceLab",
        line: "Add a headwind and watch the tangent's base slide right — and the best range speed increase with it.",
      },
      {
        kind: "compare",
        headline: "What helps and what hurts",
        columns: ["Max range", "Max endurance"],
        rows: [
          { label: "Weight ↑", a: "Decreases (and speed ↑)", b: "Decreases (and speed ↑)" },
          { label: "Altitude ↑", a: "INCREASES", b: "INCREASES" },
          { label: "Gear or flaps down", a: "Decreases", b: "Decreases" },
          { label: "Headwind", a: "Decreases", b: "No effect" },
          { label: "Tailwind", a: "Increases", b: "No effect" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Turboprop max range = L/Dmax = minimum total drag = parasite equals induced.",
          "Turboprop max endurance = bottom of the power required curve.",
          "Max range is FASTER and LOWER AOA than max endurance.",
          "Altitude improves BOTH. Wind affects range only.",
        ],
        formula: "M = \\frac{TAS}{LSOS}",
      },
      { kind: "question", questionId: "q-u4-027" },
      { kind: "question", questionId: "q-u4-028" },
      { kind: "question", questionId: "q-u4-029" },
      { kind: "question", questionId: "q-u4-031" },
      { kind: "question", questionId: "q-u4-032" },
      { kind: "question", questionId: "q-u4-034" },
    ],
    questionIds: [
      "q-u4-026", "q-u4-027", "q-u4-028", "q-u4-029", "q-u4-030",
      "q-u4-031", "q-u4-032", "q-u4-033", "q-u4-034", "q-cov-006",
      "q-db-013", "q-db-014",
    ],
    memorize: [
      "Prop: range at L/Dmax, endurance at bottom of power curve",
      "Max range is faster than max endurance",
      "Altitude improves both range and endurance",
    ],
    sourceReferences: [TG("Performance and Maneuvering", ["2.136", "2.137", "2.138"])],
    labIds: ["lab-performance"],
  },

  {
    id: "l19-glide-reverse-command",
    unit: "u4",
    index: 21,
    title: "Glide & the Region of Reverse Command",
    subtitle: "Best glide, and the part of the curve that kills",
    estimatedMinutes: 8,
    mapIcon: "glide",
    enablingObjectives: ["2.142", "2.143", "2.144", "2.145", "2.146"],
    conceptIds: ["c-glide", "c-reverse-command"],
    masteryThreshold: 0.85,
    screens: [
      {
        kind: "hook",
        headline: "You cannot stretch a glide",
        line: "Any AOA away from L/Dmax AOA reduces the distance you travel. Pulling harder makes it worse.",
      },
      {
        kind: "model",
        headline: "Glide range vs glide endurance",
        diagram: { id: "glide-vectors" },
        bullets: [
          "Max glide RANGE = minimum angle of descent = L/Dmax, for ANY aircraft",
          "Max glide ENDURANCE = minimum rate of descent = bottom of the P_R curve",
          "T-6B: best glide 125 KIAS, glide ratio 11:1 clean",
        ],
      },
      {
        kind: "chain",
        headline: "Weight in a glide",
        nodes: [
          { label: "Weight", trend: "up", emphasis: true },
          { label: "Hold L/Dmax AOA → L/D ratio unchanged" },
          { label: "Angle of descent", trend: "same" },
          { label: "Glide RANGE", trend: "same", emphasis: true },
          { label: "Airspeed and rate of descent", trend: "up" },
        ],
        footnote: "Same distance, arrived at faster. Glide ENDURANCE falls.",
      },
      {
        kind: "model",
        headline: "Left of max endurance is the region of reverse command",
        diagram: { id: "power-curves", props: { showRegions: true } },
        bullets: [
          "Normal command (right): airspeed-STABLE — a gust self-corrects",
          "Reverse command (left): airspeed-UNSTABLE — a slow-down keeps slowing",
          "In reverse command, velocity and throttle are INVERSELY related",
        ],
      },
      {
        kind: "manipulate",
        headline: "Try to slow down with the stick",
        widget: "ReverseCommandLab",
        line: "Pull to slow. Watch power required climb and a deficit open. Then try it with throttle instead.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Max glide range is at L/Dmax for every aircraft, regardless of engine.",
          "Weight does not change glide range — only speed and rate of descent.",
          "Reverse command: to fly slower in level flight, ADD POWER.",
          "Feather a failed propeller — windmilling drastically increases drag.",
        ],
      },
      { kind: "question", questionId: "q-u4-035" },
      { kind: "question", questionId: "trap-u4-038" },
      { kind: "question", questionId: "q-u4-036" },
      { kind: "question", questionId: "q-u4-039" },
      { kind: "question", questionId: "q-u4-040" },
      { kind: "question", questionId: "cc-u4-042" },
    ],
    questionIds: [
      "q-u4-035", "q-u4-036", "q-u4-037", "trap-u4-038", "q-u4-039",
      "q-u4-040", "gr-u4-041", "cc-u4-042", "q-u4-043",
    ],
    memorize: [
      "Max glide range = L/Dmax, always",
      "Reverse command: slower requires MORE power",
      "Weight does not change glide distance",
    ],
    sourceReferences: [TG("Performance and Maneuvering", ["2.143", "2.144", "2.146"])],
    explainerIds: ["x-region-of-reverse-command"],
  },

  /* ================================================================ */
  /* UNIT 5 — LIMITS & MANEUVERING                                     */
  /* ================================================================ */
  {
    id: "l20-boundary-layer",
    unit: "u5",
    index: 22,
    title: "The Boundary Layer",
    subtitle: "Laminar, turbulent, and the adverse gradient",
    estimatedMinutes: 6,
    mapIcon: "boundary",
    enablingObjectives: ["3.1", "3.2", "3.3"],
    conceptIds: ["c-boundary-layer", "c-laminar-turbulent", "c-pressure-gradient"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "A millimetre of air decides whether the wing works",
        line: "Everything about stalls happens inside a layer about as thick as a playing card.",
      },
      {
        kind: "model",
        headline: "Laminar first, then turbulent",
        diagram: { id: "boundary-layer", props: { aoa: 4 } },
        bullets: [
          "Laminar: smooth streamlines, very little friction, separates EASILY",
          "Turbulent: disorganised, more friction drag, ADHERES BETTER",
          "The layer is laminar near the leading edge and turns turbulent as it moves aft",
        ],
      },
      {
        kind: "chain",
        headline: "The pressure gradient runs both ways",
        nodes: [
          { label: "LE (high Pₛ) → max thickness (low Pₛ)" },
          { label: "FAVOURABLE gradient — helps the layer adhere", emphasis: true },
          { label: "Max thickness (low Pₛ) → TE (high Pₛ)" },
          { label: "ADVERSE gradient — impedes the layer", emphasis: true },
        ],
      },
      {
        kind: "manipulate",
        headline: "Raise AOA and watch the separation point",
        widget: "BoundaryLayerSlider",
        line: "The separation point marches FORWARD as AOA increases. That direction is the whole exam question.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Boundary layer: local airflow retardation due to viscosity, ~1 mm at the leading edge.",
          "Laminar = low friction, separates easily. Turbulent = more friction, adheres better.",
          "AOA ↑ → BL kinetic energy ↓ → adverse gradient ↑ → separation point moves FORWARD.",
        ],
      },
      { kind: "question", questionId: "q-u5-001" },
      { kind: "question", questionId: "q-u5-002" },
      { kind: "question", questionId: "sp-u5-005" },
      { kind: "question", questionId: "q-u5-004" },
      { kind: "question", questionId: "trap-u5-006" },
    ],
    questionIds: ["q-u5-001", "q-u5-002", "q-u5-003", "q-u5-004", "sp-u5-005", "trap-u5-006"],
    memorize: [
      "Turbulent flow adheres better and delays separation",
      "Adverse gradient: max thickness → trailing edge",
      "Separation point moves FORWARD with increasing AOA",
    ],
    sourceReferences: [TG("Stalls", ["3.1", "3.2", "3.3"])],
    explainerIds: ["x-why-a-wing-stalls"],
  },

  {
    id: "l21-the-stall",
    unit: "u5",
    index: 23,
    title: "The Stall",
    subtitle: "One cause, one cure",
    estimatedMinutes: 7,
    mapIcon: "stall",
    enablingObjectives: ["3.4", "3.5", "3.6", "3.7", "3.9", "3.16", "3.17", "3.18"],
    conceptIds: [
      "c-stall",
      "c-clmax-aoa",
      "c-bl-separation",
      "c-stall-recovery",
      "c-stall-pattern",
      "c-wing-tailoring",
    ],
    masteryThreshold: 0.85,
    screens: [
      {
        kind: "hook",
        headline: "A stalled wing still makes lift",
        line: "It just makes LESS lift than it did a moment ago — and less than you need. That is the whole definition.",
      },
      {
        kind: "model",
        headline: "Separation walks forward until CL drops",
        diagram: { id: "stall-progression", props: { aoa: 16 } },
        bullets: [
          "Below CLmax AOA the separation point sits near the trailing edge",
          "As AOA rises it progresses forward",
          "Far enough forward, the suction on top collapses and C_L falls — the stall",
        ],
      },
      {
        kind: "chain",
        headline: "The stall chain",
        nodes: [
          { label: "Angle of attack", trend: "up", emphasis: true },
          { label: "Coefficient of lift", trend: "up" },
          { label: "C_Lmax reached", trend: "same" },
          { label: "More angle of attack", trend: "up" },
          { label: "Coefficient of lift", trend: "down", emphasis: true },
        ],
        footnote: "Notice that airspeed appears nowhere in this chain. AOA is the only cause.",
      },
      {
        kind: "compare",
        headline: "Stall pattern by planform",
        columns: ["Stalls first at", "Consequence"],
        rows: [
          { label: "Rectangular (λ = 1.0)", a: "Root", b: "Good warning, ailerons stay effective" },
          { label: "Highly tapered (λ = 0.25)", a: "Tip", b: "Strong tip-stall tendency" },
          { label: "Swept", a: "Tip", b: "Stall spreads rapidly inboard" },
          { label: "Elliptical", a: "Everywhere at once", b: "Little warning; aileron loss near the stall" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Stall = an increase in AOA results in a DECREASE in C_L.",
          "The ONLY cause of a stall is excessive AOA.",
          "The only action required to recover is to reduce AOA below C_Lmax AOA.",
          "T-6B: stall at 18 units AOA · stick shaker 15.5 units · controls lost ailerons → elevator → rudder.",
          "Recovery: RELAX, MAX, LEVEL, BALL.",
        ],
        mnemonic: "RELAX · MAX · LEVEL · BALL",
      },
      { kind: "question", questionId: "q-u5-007" },
      { kind: "question", questionId: "q-u5-008" },
      { kind: "question", questionId: "cc-u5-017" },
      { kind: "question", questionId: "q-u5-009" },
      { kind: "question", questionId: "q-u5-011" },
      { kind: "question", questionId: "q-u5-022" },
    ],
    questionIds: [
      "q-u5-007", "q-u5-008", "q-u5-009", "q-u5-010", "q-u5-011",
      "cc-u5-017", "q-u5-022", "q-u5-023",
    ],
    memorize: [
      "Stall: AOA ↑ gives CL ↓",
      "Only cause: excessive AOA",
      "T-6B stalls at 18 units, always",
    ],
    sourceReferences: [TG("Stalls", ["3.5", "3.6", "3.9", "3.17", "3.18"])],
    explainerIds: ["x-why-a-wing-stalls"],
  },

  {
    id: "l22-stall-speed",
    unit: "u5",
    index: 24,
    title: "Stall Speed Factors",
    subtitle: "Weight, altitude, power and load",
    estimatedMinutes: 7,
    mapIcon: "stallspeed",
    enablingObjectives: ["3.8", "3.10", "3.11"],
    conceptIds: [
      "c-stall-speed",
      "c-stall-speed-altitude",
      "c-power-on-off-stall",
      "c-accelerated-stall",
    ],
    masteryThreshold: 0.85,
    screens: [
      {
        kind: "hook",
        headline: "The stalling ANGLE never moves. The stalling SPEED moves constantly.",
        line: "Weight, altitude, power setting, flaps and load factor all change the speed at which you reach 18 units.",
      },
      {
        kind: "model",
        headline: "Read the equation and every factor falls out",
        diagram: { id: "stall-speed-equation" },
        bullets: [
          "Weight on top: heavier means faster stall speed",
          "Density underneath: thinner air means higher TRUE stall speed",
          "C_Lmax underneath: flaps down means lower stall speed",
          "ρ₀ is a CONSTANT — which is why indicated stall speed does not move with altitude",
        ],
      },
      {
        kind: "manipulate",
        headline: "Stall Speed Lab",
        widget: "StallSpeedLab",
        line: "Change weight, altitude, flaps, power and bank. Watch true and indicated stall speed diverge.",
      },
      {
        kind: "compare",
        headline: "True vs indicated stall speed",
        columns: ["True stall speed", "Indicated stall speed"],
        rows: [
          { label: "Uses which density", a: "Local ρ", b: "Sea-level ρ₀ (a constant)" },
          { label: "Altitude ↑", a: "INCREASES", b: "UNCHANGED" },
          { label: "Weight ↑", a: "Increases", b: "Increases" },
          { label: "Flaps down", a: "Decreases", b: "Decreases" },
        ],
      },
      {
        kind: "chain",
        headline: "Why power-on stall speed is LOWER",
        nodes: [
          { label: "Power applied at high pitch attitude", emphasis: true },
          { label: "Vertical component of thrust supports part of the weight" },
          { label: "Propeller accelerates air over the wing root" },
          { label: "Lift the wing must make", trend: "down" },
          { label: "Stall speed", trend: "down", emphasis: true },
        ],
        footnote: "So power-OFF stall speed is the HIGHER of the two. Lower stall speed is the favourable case.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Vs = √(2W / ρSC_Lmax) — true. Swap ρ for ρ₀ to get indicated.",
          "Altitude ↑: true stall speed ↑, indicated stall speed unchanged.",
          "Power-on stall speed < power-off stall speed.",
          "Accelerated stall speed = Vs × √n.",
        ],
        formula: "V_S = \\sqrt{\\frac{2Wn}{\\rho S C_{L\\,max}}}",
      },
      { kind: "question", questionId: "q-u5-013" },
      { kind: "question", questionId: "q-u5-014" },
      { kind: "question", questionId: "q-u5-015" },
      { kind: "question", questionId: "q-u5-016" },
      { kind: "question", questionId: "q-u5-012" },
    ],
    questionIds: [
      "q-u5-012", "q-u5-013", "q-u5-014", "q-u5-015", "q-u5-016", "q-u5-028",
    ],
    memorize: [
      "Vs = √(2Wn / ρSCLmax)",
      "Altitude: true stall speed ↑, indicated unchanged",
      "Power-on stall speed is lower than power-off",
    ],
    sourceReferences: [TG("Stalls", ["3.8", "3.10", "3.11"])],
  },

  {
    id: "l23-high-lift-devices",
    unit: "u5",
    index: 25,
    title: "High Lift Devices",
    subtitle: "Slats raise the stall AOA; flaps lower it",
    estimatedMinutes: 6,
    mapIcon: "flaps",
    enablingObjectives: ["3.12", "3.13", "3.14", "3.15"],
    conceptIds: ["c-high-lift-purpose", "c-blc-devices", "c-camber-devices"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Two families, opposite effects on stalling AOA",
        line: "Both raise CLmax. Only one lets you stall at a HIGHER angle of attack.",
      },
      {
        kind: "model",
        headline: "Boundary layer control vs camber change",
        diagram: { id: "high-lift-comparison", props: { device: "slat" } },
        bullets: [
          "Slots and slats: inject high-energy air into the boundary layer → separation delayed",
          "Vortex generators: trip a turbulent layer that adheres better",
          "Flaps: add camber → more C_L at every AOA, but the stall arrives sooner",
        ],
      },
      {
        kind: "compare",
        headline: "The distinction the exam wants",
        columns: ["BLC devices (slot/slat)", "Camber devices (flaps)"],
        rows: [
          { label: "C_Lmax", a: "Increases", b: "Increases" },
          { label: "C_Lmax AOA", a: "INCREASES", b: "DECREASES" },
          { label: "C_L at low AOA", a: "No change (camber unchanged)", b: "Increases" },
          { label: "Drag", a: "Small increase", b: "Large increase" },
        ],
      },
      {
        kind: "manipulate",
        headline: "Deploy each device on the CL curve",
        widget: "HighLiftLab",
        line: "Toggle slat and flap independently and watch the curve move up, left or right.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Primary purpose of high lift devices: reduce takeoff and landing speeds.",
          "BLC: CLmax ↑ AND CLmax AOA ↑.",
          "Flaps: CLmax ↑ but CLmax AOA ↓.",
          "Fowler flaps add camber AND area AND slots. The T-6B uses split flaps.",
          "First 50% of flap travel gives most of the lift for less than half the drag.",
        ],
      },
      { kind: "question", questionId: "q-u5-019" },
      { kind: "question", questionId: "ba-u5-020" },
      { kind: "question", questionId: "q-u5-018" },
      { kind: "question", questionId: "q-u5-021" },
      { kind: "question", questionId: "q-u2-019" },
    ],
    questionIds: ["q-u5-018", "q-u5-019", "ba-u5-020", "q-u5-021", "q-u2-019"],
    memorize: [
      "Slats/slots: CLmax ↑ and CLmax AOA ↑",
      "Flaps: CLmax ↑ but CLmax AOA ↓",
      "Purpose: lower takeoff and landing speeds",
    ],
    sourceReferences: [TG("Stalls", ["3.12", "3.13", "3.14", "3.15"])],
  },

  {
    id: "l24-turns-load-factor",
    unit: "u5",
    index: 26,
    title: "Turns & Load Factor",
    subtitle: "Why bank raises stall speed",
    estimatedMinutes: 8,
    mapIcon: "turn",
    enablingObjectives: [
      "2.154", "2.155", "2.156", "2.157", "2.158", "2.159", "2.160",
      "2.162", "2.163",
    ],
    conceptIds: [
      "c-turn-lift",
      "c-load-factor",
      "c-accelerated-stall",
      "c-turn-rate-radius",
      "c-turn-weight-thrust-drag",
    ],
    masteryThreshold: 0.85,
    screens: [
      {
        kind: "hook",
        headline: "The chain that kills people on the approach turn",
        line: "Bank raises load factor, which raises the lift you need, which raises stall speed. At 200 ft that is fatal.",
      },
      {
        kind: "model",
        headline: "Lift splits into two components",
        diagram: { id: "turn-forces", props: { bank: 45 } },
        bullets: [
          "Horizontal component (centripetal force) turns the aircraft",
          "Vertical component must still equal weight to hold altitude",
          "Total lift must therefore INCREASE — that is the back stick",
          "More lift means more induced drag, so power must increase too",
        ],
      },
      {
        kind: "manipulate",
        headline: "Turn Lab",
        widget: "TurnLabMini",
        line: "Bank and airspeed only. Watch load factor, stall-speed multiplier, turn rate and turn radius.",
      },
      {
        kind: "chain",
        headline: "The signature maneuvering chain",
        nodes: [
          { label: "Bank angle", trend: "up", emphasis: true },
          { label: "Load factor n = 1/cos φ", trend: "up" },
          { label: "Lift required", trend: "up" },
          { label: "Angle of attack demanded", trend: "up" },
          { label: "Stall speed = Vs√n", trend: "up", emphasis: true },
        ],
        footnote: "60° bank → 2 G → stall speed 40% higher. Above 45° the numbers climb fast.",
      },
      {
        kind: "compare",
        headline: "Turn rate vs turn radius",
        columns: ["Turn rate ω", "Turn radius r"],
        rows: [
          { label: "Formula", a: "g tan φ / V", b: "V² / (g tan φ)" },
          { label: "Airspeed ↑ at fixed bank", a: "Decreases", b: "Increases" },
          { label: "Bank ↑ at fixed airspeed", a: "Increases", b: "Decreases" },
          { label: "Weight", a: "No effect", b: "No effect" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "n = L / W = 1 / cos φ.",
          "60° angle of bank = 2 G.",
          "Accelerated stall speed = Vs × √n.",
          "Turn rate and radius depend ONLY on airspeed and bank angle — never on weight.",
        ],
        formula: "n = \\frac{1}{\\cos\\phi} \\quad\\quad \\omega = \\frac{g\\tan\\phi}{V} \\quad\\quad r = \\frac{V^2}{g\\tan\\phi}",
      },
      { kind: "question", questionId: "cc-u5-027" },
      { kind: "question", questionId: "q-u5-025" },
      { kind: "question", questionId: "q-u5-026" },
      { kind: "question", questionId: "q-u5-028" },
      { kind: "question", questionId: "q-u5-030" },
      { kind: "question", questionId: "trap-u5-031" },
    ],
    questionIds: [
      "q-u5-024", "q-u5-025", "q-u5-026", "cc-u5-027", "q-u5-028",
      "sp-u5-029", "q-u5-030", "trap-u5-031", "q-cov-008",
      "q-db-020", "q-db-021", "q-db-022",
    ],
    memorize: [
      "n = L/W = 1/cos φ",
      "60° bank = 2 G = 40% higher stall speed",
      "Turn performance: airspeed and bank only",
    ],
    sourceReferences: [TG("Performance and Maneuvering", ["2.158", "2.162", "2.163"])],
    explainerIds: ["x-why-bank-raises-stall-speed", "x-turn-rate-vs-radius"],
    labIds: ["lab-turn"],
  },

  {
    id: "l25-vn-diagram",
    unit: "u5",
    index: 27,
    title: "The V-n Diagram",
    subtitle: "Structural limits and the safe envelope",
    estimatedMinutes: 8,
    mapIcon: "vn",
    enablingObjectives: ["2.164", "2.165", "2.166", "2.167", "2.168"],
    conceptIds: [
      "c-load-definitions",
      "c-vn-diagram",
      "c-maneuver-speed",
      "c-envelope-factors",
    ],
    masteryThreshold: 0.85,
    screens: [
      {
        kind: "hook",
        headline: "One picture holds every structural limit you have",
        line: "Indicated airspeed across, load factor up. Stay inside the box.",
      },
      {
        kind: "model",
        headline: "Four boundaries",
        diagram: { id: "vn-diagram", props: {} },
        bullets: [
          "Accelerated stall lines (left, curved) — set by C_Lmax AOA",
          "Positive and negative limit load factors (top and bottom)",
          "Redline airspeed V_NE (right)",
          "Maneuver point — where the stall line meets the limit load line",
        ],
      },
      {
        kind: "manipulate",
        headline: "V-n Lab",
        widget: "VnLabMini",
        line: "Drag the aircraft state around the envelope. Cross a boundary and see exactly what breaks.",
      },
      {
        kind: "compare",
        headline: "Three loads worth distinguishing",
        columns: ["Definition", "If exceeded"],
        rows: [
          {
            label: "Limit load",
            a: "Max anticipated in normal ops, no risk of permanent deformation",
            b: "Possible deformation — report the over-G",
          },
          {
            label: "Elastic limit",
            a: "Max load a component can take and still return to shape",
            b: "Permanent deformation, may still be usable",
          },
          {
            label: "Ultimate load",
            a: "Max without structural failure = 1.5 × limit",
            b: "Structural failure imminent",
          },
        ],
      },
      {
        kind: "chain",
        headline: "Why you cannot over-G below Va",
        nodes: [
          { label: "Airspeed below maneuver speed", emphasis: true },
          { label: "Accelerated stall line lies below the limit load line" },
          { label: "Pulling harder reaches C_Lmax AOA first" },
          { label: "The wing stalls before the structure is loaded", emphasis: true },
        ],
        footnote: "T-6B maneuver speed: 227 KIAS at maximum gross weight.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Ultimate = 1.5 × limit. Limit = 2/3 of ultimate.",
          "T-6B: +7.0 / −3.5 G limit; +4.7 / −1.0 G asymmetric; Va 227 KIAS.",
          "Weight ↑ → stall lines sweep RIGHT, Va ↑, limit load factor ↓.",
          "Altitude ↑ → indicated redline ↓; load limits and stall lines unchanged.",
          "Asymmetric or gust loading → reduce pilot-induced load to 2/3 of limit.",
        ],
      },
      { kind: "question", questionId: "q-u5-032" },
      { kind: "question", questionId: "gr-u5-037" },
      { kind: "question", questionId: "q-u5-035" },
      { kind: "question", questionId: "q-u5-036" },
      { kind: "question", questionId: "cs-u5-039" },
      { kind: "question", questionId: "q-u5-040" },
    ],
    questionIds: [
      "q-u5-032", "q-u5-033", "q-u5-034", "q-u5-035", "q-u5-036",
      "gr-u5-037", "q-u5-038", "cs-u5-039", "q-u5-040", "q-u5-041",
      "q-u5-042", "q-u5-043",
    ],
    memorize: [
      "Ultimate load = 1.5 × limit load",
      "Maneuver point = accelerated stall line meets limit load",
      "Below Va you stall before you over-G",
    ],
    sourceReferences: [TG("Performance and Maneuvering", ["2.164", "2.166", "2.167"])],
    explainerIds: ["x-vn-diagram"],
    labIds: ["lab-vn"],
  },

  /* ================================================================ */
  /* UNIT 6 — DEPARTURES & HAZARDS                                     */
  /* ================================================================ */
  {
    id: "l26-slips-skids-prop",
    unit: "u6",
    index: 28,
    title: "Slips, Skids & Propeller Effects",
    subtitle: "Why the nose always wants to go left",
    estimatedMinutes: 7,
    mapIcon: "rudder",
    enablingObjectives: ["2.152", "2.153", "2.161"],
    conceptIds: ["c-slip", "c-skid", "c-p-factor", "c-slipstream-swirl", "c-torque-gyro"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "One of these two stalls rolls you inverted",
        line: "Slip and skid look similar on the ball. They fail very differently.",
      },
      {
        kind: "model",
        headline: "Read the ball, read the nose",
        diagram: { id: "slip-skid", props: { mode: "skid" } },
        bullets: [
          "SLIP: insufficient rudder · nose OUTSIDE · radius ↑ · rate ↓ · ball SAME side as the turn",
          "SKID: excessive rudder · nose INSIDE · radius ↓ · rate ↑ · ball OPPOSITE side",
          "Correction for either: step on the ball",
        ],
      },
      {
        kind: "compare",
        headline: "Which one is dangerous",
        columns: ["Slip", "Skid"],
        rows: [
          { label: "Rudder", a: "Insufficient / opposite", b: "Excessive" },
          { label: "Nose", a: "Outside the turn", b: "Inside the turn" },
          { label: "Turn radius / rate", a: "Radius ↑, rate ↓", b: "Radius ↓, rate ↑" },
          { label: "If it stalls", a: "Rolls toward wings level", b: "Rolls INVERTED" },
          { label: "Useful for", a: "Crosswind landings, extra descent rate", b: "Nothing — avoid it" },
        ],
      },
      {
        kind: "manipulate",
        headline: "Four left-turning tendencies",
        widget: "PropEffectsLab",
        line: "Torque, P-factor, slipstream swirl, gyroscopic precession. All want right rudder at high power and low speed.",
      },
      {
        kind: "chain",
        headline: "P-factor at high AOA",
        nodes: [
          { label: "High power, low airspeed → high AOA", emphasis: true },
          { label: "Relative wind is below the thrust line" },
          { label: "Down-going RIGHT blade meets a larger angle" },
          { label: "Right side produces more thrust" },
          { label: "Nose yaws LEFT — apply right rudder", emphasis: true },
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Slip: insufficient rudder, nose outside, ball same side, radius ↑, rate ↓.",
          "Skid: excessive rudder, nose inside, ball opposite, radius ↓, rate ↑.",
          "P-factor and slipstream swirl are both worst at HIGH power and LOW airspeed, and both need RIGHT rudder.",
          "Gyroscopic precession acts 90° later in the direction of rotation.",
        ],
      },
      { kind: "question", questionId: "q-u6-001" },
      { kind: "question", questionId: "q-u6-002" },
      { kind: "question", questionId: "q-u6-003" },
      { kind: "question", questionId: "q-u6-005" },
      { kind: "question", questionId: "q-u6-006" },
    ],
    questionIds: [
      "q-u6-001", "q-u6-002", "q-u6-003", "q-u6-004", "q-u6-005",
      "q-u6-006", "q-u6-007", "q-u6-008",
    ],
    memorize: [
      "Slip: ball same side, nose outside. Skid: ball opposite, nose inside.",
      "Skidded-turn stall rolls inverted",
      "P-factor and swirl: high power, low speed, right rudder",
    ],
    sourceReferences: [TG("Performance and Maneuvering", ["2.152", "2.161"])],
  },

  {
    id: "l27-spins",
    unit: "u6",
    index: 29,
    title: "Spins",
    subtitle: "Stall plus yaw, and how to undo it",
    estimatedMinutes: 8,
    mapIcon: "spin",
    enablingObjectives: [
      "3.19", "3.20", "3.21", "3.22", "3.23", "3.24", "3.25", "3.26",
      "3.27", "3.28", "3.29",
    ],
    conceptIds: [
      "c-spin-definition",
      "c-spin-wings",
      "c-spin-recovery",
      "c-spin-factors",
      "c-empennage-spin",
    ],
    masteryThreshold: 0.85,
    screens: [
      {
        kind: "hook",
        headline: "Two ingredients. Remove either and there is no spin.",
        line: "The aircraft must be stalled, and yaw must be present. That is the entire recipe.",
      },
      {
        kind: "model",
        headline: "Both wings stalled — one more than the other",
        diagram: { id: "spin-wings", props: { yaw: 1 } },
        bullets: [
          "Down-going (inside) wing sees a roll relative wind from BELOW → higher AOA → more stalled",
          "Higher AOA past the stall → LOWER C_L and HIGHER C_D",
          "Lift differential sustains the ROLL; drag differential sustains the YAW",
        ],
      },
      {
        kind: "manipulate",
        headline: "Spin Lab",
        widget: "SpinLabMini",
        line: "Set AOA past the stall, then introduce yaw. Watch the two wings diverge and autorotation begin.",
      },
      {
        kind: "chain",
        headline: "T-6B spin recovery",
        nodes: [
          { label: "Gear, flaps, speed brake — retracted", emphasis: true },
          { label: "PCL — IDLE" },
          { label: "Rudder — FULL OPPOSITE to turn needle" },
          { label: "Stick — forward of neutral, ailerons neutral" },
          { label: "Recover smoothly once rotation stops", emphasis: true },
        ],
        footnote:
          "The turn needle is the only reliable indicator of spin direction. The balance ball tells you nothing.",
      },
      {
        kind: "compare",
        headline: "Two ways to make it worse",
        columns: ["Progressive spin", "Aggravated spin"],
        rows: [
          {
            label: "Caused by",
            a: "Full opposite rudder while holding full aft stick",
            b: "Pro-spin rudder held while moving the stick forward",
          },
          {
            label: "Result",
            a: "Nose pitches steeply down, rotation SNAPS into reverse",
            b: "≈70° nose down, ≈280°/sec rotation",
          },
          { label: "Recovery", a: "Standard procedure", b: "Standard procedure" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Spin = stall + yaw. Both required.",
          "Down-going wing: AOA ↑, C_L ↓, drag ↑ — more stalled.",
          "Rudder is the principal anti-spin control. Ailerons neutral.",
          "Full aft stick = flattest, slowest (unaccelerated). Anything else accelerates the spin.",
          "T-6B right spin: nose lower, faster, more oscillatory. Left spin: flatter and smoother.",
        ],
        mnemonic: "Clean · Idle · Opposite rudder · Stick forward · Recover",
      },
      { kind: "question", questionId: "q-u6-009" },
      { kind: "question", questionId: "q-u6-011" },
      { kind: "question", questionId: "cc-u6-012" },
      { kind: "question", questionId: "cc-u6-014" },
      { kind: "question", questionId: "q-u6-015" },
      { kind: "question", questionId: "q-u6-017" },
    ],
    questionIds: [
      "q-u6-009", "q-u6-010", "q-u6-011", "cc-u6-012", "q-u6-013",
      "cc-u6-014", "q-u6-015", "q-u6-016", "q-u6-017", "q-u6-018",
      "q-u6-019", "q-u6-020", "q-u6-021",
      "q-db-037", "q-db-038", "q-db-039",
    ],
    memorize: [
      "Spin = stall + yaw",
      "Down-going wing is more stalled: higher AOA, lower CL, more drag",
      "Turn needle for direction. Ignore the ball.",
    ],
    sourceReferences: [TG("Spins", ["3.19", "3.21", "3.24", "3.27"])],
    explainerIds: ["x-why-spins-happen"],
    labIds: ["lab-spin"],
  },

  {
    id: "l28-stability",
    unit: "u6",
    index: 30,
    title: "Stability & Dynamic Modes",
    subtitle: "Static, dynamic, and what each surface contributes",
    estimatedMinutes: 8,
    mapIcon: "stability",
    enablingObjectives: [
      "2.169", "2.170", "2.171", "2.172", "2.175", "2.176", "2.177", "2.178",
      "2.179", "2.180", "2.181", "2.182", "2.183", "2.184", "2.185",
    ],
    conceptIds: [
      "c-static-stability",
      "c-dynamic-stability",
      "c-stability-contributors",
      "c-dynamic-modes",
    ],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "Static is the first instant. Dynamic is everything after.",
        line: "A ball in a bowl tells you both — and static instability guarantees dynamic instability.",
      },
      {
        kind: "model",
        headline: "The ball and the bowl",
        diagram: { id: "stability-ball", props: { kind: "positive-static" } },
        bullets: [
          "Positive static: initial tendency BACK toward equilibrium",
          "Neutral static: accepts the new position",
          "Negative static: initial tendency further AWAY",
        ],
      },
      {
        kind: "compare",
        headline: "Static + dynamic combinations",
        columns: ["Dynamic stability", "Motion"],
        rows: [
          { label: "Positive static + positive dynamic", a: "Returns to equilibrium", b: "Damped oscillation" },
          { label: "Positive static + neutral dynamic", a: "Oscillates forever", b: "Undamped oscillation" },
          { label: "Positive static + negative dynamic", a: "Grows away", b: "Divergent oscillation" },
        ],
      },
      {
        kind: "manipulate",
        headline: "Which component does what",
        widget: "StabilityContributors",
        line: "Toggle each surface and see its contribution to longitudinal, directional and lateral stability.",
      },
      {
        kind: "chain",
        headline: "The two cross-coupled failure modes",
        nodes: [
          { label: "Strong directional + weak lateral", emphasis: true },
          { label: "→ SPIRAL DIVERGENCE (tight descending spiral)" },
          { label: "Strong lateral + weak directional", emphasis: true },
          { label: "→ DUTCH ROLL (tail wagging)" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Longitudinal: horizontal stabiliser is the greatest positive contributor.",
          "Directional: vertical stabiliser is the greatest positive contributor (weathervane).",
          "Lateral: dihedral wings are the greatest positive contributor; anhedral the greatest negative.",
          "AC behind the CG = stabilising. Aft CG = less stable; the neutral point is the aft limit.",
          "Adverse yaw: extra induced drag on the up-going wing yaws you away from the roll.",
        ],
      },
      { kind: "question", questionId: "q-u6-022" },
      { kind: "question", questionId: "q-u6-023" },
      { kind: "question", questionId: "q-u6-025" },
      { kind: "question", questionId: "q-u6-026" },
      { kind: "question", questionId: "q-u6-024" },
    ],
    questionIds: [
      "q-u6-022", "q-u6-023", "q-u6-024", "q-u6-025", "q-u6-026", "q-u6-027",
      "q-cov-009", "q-cov-010",
    ],
    memorize: [
      "Vertical stabiliser → directional stability",
      "Horizontal stabiliser → longitudinal stability",
      "Dihedral → lateral stability",
      "Dutch roll: lateral strong, directional weak",
    ],
    sourceReferences: [TG("Performance and Maneuvering", ["2.169", "2.177", "2.181", "2.183"])],
  },

  {
    id: "l28b-maneuverability",
    unit: "u6",
    index: 31,
    title: "Maneuverability",
    subtitle: "The other half of the stability trade",
    estimatedMinutes: 5,
    mapIcon: "turn",
    enablingObjectives: ["2.173", "2.174"],
    conceptIds: ["c-increasing-maneuverability"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "Stability and maneuverability are opposites, and the designer has to choose",
        line: "A transport wants one. A fighter wants the other. Neither is a flaw.",
      },
      {
        kind: "compare",
        headline: "The trade",
        columns: ["Stable airplane", "Maneuverable airplane"],
        rows: [
          { label: "Leaving equilibrium", a: "Resists it", b: "Departs easily" },
          { label: "Returning to equilibrium", a: "Tends to return", b: "Less likely to return" },
          { label: "Pilot workload", a: "Low", b: "Higher — needs more attention" },
          { label: "Suits", a: "Long range and easy landings", b: "High performance turning" },
        ],
      },
      {
        kind: "chain",
        headline: "Two ways to buy maneuverability",
        nodes: [
          { label: "Weaken the airplane's stability", trend: "down" },
          { label: "Or enlarge the control surfaces", trend: "up" },
          { label: "Larger surfaces generate larger moments", trend: "up", emphasis: true },
        ],
        footnote:
          "Both work. The first costs pilot attention; the second costs weight and drag.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Maneuverability is the ease of LEAVING equilibrium.",
          "Two ways to increase it: weaker stability, or larger control surfaces.",
          "The mission dictates the compromise.",
        ],
      },
      { kind: "question", questionId: "q-db-023" },
      { kind: "question", questionId: "q-db-024" },
      { kind: "question", questionId: "q-u6-021" },
    ],
    questionIds: ["q-db-023", "q-db-024", "q-u6-021"],
    memorize: [
      "Stability and maneuverability are opposites",
      "Weaker stability OR larger control surfaces",
    ],
    sourceReferences: [TG("Performance and Maneuvering", ["2.173", "2.174"])],
  },

  {
    id: "l29-wake-turbulence",
    unit: "u6",
    index: 32,
    title: "Wake Turbulence",
    subtitle: "Heavy, slow, clean — and how to stay out of it",
    estimatedMinutes: 7,
    mapIcon: "wake",
    enablingObjectives: ["2.187", "2.188", "2.189", "2.190", "2.191", "2.192"],
    conceptIds: [
      "c-wake-turbulence",
      "c-wake-strength",
      "c-wake-behavior",
      "c-wake-avoidance",
    ],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Every aircraft producing lift is making one",
        line: "Not just heavies. Not just with flaps out. From rotation until the nosewheel touches down.",
      },
      {
        kind: "model",
        headline: "Where the vortices go",
        diagram: { id: "wake-vortex", props: { time: 0.5 } },
        bullets: [
          "Sink at 400–500 fpm",
          "Level off about 900 ft below the generating flight path",
          "On the ground, move laterally outward at about 5 knots",
          "Core diameter ≈ one quarter of the generating wingspan",
        ],
      },
      {
        kind: "manipulate",
        headline: "Wake Lab",
        widget: "WakeLabMini",
        line: "Change the generator's weight, speed and configuration. Find the worst case, then fly the avoidance profile.",
      },
      {
        kind: "chain",
        headline: "Strongest vortex",
        nodes: [
          { label: "HEAVY — more lift needed", trend: "up", emphasis: true },
          { label: "SLOW — high AOA, strong vortices", trend: "up" },
          { label: "CLEAN — no flaps to unload the tip", trend: "up" },
          { label: "Maximum vortex strength", trend: "up", emphasis: true },
        ],
        footnote: "The weakest case is the exact opposite: light, fast and dirty.",
      },
      {
        kind: "compare",
        headline: "The four avoidance geometries",
        columns: ["Situation", "What you do"],
        rows: [
          {
            label: "Landing behind a LANDING aircraft",
            a: "Stay at or above its approach path",
            b: "Touch down BEYOND its touchdown point",
          },
          {
            label: "Landing behind a DEPARTING aircraft",
            a: "Stay above its flight path",
            b: "Touch down BEFORE its rotation point",
          },
          {
            label: "Departing behind a DEPARTING aircraft",
            a: "Climb above its flight path",
            b: "Rotate BEFORE its rotation point",
          },
          {
            label: "Departing behind a LANDED aircraft",
            a: "Climb above its flight path",
            b: "Rotate BEFORE its nosewheel touchdown point",
          },
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Strongest wake: HEAVY, SLOW, CLEAN.",
          "Hazards: induced roll and the induced flow field (downwash to 1,500 fpm).",
          "T-6B spacing behind a heavy: 2 minutes takeoff, 3 minutes landing.",
          "Remain ABOVE their flight path. Rotate before, land beyond.",
          "Caution: 4–6 kt crosswind, and parallel runways under 2,500 ft apart.",
        ],
      },
      { kind: "question", questionId: "q-u6-028" },
      { kind: "question", questionId: "q-u6-029" },
      { kind: "question", questionId: "q-u6-032" },
      { kind: "question", questionId: "q-u6-033" },
      { kind: "question", questionId: "q-u6-030" },
      { kind: "question", questionId: "q-u6-031" },
    ],
    questionIds: [
      "q-u6-028", "q-u6-029", "q-u6-030", "q-u6-031", "q-u6-032",
      "q-u6-033", "q-u6-034", "q-u6-035", "q-u6-036",
    ],
    memorize: [
      "Strongest wake: heavy, slow, clean",
      "Sink 400–500 fpm, level off 900 ft below",
      "2 minutes takeoff, 3 minutes landing behind a heavy",
    ],
    sourceReferences: [TG("Wake Turbulence and Wind Shear", ["2.187", "2.188", "2.190"])],
    explainerIds: ["x-wake-turbulence"],
    labIds: ["lab-wake"],
  },

  {
    id: "l30-wind-shear",
    unit: "u6",
    index: 33,
    title: "Wind Shear",
    subtitle: "Increasing, decreasing, and the microburst trap",
    estimatedMinutes: 7,
    mapIcon: "shear",
    enablingObjectives: ["2.193", "2.194", "2.195", "2.196", "2.197", "2.198"],
    conceptIds: [
      "c-wind-shear",
      "c-wind-shear-performance",
      "c-wind-shear-procedures",
    ],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "A microburst gives you good news first",
        line: "The performance INCREASE comes first. The instinctive nose-down correction is what kills you when the decrease arrives.",
      },
      {
        kind: "model",
        headline: "Shear changes indicated airspeed instantly",
        diagram: { id: "wind-shear", props: { type: "decreasing" } },
        bullets: [
          "IAS is a direct readout of dynamic pressure",
          "Increasing headwind or decreasing tailwind → IAS ↑ → lift ↑ → above glidepath",
          "Decreasing headwind or increasing tailwind → IAS ↓ → lift ↓ → below glidepath",
          "Once stabilised in the new air mass, only groundspeed has changed",
        ],
      },
      {
        kind: "manipulate",
        headline: "Wind Shear Lab",
        widget: "WindShearLab",
        line: "Fly an approach through each shear type. Watch IAS, lift and glidepath — and the power setting you end up needing.",
      },
      {
        kind: "chain",
        headline: "The microburst sequence",
        nodes: [
          { label: "Enter the outflow: strong HEADWIND", trend: "up", emphasis: true },
          { label: "IAS and lift increase — aircraft balloons" },
          { label: "Pilot instinctively pushes nose down" },
          { label: "Cross the core: strong TAILWIND", trend: "down" },
          { label: "IAS and lift collapse with the nose already low", trend: "down", emphasis: true },
        ],
        footnote:
          "Downdrafts over 700 fpm have been measured, and shears from 50 to 200 knots. Avoid at all cost.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Lose 20 knots of headwind → lose 20 knots of IAS → lose lift.",
          "Tailwind to headwind: ADD both numbers for the total swing.",
          "Microburst: performance increase FIRST, then the decrease.",
          "T-6B procedure: flaps TAKEOFF, add up to 10 knots, establish by 1,000 ft AGL, expect to land long.",
          "Best technique is avoidance — delay, divert, or go around.",
        ],
      },
      { kind: "question", questionId: "q-u6-038" },
      { kind: "question", questionId: "q-u6-039" },
      { kind: "question", questionId: "q-u6-040" },
      { kind: "question", questionId: "q-u6-041" },
      { kind: "question", questionId: "cc-u6-042" },
    ],
    questionIds: [
      "q-u6-037", "q-u6-038", "q-u6-039", "q-u6-040", "q-u6-041",
      "cc-u6-042", "q-u6-043",
    ],
    memorize: [
      "Decreasing performance shear on landing is the most hazardous case",
      "Microburst: headwind first, then tailwind",
      "Flaps TAKEOFF, +10 knots, expect to land long",
    ],
    sourceReferences: [TG("Wake Turbulence and Wind Shear", ["2.193", "2.196", "2.197"])],
    explainerIds: ["x-wind-shear"],
  },
];
