import type { Lesson, SourceReference } from "@/lib/types";

const TG = (chapter: string, eo: string[]): SourceReference => ({
  document: "Aerodynamics Trainee Guide",
  chapter,
  eo,
});

/** Lessons 1–13: Units 1, 2 and 3. */
export const LESSONS_A: Lesson[] = [
  /* ================================================================ */
  /* UNIT 1 — LEARN THE LANGUAGE                                       */
  /* ================================================================ */
  {
    id: "l01-language-of-motion",
    unit: "u1",
    index: 1,
    title: "The Language of Motion",
    subtitle: "Vectors, moments, energy and Newton",
    estimatedMinutes: 6,
    mapIcon: "vector",
    enablingObjectives: [
      "2.1", "2.2", "2.3", "2.4", "2.5", "2.6", "2.7", "2.8", "2.9", "2.10",
      "2.11", "2.12", "2.13", "2.14", "2.15", "2.16", "2.17", "2.18",
    ],
    conceptIds: [
      "c-scalar-vector",
      "c-density",
      "c-moment",
      "c-work-power-energy",
      "c-newton-laws",
      "c-equilibrium",
      "c-trimmed",
    ],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "Six words the exam will try to swap on you",
        line: "Moment, work, power, force, equilibrium, trimmed. Get them exact once and a dozen questions become free.",
      },
      {
        kind: "model",
        headline: "A moment is force × PERPENDICULAR distance",
        diagram: { id: "moment-arm", props: { arm: 0.7 } },
        line: "Drag the force along the arm. The moment grows with distance, not with the force alone.",
        bullets: [
          "M = F × d",
          "d is the moment arm — perpendicular to the force",
          "Work is force × displacement. Power is work ÷ time.",
        ],
      },
      {
        kind: "manipulate",
        headline: "Move the force. Watch the moment.",
        widget: "MomentArmSlider",
        line: "Same force, different arm. This is why a small trim tab far from the hinge can balance a large elevator force.",
      },
      {
        kind: "compare",
        headline: "Equilibrium vs trimmed",
        line: "The single most swapped pair in Unit 1.",
        columns: ["Equilibrium flight", "Trimmed flight"],
        rows: [
          { label: "Forces sum to zero", a: "Yes — required", b: "Not necessarily" },
          { label: "Moments sum to zero", a: "Yes — required", b: "Yes — required" },
          { label: "Acceleration", a: "None, linear or angular", b: "No angular acceleration" },
          {
            label: "Example",
            a: "Steady climb at constant airspeed",
            b: "Constant-bank, constant-rate turn",
          },
        ],
      },
      {
        kind: "chain",
        headline: "The containment relationship",
        nodes: [
          { label: "Equilibrium flight", emphasis: true },
          { label: "always implies", trend: "none" },
          { label: "Trimmed flight", emphasis: true },
        ],
        footnote: "But trimmed flight does NOT imply equilibrium. The arrow only runs one way.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Moment = force × perpendicular distance from the fulcrum.",
          "Work = force × displacement. Power = work ÷ time.",
          "Equilibrium = forces AND moments zero. Trimmed = moments only.",
          "Density = mass ÷ volume.",
        ],
        formula: "M = F \\times d \\quad\\quad \\rho = \\frac{m}{V}",
      },
      { kind: "question", questionId: "q-u1-001" },
      { kind: "question", questionId: "q-u1-005" },
      { kind: "question", questionId: "trap-u1-007" },
      { kind: "question", questionId: "q-u1-003" },
      { kind: "question", questionId: "q-u1-004" },
    ],
    questionIds: [
      "q-u1-001", "q-u1-005", "trap-u1-007", "q-u1-003", "q-u1-004",
      "q-u1-002", "trap-u1-006", "q-u1-047", "q-cov-001",
    ],
    memorize: [
      "Moment = force × perpendicular distance from a fulcrum",
      "Equilibrium: forces AND moments = 0",
      "Trimmed: moments = 0 only",
    ],
    sourceReferences: [TG("Basic Theory", ["2.1", "2.8", "2.15", "2.16", "2.18"])],
    explainerIds: ["x-equilibrium-vs-trimmed"],
  },

  {
    id: "l02-atmosphere",
    unit: "u1",
    index: 2,
    title: "The Atmosphere",
    subtitle: "Pressure, temperature, density, humidity",
    estimatedMinutes: 6,
    mapIcon: "atmosphere",
    enablingObjectives: [
      "2.19", "2.20", "2.21", "2.22", "2.23", "2.24", "2.25", "2.26",
      "2.27", "2.28", "2.29",
    ],
    conceptIds: [
      "c-static-pressure",
      "c-density",
      "c-temperature-lapse",
      "c-humidity-density",
      "c-viscosity",
      "c-speed-of-sound",
      "c-standard-atmosphere",
    ],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "Everything downstream starts with ρ",
        line: "Lift, drag, thrust, takeoff distance and stall speed all contain air density. Learn what moves it.",
      },
      {
        kind: "model",
        headline: "Climb and all three fall together",
        diagram: { id: "atmosphere-column", props: { altitude: 0 } },
        bullets: [
          "Pressure ↓ — less air column overhead (≈1.0 in-Hg per 1,000 ft low down)",
          "Temperature ↓ — 2 °C (3.57 °F) per 1,000 ft to ~36,000 ft",
          "Density ↓ — particles spread further apart",
        ],
      },
      {
        kind: "manipulate",
        headline: "Fly the column",
        widget: "AtmosphereSlider",
        line: "Drag altitude and watch pressure, temperature and density move together. Note where the isothermal layer begins.",
      },
      {
        kind: "chain",
        headline: "Humidity works backwards from intuition",
        nodes: [
          { label: "Humidity", trend: "up", emphasis: true },
          { label: "Water molecules displace air molecules", trend: "none" },
          { label: "Water is lighter than air", trend: "none" },
          { label: "Air density", trend: "down", emphasis: true },
        ],
        footnote: "Humid air is LESS dense. This is the reverse of what most people guess.",
      },
      {
        kind: "compare",
        headline: "Two properties that behave unusually",
        columns: ["Viscosity", "Speed of sound"],
        rows: [
          {
            label: "Depends on",
            a: "Temperature",
            b: "Temperature — and nothing else",
          },
          {
            label: "Temperature ↑",
            a: "Air viscosity INCREASES",
            b: "Speed of sound INCREASES",
          },
          {
            label: "The trap",
            a: "Liquids get thinner when hot. Air does not.",
            b: "Not pressure. Not density. Temperature only.",
          },
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold — standard atmosphere at sea level",
        statements: [
          "29.92 in-Hg (1013.25 mbar)",
          "59 °F / 15 °C",
          "ρ₀ = 0.0024 slugs/ft³",
          "Local speed of sound 661.7 knots",
          "Lapse rate 2 °C (3.57 °F) per 1,000 ft to 36,000 ft; then −56.5 °C isothermal",
        ],
      },
      { kind: "question", questionId: "q-u1-008" },
      { kind: "question", questionId: "q-u1-009" },
      { kind: "question", questionId: "q-u1-010" },
      { kind: "question", questionId: "q-u1-012" },
      { kind: "question", questionId: "q-u1-046" },
    ],
    questionIds: [
      "q-u1-008", "q-u1-009", "q-u1-010", "q-u1-012", "q-u1-046", "q-u1-011",
    ],
    memorize: [
      "Altitude ↑ → pressure, temperature and density all ↓",
      "Humidity ↑ → density ↓",
      "Air temperature ↑ → viscosity ↑ (opposite of liquids)",
      "Speed of sound depends on temperature alone",
    ],
    sourceReferences: [TG("Basic Theory", ["2.19", "2.24", "2.26", "2.28", "2.29"])],
    explainerIds: ["x-why-humid-air-is-thin"],
    labIds: [],
  },

  {
    id: "l03-continuity-bernoulli",
    unit: "u1",
    index: 3,
    title: "Continuity & Bernoulli",
    subtitle: "The two equations behind every airfoil",
    estimatedMinutes: 6,
    mapIcon: "streamtube",
    enablingObjectives: ["2.30", "2.31", "2.32", "2.33", "2.34", "2.35"],
    conceptIds: [
      "c-gas-law",
      "c-steady-airflow",
      "c-continuity",
      "c-bernoulli",
      "c-dynamic-pressure",
    ],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "Two equations produce lift. That is the whole trick.",
        line: "Continuity says squeezing the flow speeds it up. Bernoulli says speeding it up drops its static pressure.",
      },
      {
        kind: "model",
        headline: "A streamtube is a closed system",
        diagram: { id: "streamtube", props: { constriction: 0.55 } },
        bullets: [
          "Steady airflow: static pressure, density, temperature and velocity constant over time",
          "Streamline = the path a particle follows; streamtube = a bundle of them",
          "Mass and total energy cannot leave the tube",
        ],
      },
      {
        kind: "manipulate",
        headline: "Squeeze the tube",
        widget: "StreamtubeSlider",
        line: "Watch area, velocity, dynamic pressure and static pressure. Total pressure never moves.",
      },
      {
        kind: "chain",
        headline: "The mechanism, in four steps",
        nodes: [
          { label: "Cross-sectional area", trend: "down", emphasis: true },
          { label: "Velocity (continuity)", trend: "up" },
          { label: "Dynamic pressure q = ½ρV²", trend: "up" },
          { label: "Static pressure (Bernoulli)", trend: "down", emphasis: true },
        ],
        footnote: "Total pressure H = Pₛ + q stays constant. The two components trade.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "A₁V₁ = A₂V₂ — area and velocity are inverse",
          "H = Pₛ + ½ρV² — total is constant; the parts trade",
          "P = ρRT — with P constant, T and ρ are inverse",
          "Steady airflow constants: pressure, density, temperature, velocity",
        ],
        formula: "A_1V_1 = A_2V_2 \\quad\\quad H = P_S + \\tfrac{1}{2}\\rho V^2 \\quad\\quad P = \\rho R T",
      },
      { kind: "question", questionId: "q-u1-017" },
      { kind: "question", questionId: "sp-u1-018" },
      { kind: "question", questionId: "q-u1-013" },
      { kind: "question", questionId: "q-u1-016" },
      { kind: "question", questionId: "q-u1-020" },
    ],
    questionIds: [
      "q-u1-017", "sp-u1-018", "q-u1-013", "q-u1-016", "q-u1-020", "q-u1-019",
    ],
    memorize: [
      "A₁V₁ = A₂V₂",
      "H = Pₛ + ½ρV²",
      "P = ρRT; at constant P, T and ρ are inverse",
    ],
    sourceReferences: [TG("Basic Theory", ["2.30", "2.31", "2.32", "2.35"])],
    explainerIds: ["x-what-lift-really-is"],
  },

  {
    id: "l04-airspeed-ladder",
    unit: "u1",
    index: 4,
    title: "Altitude & the Airspeed Ladder",
    subtitle: "Pitot-static, ICE-TG, density altitude",
    estimatedMinutes: 7,
    mapIcon: "pitot",
    enablingObjectives: [
      "2.36", "2.37", "2.38", "2.39", "2.40", "2.41", "2.42", "2.43",
      "2.44", "2.45", "2.46", "2.47",
    ],
    conceptIds: [
      "c-altitude-types",
      "c-density-altitude",
      "c-pitot-static",
      "c-icetg",
      "c-tas-altitude",
    ],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "The cockpit cannot measure your speed",
        line: "It measures a pressure difference and infers a speed. Every airspeed rung after that is a correction.",
      },
      {
        kind: "model",
        headline: "Pitot total, static ambient, gauge the difference",
        diagram: { id: "pitot-static" },
        bullets: [
          "Pitot tube: open to the airflow, flow stops inside → total pressure H",
          "Static port: flush and parallel to the flow → static pressure Pₛ",
          "Gauge: H − Pₛ = q, which the ASI displays as indicated airspeed",
        ],
      },
      {
        kind: "manipulate",
        headline: "Climb the ladder",
        widget: "IcetgLadderWidget",
        line: "Set altitude and wind, then watch each rung. Only two corrections actually move at low speed.",
      },
      {
        kind: "chain",
        headline: "ICE-TG",
        nodes: [
          { label: "Indicated (IAS)", emphasis: true },
          { label: "Calibrated — instrument/position error" },
          { label: "Equivalent — compressibility" },
          { label: "True — density" },
          { label: "Ground — wind", emphasis: true },
        ],
        footnote: "TAS = EAS × √(ρ₀/ρ). Not CAS corrected for density — EAS.",
      },
      {
        kind: "chain",
        headline: "Why TAS runs away from you in a climb",
        nodes: [
          { label: "Altitude", trend: "up", emphasis: true },
          { label: "Density", trend: "down" },
          { label: "TAS needed for the same IAS", trend: "up", emphasis: true },
        ],
        footnote: "Rule of thumb: about +3 knots of TAS per 1,000 ft at constant IAS.",
      },
      {
        kind: "compare",
        headline: "Four altitudes worth telling apart",
        columns: ["Definition", "Used for"],
        rows: [
          { label: "True altitude", a: "Height above mean sea level", b: "Terrain and obstacle clearance" },
          { label: "Absolute altitude", a: "Height above the terrain below (AGL)", b: "Low-level flight" },
          { label: "Pressure altitude", a: "Height above the 29.92 datum plane", b: "Flight levels, performance charts" },
          {
            label: "Density altitude",
            a: "Pressure altitude corrected for temp and humidity",
            b: "Predicting performance — NOT a height reference",
          },
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "ICE-TG: Indicated → Calibrated → Equivalent → True → Ground",
          "Above sea level, IAS is less than TAS",
          "High density altitude means LOW air density",
        ],
        formula: "TAS = EAS\\sqrt{\\frac{\\rho_0}{\\rho}}",
        mnemonic: "ICE-TG",
      },
      { kind: "question", questionId: "q-u1-023" },
      { kind: "question", questionId: "cc-u1-024" },
      { kind: "question", questionId: "q-u1-021" },
      { kind: "question", questionId: "q-u1-025" },
      { kind: "question", questionId: "cs-u1-027" },
      { kind: "question", questionId: "q-u1-015" },
    ],
    questionIds: [
      "q-u1-023", "cc-u1-024", "q-u1-021", "q-u1-025", "cs-u1-027",
      "q-u1-015", "tap-u1-022", "q-u1-026", "q-u1-045", "cc-u1-014",
    ],
    memorize: [
      "ICE-TG: IAS → CAS → EAS → TAS → GS",
      "TAS = EAS √(ρ₀/ρ)",
      "High DA = low density = worse performance",
    ],
    sourceReferences: [TG("Basic Theory", ["2.40", "2.41", "2.45", "2.47"])],
    explainerIds: ["x-icetg", "x-why-tas-changes-with-altitude"],
  },

  {
    id: "l05-wing-geometry",
    unit: "u1",
    index: 5,
    title: "Airfoil & Wing Geometry",
    subtitle: "Chord, camber, span, and the two airflows",
    estimatedMinutes: 6,
    mapIcon: "airfoil",
    enablingObjectives: [
      "2.48", "2.49", "2.50", "2.51", "2.52", "2.54", "2.55", "2.56", "2.57",
      "2.58", "2.59", "2.60", "2.61", "2.62", "2.63", "2.64", "2.70", "2.71",
      "2.72", "2.73", "2.74", "2.75", "2.76",
    ],
    conceptIds: [
      "c-chordline-chord",
      "c-mean-camber-line",
      "c-camber-types",
      "c-wing-planform",
      "c-chordwise-spanwise",
    ],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "Two lines. Everything else is measured from them.",
        line: "The chord line joins the edges. The mean camber line splits the surfaces. Camber is the gap between them.",
      },
      {
        kind: "model",
        headline: "Airfoil anatomy",
        diagram: { id: "airfoil-geometry", props: { camber: 0.06, labels: true } },
        bullets: [
          "Chord line: infinitely long, through leading and trailing EDGES",
          "Mean camber line: halfway between upper and lower SURFACES",
          "Camber: max distance between them, measured perpendicular to the chord line",
        ],
      },
      {
        kind: "manipulate",
        headline: "Bend the camber",
        widget: "CamberSlider",
        line: "Positive, symmetric, negative. Watch what each one does at zero angle of attack.",
      },
      {
        kind: "compare",
        headline: "Camber decides what happens at 0° AOA",
        columns: ["MCL position", "Lift at 0° AOA"],
        rows: [
          { label: "Positive camber", a: "Above the chord line", b: "Positive lift" },
          { label: "Symmetric", a: "Same as the chord line", b: "ZERO lift" },
          { label: "Negative camber", a: "Below the chord line", b: "Negative lift" },
        ],
      },
      {
        kind: "model",
        headline: "Only one airflow makes lift",
        diagram: { id: "chordwise-spanwise" },
        bullets: [
          "Chordwise: at RIGHT ANGLES to the leading edge — accelerates over the wing, makes lift",
          "Spanwise: PARALLEL to the leading edge, root to tip — makes no lift",
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Chord line: through the edges. Mean camber line: between the surfaces.",
          "Symmetric airfoil = zero lift at zero AOA.",
          "Chordwise ⟂ LE and makes lift. Spanwise ∥ LE and does not.",
        ],
        formula: "S = b\\,c \\quad\\quad AR = \\frac{b}{c} \\quad\\quad \\lambda = \\frac{c_T}{c_R}",
      },
      { kind: "question", questionId: "q-u1-028" },
      { kind: "question", questionId: "dl-u1-030" },
      { kind: "question", questionId: "q-u1-031" },
      { kind: "question", questionId: "q-u1-032" },
      { kind: "question", questionId: "q-u1-029" },
    ],
    questionIds: [
      "q-u1-028", "dl-u1-030", "q-u1-031", "q-u1-032", "q-u1-029", "q-u1-033",
      "q-cov-002", "q-cov-003",
    ],
    memorize: [
      "Mean camber line: halfway between UPPER and LOWER SURFACES",
      "Symmetric airfoil produces zero lift at zero AOA",
      "Chordwise flow is the only lift-producing flow",
    ],
    sourceReferences: [TG("Basic Theory", ["2.54", "2.59", "2.61", "2.63", "2.64"])],
  },

  {
    id: "l06-axes-and-aoa",
    unit: "u1",
    index: 6,
    title: "Axes, CG & the AOA Trap",
    subtitle: "Why pitch attitude tells you nothing about AOA",
    estimatedMinutes: 7,
    mapIcon: "axes",
    enablingObjectives: [
      "2.53", "2.65", "2.66", "2.67", "2.68", "2.69", "2.77", "2.78", "2.79",
    ],
    conceptIds: ["c-axes", "c-cg", "c-aerodynamic-center", "c-pitch-vs-aoa"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "The single most-tested confusion in the course",
        line: "Pitch attitude is measured against the horizon. Angle of attack is measured against the relative wind. They are unrelated.",
      },
      {
        kind: "model",
        headline: "Three axes, three motions, three controls",
        diagram: { id: "axes-3d" },
        bullets: [
          "Longitudinal — nose to tail — ROLL — ailerons",
          "Lateral — wingtip to wingtip — PITCH — elevator",
          "Vertical — through the CG — YAW — rudder",
        ],
      },
      {
        kind: "compare",
        headline: "CG vs aerodynamic centre",
        columns: ["Centre of gravity", "Aerodynamic centre"],
        rows: [
          { label: "What acts there", a: "All weight", b: "All aerodynamic force" },
          { label: "Location", a: "Intersection of the three axes", b: "≈25% chord aft of the leading edge" },
          { label: "Moves?", a: "Yes — fuel burn, cargo, stores", b: "No, essentially fixed subsonically" },
        ],
      },
      {
        kind: "manipulate",
        headline: "Hold the nose. Change the flight path.",
        widget: "AoaVsPitchSlider",
        line: "Pitch attitude and flight path angle move independently. AOA is the gap between them.",
      },
      {
        kind: "chain",
        headline: "The four angles, in order",
        nodes: [
          { label: "Pitch attitude — longitudinal axis vs HORIZON" },
          { label: "Flight path — where the CG actually goes" },
          { label: "Relative wind — exactly opposite the flight path" },
          { label: "AOA — chord line vs RELATIVE WIND", emphasis: true },
        ],
        footnote:
          "Angle of incidence is a fixed structural angle: chord line vs longitudinal axis. It never changes in flight.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "AOA: angle between the chord line and the relative wind.",
          "Pitch attitude: angle between the longitudinal axis and the horizon.",
          "Angle of incidence: chord line vs longitudinal axis — fixed by the airframe.",
          "Flight path, relative wind and AOA can never be inferred from pitch attitude.",
        ],
      },
      { kind: "question", questionId: "trap-u1-040" },
      { kind: "question", questionId: "sp-u1-041" },
      { kind: "question", questionId: "q-u1-034" },
      { kind: "question", questionId: "q-u1-039" },
      { kind: "question", questionId: "q-u1-037" },
      { kind: "question", questionId: "tap-u1-042" },
    ],
    questionIds: [
      "trap-u1-040", "sp-u1-041", "q-u1-034", "q-u1-039", "q-u1-037",
      "tap-u1-042", "tap-u1-035", "q-u1-036", "q-u1-038", "q-u1-043", "q-u1-044",
    ],
    memorize: [
      "AOA = chord line vs relative wind",
      "Pitch attitude = longitudinal axis vs horizon",
      "Lateral axis → pitch → elevator",
      "AC ≈ 25% chord aft of the leading edge",
    ],
    sourceReferences: [TG("Basic Theory", ["2.53", "2.65", "2.68", "2.77", "2.78"])],
    explainerIds: ["x-aoa-in-90-seconds"],
    labIds: ["lab-aoa"],
  },

  /* ================================================================ */
  /* UNIT 2 — UNDERSTAND THE WING                                      */
  /* ================================================================ */
  {
    id: "l07-aerodynamic-force",
    unit: "u2",
    index: 7,
    title: "Aerodynamic Force",
    subtitle: "Lift and drag are components, not causes",
    estimatedMinutes: 5,
    mapIcon: "vectors",
    enablingObjectives: ["2.80", "2.81", "2.83", "2.86"],
    conceptIds: ["c-aero-force", "c-lift-def", "c-drag-def", "c-equilibrium"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "Air can only do two things to a wing",
        line: "Push on it (pressure) and rub along it (shear stress). Integrate both over the surface and you get one vector.",
      },
      {
        kind: "model",
        headline: "One force, resolved two ways",
        diagram: { id: "aero-force-components", props: { aoa: 8 } },
        bullets: [
          "Aerodynamic force = the net result of pressure + shear distribution",
          "Lift = the component PERPENDICULAR to the relative wind",
          "Drag = the component PARALLEL to and in the SAME DIRECTION as the relative wind",
        ],
      },
      {
        kind: "manipulate",
        headline: "Rotate the relative wind",
        widget: "AeroForceSlider",
        line: "Lift and drag rotate with it. Lift never cares where the horizon is.",
      },
      {
        kind: "compare",
        headline: "Which of the four forces are aerodynamic?",
        columns: ["Force", "Aerodynamic?"],
        rows: [
          { label: "Lift", a: "Component of AF, ⟂ relative wind", b: "YES" },
          { label: "Drag", a: "Component of AF, ∥ relative wind", b: "YES" },
          { label: "Weight", a: "Gravity acting on mass", b: "No" },
          { label: "Thrust", a: "Engine or engine/prop output", b: "No" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Aerodynamic force = result of pressure and friction distribution over an airfoil.",
          "Lift ⟂ relative wind. Drag ∥ relative wind, same direction.",
          "Only lift and drag are aerodynamic forces.",
        ],
        formula: "AF = qSC_F \\quad\\quad L = qSC_L \\quad\\quad D = qSC_D",
      },
      { kind: "question", questionId: "q-u2-001" },
      { kind: "question", questionId: "q-u2-002" },
      { kind: "question", questionId: "q-u2-003" },
      { kind: "question", questionId: "dl-u2-005" },
      { kind: "question", questionId: "trap-u2-022" },
    ],
    questionIds: [
      "q-u2-001", "q-u2-002", "q-u2-003", "dl-u2-005", "trap-u2-022", "q-u2-004",
    ],
    memorize: [
      "Lift is perpendicular to the relative wind",
      "Drag is parallel and in the same direction as the relative wind",
      "Only lift and drag are aerodynamic forces",
    ],
    sourceReferences: [TG("Lift Production and Drag", ["2.80", "2.83", "2.86"])],
  },

  {
    id: "l08-pressure-distribution",
    unit: "u2",
    index: 8,
    title: "How Lift Is Actually Made",
    subtitle: "Pressure distribution, not equal transit time",
    estimatedMinutes: 6,
    mapIcon: "pressure",
    enablingObjectives: ["2.82"],
    conceptIds: ["c-pressure-distribution", "c-bernoulli", "c-continuity"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "The story you were told at school is wrong",
        line: "Air does not 'have to meet up' at the trailing edge. The trainee guide calls that out explicitly as a misconception.",
      },
      {
        kind: "model",
        headline: "Streamtube A is squeezed. Streamtube B is not.",
        diagram: { id: "airfoil-pressure", props: { aoa: 6, camber: 0.06 } },
        bullets: [
          "Upper streamtube sees the airfoil as an obstruction and narrows",
          "Continuity: narrower means faster",
          "Bernoulli: faster means lower static pressure",
          "The differential pushes the wing toward the LOW pressure — upward",
        ],
      },
      {
        kind: "manipulate",
        headline: "Change AOA and watch the arrows",
        widget: "PressureDistributionSlider",
        line: "Arrow length is pressure difference from ambient. Watch the suction peak grow and move forward.",
      },
      {
        kind: "chain",
        headline: "The lift chain",
        nodes: [
          { label: "Streamtube area over the top", trend: "down", emphasis: true },
          { label: "Velocity", trend: "up" },
          { label: "Static pressure above", trend: "down" },
          { label: "Pressure differential", trend: "up" },
          { label: "Lift", trend: "up", emphasis: true },
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Max velocity occurs at maximum airfoil thickness, where static pressure is minimum.",
          "Flow decelerates to nearly zero at the trailing edge stagnation point.",
          "Lift acts toward the LOWER static pressure.",
        ],
      },
      { kind: "question", questionId: "cc-u2-006" },
      { kind: "question", questionId: "trap-u2-023" },
      { kind: "question", questionId: "q-u2-007" },
      { kind: "question", questionId: "sp-u2-008" },
    ],
    questionIds: ["cc-u2-006", "trap-u2-023", "q-u2-007", "sp-u2-008"],
    memorize: [
      "Continuity then Bernoulli — that is the mechanism",
      "Max velocity = min static pressure = max thickness",
    ],
    sourceReferences: [TG("Lift Production and Drag", ["2.82"])],
    explainerIds: ["x-what-lift-really-is"],
  },

  {
    id: "l09-lift-equation",
    unit: "u2",
    index: 9,
    title: "The Lift Equation",
    subtitle: "L = ½ρV²SC_L and what you can actually change",
    estimatedMinutes: 7,
    mapIcon: "equation",
    enablingObjectives: ["2.84", "2.85"],
    conceptIds: [
      "c-lift-equation",
      "c-coefficient-of-lift",
      "c-v-aoa-inverse",
      "c-dynamic-pressure",
    ],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Four terms. Only three you can move.",
        line: "Density is handed to you by the atmosphere. Wing area is fixed. Velocity and C_L are yours.",
      },
      {
        kind: "model",
        headline: "L = ½ρV²SC_L",
        diagram: { id: "lift-equation-anatomy" },
        bullets: [
          "ρ — density, set by altitude, temperature and humidity",
          "V — velocity, SQUARED (this is the one that dominates)",
          "S — wing surface area, b × average chord",
          "C_L — Compressibility, Aspect Ratio, Viscosity, AOA, Camber",
        ],
      },
      {
        kind: "manipulate",
        headline: "Lift Lab",
        widget: "LiftLabMini",
        line: "Double the velocity and watch lift quadruple. Halve the density and watch it merely halve.",
      },
      {
        kind: "chain",
        headline: "In level flight, V and AOA are locked together",
        nodes: [
          { label: "Velocity", trend: "down", emphasis: true },
          { label: "Dynamic pressure ½ρV²", trend: "down" },
          { label: "C_L must rise to hold L = W", trend: "up" },
          { label: "Angle of attack", trend: "up", emphasis: true },
        ],
        footnote: "This is why slow flight is high-AOA flight — and why slow flight is near the stall.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "L = ½ρV²SC_L",
          "C.AR.V.A.C — Compressibility, Aspect Ratio, Viscosity, AOA, Camber",
          "Pilot controls in flight: velocity, AOA, camber",
          "Velocity is squared. Nothing else is.",
        ],
        formula: "L = \\tfrac{1}{2}\\rho V^2 S C_L",
        mnemonic: "C.AR.V.A.C",
      },
      { kind: "question", questionId: "q-u2-012" },
      { kind: "question", questionId: "q-u2-010" },
      { kind: "question", questionId: "sp-u2-011" },
      { kind: "question", questionId: "q-u2-014" },
      { kind: "question", questionId: "q-u2-026" },
    ],
    questionIds: [
      "q-u2-012", "q-u2-010", "sp-u2-011", "q-u2-014", "q-u2-026",
      "q-u2-009", "q-u2-013", "q-u2-024",
    ],
    memorize: [
      "L = ½ρV²SC_L",
      "C.AR.V.A.C",
      "Pilot controls: V, AOA, camber",
    ],
    sourceReferences: [TG("Lift Production and Drag", ["2.84", "2.85"])],
    labIds: ["lab-lift"],
  },

  {
    id: "l10-cl-vs-aoa",
    unit: "u2",
    index: 10,
    title: "CL vs AOA, CLmax & Flaps",
    subtitle: "The curve the whole course hangs from",
    estimatedMinutes: 7,
    mapIcon: "clcurve",
    enablingObjectives: ["2.96", "3.4", "3.13"],
    conceptIds: ["c-cl-vs-aoa", "c-clmax", "c-flaps-cl", "c-camber-types"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "One curve, three exam topics",
        line: "Lift production, stalls, and flaps are all read off this single plot.",
      },
      {
        kind: "model",
        headline: "Up, then over the top",
        diagram: { id: "cl-vs-aoa", props: { camber: "positive" } },
        bullets: [
          "C_L rises nearly linearly with AOA",
          "The peak is C_Lmax; the AOA there is C_Lmax AOA",
          "Beyond it, more AOA gives LESS C_L — that is a stall",
        ],
      },
      {
        kind: "manipulate",
        headline: "Slide the AOA marker",
        widget: "CLCurveSlider",
        line: "Camber shifts the curve sideways. Flaps shift it up and left. The shape stays the same.",
      },
      {
        kind: "compare",
        headline: "Two 'best' angles of attack — do not swap them",
        columns: ["C_Lmax AOA", "L/Dmax AOA"],
        rows: [
          { label: "Nickname", a: "Most EFFECTIVE", b: "Most EFFICIENT" },
          { label: "What it maximises", a: "Coefficient of lift", b: "Lift-to-drag ratio" },
          { label: "Also called", a: "Critical / stalling AOA", b: "Max range AOA (prop)" },
          { label: "On the drag curve", a: "Far left, near stall", b: "Bottom of the total drag curve" },
        ],
      },
      {
        kind: "chain",
        headline: "Flaps down",
        nodes: [
          { label: "Camber", trend: "up", emphasis: true },
          { label: "C_L at every AOA", trend: "up" },
          { label: "C_Lmax", trend: "up" },
          { label: "C_Lmax AOA", trend: "down", emphasis: true },
          { label: "Stall speed", trend: "down" },
        ],
        footnote: "Retracting flaps reverses all of it: C_Lmax down, C_Lmax AOA up.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "C_Lmax AOA is constant for a given airfoil — weight, q and bank do not move it.",
          "Flaps DOWN: C_Lmax ↑, C_Lmax AOA ↓.",
          "Flaps UP: C_Lmax ↓, C_Lmax AOA ↑.",
          "Effective = C_Lmax AOA. Efficient = L/Dmax AOA.",
        ],
      },
      { kind: "question", questionId: "gr-u2-015" },
      { kind: "question", questionId: "ba-u2-020" },
      { kind: "question", questionId: "q-u2-019" },
      { kind: "question", questionId: "cs-u2-025" },
      { kind: "question", questionId: "q-u2-016" },
      { kind: "question", questionId: "q-u2-017" },
    ],
    questionIds: [
      "gr-u2-015", "ba-u2-020", "q-u2-019", "cs-u2-025", "q-u2-016",
      "q-u2-017", "q-u2-018", "q-u2-021",
    ],
    memorize: [
      "Stall: an increase in AOA produces a decrease in C_L",
      "Flaps down: CLmax ↑, CLmax AOA ↓",
      "CLmax AOA is fixed for a given airfoil shape",
    ],
    sourceReferences: [
      TG("Lift Production and Drag", ["2.96"]),
      {
        document: "ACA0101 Basic Theory and Lift Production",
        chapter: "Flaps effect on CL",
        eo: ["3.13"],
      },
    ],
    explainerIds: ["x-cl-vs-aoa"],
    labIds: ["lab-lift"],
  },

  /* ================================================================ */
  /* UNIT 3 — MASTER DRAG                                              */
  /* ================================================================ */
  {
    id: "l11-parasite-drag",
    unit: "u3",
    index: 11,
    title: "Parasite Drag",
    subtitle: "Form, friction, interference",
    estimatedMinutes: 6,
    mapIcon: "parasite",
    enablingObjectives: ["2.87", "2.88"],
    conceptIds: [
      "c-parasite-drag",
      "c-form-drag",
      "c-friction-drag",
      "c-interference-drag",
    ],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "The drag you would still have if the wing made no lift",
        line: "Three components, three different fixes, one V² relationship.",
      },
      {
        kind: "model",
        headline: "Three sources",
        diagram: { id: "parasite-components" },
        bullets: [
          "Form drag — separation and the low-pressure wake · fix: streamline",
          "Friction drag — viscous shear over the skin · fix: paint, clean, flush rivets",
          "Interference drag — streamlines mixing at junctions (5–10% of total) · fix: fairings and fillets",
        ],
      },
      {
        kind: "manipulate",
        headline: "Streamline the shape",
        widget: "FormDragSlider",
        line: "Flat plate → sphere → teardrop. Watch the wake shrink and the drag with it.",
      },
      {
        kind: "chain",
        headline: "Why golf balls have dimples",
        nodes: [
          { label: "Dimples trip the boundary layer turbulent", emphasis: true },
          { label: "Friction drag", trend: "up" },
          { label: "Separation is delayed" },
          { label: "Wake size and form drag", trend: "down" },
          { label: "TOTAL parasite drag", trend: "down", emphasis: true },
        ],
        footnote: "The form-drag saving is larger than the friction-drag cost.",
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "D_P = q × f = ½ρV²f",
          "Parasite drag varies with V² — double the speed, four times the drag",
          "f is an equivalent flat plate, NOT the aircraft's cross-section",
        ],
        formula: "D_P = \\tfrac{1}{2}\\rho V^2 f",
      },
      { kind: "question", questionId: "q-u3-001" },
      { kind: "question", questionId: "q-u3-002" },
      { kind: "question", questionId: "q-u3-003" },
      { kind: "question", questionId: "q-u3-007" },
      { kind: "question", questionId: "q-u3-004" },
    ],
    questionIds: [
      "q-u3-001", "q-u3-002", "q-u3-003", "q-u3-007", "q-u3-004",
      "q-u3-005", "q-u3-006",
    ],
    memorize: [
      "Parasite = form + friction + interference",
      "D_P = ½ρV²f — proportional to V²",
    ],
    sourceReferences: [TG("Lift Production and Drag", ["2.87", "2.88"])],
    explainerIds: ["x-parasite-vs-induced"],
  },

  {
    id: "l12-induced-drag",
    unit: "u3",
    index: 12,
    title: "Induced Drag & Ground Effect",
    subtitle: "The price of making lift on a finite wing",
    estimatedMinutes: 8,
    mapIcon: "vortex",
    enablingObjectives: ["2.89", "2.90", "2.91", "2.92", "2.93", "2.94", "2.95"],
    conceptIds: [
      "c-infinite-wing",
      "c-finite-wing-vortices",
      "c-induced-drag",
      "c-induced-drag-factors",
      "c-induced-drag-reduction",
      "c-ground-effect",
    ],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Real wings have ends. That costs you.",
        line: "On an infinite wing upwash and downwash cancel. Add wingtips and downwash roughly doubles.",
      },
      {
        kind: "compare",
        headline: "Infinite vs finite wing",
        columns: ["Infinite wing", "Finite wing"],
        rows: [
          { label: "Flow at the tips", a: "None — walls block it", b: "Spanwise, around the tip" },
          { label: "Upwash vs downwash", a: "Exactly balanced", b: "Downwash roughly doubles" },
          { label: "Average relative wind", a: "Unchanged", b: "Inclined downward" },
          { label: "Induced drag", a: "None", b: "Present whenever lift is made" },
        ],
      },
      {
        kind: "model",
        headline: "The lift vector tilts aft",
        diagram: { id: "wingtip-vortex", props: { showVectors: true } },
        bullets: [
          "Total lift stays perpendicular to the AVERAGE relative wind",
          "Perpendicular component = EFFECTIVE lift (less than total)",
          "Parallel component = INDUCED drag",
        ],
      },
      {
        kind: "manipulate",
        headline: "Change speed and watch the vortex",
        widget: "InducedDragSlider",
        line: "Slow down: more AOA, more C_L, stronger vortices, more induced drag.",
      },
      {
        kind: "chain",
        headline: "Induced drag chain",
        nodes: [
          { label: "Airspeed", trend: "down", emphasis: true },
          { label: "AOA required", trend: "up" },
          { label: "Coefficient of lift", trend: "up" },
          { label: "Wingtip vortex strength and downwash", trend: "up" },
          { label: "Induced drag", trend: "up", emphasis: true },
        ],
        footnote: "D_I = kW² / (ρV²b²). Weight up top and squared; ρ, V² and b² underneath.",
      },
      {
        kind: "model",
        headline: "Ground effect: the ground blocks the downwash",
        diagram: { id: "ground-effect", props: { heightFraction: 0.25 } },
        bullets: [
          "Begins within ONE WINGSPAN of the ground (~33 ft for the T-6B)",
          "Less downwash → lift vector rotates forward",
          "Effective lift ↑ and induced drag ↓",
          "1 span: −1.4% · ¼ span: −23.5% · just before touchdown: −60%",
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "Induced drag comes from increased DOWNWASH, and rises as AOA rises.",
          "D_I ∝ W², and ∝ 1/(ρV²b²).",
          "Ground effect: within one wingspan · effective lift ↑ · induced drag ↓.",
          "Leaving ground effect: lift ↓, induced drag ↑.",
        ],
        formula: "D_I = \\frac{kW^2}{\\rho V^2 b^2}",
      },
      { kind: "question", questionId: "q-u3-010" },
      { kind: "question", questionId: "cc-u3-011" },
      { kind: "question", questionId: "q-u3-013" },
      { kind: "question", questionId: "q-u3-017" },
      { kind: "question", questionId: "ba-u3-018" },
      { kind: "question", questionId: "q-u3-030" },
    ],
    questionIds: [
      "q-u3-010", "cc-u3-011", "q-u3-013", "q-u3-017", "ba-u3-018",
      "q-u3-030", "q-u3-008", "q-u3-009", "q-u3-012", "q-u3-014",
      "q-u3-015", "q-u3-016", "q-u3-019",
    ],
    memorize: [
      "Induced drag results from increased downwash",
      "D_I = kW²/(ρV²b²)",
      "Ground effect: one wingspan, effective lift ↑, induced drag ↓",
    ],
    sourceReferences: [TG("Lift Production and Drag", ["2.90", "2.91", "2.93", "2.95"])],
    explainerIds: ["x-parasite-vs-induced", "x-ground-effect"],
    labIds: ["lab-drag"],
  },

  {
    id: "l13-total-drag-ldmax",
    unit: "u3",
    index: 13,
    title: "Total Drag & L/Dmax",
    subtitle: "Where the two drags cross",
    estimatedMinutes: 7,
    mapIcon: "dragcurve",
    enablingObjectives: ["2.97", "2.98", "2.99", "2.100"],
    conceptIds: ["c-total-drag", "c-ldmax"],
    masteryThreshold: 0.85,
    screens: [
      {
        kind: "hook",
        headline: "This point shows up in five later lessons",
        line: "Max range, best glide, minimum thrust required, the bottom of the drag curve — all the same place.",
      },
      {
        kind: "model",
        headline: "Two curves, opposite slopes",
        diagram: { id: "drag-curves", props: { showComponents: true } },
        bullets: [
          "Parasite drag climbs with V²",
          "Induced drag falls with velocity",
          "Their sum is U-shaped — and its minimum is L/Dmax",
        ],
      },
      {
        kind: "manipulate",
        headline: "Drag Lab",
        widget: "DragLabMini",
        line: "Slide airspeed and watch the split between the two drags. They are equal exactly at L/Dmax.",
      },
      {
        kind: "chain",
        headline: "What L/Dmax IS",
        nodes: [
          { label: "Greatest ratio of lift to drag", emphasis: true },
          { label: "= minimum TOTAL drag" },
          { label: "= parasite drag equals induced drag" },
          { label: "= the most EFFICIENT angle of attack", emphasis: true },
        ],
        footnote:
          "It is NOT maximum lift, NOT maximum speed, and it measures the WING's efficiency, not the engine's.",
      },
      {
        kind: "compare",
        headline: "Which drag dominates?",
        columns: ["Below L/Dmax velocity", "Above L/Dmax velocity"],
        rows: [
          { label: "Dominant drag", a: "INDUCED", b: "PARASITE" },
          { label: "AOA", a: "High", b: "Low" },
          { label: "Slowing further", a: "Drag rises steeply", b: "Drag falls toward L/Dmax" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know Cold",
        statements: [
          "L/Dmax = minimum total drag = parasite equals induced.",
          "As airspeed decreases, total drag becomes primarily INDUCED.",
          "Weight ↑ or altitude ↑ moves L/Dmax AIRSPEED, not L/Dmax or its AOA.",
        ],
        formula: "\\frac{L}{D} = \\frac{C_L}{C_D}",
      },
      { kind: "question", questionId: "gr-u3-022" },
      { kind: "question", questionId: "q-u3-023" },
      { kind: "question", questionId: "q-u3-024" },
      { kind: "question", questionId: "q-u3-021" },
      { kind: "question", questionId: "cs-u3-028" },
      { kind: "question", questionId: "q-u3-026" },
    ],
    questionIds: [
      "gr-u3-022", "q-u3-023", "q-u3-024", "q-u3-021", "cs-u3-028",
      "q-u3-026", "q-u3-020", "q-u3-025", "trap-u3-027", "sp-u3-029",
    ],
    memorize: [
      "L/Dmax = minimum total drag",
      "At L/Dmax, parasite drag = induced drag",
      "L/Dmax AOA is the most EFFICIENT AOA",
    ],
    sourceReferences: [TG("Lift Production and Drag", ["2.97", "2.98", "2.100"])],
    explainerIds: ["x-ldmax-made-simple"],
    labIds: ["lab-drag"],
  },
];
