import type { Question, SourceReference } from "@/lib/types";

const TG = (chapter: string, eo: string[]): SourceReference => ({
  document: "Weather Trainee Guide",
  chapter,
  eo,
});

/**
 * Questions on the material the trainee guide covers and the condensed notes
 * do not. Every one carries the enabling objective it assesses.
 */
export const GUIDE_QUESTIONS: Question[] = [
  /* ================= w1 · the stratosphere ================= */
  {
    id: "wq-wg-001",
    type: "mcq",
    unit: "w1",
    conceptIds: ["wx-stratosphere"],
    prompt: "Flight conditions in the stratosphere are characterised by",
    options: [
      "frequent turbulence and restricted visibility",
      "smooth flying conditions and excellent visibility",
      "heavy icing and low ceilings",
      "rapidly falling temperature with altitude",
    ],
    answer: 1,
    explanation:
      "Smooth air and excellent visibility. Temperature is constant to approximately 66,000 ft, then slowly increases above that.",
    knowCold: "Stratosphere: smooth, and you can see forever.",
    difficulty: 2,
    source: TG("Atmospheric Physics", ["2.201", "2.204"]),
  },
  {
    id: "wq-wg-002",
    type: "mcq",
    unit: "w1",
    conceptIds: ["wx-stratosphere"],
    prompt: "Within the stratosphere, temperature is constant to approximately",
    options: ["36,000 ft", "55,000 ft", "66,000 ft", "158,000 ft"],
    answer: 2,
    explanation:
      "Constant to about 66,000 ft, then slowly increasing with altitude above it — an inverted lapse rate. The average top of the stratosphere over the USA is 158,000 ft MSL.",
    whyWrong: "158,000 ft is the TOP of the layer, not where the temperature starts rising.",
    knowCold: "Isothermal to 66,000, then rising. Top around 158,000.",
    difficulty: 3,
    source: TG("Atmospheric Physics", ["2.201"]),
  },
  {
    id: "wq-wg-003",
    type: "mcq",
    unit: "w1",
    conceptIds: ["wx-layer-flight-conditions", "wx-stratosphere"],
    prompt: "Which layer would you expect to give the smoothest ride?",
    options: ["The troposphere", "The tropopause", "The stratosphere", "All three are similar"],
    answer: 2,
    explanation:
      "Nearly all weather — and therefore the turbulence, icing and restricted visibility that come with it — is in the troposphere. The jet stream and its shear sit at the tropopause. The stratosphere is the smooth one, and few aircraft can fly there.",
    knowCold: "Weather below, jet stream between, smooth above.",
    difficulty: 2,
    source: TG("Atmospheric Physics", ["2.202", "2.203", "2.204"]),
  },
  {
    id: "wq-wg-004",
    type: "mcq",
    unit: "w1",
    conceptIds: ["wx-layer-flight-conditions"],
    prompt: "Turbulence, icing and restricted visibility are concentrated in the",
    options: ["stratosphere", "troposphere", "tropopause", "ionosphere"],
    answer: 1,
    explanation:
      "They travel with the weather, and nearly all weather occurs in the troposphere.",
    knowCold: "The weather layer is the hazard layer.",
    difficulty: 1,
    source: TG("Atmospheric Physics", ["2.202"]),
  },

  /* ================= w4 · mountain and valley winds ================= */
  {
    id: "wq-wg-005",
    type: "mcq",
    unit: "w4",
    conceptIds: ["wx-mountain-valley-wind"],
    prompt: "During the DAY, air flowing up a mountain slope from the valley is called a",
    options: ["mountain wind", "valley wind", "katabatic wind", "sea breeze"],
    answer: 1,
    explanation:
      "The sun heats the slopes, which heat the adjacent air by conduction. That air becomes warmer and less dense than air at the same altitude away from the slope, so it rises — and the air flowing from the valley to replace it is the valley wind.",
    knowCold: "Day: valley wind, up the slope.",
    difficulty: 2,
    source: TG("Atmospheric Circulation", ["2.220", "2.221"]),
  },
  {
    id: "wq-wg-006",
    type: "mcq",
    unit: "w4",
    conceptIds: ["wx-mountain-valley-wind"],
    prompt: "At NIGHT, air on a mountain slope becomes denser than its surroundings because of",
    options: [
      "conduction from the warm rock",
      "outgoing terrestrial radiation cooling it",
      "the pressure gradient force",
      "orographic lifting",
    ],
    answer: 1,
    explanation:
      "The cooled, denser air then flows downhill from the top of the mountain — the mountain wind, a circulation opposite to the daytime pattern.",
    knowCold: "Night: mountain wind, down the slope.",
    difficulty: 3,
    source: TG("Atmospheric Circulation", ["2.220"]),
  },
  {
    id: "wq-wg-007",
    type: "mcq",
    unit: "w4",
    conceptIds: ["wx-mountain-valley-wind"],
    prompt: "Mountain and valley winds are of particular importance to",
    options: [
      "high-altitude jet traffic",
      "light aircraft, helicopter and low-level operations",
      "aircraft in the stratosphere",
      "aircraft on instrument approaches only",
    ],
    answer: 1,
    explanation:
      "In mountainous areas where fixed-wing or helicopter performance is marginal, their location can be critical.",
    knowCold: "Light aircraft, helos and low level.",
    difficulty: 2,
    source: TG("Atmospheric Circulation", ["2.221"]),
  },

  /* ================= w3 · stability clues ================= */
  {
    id: "wq-wg-008",
    type: "mcq",
    unit: "w3",
    conceptIds: ["wx-stability-clues"],
    prompt: "Which of the following indicates STABLE air?",
    options: ["Dust devils", "Towering cumulus", "Widespread fog or low clouds", "Heavy showers"],
    answer: 2,
    explanation:
      "Stable clues: temperature inversions, widespread fog or low clouds, and rising or only slightly decreasing temperature while climbing. The other three are all unstable indicators.",
    knowCold: "Stable: inversions, fog, low cloud.",
    difficulty: 2,
    source: TG("Atmospheric Moisture", ["2.233"]),
  },
  {
    id: "wq-wg-009",
    type: "mcq",
    unit: "w3",
    conceptIds: ["wx-stability-clues"],
    prompt: "Rapidly decreasing temperature while climbing indicates",
    options: ["a stable atmosphere", "an unstable atmosphere", "a temperature inversion", "the tropopause"],
    answer: 1,
    explanation:
      "Unstable air. In stable air the temperature RISES or falls only slightly as you climb — that is what an inversion looks like from the cockpit.",
    whyWrong: "An inversion is the opposite signature and is a stable indicator.",
    knowCold: "Falling fast means unstable.",
    difficulty: 3,
    source: TG("Atmospheric Moisture", ["2.234"]),
  },
  {
    id: "wq-wg-010",
    type: "mcq",
    unit: "w3",
    conceptIds: ["wx-stability-clues"],
    prompt: "Dust devils are a clue to",
    options: ["stable air", "unstable air", "a warm front", "an inversion"],
    answer: 1,
    explanation:
      "Along with thunderstorms, towering cumulus and heavy showers. They are all signs that the air wants to rise.",
    knowCold: "Dust devils mean unstable.",
    difficulty: 1,
    source: TG("Atmospheric Moisture", ["2.234"]),
  },

  /* ================= w5 · forms of precipitation ================= */
  {
    id: "wq-wg-011",
    type: "mcq",
    unit: "w5",
    conceptIds: ["wx-precipitation-forms"],
    prompt: "Hail",
    options: [
      "leads to rapid structural icing",
      "does not lead to structural ice, but can cause structural damage",
      "is harmless to aircraft",
      "only forms in stratiform cloud",
    ],
    answer: 1,
    explanation:
      "Irregular lumps of ice that develop in severe thunderstorms. They do not produce structural ice, but they will damage the airframe.",
    whyWrong:
      "Ice on the airframe and ice hitting the airframe are two different problems. Hail is the second.",
    knowCold: "Hail damages. It does not ice.",
    difficulty: 3,
    source: TG("Atmospheric Moisture", ["2.228"]),
  },
  {
    id: "wq-wg-012",
    type: "mcq",
    unit: "w5",
    conceptIds: ["wx-precipitation-forms"],
    prompt: "Ice pellets or sleet produce structural icing",
    options: [
      "always",
      "never",
      "only when mixed with super-cooled water",
      "only above freezing",
    ],
    answer: 2,
    explanation:
      "They form when rain falls through air below freezing, and usually bounce on hard ground. On their own they do not produce structural ice.",
    knowCold: "Sleet ices only if super-cooled water is in the mix.",
    difficulty: 3,
    source: TG("Atmospheric Moisture", ["2.228"]),
  },
  {
    id: "wq-wg-013",
    type: "mcq",
    unit: "w5",
    conceptIds: ["wx-precipitation-forms"],
    prompt: "Which form of precipitation CAN lead to structural icing?",
    options: ["Snow grains", "Hail", "Partially melted or wet snow", "Dry ice pellets"],
    answer: 2,
    explanation:
      "Wet snow can lead to structural icing. Dry snow crystals, snow grains, hail and unmixed ice pellets do not.",
    knowCold: "Wet snow ices. Dry snow does not.",
    difficulty: 3,
    source: TG("Atmospheric Moisture", ["2.228"]),
  },
  {
    id: "wq-wg-014",
    type: "mcq",
    unit: "w5",
    conceptIds: ["wx-precipitation-forms"],
    prompt: "Drizzle is distinguished from rain by",
    options: [
      "its temperature",
      "droplet size — drizzle droplets are very small and appear to float",
      "the cloud it falls from",
      "whether it freezes on impact",
    ],
    answer: 1,
    explanation:
      "Rain is water droplets LARGER than drizzle. Freezing drizzle and freezing rain are the same two forms, freezing on impact with objects.",
    knowCold: "Drizzle floats. Rain falls.",
    difficulty: 2,
    source: TG("Atmospheric Moisture", ["2.228"]),
  },

  /* ================= w6 · frontal weather ================= */
  {
    id: "wq-wg-015",
    type: "mcq",
    unit: "w6",
    conceptIds: ["wx-frontal-weather-factors"],
    prompt: "Which pair are among the five factors that influence frontal weather?",
    options: [
      "Slope and stability",
      "Latitude and season",
      "Cloud base and ceiling",
      "Visibility and precipitation type",
    ],
    answer: 0,
    explanation:
      "The five are: the amount of moisture available shown by the dew point, the degree of stability of the lifted air, the slope of the front, the speed of frontal movement, and the contrast in temperature and moisture between the two air masses.",
    knowCold: "Moisture · Stability · Slope · Speed · Contrast.",
    difficulty: 3,
    officialStyle: true,
    source: TG("Frontal Mechanics", ["2.239"]),
  },
  {
    id: "wq-wg-016",
    type: "mcq",
    unit: "w6",
    conceptIds: ["wx-frontal-weather-factors"],
    prompt:
      "A front has steep slope, fast movement and strong temperature contrast, but the warm air is very dry. The likely result is",
    options: [
      "severe thunderstorms",
      "little or no significant weather",
      "widespread continuous rain",
      "heavy icing",
    ],
    answer: 1,
    explanation:
      "The guide is explicit: often little or no significant weather is associated with a front because of a lack of moisture, despite the presence of all the other factors. Moisture is the gate.",
    knowCold: "No moisture, no weather — whatever else is true.",
    difficulty: 3,
    source: TG("Frontal Mechanics", ["2.239"]),
  },
  {
    id: "wq-wg-017",
    type: "mcq",
    unit: "w6",
    conceptIds: ["wx-frontal-weather-factors"],
    prompt: "Which of the five factors determines whether cloud will be stratiform or cumuliform?",
    options: [
      "The amount of moisture available",
      "The degree of stability of the lifted air",
      "The speed of frontal movement",
      "The slope of the front",
    ],
    answer: 1,
    explanation:
      "Stability decides the form. Stratiform gives steady precipitation and little or no turbulence; cumuliform gives showery precipitation and indicates turbulence.",
    knowCold: "Stability picks the cloud shape.",
    difficulty: 2,
    source: TG("Frontal Mechanics", ["2.239"]),
  },
  {
    id: "wq-wg-018",
    type: "mcq",
    unit: "w6",
    conceptIds: ["wx-squall-line"],
    prompt: "A squall line typically develops",
    options: [
      "along the cold front itself",
      "50 to 300 miles ahead of the cold front, roughly parallel to it",
      "behind the warm front",
      "only over water",
    ],
    answer: 1,
    explanation:
      "Cold air downdrafts running ahead of the cold front lift additional warm unstable air, which starts its own thunderstorm development cycle. Squall lines can also form nowhere near a front, from convergence.",
    knowCold: "50–300 miles ahead, parallel to the cold front.",
    difficulty: 3,
    source: TG("Frontal Mechanics", ["2.241"]),
  },
  {
    id: "wq-wg-019",
    type: "mcq",
    unit: "w6",
    conceptIds: ["wx-squall-line"],
    prompt: "Squall lines are usually most intense",
    options: [
      "just before dawn",
      "at midday",
      "late afternoon and early evening, just after maximum daytime heating",
      "overnight",
    ],
    answer: 2,
    explanation:
      "They are shown on surface charts by a dashed, double-dotted red line, and like a cold front carry a 90° wind shift from SW to NW.",
    knowCold: "Late afternoon and early evening.",
    difficulty: 3,
    source: TG("Frontal Mechanics", ["2.241"]),
  },
  {
    id: "wq-wg-020",
    type: "spotTheTrap",
    unit: "w6",
    conceptIds: ["wx-squall-line"],
    prompt: '"A squall line can be safely penetrated provided the aircraft has weather radar."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. It is often impossible to fly through a squall line even with radar, because the storms sit extremely close to one another.",
    knowCold: "Radar does not open a path through a squall line.",
    difficulty: 3,
    source: TG("Frontal Mechanics", ["2.241"]),
  },
  {
    id: "wq-wg-021",
    type: "mcq",
    unit: "w6",
    conceptIds: ["wx-inactive-front"],
    prompt: "An inactive front, also called a dry front,",
    options: [
      "produces heavy continuous precipitation",
      "has no clouds or precipitation, often showing only a wind shift and a change in temperature and pressure",
      "always precedes a squall line",
      "cannot be shown on a weather chart",
    ],
    answer: 1,
    explanation:
      "The warm air mass is too dry for cloud to form even after being lifted and cooled. It is charted to mark the boundary of the opposing air masses and the location of potentially unfavourable flying weather.",
    knowCold: "Dry front: wind, temperature and pressure only.",
    difficulty: 3,
    source: TG("Frontal Mechanics", ["2.245"]),
  },
  {
    id: "wq-wg-022",
    type: "mcq",
    unit: "w6",
    conceptIds: ["wx-inactive-front"],
    prompt: "Why is an inactive front shown on a weather chart at all?",
    options: [
      "To indicate the boundary of the opposing air masses and potentially unfavourable weather",
      "Because it always produces turbulence",
      "To mark the position of the jet stream",
      "It is not — inactive fronts are omitted",
    ],
    answer: 0,
    explanation:
      "The warm air mass may gradually become moister and produce cloud and precipitation in the frontal zone later.",
    knowCold: "It marks a boundary that could turn active.",
    difficulty: 3,
    source: TG("Frontal Mechanics", ["2.245"]),
  },

  /* ================= w7 · mountain wave and CAT ================= */
  {
    id: "wq-wg-023",
    type: "mcq",
    unit: "w7",
    conceptIds: ["wx-clear-air-turbulence"],
    prompt: "Clear air turbulence is",
    options: [
      "a fifth causative factor, distinct from the other four",
      "turbulence occurring in the absence of, or outside of, clouds",
      "turbulence found only in the jet stream",
      "turbulence below 1,000 ft AGL",
    ],
    answer: 1,
    explanation:
      "Any of the four causative types may occur without the visual warning clouds provide. CAT describes where it happens, not what causes it.",
    whyWrong:
      "The four causes remain thermal, mechanical, frontal and large scale wind shear. CAT is not a fifth.",
    knowCold: "CAT is turbulence with no cloud to warn you.",
    difficulty: 3,
    source: TG("Turbulence", ["2.246"]),
  },
  {
    id: "wq-wg-024",
    type: "mcq",
    unit: "w7",
    conceptIds: ["wx-mountain-wave"],
    prompt: "Mountain waves form when strong winds blow",
    options: [
      "parallel to a mountain range",
      "approximately perpendicular to a mountain range",
      "from the leeward side toward the peak",
      "at less than 20 kt",
    ],
    answer: 1,
    explanation:
      "In stable air, large standing waves form on the LEE side and extend up to the lower stratosphere for 300 miles or more downwind.",
    knowCold: "Strong wind, perpendicular to the ridge, stable air.",
    difficulty: 2,
    source: TG("Turbulence", ["2.251"]),
  },
  {
    id: "wq-wg-025",
    type: "mcq",
    unit: "w7",
    conceptIds: ["wx-mountain-wave"],
    prompt:
      "Extreme mountain wave turbulence is usually found at low levels on the leeward side when winds at the mountaintop are",
    options: ["10 kt or greater", "25 kt or greater", "50 kt or greater", "100 kt or greater"],
    answer: 2,
    explanation:
      "At 50 kt or more at the peak, severe turbulence can exist from the surface to the tropopause and 150 miles downwind, with moderate turbulence as far as 300 miles downwind.",
    knowCold: "50 kt at the peak is the threshold.",
    difficulty: 3,
    source: TG("Turbulence", ["2.251"]),
  },
  {
    id: "wq-wg-026",
    type: "mcq",
    unit: "w7",
    conceptIds: ["wx-wave-clouds"],
    prompt: "The ROTOR cloud generally forms at about the height of",
    options: ["20,000 ft", "the mountain ridge", "the tropopause", "the cloud base of the cap cloud"],
    answer: 1,
    explanation:
      "Lenticular clouds occur usually above 20,000 ft; the rotor forms lower, at about ridge height; and the cap cloud obscures both sides of the peak.",
    knowCold: "Lenticular high, rotor at the ridge, cap on the peak.",
    difficulty: 3,
    source: TG("Turbulence", ["2.251"]),
  },
  {
    id: "wq-wg-027",
    type: "mcq",
    unit: "w7",
    conceptIds: ["wx-wave-clouds"],
    prompt: "Lenticular, rotor and cap clouds are unusual in that they",
    options: [
      "move faster than the wind",
      "remain stationary in position even though the wind flows through them",
      "form only at night",
      "produce continuous precipitation",
    ],
    answer: 1,
    explanation:
      "They mark the standing wave, which is fixed relative to the terrain. It is also possible for wave action to occur when the air is too dry to form any cloud at all — producing CAT with no visual warning.",
    knowCold: "They stand still while the wind goes through them.",
    difficulty: 3,
    source: TG("Turbulence", ["2.251"]),
  },
  {
    id: "wq-wg-028",
    type: "mcq",
    unit: "w7",
    conceptIds: ["wx-wave-technique"],
    prompt:
      "If mountain wave turbulence is forecast and you cannot avoid the area, you should fly at a level at least",
    options: [
      "1,000 ft above the highest peak",
      "50% higher than the height of the highest mountain range along the route",
      "double the height of the highest peak",
      "at the height of the ridge",
    ],
    answer: 1,
    explanation:
      "It will not keep the aircraft out of turbulence, but it provides a margin of safety if a strong downdraft is encountered.",
    knowCold: "50% above the highest terrain.",
    difficulty: 3,
    source: TG("Turbulence", ["2.252"]),
  },
  {
    id: "wq-wg-029",
    type: "mcq",
    unit: "w7",
    conceptIds: ["wx-wave-technique"],
    prompt: "A mountain range should be approached at what angle, so a quick turn away is possible?",
    options: ["90°", "45°", "30°", "Directly, at 0°"],
    answer: 1,
    explanation:
      "45°, so that a quick turn can be made away from the ridge if a severe downdraft is encountered.",
    knowCold: "45° to the ridge.",
    difficulty: 3,
    source: TG("Turbulence", ["2.252"]),
  },
  {
    id: "wq-wg-030",
    type: "mcq",
    unit: "w7",
    conceptIds: ["wx-wave-technique"],
    prompt: "Near mountain peaks, pressure altimeter readings may indicate as much as",
    options: [
      "500 ft higher than true altitude",
      "1,000 ft higher than true altitude",
      "2,500 ft higher than true altitude",
      "5,000 ft lower than true altitude",
    ],
    answer: 2,
    explanation:
      "More than 2,500 ft higher than true altitude — so do not place too much confidence in the altimeter there.",
    knowCold: "Altimeter can over-read by 2,500 ft near peaks.",
    difficulty: 3,
    source: TG("Turbulence", ["2.252"]),
  },

  /* ================= w8 · frontal and PIREP icing ================= */
  {
    id: "wq-wg-031",
    type: "mcq",
    unit: "w8",
    conceptIds: ["wx-frontal-icing"],
    prompt: "Icing at a WARM front is characteristically",
    options: [
      "clear ice, high rate of accumulation, limited area",
      "rime ice, low rate of accumulation, widespread area",
      "mixed ice, rapid accumulation, very widespread",
      "no icing at all",
    ],
    answer: 1,
    explanation:
      "Warm fronts give stratiform cloud, so rime ice at a low accumulation rate over a widespread area. Cold fronts give cumuliform cloud, clear ice, a high rate and a limited area.",
    knowCold: "Warm front: rime, slow, widespread.",
    difficulty: 3,
    source: TG("Icing", ["2.260"]),
  },
  {
    id: "wq-wg-032",
    type: "mcq",
    unit: "w8",
    conceptIds: ["wx-frontal-icing"],
    prompt: "Which front produces rapid and heavy accumulation over a very widespread area?",
    options: ["Cold front", "Warm front", "Occluded front", "Inactive front"],
    answer: 2,
    explanation:
      "The occluded front mixes stratus and cumulus, so it produces rime, clear and mixed icing at a rapid heavy rate over a very widespread area. It is the worst of the three.",
    knowCold: "Occluded is the worst icing front.",
    difficulty: 3,
    source: TG("Icing", ["2.260"]),
  },
  {
    id: "wq-wg-033",
    type: "mcq",
    unit: "w8",
    conceptIds: ["wx-pirep-icing"],
    prompt: "In a PIREP, SEVERE icing is defined by",
    options: [
      "ice becoming perceptible",
      "accumulation being a problem over an extended time",
      "the de-ice and anti-ice equipment failing to reduce or control it",
      "any accumulation on a leading edge",
    ],
    answer: 2,
    explanation:
      "Severe means the equipment cannot cope and immediate diversion is necessary. Moderate is where the rate is potentially hazardous even in short encounters and equipment or diversion becomes necessary.",
    whyWrong: "Trace is where ice merely becomes perceptible.",
    knowCold: "Severe = the equipment has lost.",
    difficulty: 3,
    source: TG("Icing", ["2.264"]),
  },
  {
    id: "wq-wg-034",
    type: "mcq",
    unit: "w8",
    conceptIds: ["wx-pirep-icing"],
    prompt: "PIREPs report icing by intensity and by",
    options: ["altitude band", "type — clear, rime or mixed", "duration", "aircraft category"],
    answer: 1,
    explanation:
      "Type and intensity together. The intensities are trace, light, moderate and severe.",
    knowCold: "Type and intensity, both.",
    difficulty: 2,
    source: TG("Icing", ["2.265"]),
  },
  {
    id: "wq-wg-035",
    type: "mcq",
    unit: "w8",
    conceptIds: ["wx-pirep-icing"],
    prompt: "TRACE icing is reported when the rate of accumulation is",
    options: [
      "slightly greater than the rate of sublimation",
      "hazardous within minutes",
      "beyond the capability of the equipment",
      "zero",
    ],
    answer: 0,
    explanation:
      "Ice becomes perceptible, and de-ice or anti-ice is not used unless the encounter is extended.",
    knowCold: "Trace: just outpacing sublimation.",
    difficulty: 3,
    source: TG("Icing", ["2.264"]),
  },

  /* ================= w9 · fog types, ash, radar ================= */
  {
    id: "wq-wg-036",
    type: "mcq",
    unit: "w9",
    conceptIds: ["wx-fog-types"],
    prompt: "The two main types of fog are",
    options: [
      "radiation fog and advection fog",
      "sea fog and ice fog",
      "upslope fog and steam fog",
      "frontal fog and valley fog",
    ],
    answer: 0,
    explanation:
      "Radiation fog comes from nocturnal cooling; advection fog comes from warm moist air moving over a cold surface.",
    knowCold: "Radiation and advection.",
    difficulty: 1,
    source: TG("Atmospheric Hazards", ["2.271"]),
  },
  {
    id: "wq-wg-037",
    type: "mcq",
    unit: "w9",
    conceptIds: ["wx-fog-types"],
    prompt: "Radiation cooling begins after the maximum daily temperature, usually between",
    options: ["1130 and 1200", "1330 and 1400", "1530 and 1600", "1830 and 1900"],
    answer: 2,
    explanation:
      "Cooling then continues until sunrise or shortly after, and it affects only the lower limits of the atmosphere.",
    knowCold: "1530 to 1600 local.",
    difficulty: 3,
    source: TG("Atmospheric Hazards", ["2.271"]),
  },
  {
    id: "wq-wg-038",
    type: "mcq",
    unit: "w9",
    conceptIds: ["wx-fog-types"],
    prompt: "Advection fog forms when",
    options: [
      "the ground radiates heat on a clear night",
      "warm, moist air moves over a cold surface and is cooled to the dew point",
      "cold air is lifted over a mountain",
      "rain falls into dry air",
    ],
    answer: 1,
    explanation:
      "Common in coastal areas, where it is often called sea fog. It can stay over the water for weeks, moving over the land late in the day and back over the water the next morning.",
    knowCold: "Warm moist air onto a cold surface.",
    difficulty: 2,
    source: TG("Atmospheric Hazards", ["2.271"]),
  },
  {
    id: "wq-wg-039",
    type: "mcq",
    unit: "w9",
    conceptIds: ["wx-fog-winds"],
    prompt: "For RADIATION fog, winds greater than 10 kt will usually",
    options: [
      "make the fog denser",
      "dissipate the fog into low stratus or stratocumulus",
      "have no effect",
      "lower the fog to the surface",
    ],
    answer: 1,
    explanation:
      "Under 5 kt gives shallow fog, 5 to 10 kt gives dense fog, and over 10 kt disperses it into cloud.",
    knowCold: "Radiation fog: 5–10 kt is the dense band.",
    difficulty: 3,
    source: TG("Atmospheric Hazards", ["2.271"]),
  },
  {
    id: "wq-wg-040",
    type: "spotTheTrap",
    unit: "w9",
    conceptIds: ["wx-fog-winds"],
    prompt: '"Increasing wind thins both radiation fog and advection fog."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False, and this is the trap. Radiation fog disperses above about 10 kt. Advection fog becomes THICKER and denser as the wind increases, up to about 15 kt — and sea fog has persisted with winds as high as 40 kt.",
    knowCold: "Wind thins radiation fog and thickens advection fog.",
    difficulty: 3,
    source: TG("Atmospheric Hazards", ["2.271"]),
  },
  {
    id: "wq-wg-041",
    type: "mcq",
    unit: "w9",
    conceptIds: ["wx-ash-clouds"],
    prompt: "Volcanic ash clouds are difficult to detect because",
    options: [
      "they are transparent",
      "radar detection is unlikely, owing to the small size of the particles",
      "they only occur at night",
      "they are always above 40,000 ft",
    ],
    answer: 1,
    explanation:
      "Their presence may be unknown until you have entered the cloud. Flight in ash is indicated by torching from the engine tailpipe, a St. Elmo's fire effect and a bright glow in the engine inlets.",
    knowCold: "Radar cannot see ash.",
    difficulty: 3,
    source: TG("Atmospheric Hazards", ["2.272"]),
  },
  {
    id: "wq-wg-042",
    type: "mcq",
    unit: "w9",
    conceptIds: ["wx-ash-clouds"],
    prompt: "Which is a hazard of flight in volcanic ash?",
    options: [
      "Loss of a single engine only",
      "Multiple engine malfunctions and flameout, affecting all engines",
      "Increased lift",
      "Radio failure only",
    ],
    answer: 1,
    explanation:
      "All engines on a multi-engine aircraft are affected. Ash also pits the windscreen, affecting cockpit visibility, and sandblasts external surfaces.",
    knowCold: "All engines. Not one.",
    difficulty: 3,
    source: TG("Atmospheric Hazards", ["2.272"]),
  },
  {
    id: "wq-wg-043",
    type: "mcq",
    unit: "w9",
    conceptIds: ["wx-ash-avoidance"],
    prompt: "On encountering a volcanic ash cloud, you should",
    options: [
      "climb over it",
      "descend beneath it",
      "make a 180° turn to escape",
      "continue on course at reduced power",
    ],
    answer: 2,
    explanation:
      "Do not proceed, and do not try to fly over or under — ash clouds are hundreds of miles long and thousands of feet thick. Turn 180°, then notify the nearest ATC and transmit a PIREP.",
    whyWrong:
      "Over and under work for a thunderstorm. An ash cloud is far too large for either.",
    knowCold: "180° out, then tell ATC.",
    difficulty: 3,
    source: TG("Atmospheric Hazards", ["2.272"]),
  },
  {
    id: "wq-wg-044",
    type: "mcq",
    unit: "w9",
    conceptIds: ["wx-ash-avoidance"],
    prompt: "After escaping an ash cloud, the pilot should",
    options: [
      "say nothing until landing",
      "notify the nearest ATC and transmit a PIREP",
      "file a written report within 24 hours",
      "return to inspect the cloud from a safe distance",
    ],
    answer: 1,
    explanation: "So that everyone else behind you knows where it is.",
    knowCold: "Notify ATC and PIREP it.",
    difficulty: 2,
    source: TG("Atmospheric Hazards", ["2.272"]),
  },
  {
    id: "wq-wg-045",
    type: "mcq",
    unit: "w9",
    conceptIds: ["wx-thunderstorm-radar"],
    prompt: "A thunderstorm with radar echo tops above 35,000 ft often contains",
    options: [
      "light turbulence only",
      "extreme turbulence and hail",
      "no significant hazard",
      "clear air only",
    ],
    answer: 1,
    explanation:
      "A direct relationship exists between the strength of the radar echoes, the presence of aircraft icing and the intensity of turbulence — stronger echoes mean a more severe storm.",
    knowCold: "Tops above 35,000 ft: extreme turbulence and hail.",
    difficulty: 3,
    source: TG("Thunderstorms", ["2.275"]),
  },
  {
    id: "wq-wg-046",
    type: "mcq",
    unit: "w9",
    conceptIds: ["wx-thunderstorm-radar"],
    prompt:
      "Severe clear air turbulence and hail may be experienced BETWEEN thunderstorms when the echoes are separated by less than",
    options: ["5 miles", "10 miles", "20 miles", "30 miles"],
    answer: 3,
    explanation:
      "Less than 30 miles apart, so the gap between two cells is not necessarily safe passage.",
    knowCold: "Under 30 miles apart, the gap is not clear.",
    difficulty: 3,
    source: TG("Thunderstorms", ["2.275"]),
  },
  {
    id: "wq-wg-047",
    type: "spotTheTrap",
    unit: "w9",
    conceptIds: ["wx-thunderstorm-radar"],
    prompt: '"Airborne weather radar eliminates the hazards of flying near a thunderstorm."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. Radar merely helps LOCATE the most severe conditions. The radarscope indicates only precipitation areas, so hazards can be encountered even in areas that look soft. It is used to circumnavigate, not to penetrate.",
    knowCold: "Radar locates. It does not protect.",
    difficulty: 3,
    source: TG("Thunderstorms", ["2.275"]),
  },

  /* ================= w10 · advisory identifiers ================= */
  {
    id: "wq-wg-048",
    type: "mcq",
    unit: "w10",
    conceptIds: ["wx-advisory-identifiers"],
    prompt: "The letter identifier for a Convective SIGMET is",
    options: ["WS", "WST", "WA", "WW"],
    answer: 1,
    explanation: "SIGMET is WS, Convective SIGMET is WST, and AIRMET is WA.",
    knowCold: "WS · WST · WA.",
    difficulty: 2,
    source: TG("Weather Products", ["2.278"]),
  },
  {
    id: "wq-wg-049",
    type: "mcq",
    unit: "w10",
    conceptIds: ["wx-advisory-identifiers"],
    prompt: "AIRMET Tango is issued for",
    options: [
      "widespread IFR conditions and mountain obscuration",
      "moderate turbulence, or sustained surface winds of 30 kt or more",
      "moderate icing or freezing level data",
      "convective activity",
    ],
    answer: 1,
    explanation:
      "Sierra is IFR and mountain obscuration, Tango is turbulence and strong surface winds, Zulu is icing and freezing level.",
    knowCold: "Sierra IFR · Tango turbulence · Zulu icing.",
    difficulty: 3,
    source: TG("Weather Products", ["2.277", "2.278"]),
  },
  {
    id: "wq-wg-050",
    type: "mcq",
    unit: "w10",
    conceptIds: ["wx-advisory-identifiers"],
    prompt: "AIRMET Zulu covers",
    options: [
      "moderate icing or freezing level data",
      "moderate turbulence",
      "IFR conditions",
      "thunderstorms",
    ],
    answer: 0,
    explanation:
      "Zulu is the icing one. Sierra covers widespread IFR — ceilings below 1,000 ft and/or visibility below 3 miles affecting over 50% of the area — or extensive mountain obscuration.",
    knowCold: "Zulu is ice.",
    difficulty: 2,
    source: TG("Weather Products", ["2.278"]),
  },
  {
    id: "wq-wg-051",
    type: "mcq",
    unit: "w10",
    conceptIds: ["wx-advisory-identifiers"],
    prompt: "Sierra, Tango and Zulu are NOT used as non-convective SIGMET designators because",
    options: [
      "they are reserved for the scheduled AIRMETs",
      "they are reserved for military use",
      "they indicate geographic areas",
      "they are no longer in service",
    ],
    answer: 0,
    explanation:
      "Non-convective SIGMETs therefore use November, Oscar, Papa, Quebec, Romeo, Uniform, Victor, Whiskey, X-ray and Yankee instead.",
    knowCold: "Sierra, Tango and Zulu belong to the AIRMETs.",
    difficulty: 3,
    source: TG("Weather Products", ["2.278"]),
  },
  {
    id: "wq-wg-052",
    type: "spotTheTrap",
    unit: "w7",
    conceptIds: ["wx-clear-air-turbulence"],
    prompt:
      '"Clear air turbulence is a fifth causative factor, alongside thermal, mechanical, frontal and wind shear."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. There are four causative factors, and ANY of them can occur outside cloud. Clear air turbulence describes the absence of a visual warning, not a separate cause.",
    knowCold: "Four causes. CAT is a circumstance, not a fifth.",
    difficulty: 3,
    source: TG("Turbulence", ["2.246"]),
  },
  {
    id: "wq-wg-053",
    type: "mcq",
    unit: "w3",
    conceptIds: ["wx-saturation"],
    prompt: "Air is saturated when it",
    options: [
      "contains any visible moisture",
      "is holding the maximum water vapour possible for its temperature and pressure",
      "has a dew point spread of 4 °F",
      "reaches its freezing point",
    ],
    answer: 1,
    explanation:
      "Saturation is relative humidity 100%, with the dew point spread at zero. Once the spread reaches 4 °F the RH is 90% and vapour is already beginning to condense into fog or cloud.",
    knowCold: "Saturation: holding the maximum possible. RH 100%.",
    difficulty: 2,
    source: TG("Atmospheric Moisture", ["2.222"]),
  },
  {
    id: "wq-wg-054",
    type: "mcq",
    unit: "w3",
    conceptIds: ["wx-saturation"],
    prompt: "Air can reach saturation by cooling, or by",
    options: [
      "compression",
      "evaporation adding moisture, which raises the dew point",
      "descending",
      "increasing the pressure",
    ],
    answer: 1,
    explanation:
      "Two routes. Cooling brings the temperature down to the dew point; evaporation brings the dew point up to the temperature. Either one closes the spread and drives the relative humidity toward 100%.",
    whyWrong:
      "Only one road to saturation is the usual assumption. Adding moisture works just as well as removing heat.",
    knowCold: "Cool it, or wet it. Either closes the spread.",
    difficulty: 3,
    source: TG("Atmospheric Moisture", ["2.222"]),
  },
];
