import type { Question, SourceReference } from "@/lib/types";

/**
 * The Weather Trainee Guide is the authority. The chapter label keeps the
 * condensed-notes block the wording came from; enabling objectives resolve
 * through each question's concepts.
 */
const NOTES = (chapter: string): SourceReference => ({
  document: "Weather Trainee Guide",
  chapter,
});

const THEORY = NOTES("WX 1: Theory");

/** Units w1–w3: the atmosphere, altitude, moisture and stability. */
export const W1_QUESTIONS: Question[] = [
  /* ================= w1 · the atmosphere ================= */
  {
    id: "wq-w1-001",
    type: "mcq",
    unit: "w1",
    conceptIds: ["wx-troposphere"],
    prompt: "Nearly all weather occurs in the",
    options: ["stratosphere", "troposphere", "tropopause", "mesosphere"],
    answer: 1,
    explanation:
      "The troposphere holds a large amount of moisture — 0 to 5% water vapour by volume — and that is where weather happens.",
    knowCold: "Weather lives in the troposphere.",
    difficulty: 1,
    source: THEORY,
  },
  {
    id: "wq-w1-002",
    type: "mcq",
    unit: "w1",
    conceptIds: ["wx-troposphere"],
    prompt: "Over the United States, the top of the troposphere averages about",
    options: ["18,000 ft MSL", "28,000 ft MSL", "36,000 ft MSL", "55,000 ft MSL"],
    answer: 2,
    explanation:
      "The troposphere's top runs 28,000 to 55,000 ft MSL worldwide, and averages about 36,000 ft MSL over the US.",
    whyWrong: "28,000 and 55,000 are the ends of the global range, not the US average.",
    knowCold: "28k–55k globally, ~36k over the US.",
    difficulty: 2,
    source: THEORY,
  },
  {
    id: "wq-w1-003",
    type: "mcq",
    unit: "w1",
    conceptIds: ["wx-troposphere"],
    prompt: "Within the troposphere, as altitude increases",
    options: [
      "temperature increases and wind decreases",
      "temperature decreases and wind increases",
      "both temperature and wind decrease",
      "both temperature and wind increase",
    ],
    answer: 1,
    explanation: "Temperature falls and wind strengthens with height through the troposphere.",
    knowCold: "Up: colder and windier.",
    difficulty: 2,
    source: THEORY,
  },
  {
    id: "wq-w1-004",
    type: "mcq",
    unit: "w1",
    conceptIds: ["wx-tropopause"],
    prompt: "The tropopause is best described as",
    options: [
      "the layer where temperature falls fastest",
      "the isothermal transition layer between the troposphere and stratosphere",
      "the top of the stratosphere",
      "the level at which all moisture freezes",
    ],
    answer: 1,
    explanation: "Isothermal means temperature stops falling and holds constant, which is what caps the troposphere: rising air loses its buoyancy there, so weather stops. It is also where the jet stream and its wind shear sit.",
    knowCold: "Tropopause: isothermal, constant temperature.",
    difficulty: 2,
    source: THEORY,
  },
  {
    id: "wq-w1-005",
    type: "spotTheTrap",
    unit: "w1",
    conceptIds: ["wx-tropopause"],
    prompt: '"Temperature continues to fall steadily as you climb through the tropopause."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. The tropopause is isothermal — the temperature holds constant through it. That is what makes it a transition layer rather than just more troposphere.",
    knowCold: "Isothermal = constant, not falling.",
    difficulty: 2,
    source: THEORY,
  },
  {
    id: "wq-w1-006",
    type: "mcq",
    unit: "w1",
    conceptIds: ["wx-heat-exchange"],
    prompt: "All weather is ultimately the result of",
    options: ["the earth's rotation", "heat exchange", "the jet stream", "moisture alone"],
    answer: 1,
    explanation:
      "Heating and cooling of the earth causes air circulation and pressure differentials. Every phenomenon in this course traces back to that.",
    knowCold: "All weather is heat exchange.",
    difficulty: 1,
    source: THEORY,
  },
  {
    id: "wcc-w1-007",
    type: "connectChain",
    unit: "w1",
    conceptIds: ["wx-heat-exchange", "wx-pgf"],
    prompt: "Trace the chain from sunlight to wind.",
    trigger: "The earth heats unevenly",
    steps: [
      "Air circulation and pressure differentials develop",
      "A pressure gradient exists between them",
      "Pressure Gradient Force acts",
      "Wind",
    ],
    explanation:
      "PGF is the initiating force for ALL winds. Nothing moves until a pressure difference exists.",
    knowCold: "Heat → pressure difference → PGF → wind.",
    difficulty: 2,
    source: THEORY,
  },
  {
    id: "wq-w1-008",
    type: "mcq",
    unit: "w1",
    conceptIds: ["wx-pgf"],
    prompt: "The pressure gradient is a rate of change measured",
    options: [
      "parallel to the isobars",
      "perpendicular to the isobars",
      "along the wind direction",
      "vertically through the atmosphere",
    ],
    answer: 1,
    explanation:
      "Perpendicular to the isobars — which is why closely spaced isobars mean a steep gradient and strong wind.",
    whyWrong:
      "Parallel to the isobars is the direction the GRADIENT WIND blows, not how the gradient is measured.",
    knowCold: "Gradient is measured across the isobars.",
    difficulty: 3,
    source: THEORY,
  },
  {
    id: "wq-w1-009",
    type: "mcq",
    unit: "w1",
    conceptIds: ["wx-pgf"],
    prompt: "The initiating force for all winds is",
    options: [
      "the Coriolis force",
      "surface friction",
      "the pressure gradient force",
      "thermal lifting",
    ],
    answer: 2,
    explanation: "PGF starts every wind. Everything else modifies what PGF began.",
    knowCold: "PGF starts it all.",
    difficulty: 1,
    source: THEORY,
  },
  {
    id: "wq-w1-010",
    type: "mcq",
    unit: "w1",
    conceptIds: ["wx-atmospheric-pressure"],
    prompt: "Atmospheric pressure is measured by",
    options: [
      "the temperature of the air at the surface",
      "the weight of a column of air above an area on the earth's surface",
      "the moisture content of the air",
      "the speed of the surface wind",
    ],
    answer: 1,
    explanation: "Pressure at a point is the WEIGHT of the air column standing above it, reported in inches of mercury or millibars. That is why climbing reduces it — you leave part of the column below you, at about 1 inHg per 1,000 ft.",
    knowCold: "The weight of the air column above you.",
    difficulty: 1,
    source: THEORY,
  },
  {
    id: "wq-w1-011",
    type: "mcq",
    unit: "w1",
    conceptIds: ["wx-standard-atmosphere", "wx-atmospheric-pressure"],
    prompt: "Standard sea level pressure and temperature are",
    options: [
      "29.92 inHg and 15 °C",
      "29.92 inHg and 15 °F",
      "28.92 inHg and 59 °C",
      "30.92 inHg and 15 °C",
    ],
    answer: 0,
    explanation: "29.92 inHg and 15 °C, which is 59 °F.",
    knowCold: "29.92 and 15 °C / 59 °F.",
    difficulty: 1,
    source: THEORY,
  },
  {
    id: "wq-w1-012",
    type: "mcq",
    unit: "w1",
    conceptIds: ["wx-standard-atmosphere"],
    prompt: "Standard sea level temperature expressed in Fahrenheit is",
    options: ["32 °F", "45 °F", "59 °F", "72 °F"],
    answer: 2,
    explanation: "59 °F, the same as 15 °C.",
    knowCold: "15 °C is 59 °F.",
    difficulty: 1,
    source: THEORY,
  },
  {
    id: "wq-w1-013",
    type: "mcq",
    unit: "w1",
    conceptIds: ["wx-lapse-rate"],
    prompt: "The average temperature lapse rate is",
    options: [
      "1 °C per 1,000 ft",
      "2 °C per 1,000 ft",
      "1 inHg per 1,000 ft",
      "3.57 °C per 1,000 ft",
    ],
    answer: 1,
    explanation:
      "2 °C per 1,000 ft for temperature. 1 inHg per 1,000 ft is the PRESSURE lapse rate — a different variable in a different unit.",
    whyWrong: "1 inHg per 1,000 ft is pressure, not temperature.",
    knowCold: "Temperature 2 °C, pressure 1 inHg, both per 1,000 ft.",
    difficulty: 2,
    source: THEORY,
  },
  {
    id: "wsl-w1-014",
    type: "sliderPredict",
    unit: "w1",
    conceptIds: ["wx-lapse-rate"],
    prompt:
      "Sea level is 15 °C and 29.92 inHg. Set the slider to 10,000 ft. What is the standard temperature there?",
    widget: "LapseRateWidget",
    options: ["+5 °C", "−5 °C", "−15 °C", "0 °C"],
    answer: 1,
    explanation:
      "2 °C per 1,000 ft over 10,000 ft is 20 °C of cooling. 15 − 20 = −5 °C. Pressure would be 29.92 − 10 = 19.92 inHg.",
    knowCold: "2 °C per 1,000 ft.",
    difficulty: 2,
    source: THEORY,
  },
  {
    id: "wq-w1-015",
    type: "mcq",
    unit: "w1",
    conceptIds: ["wx-lapse-rate", "wx-atmospheric-pressure"],
    prompt: "Climbing from sea level to 5,000 ft, standard pressure falls to approximately",
    options: ["19.92 inHg", "24.92 inHg", "27.92 inHg", "29.42 inHg"],
    answer: 1,
    explanation: "1 inHg per 1,000 ft, so 5,000 ft costs 5 inHg: 29.92 − 5 = 24.92 inHg.",
    knowCold: "1 inHg per 1,000 ft.",
    difficulty: 2,
    source: THEORY,
  },
  {
    id: "wq-w1-016",
    type: "mcq",
    unit: "w1",
    conceptIds: ["wx-slp-sp"],
    prompt: "For a station located above sea level, station pressure is always",
    options: [
      "greater than sea level pressure",
      "less than sea level pressure",
      "equal to sea level pressure",
      "equal to 29.92 inHg",
    ],
    answer: 1,
    explanation:
      "There is less air above the station than there is above sea level, so it weighs less.",
    knowCold: "Station above sea level → SP < SLP.",
    difficulty: 2,
    source: THEORY,
  },
  {
    id: "wq-w1-017",
    type: "mcq",
    unit: "w1",
    conceptIds: ["wx-slp-sp"],
    prompt: "The altimeter setting is",
    options: ["station pressure", "sea level pressure", "pressure altitude", "density altitude"],
    answer: 1,
    explanation:
      "Sea level pressure — either measured directly at sea level or calculated from a known station pressure.",
    knowCold: "The altimeter setting is SLP.",
    difficulty: 2,
    source: THEORY,
  },

  /* ================= w2 · altitude and the altimeter ================= */
  {
    id: "wq-w2-001",
    type: "mcq",
    unit: "w2",
    conceptIds: ["wx-true-altitude"],
    prompt: "True altitude is height above",
    options: ["the terrain", "mean sea level", "the standard datum plane", "the nearest airfield"],
    answer: 1,
    explanation: "Height above mean sea level. It is the standard altitude because charted terrain and obstacles are published in MSL, so it is the only one you can compare them against directly.",
    knowCold: "True = MSL.",
    difficulty: 1,
    source: THEORY,
  },
  {
    id: "wq-w2-002",
    type: "mcq",
    unit: "w2",
    conceptIds: ["wx-absolute-altitude"],
    prompt: "Absolute altitude is height above",
    options: ["mean sea level", "the terrain below you", "29.92 inHg", "the tropopause"],
    answer: 1,
    explanation: "Height above the terrain directly below — AGL. It changes as the ground rises and falls beneath an aircraft holding a constant MSL altitude, which is exactly why the two references are kept separate.",
    knowCold: "Absolute = AGL.",
    difficulty: 1,
    source: THEORY,
  },
  {
    id: "wq-w2-003",
    type: "mcq",
    unit: "w2",
    conceptIds: ["wx-pressure-altitude"],
    prompt: "Pressure altitude is displayed when the Kollsman window is set to",
    options: ["the local altimeter setting", "29.92", "the field elevation", "zero"],
    answer: 1,
    explanation:
      "It is height above the standard datum plane, and it is standard in Class A airspace.",
    knowCold: "Set 29.92 and you are reading pressure altitude.",
    difficulty: 2,
    source: THEORY,
  },
  {
    id: "wq-w2-004",
    type: "mcq",
    unit: "w2",
    conceptIds: ["wx-pressure-altitude"],
    prompt: "In which airspace is pressure altitude the standard?",
    options: ["Class B", "Class C", "Class A", "Class G"],
    answer: 2,
    explanation: "Class A, where everyone flies on 29.92 so that all aircraft share one reference.",
    knowCold: "Class A runs on 29.92.",
    difficulty: 2,
    source: THEORY,
  },
  {
    id: "wq-w2-005",
    type: "mcq",
    unit: "w2",
    conceptIds: ["wx-density-altitude"],
    prompt: "Density altitude is used to",
    options: [
      "determine terrain clearance",
      "gauge aircraft performance",
      "set the altimeter",
      "measure height above the standard datum plane",
    ],
    answer: 1,
    explanation:
      "It is a calculation of the altitude the airplane is effectively experiencing given the air density, which is what performance depends on.",
    whyWrong:
      "Density altitude is not a height. It is a performance figure expressed in the units of a height.",
    knowCold: "Density altitude is about performance, not position.",
    difficulty: 2,
    source: THEORY,
  },
  {
    id: "wq-w2-006",
    type: "mcq",
    unit: "w2",
    conceptIds: ["wx-indicated-altitude"],
    prompt: "Indicated altitude is",
    options: [
      "always exactly true altitude",
      "what the barometric altimeter indicates, attempting to be true altitude",
      "height above the terrain",
      "always higher than true altitude",
    ],
    answer: 1,
    explanation:
      "It attempts to be true altitude. Whether it succeeds depends on the setting and on the temperature.",
    knowCold: "Indicated is the attempt. True is the reality.",
    difficulty: 2,
    source: THEORY,
  },
  {
    id: "wq-w2-007",
    type: "mcq",
    unit: "w2",
    conceptIds: ["wx-altimeter"],
    prompt: "The altimeter is calibrated to display how much altitude per 1 inHg of difference?",
    options: ["100 ft", "500 ft", "1,000 ft", "2,000 ft"],
    answer: 2,
    explanation:
      "1,000 ft per 1 inHg. It measures the difference between static pressure and the sea level pressure set in the Kollsman window.",
    knowCold: "1 inHg = 1,000 ft.",
    difficulty: 2,
    source: THEORY,
  },
  {
    id: "wq-w2-008",
    type: "mcq",
    unit: "w2",
    conceptIds: ["wx-altimeter"],
    prompt: "The altimeter measures the difference between static pressure and",
    options: [
      "dynamic pressure",
      "the sea level pressure set in the Kollsman window",
      "standard temperature",
      "the pressure at the tropopause",
    ],
    answer: 1,
    explanation: "Which is why an incorrect setting produces a proportional indication error.",
    knowCold: "Static pressure versus the Kollsman setting.",
    difficulty: 2,
    source: THEORY,
  },
  {
    id: "wq-w2-009",
    type: "mcq",
    unit: "w2",
    conceptIds: ["wx-temp-altimeter-error"],
    prompt: "On a colder than standard day, the altimeter will indicate",
    options: [
      "lower than true altitude",
      "higher than true altitude",
      "exactly true altitude",
      "true altitude plus 1,000 ft regardless of conditions",
    ],
    answer: 1,
    explanation:
      "Colder than standard means the altimeter reads HIGH — so the aircraft is actually lower than the indication. That is the dangerous direction.",
    whyWrong:
      "Hotter than standard is the case where it indicates lower than true.",
    knowCold: "Cold → indicates high → you are LOWER than it says.",
    difficulty: 3,
    source: THEORY,
  },
  {
    id: "wq-w2-010",
    type: "spotTheTrap",
    unit: "w2",
    conceptIds: ["wx-temp-altimeter-error"],
    prompt:
      '"Temperature deviation affects the altimeter more noticeably than pressure changes do."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. Temperature effects are real but LESS noticeable than pressure changes, which is exactly what the notes say.",
    knowCold: "Temperature matters less than pressure here.",
    difficulty: 3,
    source: THEORY,
  },
  {
    id: "wtap-w2-011",
    type: "tapDiagram",
    unit: "w2",
    conceptIds: ["wx-absolute-altitude"],
    prompt: "Tap the measurement that represents ABSOLUTE altitude.",
    diagram: { id: "wx-altitude-types", props: { highlight: "none", labels: false } },
    targets: [
      { id: "true", label: "True — MSL", x: 150, y: 162, r: 30 },
      { id: "absolute", label: "Absolute — AGL", x: 252, y: 137, r: 30 },
      { id: "pressure", label: "Pressure — from 29.92", x: 372, y: 151, r: 30 },
    ],
    answer: "absolute",
    explanation:
      "Absolute altitude is measured from the aircraft down to the TERRAIN, which is the shorter measurement over rising ground.",
    knowCold: "Absolute stops at the terrain.",
    difficulty: 2,
    source: THEORY,
  },

  /* ================= w3 · moisture and stability ================= */
  {
    id: "wq-w3-001",
    type: "mcq",
    unit: "w3",
    conceptIds: ["wx-dew-point"],
    prompt: "Dew point is the temperature an air parcel must be cooled to",
    options: [
      "at constant volume, to freeze",
      "at constant pressure, to condense into water",
      "at any pressure, to evaporate",
      "at constant temperature, to saturate",
    ],
    answer: 1,
    explanation: "Cool an air parcel at constant pressure and it eventually saturates and condenses; that temperature is the dew point. The closer it sits to the actual temperature, the closer the air is to producing cloud, fog or precipitation.",
    knowCold: "Cool at constant pressure until it condenses.",
    difficulty: 2,
    source: THEORY,
  },
  {
    id: "wq-w3-002",
    type: "mcq",
    unit: "w3",
    conceptIds: ["wx-dew-point-spread"],
    prompt: "As the dew point depression gets SMALLER,",
    options: [
      "less moisture will condense",
      "more moisture will condense",
      "the air becomes drier",
      "nothing changes until the spread reaches zero",
    ],
    answer: 1,
    explanation:
      "A small spread means the air is close to saturation, so more moisture condenses. It is the single most useful number on a METAR for predicting fog.",
    knowCold: "Smaller spread → more condensation.",
    difficulty: 2,
    source: THEORY,
  },
  {
    id: "wsl-w3-003",
    type: "sliderPredict",
    unit: "w3",
    conceptIds: ["wx-dew-point-spread", "wx-relative-humidity"],
    prompt: "Close the spread toward zero. What happens as it approaches saturation?",
    widget: "DewPointWidget",
    options: [
      "Relative humidity falls and the air dries out",
      "Relative humidity rises toward 100% and moisture condenses",
      "Temperature rises",
      "Nothing changes until the spread is negative",
    ],
    answer: 1,
    explanation:
      "Relative humidity is the same idea as the spread expressed as a percentage — it is percent saturation.",
    knowCold: "Spread to zero = 100% relative humidity.",
    difficulty: 2,
    source: THEORY,
  },
  {
    id: "wq-w3-004",
    type: "mcq",
    unit: "w3",
    conceptIds: ["wx-relative-humidity"],
    prompt: "Relative humidity is the ratio of",
    options: [
      "dew point to temperature",
      "the actual moisture in the air to the maximum that could be in the air",
      "water vapour to dry air by weight",
      "condensed moisture to total precipitation",
    ],
    answer: 1,
    explanation: "Actual moisture over the maximum the air could hold. The maximum rises with temperature, so relative humidity can climb overnight with no new moisture arriving at all — purely because the air cooled toward its dew point.",
    knowCold: "Relative humidity is percent saturation.",
    difficulty: 1,
    source: THEORY,
  },
  {
    id: "wq-w3-005",
    type: "mcq",
    unit: "w3",
    conceptIds: ["wx-air-mass"],
    prompt: "An air mass is a large body of air with relatively the same",
    options: [
      "pressure and density across a vertical plane",
      "temperature and moisture across a horizontal plane",
      "wind speed and direction throughout",
      "cloud cover at all altitudes",
    ],
    answer: 1,
    explanation: "Uniform temperature and moisture across a HORIZONTAL plane. That uniformity is what makes an air mass behave as one body with predictable weather — and what makes the boundary between two of them, a front, so abrupt.",
    knowCold: "Same temperature and moisture, horizontally.",
    difficulty: 2,
    source: THEORY,
  },
  {
    id: "wq-w3-006",
    type: "mcq",
    unit: "w3",
    conceptIds: ["wx-air-mass", "wx-air-stability"],
    prompt: "A WARM air mass is",
    options: ["stable", "unstable", "neutral", "unstable only over water"],
    answer: 0,
    explanation:
      "Warm air masses are stable and cold air masses are unstable. That single line drives most of what follows in this course.",
    whyWrong:
      "It feels backwards because warm air rises — but stability is about the parcel relative to its SURROUNDINGS.",
    knowCold: "Warm mass stable, cold mass unstable.",
    difficulty: 3,
    source: THEORY,
  },
  {
    id: "wq-w3-007",
    type: "mcq",
    unit: "w3",
    conceptIds: ["wx-air-stability"],
    prompt: "The stability of air is determined by",
    options: [
      "its absolute temperature",
      "the temperature of the surrounding air",
      "its moisture content",
      "the altitude at which it sits",
    ],
    answer: 1,
    explanation:
      "Stable when cold relative to the surroundings, unstable when hot, neutral when the same.",
    knowCold: "Stability is always relative to the surroundings.",
    difficulty: 2,
    source: NOTES("WX 2: Mechanics"),
  },
  {
    id: "wbf-w3-008",
    type: "beforeAfter",
    unit: "w3",
    conceptIds: ["wx-air-stability"],
    prompt: "A parcel is warmer than the air around it. What does it do?",
    diagram: { id: "wx-stability" },
    states: ["Neutral", "Unstable"],
    beforeProps: { state: "neutral" },
    afterProps: { state: "unstable" },
    rows: [
      {
        label: "Parcel temperature relative to its surroundings",
        options: ["Colder", "The same", "Hotter"],
        answer: 2,
      },
      { label: "Parcel density relative to its surroundings", options: ["Higher", "The same", "Lower"], answer: 2 },
      { label: "What the parcel does", options: ["Sinks", "Stays put", "Rises"], answer: 2 },
      { label: "Classification", options: ["Stable", "Neutral", "Unstable"], answer: 2 },
    ],
    explanation:
      "Hot means unstable: the parcel is less dense than what surrounds it, so it keeps going up.",
    knowCold: "Hot → unstable → rises.",
    difficulty: 2,
    source: NOTES("WX 2: Mechanics"),
  },
  {
    id: "wq-w3-009",
    type: "mcq",
    unit: "w3",
    conceptIds: ["wx-inversion"],
    prompt: "A temperature inversion exists when",
    options: [
      "temperature decreases as altitude increases",
      "temperature increases as altitude increases",
      "temperature stays constant with altitude",
      "dew point exceeds temperature",
    ],
    answer: 1,
    explanation:
      "The normal state is temperature falling with height, so an inversion is that relationship turned upside down.",
    knowCold: "Inversion: warmer as you climb.",
    difficulty: 1,
    source: THEORY,
  },
  {
    id: "wq-w3-010",
    type: "mcq",
    unit: "w3",
    conceptIds: ["wx-inversion", "wx-wind-shear"],
    prompt: "A temperature inversion is associated with which hazard?",
    options: [
      "Clear ice",
      "Low level wind shear",
      "Orographic lifting",
      "Convective SIGMETs",
    ],
    answer: 1,
    explanation:
      "The high speed warm air wind that causes the inversion generates large wind shear at the inversion boundary. LLWS from an inversion typically occurs near the surface on cool, clear nights.",
    knowCold: "Inversion boundary = wind shear.",
    difficulty: 3,
    source: NOTES("WX 3: Hazards"),
  },
];
