import type { Question, SourceReference } from "@/lib/types";

/**
 * The Weather Trainee Guide is the authority. The chapter label keeps the
 * condensed-notes block the wording came from; enabling objectives resolve
 * through each question's concepts.
 */
const NOTES = (chapter: string): SourceReference => ({
  document: "Weather Trainee Guide",
  chapter,
});
const DUMP: SourceReference = {
  document: "Weather Dump Sheet",
  chapter: "Mnemonics",
};

const HAZ = NOTES("WX 3: Hazards");

/** Units w7–w9: turbulence, icing, storms and low visibility. */
export const W7_QUESTIONS: Question[] = [
  /* ================= w7 · turbulence and wind shear ================= */
  {
    id: "wq-w7-001",
    type: "mcq",
    unit: "w7",
    conceptIds: ["wx-turbulence"],
    prompt: "Turbulence is most hazardous at",
    options: ["high altitude", "low altitude", "the tropopause", "cruise altitude"],
    answer: 1,
    explanation:
      "Low altitude, because there is neither height nor airspeed in reserve to absorb an upset.",
    knowCold: "Low altitude is where turbulence hurts.",
    difficulty: 2,
    source: HAZ,
  },
  {
    id: "wq-w7-002",
    type: "mcq",
    unit: "w7",
    conceptIds: ["wx-turbulence"],
    prompt: "Turbulence is defined as",
    options: [
      "any wind exceeding 30 kt",
      "irregular or disturbed atmospheric flow producing gusts and/or eddies",
      "a sudden change in wind direction only",
      "vertical air movement inside a cloud",
    ],
    answer: 1,
    explanation: "Gusts and eddies, from flow that is irregular or disturbed.",
    knowCold: "Disturbed flow: gusts and eddies.",
    difficulty: 1,
    source: HAZ,
  },
  {
    id: "wq-w7-003",
    type: "mcq",
    unit: "w7",
    conceptIds: ["wx-turbulence-intensity"],
    prompt: "Which turbulence intensity requires declaring an emergency and exiting the area ASAP?",
    options: ["Light", "Moderate", "Severe", "Extreme"],
    answer: 3,
    explanation: "Extreme. The intensity classifications are light, moderate, severe and extreme.",
    knowCold: "Extreme → declare an emergency, get out.",
    difficulty: 2,
    source: HAZ,
  },
  {
    id: "wq-w7-004",
    type: "mcq",
    unit: "w7",
    conceptIds: ["wx-turbulence-duration"],
    prompt: "Turbulence occupying between one third and two thirds of the time is reported as",
    options: ["occasional", "intermittent", "continuous", "sustained"],
    answer: 1,
    explanation:
      "Occasional is less than one third, intermittent is one third to two thirds, and continuous is more than two thirds.",
    knowCold: "Occasional < ⅓ · Intermittent ⅓–⅔ · Continuous > ⅔.",
    difficulty: 3,
    source: HAZ,
  },
  {
    id: "wq-w7-005",
    type: "mcq",
    unit: "w7",
    conceptIds: ["wx-turbulence-duration"],
    prompt: "Turbulence present more than two thirds of the time is",
    options: ["occasional", "intermittent", "continuous", "extreme"],
    answer: 2,
    explanation:
      "Continuous. Note that duration and intensity are separate scales — continuous light turbulence is a perfectly ordinary report.",
    whyWrong: "Extreme is an INTENSITY, not a duration.",
    knowCold: "Duration and intensity are two different scales.",
    difficulty: 2,
    source: HAZ,
  },
  {
    id: "wq-w7-006",
    type: "mcq",
    unit: "w7",
    conceptIds: ["wx-turbulence-causes"],
    prompt: "The four turbulence causative factors are",
    options: [
      "Wind shear, Thermal, Frontal, Mechanical",
      "Wind shear, Thermal, Frontal, Convective",
      "Wake, Thermal, Frontal, Mechanical",
      "Wind shear, Terrain, Frontal, Mechanical",
    ],
    answer: 0,
    explanation: "Large scale wind shear, thermal, frontal and mechanical.",
    knowCold: "Wind shear · Thermal · Frontal · Mechanical.",
    difficulty: 2,
    source: HAZ,
  },
  {
    id: "wq-w7-007",
    type: "mcq",
    unit: "w7",
    conceptIds: ["wx-wind-shear"],
    prompt: "Low level wind shear is the most dangerous form because of",
    options: [
      "the risk of structural failure",
      "the risk of stall at low altitude",
      "its association with hail",
      "the loss of radio contact",
    ],
    answer: 1,
    explanation:
      "A stall near the surface leaves no altitude in which to recover. LLWS is due to local phenomena such as a temperature inversion, and occurs near the surface on cool, clear nights.",
    knowCold: "LLWS: stall risk with nowhere to go.",
    difficulty: 2,
    source: HAZ,
  },
  {
    id: "wq-w7-008",
    type: "mcq",
    unit: "w7",
    conceptIds: ["wx-wind-shear"],
    prompt: "High level wind shear is associated with",
    options: [
      "temperature inversions near the surface",
      "clear air turbulence, such as the jet stream",
      "mechanical obstructions",
      "thermal heating from below",
    ],
    answer: 1,
    explanation:
      "Large fluctuations in wind intensity throughout the jet stream create a high degree of wind shear.",
    knowCold: "High level shear = clear air turbulence.",
    difficulty: 2,
    source: HAZ,
  },
  {
    id: "wq-w7-009",
    type: "mcq",
    unit: "w7",
    conceptIds: ["wx-shear-sources"],
    prompt: "Wind shear at a temperature inversion boundary is generated by",
    options: [
      "the cold air sinking below the inversion",
      "the high speed warm air wind that causes the inversion",
      "mechanical mixing from terrain",
      "convergence at the surface",
    ],
    answer: 1,
    explanation:
      "The inversion and the shear share a cause: the fast warm air moving over the top.",
    knowCold: "The wind that makes the inversion makes the shear.",
    difficulty: 3,
    source: HAZ,
  },
  {
    id: "wq-w7-010",
    type: "mcq",
    unit: "w7",
    conceptIds: ["wx-thermal-turbulence"],
    prompt: "Thermal turbulence is generally strongest over",
    options: ["water", "wet ground", "dry surfaces", "forested terrain"],
    answer: 2,
    explanation:
      "Thermal turbulence results from heating below, and its strength depends on the surface being heated. Generally, the drier the surface, the stronger the turbulence.",
    knowCold: "Drier surface, stronger thermals.",
    difficulty: 2,
    source: HAZ,
  },
  {
    id: "wq-w7-011",
    type: "spotTheTrap",
    unit: "w7",
    conceptIds: ["wx-frontal-turbulence"],
    prompt: '"Warm fronts produce frontal turbulence, though less than cold fronts do."',
    options: ["True", "False"],
    answer: 1,
    explanation:
      "False. There is little or no lifting with warm fronts, so there is NO warm frontal turbulence at all. Frontal turbulence is a cold front phenomenon, and it is more prominent in a fast cold front.",
    knowCold: "No warm frontal turbulence. None.",
    difficulty: 3,
    source: HAZ,
  },
  {
    id: "wq-w7-012",
    type: "mcq",
    unit: "w7",
    conceptIds: ["wx-frontal-turbulence"],
    prompt: "Frontal turbulence is most prominent with",
    options: ["a slow warm front", "a fast cold front", "a stationary front", "an occluded front"],
    answer: 1,
    explanation: "Faster cold front, steeper lifting, more turbulence.",
    knowCold: "Fast cold front is the worst case.",
    difficulty: 2,
    source: HAZ,
  },
  {
    id: "wq-w7-013",
    type: "mcq",
    unit: "w7",
    conceptIds: ["wx-mechanical-turbulence"],
    prompt: "Mechanical turbulence usually occurs below",
    options: ["500 ft AGL", "1,000 ft AGL", "2,000 ft AGL", "5,000 ft AGL"],
    answer: 1,
    explanation:
      "Below 1,000 ft AGL, where buildings, ground objects, hills and valleys interfere with the normal wind flow.",
    knowCold: "Mechanical: usually below 1,000 ft AGL.",
    difficulty: 2,
    source: HAZ,
  },
  {
    id: "wq-w7-014",
    type: "mcq",
    unit: "w7",
    conceptIds: ["wx-mechanical-turbulence"],
    prompt: "Mechanical turbulence increases with all of the following EXCEPT",
    options: ["rougher terrain", "faster wind", "more unstable air", "higher altitude"],
    answer: 3,
    explanation:
      "Rougher terrain, faster wind and more unstable air all make it worse. Altitude takes you away from the obstructions causing it.",
    knowCold: "Rougher, faster, more unstable — all worse.",
    difficulty: 2,
    source: HAZ,
  },
  {
    id: "wq-w7-015",
    type: "mcq",
    unit: "w7",
    conceptIds: ["wx-turbulence-technique"],
    prompt: "In turbulence penetration, altitude deviations should be",
    options: [
      "corrected immediately with power",
      "allowed to vary — do not chase the altimeter",
      "corrected with large pitch inputs",
      "reported to ATC before any correction",
    ],
    answer: 1,
    explanation:
      "Allow altitude to vary and do not chase the altimeter. Likewise, do not chase airspeed deviations with power corrections.",
    knowCold: "Let altitude and airspeed wander.",
    difficulty: 2,
    source: HAZ,
  },
  {
    id: "wq-w7-016",
    type: "mcq",
    unit: "w7",
    conceptIds: ["wx-turbulence-technique"],
    prompt: "During turbulence penetration, pitch and bank are maintained by reference to",
    options: [
      "the altimeter",
      "the airspeed indicator",
      "the attitude indicator",
      "the vertical speed indicator",
    ],
    answer: 2,
    explanation:
      "The attitude indicator, with a VFR scan when conditions permit. Keep a level attitude and let the other needles move.",
    knowCold: "Fly the attitude indicator.",
    difficulty: 2,
    source: HAZ,
  },

  {
    id: "wq-w7-017",
    type: "mcq",
    unit: "w7",
    conceptIds: ["wx-turbulence-technique"],
    prompt:
      "In turbulence, airspeed begins fluctuating either side of the penetration speed. You should",
    options: [
      "correct each deviation promptly with power",
      "leave the power set and let the airspeed vary",
      "reduce to the minimum controllable airspeed",
      "increase power to restore the target airspeed",
    ],
    answer: 1,
    explanation:
      "Maintain the power setting consistent with the recommended turbulence penetration airspeed, and do not chase airspeed deviations with power corrections.",
    whyWrong:
      "Chasing the airspeed with power is what turns turbulence into an upset — the corrections arrive out of phase with the gusts.",
    knowCold: "Set the power and leave it.",
    difficulty: 2,
    source: HAZ,
  },

  /* ================= w8 · icing ================= */
  {
    id: "wq-w8-001",
    type: "mcq",
    unit: "w8",
    conceptIds: ["wx-icing-requirements"],
    prompt: "Icing requires all of the following EXCEPT",
    options: [
      "visible moisture",
      "free air temperature below freezing",
      "aircraft surface temperature below freezing",
      "precipitation reaching the ground",
    ],
    answer: 3,
    explanation:
      "Three conditions: visible moisture, free air temperature below freezing, and aircraft surface below freezing. Remove any one and ice cannot form.",
    knowCold: "Visible moisture + FAT below freezing + surface below freezing.",
    difficulty: 2,
    source: HAZ,
  },
  {
    id: "wq-w8-002",
    type: "mcq",
    unit: "w8",
    conceptIds: ["wx-icing-requirements"],
    prompt: "Flying in clear air at −15 °C, structural icing",
    options: [
      "will form rapidly",
      "cannot form, because there is no visible moisture",
      "will form as rime ice only",
      "will form only above 10,000 ft",
    ],
    answer: 1,
    explanation: "All three conditions are required. Without visible moisture there is nothing to freeze.",
    knowCold: "No visible moisture, no structural ice.",
    difficulty: 2,
    source: HAZ,
  },
  {
    id: "wq-w8-003",
    type: "mcq",
    unit: "w8",
    conceptIds: ["wx-structural-icing"],
    prompt: "The most hazardous aspect of structural icing is",
    options: [
      "the added weight",
      "the aerodynamic effect on the airfoil",
      "pitot tube blockage",
      "vibration in the flight controls",
    ],
    answer: 1,
    explanation:
      "The aerodynamic effect on the airfoil is named as the most hazardous aspect. The structural concerns — flight controls, vibration, pitot blockage, panels freezing over — are real but secondary.",
    whyWrong: "Weight is one of the performance penalties, not the primary hazard.",
    knowCold: "The shape of the wing is what kills you.",
    difficulty: 3,
    source: HAZ,
  },
  {
    id: "wq-w8-004",
    type: "mcq",
    unit: "w8",
    conceptIds: ["wx-clear-ice"],
    prompt: "Clear ice forms in the temperature range",
    options: ["0 to −10 °C", "−10 to −20 °C", "−8 to −15 °C", "below −20 °C"],
    answer: 0,
    explanation:
      "0 to −10 °C, in unstable conditions, from freezing rain and large droplets in cumulus clouds. It is the most severe type and difficult to remove.",
    knowCold: "Clear: 0 to −10.",
    difficulty: 2,
    source: HAZ,
  },
  {
    id: "wq-w8-005",
    type: "mcq",
    unit: "w8",
    conceptIds: ["wx-clear-ice"],
    prompt: "Clear ice alters the shape of the wing because it",
    options: [
      "freezes instantly on contact",
      "freezes slowly after spreading out",
      "accumulates only on the leading edge",
      "melts and refreezes repeatedly",
    ],
    answer: 1,
    explanation:
      "Large droplets spread across the surface before freezing, so the ice takes a shape the airfoil was never designed for. Rime is the one that freezes instantly.",
    knowCold: "Clear spreads then freezes. Rime freezes on contact.",
    difficulty: 3,
    source: HAZ,
  },
  {
    id: "wq-w8-006",
    type: "mcq",
    unit: "w8",
    conceptIds: ["wx-rime-ice"],
    prompt: "Rime ice is associated with",
    options: [
      "unstable conditions and cumulus clouds",
      "stable conditions and stratus clouds",
      "freezing rain",
      "temperatures above freezing",
    ],
    answer: 1,
    explanation:
      "−10 to −20 °C, stable conditions, stratus clouds, tiny droplets that freeze instantly.",
    knowCold: "Rime: stable, stratus, tiny droplets.",
    difficulty: 2,
    source: HAZ,
  },
  {
    id: "wq-w8-007",
    type: "mcq",
    unit: "w8",
    conceptIds: ["wx-rime-ice", "wx-clear-ice"],
    prompt: "Which ice type is described as the most severe and most difficult to remove?",
    options: ["Rime", "Clear", "Mixed", "Frost"],
    answer: 1,
    explanation: "Clear ice. Its slow spreading freeze is what makes it both severe and stubborn.",
    knowCold: "Clear ice is the bad one.",
    difficulty: 2,
    source: HAZ,
  },
  {
    id: "wq-w8-008",
    type: "mcq",
    unit: "w8",
    conceptIds: ["wx-mixed-ice"],
    prompt: "Mixed ice forms in the range",
    options: ["0 to −10 °C", "−10 to −20 °C", "−8 to −15 °C", "−20 to −30 °C"],
    answer: 2,
    explanation:
      "−8 to −15 °C, which OVERLAPS both the clear and the rime bands. It is a combination of the two.",
    whyWrong:
      "Mixed is not a gap between clear and rime — its band sits across the boundary between them.",
    knowCold: "Mixed: −8 to −15, overlapping both.",
    difficulty: 3,
    source: HAZ,
  },
  {
    id: "wsl-w8-009",
    type: "sliderPredict",
    unit: "w8",
    conceptIds: ["wx-clear-ice", "wx-rime-ice", "wx-mixed-ice"],
    prompt: "Set the free air temperature to −16 °C. Which ice type would you expect?",
    widget: "IcingWidget",
    options: ["Clear", "Rime", "Mixed only", "None can form"],
    answer: 1,
    explanation:
      "−16 °C sits inside the rime band of −10 to −20 °C, and beyond the mixed band which stops at −15 °C.",
    knowCold: "−10 to −20 is rime country.",
    difficulty: 3,
    source: HAZ,
  },
  {
    id: "wq-w8-010",
    type: "mcq",
    unit: "w8",
    conceptIds: ["wx-frost"],
    prompt: "Frost is",
    options: [
      "in-flight icing above 10,000 ft",
      "ground icing, which SHALL be removed prior to flight",
      "a mild form of rime ice",
      "harmless if thin",
    ],
    answer: 1,
    explanation:
      "Ground icing. It shall be removed prior to flight, and you must NOT scrape it off the aircraft, especially the windshield.",
    knowCold: "Frost is ground icing. Remove it, do not scrape it.",
    difficulty: 2,
    source: HAZ,
  },
  {
    id: "wq-w8-011",
    type: "mcq",
    unit: "w8",
    conceptIds: ["wx-engine-icing"],
    prompt: "Compressor icing forms on the",
    options: [
      "air intake and in carburettors",
      "compressor inlet screen and inlet guide vanes",
      "turbine blades",
      "exhaust nozzle",
    ],
    answer: 1,
    explanation:
      "Restricting airflow into the inlet. Induction icing is the one that forms on the air intake and in carburettors.",
    knowCold: "Compressor: inlet screen and guide vanes.",
    difficulty: 3,
    source: HAZ,
  },
  {
    id: "wq-w8-012",
    type: "mcq",
    unit: "w8",
    conceptIds: ["wx-engine-icing"],
    prompt: "Induction icing can occur in high humidity at temperatures up to",
    options: ["0 °C", "+5 °C", "+10 °C", "+15 °C"],
    answer: 2,
    explanation:
      "Up to +10 °C — well above freezing. It reduces engine pressure and can result in ice ingestion, which is FOD.",
    whyWrong:
      "Assuming icing needs sub-freezing air is exactly the trap. Induction icing does not.",
    knowCold: "Induction icing up to +10 °C.",
    difficulty: 3,
    source: HAZ,
  },
  {
    id: "wq-w8-013",
    type: "mcq",
    unit: "w8",
    conceptIds: ["wx-icing-effects"],
    prompt: "Which set of changes correctly describes the effects of icing?",
    options: [
      "Drag up, weight up, stall speed up, thrust down",
      "Drag up, weight down, stall speed down, thrust up",
      "Drag down, weight up, lift up, range up",
      "Drag up, weight up, lift up, range up",
    ],
    answer: 0,
    explanation:
      "Drag, weight, stall speed and fuel consumption all increase. Thrust, range and lift all decrease. Every number moves the wrong way.",
    knowCold: "↑ drag, weight, stall speed, fuel · ↓ thrust, range, lift.",
    difficulty: 2,
    source: HAZ,
  },
  {
    id: "wq-w8-014",
    type: "mcq",
    unit: "w8",
    conceptIds: ["wx-icing-response"],
    prompt: "The difference between de-icing and anti-icing equipment is that",
    options: [
      "de-icing prevents accumulation; anti-icing removes ice",
      "de-icing removes ice that is present; anti-icing prevents accumulation",
      "they are two names for the same system",
      "de-icing works only on the ground",
    ],
    answer: 1,
    explanation: "De-ice removes what is there. Anti-ice stops it arriving.",
    knowCold: "De-ice removes. Anti-ice prevents.",
    difficulty: 2,
    source: HAZ,
  },
  {
    id: "wq-w8-015",
    type: "mcq",
    unit: "w8",
    conceptIds: ["wx-icing-response"],
    prompt: "To escape icing by CLIMBING, you would climb to air colder than",
    options: ["0 °C", "−10 °C", "−20 °C", "−40 °C"],
    answer: 2,
    explanation:
      "Colder than −20 °C. The alternatives are to descend to warmer temperatures, get out of visible moisture, or land in an emergency — and to minimise manoeuvring throughout, because performance has decreased.",
    knowCold: "Climb past −20 °C, or descend to warmer air.",
    difficulty: 3,
    source: HAZ,
  },

  /* ================= w9 · storms and low visibility ================= */
  {
    id: "wq-w9-001",
    type: "mcq",
    unit: "w9",
    conceptIds: ["wx-thunderstorm-hazards"],
    prompt: "Which of the following is a thunderstorm hazard?",
    options: ["Frost", "Hail", "Radiation fog", "Orographic lifting"],
    answer: 1,
    explanation:
      "HI MELT: Hail, Icing, Microbursts, Extreme turbulence, Lightning, Tornados.",
    knowCold: "Hail, Icing, Microbursts, Extreme turbulence, Lightning, Tornados.",
    difficulty: 1,
    source: HAZ,
  },
  {
    id: "wq-w9-002",
    type: "mcq",
    unit: "w9",
    conceptIds: ["wx-thunderstorm-hazards"],
    prompt: "How many hazards does the thunderstorm mnemonic list?",
    options: ["Four", "Five", "Six", "Seven"],
    answer: 2,
    explanation: "Six: hail, icing, microbursts, extreme turbulence, lightning and tornados.",
    knowCold: "Six hazards.",
    difficulty: 2,
    source: DUMP,
  },
  {
    id: "wq-w9-003",
    type: "mcq",
    unit: "w9",
    conceptIds: ["wx-thunderstorm-avoidance"],
    prompt: "The FIRST priority for dealing with a thunderstorm is to",
    options: ["fly over it", "fly under it", "circumnavigate it", "penetrate the lower third"],
    answer: 2,
    explanation:
      "Circumnavigate, Over, Under, Through — and the order IS the priority. Flying around it is always the first choice.",
    knowCold: "Circumnavigate first. Always.",
    difficulty: 2,
    source: HAZ,
  },
  {
    id: "wq-w9-004",
    type: "mcq",
    unit: "w9",
    conceptIds: ["wx-thunderstorm-avoidance"],
    prompt:
      "Flying OVER a thunderstorm requires how much clearance above the top for each 10 kt of wind at the top?",
    options: ["500 ft", "1,000 ft", "2,000 ft", "5,000 ft"],
    answer: 1,
    explanation:
      "1,000 ft per 10 kt of wind at the top — which is why going over is rarely practical over a tall storm in a strong wind.",
    knowCold: "1,000 ft per 10 kt at the top.",
    difficulty: 3,
    source: HAZ,
  },
  {
    id: "wq-w9-005",
    type: "mcq",
    unit: "w9",
    conceptIds: ["wx-thunderstorm-avoidance"],
    prompt: "If you must penetrate a thunderstorm, you should fly through",
    options: [
      "the upper third, at a shallow angle",
      "the middle, perpendicular to the line",
      "the lower third, with no angle",
      "the anvil",
    ],
    answer: 2,
    explanation: "The lower third of the storm, with no angle. It is the last resort of four.",
    knowCold: "Lower third, no angle.",
    difficulty: 3,
    source: HAZ,
  },
  {
    id: "wcc-w9-006",
    type: "connectChain",
    unit: "w9",
    conceptIds: ["wx-thunderstorm-avoidance"],
    prompt: "Order the thunderstorm options from first choice to last.",
    trigger: "A thunderstorm is on your route",
    steps: ["Circumnavigate", "Over", "Under", "Through"],
    explanation: "COUT — Circumnavigate, Over, Under, Through — and it is a priority order, not a list. Going around is always first choice; through is last because it is the only option that puts you inside the hazards.",
    knowCold: "Circumnavigate, Over, Under, Through.",
    difficulty: 2,
    source: DUMP,
  },
  {
    id: "wq-w9-007",
    type: "mcq",
    unit: "w9",
    conceptIds: ["wx-microburst"],
    prompt: "A microburst downdraft is typically",
    options: ["200–600 ft per minute", "2,000–6,000 ft per minute", "20–60 ft per minute", "over 10,000 ft per minute"],
    answer: 1,
    explanation:
      "2,000–6,000 fpm, producing a vortex ring of wind of 20–200 kt, and usually lasting only 5–10 minutes.",
    knowCold: "2,000–6,000 fpm down.",
    difficulty: 2,
    source: HAZ,
  },
  {
    id: "wq-w9-008",
    type: "mcq",
    unit: "w9",
    conceptIds: ["wx-microburst"],
    prompt: "Which of the following is a visual cue of a microburst?",
    options: ["Lenticular cloud", "Virga", "Contrails", "Halo around the sun"],
    answer: 1,
    explanation: "Virga, localised blowing dust, rain shafts and roll clouds.",
    knowCold: "Virga, blowing dust, rain shafts, roll clouds.",
    difficulty: 2,
    source: HAZ,
  },
  {
    id: "wq-w9-009",
    type: "mcq",
    unit: "w9",
    conceptIds: ["wx-microburst"],
    prompt: "The severe hazard on takeoff and landing from a microburst comes from",
    options: [
      "the gradual increase in airspeed",
      "the sudden loss of airspeed on the far side",
      "hail",
      "reduced visibility",
    ],
    answer: 1,
    explanation:
      "Entering the outflow gives an initial performance INCREASE. Passing through, the headwind becomes a tailwind and airspeed drops suddenly.",
    knowCold: "It feels good on the way in and kills you on the way out.",
    difficulty: 3,
    source: HAZ,
  },
  {
    id: "wq-w9-010",
    type: "mcq",
    unit: "w9",
    conceptIds: ["wx-microburst"],
    prompt: "A microburst usually lasts",
    options: ["1–2 minutes", "5–10 minutes", "30–60 minutes", "several hours"],
    answer: 1,
    explanation: "Only 5–10 minutes, and very localised — which is what makes it so dangerous. It is too short-lived to forecast usefully and too small to show on most products, so it is met without warning on approach or departure.",
    knowCold: "5–10 minutes, very localised.",
    difficulty: 2,
    source: HAZ,
  },
  {
    id: "wq-w9-011",
    type: "mcq",
    unit: "w9",
    conceptIds: ["wx-obscuring-phenomenon"],
    prompt: "An obscuring phenomenon reduces horizontal visibility to less than",
    options: ["3 SM", "5 SM", "7 SM", "10 SM"],
    answer: 2,
    explanation: "Less than 7 statute miles of horizontal visibility. That threshold is the point at which the phenomenon must be reported, whatever is causing it — fog, haze, smoke, dust or precipitation.",
    knowCold: "Obscuring phenomenon: below 7 SM.",
    difficulty: 2,
    source: HAZ,
  },
  {
    id: "wq-w9-012",
    type: "mcq",
    unit: "w9",
    conceptIds: ["wx-fog"],
    prompt: "Fog exists when the cloud base is within how far of the ground?",
    options: ["20 ft", "50 ft", "100 ft", "200 ft"],
    answer: 1,
    explanation:
      "Within 50 ft of the ground, greater than 20 ft thick, and visibility less than ⅝ SM.",
    whyWrong: "20 ft is the minimum THICKNESS, not the height of the base.",
    knowCold: "Base within 50 ft, more than 20 ft thick, below ⅝ SM.",
    difficulty: 3,
    source: HAZ,
  },
  {
    id: "wq-w9-013",
    type: "mcq",
    unit: "w9",
    conceptIds: ["wx-fog"],
    prompt: "Fog requires condensation nuclei, a low temperature/dew point spread, and",
    options: ["calm winds", "light surface winds", "strong surface winds", "no wind at all"],
    answer: 1,
    explanation:
      "LIGHT surface winds — enough to mix the moisture through the layer, but not enough to disperse it.",
    knowCold: "Light winds, not calm and not strong.",
    difficulty: 3,
    source: HAZ,
  },
  {
    id: "wq-w9-014",
    type: "mcq",
    unit: "w9",
    conceptIds: ["wx-fog"],
    prompt: "Fog requires visibility to be less than",
    options: ["⅜ SM", "⅝ SM", "1 SM", "3 SM"],
    answer: 1,
    explanation: "⅝ SM, alongside the 50 ft base and 20 ft thickness criteria.",
    knowCold: "⅝ SM.",
    difficulty: 2,
    source: HAZ,
  },
];
