import type { Explainer, SourceReference } from "@/lib/types";

const TG = (chapter: string): SourceReference => ({
  document: "Aerodynamics Trainee Guide",
  chapter,
});

const BASIC = TG("Basic Theory");
const LIFT = TG("Lift Production and Drag");
const PERF = TG("Performance and Maneuvering");
const STALL = TG("Stalls");

/**
 * Second explainer set.
 *
 * Roughly half the Aerodynamics lessons had no sixty-second walkthrough, which
 * left their diagram sitting still on a model screen. These animate the
 * diagram each lesson already uses, so the picture does the explaining.
 */
export const EXPLAINERS_B: Explainer[] = [
  {
    id: "x-continuity-bernoulli",
    title: "Squeeze the Tube",
    promise: "Watch velocity and pressure trade places as a streamtube narrows.",
    unit: "u1",
    conceptIds: ["c-continuity", "c-bernoulli", "c-dynamic-pressure"],
    lessonId: "l03-continuity-bernoulli",
    diagram: { id: "streamtube" },
    frames: [
      { caption: "A streamtube is a closed system. Mass in equals mass out.", hold: 2800, props: { constriction: 0 } },
      { caption: "Narrow it, and the same mass must move faster.", hold: 3000, props: { constriction: 0.3 } },
      { caption: "Faster air carries more dynamic pressure.", hold: 2800, props: { constriction: 0.5 } },
      { caption: "Total pressure never changes — so static must fall.", hold: 3200, props: { constriction: 0.7 } },
      { caption: "That falling static pressure over the wing is lift.", hold: 3000, props: { constriction: 0.5 } },
    ],
    knowCold: "Area down, velocity up, static pressure down. Total is fixed.",
    source: BASIC,
  },
  {
    id: "x-camber-at-zero-aoa",
    title: "Camber at Zero AOA",
    promise: "Three airfoils at the same zero angle of attack, doing three different things.",
    unit: "u1",
    conceptIds: ["c-mean-camber-line", "c-camber-types", "c-chordline-chord"],
    lessonId: "l05-wing-geometry",
    diagram: { id: "airfoil-geometry" },
    frames: [
      { caption: "The chord line joins the leading and trailing EDGES.", hold: 2800, props: { camber: 0.06, labels: true } },
      { caption: "The mean camber line runs between the SURFACES.", hold: 2800, props: { camber: 0.06, labels: true } },
      { caption: "Positive camber: MCL above the chord line, lift at 0° AOA.", hold: 3200, props: { camber: 0.09, labels: true } },
      { caption: "Symmetric: the two lines coincide. Zero lift at 0° AOA.", hold: 3200, props: { camber: 0, labels: true } },
      { caption: "Negative camber: MCL below. Negative lift at 0° AOA.", hold: 3000, props: { camber: -0.07, labels: true } },
    ],
    knowCold: "Symmetric airfoil, zero AOA, zero lift.",
    source: BASIC,
  },
  {
    id: "x-planform-vocabulary",
    title: "Reading a Planform",
    promise: "Four measurements, and the one everybody takes from the wrong line.",
    unit: "u1",
    conceptIds: ["c-root-tip-chord", "c-sweep-angle", "c-dihedral", "c-wing-planform"],
    lessonId: "l05b-airplane-and-wing",
    diagram: { id: "wing-planform" },
    frames: [
      { caption: "Root chord at the centerline, tip chord at the wingtip.", hold: 3000, props: { labels: true } },
      { caption: "Taper ratio is tip divided by root — less than one.", hold: 3000, props: { labels: true } },
      { caption: "Sweep is measured to the 25% chord line, not the leading edge.", hold: 3400, props: { labels: true } },
      { caption: "On a tapered wing those two lines are not parallel.", hold: 3000, props: { labels: true } },
      { caption: "Dihedral needs a front view — it is invisible from above.", hold: 3000, props: { labels: true } },
    ],
    knowCold: "Taper is tip ÷ root. Sweep is to the 25% line.",
    source: BASIC,
  },
  {
    id: "x-resolving-aero-force",
    title: "Splitting the Force",
    promise: "One aerodynamic force, resolved into the two you actually care about.",
    unit: "u2",
    conceptIds: ["c-aero-force", "c-lift-def", "c-drag-def"],
    lessonId: "l07-aerodynamic-force",
    diagram: { id: "aero-force-components" },
    frames: [
      { caption: "The wing produces one total aerodynamic force.", hold: 2800, props: { aoa: 6 } },
      { caption: "Lift is the component PERPENDICULAR to the relative wind.", hold: 3200, props: { aoa: 6 } },
      { caption: "Drag is the component PARALLEL to it.", hold: 3000, props: { aoa: 6 } },
      { caption: "Raise the AOA and the whole force grows and tilts back.", hold: 3200, props: { aoa: 12 } },
      { caption: "Both references are the RELATIVE WIND — never the horizon.", hold: 3200, props: { aoa: 12 } },
    ],
    knowCold: "Lift ⟂ relative wind. Drag ∥ relative wind.",
    source: LIFT,
  },
  {
    id: "x-lift-equation-terms",
    title: "One Squared Term",
    promise: "Why velocity matters more than everything else in the lift equation.",
    unit: "u2",
    conceptIds: ["c-lift-equation", "c-coefficient-of-lift", "c-dynamic-pressure"],
    lessonId: "l09-lift-equation",
    diagram: { id: "lift-equation-anatomy" },
    frames: [
      { caption: "Four terms: density, velocity, wing area, coefficient of lift.", hold: 3000, props: { highlight: "all" } },
      { caption: "Density and area are linear — double them, double lift.", hold: 3000, props: { highlight: "rho" } },
      { caption: "C_L is set by angle of attack, and it is linear too.", hold: 3000, props: { highlight: "cl" } },
      { caption: "Velocity is the only SQUARED term.", hold: 3400, props: { highlight: "v" } },
      { caption: "Double the speed and lift quadruples. Nothing else does that.", hold: 3200, props: { highlight: "v" } },
    ],
    knowCold: "V is squared. Everything else is linear.",
    source: LIFT,
  },
  {
    id: "x-parasite-breakdown",
    title: "Three Kinds of Parasite",
    promise: "Form, friction and interference, and what each one is actually caused by.",
    unit: "u3",
    conceptIds: ["c-parasite-drag", "c-form-drag", "c-friction-drag", "c-interference-drag"],
    lessonId: "l11-parasite-drag",
    diagram: { id: "parasite-components" },
    frames: [
      { caption: "Parasite drag is everything not caused by producing lift.", hold: 2800, props: { highlight: "none" } },
      { caption: "Form drag: the shape's frontal area pushing air aside.", hold: 3000, props: { highlight: "form" } },
      { caption: "Friction drag: viscosity dragging on the skin.", hold: 3000, props: { highlight: "friction" } },
      { caption: "Interference drag: streamlines colliding where parts meet.", hold: 3200, props: { highlight: "interference" } },
      { caption: "All three grow with velocity squared.", hold: 3000, props: { highlight: "none" } },
    ],
    knowCold: "Form, friction, interference — and all rise with V².",
    source: LIFT,
  },
  {
    id: "x-thrust-versus-power",
    title: "Thrust or Power",
    promise: "Two curves that look alike and answer completely different questions.",
    unit: "u4",
    conceptIds: ["c-thrust-required", "c-power-required", "c-thrust-available", "c-power-available"],
    lessonId: "l14-thrust-and-power",
    diagram: { id: "thrust-power-pair" },
    frames: [
      { caption: "Thrust required is just the total drag curve, in pounds.", hold: 3000, props: { highlight: "thrust" } },
      { caption: "Its minimum is at L/Dmax AOA.", hold: 2800, props: { highlight: "thrust" } },
      { caption: "Power required is thrust times velocity.", hold: 3000, props: { highlight: "power" } },
      { caption: "Multiplying by V pushes its minimum to a SLOWER speed.", hold: 3400, props: { highlight: "power" } },
      { caption: "Thrust excess climbs steeply. Power excess climbs quickly.", hold: 3200, props: { highlight: "both" } },
    ],
    knowCold: "Thrust excess → angle. Power excess → rate.",
    source: LIFT,
  },
  {
    id: "x-takeoff-factors",
    title: "The 4-H Club",
    promise: "Four conditions that lengthen your takeoff roll, all through one mechanism.",
    unit: "u4",
    conceptIds: ["c-takeoff-distance", "c-4h-club", "c-takeoff-landing-speeds"],
    lessonId: "l16-takeoff-landing",
    diagram: { id: "takeoff-forces" },
    frames: [
      { caption: "Takeoff needs 1.2 times power-off stall speed.", hold: 2800, props: { phase: "roll" } },
      { caption: "High, hot and humid all reduce air density.", hold: 3000, props: { phase: "roll" } },
      { caption: "Less density means less thrust and less lift per knot.", hold: 3200, props: { phase: "roll" } },
      { caption: "Heavy is the fourth H — and it needs more lift as well.", hold: 3000, props: { phase: "rotate" } },
      { caption: "Double the weight and takeoff distance goes up four times.", hold: 3400, props: { phase: "rotate" } },
    ],
    knowCold: "High, Hot, Humid, Heavy. Weight doubles, distance ×4.",
    source: PERF,
  },
  {
    id: "x-angle-versus-rate",
    title: "Steepest or Fastest",
    promise: "Vx and Vy answer different questions, and only one clears the obstacle.",
    unit: "u4",
    conceptIds: ["c-vx-vy", "c-excess-thrust", "c-excess-power", "c-best-climb-profile"],
    lessonId: "l17-climb",
    diagram: { id: "climb-vectors" },
    frames: [
      { caption: "Climb ANGLE is altitude gained per unit of ground distance.", hold: 3000, props: { mode: "angle" } },
      { caption: "It comes from THRUST excess, and peaks at Vx.", hold: 3000, props: { mode: "angle" } },
      { caption: "Climb RATE is altitude gained per unit of TIME.", hold: 3000, props: { mode: "rate" } },
      { caption: "It comes from POWER excess, and peaks at Vy.", hold: 3000, props: { mode: "rate" } },
      { caption: "The T-6B flies 140 KIAS instead — max AOC sits near stall.", hold: 3400, props: { mode: "rate" } },
    ],
    knowCold: "Vx for the obstacle. Vy for the altitude. 140 KIAS in the T-6B.",
    source: PERF,
  },
  {
    id: "x-range-versus-endurance",
    title: "Distance or Time",
    promise: "Two points on the same curve, and the tangent line that separates them.",
    unit: "u4",
    conceptIds: ["c-max-range", "c-max-endurance", "c-fuel-flow-turboprop"],
    lessonId: "l18-range-endurance",
    diagram: { id: "power-curves" },
    frames: [
      { caption: "Endurance asks: how long can I stay airborne?", hold: 2800, props: { highlight: "min" } },
      { caption: "Minimum fuel flow — the BOTTOM of the power required curve.", hold: 3200, props: { highlight: "min" } },
      { caption: "Range asks: how far can I go on this fuel?", hold: 2800, props: { highlight: "tangent" } },
      { caption: "Minimum fuel per mile — a tangent from the origin.", hold: 3200, props: { highlight: "tangent" } },
      { caption: "For a turboprop both live on the POWER curve, not thrust.", hold: 3400, props: { highlight: "both" } },
    ],
    knowCold: "Endurance at the minimum. Range at the tangent.",
    source: PERF,
  },
  {
    id: "x-boundary-layer-transition",
    title: "Laminar to Turbulent",
    promise: "Follow the boundary layer from the leading edge to separation.",
    unit: "u5",
    conceptIds: ["c-boundary-layer", "c-laminar-turbulent", "c-pressure-gradient"],
    lessonId: "l20-boundary-layer",
    diagram: { id: "boundary-layer" },
    frames: [
      { caption: "At the leading edge the layer is laminar and about 1 mm thick.", hold: 3000, props: { aoa: 4 } },
      { caption: "Falling pressure to max thickness is a FAVOURABLE gradient.", hold: 3200, props: { aoa: 4 } },
      { caption: "Past max thickness pressure rises again — ADVERSE.", hold: 3200, props: { aoa: 8 } },
      { caption: "Turbulent flow has more energy and hangs on longer.", hold: 3000, props: { aoa: 12 } },
      { caption: "Raise AOA and separation marches forward toward the nose.", hold: 3400, props: { aoa: 16 } },
    ],
    knowCold: "Favourable to max thickness. Adverse after it.",
    source: STALL,
  },
  {
    id: "x-stall-speed-factors",
    title: "What Moves Stall Speed",
    promise: "Four factors, and the one that leaves indicated stall speed alone.",
    unit: "u5",
    conceptIds: ["c-stall-speed", "c-stall-speed-altitude", "c-accelerated-stall"],
    lessonId: "l22-stall-speed",
    diagram: { id: "stall-speed-equation" },
    frames: [
      { caption: "Stall always happens at C_Lmax AOA — never at a speed.", hold: 3000, props: { highlight: "clmax" } },
      { caption: "More weight needs more lift, so stall SPEED rises.", hold: 3000, props: { highlight: "weight" } },
      { caption: "Load factor does the same, by the square root of n.", hold: 3200, props: { highlight: "n" } },
      { caption: "Altitude raises TRUE stall speed as density falls.", hold: 3200, props: { highlight: "rho" } },
      { caption: "But INDICATED stall speed uses ρ₀ — so it does not move.", hold: 3400, props: { highlight: "rho" } },
    ],
    knowCold: "Indicated stall speed is fixed with altitude. True is not.",
    source: STALL,
  },
  {
    id: "x-high-lift-two-ways",
    title: "Two Ways to Raise C_L",
    promise: "Change the camber, or re-energise the boundary layer.",
    unit: "u5",
    conceptIds: ["c-high-lift-purpose", "c-blc-devices", "c-camber-devices"],
    lessonId: "l23-high-lift-devices",
    diagram: { id: "high-lift-comparison" },
    frames: [
      { caption: "High lift devices exist to lower stall speed for landing.", hold: 2800, props: { device: "none" } },
      { caption: "Camber devices raise C_Lmax and LOWER C_Lmax AOA.", hold: 3200, props: { device: "flap" } },
      { caption: "Plain, split, slotted and Fowler are all camber devices.", hold: 3000, props: { device: "fowler" } },
      { caption: "BLC devices re-energise the boundary layer instead.", hold: 3200, props: { device: "slat" } },
      { caption: "Those raise C_Lmax AND raise C_Lmax AOA — slats and slots.", hold: 3400, props: { device: "slat" } },
    ],
    knowCold: "Camber devices lower the stall AOA. BLC devices raise it.",
    source: STALL,
  },
  {
    id: "x-left-turning-tendencies",
    title: "Everything Pulls Left",
    promise: "Four propeller effects, and why right rudder is the answer to all of them.",
    unit: "u6",
    conceptIds: ["c-p-factor", "c-slipstream-swirl", "c-torque-gyro"],
    lessonId: "l26-slips-skids-prop",
    diagram: { id: "slip-skid" },
    frames: [
      { caption: "Torque rolls the fuselage opposite the propeller.", hold: 3000, props: { state: "coordinated" } },
      { caption: "Slipstream swirl strikes the vertical stabiliser's left side.", hold: 3200, props: { state: "slip" } },
      { caption: "That pulls the tail right, yawing the nose LEFT.", hold: 3000, props: { state: "slip" } },
      { caption: "P-factor: the descending blade bites harder at high AOA.", hold: 3200, props: { state: "slip" } },
      { caption: "Gyroscopic precession acts 90° later in the rotation.", hold: 3200, props: { state: "coordinated" } },
    ],
    knowCold: "Right rudder. All four want the nose left.",
    source: PERF,
  },
  {
    id: "x-static-then-dynamic",
    title: "The Ball in the Bowl",
    promise: "Static stability is the first instant. Dynamic is everything after.",
    unit: "u6",
    conceptIds: ["c-static-stability", "c-dynamic-stability", "c-dynamic-modes"],
    lessonId: "l28-stability",
    diagram: { id: "stability-ball" },
    frames: [
      { caption: "Displace the ball. What it does FIRST is static stability.", hold: 3000, props: { state: "positive" } },
      { caption: "Returning toward equilibrium: positive static stability.", hold: 3000, props: { state: "positive" } },
      { caption: "Moving further away: negative. Staying put: neutral.", hold: 3200, props: { state: "negative" } },
      { caption: "Dynamic stability is what happens over TIME after that.", hold: 3000, props: { state: "neutral" } },
      { caption: "Static instability guarantees dynamic instability.", hold: 3400, props: { state: "negative" } },
    ],
    knowCold: "Static is the first instant. Dynamic is the whole story.",
    source: PERF,
  },
];
