import type { Lesson, SourceReference } from "@/lib/types";

const VIFR: SourceReference = {
  document: "Flight Rules and Regulations Trainee Guide",
  chapter: "Visual / Instrument Flight Rules",
};
const AIR: SourceReference = {
  document: "Flight Rules and Regulations Trainee Guide",
  chapter: "Airspace and General Flight Rules",
};

/** FR&R lessons, units f5–f8: the rules themselves, and where they bite. */
export const LESSONS_B: Lesson[] = [
  /* ================= f5 · VFR and IFR ================= */
  {
    id: "fl17-vmc-imc-vfr-ifr",
    unit: "f5",
    index: 17,
    title: "VMC, IMC, VFR, IFR",
    subtitle: "Weather versus rules",
    estimatedMinutes: 5,
    mapIcon: "frr-cloud",
    enablingObjectives: ["2.362"],
    conceptIds: ["fr-vmc", "fr-imc", "fr-vfr-ifr-terms", "fr-forecast", "fr-see-and-avoid"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Two of these describe the sky. Two describe what you are allowed to do.",
        line: "Confusing the pair is what makes 'an IFR flight plan in VMC' sound like a contradiction. It is not.",
      },
      {
        kind: "compare",
        headline: "Which is which",
        line: "VMC and IMC are weather. VFR and IFR are rules.",
        columns: ["Term", "What it describes"],
        rows: [
          { label: "VMC", a: "Visibility, cloud distance and ceiling at or better than the minima", b: "WEATHER" },
          { label: "IMC", a: "Any of those below the minima — or, per CNAF, no distinguishable horizon", b: "WEATHER" },
          { label: "VFR", a: "The set of rules governing visual procedures", b: "RULES" },
          { label: "IFR", a: "The set of rules governing instrument procedures", b: "RULES" },
        ],
      },
      {
        kind: "rule",
        headline: "See and avoid",
        rule:
          "When weather conditions permit, regardless of whether an operation is conducted under IFR or VFR, vigilance shall be maintained by each person operating an aircraft so as to see and avoid other aircraft.",
        appliesWhen: ["Any flight, under either set of rules, whenever the weather allows"],
        watchFor:
          "'Regardless of whether IFR or VFR' — being on an IFR clearance does not hand the lookout to ATC.",
        authority: "FAR Part 91",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "VMC and IMC = weather · VFR and IFR = rules",
          "CNAF: no distinguishable horizon is IMC",
          "See and avoid applies under both sets of rules",
          "A forecast is valid for a specific area for a specific time period",
        ],
      },
      { kind: "question", questionId: "fq-f5-001" },
      { kind: "question", questionId: "fq-f5-002" },
      { kind: "question", questionId: "ftrap-f5-003" },
      { kind: "question", questionId: "fq-f5-004" },
    ],
    questionIds: ["fq-f5-001", "fq-f5-002", "ftrap-f5-003", "fq-f5-004"],
    memorize: ["VMC/IMC is the sky. VFR/IFR is the rulebook."],
    sourceReferences: [VIFR],
  },
  {
    id: "fl18-vfr-weather-minimums",
    unit: "f5",
    index: 18,
    title: "VFR Weather Minimums",
    subtitle: "1,000 and 3, and where it changes",
    estimatedMinutes: 6,
    mapIcon: "frr-minimums",
    enablingObjectives: ["2.363", "2.364"],
    conceptIds: [
      "fr-basic-vfr",
      "fr-vfr-destination",
      "fr-vfr-enroute",
      "fr-precluding-vfr",
      "fr-vfr-fuel",
    ],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "1,000 and 3 is the number everyone remembers",
        line: "The part that catches people is what happens the moment the forecast says it might not hold.",
      },
      {
        kind: "model",
        headline: "Basic VFR cloud clearance",
        diagram: { id: "frr-cloud-clearance", props: { regime: "standard" } },
        line: "1,000 feet above, 500 feet below, 2,000 feet horizontally, 3 statute miles visibility.",
      },
      {
        kind: "rule",
        headline: "Filing VFR",
        rule:
          "A VFR flight plan may be filed only when the destination forecast, for one hour before through one hour after ETA, indicates a ceiling of at least 1,000 feet and 3 SM visibility. Flights shall not be planned or conducted VFR when weather conditions along the route preclude flight in accordance with visual flight rules.",
        appliesWhen: [
          "Filing — the destination forecast window is ETA ± 1 hour",
          "En route — the whole route, not only the destination",
        ],
        watchFor:
          "If the forecast is marginal or deteriorating, an IFR flight plan is required. There is no 'plan VFR and see how it goes'.",
        authority: "CNAF M-3710.7",
      },
      {
        kind: "chain",
        headline: "The VFR fuel rule",
        nodes: [
          { label: "Fuel to reach the first point of intended landing", trend: "none" },
          { label: "Plus 10% of planned fuel requirements", trend: "none" },
          { label: "Never less than 20 minutes of reserve", trend: "up", emphasis: true },
        ],
        footnote: "The 20 minutes is a floor under the 10%, not an alternative to it.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Basic VFR: 1,000 above, 500 below, 2,000 horizontal, 3 SM",
          "File VFR only if destination forecast is 1,000/3 for ETA ± 1 hour",
          "Marginal or deteriorating → file IFR",
          "Fuel: destination + 10%, minimum 20 minutes",
        ],
      },
      { kind: "question", questionId: "fq-f5-005" },
      { kind: "question", questionId: "fcc-f5-006" },
      { kind: "question", questionId: "fq-f5-007" },
      { kind: "question", questionId: "fq-f5-018" },
    ],
    questionIds: ["fq-f5-005", "fcc-f5-006", "fq-f5-007", "fq-f5-008", "fq-f5-018"],
    memorize: ["1,000 and 3 at the destination, ETA ± 1 hour."],
    sourceReferences: [VIFR],
    labIds: ["flab-vfr-ifr"],
  },
  {
    id: "fl19-ifr-and-vfr-on-top",
    unit: "f5",
    index: 19,
    title: "IFR and VFR-On-Top",
    subtitle: "Clearances, and a clearance that looks like VFR",
    estimatedMinutes: 5,
    mapIcon: "frr-ifr",
    enablingObjectives: ["2.365", "2.366"],
    conceptIds: ["fr-ifr-general", "fr-vfr-on-top"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "VFR-on-top is an IFR clearance",
        line: "That single sentence answers most of the questions ever written about it.",
      },
      {
        kind: "rule",
        headline: "IFR operations",
        rule:
          "No person may operate an aircraft in controlled airspace under IFR unless that person has filed an IFR flight plan and received an appropriate ATC clearance. Naval aircraft shall be flown IFR whenever conditions preclude VFR flight.",
        appliesWhen: [
          "IFR in controlled airspace: flight plan AND clearance, both",
          "Any time weather precludes VFR",
        ],
        authority: "FAR Part 91 · CNAF M-3710.7",
      },
      {
        kind: "compare",
        headline: "VFR-on-top",
        line: "You are operating under IFR the whole time, choosing your own altitude within limits.",
        columns: ["What it is", "What still applies"],
        rows: [
          { label: "Clearance", a: "An IFR clearance", b: "You remain on an IFR flight plan" },
          { label: "Altitude", a: "You select it", b: "Must comply with VFR cruising altitudes" },
          { label: "Weather", a: "Must maintain VFR minimums", b: "Cloud clearance and visibility still apply" },
          { label: "ATC", a: "Reports and clearances continue", b: "You are still an IFR aircraft to the system" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "IFR in controlled airspace needs a filed plan AND a clearance",
          "VFR-on-top is an IFR clearance",
          "On top you pick the altitude, but it must be a VFR cruising altitude",
        ],
      },
      { kind: "question", questionId: "fq-f5-009" },
      { kind: "question", questionId: "fq-f5-010" },
      { kind: "question", questionId: "fq-f5-011" },
      { kind: "question", questionId: "fq-f5-019" },
    ],
    questionIds: ["fq-f5-009", "fq-f5-010", "fq-f5-011", "fq-f5-019"],
    memorize: ["VFR-on-top: IFR clearance, VFR altitudes, VFR minimums."],
    sourceReferences: [VIFR],
  },
  {
    id: "fl20-approaches-and-minimums",
    unit: "f5",
    index: 20,
    title: "Approaches and Landing Minimums",
    subtitle: "Precision, non-precision, and when you may descend",
    estimatedMinutes: 6,
    mapIcon: "frr-approach",
    enablingObjectives: ["2.367"],
    conceptIds: [
      "fr-approach-types",
      "fr-landing-minimums",
      "fr-approach-criteria",
      "fr-missed-approach",
    ],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "One question decides whether you may leave the minimum altitude",
        line: "Not 'am I close enough' — a specific test, stated in the regulation.",
      },
      {
        kind: "compare",
        headline: "Two families of approach",
        line: "The difference is whether the approach gives you vertical guidance.",
        columns: ["Precision", "Non-precision"],
        rows: [
          { label: "Guidance", a: "Course AND glideslope", b: "Course only" },
          { label: "The limit", a: "Decision height (DH)", b: "Minimum descent altitude (MDA)" },
          { label: "Examples", a: "ILS, PAR", b: "VOR, TACAN, LOC, ASR, RNAV" },
        ],
      },
      {
        kind: "rule",
        headline: "Leaving the MDA or DH",
        rule:
          "Pilots shall not descend below the minimum descent altitude, or continue below decision height, unless they have the runway environment in sight and judge that a safe landing can be made.",
        appliesWhen: ["Every instrument approach, at the MDA or DH"],
        watchFor:
          "Two conditions, both required: the runway environment IN SIGHT, and the pilot's judgment that a safe landing can be made.",
      },
      {
        kind: "chain",
        headline: "Missed approach",
        nodes: [
          { label: "Controller directs a missed approach", trend: "none" },
          { label: "Execution is MANDATORY", trend: "up", emphasis: true },
          { label: "But the pilot may also go missed at their own discretion, at any time", trend: "none" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Precision = course + glideslope, limit is DH",
          "Non-precision = course only, limit is MDA",
          "Descend below only with the runway environment in sight AND a safe landing judged",
          "A directed missed approach is mandatory",
        ],
      },
      { kind: "question", questionId: "fq-f5-012" },
      { kind: "question", questionId: "fq-f5-013" },
      { kind: "question", questionId: "fq-f5-020" },
      { kind: "question", questionId: "fq-f5-015" },
    ],
    questionIds: [
      "fq-f5-012",
      "fq-f5-013",
      "fq-f5-014",
      "fq-f5-015",
      "fq-f5-020",
    ],
    memorize: ["Runway environment in sight, and a safe landing judged. Both."],
    sourceReferences: [VIFR],
    explainerIds: ["fx-approach"],
  },
  {
    id: "fl21-alternates-and-ifr-fuel",
    unit: "f5",
    index: 21,
    title: "Alternates and IFR Fuel",
    subtitle: "When you need a second airfield",
    estimatedMinutes: 5,
    mapIcon: "frr-alternate",
    enablingObjectives: ["2.367"],
    conceptIds: ["fr-alternate", "fr-ifr-fuel", "fr-approach-criteria"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "The alternate is not just 'somewhere else nearby'",
        line: "It has to be usable with the equipment you have, in weather you might actually meet.",
      },
      {
        kind: "rule",
        headline: "The approach the alternate must have",
        rule:
          "When an alternate is required, it shall have a published approach that can be flown without the use of two-way radio, compatible with the installed operable navigation equipment, whenever the destination lacks such an approach, or the alternate's forecast weather is below a 3,000 foot ceiling and 3 SM visibility during the period one hour before through one hour after ETA.",
        appliesWhen: [
          "The destination has no no-radio published approach, OR",
          "The alternate's forecast is below 3,000/3 during ETA ± 1 hour",
        ],
        watchFor:
          "Whether an alternate is required at all is decided by the IFR Filing Criteria table in CNAF M-3710.7 — a different question from what the alternate must have.",
        authority: "CNAF M-3710.7",
      },
      {
        kind: "chain",
        headline: "IFR fuel with an alternate required",
        nodes: [
          { label: "Takeoff to the approach fix serving the destination", trend: "none" },
          { label: "Then from that fix to the alternate", trend: "none" },
          { label: "Plus 10% of planned fuel, never less than 20 minutes", trend: "up", emphasis: true },
        ],
        footnote: "With no alternate required, the fuel requirement is the same as VFR.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "The IFR Filing Criteria table decides whether an alternate is needed",
          "3,000 and 3, ETA ± 1 hour, is the alternate's own weather trigger",
          "Fuel: destination approach fix → alternate → 10%, minimum 20 minutes",
        ],
      },
      { kind: "question", questionId: "fq-f5-016" },
      { kind: "question", questionId: "fq-f5-017" },
      { kind: "question", questionId: "fq-f5-021" },
    ],
    questionIds: ["fq-f5-016", "fq-f5-017", "fq-f5-021"],
    memorize: ["3,000 and 3 at the alternate, ETA ± 1 hour."],
    sourceReferences: [VIFR],
  },

  /* ================= f6 · Altitudes and Aerobatics ================= */
  {
    id: "fl22-semicircular-rule",
    unit: "f6",
    index: 22,
    title: "The Semicircular Rule",
    subtitle: "East odd, west even",
    estimatedMinutes: 6,
    mapIcon: "frr-compass",
    enablingObjectives: ["2.368"],
    conceptIds: ["fr-semicircular", "fr-vfr-altitudes", "fr-ifr-altitudes"],
    masteryThreshold: 0.85,
    screens: [
      {
        kind: "hook",
        headline: "Two aircraft heading opposite ways never share an altitude",
        line: "That is the whole point of the rule. Everything else is just the arithmetic of it.",
      },
      {
        kind: "model",
        headline: "Which hemisphere are you in",
        diagram: { id: "frr-semicircular", props: { course: 90, rules: "vfr" } },
        line: "Courses 0° through 179° are east. Courses 180° through 359° are west. It is the COURSE, not the heading.",
      },
      {
        kind: "manipulate",
        headline: "Turn the course and switch the rules",
        widget: "SemicircularWidget",
        line: "Watch the +500 appear and disappear as you move between VFR and IFR.",
      },
      {
        kind: "compare",
        headline: "VFR versus IFR",
        line: "The +500 is the VFR signature.",
        columns: ["VFR (above 3,000 AGL)", "IFR"],
        rows: [
          { label: "East, below 18,000 MSL", a: "Odd thousands + 500", b: "Odd thousands" },
          { label: "West, below 18,000 MSL", a: "Even thousands + 500", b: "Even thousands" },
          { label: "18,000 to FL290", a: "Odd/even FL + 500", b: "Odd/even flight levels" },
          { label: "Above FL290", a: "East from FL300, west from FL320, 4,000 ft intervals", b: "East from FL290, west from FL310" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "East is 0–179 · West is 180–359 · 360 is east",
          "VFR adds 500. IFR does not.",
          "VFR altitudes only apply above 3,000 ft AGL",
          "In controlled airspace under IFR, the real answer is the ATC-assigned altitude",
        ],
      },
      { kind: "question", questionId: "fq-f6-001" },
      { kind: "question", questionId: "fq-f6-002" },
      { kind: "question", questionId: "fq-f6-003" },
      { kind: "question", questionId: "fsl-f6-006" },
      { kind: "question", questionId: "ftrap-f6-011" },
    ],
    questionIds: [
      "fq-f6-001",
      "fq-f6-002",
      "fq-f6-003",
      "fq-f6-004",
      "fsl-f6-006",
      "ftrap-f6-011",
    ],
    memorize: ["East odd, west even. VFR adds 500."],
    sourceReferences: [VIFR],
    explainerIds: ["fx-semicircular"],
    labIds: ["flab-altitude"],
  },
  {
    id: "fl23-aerobatic-flight",
    unit: "f6",
    index: 23,
    title: "Aerobatic Flight",
    subtitle: "Three numbers define it",
    estimatedMinutes: 5,
    mapIcon: "frr-aerobatic",
    enablingObjectives: ["2.369", "2.370", "2.371"],
    conceptIds: ["fr-aerobatic-definition", "fr-aerobatic-rules", "fr-unusual-maneuvers"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Aerobatic flight has a definition, not a vibe",
        line: "Bank, pitch or g — exceed one of the three thresholds intentionally and you are doing aerobatics.",
      },
      {
        kind: "rule",
        headline: "Aerobatic flight defined",
        rule:
          "An intentional manoeuvre involving abrupt bank angles greater than 60°, pitch angles greater than ±45°, or accelerations greater than 2.0 g.",
        appliesWhen: ["Any one of the three thresholds is exceeded, intentionally"],
        watchFor:
          "A break manoeuvre conforming to the model NATOPS flight manual is specifically NOT considered aerobatic flight.",
        authority: "CNAF M-3710.7",
      },
      {
        kind: "chain",
        headline: "Where aerobatics are prohibited",
        nodes: [
          { label: "Over a congested area of a city, town or settlement", trend: "none" },
          { label: "Over an open air assembly of persons", trend: "none" },
          { label: "In Class B, C, D or E designated for an airport, or on a federal airway", trend: "none" },
          { label: "Below 1,500 ft AGL", trend: "none" },
          { label: "When visibility is less than 3 SM", trend: "none" },
        ],
        footnote:
          "CNAF restates all of these and adds: not if the aircraft's NATOPS prohibits it. Commands may be stricter — the Training Command minimum is 5,000 ft AGL.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Bank > 60° · pitch > ±45° · acceleration > 2.0 g",
          "A NATOPS-conforming break is not aerobatic",
          "Floor is 1,500 ft AGL by FAR, 5,000 ft AGL in the Training Command",
        ],
      },
      { kind: "question", questionId: "fq-f6-005" },
      { kind: "question", questionId: "fq-f6-007" },
      { kind: "question", questionId: "fq-f6-008" },
      { kind: "question", questionId: "fq-f6-009" },
      { kind: "question", questionId: "fq-f6-010" },
    ],
    questionIds: [
      "fq-f6-005",
      "fq-f6-007",
      "fq-f6-008",
      "fq-f6-009",
      "fq-f6-010",
    ],
    memorize: ["60, 45, 2.0."],
    sourceReferences: [VIFR],
  },

  /* ================= f7 · Airspace ================= */
  {
    id: "fl24-controlled-and-uncontrolled",
    unit: "f7",
    index: 24,
    title: "Controlled and Uncontrolled",
    subtitle: "What the word actually means",
    estimatedMinutes: 4,
    mapIcon: "frr-airspace",
    enablingObjectives: ["2.372"],
    conceptIds: ["fr-controlled", "fr-uncontrolled", "fr-class-g"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Controlled airspace does not mean somebody is watching you",
        line: "It means ATC service is PROVIDED there. Whether you receive it depends on how you are flying.",
      },
      {
        kind: "rule",
        headline: "Controlled airspace",
        rule:
          "Airspace of defined dimensions within which air traffic control service is provided to IFR flights and to VFR flights in accordance with the airspace classification. Classes A, B, C, D and E are controlled; Class G is not.",
        appliesWhen: [
          "IFR flights receive separation service throughout",
          "VFR flights receive whatever the class provides",
        ],
        watchFor:
          "Class G is uncontrolled. ATC has neither the authority nor the responsibility to control traffic there.",
      },
      {
        kind: "model",
        headline: "The classes in profile",
        diagram: { id: "frr-airspace-profile", props: { highlight: "none" } },
        line: "Class A on top, Class B and C around the busiest airports, D at towered fields, E filling the rest of the controlled airspace, and G underneath.",
      },
      {
        kind: "manipulate",
        headline: "Where the classes actually sit",
        widget: "AirspaceProfileWidget",
        line: "Pick a class and see its floor, its ceiling, and what it takes to get in.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "A, B, C, D, E are controlled · G is uncontrolled",
          "Controlled means ATC service is provided, not that you are being watched",
        ],
      },
      { kind: "question", questionId: "fq-f7-001" },
      { kind: "question", questionId: "fq-f7-002" },
      { kind: "question", questionId: "fq-f7-029" },
    ],
    questionIds: ["fq-f7-001", "fq-f7-002", "fq-f7-003", "fq-f7-029"],
    memorize: ["Only G is uncontrolled."],
    sourceReferences: [AIR],
    explainerIds: ["fx-airspace"],
  },
  {
    id: "fl25-airspace-classes",
    unit: "f7",
    index: 25,
    title: "The Airspace Classes",
    subtitle: "Dimensions and how you get in",
    estimatedMinutes: 8,
    mapIcon: "frr-classes",
    enablingObjectives: ["2.373", "2.374"],
    conceptIds: [
      "fr-class-a",
      "fr-class-b",
      "fr-class-c",
      "fr-two-way-established",
      "fr-class-d",
      "fr-class-e",
      "fr-class-g",
    ],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "One class needs a clearance. Two need only a conversation.",
        line: "Knowing which is which is the single most useful thing in this unit.",
      },
      {
        kind: "compare",
        headline: "Dimensions and entry",
        line: "Read the right-hand column carefully — the difference between B and C/D lives there.",
        columns: ["Dimensions", "To enter"],
        rows: [
          { label: "A", a: "18,000 MSL to FL600", b: "IFR only, clearance required" },
          { label: "B", a: "Surface to ~10,000 MSL, busiest airports", b: "ATC CLEARANCE" },
          { label: "C", a: "Surface to ~4,000 AGL, 5 nm core", b: "Two-way communication established" },
          { label: "D", a: "Surface to ~2,500 AGL, towered field", b: "Two-way communication established" },
          { label: "E", a: "Controlled airspace that is not A, B, C or D", b: "Nothing, if VFR" },
          { label: "G", a: "Uncontrolled, usually below 1,200 AGL", b: "Nothing" },
        ],
      },
      {
        kind: "rule",
        headline: "Two-way communication established",
        rule:
          "If the controller responds using your aircraft call sign, two-way radio communication has been established and you may enter. If the controller responds with your call sign followed by 'remain outside the Class C airspace and standby', two-way communication has NOT been established for entry purposes.",
        appliesWhen: ["Entering Class C or Class D airspace"],
        watchFor:
          "The test is the CALL SIGN in the reply. 'Aircraft calling, standby' is not establishment.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Class B needs a clearance · Class C and D need two-way comms established",
          "Class A: 18,000 MSL to FL600, IFR only",
          "Your call sign in the reply is what establishes communication",
        ],
      },
      { kind: "question", questionId: "fq-f7-005" },
      { kind: "question", questionId: "fq-f7-006" },
      { kind: "question", questionId: "fq-f7-007" },
      { kind: "question", questionId: "fq-f7-008" },
      { kind: "question", questionId: "ftrap-f7-004" },
      { kind: "question", questionId: "ftap-f7-012" },
    ],
    questionIds: [
      "fq-f7-005",
      "fq-f7-006",
      "fq-f7-007",
      "fq-f7-008",
      "fq-f7-009",
      "fq-f7-010",
      "fq-f7-011",
      "ftrap-f7-004",
      "ftap-f7-012",
    ],
    memorize: ["B = clearance. C and D = conversation."],
    sourceReferences: [AIR],
    explainerIds: ["fx-airspace"],
    labIds: ["flab-airspace"],
  },
  {
    id: "fl26-routes-and-transponders",
    unit: "f7",
    index: 26,
    title: "Routes and Mode C",
    subtitle: "Victor airways, jet routes, and where the transponder is required",
    estimatedMinutes: 4,
    mapIcon: "frr-route",
    enablingObjectives: ["2.375"],
    conceptIds: ["fr-victor-airways", "fr-jet-routes", "fr-mode-c"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "The airway system splits at 18,000 feet",
        line: "Below it you fly Victor airways. Above it, jet routes. And at 10,000 the transponder rule kicks in.",
      },
      {
        kind: "compare",
        headline: "Two route structures",
        line: "Same idea, different altitudes.",
        columns: ["Victor airways", "Jet routes"],
        rows: [
          { label: "Altitudes", a: "1,200 AGL to 18,000 MSL", b: "18,000 MSL to FL450" },
          { label: "Width", a: "8 nm — 4 nm each side of centerline", b: "" },
          { label: "Based on", a: "VOR navigation aids", b: "VOR / VORTAC" },
        ],
      },
      {
        kind: "chain",
        headline: "Where Mode C is required",
        nodes: [
          { label: "At and above 10,000 MSL (excluding at/below 2,500 AGL)", trend: "none" },
          { label: "Within and above Class B, to 10,000 MSL", trend: "none" },
          { label: "Within 30 nm of a Class B primary airport", trend: "none" },
          { label: "Within and above Class C, to 10,000 MSL", trend: "none" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Victor airways: 1,200 AGL to 18,000 MSL, 8 nm wide",
          "Jet routes: 18,000 MSL to FL450",
          "Mode C: 10,000 MSL, and the Class B/C shells including the 30 nm veil",
        ],
      },
      { kind: "question", questionId: "fq-f7-013" },
      { kind: "question", questionId: "fq-f7-014" },
      { kind: "question", questionId: "fq-f7-015" },
      { kind: "question", questionId: "fq-f7-016" },
    ],
    questionIds: ["fq-f7-013", "fq-f7-014", "fq-f7-015", "fq-f7-016", "fq-f7-017"],
    memorize: ["Victor below 18,000. Jet routes above."],
    sourceReferences: [AIR],
  },
  {
    id: "fl27-vfr-minimums-by-class",
    unit: "f7",
    index: 27,
    title: "VFR Minimums by Class",
    subtitle: "The table",
    estimatedMinutes: 6,
    mapIcon: "frr-table",
    enablingObjectives: ["2.376"],
    conceptIds: ["fr-vfr-minimums-table"],
    masteryThreshold: 0.85,
    screens: [
      {
        kind: "hook",
        headline: "Most of this table is the same three numbers",
        line: "Learn the standard row, then learn the two places it changes: Class B, and above 10,000 feet.",
      },
      {
        kind: "model",
        headline: "The standard row",
        diagram: { id: "frr-cloud-clearance", props: { regime: "standard" } },
        line: "1,000 above, 500 below, 2,000 horizontal, 3 SM. Class C, Class D, and Class E below 10,000 MSL all use this.",
      },
      {
        kind: "compare",
        headline: "Where it changes",
        line: "Two exceptions, in opposite directions.",
        columns: ["Class B", "Class E at or above 10,000 MSL"],
        rows: [
          { label: "Cloud clearance", a: "Clear of clouds", b: "1,000 above, 1,000 below, 1 SM horizontal" },
          { label: "Visibility", a: "3 SM", b: "5 SM" },
          { label: "Why", a: "ATC is separating everyone anyway", b: "Closing speeds are higher up there" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Standard: 1,000 / 500 / 2,000 / 3 SM",
          "Class B: clear of clouds, 3 SM",
          "Class E ≥ 10,000 MSL: 1,000 / 1,000 / 1 SM / 5 SM",
          "Class A: not applicable — IFR only",
        ],
      },
      { kind: "question", questionId: "fq-f7-018" },
      { kind: "question", questionId: "fq-f7-019" },
      { kind: "question", questionId: "fq-f7-020" },
      { kind: "question", questionId: "fbf-f7-021" },
    ],
    questionIds: ["fq-f7-018", "fq-f7-019", "fq-f7-020", "fbf-f7-021"],
    memorize: ["1,000 / 500 / 2,000 / 3. Except B, and except high."],
    sourceReferences: [AIR],
    labIds: ["flab-airspace"],
  },
  {
    id: "fl28-special-use-airspace",
    unit: "f7",
    index: 28,
    title: "Special Use Airspace",
    subtitle: "Six kinds, and only one you may never enter",
    estimatedMinutes: 5,
    mapIcon: "frr-sua",
    enablingObjectives: ["2.377"],
    conceptIds: [
      "fr-prohibited-area",
      "fr-restricted-area",
      "fr-warning-area",
      "fr-moa",
      "fr-alert-area",
      "fr-controlled-firing",
    ],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Prohibited, restricted and warning are not synonyms",
        line: "One forbids entry outright. One needs permission. One is a warning because it is over international water and nobody can forbid you.",
      },
      {
        kind: "compare",
        headline: "The six",
        line: "The distinguishing detail is in the third column.",
        columns: ["What happens there", "Entry"],
        rows: [
          { label: "Prohibited", a: "National security or welfare", b: "Flight is PROHIBITED" },
          { label: "Restricted", a: "Artillery, gunnery, guided missiles", b: "Permission from the controlling agency" },
          { label: "Warning", a: "Same hazards, over international waters", b: "Not prohibited — it warns" },
          { label: "MOA", a: "Military training separated from IFR traffic", b: "VFR may enter, with caution" },
          { label: "Alert", a: "High volume of pilot training or unusual activity", b: "Open — both parties equally responsible" },
          { label: "Controlled firing", a: "Activities suspended when an aircraft approaches", b: "No restriction on the pilot" },
        ],
      },
      {
        kind: "rule",
        headline: "Warning areas",
        rule:
          "A warning area contains the same hazards as a restricted area, but is located over domestic and international waters. Because the airspace beyond three nautical miles is international, it cannot be legally designated as restricted.",
        appliesWhen: ["Airspace beyond 3 nm from the coast"],
        watchFor:
          "The name is the giveaway. A warning area warns; it does not prohibit, because it legally cannot.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Prohibited: no entry, ever",
          "Restricted: permission from the controlling agency",
          "Warning: same hazards, over water, cannot be restricted",
          "Controlled firing is the one that stops for YOU",
        ],
      },
      { kind: "question", questionId: "fq-f7-030" },
      { kind: "question", questionId: "fq-f7-023" },
      { kind: "question", questionId: "fq-f7-024" },
      { kind: "question", questionId: "fq-f7-025" },
      { kind: "question", questionId: "fq-f7-026" },
    ],
    questionIds: [
      "fq-f7-022",
      "fq-f7-023",
      "fq-f7-024",
      "fq-f7-025",
      "fq-f7-026",
      "fq-f7-027",
      "fq-f7-028",
      "fq-f7-030",
    ],
    memorize: ["Prohibited forbids. Restricted permits. Warning warns."],
    sourceReferences: [AIR],
    explainerIds: ["fx-sua"],
  },

  /* ================= f8 · General Flight Rules ================= */
  {
    id: "fl29-lights-and-relative-position",
    unit: "f8",
    index: 29,
    title: "Lights and Relative Position",
    subtitle: "Reading another aircraft at night",
    estimatedMinutes: 5,
    mapIcon: "frr-nightlights",
    enablingObjectives: ["2.378", "2.379"],
    conceptIds: ["fr-position-lights", "fr-relative-position", "fr-anticollision"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "At night, another aircraft is three coloured dots",
        line: "Which dots you can see tells you exactly which way it is going.",
      },
      {
        kind: "model",
        headline: "The three lights",
        diagram: { id: "frr-position-lights", props: { view: "headon" } },
        line: "Red on the left wing, green on the right, white facing aft.",
      },
      {
        kind: "compare",
        headline: "What you see, what it means",
        line: "Work it out from where the lights must be pointing.",
        columns: ["You see", "Its orientation"],
        rows: [
          { label: "Red AND green", a: "Head-on", b: "Opposite direction" },
          { label: "White only", a: "Tail on", b: "Same direction" },
          { label: "Red only", a: "Its left side", b: "Crossing right to left" },
          { label: "Green only", a: "Its right side", b: "Crossing left to right" },
        ],
      },
      {
        kind: "rule",
        headline: "When the lights go on",
        rule:
          "Position lights are required from 30 minutes before official sunset to 30 minutes after official sunrise, and any time visibility as seen from the cockpit is less than 3 SM. Anti-collision lights are used from before engine start until engine shutdown.",
        appliesWhen: [
          "Sunset − 30 to sunrise + 30",
          "Any time flight visibility is below 3 SM",
        ],
        watchFor:
          "CNAF permits anti-collision lights off in cloud, to prevent distracting the pilot, and where they adversely affect ground operations.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Red left, green right, white aft",
          "Red and green together = head-on",
          "Position lights: sunset − 30 to sunrise + 30, or below 3 SM",
          "Anti-collision: engine start to engine shutdown",
        ],
      },
      { kind: "question", questionId: "fq-f8-001" },
      { kind: "question", questionId: "fq-f8-005" },
      { kind: "question", questionId: "fq-f8-002" },
      { kind: "question", questionId: "fq-f8-004" },
      { kind: "question", questionId: "ftap-f8-006" },
    ],
    questionIds: ["fq-f8-001", "fq-f8-002", "fq-f8-003", "fq-f8-004", "fq-f8-005", "ftap-f8-006"],
    memorize: ["Red left, green right, white aft."],
    sourceReferences: [AIR],
    explainerIds: ["fx-night-lights"],
  },
  {
    id: "fl30-right-of-way",
    unit: "f8",
    index: 30,
    title: "Right of Way",
    subtitle: "Who yields to whom",
    estimatedMinutes: 5,
    mapIcon: "frr-rightofway",
    enablingObjectives: ["2.380"],
    conceptIds: ["fr-row-order", "fr-row-category"],
    masteryThreshold: 0.85,
    screens: [
      {
        kind: "hook",
        headline: "The rule runs on manoeuvrability, not size or speed",
        line: "Which is why a balloon outranks everything with an engine.",
      },
      {
        kind: "model",
        headline: "The situations",
        diagram: { id: "frr-right-of-way", props: { scenario: "headon" } },
        line: "Head-on: both turn right, whatever category they are. Converging: the aircraft on the right has it. Overtaking: the overtaken aircraft has it, and the overtaker passes to the right.",
      },
      {
        kind: "chain",
        headline: "Overall priority",
        nodes: [
          { label: "Aircraft in distress", trend: "up", emphasis: true },
          { label: "Landing aircraft — lower aircraft first", trend: "none" },
          { label: "Category priority: balloon, glider, airship, airplane, helicopter", trend: "none" },
          { label: "Same category: the aircraft on the right", trend: "down" },
        ],
        footnote:
          "The lower aircraft on approach may not use that priority to cut in front of another on final.",
      },
      {
        kind: "manipulate",
        headline: "Who is obliged to move",
        widget: "RightOfWayPicker",
        line: "Four situations. In one of them nobody has right of way at all.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Distress outranks everything",
          "Landing: the lower aircraft",
          "Balloon > glider > airship > airplane > helicopter",
          "Head-on: BOTH turn right · Overtaking: pass to the right",
        ],
      },
      { kind: "question", questionId: "fq-f8-007" },
      { kind: "question", questionId: "fq-f8-010" },
      { kind: "question", questionId: "fq-f8-011" },
      { kind: "question", questionId: "fcc-f8-013" },
      { kind: "question", questionId: "fq-f8-012" },
    ],
    questionIds: [
      "fq-f8-007",
      "fq-f8-008",
      "fq-f8-009",
      "fq-f8-010",
      "fq-f8-011",
      "fq-f8-012",
      "fcc-f8-013",
    ],
    memorize: ["Least manoeuvrable wins. Everything turns right."],
    sourceReferences: [AIR],
    explainerIds: ["fx-right-of-way"],
    labIds: ["flab-rules"],
  },
  {
    id: "fl31-altitude-and-airspeed",
    unit: "f8",
    index: 31,
    title: "Altitude and Airspeed Limits",
    subtitle: "The numbers that get asked",
    estimatedMinutes: 6,
    mapIcon: "frr-limits",
    enablingObjectives: ["2.381", "2.382"],
    conceptIds: [
      "fr-altitude-congested",
      "fr-altitude-other",
      "fr-altitude-cnaf",
      "fr-airspeed",
      "fr-holding-speed",
      "fr-cnaf-speed-exemption",
    ],
    masteryThreshold: 0.85,
    screens: [
      {
        kind: "hook",
        headline: "The airspeed limit under Class B is tighter than inside it",
        line: "That inversion is the most-missed number in the whole course. 250 inside, 200 underneath.",
      },
      {
        kind: "model",
        headline: "Minimum safe altitudes",
        diagram: { id: "frr-altitude", props: { setting: "congested" } },
        line: "Congested areas: 1,000 feet above the highest obstacle within a 2,000 foot radius. Elsewhere: 500 feet AGL.",
      },
      {
        kind: "model",
        headline: "Airspeed restrictions",
        diagram: { id: "frr-airspeed", props: { highlight: "underb" } },
        line: "250 below 10,000 MSL. 250 inside Class B. 200 beneath the Class B shelf. 200 within 4 nm of a Class C or D primary airport up to 2,500 AGL.",
      },
      {
        kind: "compare",
        headline: "CNAF's own altitude floors",
        line: "Stricter than the FAR, as usual.",
        columns: ["Situation", "Minimum"],
        rows: [
          { label: "VFR, fixed wing", a: "500 ft above terrain or water", b: "Except takeoff and landing, or mission need" },
          { label: "IFR outside controlled airspace", a: "1,000 ft above the highest obstacle within 22 miles", b: "" },
          { label: "IFR over designated mountainous terrain", a: "2,000 ft", b: "Within 22 miles of the intended line of flight" },
        ],
      },
      {
        kind: "manipulate",
        headline: "The floor depends on what is underneath you",
        widget: "AltitudeRulePicker",
        line: "Switch the terrain. The number changes, and so does what it is measured from.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Congested: 1,000 up, 2,000 out · Elsewhere: 500 AGL",
          "250 below 10,000 MSL · 250 inside B · 200 under B · 200 near C and D",
          "Holding: props 175, jets 230 below FL140 and 265 above, helos 80",
          "CNAF IFR uncontrolled: 1,000 ft within 22 miles, 2,000 ft over mountains",
        ],
      },
      { kind: "question", questionId: "fq-f8-018" },
      { kind: "question", questionId: "fq-f8-014" },
      { kind: "question", questionId: "fq-f8-019" },
      { kind: "question", questionId: "fq-f8-020" },
      { kind: "question", questionId: "fq-f8-021" },
      { kind: "question", questionId: "fq-f8-030" },
    ],
    questionIds: [
      "fq-f8-014",
      "fq-f8-015",
      "fq-f8-016",
      "fq-f8-017",
      "fq-f8-018",
      "fq-f8-019",
      "fq-f8-020",
      "fq-f8-021",
      "fq-f8-030",
    ],
    memorize: ["Under the shelf 200, inside B 250."],
    sourceReferences: [AIR],
    explainerIds: ["fx-airspeed"],
    labIds: ["flab-rules"],
  },
  {
    id: "fl32-disturbances-and-conduct",
    unit: "f8",
    index: 32,
    title: "Disturbances and Conduct",
    subtitle: "Noise, wildlife, TFRs, flat hatting",
    estimatedMinutes: 5,
    mapIcon: "frr-conduct",
    enablingObjectives: ["2.383", "2.384", "2.385", "2.386"],
    conceptIds: [
      "fr-careless",
      "fr-noise-sensitive",
      "fr-wildlife",
      "fr-tfr",
      "fr-commercial-avoidance",
      "fr-flat-hatting",
    ],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "The careless and reckless rule is not about actual danger",
        line: "It is about whether the person on the ground BELIEVES they are in danger. That is a much lower bar than most students expect.",
      },
      {
        kind: "rule",
        headline: "Careless and reckless flying",
        rule:
          "Naval aircraft shall be flown in a safe and non-threatening manner to both people and property on the ground. Particular effort shall be taken so that individuals do not believe they or their property are endangered.",
        appliesWhen: ["Any operation over people or property"],
        watchFor:
          "'Do not BELIEVE they are endangered.' The standard is the perception of the observer, not the judgment of the pilot.",
        authority: "CNAF M-3710.7",
      },
      {
        kind: "compare",
        headline: "The avoidance numbers",
        line: "Four different figures, four different subjects.",
        columns: ["Avoid", "By"],
        rows: [
          { label: "Noise-sensitive areas", a: "Below 3,000 ft AGL", b: "Resorts, beaches, breeding farms, national parks" },
          { label: "Wildlife habitations", a: "Maintain 3,000 ft AGL", b: "Conditions permitting" },
          { label: "Commercial and civil aircraft", a: "500 ft vertically and/or 1 SM laterally", b: "No erratic or aerobatic flight nearby" },
          { label: "TFRs", a: "Do not enter", b: "Exact dimensions in the NOTAM" },
        ],
      },
      {
        kind: "rule",
        headline: "Flat hatting",
        rule:
          "Any manoeuvre conducted at low altitude and/or high airspeed for thrill purposes over land or water is considered flat hatting, and is prohibited.",
        appliesWhen: ["Low altitude and/or high speed, flown for thrill purposes"],
        watchFor:
          "'For thrill purposes' is the whole definition. An identical profile flown for a mission is not flat hatting.",
        authority: "CNAF M-3710.7",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "The careless standard is what the observer believes",
          "Noise-sensitive and wildlife: 3,000 ft AGL",
          "Commercial carriers: 500 ft vertical, 1 SM lateral",
          "Flat hatting is low and/or fast for thrills, and is prohibited",
        ],
      },
      { kind: "question", questionId: "fq-f8-022" },
      { kind: "question", questionId: "fq-f8-023" },
      { kind: "question", questionId: "fq-f8-025" },
      { kind: "question", questionId: "fq-f8-026" },
      { kind: "question", questionId: "fq-f8-027" },
      { kind: "question", questionId: "fq-f8-028" },
    ],
    questionIds: [
      "fq-f8-022",
      "fq-f8-023",
      "fq-f8-024",
      "fq-f8-025",
      "fq-f8-026",
      "fq-f8-027",
      "fq-f8-028",
      "fq-f8-029",
    ],
    memorize: ["3,000 AGL for noise and wildlife. Flat hatting is thrills."],
    sourceReferences: [AIR],
  },
];
