import type { Lesson, SourceReference } from "@/lib/types";

const ORG: SourceReference = {
  document: "Flight Rules and Regulations Trainee Guide",
  chapter: "Federal Aviation Organization",
};
const VIFR: SourceReference = {
  document: "Flight Rules and Regulations Trainee Guide",
  chapter: "Visual / Instrument Flight Rules",
};

/**
 * FR&R lessons, units f1–f4: the rulebook, planning, the human, the airport.
 *
 * Lesson length follows the material rather than a template. A definition
 * lesson runs three or four minutes; a lesson carrying a table of numbers runs
 * longer because the retrieval has to carry more weight.
 */
export const LESSONS_A: Lesson[] = [
  /* ================= f1 · Rules and Regulators ================= */
  {
    id: "fl01-who-writes-the-rules",
    unit: "f1",
    index: 1,
    title: "Who Writes the Rules",
    subtitle: "Four publications, four authors",
    estimatedMinutes: 5,
    mapIcon: "frr-book",
    enablingObjectives: ["2.345", "2.346"],
    conceptIds: ["fr-far", "fr-aim", "fr-flip", "fr-cnaf", "fr-natops"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "Four organisations write the rules you fly by",
        line: "The FAA, the DOD, the Navy, and the people who built your aircraft. Knowing which wrote what is half of this unit.",
      },
      {
        kind: "compare",
        headline: "Who publishes what",
        line: "The FAA publishes two things, and only one of them is a regulation.",
        columns: ["Publication", "Author and nature"],
        rows: [
          { label: "FAR Part 91", a: "General operating and flight rules", b: "FAA · regulatory" },
          { label: "AIM", a: "Plain language amplification", b: "FAA · NON-regulatory" },
          { label: "FLIP", a: "En route charts, approach plates, planning guides", b: "DOD · all branches" },
          { label: "CNAF M-3710.7", a: "General procedures for all naval aircraft worldwide", b: "USN" },
          { label: "Aircraft NATOPS", a: "Procedures for one aircraft model", b: "USN · model specific" },
        ],
      },
      {
        kind: "chain",
        headline: "From broadest to narrowest",
        nodes: [
          { label: "FAA — everyone who flies in US airspace", trend: "none" },
          { label: "DOD — every branch of the armed services", trend: "none" },
          { label: "USN — every naval aircraft, worldwide", trend: "none" },
          { label: "NATOPS — one aircraft model", trend: "none" },
        ],
        footnote:
          "Each author writes for a narrower audience than the one above. That ordering is also the priority ordering, which is the next lesson.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "FAR Part 91 = general operating and flight rules, and the FAA part that most concerns you",
          "The AIM is FAA, and non-regulatory",
          "FLIP is DOD · CNAF M-3710.7 is Navy-wide · NATOPS is your aircraft",
        ],
      },
      { kind: "question", questionId: "fq-f1-001" },
      { kind: "question", questionId: "fq-f1-002" },
      { kind: "question", questionId: "fq-f1-003" },
      { kind: "question", questionId: "fq-f1-017" },
    ],
    questionIds: ["fq-f1-001", "fq-f1-002", "fq-f1-003", "fq-f1-017"],
    memorize: ["FAR regulates. The AIM explains."],
    sourceReferences: [ORG],
    explainerIds: ["fx-priority"],
  },
  {
    id: "fl02-priority-of-regulations",
    unit: "f1",
    index: 2,
    title: "Priority of Regulations",
    subtitle: "Which one wins",
    estimatedMinutes: 4,
    mapIcon: "frr-stack",
    enablingObjectives: ["2.347"],
    conceptIds: ["fr-priority", "fr-natops"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "When two publications disagree, one of them wins",
        line: "And the answer is always the same: the more specific the document, the higher it ranks.",
      },
      {
        kind: "model",
        headline: "The stack",
        diagram: { id: "frr-priority", props: { highlight: "natops" } },
        line: "Your aircraft's manual outranks the fleet-wide manual, which outranks the DOD publication, which outranks the FAA regulation.",
      },
      {
        kind: "chain",
        headline: "Highest to lowest",
        nodes: [
          { label: "Aircraft NATOPS", trend: "up", emphasis: true },
          { label: "CNAF M-3710.7", trend: "none" },
          { label: "FLIP", trend: "none" },
          { label: "FAR Part 91", trend: "down" },
        ],
        footnote:
          "CNAF is usually MORE stringent than the FAR rather than less, so following the tighter rule is normally the right instinct.",
      },
      {
        kind: "manipulate",
        headline: "Which document wins",
        widget: "PriorityPicker",
        line: "Pick one and see what it beats. Specific always outranks general.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "NATOPS → CNAF M-3710.7 → FLIP → FAR Part 91",
          "The aircraft-specific document always wins",
        ],
      },
      { kind: "question", questionId: "fcc-f1-004" },
      { kind: "question", questionId: "fq-f1-005" },
      { kind: "question", questionId: "ftap-f1-006" },
    ],
    questionIds: ["fcc-f1-004", "fq-f1-005", "ftap-f1-006"],
    memorize: ["NATOPS beats CNAF beats FLIP beats FAR."],
    sourceReferences: [ORG],
    explainerIds: ["fx-priority"],
  },
  {
    id: "fl03-shall-should-may-will",
    unit: "f1",
    index: 3,
    title: "Shall, Should, May, Will",
    subtitle: "Four words, four meanings",
    estimatedMinutes: 4,
    mapIcon: "frr-words",
    enablingObjectives: ["2.348"],
    conceptIds: ["fr-wording"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "In a regulation, ordinary words stop meaning ordinary things",
        line: "One of these four compels you. One of them compels nothing at all. They look almost identical in a sentence.",
      },
      {
        kind: "rule",
        headline: "The four words",
        rule:
          "Shall is used only when application of a procedure is mandatory. Should is used only when it is recommended. May is used only when it is optional. Will is used only to indicate futurity.",
        appliesWhen: [
          "Reading any CNAF M-3710.7 procedure",
          "Deciding whether a statement binds you or merely describes",
        ],
        watchFor:
          "'Will' carries NO degree of requirement. It only says something is going to happen — which is exactly why it appears in exam distractors.",
        authority: "CNAF M-3710.7",
      },
      {
        kind: "compare",
        headline: "The same sentence, four ways",
        line: "Watch what changes when only the verb changes.",
        columns: ["Wording", "What it obliges"],
        rows: [
          { label: "Shall", a: "The aircraft SHALL be configured", b: "You must" },
          { label: "Should", a: "The aircraft SHOULD be configured", b: "You are advised to" },
          { label: "May", a: "The aircraft MAY be configured", b: "Your choice" },
          { label: "Will", a: "The aircraft WILL be configured", b: "Nothing — it merely describes" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Shall = mandatory",
          "Should = recommended",
          "May = optional",
          "Will = futurity, never a requirement",
        ],
      },
      { kind: "question", questionId: "fq-f1-007" },
      { kind: "question", questionId: "fdl-f1-008" },
      { kind: "question", questionId: "fq-f1-016" },
    ],
    questionIds: ["fq-f1-007", "fdl-f1-008", "fq-f1-016"],
    memorize: ["Only 'shall' makes you do anything."],
    sourceReferences: [ORG],
  },
  {
    id: "fl04-air-traffic-control",
    unit: "f1",
    index: 4,
    title: "Air Traffic Control",
    subtitle: "One agency, four parts",
    estimatedMinutes: 6,
    mapIcon: "frr-atc",
    enablingObjectives: ["2.349"],
    conceptIds: ["fr-atc", "fr-fss", "fr-tower", "fr-approach", "fr-artcc"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "Four agencies, and the exam wants to know which does what",
        line: "The distinction that gets missed most often is between Approach and Center — terminal versus en route.",
      },
      {
        kind: "model",
        headline: "The organisation",
        diagram: { id: "frr-atc-org", props: { highlight: "none" } },
        line: "ATC enforces the FAR, approves flight plans and grants all clearances. Four subordinate agencies do the work.",
      },
      {
        kind: "compare",
        headline: "Who owns which airspace",
        line: "Read down the middle column — that is where the exam questions live.",
        columns: ["Agency", "Responsibility"],
        rows: [
          { label: "FSS", a: "Briefings, flight plan filing, NOTAMs, SAR, flight following", b: "Also called base ops" },
          { label: "Control Tower", a: "Safe, orderly, expeditious flow at and around the airport", b: "Air AND ground traffic" },
          { label: "Approach (TRACON)", a: "All instrument flight in the terminal area", b: "One or more airfields" },
          { label: "ARTCC", a: "Positive control of IFR aircraft en route", b: "Advisories to VFR when workload permits" },
        ],
      },
      {
        kind: "manipulate",
        headline: "Who owns this traffic",
        widget: "AtcOrgPicker",
        line: "Walk it inbound, from the en route structure down to the runway.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "ATC grants all IFR clearances",
          "Tower = at and around the airport",
          "Approach = terminal IFR · Center = en route IFR",
          "FSS = briefings, flight plans, search and rescue",
        ],
      },
      { kind: "question", questionId: "fq-f1-009" },
      { kind: "question", questionId: "fq-f1-010" },
      { kind: "question", questionId: "fq-f1-011" },
      { kind: "question", questionId: "fq-f1-012" },
    ],
    questionIds: ["fq-f1-009", "fq-f1-010", "fq-f1-011", "fq-f1-012", "fq-f1-013"],
    memorize: ["Approach owns the terminal area. Center owns en route."],
    sourceReferences: [ORG],
    explainerIds: ["fx-atc"],
  },
  {
    id: "fl05-notams-transponders",
    unit: "f1",
    index: 5,
    title: "NOTAMs and Transponders",
    subtitle: "Temporary information, and being seen",
    estimatedMinutes: 4,
    mapIcon: "frr-signal",
    enablingObjectives: ["2.349", "2.351"],
    conceptIds: ["fr-notam", "fr-transponder"],
    masteryThreshold: 0.7,
    screens: [
      {
        kind: "hook",
        headline: "Two ways the system tells you, and tells others about you",
        line: "A NOTAM carries what could not be published in time. A transponder answers for you when nobody can see you.",
      },
      {
        kind: "rule",
        headline: "NOTAM",
        rule:
          "A Notice to Airmen contains information concerning the establishment, condition or change in any aeronautical facility, service, procedure or hazard which is of a temporary nature and not known sufficiently in advance to publicise by other means.",
        appliesWhen: [
          "Preflight planning — NOTAMs are on the minimum list",
          "Temporary flight restrictions, whose exact dimensions are published this way",
        ],
        authority: "FAA",
      },
      {
        kind: "compare",
        headline: "What each mode reports",
        line: "Two modes, two different answers.",
        columns: ["Mode 3", "Mode C"],
        rows: [
          { label: "Reports", a: "Aircraft identity", b: "Pressure altitude" },
          { label: "Answers", a: "Who are you?", b: "How high are you?" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "NOTAM = temporary, or too late to publish otherwise",
          "Mode 3 identifies · Mode C reports pressure altitude",
          "ADS-B broadcasts GPS position, altitude and ground speed once per second",
        ],
      },
      { kind: "question", questionId: "fq-f1-014" },
      { kind: "question", questionId: "fq-f1-015" },
      { kind: "question", questionId: "fq-f1-018" },
    ],
    questionIds: ["fq-f1-014", "fq-f1-015", "fq-f1-018"],
    memorize: ["Mode 3 = who. Mode C = how high."],
    sourceReferences: [ORG],
  },

  /* ================= f2 · Planning and Responsibility ================= */
  {
    id: "fl06-pilot-in-command",
    unit: "f2",
    index: 6,
    title: "The Pilot in Command",
    subtitle: "Final authority",
    estimatedMinutes: 4,
    mapIcon: "frr-pic",
    enablingObjectives: ["2.350", "2.354"],
    conceptIds: ["fr-pic", "fr-deviation"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "One person is the final authority, and it is not ATC",
        line: "Which is also why one person is permitted to break the rules — but only under a very specific condition.",
      },
      {
        kind: "compare",
        headline: "What each publication says the PIC owns",
        line: "Together they cover the aircraft, the flight and the people in it.",
        columns: ["FAR", "CNAF M-3710.7"],
        rows: [
          {
            label: "Responsibility",
            a: "Directly responsible for, and final authority as to, the operation of that aircraft",
            b: "The safe, orderly flight of the aircraft and the well-being of the crew",
          },
        ],
      },
      {
        kind: "rule",
        headline: "Deviation authority",
        rule:
          "Deviation from specified flight and operating instructions is authorised in emergency situations when, in the judgment of the pilot in command, safety justifies such a deviation.",
        appliesWhen: [
          "An emergency situation exists",
          "The PIC judges that safety justifies the deviation",
        ],
        watchFor:
          "Mission requirement alone is not the trigger. The provision names emergencies, and the judgment is the PIC's.",
        authority: "CNAF M-3710.7",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "The PIC is responsible for the aircraft, the flight and the crew",
          "Deviation is permitted in emergencies, on the PIC's judgment",
        ],
      },
      { kind: "question", questionId: "fq-f2-001" },
      { kind: "question", questionId: "fq-f2-002" },
      { kind: "question", questionId: "ftrap-f2-012" },
    ],
    questionIds: ["fq-f2-001", "fq-f2-002", "ftrap-f2-012"],
    memorize: ["Aircraft, flight, crew. Deviation only in emergency."],
    sourceReferences: [ORG],
  },
  {
    id: "fl07-preflight-and-flight-plans",
    unit: "f2",
    index: 7,
    title: "Preflight and Flight Plans",
    subtitle: "What must be checked, and why you file",
    estimatedMinutes: 5,
    mapIcon: "frr-plan",
    enablingObjectives: ["2.351", "2.352"],
    conceptIds: ["fr-preflight", "fr-flight-plan"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "A flight plan is not a clearance",
        line: "Its real job only becomes obvious when something goes wrong and somebody has to come looking for you.",
      },
      {
        kind: "rule",
        headline: "Preflight planning",
        rule:
          "Preflight planning is a pilot in command responsibility, and at minimum includes available weather reports and forecasts, NOTAMs, fuel requirements, alternates available if the flight cannot be completed as planned, and any anticipated traffic delays.",
        appliesWhen: [
          "Every flight — local training flights included",
          "Urgent combat missions",
          "Flights departing uncontrolled airports with no tower",
        ],
        watchFor:
          "There is no familiarity exemption and no urgency exemption. The answer to 'when is preflight planning required' is all of the above.",
        authority: "CNAF M-3710.7",
      },
      {
        kind: "chain",
        headline: "What a flight plan is actually for",
        nodes: [
          { label: "You file departure, destination and intermediate agencies", trend: "none" },
          { label: "Communications are lost, or the aircraft is", trend: "down" },
          { label: "The plan is the baseline for finding you", trend: "up", emphasis: true },
        ],
        footnote: "Filed at base operations or a Flight Service Station.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Weather, NOTAMs, fuel, alternates, delays",
          "Preflight planning is required on every flight",
          "A flight plan's primary purpose is the lost communications and lost aircraft baseline",
        ],
      },
      { kind: "question", questionId: "fq-f2-003" },
      { kind: "question", questionId: "fq-f2-004" },
      { kind: "question", questionId: "fq-f2-005" },
    ],
    questionIds: ["fq-f2-003", "fq-f2-004", "fq-f2-005"],
    memorize: ["The flight plan exists so someone can find you."],
    sourceReferences: [ORG],
  },
  {
    id: "fl08-weather-brief",
    unit: "f2",
    index: 8,
    title: "The Weather Brief",
    subtitle: "DD-175-1 and two clocks",
    estimatedMinutes: 5,
    mapIcon: "frr-clock",
    enablingObjectives: ["2.353"],
    conceptIds: ["fr-weather-brief", "fr-icing-thunderstorms"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Two clocks start the moment you are briefed",
        line: "Whichever runs out first kills the brief. Reading it as 'whichever is later' is the single most common error here.",
      },
      {
        kind: "model",
        headline: "When the brief dies",
        diagram: { id: "frr-brief-void", props: { etd: 120 } },
        line: "Brief time plus 3 hours, or ETD plus 30 minutes. The earlier one wins.",
      },
      {
        kind: "manipulate",
        headline: "Move the ETD and watch which clock fires",
        widget: "BriefVoidWidget",
        line: "With an early departure the ETD clock governs. Push the ETD late enough and the three-hour clock takes over.",
      },
      {
        kind: "rule",
        headline: "Planning around weather",
        rule:
          "Flights shall be planned to circumvent areas of forecast atmospheric icing and thunderstorm conditions whenever practicable.",
        appliesWhen: ["Preflight planning, whenever those conditions are forecast"],
        watchFor: "The rule names icing and thunderstorms specifically, qualified by 'whenever practicable'.",
        authority: "CNAF M-3710.7",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Naval weather briefs are on a DD-175-1",
          "Void at brief + 3 hours, or ETD + 30 minutes — whichever is EARLIER",
          "Primary source is the Fleet Weather Brief",
        ],
      },
      { kind: "question", questionId: "fq-f2-006" },
      { kind: "question", questionId: "fsl-f2-007" },
      { kind: "question", questionId: "fq-f2-008" },
    ],
    questionIds: ["fq-f2-006", "fsl-f2-007", "fq-f2-008"],
    memorize: ["DD-175-1. Brief + 3, or ETD + 30. Earlier wins."],
    sourceReferences: [ORG],
    explainerIds: ["fx-brief-void"],
  },
  {
    id: "fl09-airfields-fuel-closing",
    unit: "f2",
    index: 9,
    title: "Airfields, Fuel and Closing Out",
    subtitle: "Before you go, and after you land",
    estimatedMinutes: 4,
    mapIcon: "frr-airfield",
    enablingObjectives: ["2.355"],
    conceptIds: ["fr-authorized-airfields", "fr-fuel-purchase", "fr-closing-plans"],
    masteryThreshold: 0.7,
    screens: [
      {
        kind: "hook",
        headline: "Three small rules that each carry an exception list",
        line: "Where you may land, where you may buy fuel, and who has to tell somebody you got there.",
      },
      {
        kind: "compare",
        headline: "Three responsibilities",
        line: "Each one has a specific list attached to it.",
        columns: ["Responsibility", "The detail"],
        rows: [
          {
            label: "Authorized airfields",
            a: "Prior permission required",
            b: "Know local procedures, runway length and load bearing, DoD contract services, security",
          },
          {
            label: "Fuel purchases",
            a: "Military or government contract sources",
            b: "Except mission requirements, emergency landings, alternate landings",
          },
          {
            label: "Closing flight plans",
            a: "PIC and formation leader",
            b: "Verbally to tower or base ops, or with an FSS by any means",
          },
        ],
      },
      {
        kind: "rule",
        headline: "Closing the flight plan",
        rule:
          "The pilot in command and the formation leader are responsible for closing out flight plans. This may be done verbally with the tower or base operations, or with a Flight Service Station by any means available.",
        appliesWhen: [
          "Every flight, on arrival",
          "Formation flights — the leader closes as well as the individual PIC",
        ],
        watchFor:
          "The responsibility is shared, not delegated. A question offering only one of the two is offering an incomplete answer.",
        authority: "CNAF M-3710.7",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Authorized airfields: prior permission required",
          "Fuel: military or contract, except mission, emergency, alternate",
          "Closing the plan is on BOTH the PIC and the formation leader",
        ],
      },
      { kind: "question", questionId: "fq-f2-009" },
      { kind: "question", questionId: "fq-f2-010" },
      { kind: "question", questionId: "fq-f2-011" },
    ],
    questionIds: ["fq-f2-009", "fq-f2-010", "fq-f2-011"],
    memorize: ["PIC and formation leader both own closing the plan."],
    sourceReferences: [ORG],
  },

  /* ================= f3 · Safety and the Human ================= */
  {
    id: "fl10-safety-equipment",
    unit: "f3",
    index: 10,
    title: "Safety and Survival Equipment",
    subtitle: "Harnesses, PPE, life rafts",
    estimatedMinutes: 5,
    mapIcon: "frr-ppe",
    enablingObjectives: ["2.356"],
    conceptIds: ["fr-harness", "fr-ppe", "fr-life-rafts"],
    masteryThreshold: 0.7,
    screens: [
      {
        kind: "hook",
        headline: "What you must be wearing before the aircraft moves",
        line: "The list is long, and the exam picks items off it — including the one that is not on it.",
      },
      {
        kind: "rule",
        headline: "Safety belts and harnesses",
        rule:
          "Shall be worn and tightened prior to takeoff and until completion of flight, except when necessary activities require removal. Inertial reels, when provided, shall be manually locked for takeoffs and landings and when high G forces are anticipated.",
        appliesWhen: [
          "From before takeoff until the flight is complete",
          "Reels locked for takeoff, landing and anticipated high G",
        ],
        watchFor: "Except where locking the reel would itself be detrimental to safety.",
        authority: "CNAF M-3710.7",
      },
      {
        kind: "chain",
        headline: "Minimum aircrew PPE",
        nodes: [
          { label: "Protective helmet", trend: "none" },
          { label: "Safety or flyer boots, fire-resistant suit and gloves", trend: "none" },
          { label: "Survival knife, personal survival kit, signal device", trend: "none" },
          { label: "Survival radio, emergency beacon, flashlight, ID tags", trend: "none" },
        ],
        footnote:
          "An inflatable life preserver is worn aboard ship, in ejection-seat aircraft, and on missions below 1,000 feet over water.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Belts and harnesses tightened before takeoff, worn until the flight ends",
          "Reels locked for takeoff, landing and high G",
          "Life rafts when there is significant risk of water entry",
        ],
      },
      { kind: "question", questionId: "fq-f3-010" },
      { kind: "question", questionId: "fq-f3-011" },
      { kind: "question", questionId: "fq-f3-013" },
    ],
    questionIds: ["fq-f3-010", "fq-f3-011", "fq-f3-013"],
    memorize: ["Helmet, boots, suit, gloves, knife, kit, signal, radio, beacon, light, tags."],
    sourceReferences: [ORG],
  },
  {
    id: "fl11-oxygen",
    unit: "f3",
    index: 11,
    title: "Oxygen Requirements",
    subtitle: "Three ceilings, one trigger",
    estimatedMinutes: 6,
    mapIcon: "frr-oxygen",
    enablingObjectives: ["2.357"],
    conceptIds: ["fr-oxygen", "fr-oxygen-unpressurized", "fr-oxygen-tacjet"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "One trigger altitude, then three different ceilings",
        line: "10,000 feet starts everything. What happens above it depends entirely on what equipment the aircraft has.",
      },
      {
        kind: "rule",
        headline: "The general rule",
        rule:
          "All occupants aboard naval aircraft shall use supplemental oxygen on flights in which the cabin altitude exceeds 10,000 feet.",
        appliesWhen: ["Cabin altitude — not aircraft altitude — exceeds 10,000 feet"],
        authority: "CNAF M-3710.7",
      },
      {
        kind: "model",
        headline: "Unpressurized, with an oxygen system",
        diagram: { id: "frr-oxygen", props: { altitude: 12000, equipped: true } },
        line: "The pilot and any aircrew doing physical work use oxygen continuously above 10,000. Where oxygen is not available to other occupants, 10,000–13,000 is limited to 3 hours and above 13,000 is prohibited.",
      },
      {
        kind: "compare",
        headline: "Three sets of limits",
        line: "The equipment fitted decides which set applies.",
        columns: ["Situation", "Limits"],
        rows: [
          { label: "Unpressurized, system fitted, no oxygen for others", a: "10,000–13,000 ft", b: "3 hours max · above 13,000 prohibited" },
          { label: "No oxygen system at all (e.g. helicopters)", a: "Above 10,000 ft", b: "Mission essential · 1 hour max · 12,000 ft ceiling" },
          { label: "Tactical jet and tac jet training", a: "All altitudes", b: "Oxygen from takeoff to landing" },
        ],
      },
      {
        kind: "manipulate",
        headline: "Raise the cabin and find the limits",
        widget: "OxygenWidget",
        line: "10,000 ft is the trigger. What happens above it depends on the equipment fitted.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Cabin altitude above 10,000 ft → oxygen for all occupants",
          "System fitted: 3 hours to 13,000 · No system: 1 hour to 12,000",
          "Tactical jets: oxygen from takeoff to landing",
        ],
      },
      { kind: "question", questionId: "fq-f3-001" },
      { kind: "question", questionId: "fq-f3-002" },
      { kind: "question", questionId: "fq-f3-003" },
      { kind: "question", questionId: "fq-f3-004" },
    ],
    questionIds: ["fq-f3-001", "fq-f3-002", "fq-f3-003", "fq-f3-004"],
    memorize: ["10,000 triggers it. 13,000 with a system, 12,000 without."],
    sourceReferences: [ORG],
    explainerIds: ["fx-oxygen"],
  },
  {
    id: "fl12-human-performance",
    unit: "f3",
    index: 12,
    title: "Human Performance",
    subtitle: "Rest, alcohol, caffeine, medication",
    estimatedMinutes: 5,
    mapIcon: "frr-human",
    enablingObjectives: ["2.358", "2.359"],
    conceptIds: [
      "fr-performance-factors",
      "fr-crew-rest",
      "fr-alcohol",
      "fr-caffeine-drugs",
      "fr-immunization-blood",
    ],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Five numbers, and each one is a likely question",
        line: "8, 18, 12, 450 and 4 — all attached to something different.",
      },
      {
        kind: "compare",
        headline: "The limits",
        line: "Note carefully what each clock is measured FROM.",
        columns: ["Limit", "Detail"],
        rows: [
          { label: "Crew rest", a: "8 hours uninterrupted sleep", b: "In every 24-hour period" },
          { label: "Crew day", a: "Should not exceed 18 hours", b: "" },
          { label: "Alcohol", a: "None within 12 hours", b: "Of the mission BRIEF or flight planning" },
          { label: "Caffeine", a: "450 mg per day recommended maximum", b: "About 3–4 cups of coffee" },
          { label: "Immunizations", a: "Grounded 12 hours", b: "" },
          { label: "Blood donation", a: "No flight duties for 4 days", b: "One pint" },
        ],
      },
      {
        kind: "rule",
        headline: "Medication",
        rule:
          "Use of BOTH prescription and over-the-counter drugs is prohibited for flight personnel unless specifically approved by a flight surgeon.",
        appliesWhen: ["Any medication at all, prescription or otherwise"],
        watchFor:
          "Over-the-counter is not exempt just because it needs no prescription. That is the trap.",
        authority: "CNAF M-3710.7",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "8 hours sleep per 24 · crew day not beyond 18 hours",
          "Alcohol: 12 hours from the BRIEF, not from takeoff",
          "Caffeine: 450 mg a day",
          "Blood: 4 days · Immunizations: 12 hours",
        ],
      },
      { kind: "question", questionId: "fq-f3-005" },
      { kind: "question", questionId: "fq-f3-006" },
      { kind: "question", questionId: "fq-f3-007" },
      { kind: "question", questionId: "fq-f3-008" },
      { kind: "question", questionId: "fq-f3-009" },
    ],
    questionIds: [
      "fq-f3-005",
      "fq-f3-006",
      "fq-f3-007",
      "fq-f3-008",
      "fq-f3-009",
      "fq-f3-012",
    ],
    memorize: ["8 and 18. Alcohol 12 from the brief. Caffeine 450. Blood 4 days."],
    sourceReferences: [ORG],
  },

  /* ================= f4 · The Airport ================= */
  {
    id: "fl13-runway-orientation",
    unit: "f4",
    index: 13,
    title: "Runway Orientation",
    subtitle: "Heading to number",
    estimatedMinutes: 4,
    mapIcon: "frr-runway",
    enablingObjectives: ["2.360"],
    conceptIds: ["fr-runway-numbering"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "The number painted on the runway is your magnetic heading",
        line: "Rounded to the nearest ten, with the last digit dropped.",
      },
      {
        kind: "model",
        headline: "Heading to runway number",
        diagram: { id: "frr-runway-numbering", props: { heading: 93 } },
        line: "093° rounds to 090, drop the zero, runway 09. The other end of the same strip is always the reciprocal.",
      },
      {
        kind: "manipulate",
        headline: "Swing the heading and read the number",
        widget: "RunwayNumberWidget",
        line: "Watch both ends change together — they always differ by 18.",
      },
      {
        kind: "compare",
        headline: "Both ends of one strip",
        line: "A runway has two numbers because it has two directions. They always differ by 18.",
        columns: ["Approach from", "Runway"],
        rows: [
          { label: "Heading 093°", a: "Rounds to 090°", b: "Runway 09" },
          { label: "Heading 273°", a: "Rounds to 270°", b: "Runway 27" },
          { label: "Heading 355°", a: "Rounds to 360°", b: "Runway 36" },
          { label: "Heading 178°", a: "Rounds to 180°", b: "Runway 18" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Round the magnetic heading to the nearest 10, drop the last digit",
          "The opposite end is the reciprocal — 09 and 27 are the same strip",
        ],
      },
      { kind: "question", questionId: "fq-f4-001" },
      { kind: "question", questionId: "fq-f4-017" },
      { kind: "question", questionId: "fq-f4-018" },
    ],
    questionIds: ["fq-f4-001", "fq-f4-017", "fq-f4-018"],
    memorize: ["Round to ten, drop a digit."],
    sourceReferences: [VIFR],
    labIds: ["flab-airport"],
  },
  {
    id: "fl14-signals-and-signs",
    unit: "f4",
    index: 14,
    title: "Signals and Signs",
    subtitle: "When the radio is out",
    estimatedMinutes: 5,
    mapIcon: "frr-lightgun",
    enablingObjectives: ["2.361"],
    conceptIds: ["fr-aldis", "fr-airport-signs", "fr-waveoff", "fr-wind-indicators", "fr-displaced-threshold"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "The airport can talk to you without a radio",
        line: "Light guns, signs, a windsock and a tetrahedron. Each says something different, and two of them are routinely confused.",
      },
      {
        kind: "model",
        headline: "Aldis lamp signals",
        diagram: { id: "frr-light-gun", props: { highlight: "green" } },
        line: "Steady green clears you to land. Steady red says give way and keep circling. Flashing white says return for landing.",
      },
      {
        kind: "compare",
        headline: "Wind sock versus tetrahedron",
        line: "They sit near each other and mean different things.",
        columns: ["Wind sock", "Tetrahedron"],
        rows: [
          { label: "Indicates", a: "Wind direction and approximate velocity", b: "Direction of landing and takeoff" },
          { label: "Lights", a: "—", b: "Green on the port base, red on the starboard base and spine" },
        ],
      },
      {
        kind: "rule",
        headline: "Waveoff",
        rule:
          "A waveoff means DO NOT LAND. Compliance is mandatory, except in an emergency. Any high intensity red lights at the approach end should be treated as a waveoff signal.",
        appliesWhen: ["Whenever the signal is given, from any source"],
        watchFor:
          "Mandatory means mandatory. The only exception is an emergency in your own aircraft.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Steady green = cleared to land · Flashing white = return for landing",
          "Mandatory instruction signs: white letters on red",
          "Sock = wind · Tetrahedron = landing direction",
          "Displaced threshold: takeoff and rollout, never landing",
        ],
      },
      { kind: "question", questionId: "fq-f4-005" },
      { kind: "question", questionId: "ftap-f4-006" },
      { kind: "question", questionId: "fq-f4-002" },
      { kind: "question", questionId: "fq-f4-003" },
      { kind: "question", questionId: "fq-f4-004" },
    ],
    questionIds: [
      "fq-f4-002",
      "fq-f4-003",
      "fq-f4-004",
      "fq-f4-005",
      "ftap-f4-006",
      "fq-f4-007",
      "fq-f4-014",
    ],
    memorize: ["Steady green clears you. Flashing white sends you around."],
    sourceReferences: [VIFR],
    explainerIds: ["fx-light-gun"],
  },
  {
    id: "fl15-airport-lighting",
    unit: "f4",
    index: 15,
    title: "Airport Lighting",
    subtitle: "Reading the field by colour",
    estimatedMinutes: 5,
    mapIcon: "frr-lights",
    enablingObjectives: ["2.361"],
    conceptIds: ["fr-runway-lighting", "fr-beacon", "fr-als"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "Every colour on the field means one thing",
        line: "And one pair of lights means opposite things depending on which end you are looking from.",
      },
      {
        kind: "compare",
        headline: "The colour code",
        line: "Learn it as a list; the exam asks it as a list.",
        columns: ["Element", "Colour"],
        rows: [
          { label: "Runway edges", a: "White", b: "HIRL / MIRL / LIRL by intensity" },
          { label: "Runway ends", a: "Green approaching (threshold)", b: "Red from the runway (overrun)" },
          { label: "Touchdown zone", a: "White", b: "3,000 ft or midpoint, whichever is less" },
          { label: "Runway centerline", a: "White, then white/red, then red", b: "Red for the final 1,000 ft" },
          { label: "Taxiway edges / centerline", a: "Blue / green", b: "Turnoff lights green" },
          { label: "Obstructions", a: "White strobes, or red flashing or steady", b: "" },
        ],
      },
      {
        kind: "rule",
        headline: "Airport rotating beacon",
        rule:
          "The rotating beacon indicates the location of a lighted airport. A civilian beacon alternates solid white with solid green; a military beacon shows dual-peaked white flashes alternating with a green flash.",
        appliesWhen: [
          "Sunset to sunrise",
          "Sometimes during daylight when visibility is restricted",
        ],
        watchFor: "Two quick white flashes is what marks the field as military.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Green approaching = threshold · Red from the runway = overrun",
          "Centerline: white, then alternating for 2,000 ft, then red for the last 1,000 ft",
          "Taxiway: blue edges, green centerline",
          "Two quick whites on the beacon = military field",
        ],
      },
      { kind: "question", questionId: "fq-f4-010" },
      { kind: "question", questionId: "fq-f4-011" },
      { kind: "question", questionId: "fq-f4-012" },
      { kind: "question", questionId: "fq-f3-014" },
    ],
    questionIds: ["fq-f4-010", "fq-f4-011", "fq-f4-012", "fq-f4-013", "fq-f3-014"],
    memorize: ["Blue edges, green centerline. Red is always the end."],
    sourceReferences: [VIFR],
  },
  {
    id: "fl16-glideslope-indicators",
    unit: "f4",
    index: 16,
    title: "Glideslope Indicators",
    subtitle: "VASI, IFLOLS, SGSI",
    estimatedMinutes: 5,
    mapIcon: "frr-vasi",
    enablingObjectives: ["2.361"],
    conceptIds: ["fr-vasi", "fr-iflols", "fr-sgsi"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "Three systems, three colour languages",
        line: "Ashore you read a VASI. Aboard ship you read a ball or a beam. All three answer the same question.",
      },
      {
        kind: "model",
        headline: "VASI",
        diagram: { id: "frr-vasi", props: { state: "on" } },
        line: "Red over white is on glideslope. All white is high. All red is low.",
      },
      {
        kind: "manipulate",
        headline: "Fly the VASI",
        widget: "VasiWidget",
        line: "Move above and below the slope and watch the bars change.",
      },
      {
        kind: "compare",
        headline: "Shipboard systems",
        line: "Different hardware, same three answers.",
        columns: ["IFLOLS", "SGSI"],
        rows: [
          { label: "On glideslope", a: "Amber ball aligned with the green datum bar", b: "Amber-red interface" },
          { label: "Below", a: "Ball below the datum, turns red", b: "Red" },
          { label: "Above", a: "Ball above the datum", b: "Amber slightly above · green well above" },
          { label: "Used for", a: "Ships and many Naval air stations", b: "Shipboard helicopter operations" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "VASI: red over white, you're alright · red over red, you're dead",
          "IFLOLS: ball on the green datum = on glideslope",
          "SGSI: red is low, amber-red interface is on",
        ],
      },
      { kind: "question", questionId: "fq-f4-008" },
      { kind: "question", questionId: "fbf-f4-009" },
      { kind: "question", questionId: "fq-f4-015" },
      { kind: "question", questionId: "fq-f4-016" },
    ],
    questionIds: ["fq-f4-008", "fbf-f4-009", "fq-f4-015", "fq-f4-016"],
    memorize: ["Red over white, you're alright."],
    sourceReferences: [VIFR],
    explainerIds: ["fx-glideslope"],
    labIds: ["flab-airport"],
  },
];
