import type { Lesson, SourceReference } from "@/lib/types";

const L201: SourceReference = {
  document: "Principles of Gas Turbine/Reciprocating Operation",
  chapter: "Principles of Gas Turbine/Reciprocating Operation",
};
const L202: SourceReference = {
  document: "Gas Turbine/Reciprocating Engines",
  chapter: "Gas Turbine/Reciprocating Engines",
};

/**
 * Engines lessons, units e1–e4: principles, thrust, and the gas path from
 * inlet to exhaust. The cutaway recurs on purpose — every fact in this half of
 * the course should end up pinned to a location on that silhouette.
 */
export const LESSONS_A: Lesson[] = [
  /* ================= e1 · Principles ================= */
  {
    id: "el01-pressure-and-velocity",
    unit: "e1",
    index: 1,
    title: "Pressure, Velocity, Total",
    subtitle: "The two things air carries",
    estimatedMinutes: 5,
    mapIcon: "eng-pressure",
    enablingObjectives: ["1.1"],
    conceptIds: ["e-static-pressure", "e-dynamic-pressure", "e-total-pressure"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "Inside an engine, two familiar words change meaning",
        line: "'Pressure' means static. 'Velocity' means dynamic. Get that straight now and half of unit 1 stops being confusing.",
      },
      {
        kind: "model",
        headline: "Total pressure is a fixed budget",
        diagram: { id: "eng-pressure-split", props: { dynamic: 0.35 } },
        line: "Static is the energy of molecules at rest. Dynamic is the energy of molecules in motion. Together they are total pressure.",
        bullets: [
          "Static pressure = potential of molecules at rest",
          "Dynamic pressure = kinetic energy of molecules in motion",
          "Total = static + dynamic",
        ],
      },
      {
        kind: "manipulate",
        headline: "Spend one, gain the other",
        widget: "EnginePressureSplit",
        line: "Slide the split. Total never changes — the two components just trade.",
      },
      {
        kind: "chain",
        headline: "The trade, in one line",
        nodes: [
          { label: "Static pressure decreases", trend: "down" },
          { label: "Dynamic pressure increases", trend: "up" },
          { label: "Total pressure unchanged", trend: "same", emphasis: true },
        ],
        footnote:
          "This only holds in a closed system. The compressor adds energy, so total pressure rises across it.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "In the engine: pressure = static, velocity = dynamic",
          "Total pressure = static + dynamic",
          "One goes down, the other goes up",
        ],
        formula: "P_{total} = P_{static} + P_{dynamic}",
      },
      { kind: "question", questionId: "eq-e1-001" },
      { kind: "question", questionId: "eq-e1-002" },
      { kind: "question", questionId: "esl-e1-003" },
    ],
    questionIds: ["eq-e1-001", "eq-e1-002", "esl-e1-003"],
    memorize: ["Pressure = static. Velocity = dynamic. Total = both."],
    sourceReferences: [L201],
    explainerIds: ["ex-pressure-budget"],
  },
  {
    id: "el02-nozzles-and-diffusers",
    unit: "e1",
    index: 2,
    title: "Nozzles and Diffusers",
    subtitle: "What a duct does to subsonic air",
    estimatedMinutes: 6,
    mapIcon: "eng-duct",
    enablingObjectives: ["1.2"],
    conceptIds: ["e-subsonic-convergent", "e-subsonic-divergent", "e-nozzle", "e-diffuser"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "A nozzle is a job, not a shape",
        line: "Nozzles always speed air up. Diffusers always slow it down. The shape that achieves it depends on the speed of the flow.",
      },
      {
        kind: "model",
        headline: "Subsonic through a convergent duct",
        diagram: { id: "eng-duct", props: { shape: "convergent", regime: "subsonic" } },
        line: "Squeeze incompressible flow and it speeds up, losing static pressure. This is Bernoulli.",
      },
      {
        kind: "model",
        headline: "Subsonic through a divergent duct",
        diagram: { id: "eng-duct", props: { shape: "divergent", regime: "subsonic" } },
        line: "Open the duct out and subsonic flow slows down, gaining pressure. This is exactly what an inlet duct is for.",
      },
      {
        kind: "compare",
        headline: "Nozzle versus diffuser",
        line: "Memorise the effect, then derive the shape.",
        columns: ["Nozzle", "Diffuser"],
        rows: [
          { label: "Velocity", a: "Always increases", b: "Always decreases" },
          { label: "Pressure", a: "Always decreases", b: "Always increases" },
          { label: "Shape if subsonic", a: "Convergent", b: "Divergent" },
          { label: "Shape if supersonic", a: "Divergent", b: "Convergent" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Nozzle → velocity up, pressure down. Always.",
          "Diffuser → velocity down, pressure up. Always.",
          "Subsonic + convergent → faster. Subsonic + divergent → slower.",
        ],
      },
      { kind: "question", questionId: "eq-e1-005" },
      { kind: "question", questionId: "eq-e1-006" },
      { kind: "question", questionId: "eq-e1-010" },
      { kind: "question", questionId: "eq-e1-011" },
    ],
    questionIds: ["eq-e1-005", "eq-e1-006", "eq-e1-010", "eq-e1-011", "etrap-e1-012"],
    memorize: ["Nozzle speeds up. Diffuser slows down. Shape follows the speed regime."],
    sourceReferences: [L201],
    labIds: ["elab-duct"],
  },
  {
    id: "el03-supersonic-reversal",
    unit: "e1",
    index: 3,
    title: "Supersonic Reverses the Rules",
    subtitle: "The same duct, the opposite result",
    estimatedMinutes: 6,
    mapIcon: "eng-supersonic",
    enablingObjectives: ["1.3"],
    conceptIds: ["e-compressibility", "e-supersonic-ducts"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Everything you just learned flips above Mach 1",
        line: "This is the most reliable trap in the whole block, and it exists for one physical reason: compressibility.",
      },
      {
        kind: "model",
        headline: "Why it flips",
        diagram: { id: "eng-duct", props: { shape: "convergent", regime: "supersonic" } },
        line: "Air is a compressible fluid, but subsonic airflow behaves as though it is not. Approaching supersonic speed, compressibility takes over and the duct behaves the other way round.",
        bullets: [
          "Supersonic + convergent → velocity down, pressure up",
          "Supersonic + divergent → velocity up, pressure down",
        ],
      },
      {
        kind: "manipulate",
        headline: "Flip the regime, watch the arrows swap",
        widget: "DuctRegimeToggle",
        line: "Same geometry either side of Mach 1. Only the speed regime decides the outcome.",
      },
      {
        kind: "chain",
        headline: "Why a supersonic exhaust nozzle is convergent/divergent",
        nodes: [
          { label: "Convergent section accelerates gas toward Mach 1", trend: "up" },
          { label: "Flow reaches sonic speed", trend: "same" },
          { label: "Divergent section accelerates it further", trend: "up", emphasis: true },
        ],
        footnote: "The shape changes halfway because the physics does.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Supersonic does the OPPOSITE of subsonic",
          "The shape does not decide the outcome — the speed regime does",
          "Supersonic nozzle = divergent. Supersonic diffuser = convergent.",
        ],
      },
      { kind: "question", questionId: "eq-e1-004" },
      { kind: "question", questionId: "eq-e1-007" },
      { kind: "question", questionId: "eq-e1-008" },
      { kind: "question", questionId: "ebf-e1-009" },
      { kind: "question", questionId: "etrap-e1-012" },
    ],
    questionIds: ["eq-e1-004", "eq-e1-007", "eq-e1-008", "ebf-e1-009", "etrap-e1-012"],
    memorize: ["Above Mach 1 every duct does the opposite of what Bernoulli says."],
    sourceReferences: [L201],
    explainerIds: ["ex-supersonic-flip"],
    labIds: ["elab-duct"],
  },
  {
    id: "el04-gas-generator-and-cycles",
    unit: "e1",
    index: 4,
    title: "The Gas Generator",
    subtitle: "Three sections, two cycles",
    estimatedMinutes: 6,
    mapIcon: "eng-core",
    enablingObjectives: ["1.4", "1.5", "1.6", "1.7"],
    conceptIds: ["e-gas-generator", "e-brayton", "e-otto", "e-station-changes"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "Three sections make an engine an engine",
        line: "Compressor, combustion chamber, turbine. Everything else is plumbing bolted to the front and back.",
      },
      {
        kind: "model",
        headline: "The gas path",
        diagram: { id: "eng-cutaway", props: { highlight: "all" } },
        line: "Air enters at the left, is squeezed, burned, expanded through the turbine, and thrown out the back.",
        bullets: [
          "Gas generator = compressor + combustion chamber + turbine",
          "The inlet and exhaust attach to it but are not part of it",
        ],
      },
      {
        kind: "model",
        headline: "What each section does to the air",
        diagram: { id: "eng-station-changes" },
        line: "Read this table across, not down. Combustion is the one that surprises people — pressure drops slightly.",
      },
      {
        kind: "model",
        headline: "Brayton and Otto: same events, different timing",
        diagram: { id: "eng-cycles", props: { cycle: "both" } },
        line: "Both cycles are intake, compression, combustion, exhaust. The turbine does all four at once; the piston does them in turn.",
      },
      {
        kind: "manipulate",
        headline: "Follow one parcel of air through the engine",
        widget: "EngineStationStepper",
        line: "Step the stations. Watch which of pressure, temperature and velocity moves at each one.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Gas generator = compressor + combustion chamber + turbine",
          "Brayton = simultaneous. Otto = sequential.",
          "Combustion: temperature up, velocity up, pressure slightly DOWN",
        ],
        mnemonic: "Otto goes suck, squeeze, bang, blow — one at a time.",
      },
      { kind: "question", questionId: "eq-e1-013" },
      { kind: "question", questionId: "etap-e1-014" },
      { kind: "question", questionId: "eq-e1-015" },
      { kind: "question", questionId: "ecc-e1-017" },
      { kind: "question", questionId: "eq-e1-018" },
    ],
    questionIds: [
      "eq-e1-013",
      "etap-e1-014",
      "eq-e1-015",
      "eq-e1-016",
      "ecc-e1-017",
      "eq-e1-018",
      "eq-e1-019",
      "eq-e1-020",
    ],
    memorize: ["Compressor, combustion chamber, turbine. Brayton all at once."],
    sourceReferences: [L201],
    explainerIds: ["ex-air-through-engine"],
    labIds: ["elab-flow"],
  },

  /* ================= e2 · Thrust ================= */
  {
    id: "el05-thrust-equation",
    unit: "e2",
    index: 5,
    title: "Thrust = Mass × Acceleration",
    subtitle: "Gross, net, and what they measure",
    estimatedMinutes: 5,
    mapIcon: "eng-thrust",
    enablingObjectives: ["1.8"],
    conceptIds: ["e-thrust-equation", "e-gross-thrust", "e-net-thrust"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "Every thrust question is this one equation",
        line: "T = m × a. Anything that changes thrust changes either the mass of air or its acceleration. Find which, and the answer follows.",
      },
      {
        kind: "compare",
        headline: "Gross versus net thrust",
        line: "One difference, and the exam asks about it directly.",
        columns: ["Gross thrust", "Net thrust"],
        rows: [
          { label: "Inlet velocity", a: "Ignored", b: "Corrected for" },
          { label: "Measured", a: "Stationary engine or ground run-up", b: "Realistic in-flight value" },
          { label: "Conditions", a: "Standard day, 29.92 inHg and 15 °C", b: "Actual" },
          { label: "Usual meaning of 'thrust'", a: "No", b: "Yes" },
        ],
      },
      {
        kind: "chain",
        headline: "When are they equal?",
        nodes: [
          { label: "Inlet velocity is zero", trend: "none" },
          { label: "Nothing to correct for", trend: "same" },
          { label: "Net thrust = gross thrust", trend: "same", emphasis: true },
        ],
        footnote: "At standard day conditions.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "T = m × a",
          "Gross ignores inlet velocity; net corrects for it",
          "Equal only when inlet velocity is zero",
        ],
        formula: "T_{net} = m \\times \\frac{V_{final} - V_{initial}}{t}",
      },
      { kind: "question", questionId: "eq-e2-001" },
      { kind: "question", questionId: "eq-e2-002" },
      { kind: "question", questionId: "eq-e2-003" },
      { kind: "question", questionId: "eq-e2-018" },
    ],
    questionIds: ["eq-e2-001", "eq-e2-002", "eq-e2-003", "eq-e2-018"],
    memorize: ["T = m × a. Gross ignores the inlet, net corrects for it."],
    sourceReferences: [L201],
  },
  {
    id: "el06-density-and-thrust",
    unit: "e2",
    index: 6,
    title: "Density Drives Thrust",
    subtitle: "Temperature, pressure, altitude",
    estimatedMinutes: 7,
    mapIcon: "eng-density",
    enablingObjectives: ["1.9", "1.10", "1.11"],
    conceptIds: [
      "e-density-thrust",
      "e-temperature-thrust",
      "e-pressure-thrust",
      "e-altitude-thrust",
    ],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Three factors, one mechanism",
        line: "Temperature, pressure and altitude do not each have their own rule. They all reach thrust through density.",
      },
      {
        kind: "chain",
        headline: "The chain every atmospheric factor runs through",
        nodes: [
          { label: "Air density changes", trend: "none" },
          { label: "Mass of air through the engine changes", trend: "none" },
          { label: "Thrust changes, because T = m × a", trend: "none", emphasis: true },
        ],
        footnote: "Learn this once instead of memorising three separate arrows.",
      },
      {
        kind: "model",
        headline: "Colder air is denser air",
        diagram: { id: "eng-thrust-factor", props: { factor: "temperature" } },
        line: "Lower temperature packs molecules closer together, raising density and therefore thrust.",
      },
      {
        kind: "model",
        headline: "Altitude: two effects, one winner",
        diagram: { id: "eng-thrust-factor", props: { factor: "altitude", marker: 20 } },
        line: "Climbing gives you colder air, which helps, and lower pressure, which hurts. Pressure wins, so thrust falls.",
        bullets: [
          "Above 36,000 ft temperature stabilises",
          "With nothing offsetting pressure, thrust falls off more rapidly",
        ],
      },
      {
        kind: "manipulate",
        headline: "Climb the aircraft and watch thrust go",
        widget: "ThrustFactorExplorer",
        line: "Switch factors and read the direction. The break at 36,000 ft is worth finding yourself.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Temperature ↓ → density ↑ → thrust ↑",
          "Pressure ↓ → density ↓ → thrust ↓",
          "Altitude ↑ → thrust ↓, because pressure beats temperature",
          "Above 36,000 ft thrust falls faster",
        ],
      },
      { kind: "question", questionId: "eq-e2-004" },
      { kind: "question", questionId: "eq-e2-005" },
      { kind: "question", questionId: "eq-e2-007" },
      { kind: "question", questionId: "eq-e2-008" },
      { kind: "question", questionId: "ecc-e2-013" },
    ],
    questionIds: [
      "eq-e2-004",
      "eq-e2-005",
      "eq-e2-006",
      "eq-e2-007",
      "eq-e2-008",
      "ecs-e2-009",
      "ecc-e2-013",
      "eq-e2-019",
    ],
    memorize: ["Everything atmospheric works through density."],
    sourceReferences: [L201],
    explainerIds: ["ex-density-thrust"],
    labIds: ["elab-thrust"],
  },
  {
    id: "el07-rpm-airspeed-ram",
    unit: "e2",
    index: 7,
    title: "RPM, Airspeed and Ram",
    subtitle: "The three non-atmospheric factors",
    estimatedMinutes: 6,
    mapIcon: "eng-rpm",
    enablingObjectives: ["1.12", "1.13", "1.14"],
    conceptIds: ["e-rpm-thrust", "e-airspeed-thrust", "e-ram-effect"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Airspeed takes thrust away. Ram effect gives it back.",
        line: "These two are always tested together, because either one alone gives the wrong answer.",
      },
      {
        kind: "model",
        headline: "RPM is not linear",
        diagram: { id: "eng-thrust-factor", props: { factor: "rpm", marker: 90 } },
        line: "At low RPM a throttle push buys almost nothing. At high RPM a small push buys a lot.",
      },
      {
        kind: "model",
        headline: "Airspeed alone erodes thrust",
        diagram: { id: "eng-thrust-factor", props: { factor: "airspeed" } },
        line: "As inlet velocity approaches exhaust velocity, the difference between them shrinks — and that difference is the acceleration term.",
      },
      {
        kind: "chain",
        headline: "Then ram effect intervenes",
        nodes: [
          { label: "Airspeed increases", trend: "up" },
          { label: "More molecules rammed into the inlet", trend: "up" },
          { label: "Mass increases", trend: "up" },
          { label: "Subsonic: thrust roughly constant", trend: "same", emphasis: true },
          { label: "Supersonic: thrust increases greatly", trend: "up", emphasis: true },
        ],
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "RPM ↑ → thrust ↑, and the effect grows with RPM",
          "Airspeed alone → thrust ↓",
          "Ram effect keeps thrust constant subsonic, increases it supersonic",
        ],
      },
      { kind: "question", questionId: "eq-e2-010" },
      { kind: "question", questionId: "eq-e2-011" },
      { kind: "question", questionId: "eq-e2-012" },
      { kind: "question", questionId: "etrap-e2-017" },
    ],
    questionIds: ["eq-e2-010", "eq-e2-011", "eq-e2-012", "etrap-e2-017"],
    memorize: ["Airspeed hurts thrust; ram effect pays it back."],
    sourceReferences: [L201],
    labIds: ["elab-thrust"],
  },
  {
    id: "el08-thrust-instruments",
    unit: "e2",
    index: 8,
    title: "Reading Thrust in the Cockpit",
    subtitle: "EPR, torquemeter, tachometer",
    estimatedMinutes: 4,
    mapIcon: "eng-gauge",
    enablingObjectives: ["1.15"],
    conceptIds: ["e-epr", "e-torquemeter", "e-tachometer"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "Which gauge you read depends on where the thrust comes from",
        line: "Jets read a pressure ratio. Propellers read shaft power. Everyone watches RPM.",
      },
      {
        kind: "compare",
        headline: "Three instruments",
        line: "The pairing with engine type is the exam question.",
        columns: ["Measures thrust", "Monitors only"],
        rows: [
          { label: "EPR", a: "Inlet-to-exhaust pressure ratio", b: "—" },
          { label: "Torquemeter", a: "Shaft horsepower to prop or rotor", b: "—" },
          { label: "Tachometer", a: "—", b: "Engine rotation, percent RPM" },
          { label: "Used on", a: "EPR: turbojet/turbofan · Torque: turboprop/turboshaft", b: "All types" },
        ],
      },
      {
        kind: "model",
        headline: "One gauge, read three ways",
        diagram: { id: "eng-stall-indications", props: { stalled: false } },
        line: "Whatever the instrument, you are inferring how hard the engine is working. Only EPR and the torquemeter actually quantify thrust.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "EPR → turbojet and turbofan",
          "Torquemeter → propeller and rotor aircraft",
          "Tachometer → percent RPM, monitors but does not measure thrust",
        ],
      },
      { kind: "question", questionId: "eq-e2-014" },
      { kind: "question", questionId: "eq-e2-015" },
      { kind: "question", questionId: "eq-e2-016" },
    ],
    questionIds: ["eq-e2-014", "eq-e2-015", "eq-e2-016", "eq-e2-020"],
    memorize: ["EPR for jets, torquemeter for props, tachometer for everyone."],
    sourceReferences: [L201],
  },

  /* ================= e3 · Inlet and Compressor ================= */
  {
    id: "el09-inlet-ducts",
    unit: "e3",
    index: 9,
    title: "Inlet Ducts",
    subtitle: "The first diffuser",
    estimatedMinutes: 5,
    mapIcon: "eng-inlet",
    enablingObjectives: ["2.1"],
    conceptIds: ["e-inlet-purpose", "e-single-entrance", "e-divided-entrance"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "The compressor is fussy about what it is fed",
        line: "High pressure, steady, uniform, turbulence-free. Fail any of those and you get a compressor stall three sections later.",
      },
      {
        kind: "model",
        headline: "Where the inlet sits",
        diagram: { id: "eng-cutaway", props: { highlight: "inlet" } },
        line: "The inlet is designed to act as a diffuser: it slows the air down and raises its pressure before the first compressor stage.",
      },
      {
        kind: "compare",
        headline: "Single versus divided entrance",
        line: "Each buys something and costs something.",
        columns: ["Single entrance", "Divided entrance"],
        rows: [
          { label: "Simplicity", a: "Simplest and most efficient", b: "More complex" },
          { label: "Duct length", a: "Often long on single-engine aircraft", b: "Shorter" },
          { label: "Friction loss", a: "Higher on long ducts", b: "Less" },
          { label: "Turbulence", a: "Undisturbed air", b: "More inlet air turbulence" },
          { label: "Weakness", a: "Short ducts stall at low speed / high AOA", b: "Turbulence" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Inlet purpose: high pressure, turbulence-free, steady, uniform air to the first compressor stage",
          "Inlet ducts act as diffusers",
          "Divided entrance: less friction, MORE turbulence",
        ],
      },
      { kind: "question", questionId: "eq-e3-001" },
      { kind: "question", questionId: "eq-e3-002" },
      { kind: "question", questionId: "eq-e3-003" },
      { kind: "question", questionId: "eq-e3-004" },
    ],
    questionIds: ["eq-e3-001", "eq-e3-002", "eq-e3-003", "eq-e3-004"],
    memorize: ["The inlet is a diffuser: pressure up, velocity down."],
    sourceReferences: [L202],
  },
  {
    id: "el10-inlet-geometry",
    unit: "e3",
    index: 10,
    title: "Inlet Geometry",
    subtitle: "Subsonic, supersonic, variable",
    estimatedMinutes: 5,
    mapIcon: "eng-variable",
    enablingObjectives: ["2.1"],
    conceptIds: ["e-inlet-geometry", "e-variable-geometry-inlet"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "The inlet must stay a diffuser at any speed",
        line: "Since supersonic flow reverses the rules, keeping the same job means changing the shape.",
      },
      {
        kind: "chain",
        headline: "Why a supersonic inlet needs two sections",
        nodes: [
          { label: "Convergent section slows supersonic flow", trend: "down" },
          { label: "Flow drops below supersonic", trend: "same" },
          { label: "Divergent section slows it further and raises pressure", trend: "up", emphasis: true },
        ],
        footnote: "Both halves are doing the same job — diffusing — under different physics.",
      },
      {
        kind: "model",
        headline: "Variable geometry",
        diagram: { id: "eng-duct", props: { shape: "divergent", regime: "subsonic" } },
        line: "Ramps, cones and wedges physically change the duct shape as the aircraft accelerates: divergent subsonic, convergent/divergent supersonic.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Subsonic inlet = divergent",
          "Supersonic inlet = convergent/divergent",
          "Variable geometry keeps it a diffuser throughout",
        ],
      },
      { kind: "question", questionId: "eq-e3-005" },
      { kind: "question", questionId: "eq-e3-006" },
      { kind: "question", questionId: "eq-e1-008" },
    ],
    questionIds: ["eq-e3-005", "eq-e3-006", "eq-e1-008"],
    memorize: ["Subsonic inlet divergent, supersonic inlet convergent/divergent."],
    sourceReferences: [L202],
  },
  {
    id: "el11-centrifugal-compressor",
    unit: "e3",
    index: 11,
    title: "Centrifugal Compressors",
    subtitle: "Impeller, diffuser, manifold",
    estimatedMinutes: 5,
    mapIcon: "eng-centrifugal",
    enablingObjectives: ["2.2"],
    conceptIds: ["e-compressor-purpose", "e-centrifugal-compressor", "e-centrifugal-tradeoffs"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "Fling the air outward, then catch it",
        line: "The impeller adds speed. The diffuser converts that speed into the pressure combustion needs.",
      },
      {
        kind: "model",
        headline: "Three components",
        diagram: { id: "eng-centrifugal" },
        line: "Air enters at the hub, is thrown to the rim by the impeller, slowed and pressurised by the diffuser, then routed onward by the manifold.",
        bullets: [
          "Impeller — velocity increases (and its divergent blade shape raises pressure)",
          "Diffuser — stationary, converts high velocity to high pressure",
          "Manifold — directs airflow to the combustion chambers",
        ],
      },
      {
        kind: "compare",
        headline: "What it buys and what it costs",
        line: "Every compressor question is a trade-off question.",
        columns: ["Advantages", "Disadvantages"],
        rows: [
          { label: "Build", a: "Rugged, low cost", b: "—" },
          { label: "RPM range", a: "Good output over a wide range", b: "—" },
          { label: "Pressure", a: "High increase per stage", b: "—" },
          { label: "Size", a: "—", b: "Large frontal area increases drag" },
          { label: "Staging", a: "—", b: "Impractical for multiple stages" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Impeller → diffuser → manifold",
          "Rugged and wide-RPM, but draggy and effectively single-stage",
          "Across the compressor, pressure AND velocity increase",
        ],
      },
      { kind: "question", questionId: "eq-e3-007" },
      { kind: "question", questionId: "eq-e3-008" },
      { kind: "question", questionId: "eq-e3-009" },
    ],
    questionIds: ["eq-e3-007", "eq-e3-008", "eq-e3-009", "etrap-e3-020"],
    memorize: ["Centrifugal: impeller, diffuser, manifold."],
    sourceReferences: [L202],
    labIds: ["elab-compressor"],
  },
  {
    id: "el12-axial-compressor",
    unit: "e3",
    index: 12,
    title: "Axial Compressors and Spools",
    subtitle: "Rotor, stator, and the dual spool order",
    estimatedMinutes: 7,
    mapIcon: "eng-axial",
    enablingObjectives: ["2.2"],
    conceptIds: ["e-axial-compressor", "e-axial-tradeoffs", "e-spools", "e-axial-centrifugal"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Straight through, many times over",
        line: "Each stage adds a little pressure. Stack fifteen of them and you reach 30:1.",
      },
      {
        kind: "model",
        headline: "One rotor plus one stator is one stage",
        diagram: { id: "eng-axial", props: { stages: 5 } },
        line: "The rotor accelerates the air. The stator slows it, converting that speed to pressure, and straightens the flow for the next rotor.",
        bullets: [
          "Rotor: pressure and velocity increase",
          "Stator: velocity decreases, pressure increases, flow straightened",
          "Overall compression ratios of 15:1 to 30:1",
        ],
      },
      {
        kind: "manipulate",
        headline: "Add stages, build pressure",
        widget: "AxialStageBuilder",
        line: "Watch what one more rotor-stator pair does to the pressure at the diffuser.",
      },
      {
        kind: "model",
        headline: "Dual spool: two independent shafts",
        diagram: { id: "eng-spools", props: { dual: true } },
        line: "Forward to aft: LPC, HPC, HPT, LPT. Each turbine drives the compressor of its own spool, and the different speeds ease airflow through.",
      },
      {
        kind: "compare",
        headline: "Axial versus centrifugal",
        line: "They fail in opposite ways, which is what the exam probes.",
        columns: ["Axial", "Centrifugal"],
        rows: [
          { label: "Frontal area", a: "Small — less drag", b: "Large — more drag" },
          { label: "Staging", a: "Easy, many stages", b: "Impractical" },
          { label: "Stall at low airspeed", a: "More likely", b: "Less of an issue" },
          { label: "RPM range", a: "Narrow efficient band", b: "Good over a wide range" },
          { label: "Cost", a: "Difficult and costly", b: "Low cost, rugged" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "One rotor + one stator = one stage",
          "LPC → HPC → HPT → LPT, forward to aft",
          "Axial stalls more readily at low airspeed",
          "T-6: four-stage axial plus one centrifugal impeller",
        ],
      },
      { kind: "question", questionId: "eq-e3-010" },
      { kind: "question", questionId: "eq-e3-011" },
      { kind: "question", questionId: "eq-e3-012" },
      { kind: "question", questionId: "eq-e3-013" },
      { kind: "question", questionId: "eq-e3-015" },
    ],
    questionIds: [
      "eq-e3-010",
      "eq-e3-011",
      "eq-e3-012",
      "eq-e3-013",
      "eq-e3-014",
      "eq-e3-015",
      "eq-e3-019",
    ],
    memorize: ["LPC, HPC, HPT, LPT — forward to aft."],
    sourceReferences: [L202],
    explainerIds: ["ex-compressor-does"],
    labIds: ["elab-compressor"],
  },
  {
    id: "el13-guide-vanes-diffuser",
    unit: "e3",
    index: 13,
    title: "Guide Vanes and the Diffuser",
    subtitle: "The highest pressure in the engine",
    estimatedMinutes: 5,
    mapIcon: "eng-diffuser",
    enablingObjectives: ["2.2"],
    conceptIds: ["e-guide-vanes", "e-compressor-diffuser", "e-station-changes"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "The peak pressure point is not where you would guess",
        line: "It is not the last compressor stage and it is definitely not the burner. It is the diffuser.",
      },
      {
        kind: "compare",
        headline: "Two sets of vanes, opposite jobs",
        line: "One swirls the air in, the other straightens it out.",
        columns: ["Inlet guide vanes", "Exit guide vanes"],
        rows: [
          { label: "Position", a: "Ahead of the first rotor", b: "Compressor discharge end" },
          { label: "Effect on flow", a: "Imparts swirl in the direction of rotation", b: "Straightens rotational flow" },
          { label: "Purpose", a: "Directs air onto the first rotor, reduces its drag", b: "Prepares airflow for the diffuser" },
        ],
      },
      {
        kind: "model",
        headline: "Then the diffuser takes over",
        diagram: { id: "eng-station-changes", props: { highlight: "compressor" } },
        line: "Divergent in design, it drops velocity and gives the final pressure increase — the point of highest compression in the engine.",
      },
      {
        kind: "manipulate",
        headline: "What changes, station by station",
        widget: "StationChangePicker",
        line: "Step the engine. Only one station drops pressure while adding energy — find it.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Inlet guide vanes swirl in; exit guide vanes straighten out",
          "The diffuser is the point of HIGHEST compression",
          "Diffuser is divergent, dropping velocity for a final pressure rise",
        ],
      },
      { kind: "question", questionId: "eq-e3-016" },
      { kind: "question", questionId: "eq-e3-017" },
      { kind: "question", questionId: "etap-e3-018" },
    ],
    questionIds: ["eq-e3-016", "eq-e3-017", "etap-e3-018"],
    memorize: ["Highest pressure in the engine is at the diffuser."],
    sourceReferences: [L202],
  },

  /* ================= e4 · Burn, Turbine, Exhaust ================= */
  {
    id: "el14-burner-section",
    unit: "e4",
    index: 14,
    title: "The Burner Section",
    subtitle: "25% burns, 75% cools",
    estimatedMinutes: 6,
    mapIcon: "eng-burner",
    enablingObjectives: ["2.3", "2.4"],
    conceptIds: ["e-burner-purpose", "e-primary-secondary-air", "e-burner-criteria"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Only a quarter of the air actually burns",
        line: "The other three quarters are there to keep the chamber and the turbine from melting.",
      },
      {
        kind: "model",
        headline: "The split",
        diagram: { id: "eng-burner-split" },
        line: "Primary air goes into the liner and mixes with fuel. Secondary air flows around the outside.",
        bullets: [
          "25% primary — mixed with fuel for ignition",
          "75% secondary — cools chamber walls and turbine, controls the flame, feeds the afterburner",
        ],
      },
      {
        kind: "model",
        headline: "Where it sits in the engine",
        diagram: { id: "eng-cutaway", props: { highlight: "burner" } },
        line: "Between the diffuser's peak pressure and the turbine's extraction. Pressure actually drops slightly across it.",
      },
      {
        kind: "chain",
        headline: "Four design requirements",
        nodes: [
          { label: "Minimise pressure decrease", trend: "down" },
          { label: "Combust efficiently", trend: "up" },
          { label: "Flame must not blow out", trend: "same" },
          { label: "Burning complete before the turbine", trend: "same", emphasis: true },
        ],
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "25% primary burns · 75% secondary cools and controls",
          "Deliver gas below the turbine blade temperature limit",
          "Minimise pressure loss — the burner never raises pressure",
        ],
      },
      { kind: "question", questionId: "eq-e4-001" },
      { kind: "question", questionId: "eq-e4-002" },
      { kind: "question", questionId: "eq-e4-003" },
      { kind: "question", questionId: "eq-e4-004" },
    ],
    questionIds: ["eq-e4-001", "eq-e4-002", "eq-e4-003", "eq-e4-004"],
    memorize: ["25% primary burns, 75% secondary cools."],
    sourceReferences: [L202],
    explainerIds: ["ex-why-not-forward"],
  },
  {
    id: "el15-combustion-chambers",
    unit: "e4",
    index: 15,
    title: "Three Combustion Chambers",
    subtitle: "Can, annular, can-annular",
    estimatedMinutes: 6,
    mapIcon: "eng-chamber",
    enablingObjectives: ["2.4"],
    conceptIds: ["e-can-chamber", "e-annular-chamber", "e-can-annular-chamber"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "Three ways to hold a fire in a hurricane",
        line: "Each design trades maintenance access against heat distribution against cost.",
      },
      {
        kind: "compare",
        headline: "The three types",
        line: "Learn one distinguishing advantage and one disadvantage for each.",
        columns: ["Advantage", "Disadvantage"],
        rows: [
          { label: "Can", a: "Strength, durability, ease of maintenance", b: "Poor use of space, pressure loss, cold spots on turbine" },
          { label: "Annular", a: "Uniform heat across turbine face, smaller diameter", b: "Maintenance needs major overhaul, thin-wall structural problems" },
          { label: "Can-annular", a: "Easy maintenance, good thermodynamics, stability, lower pressure loss", b: "High cost of procurement and replacement" },
        ],
      },
      {
        kind: "model",
        headline: "Where each is used",
        diagram: { id: "eng-cutaway", props: { highlight: "burner" } },
        line: "Can with older centrifugal compressor engines. Annular where diameter matters. Can-annular on larger high performance aircraft.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Annular liner = burner basket",
          "Annular gives uniform heat and the smallest diameter",
          "Can-annular eliminates cold spots from clogged nozzles",
        ],
      },
      { kind: "question", questionId: "eq-e4-005" },
      { kind: "question", questionId: "eq-e4-006" },
      { kind: "question", questionId: "eq-e4-007" },
      { kind: "question", questionId: "eq-e4-008" },
    ],
    questionIds: ["eq-e4-005", "eq-e4-006", "eq-e4-007", "eq-e4-008"],
    memorize: ["Can = maintainable. Annular = uniform and slim. Can-annular = big aircraft."],
    sourceReferences: [L202],
  },
  {
    id: "el16-turbine-section",
    unit: "e4",
    index: 16,
    title: "The Turbine Section",
    subtitle: "75% of the energy never leaves",
    estimatedMinutes: 6,
    mapIcon: "eng-turbine",
    enablingObjectives: ["2.5", "2.6"],
    conceptIds: ["e-turbine-purpose", "e-turbine-construction", "e-creep", "e-fir-tree"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Most of the fire is spent keeping the engine running",
        line: "Only a quarter of the energy reaching the turbine ever becomes thrust.",
      },
      {
        kind: "model",
        headline: "The energy split",
        diagram: { id: "eng-turbine-energy" },
        line: "75% goes to driving the compressor and accessory gear box. 25% is left for thrust.",
      },
      {
        kind: "compare",
        headline: "Two 25/75 splits, one section apart",
        line: "This is the single most swapped pair in the Engines block.",
        columns: ["Burner", "Turbine"],
        rows: [
          { label: "What is split", a: "AIRFLOW", b: "ENERGY" },
          { label: "The 25%", a: "Primary air, which burns", b: "Left over for thrust" },
          { label: "The 75%", a: "Secondary air, which cools", b: "Drives compressor and AGB" },
        ],
      },
      {
        kind: "chain",
        headline: "Creep",
        nodes: [
          { label: "Excessive temperature and speed", trend: "up" },
          { label: "Turbine blades elongate abnormally", trend: "up" },
          { label: "Permanent blade deformation", trend: "none", emphasis: true },
        ],
        footnote:
          "The fir tree attachment exists to allow NORMAL thermal expansion, so ordinary heating does not become damage.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Turbine: 75% drives the compressor and AGB, 25% is thrust",
          "Creep = abnormal blade elongation from overheating",
          "Fir tree attachment allows normal expansion",
          "Turbine is the most stressed part of the engine",
        ],
      },
      { kind: "question", questionId: "eq-e4-009" },
      { kind: "question", questionId: "eq-e4-010" },
      { kind: "question", questionId: "eq-e4-011" },
      { kind: "question", questionId: "eq-e4-012" },
      { kind: "question", questionId: "ecc-e4-021" },
    ],
    questionIds: [
      "eq-e4-009",
      "eq-e4-010",
      "eq-e4-011",
      "eq-e4-012",
      "ecc-e4-021",
      "eq-cov-001",
    ],
    memorize: ["Burner splits air 25/75. Turbine splits energy 75/25."],
    sourceReferences: [L202],
    explainerIds: ["ex-turbine-vs-compressor"],
  },
  {
    id: "el17-exhaust-and-afterburner",
    unit: "e4",
    index: 17,
    title: "Exhaust and Afterburner",
    subtitle: "The last acceleration",
    estimatedMinutes: 7,
    mapIcon: "eng-exhaust",
    enablingObjectives: ["2.7", "2.8", "2.9"],
    conceptIds: [
      "e-exhaust-section",
      "e-exhaust-nozzles",
      "e-afterburner",
      "e-afterburner-ignition",
      "e-afterburner-components",
      "e-variable-exhaust-nozzle",
      "e-recip-components",
    ],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "One more chance to add velocity",
        line: "And, if you are willing to burn fuel extravagantly, one more chance to add 50% thrust.",
      },
      {
        kind: "model",
        headline: "The exhaust section",
        diagram: { id: "eng-cutaway", props: { highlight: "exhaust" } },
        line: "Outer duct, inner cone and radial struts direct hot gases rearward at high velocity while preventing turbulence.",
      },
      {
        kind: "compare",
        headline: "Two nozzle types",
        line: "Straight out of the supersonic reversal you learned in unit e1.",
        columns: ["Convergent", "Convergent/divergent"],
        rows: [
          { label: "Used on", a: "Subsonic exhaust", b: "Supersonic aircraft" },
          { label: "Convergent part", a: "Accelerates gases, directs to a focal point", b: "Accelerates toward the speed of sound" },
          { label: "Divergent part", a: "—", b: "Further acceleration to supersonic" },
        ],
      },
      {
        kind: "chain",
        headline: "Why the variable nozzle must open",
        nodes: [
          { label: "Afterburner lights, gases expand", trend: "up" },
          { label: "Nozzle fails to open", trend: "none" },
          { label: "Gases back up, back pressure builds", trend: "up" },
          { label: "Compressor stalls", trend: "down", emphasis: true },
        ],
        footnote:
          "This is the link between the back of the engine and a compressor stall at the front — and it reappears in unit e5.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Afterburner adds 50% or more thrust, briefly",
          "Spray bars, flame holders, screech liners, variable exhaust nozzle",
          "Screech liner = shock absorber for pressure fluctuations",
          "Nozzle convergent with afterburner off; opens when lit",
        ],
      },
      { kind: "question", questionId: "eq-e4-013" },
      { kind: "question", questionId: "eq-e4-014" },
      { kind: "question", questionId: "eq-e4-015" },
      { kind: "question", questionId: "eq-e4-017" },
      { kind: "question", questionId: "eq-e4-018" },
      { kind: "question", questionId: "eq-e4-020" },
    ],
    questionIds: [
      "eq-e4-013",
      "eq-e4-014",
      "eq-e4-015",
      "eq-e4-016",
      "eq-e4-017",
      "eq-e4-018",
      "eq-e4-019",
      "eq-e4-020",
    ],
    memorize: ["Nozzle stuck shut in afterburner means back pressure, which stalls the compressor."],
    sourceReferences: [L202],
  },
];
