import type { Lesson, SourceReference } from "@/lib/types";

const L203: SourceReference = {
  document: "Compressor Stalls",
  chapter: "Compressor Stalls",
};
/** The systems lecture is the authority for the accessory, starter and ignition block. */
const L209: SourceReference = {
  document: "Accessory, Starter and Ignition Systems",
  chapter: "Accessory, Starter and Ignition Systems",
};

const NOTES = (chapter: string): SourceReference => ({
  document: "Engines Condensed Notes",
  chapter,
});

/**
 * Engines lessons, units e5–e7: compressor stalls, engine types, and the
 * aircraft systems around the engine.
 *
 * From e6 onward the only supplied source is the condensed notes, so these
 * lessons claim no enabling objectives — the EO matrix should show e1–e5
 * fully covered and stop there rather than inventing objectives.
 */
export const LESSONS_B: Lesson[] = [
  /* ================= e5 · Compressor Stalls ================= */
  {
    id: "el18-blade-aoa",
    unit: "e5",
    index: 18,
    title: "Compressor Blade AOA",
    subtitle: "Why a rotor blade is a wing",
    estimatedMinutes: 6,
    mapIcon: "eng-blade",
    enablingObjectives: ["3.1", "3.2"],
    conceptIds: ["e-compressor-relative-wind", "e-compressor-aoa", "e-stall-definition"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Compressor blades stall exactly like wings do",
        line: "Same airfoil, same excessive angle of attack, same breakaway of flow. Only the relative wind is built differently.",
      },
      {
        kind: "model",
        headline: "Two vectors make the relative wind",
        diagram: { id: "eng-blade-aoa", props: { inletFlow: 1, rpm: 1 } },
        line: "Inlet airflow comes down the engine axis. Blade speed comes from RPM. Add them and you get the wind the blade actually feels.",
        bullets: [
          "Relative wind = inlet airflow + compressor RPM",
          "AOA = angle between the rotor blade chordline and that relative wind",
          "Too low is inefficient; too high stalls",
        ],
      },
      {
        kind: "manipulate",
        headline: "Starve the airflow, or spin it faster",
        widget: "BladeAoaWidget",
        line: "Either one swings the relative wind and drives AOA up. Find the combination that stalls the blade.",
      },
      {
        kind: "chain",
        headline: "The rule the whole unit rests on",
        nodes: [
          { label: "Inlet airflow decreases OR compressor RPM increases", trend: "none" },
          { label: "Relative wind swings", trend: "up" },
          { label: "Blade angle of attack increases", trend: "up" },
          { label: "Compressor stall becomes likely", trend: "down", emphasis: true },
        ],
        footnote: "Note the directions run opposite: less airflow, or more RPM.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Compressor RW = inlet airflow + compressor RPM",
          "Anything that decreases inlet airflow or increases RPM raises AOA",
          "A stall could lead to engine flameout",
        ],
      },
      { kind: "question", questionId: "eq-e5-001" },
      { kind: "question", questionId: "eq-e5-002" },
      { kind: "question", questionId: "eq-e5-003" },
      { kind: "question", questionId: "esl-e5-004" },
      { kind: "question", questionId: "etrap-e5-018" },
    ],
    questionIds: [
      "eq-e5-001",
      "eq-e5-002",
      "eq-e5-003",
      "esl-e5-004",
      "eq-e5-005",
      "etrap-e5-018",
    ],
    memorize: ["Less inlet airflow or more RPM = higher blade AOA = stall risk."],
    sourceReferences: [L203],
    explainerIds: ["ex-why-stalls-happen"],
    labIds: ["elab-stall"],
  },
  {
    id: "el19-stall-indications",
    unit: "e5",
    index: 19,
    title: "Stall Indications",
    subtitle: "What it sounds and looks like",
    estimatedMinutes: 4,
    mapIcon: "eng-gauge-alert",
    enablingObjectives: ["3.2"],
    conceptIds: ["e-stall-indications"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Two needles move in opposite directions",
        line: "RPM down, ITT up. If you remember nothing else about indications, remember that pair.",
      },
      {
        kind: "model",
        headline: "The gauge cluster",
        diagram: { id: "eng-stall-indications", props: { stalled: true } },
        line: "Severity decides how obvious it is, but the direction of the two key gauges never changes.",
        bullets: [
          "Mild: pulsations, engine vibration with noise",
          "Fluctuating torquemeter, ITT, compressor and fuel flow gauges",
          "Severe: loud bangs, RPM decrease, ITT increase",
        ],
      },
      {
        kind: "chain",
        headline: "At a constant PCL position",
        nodes: [
          { label: "RPM decay", trend: "down" },
          { label: "Rise in ITT", trend: "up" },
          { label: "Possible loud noises", trend: "none", emphasis: true },
        ],
        footnote: "You have not moved the throttle, and the engine is changing anyway. That is the tell.",
      },
      {
        kind: "manipulate",
        headline: "Flip the stall and watch the needles part",
        widget: "StallGaugeToggle",
        line: "Normal, then stalled. The two gauges that matter move in opposite directions.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Severe stall: RPM decreases, ITT increases",
          "Mild stall: pulsations and fluctuating gauges",
          "Loud bangs are a change in engine sound, not an explosion",
        ],
      },
      { kind: "question", questionId: "eq-e5-006" },
      { kind: "question", questionId: "eq-e5-007" },
      { kind: "question", questionId: "eq-e5-019" },
    ],
    questionIds: ["eq-e5-006", "eq-e5-007", "eq-e5-019"],
    memorize: ["Stall: RPM down, ITT up."],
    sourceReferences: [L203],
    explainerIds: ["ex-indications-90s"],
  },
  {
    id: "el20-stall-causes",
    unit: "e5",
    index: 20,
    title: "Causes of Compressor Stall",
    subtitle: "Distortion and malfunction",
    estimatedMinutes: 6,
    mapIcon: "eng-distortion",
    enablingObjectives: ["3.3"],
    conceptIds: ["e-airflow-distortion", "e-mechanical-malfunctions"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Two families of cause, and one is far more common",
        line: "Airflow distortion is the usual culprit. Mechanical malfunctions are the memorable four.",
      },
      {
        kind: "compare",
        headline: "Sort every cause into one of two columns",
        line: "If a component broke, it is mechanical. If the air was disturbed, it is distortion.",
        columns: ["Airflow distortion (most common)", "Mechanical malfunction"],
        rows: [
          { label: "1", a: "Abrupt aircraft attitude change", b: "Variable inlet guide vane failure" },
          { label: "2", a: "Air turbulence", b: "Fuel control unit failure" },
          { label: "3", a: "Deficiency of air velocity/volume from atmospheric conditions", b: "Foreign object damage" },
          { label: "4", a: "Rapid throttle movement", b: "Variable exhaust nozzle failure" },
        ],
      },
      {
        kind: "chain",
        headline: "How a broken component reaches the compressor",
        nodes: [
          { label: "FCU meters extra fuel to the burner", trend: "up" },
          { label: "Excessive back pressure builds", trend: "up" },
          { label: "Airflow through the compressor is disrupted", trend: "down" },
          { label: "Compressor stall", trend: "down", emphasis: true },
        ],
        footnote:
          "The variable exhaust nozzle failing to open during afterburner operation does the same thing, from further aft.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Airflow distortion is the MOST COMMON cause",
          "Four mechanical malfunctions: IGV, FCU, FOD, variable exhaust nozzle",
          "IGV failure gives insufficient airflow at lower RPM",
        ],
      },
      { kind: "question", questionId: "eq-e5-008" },
      { kind: "question", questionId: "eq-e5-009" },
      { kind: "question", questionId: "eq-e5-010" },
      { kind: "question", questionId: "eq-e5-011" },
      { kind: "question", questionId: "eq-e5-020" },
    ],
    questionIds: [
      "eq-e5-008",
      "eq-e5-009",
      "eq-e5-010",
      "eq-e5-011",
      "eq-e5-020",
    ],
    memorize: ["Distortion is most common. IGV, FCU, FOD, nozzle are the mechanical four."],
    sourceReferences: [L203],
    labIds: ["elab-malfunction"],
  },
  {
    id: "el21-avoid-prevent-recover",
    unit: "e5",
    index: 21,
    title: "Avoid, Prevent, Recover",
    subtitle: "Pilot actions versus engine design",
    estimatedMinutes: 6,
    mapIcon: "eng-recovery",
    enablingObjectives: ["3.4", "3.5"],
    conceptIds: ["e-stall-avoidance", "e-stall-prevention", "e-stall-recovery"],
    masteryThreshold: 0.85,
    screens: [
      {
        kind: "hook",
        headline: "Avoidance and prevention are not synonyms here",
        line: "Avoidance is what you do. Prevention is what the engineers already did. The exam mixes the two lists on purpose.",
      },
      {
        kind: "compare",
        headline: "Who is responsible for what",
        line: "Four items in each column.",
        columns: ["Avoidance — the pilot", "Prevention — the engine"],
        rows: [
          { label: "1", a: "Avoid erratic or abrupt PCL movement", b: "Variable inlet guide vanes" },
          { label: "2", a: "Maintain prescribed minimums", b: "Dual/twin/split-spool axial compressor" },
          { label: "3", a: "Avoid abrupt attitude changes", b: "Bleed valves" },
          { label: "4", a: "Avoid severe weather and turbulence", b: "Variable exhaust nozzle" },
        ],
      },
      {
        kind: "chain",
        headline: "The recovery, in order",
        nodes: [
          { label: "Reduce aircraft attitude — lower the nose", trend: "down", emphasis: true },
          { label: "Slowly retard the PCL below the stall threshold", trend: "down" },
          { label: "Bleed valves increase airflow", trend: "up" },
          { label: "Once normal, slowly advance the PCL", trend: "up" },
        ],
        footnote:
          "Lowering the nose comes first because it attacks the cause — inlet air AOA. Every PCL movement is slow.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "First action: lower the nose to reduce inlet air AOA",
          "Retard the PCL SLOWLY so the engine can catch up with the airflow",
          "Avoidance = pilot. Prevention = hardware.",
          "Warning: avoid unnecessary PCL movement",
        ],
      },
      { kind: "question", questionId: "eq-e5-012" },
      { kind: "question", questionId: "eq-e5-013" },
      { kind: "question", questionId: "eq-e5-014" },
      { kind: "question", questionId: "ecc-e5-015" },
      { kind: "question", questionId: "eq-e5-017" },
    ],
    questionIds: [
      "eq-e5-012",
      "eq-e5-013",
      "eq-e5-014",
      "ecc-e5-015",
      "eq-e5-016",
      "eq-e5-017",
    ],
    memorize: ["Nose down first, then PCL back slowly."],
    sourceReferences: [L203],
    labIds: ["elab-stall"],
  },

  /* ================= e6 · Engine Types ================= */
  {
    id: "el22-turbojet-turbofan",
    unit: "e6",
    index: 22,
    title: "Turbojet and Turbofan",
    subtitle: "Bypass ratio and TSFC",
    estimatedMinutes: 6,
    mapIcon: "eng-turbofan",
    enablingObjectives: ["4.1", "4.2", "4.3", "4.4", "4.12", "4.13"],
    conceptIds: ["e-turbojet", "e-turbofan", "e-tsfc"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "Bolt a big fan on the front and everything changes",
        line: "More thrust at low speed, less fuel burned, more noise absorbed — at the price of frontal area and high-altitude efficiency.",
      },
      {
        kind: "model",
        headline: "Where turbofan thrust comes from",
        diagram: { id: "eng-type-split", props: { type: "turbofan" } },
        line: "40–70% from the gas generator, 30–60% from the ducted fan.",
      },
      {
        kind: "compare",
        headline: "Turbojet versus turbofan",
        line: "Each row is a plausible exam stem.",
        columns: ["Turbojet", "Turbofan"],
        rows: [
          { label: "High-end performance", a: "Best — flies higher and faster", b: "Lower" },
          { label: "Specific weight", a: "Lightest", b: "Higher" },
          { label: "Low-speed thrust", a: "Low propulsive efficiency", b: "Higher thrust at low airspeed" },
          { label: "TSFC", a: "High", b: "Lower — more efficient" },
          { label: "Takeoff distance", a: "Longer", b: "Shorter" },
          { label: "Frontal area", a: "Small", b: "Larger — more drag" },
        ],
      },
      {
        kind: "chain",
        headline: "Bypass ratio decides the personality",
        nodes: [
          { label: "Bypass ratio increases", trend: "up" },
          { label: "TSFC decreases", trend: "down" },
          { label: "More fuel efficient — airliners and cargo", trend: "up", emphasis: true },
        ],
        footnote: "Fighters go the other way: low bypass, turbojet-like performance, turbofan efficiency.",
      },
      {
        kind: "manipulate",
        headline: "One gas generator, four ways to spend it",
        widget: "EngineTypePicker",
        line: "Switch the type and watch where the thrust actually comes from.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Turbofan: 40–70% core, 30–60% fan",
          "Bypass ratio ↑ → TSFC ↓ → more efficient",
          "TSFC = fuel required to produce one pound of thrust",
          "Fighters low bypass, airliners high bypass",
        ],
      },
      { kind: "question", questionId: "eq-e6-001" },
      { kind: "question", questionId: "eq-e6-002" },
      { kind: "question", questionId: "eq-e6-003" },
      { kind: "question", questionId: "eq-e6-008" },
      { kind: "question", questionId: "eq-e6-015" },
    ],
    questionIds: [
      "eq-e6-001",
      "eq-e6-002",
      "eq-e6-003",
      "eq-e6-008",
      "eq-e6-012",
      "eq-e6-015",
    ],
    memorize: ["Bypass up, TSFC down."],
    sourceReferences: [NOTES("Engine Types")],
  },
  {
    id: "el23-turboprop-turboshaft",
    unit: "e6",
    index: 23,
    title: "Turboprop and Turboshaft",
    subtitle: "Gear boxes, torque and 90/10",
    estimatedMinutes: 7,
    mapIcon: "eng-prop",
    enablingObjectives: ["4.5", "4.6", "4.7", "4.8", "4.9", "4.10"],
    conceptIds: [
      "e-turboprop",
      "e-rgb",
      "e-turboprop-torquemeter",
      "e-propeller-ranges",
      "e-turboshaft",
    ],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "The propeller does 90% of the work",
        line: "Which is why a turboprop reads a torquemeter, not an EPR gauge.",
      },
      {
        kind: "model",
        headline: "The power path",
        diagram: { id: "eng-turboprop-flow" },
        line: "Combustion to turbine to shaft to gear box to propeller. The gear box exists for one reason: keeping propeller tips subsonic.",
      },
      {
        kind: "model",
        headline: "The thrust split",
        diagram: { id: "eng-type-split", props: { type: "turboprop" } },
        line: "90% from the propeller, 10% from the exhaust gases.",
      },
      {
        kind: "compare",
        headline: "Alpha and beta range",
        line: "One is for flying, one is strictly for the ground.",
        columns: ["Alpha range", "Beta range"],
        rows: [
          { label: "When", a: "Flight range", b: "Ground only" },
          { label: "PCL travel", a: "Idle to full power", b: "Idle to max reverse" },
          { label: "PCL controls", a: "The FCU, which controls fuel flow", b: "Mechanically linked to FCU and pitch change assembly" },
          { label: "Blade angle set by", a: "Propeller governor", b: "PCL directly" },
        ],
      },
      {
        kind: "compare",
        headline: "Turboprop versus turboshaft",
        line: "Nearly the same machine, one decisive difference.",
        columns: ["Turboprop", "Turboshaft"],
        rows: [
          { label: "Thrust from exhaust", a: "10%", b: "None at all" },
          { label: "Power turbine", a: "Not necessarily free", b: "ALWAYS a free/power turbine" },
          { label: "Propulsion", a: "Propeller", b: "Rotor" },
        ],
      },
      {
        kind: "manipulate",
        headline: "Follow the power from burn to propeller",
        widget: "TurbopropFlowStepper",
        line: "Each stage changes the form of the energy. The gear box is where RPM becomes torque.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Turboprop: 90% propeller, 10% exhaust",
          "RGB: high RPM/low torque → low RPM/high torque",
          "Alpha = flight, beta = ground",
          "Turboshaft gets zero propulsion from exhaust",
          "Turboprop has the lowest TSFC, limited to ~400–450 knots",
        ],
      },
      { kind: "question", questionId: "eq-e6-004" },
      { kind: "question", questionId: "eq-e6-005" },
      { kind: "question", questionId: "eq-e6-006" },
      { kind: "question", questionId: "eq-e6-007" },
      { kind: "question", questionId: "ecc-e6-014" },
    ],
    questionIds: [
      "eq-e6-004",
      "eq-e6-005",
      "eq-e6-006",
      "eq-e6-007",
      "eq-e6-009",
      "eq-e6-010",
      "eq-e6-011",
      "ecc-e6-014",
    ],
    memorize: ["Turboprop 90/10. Turboshaft 100/0."],
    sourceReferences: [NOTES("Engine Types")],
    explainerIds: ["ex-turbine-to-prop"],
    labIds: ["elab-turboprop"],
  },
  {
    id: "el24-reciprocating",
    unit: "e6",
    index: 24,
    title: "Reciprocating Engines",
    subtitle: "Pistons, crankshafts and governors",
    estimatedMinutes: 4,
    mapIcon: "eng-piston",
    enablingObjectives: ["1.6", "4.11"],
    conceptIds: ["e-recip-propulsion", "e-otto"],
    masteryThreshold: 0.7,
    screens: [
      {
        kind: "hook",
        headline: "The other cycle, and the other way to turn a propeller",
        line: "Same four events as a turbine, taken one at a time by a piston.",
      },
      {
        kind: "model",
        headline: "Otto cycle, sequentially",
        diagram: { id: "eng-cycles", props: { cycle: "otto" } },
        line: "Intake, compression, combustion, exhaust — suck, squeeze, bang, blow. One after another, not all at once.",
      },
      {
        kind: "chain",
        headline: "From crankshaft to thrust",
        nodes: [
          { label: "Crankshaft rotates", trend: "up" },
          { label: "Directly or through a reduction gear box", trend: "none" },
          { label: "Propeller produces all the thrust", trend: "up", emphasis: true },
        ],
        footnote: "A governor controls blade angle and propeller speed.",
      },
      {
        kind: "manipulate",
        headline: "Same four events, different timing",
        widget: "CyclePicker",
        line: "Show one, then the other, then both. The difference is when, not what.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Components: crankcase, cylinders, pistons, connecting rods, valves, valve-operating mechanism, crankshaft",
          "All thrust comes from the propeller",
          "Governor controls blade angle and propeller speed",
        ],
      },
      { kind: "question", questionId: "eq-e6-013" },
      { kind: "question", questionId: "eq-e4-020" },
      { kind: "question", questionId: "eq-e1-015" },
    ],
    questionIds: ["eq-e6-013", "eq-e4-020", "eq-e1-015"],
    memorize: ["Otto is sequential; the governor sets blade angle."],
    sourceReferences: [NOTES("Engine Types")],
  },

  /* ================= e7 · Aircraft Systems ================= */
  {
    id: "el25-fuel-system",
    unit: "e7",
    index: 25,
    title: "Fuel System and the FCU",
    subtitle: "Tank to nozzle",
    estimatedMinutes: 7,
    mapIcon: "eng-fuel",
    enablingObjectives: ["7.4", "7.6", "7.7"],
    conceptIds: ["e-fuel-path", "e-boost-pump", "e-fcu", "e-fuel-manifolds"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "Everything upstream of the FCU just delivers clean fuel at pressure",
        line: "The FCU decides how much of it the engine actually gets. That is why it is called the brain.",
      },
      {
        kind: "model",
        headline: "The path",
        diagram: { id: "eng-fuel-system", props: { highlight: "fcu" } },
        line: "Tank, boost pump, low pressure filter, engine-driven pump, FCU, P&D valve, manifolds, nozzles.",
      },
      {
        kind: "chain",
        headline: "What the FCU is watching",
        nodes: [
          { label: "Compressor Inlet Temperature", trend: "none" },
          { label: "Engine RPM", trend: "none" },
          { label: "Turbine temperature (ITT)", trend: "none" },
          { label: "PCL input from the aviator", trend: "none" },
          { label: "Metered fuel to the manifold", trend: "up", emphasis: true },
        ],
        footnote:
          "In manual operation you lose acceleration limiting, RPM limiting and governing — and must watch ITT yourself.",
      },
      {
        kind: "compare",
        headline: "Two manifolds",
        line: "Different pressures for different phases of flight.",
        columns: ["Primary manifold", "Secondary manifold"],
        rows: [
          { label: "Size", a: "Smaller", b: "Larger" },
          { label: "Purpose", a: "High pressure for high atomization", b: "Supplies once RPM raises pressure" },
          { label: "When", a: "Starting and altitude idling", b: "At a predetermined pressure level" },
        ],
      },
      {
        kind: "manipulate",
        headline: "Follow the fuel, tank to nozzle",
        widget: "FuelPathTracer",
        line: "Step along the path. Each component has one job, and one way it can fail.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Boost pump prevents AERATION during rapid climb pressure change",
          "FCU senses CIT, RPM, ITT and PCL",
          "Small primary manifold = high pressure = good atomization for starting",
        ],
      },
      { kind: "question", questionId: "eq-e7-001" },
      { kind: "question", questionId: "eq-e7-002" },
      { kind: "question", questionId: "eq-e7-003" },
      { kind: "question", questionId: "ecc-e7-025" },
    ],
    questionIds: ["eq-e7-001", "eq-e7-002", "eq-e7-003", "eq-e7-007", "ecc-e7-025"],
    memorize: ["Tank → boost → filter → pump → FCU → manifolds → nozzles."],
    sourceReferences: [NOTES("Fuel Systems")],
    labIds: ["elab-systems"],
  },
  {
    id: "el26-fuels-and-ratings",
    unit: "e7",
    index: 26,
    title: "Fuels and Thrust Ratings",
    subtitle: "Flash points and time limits",
    estimatedMinutes: 5,
    mapIcon: "eng-fuel-type",
    enablingObjectives: ["7.1", "7.2", "7.3", "7.5"],
    conceptIds: ["e-fuel-types", "e-thrust-ratings"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "The Navy picked its fuel for one number",
        line: "JP-5's flash point is 140 °F. On a ship, that is the whole argument.",
      },
      {
        kind: "compare",
        headline: "Four fuels",
        line: "Volatility and flash point are inversely related.",
        columns: ["Flash point", "Notes"],
        rows: [
          { label: "JP-4 (F-40)", a: "−35 °F", b: "Highly volatile, easier starting, shorter range" },
          { label: "JP-5 (F-44)", a: "140 °F", b: "Navy primary, only jet fuel used aboard ships" },
          { label: "JP-8 (F-34)", a: "100 °F", b: "NATO and Air Force, thermally safe, high cost" },
          { label: "Avgas", a: "−45 °F", b: "Very volatile, high-octane, 100 green / 100LL blue" },
        ],
      },
      {
        kind: "compare",
        headline: "Three thrust ratings",
        line: "All based on allowable turbine inlet temperature — except one.",
        columns: ["Basis", "Time limit"],
        rows: [
          { label: "Normal", a: "Maximum continuous turbine temperature", b: "None" },
          { label: "Military", a: "Maximum turbine temperature", b: "≈ 30 minutes" },
          { label: "Combat", a: "Afterburner — not turbine temperature limited", b: "—" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Volatility ↑ → flash point ↓",
          "JP-5: 140 °F flash point, shipboard, Navy primary",
          "Normal unlimited · Military ≈ 30 min · Combat = afterburner",
        ],
      },
      { kind: "question", questionId: "eq-e7-004" },
      { kind: "question", questionId: "eq-e7-005" },
      { kind: "question", questionId: "eq-e7-006" },
    ],
    questionIds: ["eq-e7-004", "eq-e7-005", "eq-e7-006"],
    memorize: ["JP-5, 140 °F, the only jet fuel used aboard ships."],
    sourceReferences: [NOTES("Fuel Systems")],
  },
  {
    id: "el27-lubrication",
    unit: "e7",
    index: 27,
    title: "Lubrication Systems",
    subtitle: "Pressure, scavenge, breather",
    estimatedMinutes: 6,
    mapIcon: "eng-oil",
    enablingObjectives: ["8.1", "8.2", "8.3", "8.4"],
    conceptIds: [
      "e-lubricant-function",
      "e-synthetic-oil",
      "e-oil-sumps",
      "e-oil-subsystems",
      "e-oil-pump",
      "e-oil-contamination",
      "e-chip-detector",
      "e-viscosity",
    ],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "Three subsystems, and the warning light that matters",
        line: "If the chip detector lights, metal is coming off something inside your engine.",
      },
      {
        kind: "model",
        headline: "The three subsystems",
        diagram: { id: "eng-oil-system", props: { subsystem: "scavenge" } },
        line: "Pressure supplies, scavenge returns, breather pressurizes. Scavenge deliberately has the greater capacity.",
      },
      {
        kind: "compare",
        headline: "Wet sump versus dry sump",
        line: "Where the oil lives decides how well it can be cooled.",
        columns: ["Wet sump", "Dry sump"],
        rows: [
          { label: "Tank location", a: "Internal to the engine", b: "External" },
          { label: "Cooling", a: "Difficult — engine proximity", b: "Easier and better" },
          { label: "Unusual attitudes", a: "Cannot adapt", b: "Suited to modern aircraft" },
          { label: "Oil quantity", a: "Limited", b: "Larger quantities" },
        ],
      },
      {
        kind: "chain",
        headline: "Four contaminations, most common first",
        nodes: [
          { label: "Metal particles from metal-to-metal contact", trend: "up", emphasis: true },
          { label: "Coking — carbon deposits from oil evaporation", trend: "none" },
          { label: "Foreign objects: sand, dirt", trend: "none" },
          { label: "Oil contamination from over-long storage", trend: "none" },
        ],
      },
      {
        kind: "manipulate",
        headline: "Three subsystems, three directions",
        widget: "OilSubsystemPicker",
        line: "Pick one and see where the oil is going, and why scavenge needs the greater capacity.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Scavenge capacity is GREATER than pressure capacity",
          "Metal particles are the most common contamination",
          "Chip detector sits in the SCAVENGE path",
          "Viscosity is inversely related to temperature",
        ],
      },
      { kind: "question", questionId: "eq-e7-008" },
      { kind: "question", questionId: "eq-e7-009" },
      { kind: "question", questionId: "eq-e7-010" },
      { kind: "question", questionId: "eq-e7-011" },
      { kind: "question", questionId: "eq-e7-012" },
    ],
    questionIds: [
      "eq-e7-008",
      "eq-e7-009",
      "eq-e7-010",
      "eq-e7-011",
      "eq-e7-012",
      "eq-e7-013", "eq-lub-001", "eq-lub-002", "eq-lub-003", "eq-lub-004", "eq-lec-012", "eq-lec-013"],
    memorize: ["Pressure, scavenge, breather. Scavenge is bigger."],
    sourceReferences: [NOTES("Lubrication")],
    labIds: ["elab-systems"],
  },
  {
    id: "el28-starting-ignition",
    unit: "e7",
    index: 28,
    title: "Starting the Engine",
    subtitle: "30% RPM, four bad starts, and two ways to spin it up",
    estimatedMinutes: 6,
    mapIcon: "eng-start",
    enablingObjectives: ["9.3", "9.4", "9.5", "9.6"],
    conceptIds: ["e-start-sequence", "e-abnormal-starts", "e-starters"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "Fuel does not go in until 30% RPM",
        line: "Put it in early and you get one of the four abnormal starts — the reason that number is worth knowing exactly.",
      },
      {
        kind: "model",
        headline: "The normal sequence",
        diagram: { id: "eng-start-sequence", props: { stage: "fuel" } },
        line: "Starter engages until self-accelerating speed. Fuel flows after 30% RPM. Ignition when airflow can support combustion.",
      },
      {
        kind: "compare",
        headline: "Four abnormal starts",
        line: "Hung and false differ only in temperature. Read carefully.",
        columns: ["RPM", "Turbine temperature"],
        rows: [
          { label: "Hot start", a: "—", b: "Exceeds maximum allowed during start" },
          { label: "Hung start", a: "Stabilizes below normal", b: "Continues to RISE" },
          { label: "False start", a: "Stabilizes below normal", b: "Remains WITHIN limits" },
          { label: "Wet start", a: "—", b: "No light-off — most dangerous, can light at any time" },
        ],
      },
      {
        kind: "manipulate",
        headline: "Air first, then fuel, then light",
        widget: "StartSequenceStepper",
        line: "Step the start. The 30% gate is what separates a start from a hot start.",
      },
      {
        kind: "compare",
        headline: "Two starters, chosen by engine size",
        line: "Both spin the compressor up to self-accelerating speed. They differ in what does the spinning.",
        columns: ["DC electric motor starter", "Air turbine starter"],
        rows: [
          { label: "Used on", a: "Smaller engines", b: "Larger gas turbine engines" },
          { label: "Mechanism", a: "Motor mechanically connected to the compressor", b: "Small geared air turbine attached to the engine" },
          { label: "Supplied by", a: "Battery, APU or external power", b: "Delivered air" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Fuel flows after 30% RPM",
          "Hung = RPM low + temp rising · False = RPM low + temp OK",
          "Wet start is the most dangerous — it did not light, and it still might",
          "DC motor starter on small engines, air turbine starter on large ones",
        ],
      },
      { kind: "question", questionId: "eq-e7-014" },
      { kind: "question", questionId: "eq-e7-015" },
      { kind: "question", questionId: "eq-e7-016" },
      { kind: "question", questionId: "eq-e7-017" },
      { kind: "question", questionId: "eq-lec-008" },
      { kind: "question", questionId: "eq-lec-009" },
    ],
    questionIds: [
      "eq-e7-014", "eq-e7-015", "eq-e7-016", "eq-e7-017",
      "eq-cov-002", "eq-cov-003", "eq-lec-008", "eq-lec-009",
    ],
    memorize: ["Fuel at 30% RPM. Wet start is the dangerous one."],
    sourceReferences: [NOTES("Starting and Ignition")],
    labIds: ["elab-malfunction"],
  },
  {
    id: "el28b-accessories-and-ignition",
    unit: "e7",
    index: 29,
    title: "Accessories and Ignition",
    subtitle: "What else the engine drives, and what lights the fire",
    estimatedMinutes: 6,
    mapIcon: "eng-start",
    enablingObjectives: ["9.1", "9.2", "9.7"],
    conceptIds: ["e-bleed-air", "e-igniters"],
    masteryThreshold: 0.8,
    screens: [
      {
        kind: "hook",
        headline: "The engine does more than make thrust",
        line: "It also runs the environmental system, pressurises the cabin, de-ices the inlet and turns the generator — by two routes, and only two.",
      },
      {
        kind: "compare",
        headline: "Two ways to drive an accessory",
        line: "Every accessory on the aircraft is on one of these two lines.",
        columns: ["Compressor bleed air", "Mechanically driven"],
        rows: [
          { label: "Taken from", a: "Air bled off the compressor", b: "The accessory gear box around the compressor" },
          { label: "Driven by", a: "The air itself", b: "Gearing off the main shaft" },
          { label: "Runs", a: "Environmental systems, cabin pressurisation, engine anti-ice", b: "Tachometer, hydraulic pumps, alternator or generator" },
        ],
      },
      {
        kind: "model",
        headline: "Where the accessory gear box sits",
        diagram: { id: "eng-cutaway", props: { highlight: "compressor" } },
        line: "Mounted around the compressor, so it can be gear driven off the main shaft.",
      },
      {
        kind: "rule",
        headline: "Why the ignition system is more powerful than it looks",
        rule:
          "Today's military aircraft use a high heat-intensity capacitor ignition system. The high heat discharge ensures ignition of the low-volatility fuel at all temperatures and high altitudes, and it also prevents the igniters from fouling.",
        appliesWhen: [
          "Cold conditions, where a weaker spark would not light the fuel",
          "High altitude, where there is less air to support combustion",
        ],
        watchFor:
          "The same low volatility that makes JP-5 safe to carry aboard ship is what makes a powerful igniter necessary.",
        authority: "Ignition systems",
      },
      {
        kind: "compare",
        headline: "Two spark igniters",
        columns: ["Annular-gap", "Constrained-gap"],
        rows: [
          { label: "Position", a: "Protrudes INTO the chamber", b: "Extends the spark BEYOND the liner face" },
          { label: "Temperature", a: "Hotter", b: "Runs cooler" },
          { label: "Prevalence", a: "Most common", b: "Less common" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Accessories run on bleed air OR off the accessory gear box",
          "Bleed air: environmental, cabin pressurisation, engine anti-ice",
          "Gear box: tachometer, hydraulic pumps, alternator and generator",
          "High heat-intensity capacitor ignition — lights low-volatility fuel, resists fouling",
          "Annular-gap protrudes in and is common · constrained-gap reaches out and runs cooler",
        ],
      },
      { kind: "question", questionId: "eq-lec-007" },
      { kind: "question", questionId: "eq-lec-010" },
      { kind: "question", questionId: "eq-lec-011" },
      { kind: "question", questionId: "eq-e7-018" },
    ],
    questionIds: ["eq-lec-007", "eq-lec-010", "eq-lec-011", "eq-e7-018"],
    memorize: [
      "Bleed air or accessory gear box — those are the only two.",
      "Annular-gap in and common. Constrained-gap out and cooler.",
    ],
    sourceReferences: [L209],
    labIds: ["elab-systems"],
  },
  {
    id: "el29-hydraulics",
    unit: "e7",
    index: 30,
    title: "Hydraulic Systems",
    subtitle: "Pascal's law and the components",
    estimatedMinutes: 6,
    mapIcon: "eng-hydraulic",
    enablingObjectives: ["5.1", "5.2", "5.3"],
    conceptIds: ["e-pascal", "e-hydraulic-pumps", "e-accumulator", "e-hydraulic-components"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "You buy force with distance",
        line: "Pressure is constant through a confined liquid, so a bigger piston gives more force over less travel. That is the whole system.",
      },
      {
        kind: "model",
        headline: "Pascal's law",
        diagram: { id: "eng-hydraulic", props: { ratio: 3 } },
        line: "Triple the output area and you triple the force — and get a third of the movement.",
      },
      {
        kind: "compare",
        headline: "Two power pumps",
        line: "Only one of them needs a regulator.",
        columns: ["Variable displacement", "Constant displacement"],
        rows: [
          { label: "Output", a: "Regulates volume to system demand", b: "Steady flow regardless of pressure" },
          { label: "Pressure", a: "Maintains near constant pressure", b: "Varies with demand" },
          { label: "Requires", a: "—", b: "Pressure regulator / unloader valve" },
        ],
      },
      {
        kind: "chain",
        headline: "What the accumulator is for",
        nodes: [
          { label: "Acts as a shock absorber", trend: "none" },
          { label: "Provides one-time emergency pressure", trend: "none" },
          { label: "Supports pressure during peak demand", trend: "none" },
          { label: "Holds system pressure at shutdown, with the check valve", trend: "none", emphasis: true },
        ],
      },
      {
        kind: "manipulate",
        headline: "Buy force, pay in distance",
        widget: "HydraulicAdvantage",
        line: "Grow the output area. Watch force, travel and pressure — only two of them move.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "P = F/A · force ×2 means travel ÷2",
          "Constant displacement pump REQUIRES an unloader valve",
          "Hand pump is the emergency backup",
          "Hydraulic fuse stops a leak draining the system",
        ],
        formula: "P = \\frac{F}{A}",
      },
      { kind: "question", questionId: "eq-e7-018" },
      { kind: "question", questionId: "eq-e7-019" },
      { kind: "question", questionId: "eq-e7-020" },
    ],
    questionIds: ["eq-e7-018", "eq-e7-019", "eq-e7-020", "eq-cov-004"],
    memorize: ["Force up, travel down. Constant displacement needs an unloader."],
    sourceReferences: [NOTES("Hydraulic Systems")],
  },
  {
    id: "el30-electrical",
    unit: "e7",
    index: 31,
    title: "Electrical Systems",
    subtitle: "Sources, conversion and buses",
    estimatedMinutes: 6,
    mapIcon: "eng-electrical",
    enablingObjectives: ["6.1", "6.2"],
    conceptIds: ["e-ac-dc", "e-power-sources", "e-csd", "e-buses"],
    masteryThreshold: 0.75,
    screens: [
      {
        kind: "hook",
        headline: "Two conversions, pointing opposite ways",
        line: "Inverter goes DC to AC. Transformer rectifier goes AC to DC. Swap them and the question is wrong.",
      },
      {
        kind: "compare",
        headline: "AC and DC",
        line: "AC wins on weight, which on an aircraft usually settles it.",
        columns: ["Alternating current", "Direct current"],
        rows: [
          { label: "Waveform", a: "Alternates either side of base voltage", b: "Straight line voltage" },
          { label: "Current load", a: "Less — lighter wiring, saves weight", b: "Higher" },
          { label: "Components", a: "Lighter", b: "Heavier, more maintenance" },
        ],
      },
      {
        kind: "chain",
        headline: "Sources and conversions",
        nodes: [
          { label: "Alternator: mechanical → AC (primary source)", trend: "none" },
          { label: "Inverter: DC → AC", trend: "none", emphasis: true },
          { label: "Transformer rectifier: AC → DC", trend: "none", emphasis: true },
          { label: "Battery: DC for emergency power and starting", trend: "none" },
        ],
        footnote:
          "The Constant Speed Drive sits between engine and generator, turning variable engine RPM into the constant speed the generator needs.",
      },
      {
        kind: "model",
        headline: "Four buses, ranked by how much depends on them",
        diagram: { id: "eng-electrical", props: { highlight: "essential" } },
        line: "Essential for flight safety, primary for the mission, monitor for convenience, starter for engine starts.",
      },
      {
        kind: "manipulate",
        headline: "Shed the buses in order",
        widget: "BusPicker",
        line: "Pick a bus and see what it feeds. What it feeds is what decides when you can lose it.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Inverter: DC → AC. Transformer rectifier: AC → DC.",
          "CSD: variable engine RPM → constant generator speed",
          "Essential = safety · Primary = mission · Monitor = convenience · Starter = starting",
        ],
      },
      { kind: "question", questionId: "eq-e7-021" },
      { kind: "question", questionId: "eq-e7-022" },
      { kind: "question", questionId: "eq-e7-023" },
      { kind: "question", questionId: "eq-e7-024" },
    ],
    questionIds: ["eq-e7-021", "eq-e7-022", "eq-e7-023", "eq-e7-024"],
    memorize: ["Inverter DC→AC. Transformer rectifier AC→DC."],
    sourceReferences: [NOTES("Electrical Systems")],
  },
];
