import type { Lesson, SourceReference } from "@/lib/types";

/**
 * Units 5 to 7: chart work, the CR-3, and airspeed.
 *
 * This is where the course changes character. From here on almost every lesson
 * ends with the student producing numbers on a tool rather than choosing
 * between options, and every method screen carries the tolerance the answer
 * will be graded to — because a navigation answer without a tolerance is not
 * an answer.
 */

const TG = (chapter: string): SourceReference => ({
  document: "Navigation Trainee Guide",
  chapter,
});

const C2 = TG("Chart Projections, Plotting and Global Timekeeping");
const C3 = TG("CR-3 Air Navigation Computer");
const C4 = TG("Airspeeds");

export const LESSONS_B: Lesson[] = [
  /* ================= n5 — chart work ================= */
  {
    id: "nl11-plotter-and-dividers",
    unit: "n5",
    index: 11,
    title: "The Plotter and the Dividers",
    subtitle: "Two instruments, and one of them lies",
    estimatedMinutes: 6,
    enablingObjectives: [],
    conceptIds: ["nav-plotter", "nav-dividers"],
    mapIcon: "ruler",
    screens: [
      {
        kind: "hook",
        headline: "One measures angles. The other measures distance.",
        line: "The plotter has a distance scale printed on it. Do not use it.",
        diagram: { id: "nav-plotter", props: { highlight: "none" } },
      },
      {
        kind: "model",
        headline: "The parts of the plotter",
        diagram: { id: "nav-plotter", props: { highlight: "grommet" } },
        bullets: [
          "The straightedge, for drawing and for laying against the dividers.",
          "The grommet, the hole at the centre of the protractor. It goes on a meridian.",
          "The outer scales: 0–180 along the top, 180–360 along the bottom.",
          "The inner north/south scale, for lines that run up and down the chart.",
        ],
      },
      {
        kind: "rule",
        headline: "The number line is reversed",
        rule: "On the plotter's outer scale, the numbers increase to the LEFT and decrease to the right.",
        appliesWhen: ["Every direction you measure or plot with the outer scale"],
        watchFor:
          "Read it the intuitive way and you will be ten degrees out, or a hundred and eighty. The defence is bracketing — look at the numbers on both sides of the meridian before committing to one.",
        authority: "NAVAVSCOLSCOM-SG-200, Information Sheet 6-2-2",
      },
      {
        kind: "tool",
        headline: "Pick it up",
        line: "Drag the body to move it, drag the green handle to rotate. Put the grommet on a meridian and look at what the scale is telling you.",
        tool: "chart",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Plotter for direction. Dividers for distance.",
          "The straightedge's distance scale is not accurate.",
          "Grommet on a meridian → outer scale. On a parallel → inner north/south scale.",
          "The outer scale counts up to the left.",
        ],
      },
      { kind: "question", questionId: "nq-c-040" },
      { kind: "question", questionId: "nq-c-043" },
      { kind: "question", questionId: "nq-c-045" },
    ],
    questionIds: ["nq-c-040", "nq-c-043", "nq-c-045", "nq-c-053"],
    memorize: ["The plotter's outer scale counts up to the LEFT."],
    sourceReferences: [C2],
    masteryThreshold: 0.75,
  },
  {
    id: "nl12-pulling-coordinates",
    unit: "n5",
    index: 12,
    title: "Pulling Coordinates",
    subtitle: "Reading a position off the sheet",
    estimatedMinutes: 8,
    enablingObjectives: [],
    conceptIds: ["nav-pulling-coordinates", "nav-speed-marks"],
    mapIcon: "crosshair",
    screens: [
      {
        kind: "hook",
        headline: "You can see the tower. What are its coordinates?",
        line: "Four steps, and a way of counting that saves you counting sixty tick marks.",
        diagram: { id: "nav-speed-marks" },
      },
      {
        kind: "method",
        headline: "Pulling a latitude",
        given: ["A point you can see on the chart"],
        find: ["Its latitude, to the nearest tenth of a minute"],
        steps: [
          "Position the plotter with the point just below the straightedge",
          "Align the grommet and the 90° mark along the same meridian — any meridian",
          "Slide down until the straightedge touches the point, then check the alignment again",
          "Mark where the straightedge crosses the meridian",
          "Find the nearest whole degree and count up, using the speed marks",
        ],
        watchFor: "The alignment drifts as you slide. Check it a second time before you mark.",
        tolerance: "±1 minute",
      },
      {
        kind: "model",
        headline: "The speed marks",
        line: "The graduation exists so you never have to count sixty of anything.",
        diagram: { id: "nav-speed-marks" },
        bullets: [
          "A mark every minute.",
          "Every five minutes, a longer mark that stays on the LEFT of the meridian.",
          "Every ten minutes, a longer mark still that CROSSES the meridian.",
          "Round to the nearest tenth of a minute.",
        ],
      },
      {
        kind: "chain",
        headline: "And longitude is the same four steps, rotated",
        nodes: [
          { label: "Rotate the plotter ninety degrees" },
          { label: "Align grommet and 90° along a PARALLEL" },
          { label: "Slide until the straightedge touches the point" },
          { label: "Count along the parallel", emphasis: true },
        ],
        footnote:
          "Latitude is counted up a meridian; longitude along a parallel. The line you count along is always at right angles to the thing you are measuring.",
      },
      {
        kind: "worked",
        headline: "Watch it done",
        line: "One point, both coordinates, at the pace you would work at.",
        problemId: "nq-chart-pull-1",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Align, slide, mark, count.",
          "Latitude against a meridian. Longitude against a parallel.",
          "Ten-minute marks cross the line; five-minute marks sit to its left.",
          "±1 minute.",
        ],
      },
      { kind: "question", questionId: "nq-c-046" },
      { kind: "question", questionId: "nq-c-047" },
      { kind: "question", questionId: "nq-chart-pull-2" },
    ],
    questionIds: ["nq-c-046", "nq-c-047", "nq-chart-pull-1", "nq-chart-pull-2"],
    memorize: ["Ten-minute marks cross the meridian. Five-minute marks stay left."],
    sourceReferences: [C2],
    masteryThreshold: 0.8,
  },
  {
    id: "nl13-measuring-direction",
    unit: "n5",
    index: 13,
    title: "Measuring Direction",
    subtitle: "Estimate, span, slide, read",
    estimatedMinutes: 8,
    enablingObjectives: [],
    conceptIds: ["nav-measuring-direction", "nav-north-south-scale"],
    mapIcon: "protractor",
    screens: [
      {
        kind: "hook",
        headline: "The scale will offer you two answers",
        line: "One of them is a hundred and eighty degrees wrong, and nothing on the instrument will tell you which.",
        diagram: { id: "nav-plotter", props: { highlight: "outer" } },
      },
      {
        kind: "method",
        headline: "Measuring a course",
        given: ["Two points on the chart"],
        find: ["The true course between them"],
        steps: [
          "Connect them with the straightedge, and draw a single arrow for the direction of travel",
          "ESTIMATE the general direction before touching the scale",
          "Span the dividers along the course line",
          "Lay the straightedge against the divider points",
          "Slide until the grommet sits on a meridian, ideally halfway along the course",
          "Read the outer scale, choosing the value nearest the estimate",
        ],
        estimateFirst:
          "A leg running north-west has to come out between 270° and 360°. That single sentence eliminates the reciprocal.",
        watchFor:
          "Bracket the meridian — read the numbers to its left and right — or you can be exactly ten degrees out with an answer that looks entirely reasonable.",
        tolerance: "±1°",
      },
      {
        kind: "model",
        headline: "When no meridian will fit under the grommet",
        line: "A course running nearly north–south leaves nowhere to put it.",
        diagram: { id: "nav-plotter", props: { highlight: "inner" } },
        bullets: [
          "Keep the straightedge on the course line, but put a PARALLEL under the grommet instead.",
          "Follow that parallel out to the inner north/south scale and read there.",
          "The estimate matters even more here, because the inner scale also offers two answers.",
        ],
      },
      {
        kind: "worked",
        headline: "Watch it done",
        line: "A full leg: estimate, measure, convert, then the distance.",
        problemId: "nq-chart-leg-1",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Estimate. Span. Slide. Read.",
          "Meridian under the grommet → outer scale.",
          "Parallel under the grommet → inner north/south scale.",
          "Bracket before you commit.",
        ],
      },
      { kind: "question", questionId: "nq-c-044" },
      { kind: "question", questionId: "nq-c-048" },
      { kind: "question", questionId: "nq-chart-leg-2" },
      { kind: "question", questionId: "nq-chart-plot-1" },
    ],
    questionIds: ["nq-c-044", "nq-c-048", "nq-chart-leg-1", "nq-chart-leg-2", "nq-chart-plot-1"],
    memorize: ["Estimate first, or you will read the reciprocal."],
    sourceReferences: [C2],
    masteryThreshold: 0.8,
  },
  {
    id: "nl14-measuring-distance",
    unit: "n5",
    index: 14,
    title: "Measuring Distance",
    subtitle: "Up a meridian, and never along a parallel",
    estimatedMinutes: 7,
    enablingObjectives: [],
    conceptIds: ["nav-measuring-distance", "nav-walking-dividers"],
    mapIcon: "dividers",
    screens: [
      {
        kind: "hook",
        headline: "One minute of latitude is one nautical mile",
        line: "Everywhere on the chart, at every latitude. That is the whole basis of chart distance.",
        diagram: { id: "nav-speed-marks" },
      },
      {
        kind: "method",
        headline: "Measuring a leg",
        given: ["Two points, connected by a course line"],
        find: ["The distance in nautical miles"],
        steps: [
          "Spread the dividers with a tip on each point",
          "Without changing the setting, carry the span to the nearest meridian",
          "Put one leg on the intersection of a meridian and a parallel",
          "Count the tick marks, using the five- and ten-minute speed marks",
        ],
        watchFor:
          "Never measure along a parallel. A parallel is a small circle, so its minutes are shorter than a mile — and shorter still the further from the equator you are.",
        tolerance: "±½ NM",
      },
      {
        kind: "method",
        headline: "When the leg is longer than the dividers",
        given: ["A leg the dividers cannot span"],
        find: ["The distance"],
        steps: [
          "Set the dividers to a fixed distance — 30 NM works well",
          "Put one tip on the departure point and rotate the other along the line",
          "Keep walking, counting in multiples: 30, 60, 90",
          "When you overshoot, close the dividers on the remainder and add it",
        ],
        estimateFirst: "Count the walks before you start. A leg that looks like four spans should not come out as two.",
        tolerance: "±½ NM",
      },
      {
        kind: "chain",
        headline: "Why the parallel is wrong",
        nodes: [
          { label: "A nautical mile is one minute of arc on a GREAT circle" },
          { label: "Meridians are great circles", trend: "same" },
          { label: "Parallels are not", trend: "down" },
          { label: "So a minute of longitude is short of a mile", emphasis: true },
        ],
        footnote:
          "The degrees printed along the longitude lines are degrees of LATITUDE. That is what you are counting when you carry the dividers to a meridian.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "1 minute of latitude = 1 NM.",
          "1 degree of latitude = 60 NM.",
          "Carry the span to a meridian.",
          "Walk the dividers in 30-mile steps, then close on the remainder.",
        ],
      },
      { kind: "question", questionId: "nq-c-041" },
      { kind: "question", questionId: "nq-c-042" },
      { kind: "question", questionId: "nq-c-049" },
      { kind: "question", questionId: "nq-chart-leg-3" },
    ],
    questionIds: ["nq-c-041", "nq-c-042", "nq-c-049", "nq-chart-leg-3", "nq-chart-leg-4"],
    memorize: ["Distance up a meridian. Never along a parallel."],
    sourceReferences: [C2],
    masteryThreshold: 0.8,
  },
  {
    id: "nl15-plotting-onto-the-chart",
    unit: "n5",
    index: 15,
    title: "Plotting onto the Chart",
    subtitle: "Coordinates in, and a course out from a point",
    estimatedMinutes: 7,
    enablingObjectives: [],
    conceptIds: ["nav-plotting-coordinates", "nav-plotting-direction"],
    mapIcon: "pencil",
    screens: [
      {
        kind: "hook",
        headline: "Pulling in reverse",
        line: "Same instrument, same alignments, opposite direction of travel.",
        diagram: { id: "nav-plotter", props: { highlight: "straightedge" } },
      },
      {
        kind: "method",
        headline: "Plotting a set of coordinates",
        given: ["A latitude and a longitude"],
        find: ["The point on the chart"],
        steps: [
          "Plotter horizontal, grommet and 90° mark on the same meridian",
          "Move it vertically until the straightedge rests on the latitude, and draw",
          "Rotate 90°, grommet and 90° mark on the same parallel",
          "Move horizontally to the longitude, and draw",
          "The intersection is the position",
        ],
        tolerance: "±1 minute",
      },
      {
        kind: "method",
        headline: "Plotting a direction from a point",
        given: ["A starting point", "A course to draw"],
        find: ["The line, and where it takes you"],
        steps: [
          "Estimate the direction so you know which half of the scale you want",
          "Hold a pencil on the point and slide the straightedge up against it",
          "Slide the grommet along the nearest meridian until the direction reads on the outer scale",
          "Draw, then measure the distance along it with the dividers",
        ],
        estimateFirst: "Estimating keeps you on the right scale. Without it the line goes out backwards.",
        watchFor:
          "If the course you were given is MAGNETIC, convert it to true before plotting. The chart is true.",
        tolerance: "±1° and ±½ NM",
      },
      {
        kind: "worked",
        headline: "Watch it done",
        line: "A magnetic course, converted, plotted, measured, and the coordinates pulled at the far end.",
        problemId: "nq-chart-plot-2",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Two lines, one intersection.",
          "Estimate before you place the plotter, every time.",
          "A magnetic course must become true before it goes on the chart.",
        ],
      },
      { kind: "question", questionId: "nq-c-053" },
      { kind: "question", questionId: "nq-chart-plot-2" },
      { kind: "question", questionId: "nq-chart-plot-3" },
    ],
    questionIds: ["nq-c-053", "nq-chart-plot-1", "nq-chart-plot-2", "nq-chart-plot-3"],
    memorize: ["The chart is true. Convert before you plot."],
    sourceReferences: [C2],
    masteryThreshold: 0.8,
  },
  {
    id: "nl16-tacan-fixes",
    unit: "n5",
    index: 16,
    title: "TACAN Position Fixing",
    subtitle: "The one conversion that runs backwards",
    estimatedMinutes: 8,
    enablingObjectives: [],
    conceptIds: ["nav-tacan-fix", "nav-needle-head-tail"],
    mapIcon: "radial",
    screens: [
      {
        kind: "hook",
        headline: "A radial and a distance is a position",
        line: "As long as you remember that the radial arrives in the wrong reference frame.",
        diagram: { id: "nav-tacan-fix", props: { stage: "magnetic" } },
      },
      {
        kind: "model",
        headline: "Reading the BDHI",
        line: "The #2 needle carries the TACAN. Both ends of it mean something.",
        diagram: { id: "nav-tacan-fix", props: { stage: "magnetic", radial: 135, variation: 7 } },
        bullets: [
          "The HEAD gives the magnetic bearing TO the station.",
          "The TAIL gives the radial you are on.",
          "They are reciprocals, and a problem that hands you one is testing whether you noticed which.",
          "The distance shown is slant range. For this course, treat it as ground range.",
        ],
      },
      {
        kind: "method",
        headline: "Plotting the fix",
        given: ["A radial and a DME", "The station's position", "The variation at the station"],
        find: ["Your position on the chart"],
        steps: [
          "If you were given a bearing TO the station, flip it to get the radial",
          "Find the variation from the nearest isogonic line to the navaid",
          "Convert the radial from magnetic to true — so easterly variation is ADDED",
          "Plot the true radial out from the station",
          "Measure the DME along it and circle the point",
        ],
        estimateFirst: "Which quadrant of the station should the fix land in? Check the plot against that.",
        watchFor:
          "This conversion is the reverse of the flight-planning one. Going magnetic → true, east adds. Getting it backwards puts you twice the variation off, in the wrong direction.",
        tolerance: "±1° and ±½ NM",
      },
      {
        kind: "worked",
        headline: "Watch it done",
        line: "Radial converted, plotted, measured, position pulled.",
        problemId: "nq-chart-fix-1",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Head = bearing TO. Tail = the radial you are on.",
          "Radial is magnetic. Chart is true. East ADDS.",
          "Use the isogonic line nearest the navaid.",
        ],
      },
      { kind: "question", questionId: "nq-c-051" },
      { kind: "question", questionId: "nq-c-052" },
      { kind: "question", questionId: "nq-chart-fix-2" },
      { kind: "question", questionId: "nq-chart-fix-3" },
    ],
    questionIds: ["nq-c-051", "nq-c-052", "nq-chart-fix-1", "nq-chart-fix-2", "nq-chart-fix-3"],
    memorize: ["Plotting a radial: magnetic to true, so east ADDS."],
    sourceReferences: [C2],
    masteryThreshold: 0.8,
  },

  /* ================= n6 — the CR-3 ================= */
  {
    id: "nl17-the-cr3",
    unit: "n6",
    index: 17,
    title: "Meeting the CR-3",
    subtitle: "Two wheels, three indexes, one floating decimal",
    estimatedMinutes: 7,
    enablingObjectives: [],
    conceptIds: ["nav-cr3", "nav-cr3-wheels", "nav-floating-decimal", "nav-tick-values", "nav-cursor"],
    mapIcon: "cr3",
    screens: [
      {
        kind: "hook",
        headline: "A disc of plastic that outperforms a calculator",
        line: "Not at arithmetic. At being reliable at altitude, and at costing nothing.",
        diagram: { id: "nav-cr3-indexes", props: { highlight: "none" } },
      },
      {
        kind: "model",
        headline: "Two wheels, both logarithmic",
        line: "And identical: line up the tens and the scales read the same.",
        diagram: { id: "nav-log-scale" },
        bullets: [
          "Outer, white, on the base: distance, and fuel in pounds.",
          "Inner, grey, rotating: time.",
          "Numerators go outside, denominators inside — set the fraction up as you would write it.",
        ],
      },
      {
        kind: "rule",
        headline: "The floating decimal",
        rule: "A printed number stands for any power of ten of itself. The 21 on the scale may be 0.21, 2.1, 21, 210 or 2100.",
        appliesWhen: ["Every value you set", "Every value you read"],
        watchFor:
          "Nothing on the instrument knows where the decimal goes. That is why the guide puts ESTIMATE at step one of every procedure — the estimate is not politeness, it is the missing digit.",
        authority: "NAVAVSCOLSCOM-SG-200, Information Sheet 6-3-2",
      },
      {
        kind: "model",
        headline: "A tick mark is not always worth the same",
        line: "The scale is logarithmic, so the graduation changes as you go round it.",
        diagram: { id: "nav-log-scale" },
        bullets: [
          "10 to 15: nine ticks between whole numbers, so each is worth one.",
          "15 to 30: four ticks, so each is worth two.",
          "30 to 60: one tick between whole numbers, worth five.",
          "The ±1% tolerance is defined against the 10-to-15 section, where the ticks are finest.",
        ],
      },
      {
        kind: "tool",
        headline: "Turn it",
        line: "Drag the grey wheel. Notice that setting one pair sets every equivalent pair at the same time — that is not a shortcut, it is what a slide rule is.",
        tool: "cr3calc",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Outer: distance and fuel. Inner: time.",
          "Numerator outside, denominator inside.",
          "10–15 → 1 per tick. 15–30 → 2. 30–60 → 5.",
          "The wheel gives digits. Your estimate gives the decimal point.",
        ],
      },
      { kind: "question", questionId: "nq-c-054" },
      { kind: "question", questionId: "nq-c-055" },
      { kind: "question", questionId: "nq-c-056" },
      { kind: "question", questionId: "nq-c-057" },
      { kind: "question", questionId: "nq-c-065" },
    ],
    questionIds: ["nq-c-054", "nq-c-055", "nq-c-056", "nq-c-057", "nq-c-065", "nq-c-064"],
    memorize: ["The wheel gives digits. The estimate gives the decimal point."],
    sourceReferences: [C3],
    masteryThreshold: 0.75,
  },
  {
    id: "nl18-the-three-indexes",
    unit: "n6",
    index: 18,
    title: "The Three Indexes",
    subtitle: "Which mark you set against, and why",
    estimatedMinutes: 6,
    enablingObjectives: [],
    conceptIds: ["nav-rate-index", "nav-high-speed-index", "nav-unit-index", "nav-hour-circle"],
    mapIcon: "index",
    screens: [
      {
        kind: "hook",
        headline: "The first decision in every problem",
        line: "Not what to set, but what to set it against.",
        diagram: { id: "nav-cr3-indexes", props: { highlight: "none" } },
      },
      {
        kind: "model",
        headline: "Rate index — the hour",
        line: "The triangle where 60 would be on the inner wheel.",
        diagram: { id: "nav-cr3-indexes", props: { highlight: "rate" } },
        bullets: [
          "60 minutes is one hour, and almost every rate in aviation is per hour.",
          "It marks 0.6, 6.0 or 60 MINUTES. Never 1.",
        ],
      },
      {
        kind: "model",
        headline: "High-speed index — the hour, in seconds",
        line: "The small SEC arrow at 36, because 3,600 seconds is also an hour.",
        diagram: { id: "nav-cr3-indexes", props: { highlight: "sec" } },
        bullets: [
          "Reach for it when the time is five minutes or less,",
          "or the distance is five miles or less,",
          "or the speed is 500 kt or more,",
          "or seconds appear in the estimate, the question or the answer.",
        ],
      },
      {
        kind: "model",
        headline: "Unit index — no time at all",
        line: "The mark at 10 on both wheels.",
        diagram: { id: "nav-cr3-indexes", props: { highlight: "unit" } },
        bullets: [
          "For any calculation that is a plain ratio: fuel conversion above all.",
          "Using the rate index on a gallons-to-pounds problem is a factor-of-six error.",
        ],
      },
      {
        kind: "model",
        headline: "The hour circle",
        line: "Under the minute scale, converting to hours and minutes with no arithmetic.",
        diagram: { id: "nav-log-scale" },
        bullets: [
          "150 on the time scale shows 2:30 directly beneath it.",
          "The small marks between hours are ten-minute steps.",
          "Read the time scale as SECONDS and the hour circle reads MINUTES — the ratio is the same.",
        ],
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Rate index at 60: one hour.",
          "SEC bug at 36: 3,600 seconds.",
          "Unit index at 10: no time in the problem.",
          "Four triggers for the seconds bug: ≤5 min, ≤5 NM, ≥500 kt, or seconds anywhere.",
        ],
      },
      { kind: "question", questionId: "nq-c-058" },
      { kind: "question", questionId: "nq-c-059" },
      { kind: "question", questionId: "nq-c-060" },
      { kind: "question", questionId: "nq-c-061" },
      { kind: "question", questionId: "nq-c-062" },
    ],
    questionIds: ["nq-c-058", "nq-c-059", "nq-c-060", "nq-c-061", "nq-c-062"],
    memorize: ["≤5 min, ≤5 NM, ≥500 kt, or seconds anywhere — use the SEC bug."],
    sourceReferences: [C3],
    masteryThreshold: 0.8,
  },
  {
    id: "nl19-time-speed-distance",
    unit: "n6",
    index: 19,
    title: "Time, Speed, Distance",
    subtitle: "One setup, three answers",
    estimatedMinutes: 8,
    enablingObjectives: [],
    conceptIds: ["nav-ratio", "nav-rule-of-60", "nav-rule-of-6"],
    mapIcon: "tsd",
    screens: [
      {
        kind: "hook",
        headline: "Set it up once. Read whichever one you need.",
        line: "The wheel does not care which of the three is missing.",
        diagram: { id: "nav-cr3-indexes", props: { highlight: "rate" } },
      },
      {
        kind: "method",
        headline: "The rate problem",
        given: ["Any two of speed, time and distance"],
        find: ["The third"],
        steps: [
          "Estimate, using the rule of 60",
          "Choose the index: rate for minutes, seconds bug for seconds",
          "Set the known pair — speed over the index, or distance over time",
          "Read the third value off the other scale",
          "Place the decimal from the estimate",
        ],
        estimateFirst:
          "Groundspeed ÷ 60 is nautical miles per minute. At 300 kt you cover 5 NM a minute, so 40 NM is about eight minutes.",
        tolerance: "±1 unit on the log scale, about ±1%",
      },
      {
        kind: "model",
        headline: "Two estimating rules, and they are the same rule",
        diagram: { id: "nav-log-scale" },
        bullets: [
          "Rule of 60: groundspeed ÷ 60 is NM per minute.",
          "Rule of 6: a tenth of groundspeed is the distance covered in six minutes.",
          "At 420 kt: 7 NM a minute, 42 NM in six.",
        ],
      },
      {
        kind: "worked",
        headline: "Watch it done",
        line: "A long leg on the rate index, worked from the estimate outwards.",
        problemId: "nq-tsd-t001",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "SPEED ÷ RATE INDEX = DISTANCE ÷ TIME.",
          "GS ÷ 60 = NM per minute.",
          "GS ÷ 10 = NM in six minutes.",
        ],
        formula: "\\frac{\\text{Speed}}{\\text{Rate index}} = \\frac{\\text{Distance}}{\\text{Time}}",
      },
      { kind: "question", questionId: "nq-c-063" },
      { kind: "question", questionId: "nq-tsd-t003" },
      { kind: "question", questionId: "nq-tsd-s001" },
      { kind: "question", questionId: "nq-tsd-d002" },
    ],
    questionIds: ["nq-c-063", "nq-tsd-t001", "nq-tsd-t003", "nq-tsd-s001", "nq-tsd-d002"],
    memorize: ["Speed over the rate index equals distance over time."],
    sourceReferences: [C3],
    masteryThreshold: 0.8,
  },
  {
    id: "nl20-short-and-fast",
    unit: "n6",
    index: 20,
    title: "Short and Fast",
    subtitle: "Working in seconds on the high-speed index",
    estimatedMinutes: 6,
    enablingObjectives: [],
    conceptIds: ["nav-high-speed-index", "nav-rule-of-60"],
    mapIcon: "stopwatch",
    screens: [
      {
        kind: "hook",
        headline: "Five miles at 420 knots is not a minutes problem",
        line: "It is forty-three seconds, and the rate index cannot read it accurately.",
        diagram: { id: "nav-cr3-indexes", props: { highlight: "sec" } },
      },
      {
        kind: "method",
        headline: "Working in seconds",
        given: ["A short time, a short distance, or a high speed"],
        find: ["The missing value, in seconds"],
        steps: [
          "Recognise the trigger: ≤5 minutes, ≤5 NM, ≥500 kt, or seconds in the problem",
          "Estimate in NM per minute first, then convert to seconds",
          "Set the speed over the SEC index at 36 rather than the rate index",
          "Read the time in seconds on the inner scale",
          "Use the innermost scale to convert to minutes and seconds if you need to",
        ],
        estimateFirst:
          "250 kt is about 4 NM a minute, so 5 NM is a little over a minute. That places the decimal and catches a factor-of-sixty error.",
        tolerance: "±1 unit on the log scale",
      },
      {
        kind: "chain",
        headline: "Why 36 and not 60",
        nodes: [
          { label: "The rate index means one hour" },
          { label: "One hour is 60 minutes — the mark at 60" },
          { label: "One hour is also 3,600 seconds", trend: "same" },
          { label: "Floating decimal: 3,600 prints as 36", emphasis: true },
        ],
        footnote:
          "It is the same index doing the same job in different units. Which is why the hour circle beneath also changes meaning, from hours to minutes.",
      },
      {
        kind: "worked",
        headline: "Watch it done",
        line: "Five miles at 250 knots, the guide's own worked example.",
        problemId: "nq-tsd-t006",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "SEC bug at 36. 3,600 seconds to the hour.",
          "≤5 min, ≤5 NM, ≥500 kt, or seconds anywhere in the problem.",
          "Time scale in seconds → hour circle in minutes.",
        ],
      },
      { kind: "question", questionId: "nq-tsd-t006" },
      { kind: "question", questionId: "nq-tsd-t007" },
      { kind: "question", questionId: "nq-tsd-s008" },
    ],
    questionIds: ["nq-tsd-t006", "nq-tsd-t007", "nq-tsd-s008", "nq-c-059", "nq-c-060"],
    memorize: ["Seconds bug at 36 — 3,600 seconds to the hour."],
    sourceReferences: [C3],
    masteryThreshold: 0.8,
  },
  {
    id: "nl21-fuel",
    unit: "n6",
    index: 21,
    title: "Fuel",
    subtitle: "The same rate problem, and one that is not",
    estimatedMinutes: 8,
    enablingObjectives: [],
    conceptIds: ["nav-fuel-consumption", "nav-fuel-conversion"],
    mapIcon: "fuel",
    screens: [
      {
        kind: "hook",
        headline: "Swap distance for pounds and nothing else changes",
        line: "Until you get to gallons, where the rate index is suddenly the wrong mark.",
        diagram: { id: "nav-cr3-indexes", props: { highlight: "rate" } },
      },
      {
        kind: "method",
        headline: "Fuel consumption",
        given: ["Any two of fuel flow, time and fuel quantity"],
        find: ["The third"],
        steps: [
          "Estimate — how many hours, at roughly what rate?",
          "Set the fuel flow over the rate index, or the pair you were given",
          "Read the third value",
        ],
        estimateFirst: "1,000 pph for a bit under two hours is a bit under 2,000 lb. That is enough to place the decimal.",
        tolerance: "±1 unit on the log scale",
      },
      {
        kind: "method",
        headline: "Fuel conversion",
        given: ["A fuel weight in pounds per gallon", "Either the gallons or the pounds"],
        find: ["The other"],
        steps: [
          "Estimate by rounding the fuel weight to a whole number",
          "Set the fuel weight over the UNIT INDEX at 10 — there is no time in this problem",
          "Read the answer off the other scale",
          "Check: there must be more pounds than gallons",
        ],
        watchFor:
          "The 10 on the inner wheel represents one gallon. Reaching for the rate index here is the classic slip, and it is out by a factor of six.",
        tolerance: "±1 unit on the log scale",
      },
      {
        kind: "worked",
        headline: "Watch it done",
        line: "Gallons to pounds, off the unit index, with the sanity check at the end.",
        problemId: "nq-fuelconv-001",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "FUEL FLOW ÷ RATE INDEX = TOTAL POUNDS ÷ TIME.",
          "WEIGHT OF 1 GAL ÷ 1.0 = TOTAL POUNDS ÷ TOTAL GALLONS.",
          "Conversions use the unit index. No time, no rate index.",
          "Always more pounds than gallons.",
        ],
        formula: "\\frac{\\text{Fuel weight}}{1\\text{ gal}} = \\frac{\\text{Total lb}}{\\text{Total gal}}",
      },
      { kind: "question", questionId: "nq-fuel-001" },
      { kind: "question", questionId: "nq-fuel-006" },
      { kind: "question", questionId: "nq-fuelconv-003" },
      { kind: "question", questionId: "nq-c-061" },
    ],
    questionIds: ["nq-fuel-001", "nq-fuel-006", "nq-fuelconv-001", "nq-fuelconv-003", "nq-c-061"],
    memorize: ["No time in the problem → unit index."],
    sourceReferences: [C3],
    masteryThreshold: 0.8,
  },

  /* ================= n7 — altitude and airspeed ================= */
  {
    id: "nl22-altitude",
    unit: "n7",
    index: 22,
    title: "Five Altitudes",
    subtitle: "And which one the airspeed problem wants",
    estimatedMinutes: 8,
    enablingObjectives: [],
    conceptIds: [
      "nav-standard-day",
      "nav-altitude-types",
      "nav-instrument-error",
      "nav-altimeter-errors",
      "nav-temperature-error",
    ],
    mapIcon: "altimeter",
    screens: [
      {
        kind: "hook",
        headline: "The altimeter is a barometer with a scale in feet",
        line: "Which means it is measuring pressure and telling you about height, and those are not the same thing.",
        diagram: { id: "nav-altitude-ladder", props: { highlight: "none" } },
      },
      {
        kind: "model",
        headline: "The standard day",
        line: "29.92 inches of mercury and +15 °C at mean sea level.",
        diagram: { id: "nav-altitude-ladder", props: { highlight: "pressure" } },
        bullets: [
          "Standard lapse rate: 2 °C and 1 inHg per 1,000 feet of altitude.",
          "On a standard day, calibrated altitude and true altitude are the same.",
          "They rarely are, because inversions and pressure systems exist.",
        ],
      },
      {
        kind: "model",
        headline: "Five altitudes, five references",
        diagram: { id: "nav-altitude-ladder", props: { highlight: "true" } },
        bullets: [
          "Indicated: what the altimeter reads on the local setting.",
          "Calibrated: indicated, corrected for instrument error.",
          "Pressure: calibrated, corrected to 29.92. This is what TAS needs.",
          "True: actual height above mean sea level — what chart terrain is measured against.",
          "Absolute: height above the surface, AGL.",
        ],
      },
      {
        kind: "rule",
        headline: "Instrument error cannot be corrected",
        rule: "Instrument error is the difference between known field elevation and indicated altitude with the current setting dialled in. It is noted, not removed.",
        appliesWhen: ["Before every departure"],
        watchFor: "If total altimeter error exceeds 75 feet, the aircraft is unsafe for IFR flight.",
        authority: "NAVAVSCOLSCOM-SG-200, Information Sheet 6-4-2",
      },
      {
        kind: "chain",
        headline: "Flying into falling pressure",
        nodes: [
          { label: "Pressure at the surface falls" },
          { label: "The whole column of air aloft is lowered", trend: "down" },
          { label: "You follow a constant pressure surface down", trend: "down" },
          { label: "The altimeter still reads high", emphasis: true },
        ],
        footnote:
          "High to low, look out below. Low to high, plenty of sky. And 0.10 inHg is worth 100 feet — which is why you get a setting from the destination tower before landing.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "29.92 and +15 °C at MSL.",
          "2 °C and 1 inHg per 1,000 ft.",
          "Pressure altitude is the reference for TAS.",
          "High to low, look out below.",
          "11 °C off standard → 4% altimeter error.",
        ],
      },
      { kind: "question", questionId: "nq-c-066" },
      { kind: "question", questionId: "nq-c-067" },
      { kind: "question", questionId: "nq-c-076" },
      { kind: "question", questionId: "nq-c-077" },
      { kind: "question", questionId: "nq-c-078" },
    ],
    questionIds: ["nq-c-066", "nq-c-067", "nq-c-076", "nq-c-077", "nq-c-078", "nq-c-068"],
    memorize: ["High to low, look out below. Low to high, plenty of sky."],
    sourceReferences: [C4],
    masteryThreshold: 0.75,
  },
  {
    id: "nl23-airspeeds",
    unit: "n7",
    index: 23,
    title: "Four Airspeeds",
    subtitle: "IAS, CAS, TAS, GS — and the corrections between them",
    estimatedMinutes: 6,
    enablingObjectives: [],
    conceptIds: ["nav-ias", "nav-cas", "nav-tas", "nav-groundspeed", "nav-density-effect"],
    mapIcon: "airspeed",
    screens: [
      {
        kind: "hook",
        headline: "Four numbers, three corrections",
        line: "And only the last correction has anything to do with the wind.",
        diagram: { id: "nav-airspeed-chain", props: { stage: 4 } },
      },
      {
        kind: "model",
        headline: "From the dial outwards",
        diagram: { id: "nav-airspeed-chain", props: { stage: 2 } },
        bullets: [
          "Indicated: read straight off the airspeed indicator.",
          "Calibrated: indicated corrected for instrument and installation error, from the calibration card.",
          "True: calibrated corrected for air density — the speed through the air mass.",
          "Ground: true corrected for the head or tail component of the wind.",
        ],
      },
      {
        kind: "chain",
        headline: "Why altitude raises true airspeed",
        nodes: [
          { label: "Climb at a constant indicated airspeed" },
          { label: "Air density falls", trend: "down" },
          { label: "The same pitot pressure needs more real speed", trend: "up" },
          { label: "TAS rises", trend: "up", emphasis: true },
        ],
        footnote:
          "Which is the whole reason the CR-3 has a TAS window: the number on the dial stops being the number you are travelling at as soon as you leave sea level.",
      },
      {
        kind: "compare",
        headline: "Two things wind does not affect",
        columns: ["True airspeed", "Ground speed"],
        rows: [
          { label: "Measured against", a: "The air mass", b: "The ground" },
          { label: "Affected by wind", a: "No", b: "Yes" },
          { label: "Found from", a: "CAS + pressure altitude + temperature", b: "TAS ± the head/tail component" },
          { label: "Used for", a: "Setting up the wind triangle", b: "Time en route and fuel" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "IAS → instrument error → CAS → density → TAS → wind → GS.",
          "TAS is speed through the air mass. Wind does not touch it.",
          "Climb at a fixed IAS and TAS rises.",
        ],
      },
      { kind: "question", questionId: "nq-c-070" },
      { kind: "question", questionId: "nq-c-071" },
      { kind: "question", questionId: "nq-c-072" },
      { kind: "question", questionId: "nq-c-075" },
    ],
    questionIds: ["nq-c-070", "nq-c-071", "nq-c-072", "nq-c-075", "nq-c-073"],
    memorize: ["IAS, CAS, TAS, GS — instrument error, density, wind."],
    sourceReferences: [C4],
    masteryThreshold: 0.75,
  },
  {
    id: "nl24-tas-and-mach",
    unit: "n7",
    index: 24,
    title: "Solving for TAS and Mach",
    subtitle: "Pressure altitude first, then the window",
    estimatedMinutes: 9,
    enablingObjectives: [],
    conceptIds: ["nav-pressure-altitude", "nav-tas-procedure", "nav-mach", "nav-shock-wave"],
    mapIcon: "mach",
    screens: [
      {
        kind: "hook",
        headline: "Three inputs, two outputs, one window",
        line: "And the whole thing falls over if the pressure altitude is wrong.",
        diagram: { id: "nav-airspeed-chain", props: { stage: 3 } },
      },
      {
        kind: "method",
        headline: "Pressure altitude, first, every time",
        given: ["An indicated or calibrated altitude", "The altimeter setting"],
        find: ["Pressure altitude"],
        steps: [
          "Correct indicated for instrument error to get calibrated altitude",
          "Find the difference between the setting and 29.92",
          "Turn it into feet at 1,000 feet per inch",
          "Apply LAGS: setting Less than 29.92 → Add. Greater → Subtract.",
        ],
        estimateFirst: "The correction is a thousand feet per inch. A setting a half inch off is worth five hundred feet, not five thousand.",
        watchFor:
          "In flight you can read pressure altitude straight off the altimeter — but only with 29.92 in the Kollsman window and no instrument error.",
        tolerance: "exact",
      },
      {
        kind: "method",
        headline: "True airspeed",
        given: ["Calibrated airspeed", "Pressure altitude", "Outside air temperature"],
        find: ["True airspeed"],
        steps: [
          "Set the CAS over the pressure altitude in the window",
          "Go to the large window at twelve o'clock",
          "Put the hairline exactly where the temperature curve crosses the Mach spiral",
          "Follow the hairline down to the TAS scale and read",
        ],
        estimateFirst: "Up high and cold, TAS will beat CAS considerably. Low and cold, it may not beat it at all.",
        watchFor: "Those two scales increase in OPPOSITE directions — 10,000 sits to the right of 15,000.",
        tolerance: "±2 kt",
      },
      {
        kind: "model",
        headline: "Mach comes free",
        line: "From the same setting, with no temperature input at all.",
        diagram: { id: "nav-airspeed-chain", props: { stage: 3 } },
        bullets: [
          "Mach is the ratio of true airspeed to the local speed of sound.",
          "Read it at the Mach index in the same window.",
          "At a constant Mach number the corresponding TAS is temperature dependent — but the Mach reading itself is not.",
          "It matters because pressure waves travel at the speed of sound; catch them and they pile into a shock wave.",
        ],
      },
      {
        kind: "worked",
        headline: "Watch it done",
        line: "Setting, altitude, temperature, TAS, Mach — one problem, all the way through.",
        problemId: "nq-tas-001",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "LAGS: Less, Add. Greater, Subtract.",
          "TAS needs CAS, OAT and PRESSURE altitude.",
          "Mach needs no temperature.",
          "±2 kt on TAS. ±0.01 on Mach.",
        ],
        mnemonic: "LAGS — Less Add, Greater Subtract",
      },
      { kind: "question", questionId: "nq-c-069" },
      { kind: "question", questionId: "nq-c-073" },
      { kind: "question", questionId: "nq-c-074" },
      { kind: "question", questionId: "nq-tas-002" },
    ],
    questionIds: ["nq-c-069", "nq-c-073", "nq-c-074", "nq-tas-001", "nq-tas-002", "nq-c-079"],
    memorize: ["LAGS. And TAS wants pressure altitude, not true altitude."],
    sourceReferences: [C4],
    masteryThreshold: 0.8,
  },
];
