import type { Lesson, SourceReference } from "@/lib/types";

/**
 * Units 1 to 4: what navigation is, the earth on paper, direction, and time.
 *
 * These are the four units where Navigation looks most like the other courses,
 * because they are mostly vocabulary and geometry. The doing starts in unit 5.
 * Even here, though, every lesson ends on something the student produces
 * rather than recognises — a conversion, a sign, a quarter named.
 */

const TG = (chapter: string): SourceReference => ({
  document: "Navigation Trainee Guide",
  chapter,
});

const C1 = TG("Introduction to Air Navigation");
const C2 = TG("Chart Projections, Plotting and Global Timekeeping");

export const LESSONS_A: Lesson[] = [
  /* ================= n1 ================= */
  {
    id: "nl01-what-navigation-is",
    unit: "n1",
    index: 1,
    title: "What Navigation Is",
    subtitle: "Three types, and why two of them are back-ups",
    estimatedMinutes: 6,
    enablingObjectives: [],
    conceptIds: ["nav-definition", "nav-dead-reckoning", "nav-types", "nav-visual", "nav-electronic"],
    mapIcon: "compass",
    screens: [
      {
        kind: "hook",
        headline: "Where am I, and where is the nose pointing?",
        line: "Every instrument, chart and wheel in this course exists to answer those two questions.",
        diagram: { id: "nav-dr-components", props: { highlight: "none" } },
      },
      {
        kind: "model",
        headline: "One definition, and it is worth memorising",
        line: "Air navigation is determining geographic position and maintaining the desired direction of an aircraft relative to the surface of the earth.",
        diagram: { id: "nav-dr-components", props: { highlight: "position" } },
        bullets: [
          "Position and direction. Everything else serves those two.",
          "Navigation is both the history of the flight path and the prediction of it.",
        ],
      },
      {
        kind: "compare",
        headline: "Three types, not equal partners",
        line: "Dead reckoning is the method. The other two support it.",
        columns: ["Dead reckoning", "Visual and electronic"],
        rows: [
          { label: "Status", a: "The basis for all air navigation", b: "Back-up techniques" },
          { label: "Needs", a: "A known starting point and the four components", b: "Visibility, or a working receiver" },
          { label: "Fails when", a: "The plot is not kept", b: "Cloud, night, or a station goes down" },
          { label: "Without it", a: "Nothing else has a reference", b: "You still have a plot to fly" },
        ],
      },
      {
        kind: "chain",
        headline: "Why visual is not a method on its own",
        nodes: [
          { label: "No DR plot" },
          { label: "No expectation of what is below", trend: "down" },
          { label: "Ground references misidentified", trend: "down" },
          { label: "Lost", emphasis: true },
        ],
        footnote:
          "The guide's own words: without DR, the aviator is likely to misidentify ground references and become lost. A river confirms a position you already expected; it does not supply one.",
      },
      {
        kind: "model",
        headline: "Electronic navigation, in three families",
        line: "Grouped by where the signal comes from.",
        diagram: { id: "nav-dr-components", props: { highlight: "direction" } },
        bullets: [
          "Receive from a ground station — VOR, TACAN, ADF, VORTAC, VOR/DME.",
          "Transmit your own — radar, Doppler.",
          "Self-contained, initialised by the crew — INS. GPS receives from satellites.",
          "The INS is a high-speed DR computer: it does what you do, faster and more accurately.",
        ],
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Three types: dead reckoning, visual, electronic.",
          "Visual and electronic are aids. Neither relieves you of the plot.",
          "Inertial is a category of electronic navigation, not a fourth type.",
        ],
      },
      { kind: "question", questionId: "nq-c-001" },
      { kind: "question", questionId: "nq-c-002" },
      { kind: "question", questionId: "nq-c-014" },
      { kind: "question", questionId: "nq-c-015" },
    ],
    questionIds: ["nq-c-001", "nq-c-002", "nq-c-014", "nq-c-015", "nq-c-013"],
    memorize: ["Dead reckoning, visual, electronic — and only the first is a method."],
    sourceReferences: [C1],
    masteryThreshold: 0.75,
  },
  {
    id: "nl02-the-four-components",
    unit: "n1",
    index: 2,
    title: "The Four Components",
    subtitle: "Position, direction, time, speed",
    estimatedMinutes: 6,
    enablingObjectives: [],
    conceptIds: ["nav-dr-components", "nav-latitude-longitude", "nav-elapsed-time"],
    mapIcon: "grid",
    screens: [
      {
        kind: "hook",
        headline: "Know any three, and the fourth is not a guess",
        line: "That single fact is the engine of the whole course.",
        diagram: { id: "nav-dr-components" },
      },
      {
        kind: "model",
        headline: "The four, in the order the guide lists them",
        diagram: { id: "nav-dr-components", props: { highlight: "speed" } },
        bullets: [
          "Position — a set of coordinates defining where you are above the surface.",
          "Direction — an angular measurement from a reference.",
          "Time — of day, or elapsed.",
          "Speed — distance travelled with respect to time, in knots.",
          "Speed × time gives distance. Any three give the fourth.",
        ],
      },
      {
        kind: "model",
        headline: "Position: latitude and longitude",
        line: "Angular distances, so they are measured in degrees and minutes.",
        diagram: { id: "nav-great-circles", props: { highlight: "parallels" } },
        bullets: [
          "Latitude: 0 to 90, north or south of the equator. Lines of latitude are parallels.",
          "Longitude: 0 to 180, east or west of the prime meridian. Lines of longitude are meridians.",
          "Sixty minutes in a degree — not the other way round.",
          "Read latitude first, and write longitude with three digits: 30° 22'N, 087° 19'W.",
        ],
      },
      {
        kind: "rule",
        headline: "Writing time",
        rule: "Times of day are four digits. Elapsed times take a plus sign.",
        appliesWhen: [
          "ETD and ETA are times of day: 0815, 1400",
          "ETE is elapsed: 2+30, or 09+15+20 in six-digit form",
          "For short legs, elapsed time is minutes and seconds",
        ],
        watchFor:
          "0230 and 2+30 are different things. The plus sign is the only thing distinguishing an elapsed time from a clock time, which is why the course insists on it.",
        authority: "NAVAVSCOLSCOM-SG-200, Information Sheet 6-1-2",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Position, direction, time, speed.",
          "Speed = Distance ÷ Time.",
          "60 minutes in a degree.",
          "Latitude first. Longitude in three digits.",
        ],
        formula: "\\text{Speed} = \\frac{\\text{Distance}}{\\text{Time}}",
      },
      { kind: "question", questionId: "nq-c-003" },
      { kind: "question", questionId: "nq-c-009" },
      { kind: "question", questionId: "nq-c-010" },
      { kind: "question", questionId: "nq-c-011" },
    ],
    questionIds: ["nq-c-003", "nq-c-009", "nq-c-010", "nq-c-011", "nq-c-004"],
    memorize: ["Position, direction, time, speed — three known gives the fourth."],
    sourceReferences: [C1],
    masteryThreshold: 0.75,
  },
  {
    id: "nl03-the-instruments",
    unit: "n1",
    index: 3,
    title: "The Instruments",
    subtitle: "Three primary, two secondary, one TACAN",
    estimatedMinutes: 6,
    enablingObjectives: [],
    conceptIds: [
      "nav-primary-instruments",
      "nav-secondary-instruments",
      "nav-bdhi",
      "nav-standby-compass",
      "nav-tacan-station",
    ],
    mapIcon: "gauge",
    screens: [
      {
        kind: "hook",
        headline: "One instrument for each thing you can measure",
        line: "Three of the four DR components are read directly off the panel. The fourth has to be worked out.",
        diagram: { id: "nav-dr-components", props: { highlight: "time" } },
      },
      {
        kind: "compare",
        headline: "Primary and secondary",
        line: "The secondary pair do not measure a component. They correct one.",
        columns: ["Primary", "Secondary"],
        rows: [
          { label: "Instruments", a: "Compass, clock, airspeed indicator", b: "Altimeter, OAT gauge" },
          { label: "Give you", a: "Direction and position, time, speed", b: "Altitude and temperature" },
          { label: "Used for", a: "The DR plot itself", b: "Air density, which sets true airspeed" },
        ],
      },
      {
        kind: "model",
        headline: "Two compass systems, always",
        line: "A primary and a back-up, in every military aircraft.",
        diagram: { id: "nav-course-heading-track", props: { show: "heading" } },
        bullets: [
          "Primary: the remote gyro vertical compass card — the BDHI or EHSI.",
          "Modern aircraft drive it from a ring laser gyro INS, with no magnetic input at all.",
          "Back-up: the stand-by compass, a direct-reading needle in fluid.",
          "The wet compass is unstable in manoeuvre, but it is independent of the electrical system.",
        ],
      },
      {
        kind: "model",
        headline: "TACAN, in one paragraph",
        line: "A ground station that hands you a distance and a bearing.",
        diagram: { id: "nav-tacan-fix", props: { stage: "magnetic" } },
        bullets: [
          "962 to 1213 MHz, channels 1 to 126, sub-designated X or Y.",
          "360 radials, calibrated to MAGNETIC north, radiating like spokes.",
          "The station's position is known, so a radial and a DME fix you over the earth.",
        ],
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Primary: compass, clock, airspeed indicator.",
          "Secondary: altimeter and OAT.",
          "Primary direction instrument is the remote gyro vertical compass card.",
          "The stand-by compass is fluid-damped, not gyro-stabilised.",
        ],
      },
      { kind: "question", questionId: "nq-c-005" },
      { kind: "question", questionId: "nq-c-006" },
      { kind: "question", questionId: "nq-c-007" },
      { kind: "question", questionId: "nq-c-008" },
      { kind: "question", questionId: "nq-c-012" },
    ],
    questionIds: ["nq-c-005", "nq-c-006", "nq-c-007", "nq-c-008", "nq-c-012"],
    memorize: ["Compass, clock, airspeed. Then altimeter and OAT."],
    sourceReferences: [C1],
    masteryThreshold: 0.75,
  },

  /* ================= n2 ================= */
  {
    id: "nl04-earth-on-paper",
    unit: "n2",
    index: 4,
    title: "The Earth on Paper",
    subtitle: "Why every chart lies, and how much",
    estimatedMinutes: 6,
    enablingObjectives: [],
    conceptIds: ["nav-undevelopable", "nav-great-circle", "nav-small-circle"],
    mapIcon: "globe",
    screens: [
      {
        kind: "hook",
        headline: "Peel an orange and try to flatten the peel",
        line: "It tears. That is the entire problem of chart projection in one image.",
        diagram: { id: "nav-conic-projection", props: { cone: false } },
      },
      {
        kind: "model",
        headline: "Developable and undevelopable",
        line: "A sphere cannot be flattened without stretching or tearing. A cone or a cylinder can.",
        diagram: { id: "nav-conic-projection", props: { cone: true } },
        bullets: [
          "Some distortion is always present. The job is to minimise it and know where it is.",
          "The desirable properties: a constant scale, and course lines that are great circles.",
        ],
      },
      {
        kind: "model",
        headline: "Great circles",
        line: "A circle whose plane passes through the earth's centre, dividing it into two equal halves.",
        diagram: { id: "nav-great-circles", props: { highlight: "meridians" } },
        bullets: [
          "It is the shortest distance between two points — so it saves time and fuel.",
          "They are not restricted to horizontal or vertical. Any plane through the centre gives one.",
          "All meridians are great circles, because each one bisects the earth.",
          "Of the parallels, only the equator qualifies.",
        ],
      },
      {
        kind: "chain",
        headline: "Why it matters that a meridian is a great circle",
        nodes: [
          { label: "A meridian is a great circle" },
          { label: "One minute of arc on a great circle is one nautical mile" },
          { label: "So one minute of LATITUDE is one mile", trend: "same" },
          { label: "Measure every distance up a meridian", emphasis: true },
        ],
        footnote:
          "A parallel is a small circle, so its minutes are short of a mile — and shorter the further north you go. Measuring along one is the most common distance error in the course.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "A sphere is undevelopable; a cone is not.",
          "Great circle: the plane passes through the earth's centre.",
          "All meridians. Of the parallels, only the equator.",
          "Shortest distance, so time and fuel.",
        ],
      },
      { kind: "question", questionId: "nq-c-016" },
      { kind: "question", questionId: "nq-c-017" },
      { kind: "question", questionId: "nq-c-018" },
      { kind: "question", questionId: "nq-c-023" },
    ],
    questionIds: ["nq-c-016", "nq-c-017", "nq-c-018", "nq-c-023", "nq-c-042"],
    memorize: ["All meridians are great circles. Of the parallels, only the equator."],
    sourceReferences: [C2],
    masteryThreshold: 0.75,
  },
  {
    id: "nl05-lambert",
    unit: "n2",
    index: 5,
    title: "The Lambert Conformal",
    subtitle: "The chart you will actually use",
    estimatedMinutes: 6,
    enablingObjectives: [],
    conceptIds: ["nav-lambert", "nav-onc-tpc", "nav-mercator"],
    mapIcon: "map",
    screens: [
      {
        kind: "hook",
        headline: "A cone, laid over the earth, cutting at two parallels",
        line: "Everything useful about this chart follows from that one construction.",
        diagram: { id: "nav-conic-projection" },
      },
      {
        kind: "model",
        headline: "Four characteristics, and one consequence",
        diagram: { id: "nav-conic-projection", props: { cone: false } },
        bullets: [
          "Parallels: equally spaced concentric circles — so they appear CURVED.",
          "Meridians: straight lines converging at the poles.",
          "Scale: constant.",
          "Great circles: plot as straight lines.",
          "And the consequence: the meridians point at TRUE north, so a line you draw is a true course.",
        ],
      },
      {
        kind: "rule",
        headline: "Everything on the chart is true. Everything in the cockpit is magnetic.",
        rule: "Lines drawn on a Lambert chart are TRUE directions, because the meridians are oriented to the geographic north pole.",
        appliesWhen: [
          "You measure a course off the chart — it is true",
          "You read a heading in the cockpit — it is magnetic",
          "You plot a TACAN radial — it arrives magnetic and has to be converted",
        ],
        watchFor:
          "This is why variation is a step in almost every plotting problem, and why forgetting it produces an answer that is off by a small, plausible amount rather than an obviously silly one.",
        authority: "NAVAVSCOLSCOM-SG-200, Information Sheet 6-2-2",
      },
      {
        kind: "compare",
        headline: "The two charts you will meet",
        columns: ["ONC", "TPC"],
        rows: [
          { label: "Scale", a: "1:1,000,000", b: "1:500,000" },
          { label: "Detail", a: "Multicolour hydrographic and cultural", b: "Increased ground detail" },
          { label: "Used for", a: "Long-range planning", b: "Route and checkpoint determination" },
          { label: "You will use", a: "At your follow-on squadron", b: "Here" },
        ],
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Parallels curve. Meridians are straight and converge.",
          "Great circles plot as straight lines.",
          "TPC 1:500,000 · ONC 1:1,000,000.",
          "Chart lines are TRUE.",
        ],
      },
      { kind: "question", questionId: "nq-c-019" },
      { kind: "question", questionId: "nq-c-020" },
      { kind: "question", questionId: "nq-c-021" },
      { kind: "question", questionId: "nq-c-022" },
      { kind: "question", questionId: "nq-c-024" },
    ],
    questionIds: ["nq-c-019", "nq-c-020", "nq-c-021", "nq-c-022", "nq-c-024"],
    memorize: ["Parallels curve, meridians converge, great circles are straight, and it is all TRUE."],
    sourceReferences: [C2],
    masteryThreshold: 0.75,
  },

  /* ================= n3 ================= */
  {
    id: "nl06-course-heading-track",
    unit: "n3",
    index: 6,
    title: "Course, Heading, Track",
    subtitle: "Three words that are not synonyms",
    estimatedMinutes: 6,
    enablingObjectives: [],
    conceptIds: ["nav-direction", "nav-course", "nav-heading", "nav-track"],
    mapIcon: "route",
    screens: [
      {
        kind: "hook",
        headline: "Intended, pointed, achieved",
        line: "Three lines from the same point, and the exam swaps them constantly.",
        diagram: { id: "nav-course-heading-track", props: { show: "all" } },
      },
      {
        kind: "model",
        headline: "Course — what you meant",
        line: "The intended flight path. Draw a line from departure to destination on a Lambert chart and you have plotted the true course.",
        diagram: { id: "nav-course-heading-track", props: { show: "course" } },
      },
      {
        kind: "model",
        headline: "Heading — where the nose points",
        line: "The angular distance of the longitudinal axis from a reference. It differs from course to compensate for crosswind.",
        diagram: { id: "nav-course-heading-track", props: { show: "heading" } },
      },
      {
        kind: "model",
        headline: "Track — what actually happened",
        line: "A line from the departure point to the current fix. It only equals the course if the forecast was right.",
        diagram: { id: "nav-course-heading-track", props: { show: "track" } },
      },
      {
        kind: "rule",
        headline: "Directions run 001 to 360",
        rule: "Direction is stated in whole numbers from 001° to a maximum of 360°.",
        appliesWhen: ["Any course, heading, track, radial or bearing"],
        watchFor: "There is no 000. Due north is written 360.",
        authority: "NAVAVSCOLSCOM-SG-200, Information Sheet 6-1-2",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Course = intended.",
          "Heading = pointed.",
          "Track = achieved.",
          "001 to 360. Never 000.",
        ],
      },
      { kind: "question", questionId: "nq-c-025" },
      { kind: "question", questionId: "nq-c-026" },
      { kind: "question", questionId: "nq-c-031" },
      { kind: "question", questionId: "nq-c-091" },
    ],
    questionIds: ["nq-c-025", "nq-c-026", "nq-c-031", "nq-c-091", "nq-c-033"],
    memorize: ["Course intended, heading pointed, track achieved."],
    sourceReferences: [C2],
    masteryThreshold: 0.75,
  },
  {
    id: "nl07-variation",
    unit: "n3",
    index: 7,
    title: "Variation",
    subtitle: "Two norths, and the angle between them",
    estimatedMinutes: 5,
    enablingObjectives: [],
    conceptIds: ["nav-true-vs-magnetic-north", "nav-variation", "nav-isogonic"],
    mapIcon: "compass-rose",
    screens: [
      {
        kind: "hook",
        headline: "The compass does not point at the top of the earth",
        line: "It points at northern Canada, and the difference is worth a step in every plotting problem.",
        diagram: { id: "nav-variation", props: { east: 6 } },
      },
      {
        kind: "model",
        headline: "Variation is a local quantity",
        line: "The angular difference between true north and magnetic north FROM A GIVEN POSITION.",
        diagram: { id: "nav-variation", props: { east: 10 } },
        bullets: [
          "Expressed in degrees east or west.",
          "Easterly when magnetic north lies east of true north from where you are.",
          "It changes as you move across the chart, which is why it is a local value and not a constant.",
        ],
      },
      {
        kind: "model",
        headline: "Isogonic lines do the looking-up for you",
        line: "A line connecting points of equal variation.",
        diagram: { id: "nav-variation", props: { east: 4 } },
        bullets: [
          "On TPC and ONC charts they appear as dashed blue lines with the value in degrees.",
          "Use the line nearest the point you care about — for a TACAN fix, nearest the navaid.",
        ],
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "Variation: the angle from true north to magnetic north at your position.",
          "Isogonic lines join points of EQUAL VARIATION.",
          "Dashed blue on the chart.",
        ],
      },
      { kind: "question", questionId: "nq-c-027" },
      { kind: "question", questionId: "nq-c-028" },
      { kind: "question", questionId: "nq-c-032" },
    ],
    questionIds: ["nq-c-027", "nq-c-028", "nq-c-032", "nq-c-029"],
    memorize: ["Isogonic lines join equal variation. Dashed blue."],
    sourceReferences: [C2],
    masteryThreshold: 0.75,
  },
  {
    id: "nl08-applying-variation",
    unit: "n3",
    index: 8,
    title: "Applying Variation",
    subtitle: "East is least, and the trap in reversing it",
    estimatedMinutes: 7,
    enablingObjectives: [],
    conceptIds: ["nav-variation-conversion"],
    mapIcon: "swap",
    screens: [
      {
        kind: "hook",
        headline: "Two words, one arithmetic sign, and a lot of lost marks",
        line: "The rule is easy. Knowing which direction you are travelling in is not.",
        diagram: { id: "nav-variation", props: { east: 7 } },
      },
      {
        kind: "method",
        headline: "True to magnetic",
        given: ["A true course measured off the chart", "The variation from the nearest isogonic line"],
        find: ["The magnetic course to fly"],
        steps: [
          "Read the variation and note whether it is east or west",
          "East is least: subtract it",
          "West is best: add it",
          "Normalise to 001–360",
        ],
        estimateFirst: "The correction is small. If the answer moved by more than the variation, the sign is wrong.",
        watchFor:
          "This is the direction you use for flight planning. Plotting a TACAN radial runs the OTHER way, and the formula reverses with it.",
        tolerance: "±1°",
      },
      {
        kind: "compare",
        headline: "Which way am I going?",
        line: "The same variation, applied in opposite directions.",
        columns: ["Chart → cockpit", "Cockpit → chart"],
        rows: [
          { label: "You have", a: "A true course off the chart", b: "A magnetic radial off the BDHI" },
          { label: "You want", a: "A magnetic course to fly", b: "A true radial to plot" },
          { label: "Easterly variation", a: "Subtract", b: "Add" },
          { label: "Example, 7°E", a: "142 true → 135 magnetic", b: "135 magnetic → 142 true" },
        ],
      },
      {
        kind: "worked",
        headline: "Watch it done",
        line: "The reversal, worked through slowly, because it is the one people get wrong.",
        problemId: "nq-c-030",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "MC = TC − East. MC = TC + West.",
          "East is least, and west is best.",
          "Plotting a radial: magnetic to true, so east ADDS.",
        ],
        formula: "MC = TC - E \\qquad MC = TC + W",
        mnemonic: "East is least, and west is best",
      },
      { kind: "question", questionId: "nq-c-029" },
      { kind: "question", questionId: "nq-c-030" },
      { kind: "question", questionId: "nq-c-050" },
    ],
    questionIds: ["nq-c-029", "nq-c-030", "nq-c-050", "nq-c-020"],
    memorize: ["East is least, west is best — going true to magnetic."],
    sourceReferences: [C2],
    masteryThreshold: 0.8,
  },

  /* ================= n4 ================= */
  {
    id: "nl09-the-zone-system",
    unit: "n4",
    index: 9,
    title: "The Zone System",
    subtitle: "Twenty-four zones and one reference clock",
    estimatedMinutes: 5,
    enablingObjectives: [],
    conceptIds: ["nav-gmt", "nav-time-zones", "nav-zone-description"],
    mapIcon: "clock",
    screens: [
      {
        kind: "hook",
        headline: "You cannot brief a mission in local time",
        line: "Not when the aircraft crosses three of them before lunch.",
        diagram: { id: "nav-time-zones", props: { zd: 0 } },
      },
      {
        kind: "model",
        headline: "Where the fifteen degrees comes from",
        line: "The earth turns 360° in 24 hours.",
        diagram: { id: "nav-time-zones", props: { zd: -6 } },
        bullets: [
          "360 ÷ 24 = 15° an hour, so 24 zones each 15° of longitude wide.",
          "Each is centred on a meridian that is a multiple of 15°.",
          "The zone on the prime meridian is Z — Zulu — and its time is GMT.",
        ],
      },
      {
        kind: "rule",
        headline: "Look the zone description up. Do not derive it.",
        rule: "The zone description is the difference in hours from local time to GMT, found in the IFR en route supplement after the airfield's coordinates.",
        appliesWhen: [
          "Any time conversion for a real airfield",
          "The TPC covering the area is a secondary source",
        ],
        watchFor:
          "Dividing longitude by 15 looks right and is not: zone boundaries follow geographic and political lines, cities are never split, some countries use one zone across three, and daylight saving moves the value. Sherman Field is −6, except in daylight saving when it is −5.",
        authority: "NAVAVSCOLSCOM-SG-200, Information Sheet 6-2-2",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "15° of longitude to the hour.",
          "24 zones, each centred on a multiple of 15°.",
          "Zulu is the reference. Weather and flight plans are filed in it.",
        ],
      },
      { kind: "question", questionId: "nq-c-034" },
      { kind: "question", questionId: "nq-c-035" },
      { kind: "question", questionId: "nq-c-036" },
    ],
    questionIds: ["nq-c-034", "nq-c-035", "nq-c-036", "nq-zulu-001"],
    memorize: ["360 ÷ 24 = 15° an hour."],
    sourceReferences: [C2],
    masteryThreshold: 0.75,
  },
  {
    id: "nl10-flying-in-zulu",
    unit: "n4",
    index: 10,
    title: "Flying in Zulu",
    subtitle: "Convert out, add the time, convert back",
    estimatedMinutes: 8,
    enablingObjectives: [],
    conceptIds: ["nav-zulu-conversion", "nav-fly-in-zulu"],
    mapIcon: "clock-arrow",
    screens: [
      {
        kind: "hook",
        headline: "The sign is the whole problem",
        line: "The arithmetic is trivial. Subtracting a negative is where people lose the mark.",
        diagram: { id: "nav-time-zones", props: { zd: -8 } },
      },
      {
        kind: "method",
        headline: "Converting a single time",
        given: ["A time", "Whether it is local or Zulu", "The zone description"],
        find: ["The other one"],
        steps: [
          "Write the formula down before substituting anything",
          "GMT (Z) = LMT − (ZD)",
          "LMT = GMT + (ZD)",
          "Keep the brackets — they are what makes the sign behave",
        ],
        estimateFirst:
          "West of Greenwich, Zulu is later than local. East of it, Zulu is earlier. Check the answer against that before writing it down.",
        watchFor: "A zone description of −6 means GMT is six hours AHEAD, because subtracting a negative adds.",
        tolerance: "exact to the minute",
      },
      {
        kind: "tool",
        headline: "The zone wheel",
        line: "Set the zone description and every local hour lines up against its Zulu hour at once. Turning it the wrong way is the same mistake as getting the sign wrong — which is the point.",
        tool: "timezone",
      },
      {
        kind: "method",
        headline: "Flying a leg across zones",
        given: ["A departure time and its zone", "A time en route", "The destination's zone"],
        find: ["The local time of arrival"],
        steps: [
          "Convert the departure to Zulu",
          "Add the time en route — in Zulu",
          "Convert the arrival to the destination's local time",
          "Note any day rollover, which happens in the middle step",
        ],
        estimateFirst: "Flying east, the local clock gains. Flying west, it loses.",
        watchFor:
          "Never add the flight time to a local clock and then convert. The middle step exists so the addition never crosses a zone boundary.",
      },
      {
        kind: "anchor",
        headline: "Know cold",
        statements: [
          "GMT (Z) = LMT − (ZD).",
          "LMT = GMT + (ZD).",
          "Subtracting a negative adds.",
          "Convert out, fly in Zulu, convert back.",
        ],
        formula: "GMT = LMT - (ZD) \\qquad LMT = GMT + (ZD)",
      },
      { kind: "question", questionId: "nq-c-039" },
      { kind: "question", questionId: "nq-zulu-004" },
      { kind: "question", questionId: "nq-c-037" },
      { kind: "question", questionId: "nq-c-038" },
    ],
    questionIds: ["nq-c-039", "nq-zulu-004", "nq-c-037", "nq-c-038", "nq-zulu-005"],
    memorize: ["GMT = LMT − (ZD). LMT = GMT + (ZD)."],
    sourceReferences: [C2],
    masteryThreshold: 0.8,
  },
];
